### ISSUE TITLE
[Bug]: Stuck at "Adjusting world_size=16 rank=0 distributed_init_method=tcp://127.0.0.1:42051 for DP"

### ISSUE THREAD

**Issue by qinghuanguayu** [vllm-project/vllm-ascend#1255]
### Your current environment

<details>
<summary>The output of `python collect_env.py`</summary>

```text
Collecting environment information...
PyTorch version: 2.5.1
Is debug build: False

OS: Ubuntu 22.04.5 LTS (aarch64)
GCC version: (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
Clang version: Could not collect
CMake version: version 4.0.0
Libc version: glibc-2.35

Python version: 3.10.17 (main, Apr 30 2025, 16:00:31) [GCC 11.4.0] (64-bit runtime)
Python platform: Linux-5.15.0-25-generic-aarch64-with-glibc2.35

CPU:
Architecture:                    aarch64
CPU op-mode(s):                  64-bit
Byte Order:                      Little Endian
CPU(s):                          192
On-line CPU(s) list:             0-191
Vendor ID:                       HiSilicon
Model name:                      Kunpeng-920
Model:                           0
Thread(s) per core:              1
Core(s) per cluster:             48
Socket(s):                       -
Cluster(s):                      4
Stepping:                        0x1
BogoMIPS:                        200.00
Flags:                           fp asimd evtstrm aes pmull sha1 sha2 crc32 atomics fphp asimdhp cpuid asimdrdm jscvt fcma dcpop asimddp asimdfhm ssbs
L1d cache:                       12 MiB (192 instances)
L1i cache:                       12 MiB (192 instances)
L2 cache:                        96 MiB (192 instances)
L3 cache:                        192 MiB (8 instances)
NUMA node(s):                    8
NUMA node0 CPU(s):               0-23
NUMA node1 CPU(s):               24-47
NUMA node2 CPU(s):               48-71
NUMA node3 CPU(s):               72-95
NUMA node4 CPU(s):               96-119
NUMA node5 CPU(s):               120-143
NUMA node6 CPU(s):               144-167
NUMA node7 CPU(s):               168-191
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl
Vulnerability Spectre v1:        Mitigation; __user pointer sanitization
Vulnerability Spectre v2:        Not affected
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected

Versions of relevant libraries:
[pip3] numpy==1.26.4
[pip3] pyzmq==26.4.0
[pip3] torch==2.5.1
[pip3] torch-npu==2.5.1
[pip3] torchvision==0.20.1
[pip3] transformers==4.51.3
[conda] Could not collect
vLLM Version: 0.8.5.post1
vLLM Ascend Version: 0.8.5rc1

ENV Variables:
ATB_OPSRUNNER_KERNEL_CACHE_TILING_SIZE=10240
ATB_OPSRUNNER_KERNEL_CACHE_LOCAL_COUNT=1
ATB_STREAM_SYNC_EVERY_RUNNER_ENABLE=0
ASCEND_RT_VISIBLE_DEVICES=0,1,2,3,4,5,6,7
ATB_OPSRUNNER_SETUP_CACHE_ENABLE=1
ATB_WORKSPACE_MEM_ALLOC_GLOBAL=0
ATB_DEVICE_TILING_BUFFER_BLOCK_NUM=32
ATB_STREAM_SYNC_EVERY_KERNEL_ENABLE=0
ATB_OPSRUNNER_KERNEL_CACHE_GLOABL_COUNT=5
PYTORCH_NPU_ALLOC_CONF=max_split_size_mb:256
ATB_HOME_PATH=/usr/local/Ascend/nnal/atb/latest/atb/cxx_abi_1
ASCEND_TOOLKIT_HOME=/usr/local/Ascend/ascend-toolkit/latest
ASCEND_PROCESS_LOG_PATH=/workspace/ascend_process_log/
ATB_COMPARE_TILING_EVERY_KERNEL=0
ASCEND_OPP_PATH=/usr/local/Ascend/ascend-toolkit/latest/opp
LD_LIBRARY_PATH=/usr/local/Ascend/nnal/atb/latest/atb/cxx_abi_1/lib:/usr/local/Ascend/nnal/atb/latest/atb/cxx_abi_1/examples:/usr/local/Ascend/nnal/atb/latest/atb/cxx_abi_1/tests/atbopstest:/usr/local/Ascend/ascend-toolkit/latest/tools/aml/lib64:/usr/local/Ascend/ascend-toolkit/latest/tools/aml/lib64/plugin:/usr/local/Ascend/ascend-toolkit/latest/lib64:/usr/local/Ascend/ascend-toolkit/latest/lib64/plugin/opskernel:/usr/local/Ascend/ascend-toolkit/latest/lib64/plugin/nnengine:/usr/local/Ascend/ascend-toolkit/latest/opp/built-in/op_impl/ai_core/tbe/op_tiling:/usr/local/Ascend/driver/lib64/common/:/usr/local/Ascend/driver/lib64/driver/:
ASCEND_AICPU_PATH=/usr/local/Ascend/ascend-toolkit/latest
ATB_OPSRUNNER_KERNEL_CACHE_TYPE=3
VLLM_HOST_IP=192.168.0.225
ATB_RUNNER_POOL_SIZE=64
ATB_STREAM_SYNC_EVERY_OPERATION_ENABLE=0
ASCEND_HOME_PATH=/usr/local/Ascend/ascend-toolkit/latest
ATB_MATMUL_SHUFFLE_K_ENABLE=1
ATB_LAUNCH_KERNEL_WITH_TILING=1
ATB_WORKSPACE_MEM_ALLOC_ALG_TYPE=1
ATB_HOST_TILING_BUFFER_BLOCK_NUM=128
ATB_SHARE_MEMORY_NAME_SUFFIX=
TORCH_DEVICE_BACKEND_AUTOLOAD=1
PYTORCH_NVML_BASED_CUDA_CHECK=1
TORCHINDUCTOR_COMPILE_THREADS=1


NPU:
+------------------------------------------------------------------------------------------------+
| npu-smi 24.1.rc2                 Version: 24.1.rc2                                             |
+---------------------------+---------------+----------------------------------------------------+
| NPU   Name                | Health        | Power(W)    Temp(C)           Hugepages-Usage(page)|
| Chip                      | Bus-Id        | AICore(%)   Memory-Usage(MB)  HBM-Usage(MB)        |
+===========================+===============+====================================================+
| 0     910B2               | OK            | 91.8        39                0    / 0             |
| 0                         | 0000:C1:00.0  | 0           0    / 0          3415 / 65536         |
+===========================+===============+====================================================+
| 1     910B2               | OK            | 96.1        40                0    / 0             |
| 0                         | 0000:01:00.0  | 0           0    / 0          3353 / 65536         |
+===========================+===============+====================================================+
| 2     910B2               | OK            | 93.4        39                0    / 0             |
| 0                         | 0000:C2:00.0  | 0           0    / 0          3351 / 65536         |
+===========================+===============+====================================================+
| 3     910B2               | OK            | 96.6        41                0    / 0             |
| 0                         | 0000:02:00.0  | 0           0    / 0          3351 / 65536         |
+===========================+===============+====================================================+
| 4     910B2               | OK            | 93.5        39                0    / 0             |
| 0                         | 0000:81:00.0  | 0           0    / 0          3352 / 65536         |
+===========================+===============+====================================================+
| 5     910B2               | OK            | 95.1        38                0    / 0             |
| 0                         | 0000:41:00.0  | 0           0    / 0          3351 / 65536         |
+===========================+===============+====================================================+
| 6     910B2               | OK            | 98.2        38                0    / 0             |
| 0                         | 0000:82:00.0  | 0           0    / 0          3351 / 65536         |
+===========================+===============+====================================================+
| 7     910B2               | OK            | 97.6        39                0    / 0             |
| 0                         | 0000:42:00.0  | 0           0    / 0          3352 / 65536         |
+===========================+===============+====================================================+
+---------------------------+---------------+----------------------------------------------------+
| NPU     Chip              | Process id    | Process name             | Process memory(MB)      |
+===========================+===============+====================================================+
| 0       0                 | 30288         | python                   | 114                     |
+===========================+===============+====================================================+
| No running processes found in NPU 1                                                            |
+===========================+===============+====================================================+
| No running processes found in NPU 2                                                            |
+===========================+===============+====================================================+
| No running processes found in NPU 3                                                            |
+===========================+===============+====================================================+
| No running processes found in NPU 4                                                            |
+===========================+===============+====================================================+
| No running processes found in NPU 5                                                            |
+===========================+===============+====================================================+
| No running processes found in NPU 6                                                            |
+===========================+===============+====================================================+
| No running processes found in NPU 7                                                            |
+===========================+===============+====================================================+

CANN:
package_name=Ascend-cann-toolkit
version=8.1.RC1
innerversion=V100R001C21SPC001B238
compatible_version=[V100R001C15],[V100R001C18],[V100R001C19],[V100R001C20],[V100R001C21]
arch=aarch64
os=linux
path=/usr/local/Ascend/ascend-toolkit/8.1.RC1/aarch64-linux
```

</details>

### 🐛 Describe the bug

We use the following command to start vllm-ascend-0.8.5rc1 to deploy deepseek-r1-w8a8

```
python -m vllm.entrypoints.openai.api_server  \
--model ${VLLM_MODEL_PATH} \
--served-model-name ${VLLM_SERVED_NAME} \
--trust-remote-code \
--enforce-eager \
--max-model-len 4096 \
--gpu-memory-utilization "0.95" \
--distributed-executor-backend "ray" \
--quantization "ascend" \
--disable-log-requests \
--disable-log-stats \
--disable-frontend-multiprocessing \
--data-parallel-size 16 \
--enable-expert-parallel \
--port ${VLLM_SERVED_PORT}
```

However, there is a problem as follows, the log shows that the deployment is stuck at this step, how to solve it!

```
INFO 06-17 06:41:46 [parallel_state.py:883] Adjusting world_size=16 rank=0 distributed_init_method=tcp://127.0.0.1:42051 for DP
```

**Comment by MengqingCao** [comment]
Could you try with the latest main? I think this has been resolved by https://github.com/vllm-project/vllm-ascend/pull/1235 and https://github.com/vllm-project/vllm-ascend/pull/884

**Comment by xie-qiang** [comment]
Have you solved this problem? I still have this problem even when installing with the latest branch.

**Comment by YanWuHao** [comment]
I meet the same problem, can any one help us?

**Comment by hacine** [comment]
I meet the same problem, can any one help us?

**Comment by fangtaosong** [comment]
I meet the same problem, can any one help us?

**Comment by AJF-cmd** [comment]
This issue has been resolved in the latest version. Please use the latest release or rc version (https://github.com/vllm-project/vllm-ascend/releases). If the issue persists, feel free to submit a new issue.
