### ISSUE TITLE
[Bug]: vllm-ascend 0.10.1rc1官方镜像部署量化模型Qwen3-30B-A3B-W8A8出现call aclnnGroupedMatmulV5 failed,error code is 161002

### ISSUE THREAD

**Issue by wing2791** [vllm-project/vllm-ascend#2807]
### Your current environment

<details>
<summary>The output of `python collect_env.py`</summary>

```text
即为vllm-ascend 0.10.rc1官方docker镜像的环境（m.daocloud.io/quay.io/ascend/vllm-ascend:v0.10.1rc1）

```

</details>

### 🐛 Describe the bug

vllm-ascend
版本：m.daocloud.io/quay.io/ascend/vllm-ascend:v0.10.1rc1
启动：
docker run --rm \
--name vllm-ascend-0.10.1rc1 \
--device /dev/davinci4 \
--device /dev/davinci5 \
--device /dev/davinci6 \
--device /dev/davinci7 \
--device /dev/davinci_manager 
--device /dev/devmm_svm \
--device /dev/hisi_hdc \
--platform linux/arm64 \
-v /usr/local/dcmi:/usr/local/dcmi \
-v /usr/local/bin/npu-smi:/usr/local/bin/npu-smi \
-v /usr/local/Ascend/driver/lib64/:/usr/local/Ascend/driver/lib64/ \
-v /usr/local/Ascend/driver/version.info:/usr/local/Ascend/driver/version.info \
-v /etc/ascend_install.info:/etc/ascend_install.info \
-v /root/.cache:/root/.cache \
-v /te:/te\
-v /home3/bitbrain/xczhu9/vllm:/workspace/vllm \
-p 8000:8000\
-it vllm-ascend:v0.10.1rc1 bash

Qwen3-30B-A3B-W8A8
官方文档推荐：https://www.modelscope.cn/models/vllm-ascend/Qwen3-30B-A3B-W8A8
自己量化：br_release_MindStudio_8.1RC2_TR5_20260624（报同样的错）

vllm拉起命令：
vllm serve /te/xczhu9/open models/0wen3-30B-A3B-W8A8-3
-tensor-parallel-size 4
-enable expert parallel
-served-model-name qwen30-3
-quantization ascend

bug上下文

(EngineCore_0 pid=7114)ERROR 09-08 03:22:04 [core.py:700]return self.quant_method.apply(
(EngineCore_0 pid=7114)ERR0R09-0803:22:04[core.py:700]AAAAAAAAAAAAAAAAAAAAAAAA
(EngineCore_0 pid=7114) ERROR 09-08 03:22:04 [core.py:700]File "/vllm-workspace/vllm-ascend/vllm_ascend/quantizati
amic.py", line 390, in apply
(EngineCore_0 pid=7114）EERROR 09-08 03:22:04 [core.py:700]return unified_fused_experts(
(EngineCore_0 pid=7114)ERR0R09-0803:22:04[core.py:700]AAAAAAAAAAAAAAAAAAAAAA
(EngineCore_0 pid=7114）EERROR 09-08 03:22:04 [core.py:700]File"/vllm-workspace/vllm-ascend/vllm_ascend/ops/common
py", line 99, in fused_experts
(EngineCore_0 pid=7114)ERROR 09-08 03:22:04 [core.Py:700]gate_up_output = torch_npu.npu_grouped_matmul(
(EngineCore_0 pid=7114)ERROR 09-08 03:22:04[core.py:700]AAAAAAAAAAAAAAAAAAAAAAAAAAAAA
(EngineCore_0 pid=7114)ERROR 09-08 03:22:044 [core.py:700]File "/usr/local/python3.11.13/lib/python3.11/site-packa
ops.py", line 1158, incall
(EngineCore_0 pid=7114)ERROR 09-08 03:22:04 [core.Py:700]return self._op(*args, **(kwargs or {))
(EngineCore_0 pid=7114)ERROR 09-08 03:22:044 [core.py:700]AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
(EngineCore_0 pid=7114)ERROR 09-08 03:22:04 [core.py:700] RuntimeError: npu_grouped_matmul:build/CMakeFiles/torch_np
ler_depend.ts:380 NPU function error: call aclnnGroupedMatmulV5 failed,error code is 161002
(EngineCore_0 pid=7114） ERROR 09-08 03:22:04 [core.Py:700] [ERROR] 2025-09-08-03:22:04 (PID:7114, Device:0,RankID:-1
PTA call acl api failed.
(EngineCore_0 pid=7114) ERROR 09-08 03:22:04 [core.py:700] EZ1001: [PID: 7114] 2025-09-08-03:22:04.869.394 Tensor ten
d dtype is DT_BFLOAT16 but found DT_INT32.
(EngineCore_0 pid=7114)ERROR 09-08 03:22:044 [core.py:700]TraceBack (most recent call last):
(EngineCore_0 pid=7114)ERROR 09-08 03:22:04[core.py:700]GMM:y dtype does not match with required dtype[DT
(EngineCore_0 pid=7114)ERROR 09-08 03:22:04 [core.Py:700]
(EngineCore_0 pid=7114)Process EngineCore_0:
(EngineCore_0 pid=7114)Traceback (most recent call last):
(EngineCore_0 pid=7114)File "/usr/local/python3.11.13/lib/python3.11/multiprocessing/process.py", line 314, in _bo
(EngineCore_0 pid=7114)self.run()
(EngineCore_0 pid=7114)File "/usr/local/python3.11.13/lib/python3.11/multiprocessing/process.py", line 108, in run
(EngineCore_0 pid=7114)
(EngineCore_0 pid=7114)File "/vilm-workspace/vlim/vllm/v1/engine/core.py", line 704, in run_engine_coreself._target(*self._args, **self._kwargs)
(EngineCore_0 pid=7114)raise e
(EngineCore_0 pid=7114)File "/vllm-workspace/vllm/vllm/v1/engine/core.py", line 691, in run_engine_core

**Comment by LoganJane** [comment]
@wing2791 This issue has been resolved in the latest version. Please use the latest release or rc version (https://github.com/vllm-project/vllm-ascend/releases). If the issue persists, feel free to submit a new issue.
