### ISSUE TITLE
[Bug]: 0.11.0rc0 OOM! Failed run Qwen/Qwen3-Next-80B-A3B-Instruct with RuntimeError: Worker with error 'NPU out of memory.

### ISSUE THREAD

**Issue by lishengting** [vllm-project/vllm-ascend#3308]
### Your current environment

<details>
<summary>The output of `python collect_env.py`</summary>

```Collecting environment information...
PyTorch version: 2.7.1+cpu
Is debug build: False

OS: Ubuntu 22.04.5 LTS (aarch64)
GCC version: (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
Clang version: Could not collect
CMake version: version 4.1.0
Libc version: glibc-2.35

Python version: 3.11.13 (main, Jul 26 2025, 07:27:32) [GCC 11.4.0] (64-bit runtime)
Python platform: Linux-4.19.90-89.11.v2401.ky10.aarch64-aarch64-with-glibc2.35

CPU:
Architecture:                       aarch64
CPU op-mode(s):                     64-bit
Byte Order:                         Little Endian
CPU(s):                             192
On-line CPU(s) list:                0-191
Vendor ID:                          HiSilicon
Model name:                         Kunpeng-920
Model:                              0
Thread(s) per core:                 1
Core(s) per cluster:                48
Socket(s):                          -
Cluster(s):                         4
Stepping:                           0x1
Frequency boost:                    disabled
CPU max MHz:                        2600.0000
CPU min MHz:                        200.0000
BogoMIPS:                           200.00
Flags:                              fp asimd evtstrm aes pmull sha1 sha2 crc32 atomics fphp asimdhp cpuid asimdrdm jscvt fcma dcpop asimddp asimdfhm ssbs
L1d cache:                          12 MiB (192 instances)
L1i cache:                          12 MiB (192 instances)
L2 cache:                           96 MiB (192 instances)
L3 cache:                           192 MiB (8 instances)
NUMA node(s):                       8
NUMA node0 CPU(s):                  0-23
NUMA node1 CPU(s):                  24-47
NUMA node2 CPU(s):                  48-71
NUMA node3 CPU(s):                  72-95
NUMA node4 CPU(s):                  96-119
NUMA node5 CPU(s):                  120-143
NUMA node6 CPU(s):                  144-167
NUMA node7 CPU(s):                  168-191
Vulnerability Gather data sampling: Not affected
Vulnerability Itlb multihit:        Not affected
Vulnerability L1tf:                 Not affected
Vulnerability Mds:                  Not affected
Vulnerability Meltdown:             Not affected
Vulnerability Mmio stale data:      Not affected
Vulnerability Retbleed:             Not affected
Vulnerability Spec store bypass:    Mitigation; Speculative Store Bypass disabled via prctl
Vulnerability Spectre v1:           Mitigation; __user pointer sanitization
Vulnerability Spectre v2:           Not affected
Vulnerability Srbds:                Not affected
Vulnerability Tsx async abort:      Not affected

Versions of relevant libraries:
[pip3] numpy==1.26.4
[pip3] pyzmq==27.1.0
[pip3] torch==2.7.1+cpu
[pip3] torch_npu==2.7.1.dev20250724
[pip3] torchvision==0.22.1
[pip3] transformers==4.56.2
[conda] Could not collect
vLLM Version: 0.11.0rc3
vLLM Ascend Version: 0.11.0rc0

ENV Variables:
ATB_OPSRUNNER_KERNEL_CACHE_LOCAL_COUNT=1
ATB_STREAM_SYNC_EVERY_RUNNER_ENABLE=0
ATB_OPSRUNNER_SETUP_CACHE_ENABLE=1
ATB_WORKSPACE_MEM_ALLOC_GLOBAL=0
ATB_DEVICE_TILING_BUFFER_BLOCK_NUM=32
ATB_STREAM_SYNC_EVERY_KERNEL_ENABLE=0
ATB_OPSRUNNER_KERNEL_CACHE_GLOABL_COUNT=5
VLLM_USE_MODELSCOPE=True
ATB_HOME_PATH=/usr/local/Ascend/nnal/atb/latest/atb/cxx_abi_1
ASCEND_TOOLKIT_HOME=/usr/local/Ascend/ascend-toolkit/latest
ATB_COMPARE_TILING_EVERY_KERNEL=0
ASCEND_OPP_PATH=/usr/local/Ascend/ascend-toolkit/latest/opp
LD_LIBRARY_PATH=/usr/local/Ascend/nnal/atb/latest/atb/cxx_abi_1/lib:/usr/local/Ascend/nnal/atb/latest/atb/cxx_abi_1/examples:/usr/local/Ascend/nnal/atb/latest/atb/cxx_abi_1/tests/atbopstest:/usr/local/Ascend/ascend-toolkit/latest/tools/aml/lib64:/usr/local/Ascend/ascend-toolkit/latest/tools/aml/lib64/plugin:/usr/local/Ascend/ascend-toolkit/latest/lib64:/usr/local/Ascend/ascend-toolkit/latest/lib64/plugin/opskernel:/usr/local/Ascend/ascend-toolkit/latest/lib64/plugin/nnengine:/usr/local/Ascend/ascend-toolkit/latest/opp/built-in/op_impl/ai_core/tbe/op_tiling/lib/linux/aarch64:/usr/local/Ascend/nnal/atb/latest/atb/cxx_abi_0/lib:/usr/local/Ascend/nnal/atb/latest/atb/cxx_abi_0/examples:/usr/local/Ascend/nnal/atb/latest/atb/cxx_abi_0/tests/atbopstest:/usr/local/Ascend/ascend-toolkit/latest/tools/aml/lib64:/usr/local/Ascend/ascend-toolkit/latest/tools/aml/lib64/plugin:/usr/local/Ascend/ascend-toolkit/latest/lib64:/usr/local/Ascend/ascend-toolkit/latest/lib64/plugin/opskernel:/usr/local/Ascend/ascend-toolkit/latest/lib64/plugin/nnengine:/usr/local/Ascend/ascend-toolkit/latest/opp/built-in/op_impl/ai_core/tbe/op_tiling:/usr/local/Ascend/driver/lib64/common/:/usr/local/Ascend/driver/lib64/driver/:
ASCEND_AICPU_PATH=/usr/local/Ascend/ascend-toolkit/latest
ATB_STREAM_SYNC_EVERY_OPERATION_ENABLE=0
ASCEND_HOME_PATH=/usr/local/Ascend/ascend-toolkit/latest
ATB_MATMUL_SHUFFLE_K_ENABLE=1
ATB_WORKSPACE_MEM_ALLOC_ALG_TYPE=1
ATB_HOST_TILING_BUFFER_BLOCK_NUM=128
ATB_SHARE_MEMORY_NAME_SUFFIX=
TORCH_DEVICE_BACKEND_AUTOLOAD=1
PYTORCH_NVML_BASED_CUDA_CHECK=1
TORCHINDUCTOR_COMPILE_THREADS=1


NPU:
+------------------------------------------------------------------------------------------------+
| npu-smi 24.1.rc1                 Version: 24.1.rc1                                             |
+---------------------------+---------------+----------------------------------------------------+
| NPU   Name                | Health        | Power(W)    Temp(C)           Hugepages-Usage(page)|
| Chip                      | Bus-Id        | AICore(%)   Memory-Usage(MB)  HBM-Usage(MB)        |
+===========================+===============+====================================================+
| 0     910B4               | OK            | 89.3        49                0    / 0             |
| 0                         | 0000:C1:00.0  | 0           0    / 0          2793 / 32768         |
+===========================+===============+====================================================+
| 1     910B4               | OK            | 84.2        48                0    / 0             |
| 0                         | 0000:C2:00.0  | 0           0    / 0          2787 / 32768         |
+===========================+===============+====================================================+
| 2     910B4               | OK            | 83.6        50                0    / 0             |
| 0                         | 0000:81:00.0  | 0           0    / 0          2787 / 32768         |
+===========================+===============+====================================================+
| 3     910B4               | OK            | 89.8        47                0    / 0             |
| 0                         | 0000:82:00.0  | 0           0    / 0          2787 / 32768         |
+===========================+===============+====================================================+
| 4     910B4               | OK            | 93.6        53                0    / 0             |
| 0                         | 0000:01:00.0  | 0           0    / 0          2788 / 32768         |
+===========================+===============+====================================================+
| 5     910B4               | OK            | 89.8        50                0    / 0             |
| 0                         | 0000:02:00.0  | 0           0    / 0          2787 / 32768         |
+===========================+===============+====================================================+
| 6     910B4               | OK            | 89.2        52                0    / 0             |
| 0                         | 0000:41:00.0  | 0           0    / 0          2787 / 32768         |
+===========================+===============+====================================================+
| 7     910B4               | OK            | 84.0        51                0    / 0             |
| 0                         | 0000:42:00.0  | 0           0    / 0          2788 / 32768         |
+===========================+===============+====================================================+
+---------------------------+---------------+----------------------------------------------------+
| NPU     Chip              | Process id    | Process name             | Process memory(MB)      |
+===========================+===============+====================================================+
| No running processes found in NPU 0                                                            |
+===========================+===============+====================================================+
| No running processes found in NPU 1                                                            |
+===========================+===============+====================================================+
| No running processes found in NPU 2                                                            |
+===========================+===============+====================================================+
| No running processes found in NPU 3                                                            |
+===========================+===============+====================================================+
| No running processes found in NPU 4                                                            |
+===========================+===============+====================================================+
| No running processes found in NPU 5                                                            |
+===========================+===============+====================================================+
| No running processes found in NPU 6                                                            |
+===========================+===============+====================================================+
| No running processes found in NPU 7                                                            |
+===========================+===============+====================================================+

CANN:
package_name=Ascend-cann-toolkit
version=8.2.RC1
innerversion=V100R001C22SPC001B231
compatible_version=[V100R001C15],[V100R001C18],[V100R001C19],[V100R001C20],[V100R001C21],[V100R001C23]
arch=aarch64
os=linux
path=/usr/local/Ascend/ascend-toolkit/8.2.RC1/aarch64-linux

```

</details>

### 🐛 Describe the bug

The memory of NPU is more than enough but still failed.
CMD: vllm serve Qwen/Qwen3-Next-80B-A3B-Instruct --tensor-parallel-size 8 --max-model-len 1024 --gpu-memory-utilization 0.95 --enforce-eager

```...
[1;36m(Worker_TP0 pid=22152)[0;0m INFO 10-02 05:47:21 [default_loader.py:267] Loading weights took 34.94 seconds
[1;36m(Worker_TP7 pid=22159)[0;0m Downloading Model from https://www.modelscope.cn to directory: /root/.cache/modelscope/hub/models/Qwen/Qwen3-Next-80B-A3B-Instruct
[1;36m(Worker_TP7 pid=22159)[0;0m INFO 10-02 05:47:22 [default_loader.py:267] Loading weights took 34.54 seconds
[1;36m(Worker_TP0 pid=22152)[0;0m INFO 10-02 05:47:22 [model_runner_v1.py:2661] Loading model weights took 18.6823 GB
[1;36m(Worker_TP7 pid=22159)[0;0m INFO 10-02 05:47:22 [model_runner_v1.py:2661] Loading model weights took 18.6823 GB
[1;36m(Worker_TP4 pid=22156)[0;0m Downloading Model from https://www.modelscope.cn to directory: /root/.cache/modelscope/hub/models/Qwen/Qwen3-Next-80B-A3B-Instruct
[1;36m(Worker_TP4 pid=22156)[0;0m INFO 10-02 05:47:24 [default_loader.py:267] Loading weights took 35.59 seconds
[1;36m(Worker_TP1 pid=22153)[0;0m Downloading Model from https://www.modelscope.cn to directory: /root/.cache/modelscope/hub/models/Qwen/Qwen3-Next-80B-A3B-Instruct
[1;36m(Worker_TP1 pid=22153)[0;0m INFO 10-02 05:47:25 [default_loader.py:267] Loading weights took 35.81 seconds
[1;36m(Worker_TP4 pid=22156)[0;0m INFO 10-02 05:47:25 [model_runner_v1.py:2661] Loading model weights took 18.6823 GB
[1;36m(Worker_TP3 pid=22155)[0;0m Downloading Model from https://www.modelscope.cn to directory: /root/.cache/modelscope/hub/models/Qwen/Qwen3-Next-80B-A3B-Instruct
[1;36m(Worker_TP3 pid=22155)[0;0m INFO 10-02 05:47:25 [default_loader.py:267] Loading weights took 35.36 seconds
[1;36m(Worker_TP3 pid=22155)[0;0m INFO 10-02 05:47:26 [model_runner_v1.py:2661] Loading model weights took 18.6823 GB
[1;36m(Worker_TP1 pid=22153)[0;0m INFO 10-02 05:47:26 [model_runner_v1.py:2661] Loading model weights took 18.6823 GB
[1;36m(Worker_TP2 pid=22154)[0;0m Downloading Model from https://www.modelscope.cn to directory: /root/.cache/modelscope/hub/models/Qwen/Qwen3-Next-80B-A3B-Instruct
[1;36m(Worker_TP2 pid=22154)[0;0m INFO 10-02 05:47:27 [default_loader.py:267] Loading weights took 35.14 seconds
[1;36m(Worker_TP5 pid=22157)[0;0m Downloading Model from https://www.modelscope.cn to directory: /root/.cache/modelscope/hub/models/Qwen/Qwen3-Next-80B-A3B-Instruct
[1;36m(Worker_TP5 pid=22157)[0;0m INFO 10-02 05:47:28 [default_loader.py:267] Loading weights took 36.73 seconds
[1;36m(Worker_TP2 pid=22154)[0;0m INFO 10-02 05:47:28 [model_runner_v1.py:2661] Loading model weights took 18.6823 GB
[1;36m(Worker_TP6 pid=22158)[0;0m Downloading Model from https://www.modelscope.cn to directory: /root/.cache/modelscope/hub/models/Qwen/Qwen3-Next-80B-A3B-Instruct
[1;36m(Worker_TP6 pid=22158)[0;0m INFO 10-02 05:47:28 [default_loader.py:267] Loading weights took 35.78 seconds
[1;36m(Worker_TP5 pid=22157)[0;0m INFO 10-02 05:47:29 [model_runner_v1.py:2661] Loading model weights took 18.6823 GB
[1;36m(Worker_TP6 pid=22158)[0;0m INFO 10-02 05:47:29 [model_runner_v1.py:2661] Loading model weights took 18.6823 GB
[1;36m(Worker_TP3 pid=22155)[0;0m INFO 10-02 05:47:52 [worker_v1.py:234] Available memory: 8312886169, total memory: 31675383808
[1;36m(Worker_TP6 pid=22158)[0;0m INFO 10-02 05:47:52 [worker_v1.py:234] Available memory: 8312501145, total memory: 31675383808
[1;36m(Worker_TP0 pid=22152)[0;0m INFO 10-02 05:47:52 [worker_v1.py:234] Available memory: 7901660057, total memory: 31675383808
[1;36m(Worker_TP2 pid=22154)[0;0m INFO 10-02 05:47:52 [worker_v1.py:234] Available memory: 8313103257, total memory: 31675383808
[1;36m(Worker_TP7 pid=22159)[0;0m INFO 10-02 05:47:52 [worker_v1.py:234] Available memory: 8312021913, total memory: 31675383808
[1;36m(Worker_TP5 pid=22157)[0;0m INFO 10-02 05:47:52 [worker_v1.py:234] Available memory: 8312365977, total memory: 31675383808
[1;36m(Worker_TP1 pid=22153)[0;0m INFO 10-02 05:47:53 [worker_v1.py:234] Available memory: 8312587161, total memory: 31675383808
[1;36m(Worker_TP4 pid=22156)[0;0m INFO 10-02 05:47:53 [worker_v1.py:234] Available memory: 8312091545, total memory: 31675383808
[1;36m(EngineCore_DP0 pid=22014)[0;0m INFO 10-02 05:47:53 [kv_cache_utils.py:1087] GPU KV cache size: 160,704 tokens
[1;36m(EngineCore_DP0 pid=22014)[0;0m INFO 10-02 05:47:53 [kv_cache_utils.py:1091] Maximum concurrency for 1,024 tokens per request: 372.11x
[1;36m(EngineCore_DP0 pid=22014)[0;0m INFO 10-02 05:47:53 [kv_cache_utils.py:1087] GPU KV cache size: 168,960 tokens
[1;36m(EngineCore_DP0 pid=22014)[0;0m INFO 10-02 05:47:53 [kv_cache_utils.py:1091] Maximum concurrency for 1,024 tokens per request: 391.44x
[1;36m(EngineCore_DP0 pid=22014)[0;0m INFO 10-02 05:47:53 [kv_cache_utils.py:1087] GPU KV cache size: 168,960 tokens
[1;36m(EngineCore_DP0 pid=22014)[0;0m INFO 10-02 05:47:53 [kv_cache_utils.py:1091] Maximum concurrency for 1,024 tokens per request: 391.44x
[1;36m(EngineCore_DP0 pid=22014)[0;0m INFO 10-02 05:47:53 [kv_cache_utils.py:1087] GPU KV cache size: 168,960 tokens
[1;36m(EngineCore_DP0 pid=22014)[0;0m INFO 10-02 05:47:53 [kv_cache_utils.py:1091] Maximum concurrency for 1,024 tokens per request: 391.44x
[1;36m(EngineCore_DP0 pid=22014)[0;0m INFO 10-02 05:47:53 [kv_cache_utils.py:1087] GPU KV cache size: 168,960 tokens
[1;36m(EngineCore_DP0 pid=22014)[0;0m INFO 10-02 05:47:53 [kv_cache_utils.py:1091] Maximum concurrency for 1,024 tokens per request: 391.44x
[1;36m(EngineCore_DP0 pid=22014)[0;0m INFO 10-02 05:47:53 [kv_cache_utils.py:1087] GPU KV cache size: 168,960 tokens
[1;36m(EngineCore_DP0 pid=22014)[0;0m INFO 10-02 05:47:53 [kv_cache_utils.py:1091] Maximum concurrency for 1,024 tokens per request: 391.44x
[1;36m(EngineCore_DP0 pid=22014)[0;0m INFO 10-02 05:47:53 [kv_cache_utils.py:1087] GPU KV cache size: 168,960 tokens
[1;36m(EngineCore_DP0 pid=22014)[0;0m INFO 10-02 05:47:53 [kv_cache_utils.py:1091] Maximum concurrency for 1,024 tokens per request: 391.44x
[1;36m(EngineCore_DP0 pid=22014)[0;0m INFO 10-02 05:47:53 [kv_cache_utils.py:1087] GPU KV cache size: 168,960 tokens
[1;36m(EngineCore_DP0 pid=22014)[0;0m INFO 10-02 05:47:53 [kv_cache_utils.py:1091] Maximum concurrency for 1,024 tokens per request: 391.44x
[1;36m(Worker_TP0 pid=22152)[0;0m ERROR 10-02 05:47:55 [multiproc_executor.py:671] WorkerProc hit an exception.
[1;36m(Worker_TP0 pid=22152)[0;0m ERROR 10-02 05:47:55 [multiproc_executor.py:671] Traceback (most recent call last):
[1;36m(Worker_TP0 pid=22152)[0;0m ERROR 10-02 05:47:55 [multiproc_executor.py:671]   File "/vllm-workspace/vllm/vllm/v1/executor/multiproc_executor.py", line 666, in worker_busy_loop
[1;36m(Worker_TP0 pid=22152)[0;0m ERROR 10-02 05:47:55 [multiproc_executor.py:671]     output = func(*args, **kwargs)
[1;36m(Worker_TP0 pid=22152)[0;0m ERROR 10-02 05:47:55 [multiproc_executor.py:671]              ^^^^^^^^^^^^^^^^^^^^^
[1;36m(Worker_TP0 pid=22152)[0;0m ERROR 10-02 05:47:55 [multiproc_executor.py:671]   File "/vllm-workspace/vllm/vllm/worker/worker_base.py", line 254, in initialize_from_config
[1;36m(Worker_TP0 pid=22152)[0;0m ERROR 10-02 05:47:55 [multiproc_executor.py:671]     self.worker.initialize_from_config(kv_cache_config)  # type: ignore
[1;36m(Worker_TP0 pid=22152)[0;0m ERROR 10-02 05:47:55 [multiproc_executor.py:671]     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[1;36m(Worker_TP0 pid=22152)[0;0m ERROR 10-02 05:47:55 [multiproc_executor.py:671]   File "/vllm-workspace/vllm-ascend/vllm_ascend/worker/worker_v1.py", line 336, in initialize_from_config
[1;36m(Worker_TP0 pid=22152)[0;0m ERROR 10-02 05:47:55 [multiproc_executor.py:671]     self.model_runner.initialize_kv_cache(kv_cache_config)
[1;36m(Worker_TP0 pid=22152)[0;0m ERROR 10-02 05:47:55 [multiproc_executor.py:671]   File "/vllm-workspace/vllm-ascend/vllm_ascend/worker/model_runner_v1.py", line 2709, in initialize_kv_cache
[1;36m(Worker_TP0 pid=22152)[0;0m ERROR 10-02 05:47:55 [multiproc_executor.py:671]     kv_caches = self.initialize_kv_cache_tensors(kv_cache_config)
[1;36m(Worker_TP0 pid=22152)[0;0m ERROR 10-02 05:47:55 [multiproc_executor.py:671]                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[1;36m(Worker_TP0 pid=22152)[0;0m ERROR 10-02 05:47:55 [multiproc_executor.py:671]   File "/vllm-workspace/vllm-ascend/vllm_ascend/worker/model_runner_v1.py", line 2945, in initialize_kv_cache_tensors
[1;36m(Worker_TP0 pid=22152)[0;0m ERROR 10-02 05:47:55 [multiproc_executor.py:671]     tensor = torch.zeros(kv_cache_tensor.size,
[1;36m(Worker_TP0 pid=22152)[0;0m ERROR 10-02 05:47:55 [multiproc_executor.py:671]              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[1;36m(Worker_TP0 pid=22152)[0;0m ERROR 10-02 05:47:55 [multiproc_executor.py:671] RuntimeError: NPU out of memory. Tried to allocate 628.00 MiB (NPU 0; 29.50 GiB total capacity; 27.39 GiB already allocated; 27.39 GiB current active; 478.15 MiB free; 27.80 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.
[1;36m(Worker_TP0 pid=22152)[0;0m ERROR 10-02 05:47:55 [multiproc_executor.py:671] Traceback (most recent call last):
[1;36m(Worker_TP0 pid=22152)[0;0m ERROR 10-02 05:47:55 [multiproc_executor.py:671]   File "/vllm-workspace/vllm/vllm/v1/executor/multiproc_executor.py", line 666, in worker_busy_loop
[1;36m(Worker_TP0 pid=22152)[0;0m ERROR 10-02 05:47:55 [multiproc_executor.py:671]     output = func(*args, **kwargs)
[1;36m(Worker_TP0 pid=22152)[0;0m ERROR 10-02 05:47:55 [multiproc_executor.py:671]              ^^^^^^^^^^^^^^^^^^^^^
[1;36m(Worker_TP0 pid=22152)[0;0m ERROR 10-02 05:47:55 [multiproc_executor.py:671]   File "/vllm-workspace/vllm/vllm/worker/worker_base.py", line 254, in initialize_from_config
[1;36m(Worker_TP0 pid=22152)[0;0m ERROR 10-02 05:47:55 [multiproc_executor.py:671]     self.worker.initialize_from_config(kv_cache_config)  # type: ignore
[1;36m(Worker_TP0 pid=22152)[0;0m ERROR 10-02 05:47:55 [multiproc_executor.py:671]     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[1;36m(Worker_TP0 pid=22152)[0;0m ERROR 10-02 05:47:55 [multiproc_executor.py:671]   File "/vllm-workspace/vllm-ascend/vllm_ascend/worker/worker_v1.py", line 336, in initialize_from_config
[1;36m(Worker_TP0 pid=22152)[0;0m ERROR 10-02 05:47:55 [multiproc_executor.py:671]     self.model_runner.initialize_kv_cache(kv_cache_config)
[1;36m(Worker_TP0 pid=22152)[0;0m ERROR 10-02 05:47:55 [multiproc_executor.py:671]   File "/vllm-workspace/vllm-ascend/vllm_ascend/worker/model_runner_v1.py", line 2709, in initialize_kv_cache
[1;36m(Worker_TP0 pid=22152)[0;0m ERROR 10-02 05:47:55 [multiproc_executor.py:671]     kv_caches = self.initialize_kv_cache_tensors(kv_cache_config)
[1;36m(Worker_TP0 pid=22152)[0;0m ERROR 10-02 05:47:55 [multiproc_executor.py:671]                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[1;36m(Worker_TP0 pid=22152)[0;0m ERROR 10-02 05:47:55 [multiproc_executor.py:671]   File "/vllm-workspace/vllm-ascend/vllm_ascend/worker/model_runner_v1.py", line 2945, in initialize_kv_cache_tensors
[1;36m(Worker_TP0 pid=22152)[0;0m ERROR 10-02 05:47:55 [multiproc_executor.py:671]     tensor = torch.zeros(kv_cache_tensor.size,
[1;36m(Worker_TP0 pid=22152)[0;0m ERROR 10-02 05:47:55 [multiproc_executor.py:671]              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[1;36m(Worker_TP0 pid=22152)[0;0m ERROR 10-02 05:47:55 [multiproc_executor.py:671] RuntimeError: NPU out of memory. Tried to allocate 628.00 MiB (NPU 0; 29.50 GiB total capacity; 27.39 GiB already allocated; 27.39 GiB current active; 478.15 MiB free; 27.80 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.
[1;36m(Worker_TP0 pid=22152)[0;0m ERROR 10-02 05:47:55 [multiproc_executor.py:671] 
[1;36m(EngineCore_DP0 pid=22014)[0;0m ERROR 10-02 05:47:55 [core.py:708] EngineCore failed to start.
[1;36m(EngineCore_DP0 pid=22014)[0;0m ERROR 10-02 05:47:55 [core.py:708] Traceback (most recent call last):
[1;36m(EngineCore_DP0 pid=22014)[0;0m ERROR 10-02 05:47:55 [core.py:708]   File "/vllm-workspace/vllm/vllm/v1/engine/core.py", line 699, in run_engine_core
[1;36m(EngineCore_DP0 pid=22014)[0;0m ERROR 10-02 05:47:55 [core.py:708]     engine_core = EngineCoreProc(*args, **kwargs)
[1;36m(EngineCore_DP0 pid=22014)[0;0m ERROR 10-02 05:47:55 [core.py:708]                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[1;36m(EngineCore_DP0 pid=22014)[0;0m ERROR 10-02 05:47:55 [core.py:708]   File "/vllm-workspace/vllm/vllm/v1/engine/core.py", line 498, in __init__
[1;36m(EngineCore_DP0 pid=22014)[0;0m ERROR 10-02 05:47:55 [core.py:708]     super().__init__(vllm_config, executor_class, log_stats,
[1;36m(EngineCore_DP0 pid=22014)[0;0m ERROR 10-02 05:47:55 [core.py:708]   File "/vllm-workspace/vllm/vllm/v1/engine/core.py", line 92, in __init__
[1;36m(EngineCore_DP0 pid=22014)[0;0m ERROR 10-02 05:47:55 [core.py:708]     self._initialize_kv_caches(vllm_config)
[1;36m(EngineCore_DP0 pid=22014)[0;0m ERROR 10-02 05:47:55 [core.py:708]   File "/vllm-workspace/vllm/vllm/v1/engine/core.py", line 207, in _initialize_kv_caches
[1;36m(EngineCore_DP0 pid=22014)[0;0m ERROR 10-02 05:47:55 [core.py:708]     self.model_executor.initialize_from_config(kv_cache_configs)
[1;36m(EngineCore_DP0 pid=22014)[0;0m ERROR 10-02 05:47:55 [core.py:708]   File "/vllm-workspace/vllm/vllm/v1/executor/abstract.py", line 73, in initialize_from_config
[1;36m(EngineCore_DP0 pid=22014)[0;0m ERROR 10-02 05:47:55 [core.py:708]     self.collective_rpc("initialize_from_config",
[1;36m(EngineCore_DP0 pid=22014)[0;0m ERROR 10-02 05:47:55 [core.py:708]   File "/vllm-workspace/vllm/vllm/v1/executor/multiproc_executor.py", line 264, in collective_rpc
[1;36m(EngineCore_DP0 pid=22014)[0;0m ERROR 10-02 05:47:55 [core.py:708]     result = get_response(w, dequeue_timeout,
[1;36m(EngineCore_DP0 pid=22014)[0;0m ERROR 10-02 05:47:55 [core.py:708]              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[1;36m(EngineCore_DP0 pid=22014)[0;0m ERROR 10-02 05:47:55 [core.py:708]   File "/vllm-workspace/vllm/vllm/v1/executor/multiproc_executor.py", line 248, in get_response
[1;36m(EngineCore_DP0 pid=22014)[0;0m ERROR 10-02 05:47:55 [core.py:708]     raise RuntimeError(
[1;36m(EngineCore_DP0 pid=22014)[0;0m ERROR 10-02 05:47:55 [core.py:708] RuntimeError: Worker failed with error 'NPU out of memory. Tried to allocate 628.00 MiB (NPU 0; 29.50 GiB total capacity; 27.39 GiB already allocated; 27.39 GiB current active; 478.15 MiB free; 27.80 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.', please check the stack trace above for the root cause
[1;36m(EngineCore_DP0 pid=22014)[0;0m ERROR 10-02 05:48:06 [multiproc_executor.py:154] Worker proc VllmWorker-0 died unexpectedly, shutting down executor.
[1;36m(EngineCore_DP0 pid=22014)[0;0m Process EngineCore_DP0:
[1;36m(EngineCore_DP0 pid=22014)[0;0m Traceback (most recent call last):
[1;36m(EngineCore_DP0 pid=22014)[0;0m   File "/usr/local/python3.11.13/lib/python3.11/multiprocessing/process.py", line 314, in _bootstrap
[1;36m(EngineCore_DP0 pid=22014)[0;0m     self.run()
[1;36m(EngineCore_DP0 pid=22014)[0;0m   File "/usr/local/python3.11.13/lib/python3.11/multiprocessing/process.py", line 108, in run
[1;36m(EngineCore_DP0 pid=22014)[0;0m     self._target(*self._args, **self._kwargs)
[1;36m(EngineCore_DP0 pid=22014)[0;0m   File "/vllm-workspace/vllm/vllm/v1/engine/core.py", line 712, in run_engine_core
[1;36m(EngineCore_DP0 pid=22014)[0;0m     raise e
[1;36m(EngineCore_DP0 pid=22014)[0;0m   File "/vllm-workspace/vllm/vllm/v1/engine/core.py", line 699, in run_engine_core
[1;36m(EngineCore_DP0 pid=22014)[0;0m     engine_core = EngineCoreProc(*args, **kwargs)
[1;36m(EngineCore_DP0 pid=22014)[0;0m                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[1;36m(EngineCore_DP0 pid=22014)[0;0m   File "/vllm-workspace/vllm/vllm/v1/engine/core.py", line 498, in __init__
[1;36m(EngineCore_DP0 pid=22014)[0;0m     super().__init__(vllm_config, executor_class, log_stats,
[1;36m(EngineCore_DP0 pid=22014)[0;0m   File "/vllm-workspace/vllm/vllm/v1/engine/core.py", line 92, in __init__
[1;36m(EngineCore_DP0 pid=22014)[0;0m     self._initialize_kv_caches(vllm_config)
[1;36m(EngineCore_DP0 pid=22014)[0;0m   File "/vllm-workspace/vllm/vllm/v1/engine/core.py", line 207, in _initialize_kv_caches
[1;36m(EngineCore_DP0 pid=22014)[0;0m     self.model_executor.initialize_from_config(kv_cache_configs)
[1;36m(EngineCore_DP0 pid=22014)[0;0m   File "/vllm-workspace/vllm/vllm/v1/executor/abstract.py", line 73, in initialize_from_config
[1;36m(EngineCore_DP0 pid=22014)[0;0m     self.collective_rpc("initialize_from_config",
[1;36m(EngineCore_DP0 pid=22014)[0;0m   File "/vllm-workspace/vllm/vllm/v1/executor/multiproc_executor.py", line 264, in collective_rpc
[1;36m(EngineCore_DP0 pid=22014)[0;0m     result = get_response(w, dequeue_timeout,
[1;36m(EngineCore_DP0 pid=22014)[0;0m              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[1;36m(EngineCore_DP0 pid=22014)[0;0m   File "/vllm-workspace/vllm/vllm/v1/executor/multiproc_executor.py", line 248, in get_response
[1;36m(EngineCore_DP0 pid=22014)[0;0m     raise RuntimeError(
[1;36m(EngineCore_DP0 pid=22014)[0;0m RuntimeError: Worker failed with error 'NPU out of memory. Tried to allocate 628.00 MiB (NPU 0; 29.50 GiB total capacity; 27.39 GiB already allocated; 27.39 GiB current active; 478.15 MiB free; 27.80 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.', please check the stack trace above for the root cause
[1;36m(APIServer pid=21740)[0;0m Traceback (most recent call last):
[1;36m(APIServer pid=21740)[0;0m   File "/usr/local/python3.11.13/bin/vllm", line 8, in <module>
[1;36m(APIServer pid=21740)[0;0m     sys.exit(main())
[1;36m(APIServer pid=21740)[0;0m              ^^^^^^
[1;36m(APIServer pid=21740)[0;0m   File "/vllm-workspace/vllm/vllm/entrypoints/cli/main.py", line 54, in main
[1;36m(APIServer pid=21740)[0;0m     args.dispatch_function(args)
[1;36m(APIServer pid=21740)[0;0m   File "/vllm-workspace/vllm/vllm/entrypoints/cli/serve.py", line 57, in cmd
[1;36m(APIServer pid=21740)[0;0m     uvloop.run(run_server(args))
[1;36m(APIServer pid=21740)[0;0m   File "/usr/local/python3.11.13/lib/python3.11/site-packages/uvloop/__init__.py", line 105, in run
[1;36m(APIServer pid=21740)[0;0m     return runner.run(wrapper())
[1;36m(APIServer pid=21740)[0;0m            ^^^^^^^^^^^^^^^^^^^^^
[1;36m(APIServer pid=21740)[0;0m   File "/usr/local/python3.11.13/lib/python3.11/asyncio/runners.py", line 118, in run
[1;36m(APIServer pid=21740)[0;0m     return self._loop.run_until_complete(task)
[1;36m(APIServer pid=21740)[0;0m            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[1;36m(APIServer pid=21740)[0;0m   File "uvloop/loop.pyx", line 1518, in uvloop.loop.Loop.run_until_complete
[1;36m(APIServer pid=21740)[0;0m   File "/usr/local/python3.11.13/lib/python3.11/site-packages/uvloop/__init__.py", line 61, in wrapper
[1;36m(APIServer pid=21740)[0;0m     return await main
[1;36m(APIServer pid=21740)[0;0m            ^^^^^^^^^^
[1;36m(APIServer pid=21740)[0;0m   File "/vllm-workspace/vllm/vllm/entrypoints/openai/api_server.py", line 1884, in run_server
[1;36m(APIServer pid=21740)[0;0m     await run_server_worker(listen_address, sock, args, **uvicorn_kwargs)
[1;36m(APIServer pid=21740)[0;0m   File "/vllm-workspace/vllm/vllm/entrypoints/openai/api_server.py", line 1902, in run_server_worker
[1;36m(APIServer pid=21740)[0;0m     async with build_async_engine_client(
[1;36m(APIServer pid=21740)[0;0m   File "/usr/local/python3.11.13/lib/python3.11/contextlib.py", line 210, in __aenter__
[1;36m(APIServer pid=21740)[0;0m     return await anext(self.gen)
[1;36m(APIServer pid=21740)[0;0m            ^^^^^^^^^^^^^^^^^^^^^
[1;36m(APIServer pid=21740)[0;0m   File "/vllm-workspace/vllm/vllm/entrypoints/openai/api_server.py", line 180, in build_async_engine_client
[1;36m(APIServer pid=21740)[0;0m     async with build_async_engine_client_from_engine_args(
[1;36m(APIServer pid=21740)[0;0m   File "/usr/local/python3.11.13/lib/python3.11/contextlib.py", line 210, in __aenter__
[1;36m(APIServer pid=21740)[0;0m     return await anext(self.gen)
[1;36m(APIServer pid=21740)[0;0m            ^^^^^^^^^^^^^^^^^^^^^
[1;36m(APIServer pid=21740)[0;0m   File "/vllm-workspace/vllm/vllm/entrypoints/openai/api_server.py", line 225, in build_async_engine_client_from_engine_args
[1;36m(APIServer pid=21740)[0;0m     async_llm = AsyncLLM.from_vllm_config(
[1;36m(APIServer pid=21740)[0;0m                 ^^^^^^^^^^^^^^^^^^^^^^^^^^
[1;36m(APIServer pid=21740)[0;0m   File "/vllm-workspace/vllm/vllm/utils/__init__.py", line 1571, in inner
[1;36m(APIServer pid=21740)[0;0m     return fn(*args, **kwargs)
[1;36m(APIServer pid=21740)[0;0m            ^^^^^^^^^^^^^^^^^^^
[1;36m(APIServer pid=21740)[0;0m   File "/vllm-workspace/vllm/vllm/v1/engine/async_llm.py", line 207, in from_vllm_config
[1;36m(APIServer pid=21740)[0;0m     return cls(
[1;36m(APIServer pid=21740)[0;0m            ^^^^
[1;36m(APIServer pid=21740)[0;0m   File "/vllm-workspace/vllm/vllm/v1/engine/async_llm.py", line 134, in __init__
[1;36m(APIServer pid=21740)[0;0m     self.engine_core = EngineCoreClient.make_async_mp_client(
[1;36m(APIServer pid=21740)[0;0m                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[1;36m(APIServer pid=21740)[0;0m   File "/vllm-workspace/vllm/vllm/v1/engine/core_client.py", line 102, in make_async_mp_client
[1;36m(APIServer pid=21740)[0;0m     return AsyncMPClient(*client_args)
[1;36m(APIServer pid=21740)[0;0m            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
[1;36m(APIServer pid=21740)[0;0m   File "/vllm-workspace/vllm/vllm/v1/engine/core_client.py", line 769, in __init__
[1;36m(APIServer pid=21740)[0;0m     super().__init__(
[1;36m(APIServer pid=21740)[0;0m   File "/vllm-workspace/vllm/vllm/v1/engine/core_client.py", line 448, in __init__
[1;36m(APIServer pid=21740)[0;0m     with launch_core_engines(vllm_config, executor_class,
[1;36m(APIServer pid=21740)[0;0m   File "/usr/local/python3.11.13/lib/python3.11/contextlib.py", line 144, in __exit__
[1;36m(APIServer pid=21740)[0;0m     next(self.gen)
[1;36m(APIServer pid=21740)[0;0m   File "/vllm-workspace/vllm/vllm/v1/engine/utils.py", line 732, in launch_core_engines
[1;36m(APIServer pid=21740)[0;0m     wait_for_engine_startup(
[1;36m(APIServer pid=21740)[0;0m   File "/vllm-workspace/vllm/vllm/v1/engine/utils.py", line 785, in wait_for_engine_startup
[1;36m(APIServer pid=21740)[0;0m     raise RuntimeError("Engine core initialization failed. "
[1;36m(APIServer pid=21740)[0;0m RuntimeError: Engine core initialization failed. See root cause above. Failed core proc(s): {}
[1;36m(APIServer pid=21740)[0;0m [ERROR] 2025-10-02-05:48:09 (PID:21740, Device:-1, RankID:-1) ERR99999 UNKNOWN applicaiton exception
```

The attachment is stderr with VLLM_LOGGING_LEVEL=DEBUG.
[Qwen3-Next-80B-A3B-Instruct.20251002.log](https://github.com/user-attachments/files/22654255/Qwen3-Next-80B-A3B-Instruct.20251002.log)

**Comment by lishengting** [comment]
Anybody can help? @Yikun

**Comment by ej1-hw** [comment]
```
VLLM_USE_FLASHINFER_MOE_FP16=1 \
ASCEND_RT_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 \
vllm serve Qwen3-Next-80B-A3B-Instruct \
--tensor-parallel-size 8 \
--max-model-len 98304 \
--gpu-memory-utilization 0.7 \
--enforce-eager
```

I managed to get it to work with this using this custom built image:
```
FROM quay.io/ascend/vllm-ascend:v0.11.0rc0
RUN pip install --upgrade "torch>=2.8.0"
RUN pip install --extra-index-url https://mirrors.huaweicloud.com/ascend/repos/pypi "torch-npu>=2.8.0rc1"

# Using whl built https://github.com/zhangxinyuehfad/vllm-ascend/tree/zxy_fix_ascend_config
# Above is to fix ascend_config error as per pull request 3305: https://github.com/vllm-project/vllm-ascend/pull/3305
RUN pip install --ignore-installed vllm_ascend-0.11.0rc0+patch20251008-cp311-cp311-linux_aarch64.whl

RUN wget --no-check-certificate https://vllm-ascend.obs.cn-north-4.myhuaweicloud.com/vllm-ascend/Ascend-BiSheng-toolkit_aarch64.run && \
    chmod a+x Ascend-BiSheng-toolkit_aarch64.run && \
    ./Ascend-BiSheng-toolkit_aarch64.run --install && \
    source /usr/local/Ascend/8.3.RC1/bisheng_toolkit/set_env.sh

RUN wget --no-check-certificate https://vllm-ascend.obs.cn-north-4.myhuaweicloud.com/vllm-ascend/triton_ascend-3.2.0.dev20250914-cp311-cp311-manylinux_2_27_aarch64.manylinux_2_28_aarch64.whl && \
    pip install triton_ascend-3.2.0.dev20250914-cp311-cp311-manylinux_2_27_aarch64.manylinux_2_28_aarch64.whl


RUN echo 'source /usr/local/Ascend/ascend-toolkit/set_env.sh' >> ~/.bashrc && \
    echo 'source /usr/local/Ascend/nnal/atb/set_env.sh' >> ~/.bashrc && \
    echo 'source /usr/local/Ascend/8.3.RC1/bisheng_toolkit/set_env.sh' >> ~/.bashrc

RUN source ~/.bashrc
```

**Comment by Jerry-bear** [comment]
same question

**Comment by lishengting** [comment]
> ```
> VLLM_USE_FLASHINFER_MOE_FP16=1 \
> ASCEND_RT_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 \
> vllm serve Qwen3-Next-80B-A3B-Instruct \
> --tensor-parallel-size 8 \
> --max-model-len 98304 \
> --gpu-memory-utilization 0.7 \
> --enforce-eager
> ```
> 
> I managed to get it to work with this using this custom built image:
> 
> ```
> FROM quay.io/ascend/vllm-ascend:v0.11.0rc0
> RUN pip install --upgrade "torch>=2.8.0"
> RUN pip install --extra-index-url https://mirrors.huaweicloud.com/ascend/repos/pypi "torch-npu>=2.8.0rc1"
> 
> # Using whl built https://github.com/zhangxinyuehfad/vllm-ascend/tree/zxy_fix_ascend_config
> # Above is to fix ascend_config error as per pull request 3305: https://github.com/vllm-project/vllm-ascend/pull/3305
> RUN pip install --ignore-installed vllm_ascend-0.11.0rc0+patch20251008-cp311-cp311-linux_aarch64.whl
> 
> RUN wget --no-check-certificate https://vllm-ascend.obs.cn-north-4.myhuaweicloud.com/vllm-ascend/Ascend-BiSheng-toolkit_aarch64.run && \
>     chmod a+x Ascend-BiSheng-toolkit_aarch64.run && \
>     ./Ascend-BiSheng-toolkit_aarch64.run --install && \
>     source /usr/local/Ascend/8.3.RC1/bisheng_toolkit/set_env.sh
> 
> RUN wget --no-check-certificate https://vllm-ascend.obs.cn-north-4.myhuaweicloud.com/vllm-ascend/triton_ascend-3.2.0.dev20250914-cp311-cp311-manylinux_2_27_aarch64.manylinux_2_28_aarch64.whl && \
>     pip install triton_ascend-3.2.0.dev20250914-cp311-cp311-manylinux_2_27_aarch64.manylinux_2_28_aarch64.whl
> 
> 
> RUN echo 'source /usr/local/Ascend/ascend-toolkit/set_env.sh' >> ~/.bashrc && \
>     echo 'source /usr/local/Ascend/nnal/atb/set_env.sh' >> ~/.bashrc && \
>     echo 'source /usr/local/Ascend/8.3.RC1/bisheng_toolkit/set_env.sh' >> ~/.bashrc
> 
> RUN source ~/.bashrc
> ```

but how to get vllm_ascend-0.11.0rc0+patch20251008-cp311-cp311-linux_aarch64.whl?
I tried to build it but failed. @ej1-hw 

> root@8077defb9424:/workspace/vllm-ascend# python -m build --wheel
> * Creating isolated environment: venv+pip...
> * Installing packages in isolated environment:
>   - cmake>=3.26
>   - decorator
>   - einops
>   - msgpack
>   - numba
>   - numpy<2.0.0
>   - packaging
>   - pip
>   - pybind11
>   - pyyaml
>   - quart
>   - scipy
>   - setuptools-scm>=8
>   - setuptools>=64
>   - torch-npu==2.7.1.dev20250919
>   - torch>=2.7.1
>   - torchvision
>   - wheel
> > /usr/local/python3.11.13/bin/python -m pip --python /tmp/build-env-2zqjzl1n/bin/python install --use-pep517 --no-warn-script-location --no-compile -r /tmp/build-reqs-jhg8nu7w.txt
> < Collecting pybind11 (from -r /tmp/build-reqs-jhg8nu7w.txt (line 1))
> <   Downloading pybind11-3.0.1-py3-none-any.whl.metadata (10.0 kB)
> < Collecting setuptools-scm>=8 (from -r /tmp/build-reqs-jhg8nu7w.txt (line 2))
> <   Downloading setuptools_scm-9.2.1-py3-none-any.whl.metadata (7.7 kB)
> < Collecting scipy (from -r /tmp/build-reqs-jhg8nu7w.txt (line 3))
> <   Downloading scipy-1.16.2-cp311-cp311-manylinux2014_aarch64.manylinux_2_17_aarch64.whl.metadata (62 kB)
> < Collecting wheel (from -r /tmp/build-reqs-jhg8nu7w.txt (line 4))
> <   Downloading wheel-0.45.1-py3-none-any.whl.metadata (2.3 kB)
> < Collecting numba (from -r /tmp/build-reqs-jhg8nu7w.txt (line 5))
> <   Downloading numba-0.62.1-cp311-cp311-manylinux_2_27_aarch64.manylinux_2_28_aarch64.whl.metadata (2.8 kB)
> < WARNING: The directory '/root/.cache/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with
>   sudo, you should use sudo's -H flag.
> < ERROR: Ignored the following versions that require a different python version: 0.52.0 Requires-Python >=3.6,<3.9; 0.52.0rc3 Requires-Python >=3.6,<3.9; 0.53.0 Requires-Python >=3.6,<3.10; 0.53.0rc1.post1 Requires-Python
>   >=3.6,<3.10; 0.53.0rc2 Requires-Python >=3.6,<3.10; 0.53.0rc3 Requires-Python >=3.6,<3.10; 0.53.1 Requires-Python >=3.6,<3.10; 0.54.0 Requires-Python >=3.7,<3.10; 0.54.0rc2 Requires-Python >=3.7,<3.10; 0.54.0rc3 Requires-
>   Python >=3.7,<3.10; 0.54.1 Requires-Python >=3.7,<3.10; 0.55.0 Requires-Python >=3.7,<3.11; 0.55.0rc1 Requires-Python >=3.7,<3.11; 0.55.1 Requires-Python >=3.7,<3.11; 0.55.2 Requires-Python >=3.7,<3.11; 1.6.2 Requires-
>   Python >=3.7,<3.10; 1.6.3 Requires-Python >=3.7,<3.10; 1.7.0 Requires-Python >=3.7,<3.10; 1.7.1 Requires-Python >=3.7,<3.10; 1.7.2 Requires-Python >=3.7,<3.11; 1.7.3 Requires-Python >=3.7,<3.11; 1.8.0 Requires-Python
>   >=3.8,<3.11; 1.8.0rc1 Requires-Python >=3.8,<3.11; 1.8.0rc2 Requires-Python >=3.8,<3.11; 1.8.0rc3 Requires-Python >=3.8,<3.11; 1.8.0rc4 Requires-Python >=3.8,<3.11; 1.8.1 Requires-Python >=3.8,<3.11
> < ERROR: Could not find a version that satisfies the requirement torch-npu==2.7.1.dev20250919 (from versions: 2.1.0.post8, 2.1.0.post10, 2.1.0.post12, 2.1.0.post13, 2.3.1.post2, 2.3.1.post4, 2.3.1.post6, 2.4.0, 2.4.0.post2,
>   2.4.0.post4, 2.5.1rc1, 2.5.1, 2.5.1.post1, 2.6.0rc1, 2.6.0, 2.7.1rc1, 2.8.0rc1)
> < ERROR: No matching distribution found for torch-npu==2.7.1.dev20250919
> 
> Traceback (most recent call last):
>   File "/usr/local/python3.11.13/lib/python3.11/site-packages/build/__main__.py", line 179, in _handle_build_error
>     yield
>   File "/usr/local/python3.11.13/lib/python3.11/site-packages/build/__main__.py", line 460, in main
>     built = build_call(
>             ^^^^^^^^^^^
>   File "/usr/local/python3.11.13/lib/python3.11/site-packages/build/__main__.py", line 239, in build_package
>     out = _build(isolation, srcdir, outdir, distribution, config_settings, skip_dependency_check, installer)
>           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/python3.11.13/lib/python3.11/site-packages/build/__main__.py", line 171, in _build
>     return _build_in_isolated_env(srcdir, outdir, distribution, config_settings, installer)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/local/python3.11.13/lib/python3.11/site-packages/build/__main__.py", line 136, in _build_in_isolated_env
>     env.install(builder.build_system_requires)
>   File "/usr/local/python3.11.13/lib/python3.11/site-packages/build/env.py", line 137, in install
>     self._env_backend.install_requirements(requirements)
>   File "/usr/local/python3.11.13/lib/python3.11/site-packages/build/env.py", line 286, in install_requirements
>     run_subprocess(cmd)
>   File "/usr/local/python3.11.13/lib/python3.11/site-packages/build/_ctx.py", line 72, in run_subprocess
>     subprocess.run(cmd, capture_output=True, check=True, env=env)
>   File "/usr/local/python3.11.13/lib/python3.11/subprocess.py", line 571, in run
>     raise CalledProcessError(retcode, process.args,
> subprocess.CalledProcessError: Command '['/usr/local/python3.11.13/bin/python', '-m', 'pip', '--python', '/tmp/build-env-2zqjzl1n/bin/python', 'install', '--use-pep517', '--no-warn-script-location', '--no-compile', '-r', '/tmp/build-reqs-jhg8nu7w.txt']' returned non-zero exit status 1.
> 
> ERROR Command '['/usr/local/python3.11.13/bin/python', '-m', 'pip', '--python', '/tmp/build-env-2zqjzl1n/bin/python', 'install', '--use-pep517', '--no-warn-script-location', '--no-compile', '-r', '/tmp/build-reqs-jhg8nu7w.txt']' returned non-zero exit status 1.
> root@8077defb9424:/workspace/vllm-ascend#

**Comment by ej1-hw** [comment]
You can use this prebuilt-whl
[vllm_ascend-0.11.0rc0+patch20251008-cp311-cp311-linux_aarch64.zip](https://github.com/user-attachments/files/22875637/vllm_ascend-0.11.0rc0%2Bpatch20251008-cp311-cp311-linux_aarch64.zip)

or this prebuilt docker image tar file [ link valid for 18 hours]:
[vllm-ascend_v0.11.0rc3_patched.tar - 16GB](https://svc-modelarts-obs-hk.obs.ap-southeast-1.myhuaweicloud.com:443/vllm-ascend_v0.11.0rc3_patched.tar?AccessKeyId=HSTAH2B65HCOZ130I1QZ&Expires=1760383493&x-obs-security-token=hQ5hcC1zb3V0aGVhc3QtMwEAAAPPSFNUQUgyQjY1SENPWjEzMEkxUVrQn2fLGSqcduPHyViSoac7s6ASvK8KhuYpf0P2-W7M26XMsZtxTS4wEBgHVaPvEpDLcYyDokrw515RJDX81QlulQmPXAHJS9FtLPVBV5-t-VmLxXlICMJ6EbYmxUMODmrK6MqLbbYW98ZLNgZM2BYokMR0VOVOM1nKkbAS9R_jYT1JIgM5WH74MXiwL-UooHG4l4cMRdEUFfuM-aj9miS6iCBl2b3Fj2m3gyMUOMTuvvxMIqwBoSIJQ82reDmUFj_xPkY4dvaxTj6o5g-RBs6FL9i8Ja7Fe9OGDjRvb-pKcgZOtUByZ6VBh7Tjdlx1fIJzI5QAIxO2F_kFjmmfGAkPmW6AfCuGMIZyt1g5ICcuuJ-4jP-hCzWgI1xe0GSgY4_82Ugxd902P1nAG3BrhC4CnhMHE8I5Sr55xny24Wg6ysE1rlvklLdNqx0NTK0a3kIroa0-V9oWRveVbu7AQbvPpcrVpixr5JeTuraZxMwbz9Nt9hnL_UVRrAmXZ8F3sfuG4oCIjPfhbfSSb462J2VtF-fuxCmk9X-7e86UJewVufVawoM-D_krQjnfcgH0hfnt-Js7NsJPm6BrpdvFnfdbJ-ImIopnxMN7eFqLX30%3D&Signature=UHvc/dr/4aiJLUxk6c2UnzOvBTI%3D)

Please use above file at your own discretion. I will not be liable for any issues or damages arising from its use.

**Comment by wxsIcey** [comment]
Please adjust ```--gpu-memory-utilization to 0.5``` when tp=8. I have tested that there is no OOM problem.

Before running, you can add the following environment setting to prevent server-side oom :
```
export PYTORCH_NPU_ALLOC_CONF=max_split_size_mb:32
export PYTORCH_NPU_ALLOC_CONF=expandable_segments:True

```

**Comment by Tflowers-0129** [comment]
这个问题已经解决了 @Nagisa125  能否提供解决的PR或者版本参考

**Comment by Nagisa125** [comment]
自动化回复：OOM 修复已合入 v0.11.0rc1 及之后版本，相关 PR：#3305（Ascend config init）和 #3557。建议使用最新正式版本，将 `--gpu-memory-utilization` 设为 0.5 可进一步降低 OOM 风险。
