### ISSUE TITLE
[Bug]: Qwen3 235B RL Training: multi-level graph compilation process in full-graph mode hangs

### ISSUE THREAD

**Issue by johnjunjun7** [vllm-project/vllm-ascend#3413]
### Your current environment

<details> 
<summary>The output of `python collect_env.py`</summary>

```text
using vllm code and vllm-ascend code commit ID:
vllm-ascend: d01fd1d1c3526ef038f05edc2464a1e77dfb200d
vllm: f225ea7dd98e9f29752e5c032cd4a8ee1d712f16
The image used is the main-a3 image from September 23 provided by the official vLLM-Ascend repository on quay.io
```

</details>
When running the Qwen3-235B model under the veRL framework, which utilizes the vLLM-Ascend backend for inference with full-graph mode enabled, we encounter a hang/freeze issue during the multi-level graph compilation process. A single machine can compile and run the Qwen3-30B model without issues, but in a multi-machine setup for the Qwen3-235B model, the graph compilation process hangs after successfully compiling just one graph.

### 🐛 Describe the bug

[Codes]:
self.inference_engine = LLM(
            model=model_path,
            enable_sleep_mode=True,
            tensor_parallel_size=tensor_parallel_size,
            distributed_executor_backend="external_launcher",
            dtype=config.dtype,
            enforce_eager=config.enforce_eager,
            gpu_memory_utilization=config.gpu_memory_utilization,
            disable_custom_all_reduce=True,
            enable_expert_parallel=True,
            skip_tokenizer_init=False,
            max_model_len=max_model_len,
            max_num_seqs=config.max_num_seqs,
            load_format=load_format,
            disable_log_stats=config.disable_log_stats,
            max_num_batched_tokens=max_num_batched_tokens,
            enable_chunked_prefill=config.enable_chunked_prefill,
            enable_prefix_caching=False,
            trust_remote_code=trust_remote_code,
            seed=config.get("seed", 0),
            additional_config={
                "torchair_graph_config": {
                    "enable_frozen_parameter": False,
                },
                "ascend_scheduler_config": {
                    "enabled": True,
                    "enable_chunked_prefill": True,
                },
                "refresh": True,
            },
            compilation_config={
                "cudagraph_capture_sizes": [4, 8, 16, 32, 64, 128, 256],
                "cudagraph_mode": "FULL_DECODE_ONLY",
            },
            **lora_kwargs,
            **engine_kwargs,
        )

[Errors]:

[36m(WorkerDict pid=23510)[0m INFO 10-11 14:54:02 [kv_cache_utils.py:1091] Maximum concurrency for 34,816 tokens per request: 25.17x
[36m(WorkerDict pid=23511)[0m INFO 10-11 14:54:02 [kv_cache_utils.py:1087] GPU KV cache size: 876,416 tokens
[36m(WorkerDict pid=23511)[0m INFO 10-11 14:54:02 [kv_cache_utils.py:1091] Maximum concurrency for 34,816 tokens per request: 25.17x
[36m(WorkerDict pid=2963, ip=172.16.3.196)[0m INFO 10-11 14:54:02 [model_runner_v1.py:3384] Starting to capture ACL graphs for cases: [256, 128, 64, 32, 16, 8, 4], mode: FULL, uniform_decode: True
[36m(WorkerDict pid=2963, ip=172.16.3.196)[0m 
Capturing ACL graphs (decode, FULL):   0%|          | 0/7 [00:00<?, ?it/s]
[36m(WorkerDict pid=2968, ip=172.16.3.196)[0m [rank5]:[W1011 14:54:05.900183195 compiler_depend.ts:149] Warning: Waiting for pending NCCL work to finish before starting graph capture. (function operator())
[36m(WorkerDict pid=2963, ip=172.16.3.196)[0m 
Capturing ACL graphs (decode, FULL):  14%|█▍        | 1/7 [00:03<00:21,  3.67s/it]
time="2025-10-11T22:56:07+08:00" level=info msg="analyzer is diagnosing" file="analyzer.go:308" Command=analyze Component=ma-training-toolkit Container=modelarts-training-sidecar Platform=ModelArts-Service
time="2025-10-11T22:56:07+08:00" level=info msg="time required for conclude： 90 ms" file="analyzer.go:416" Command=analyze Component=ma-training-toolkit Container=modelarts-training-sidecar Platform=ModelArts-Service
time="2025-10-11T23:06:07+08:00" level=info msg="analyzer is diagnosing" file="analyzer.go:308" Command=analyze Component=ma-training-toolkit Container=modelarts-training-sidecar Platform=ModelArts-Service
time="2025-10-11T23:06:08+08:00" level=info msg="time required for conclude： 92 ms" file="analyzer.go:416" Command=analyze Component=ma-training-toolkit Container=modelarts-training-sidecar Platform=ModelArts-Service
time="2025-10-11T23:06:39+08:00" level=info msg="auth file has been updated" file="authentication.go:139" Command=obs/upload_by_channels Component=ma-training-toolkit Container=modelarts-training-sidecar Platform=ModelArts-Service Task=log_url
time="2025-10-11T23:06:39+08:00" level=info msg="auth file has been updated" file="authentication.go:139" Command=obs/upload_by_channels Component=ma-training-toolkit Container=modelarts-training-sidecar Platform=ModelArts-Service Task=srt_log_collection
time="2025-10-11T23:06:40+08:00" level=info msg="auth info has been updated" file="authentication.go:157" Command=obs/upload_by_channels Component=ma-training-toolkit Container=modelarts-training-sidecar Platform=ModelArts-Service Task=srt_log_collection
time="2025-10-11T23:06:40+08:00" level=info msg="obs client has been updated" file="upload.go:212" Command=obs/upload_by_channels Component=ma-training-toolkit Container=modelarts-training-sidecar Platform=ModelArts-Service Task=srt_log_collection
time="2025-10-11T23:06:41+08:00" level=warning msg="refresh rclone config failed: enableRclone is false " file="authentication.go:154" Command=obs/upload_by_channels Component=ma-training-toolkit Container=modelarts-training-sidecar Platform=ModelArts-Service Task=log_url
time="2025-10-11T23:06:41+08:00" level=info msg="auth info has been updated" file="authentication.go:157" Command=obs/upload_by_channels Component=ma-training-toolkit Container=modelarts-training-sidecar Platform=ModelArts-Service Task=log_url
time="2025-10-11T23:06:41+08:00" level=info msg="obs client has been updated" file="upload.go:212" Command=obs/upload_by_channels Component=ma-training-toolkit Container=modelarts-training-sidecar Platform=ModelArts-Service Task=log_url
Error executing job with overrides: ['algorithm.adv_estimator=grpo', 'data.train_files=/home/ma-user/modelarts/user-job-dir/veRL-cann/data/deepscaler/train.parquet', 'data.val_files=/home/ma-user/modelarts/user-job-dir/veRL-cann/data/deepscaler/valid.parquet', 'data.train_batch_size=512', 'data.max_prompt_length=2048', 'data.max_response_length=32768', 'data.filter_overlong_prompts=True', 'data.truncation=error', 'data.shuffle=False', 'custom_reward_function.path=recipe/r1_npu/deepscaler.py', 'custom_reward_function.name=compute_score', 'actor_rollout_ref.model.path=/home/ma-user/modelarts/user-job-dir/veRL-cann/Qwen3-235B-A22B-hf', 'actor_rollout_ref.actor.optim.lr=1e-6', 'actor_rollout_ref.actor.optim.clip_grad=10000', 'actor_rollout_ref.actor.ppo_mini_batch_size=512', 'actor_rollout_ref.actor.ppo_micro_batch_size_per_gpu=1', 'actor_rollout_ref.actor.megatron.sequence_parallel=True', 'actor_rollout_ref.actor.megatron.tensor_model_parallel_size=4', 'actor_rollout_ref.actor.megatron.pipeline_model_parallel_size=4', 'actor_rollout_ref.actor.megatron.context_parallel_size=4', 'actor_rollout_ref.actor.megatron.expert_model_parallel_size=32', 'actor_rollout_ref.actor.megatron.expert_tensor_parallel_size=1', 'actor_rollout_ref.actor.megatron.param_offload=True', 'actor_rollout_ref.actor.megatron.grad_offload=True', 'actor_rollout_ref.actor.megatron.optimizer_offload=False', 'actor_rollout_ref.actor.use_kl_loss=True', 'actor_rollout_ref.actor.kl_loss_coef=0.001', 'actor_rollout_ref.actor.kl_loss_type=low_var_kl', 'actor_rollout_ref.actor.load_weight=True', 'actor_rollout_ref.actor.megatron.use_dist_checkpointing=True', 'actor_rollout_ref.actor.megatron.dist_checkpointing_path=/home/ma-user/modelarts/inputs/data_url_0', 'actor_rollout_ref.actor.use_dynamic_bsz=True', 'actor_rollout_ref.actor.ppo_max_token_len_per_gpu=8704', 'actor_rollout_ref.actor.recompute_old_log_prob=False', 'actor_rollout_ref.rollout.log_prob_micro_batch_size_per_gpu=4', 'actor_rollout_ref.rollout.tensor_model_parallel_size=4', 'actor_rollout_ref.rollout.name=vllm', 'actor_rollout_ref.rollout.gpu_memory_utilization=0.85', 'actor_rollout_ref.rollout.max_num_batched_tokens=2048', 'actor_rollout_ref.rollout.enable_chunked_prefill=True', 'actor_rollout_ref.rollout.enforce_eager=False', 'actor_rollout_ref.rollout.max_num_seqs=256', 'actor_rollout_ref.rollout.n=16', 'actor_rollout_ref.rollout.temperature=0.9', 'actor_rollout_ref.rollout.top_k=50', 'actor_rollout_ref.rollout.top_p=0.9', 'actor_rollout_ref.rollout.ignore_eos=False', 'actor_rollout_ref.ref.log_prob_micro_batch_size_per_gpu=8', 'actor_rollout_ref.ref.megatron.param_offload=True', 'actor_rollout_ref.ref.load_weight=True', 'actor_rollout_ref.ref.megatron.use_dist_checkpointing=True', 'actor_rollout_ref.ref.megatron.dist_checkpointing_path=/home/ma-user/modelarts/inputs/data_url_0', 'actor_rollout_ref.ref.megatron.context_parallel_size=4', 'algorithm.kl_ctrl.kl_coef=0.001', 'trainer.balance_batch=False', 'trainer.device=npu', 'trainer.val_before_train=False', 'trainer.critic_warmup=0', 'trainer.logger=[console,tensorboard]', 'trainer.project_name=verl_grpo_example_gsm8k', 'trainer.experiment_name=qwen3_255b_verl_mindspeedllm_vllm', 'trainer.n_gpus_per_node=16', 'trainer.nnodes=8', 'trainer.save_freq=-1', 'trainer.test_freq=5', 'trainer.total_epochs=1', '+actor_rollout_ref.actor.megatron.override_transformer_config.seq_length=2048', '+actor_rollout_ref.actor.megatron.override_transformer_config.swap_optimizer=True', '+actor_rollout_ref.actor.megatron.override_transformer_config.pipeline_num_transformer_layers=[[23],[24],[24],[23]]', '+actor_rollout_ref.actor.megatron.override_transformer_config.num_layers_in_first_pipeline_stage=23', '+actor_rollout_ref.actor.megatron.override_transformer_config.num_layers_in_last_pipeline_stage=23', '+actor_rollout_ref.actor.megatron.override_transformer_config.use_flash_attn=True', '+actor_rollout_ref.actor.megatron.override_transformer_config.use_fused_rotary_pos_emb=True', '+actor_rollout_ref.actor.megatron.override_transformer_config.use_fused_swiglu=True', '+actor_rollout_ref.actor.megatron.override_transformer_config.context_parallel_size=4', '+actor_rollout_ref.actor.megatron.override_transformer_config.use_cp_send_recv_overlap=True', '+actor_rollout_ref.actor.megatron.override_transformer_config.context_parallel_algo=megatron_cp_algo', '+actor_rollout_ref.actor.megatron.override_transformer_config.use_fused_ring_attention_update=True', '+actor_rollout_ref.actor.megatron.override_transformer_config.cp_window_size=1', '+actor_rollout_ref.actor.megatron.override_transformer_config.moe_token_dispatcher_type=alltoall', '+actor_rollout_ref.actor.megatron.override_transformer_config.moe_alltoall_overlap_comm=True', '+actor_rollout_ref.actor.megatron.override_transformer_config.moe_grouped_gemm=True', '+actor_rollout_ref.actor.megatron.override_transformer_config.moe_zero_memory=level1', '+actor_rollout_ref.actor.megatron.override_transformer_config.moe_permute_fusion=True', '+actor_rollout_ref.actor.megatron.override_transformer_config.gemm_gradient_accumulation_fusion=True']
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/ma-user/modelarts/user-job-dir/veRL-cann/recipe/r1_npu/main_ppo.py", line 390, in <module>
    main()
  File "/usr/local/python3.11.13/lib/python3.11/site-packages/hydra/main.py", line 94, in decorated_main
    _run_hydra(
  File "/usr/local/python3.11.13/lib/python3.11/site-packages/hydra/_internal/utils.py", line 394, in _run_hydra
    _run_app(
  File "/usr/local/python3.11.13/lib/python3.11/site-packages/hydra/_internal/utils.py", line 457, in _run_app
    run_and_report(
  File "/usr/local/python3.11.13/lib/python3.11/site-packages/hydra/_internal/utils.py", line 223, in run_and_report
    raise ex
  File "/usr/local/python3.11.13/lib/python3.11/site-packages/hydra/_internal/utils.py", line 220, in run_and_report
    return func()
           ^^^^^^
  File "/usr/local/python3.11.13/lib/python3.11/site-packages/hydra/_internal/utils.py", line 458, in <lambda>
    lambda: hydra.run(
            ^^^^^^^^^^
  File "/usr/local/python3.11.13/lib/python3.11/site-packages/hydra/_internal/hydra.py", line 132, in run
    _ = ret.return_value
        ^^^^^^^^^^^^^^^^
  File "/usr/local/python3.11.13/lib/python3.11/site-packages/hydra/core/utils.py", line 260, in return_value
    raise self._return_value
  File "/usr/local/python3.11.13/lib/python3.11/site-packages/hydra/core/utils.py", line 186, in run_job
    ret.return_value = task_function(task_cfg)
                       ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ma-user/modelarts/user-job-dir/veRL-cann/recipe/r1_npu/main_ppo.py", line 42, in main
    run_ppo(config)
  File "/home/ma-user/modelarts/user-job-dir/veRL-cann/recipe/r1_npu/main_ppo.py", line 85, in run_ppo
    ray.get(runner.run.remote(config))
  File "/usr/local/python3.11.13/lib/python3.11/site-packages/ray/_private/auto_init_hook.py", line 22, in auto_init_wrapper
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/python3.11.13/lib/python3.11/site-packages/ray/_private/client_mode_hook.py", line 104, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/python3.11.13/lib/python3.11/site-packages/ray/_private/worker.py", line 2882, in get
    values, debugger_breakpoint = worker.get_objects(object_refs, timeout=timeout)
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/python3.11.13/lib/python3.11/site-packages/ray/_private/worker.py", line 968, in get_objects
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(RuntimeError): [36mray::TaskRunner.run()[39m (pid=13939, ip=172.16.5.166, actor_id=858cd635f459f166241d5c3301000000, repr=<main_ppo.TaskRunner object at 0xffff8cdedad0>)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ma-user/modelarts/user-job-dir/veRL-cann/recipe/r1_npu/main_ppo.py", line 292, in run
    trainer.init_workers()
  File "/home/ma-user/modelarts/user-job-dir/veRL-cann/verl/trainer/ppo/ray_trainer.py", line 729, in init_workers
    self.actor_rollout_wg.init_model()
  File "/home/ma-user/modelarts/user-job-dir/veRL-cann/verl/single_controller/ray/base.py", line 48, in __call__
    output = ray.get(output)
             ^^^^^^^^^^^^^^^
           ^^^^^^^^^^^^^^^^^^^
           ^^^^^^^^^^^^^^^^^^^^^
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ray.exceptions.RayTaskError(RuntimeError): [36mray::WorkerDict.actor_rollout_init_model()[39m (pid=2969, ip=172.16.5.149, actor_id=ad1b7721665d07e3c70db30101000000, repr=<verl.single_controller.ray.base.WorkerDict object at 0xffcf8ee0c510>)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ma-user/modelarts/user-job-dir/veRL-cann/verl/single_controller/ray/base.py", line 701, in func
    return getattr(self.worker_dict[key], name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ma-user/modelarts/user-job-dir/veRL-cann/verl/single_controller/base/decorator.py", line 430, in inner
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/ma-user/modelarts/user-job-dir/veRL-cann/verl/workers/megatron_workers.py", line 534, in init_model
    self.rollout, self.sharding_manager = self._build_rollout(
                                          ^^^^^^^^^^^^^^^^^^^^
  File "/home/ma-user/modelarts/user-job-dir/veRL-cann/recipe/r1_npu/megatron_workers.py", line 59, in _build_rollout
    rollout = vllm_rollout_cls(
              ^^^^^^^^^^^^^^^^^
  File "/home/ma-user/modelarts/user-job-dir/veRL-cann/recipe/r1_npu/vllm_rollout_spmd.py", line 163, in __init__
    self.inference_engine = LLM(
                            ^^^^
  File "/home/ma-user/modelarts/user-job-dir/veRL-cann/vllm/entrypoints/llm.py", line 322, in __init__
    self.llm_engine = LLMEngine.from_engine_args(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ma-user/modelarts/user-job-dir/veRL-cann/vllm/v1/engine/llm_engine.py", line 177, in from_engine_args
    return cls(vllm_config=vllm_config,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ma-user/modelarts/user-job-dir/veRL-cann/vllm/v1/engine/llm_engine.py", line 118, in __init__
    self.engine_core = EngineCoreClient.make_client(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ma-user/modelarts/user-job-dir/veRL-cann/vllm/v1/engine/core_client.py", line 82, in make_client
    return InprocClient(vllm_config, executor_class, log_stats)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ma-user/modelarts/user-job-dir/veRL-cann/vllm/v1/engine/core_client.py", line 245, in __init__
    self.engine_core = EngineCore(*args, **kwargs)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ma-user/modelarts/user-job-dir/veRL-cann/vllm/v1/engine/core.py", line 92, in __init__
    self._initialize_kv_caches(vllm_config)
  File "/home/ma-user/modelarts/user-job-dir/veRL-cann/vllm/v1/engine/core.py", line 207, in _initialize_kv_caches
    self.model_executor.initialize_from_config(kv_cache_configs)
  File "/home/ma-user/modelarts/user-job-dir/veRL-cann/vllm/v1/executor/abstract.py", line 75, in initialize_from_config
    self.collective_rpc("compile_or_warm_up_model")
  File "/home/ma-user/modelarts/user-job-dir/veRL-cann/vllm/executor/uniproc_executor.py", line 83, in collective_rpc
    return [run_method(self.driver_worker, method, args, kwargs)]
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ma-user/modelarts/user-job-dir/veRL-cann/vllm/utils/__init__.py", line 3010, in run_method
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/ma-user/modelarts/user-job-dir/veRL-cann/vllm_ascend/worker/worker_v1.py", line 284, in compile_or_warm_up_model
    self.model_runner.capture_model()
  File "/home/ma-user/modelarts/user-job-dir/veRL-cann/vllm_ascend/worker/model_runner_v1.py", line 3465, in capture_model
    self._capture_model()
  File "/home/ma-user/modelarts/user-job-dir/veRL-cann/vllm_ascend/worker/model_runner_v1.py", line 3446, in _capture_model
    self._capture_aclgraphs(
  File "/home/ma-user/modelarts/user-job-dir/veRL-cann/vllm_ascend/worker/model_runner_v1.py", line 3403, in _capture_aclgraphs
    self._dummy_run(num_tokens,
  File "/usr/local/python3.11.13/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/ma-user/modelarts/user-job-dir/veRL-cann/vllm_ascend/worker/model_runner_v1.py", line 2369, in _dummy_run
    _) = self._sync_metadata_across_dp(num_tokens, with_prefill, False)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ma-user/modelarts/user-job-dir/veRL-cann/vllm_ascend/worker/model_runner_v1.py", line 836, in _sync_metadata_across_dp
    max_tokens_across_dp = torch.max(num_tokens_across_dp).item()
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: operator():build/CMakeFiles/torch_npu.dir/compiler_depend.ts:47 NPU function error: c10_npu::acl::AclrtSynchronizeStreamWithTimeout(copy_stream), error code is 107020
[ERROR] 2025-10-11-15:09:34 (PID:2969, Device:0, RankID:101) ERR00100 PTA call acl api failed.
EI0002: [PID: 2969] 2025-10-11-15:09:34.713.335 The wait execution of the Notify register times out. Reason: The Notify register has not received the Notify record from remote rank: [24]. base information: [streamID:[109], taskID[38], taskType[Notify Wait], tag[AllReduce_group_name_1654NHRAllReduceComm_device], AlgType(level 0-1-2):[ring-NHR-NHR].]. task information: [notify id:[0x0000000000000213], stage:[0], remote rank:[24]]. group information: [group:[group_name_1654], user define information[Unspecified], rankSize[32], rankId[25 24]]
        Possible Cause: 1. An exception occurs during the execution on some NPUs in the cluster. As a result, collective communication operation failed.2. The execution speed on some NPU in the cluster is too slow to complete a communication operation within the timeout interval. (default 1800s, You can set the interval by using HCCL_EXEC_TIMEOUT.)3. The number of training samples of each NPU is inconsistent.4. Packet loss or other connectivity problems occur on the communication link.
        Solution: 1. If this error is reported on part of these ranks, check other ranks to see whether other errors have been reported earlier.2. If this error is reported for all ranks, check whether the error reporting time is consistent (the maximum difference must not exceed 1800s). If not, locate the cause or adjust the locate the cause or set the HCCL_EXEC_TIMEOUT environment variable to a larger value.3. Check whether the completion queue element (CQE) of the error exists in the plog(grep -rn 'error cqe'). If so, check the network connection status. 4. Ensure that the number of training samples of each NPU is consistent.
        TraceBack (most recent call last):
        The error from device(chipId:2, dieId:1), serial number is 148, notify wait timeout occurred during task execution, stream_id:25, sq_id:25, task_id:17, notify_id=537, timeout=927s.[FUNC:ProcessStarsWaitTimeoutErrorInfo][FILE:device_error_proc.cc][LINE:1394]
        The error from device(chipId:2, dieId:1), serial number is 149, notify wait timeout occurred during task execution, stream_id:109, sq_id:109, task_id:38, notify_id=531, timeout=900s.[FUNC:ProcessStarsWaitTimeoutErrorInfo][FILE:device_error_proc.cc][LINE:1394]
        Error task from the device stream.[FUNC:ProcessStarsWaitTimeoutErrorInfo][FILE:device_error_proc.cc][LINE:1409]
        The wait execution of the Notify register times out. Reason: The Notify register has not received the Notify record from remote rank: [24]. base information: [streamID:[109], taskID[38], taskType[Notify Wait], tag[AllReduce_group_name_1654NHRAllReduceComm_device], AlgType(level 0-1-2):[ring-NHR-NHR].]. task information: [notify id:[0x0000000000000213], stage:[0], remote rank:[24]]. group information: [group:[group_name_1654], user define information[Unspecified], rankSize[32], rankId[25 24]]
        rtStreamSynchronizeWithTimeout execute failed, reason=[task timeout][FUNC:FuncErrorReason][FILE:error_message_manage.cc][LINE:53]
        synchronize stream failed, runtime result = 107020[FUNC:ReportCallError][FILE:log_inner.cpp][LINE:161]

**Comment by Tflowers-0129** [comment]
@yiz-liu pls take a look

**Comment by yiz-liu** [comment]
I think we have solved this last year and please try the latest version, feel free to create another issue if the problem persists.
