### ISSUE TITLE
[Bug]: vllm-ascend-0.11.0rc0 部署qwen3-vl-30b-a3b，请求消息带视频，报错。

### ISSUE THREAD

**Issue by chenm202501** [vllm-project/vllm-ascend#3468]
### Your current environment

Atlas 800I A2
vLLM-Ascend 0.11.0rc0
Qwen3-VL-30B-A3B-Instruct

```
docker run \
  --name houmong-qwen3-vl-30b-a3b \
  --device /dev/davinci6 \
  --device /dev/davinci7 \
  --device /dev/davinci_manager \
  --device /dev/devmm_svm \
  --device /dev/hisi_hdc \
  -e VLLM_USE_MODELSCOPE=true \
  -v /usr/local/dcmi:/usr/local/dcmi \
  -v /usr/local/bin/npu-smi:/usr/local/bin/npu-smi \
  -v /usr/local/Ascend/driver/lib64/:/usr/local/Ascend/driver/lib64/ \
  -v /usr/local/Ascend/driver/version.info:/usr/local/Ascend/driver/version.info \
  -v /etc/ascend_install.info:/etc/ascend_install.info \
  -v /opt/models:/root/.cache \
  -v /opt/houmong/run_docker/vllm-qwen3-vl-30b-a3b:/workspace \
  -v /opt/houmong/emp/emp-imcp-core/media:/media \
  -p 30115:8000 \
  -itd quay.io/ascend/vllm-ascend:v0.11.0rc0-transformers-4.57.0 \
  vllm serve /root/.cache/models/Qwen/Qwen3-VL-30B-A3B-Instruct \
  --served-model-name Qwen/Qwen3-VL-30B-A3B-Instruct \
  --tensor-parallel-size 2 \
  --enable_expert_parallel \
  --max-model-len 40960 \
  --allowed-local-media-path /media
```

请求消息：

```
{
    "model": "Qwen/Qwen3-VL-30B-A3B-Instruct",
    "enable_thinking": true,
    "thinking_budget": true,
    "stream": true,
    "messages": [
        {
            "role": "user",
            "content": [
                {
                    "type": "video_url",
                    "video_url": {
                        "url": "file:///media/test4.mp4"
                    }
                },
                {
                    "type": "text",
                    "text": "逐帧分析提供的视频，找出所有白色汽车驶入画面时距离视频开始经过的秒数，输出json列表，每项包括以下字段：begin，取值为整型数值，表示距离视频开始经过的秒数；content，简要描述车辆的概况（车辆颜色、类型、品牌型号、车牌等）"
                }
            ]
        }
    ]
}
```

### 🐛 Describe the bug

报错如下：

(Worker_TP1_EP1 pid=551) ERROR 10-15 03:21:23 [multiproc_executor.py:671] WorkerProc hit an exception.
(Worker_TP1_EP1 pid=551) ERROR 10-15 03:21:23 [multiproc_executor.py:671] Traceback (most recent call last):
(Worker_TP1_EP1 pid=551) ERROR 10-15 03:21:23 [multiproc_executor.py:671]   File "/vllm-workspace/vllm/vllm/v1/executor/multiproc_executor.py", line 666, in worker_busy_loop
(Worker_TP1_EP1 pid=551) ERROR 10-15 03:21:23 [multiproc_executor.py:671]     output = func(*args, **kwargs)
(Worker_TP1_EP1 pid=551) ERROR 10-15 03:21:23 [multiproc_executor.py:671]              ^^^^^^^^^^^^^^^^^^^^^
(Worker_TP1_EP1 pid=551) ERROR 10-15 03:21:23 [multiproc_executor.py:671]   File "/vllm-workspace/vllm-ascend/vllm_ascend/worker/worker_v1.py", line 254, in execute_model
(Worker_TP1_EP1 pid=551) ERROR 10-15 03:21:23 [multiproc_executor.py:671]     output = self.model_runner.execute_model(scheduler_output,
(Worker_TP1_EP1 pid=551) ERROR 10-15 03:21:23 [multiproc_executor.py:671]              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(Worker_TP1_EP1 pid=551) ERROR 10-15 03:21:23 [multiproc_executor.py:671]   File "/usr/local/python3.11.13/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
(Worker_TP1_EP1 pid=551) ERROR 10-15 03:21:23 [multiproc_executor.py:671]     return func(*args, **kwargs)
(Worker_TP1_EP1 pid=551) ERROR 10-15 03:21:23 [multiproc_executor.py:671]            ^^^^^^^^^^^^^^^^^^^^^
(Worker_TP1_EP1 pid=551) ERROR 10-15 03:21:23 [multiproc_executor.py:671]   File "/vllm-workspace/vllm-ascend/vllm_ascend/worker/model_runner_v1.py", line 2030, in execute_model
(Worker_TP1_EP1 pid=551) ERROR 10-15 03:21:23 [multiproc_executor.py:671]     sampler_output = self.sampler(
(Worker_TP1_EP1 pid=551) ERROR 10-15 03:21:23 [multiproc_executor.py:671]                      ^^^^^^^^^^^^^
(Worker_TP1_EP1 pid=551) ERROR 10-15 03:21:23 [multiproc_executor.py:671]   File "/usr/local/python3.11.13/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
(Worker_TP1_EP1 pid=551) ERROR 10-15 03:21:23 [multiproc_executor.py:671]     return self._call_impl(*args, **kwargs)
(Worker_TP1_EP1 pid=551) ERROR 10-15 03:21:23 [multiproc_executor.py:671]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(Worker_TP1_EP1 pid=551) ERROR 10-15 03:21:23 [multiproc_executor.py:671]   File "/usr/local/python3.11.13/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1762, in _call_impl
(Worker_TP1_EP1 pid=551) ERROR 10-15 03:21:23 [multiproc_executor.py:671]     return forward_call(*args, **kwargs)
(Worker_TP1_EP1 pid=551) ERROR 10-15 03:21:23 [multiproc_executor.py:671]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(Worker_TP1_EP1 pid=551) ERROR 10-15 03:21:23 [multiproc_executor.py:671]   File "/vllm-workspace/vllm/vllm/v1/sample/sampler.py", line 100, in forward
(Worker_TP1_EP1 pid=551) ERROR 10-15 03:21:23 [multiproc_executor.py:671]     sampled, processed_logprobs = self.sample(logits, sampling_metadata)
(Worker_TP1_EP1 pid=551) ERROR 10-15 03:21:23 [multiproc_executor.py:671]                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(Worker_TP1_EP1 pid=551) ERROR 10-15 03:21:23 [multiproc_executor.py:671]   File "/vllm-workspace/vllm/vllm/v1/sample/sampler.py", line 180, in sample
(Worker_TP1_EP1 pid=551) ERROR 10-15 03:21:23 [multiproc_executor.py:671]     random_sampled, processed_logprobs = self.topk_topp_sampler(
(Worker_TP1_EP1 pid=551) ERROR 10-15 03:21:23 [multiproc_executor.py:671]                                          ^^^^^^^^^^^^^^^^^^^^^^^
(Worker_TP1_EP1 pid=551) ERROR 10-15 03:21:23 [multiproc_executor.py:671]   File "/usr/local/python3.11.13/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
(Worker_TP1_EP1 pid=551) ERROR 10-15 03:21:23 [multiproc_executor.py:671]     return self._call_impl(*args, **kwargs)
(Worker_TP1_EP1 pid=551) ERROR 10-15 03:21:23 [multiproc_executor.py:671]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(Worker_TP1_EP1 pid=551) ERROR 10-15 03:21:23 [multiproc_executor.py:671]   File "/usr/local/python3.11.13/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1762, in _call_impl
(Worker_TP1_EP1 pid=551) ERROR 10-15 03:21:23 [multiproc_executor.py:671]     return forward_call(*args, **kwargs)
(Worker_TP1_EP1 pid=551) ERROR 10-15 03:21:23 [multiproc_executor.py:671]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(Worker_TP1_EP1 pid=551) ERROR 10-15 03:21:23 [multiproc_executor.py:671]   File "/vllm-workspace/vllm-ascend/vllm_ascend/sample/sampler.py", line 70, in forward_native
(Worker_TP1_EP1 pid=551) ERROR 10-15 03:21:23 [multiproc_executor.py:671]     logits = self._apply_top_k_top_p(logits, k, p)
(Worker_TP1_EP1 pid=551) ERROR 10-15 03:21:23 [multiproc_executor.py:671]              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(Worker_TP1_EP1 pid=551) ERROR 10-15 03:21:23 [multiproc_executor.py:671]   File "/vllm-workspace/vllm-ascend/vllm_ascend/sample/sampler.py", line 32, in _apply_top_k_top_p
(Worker_TP1_EP1 pid=551) ERROR 10-15 03:21:23 [multiproc_executor.py:671]     if not is_310p() and p is not None and k is not None and 1 <= int(
(Worker_TP1_EP1 pid=551) ERROR 10-15 03:21:23 [multiproc_executor.py:671]                                                                   ^^^^
(Worker_TP1_EP1 pid=551) ERROR 10-15 03:21:23 [multiproc_executor.py:671] RuntimeError: The Inner error is reported as above. The process exits for this inner error, and the current working operator name is aclnnSwiGlu.
(Worker_TP1_EP1 pid=551) ERROR 10-15 03:21:23 [multiproc_executor.py:671] Since the operator is called asynchronously, the stacktrace may be inaccurate. If you want to get the accurate stacktrace, please set the environment variable ASCEND_LAUNCH_BLOCKING=1.
(Worker_TP1_EP1 pid=551) ERROR 10-15 03:21:23 [multiproc_executor.py:671] Note: ASCEND_LAUNCH_BLOCKING=1 will force ops to run in synchronous mode, resulting in performance degradation. Please unset ASCEND_LAUNCH_BLOCKING in time after debugging.
(Worker_TP1_EP1 pid=551) ERROR 10-15 03:21:23 [multiproc_executor.py:671] [ERROR] 2025-10-15-03:21:23 (PID:551, Device:1, RankID:-1) ERR00100 PTA call acl api failed.
(Worker_TP1_EP1 pid=551) ERROR 10-15 03:21:23 [multiproc_executor.py:671]
(Worker_TP1_EP1 pid=551) ERROR 10-15 03:21:23 [multiproc_executor.py:671] Traceback (most recent call last):
(Worker_TP1_EP1 pid=551) ERROR 10-15 03:21:23 [multiproc_executor.py:671]   File "/vllm-workspace/vllm/vllm/v1/executor/multiproc_executor.py", line 666, in worker_busy_loop
(Worker_TP1_EP1 pid=551) ERROR 10-15 03:21:23 [multiproc_executor.py:671]     output = func(*args, **kwargs)
(Worker_TP1_EP1 pid=551) ERROR 10-15 03:21:23 [multiproc_executor.py:671]              ^^^^^^^^^^^^^^^^^^^^^
(Worker_TP1_EP1 pid=551) ERROR 10-15 03:21:23 [multiproc_executor.py:671]   File "/vllm-workspace/vllm-ascend/vllm_ascend/worker/worker_v1.py", line 254, in execute_model
(Worker_TP1_EP1 pid=551) ERROR 10-15 03:21:23 [multiproc_executor.py:671]     output = self.model_runner.execute_model(scheduler_output,
(Worker_TP1_EP1 pid=551) ERROR 10-15 03:21:23 [multiproc_executor.py:671]              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(Worker_TP1_EP1 pid=551) ERROR 10-15 03:21:23 [multiproc_executor.py:671]   File "/usr/local/python3.11.13/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
(Worker_TP1_EP1 pid=551) ERROR 10-15 03:21:23 [multiproc_executor.py:671]     return func(*args, **kwargs)
(Worker_TP1_EP1 pid=551) ERROR 10-15 03:21:23 [multiproc_executor.py:671]            ^^^^^^^^^^^^^^^^^^^^^
(Worker_TP1_EP1 pid=551) ERROR 10-15 03:21:23 [multiproc_executor.py:671]   File "/vllm-workspace/vllm-ascend/vllm_ascend/worker/model_runner_v1.py", line 2030, in execute_model
(Worker_TP1_EP1 pid=551) ERROR 10-15 03:21:23 [multiproc_executor.py:671]     sampler_output = self.sampler(
(Worker_TP1_EP1 pid=551) ERROR 10-15 03:21:23 [multiproc_executor.py:671]                      ^^^^^^^^^^^^^
(Worker_TP1_EP1 pid=551) ERROR 10-15 03:21:23 [multiproc_executor.py:671]   File "/usr/local/python3.11.13/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
(Worker_TP1_EP1 pid=551) ERROR 10-15 03:21:23 [multiproc_executor.py:671]     return self._call_impl(*args, **kwargs)
(Worker_TP1_EP1 pid=551) ERROR 10-15 03:21:23 [multiproc_executor.py:671]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(Worker_TP1_EP1 pid=551) ERROR 10-15 03:21:23 [multiproc_executor.py:671]   File "/usr/local/python3.11.13/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1762, in _call_impl
(Worker_TP1_EP1 pid=551) ERROR 10-15 03:21:23 [multiproc_executor.py:671]     return forward_call(*args, **kwargs)
(Worker_TP1_EP1 pid=551) ERROR 10-15 03:21:23 [multiproc_executor.py:671]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(Worker_TP1_EP1 pid=551) ERROR 10-15 03:21:23 [multiproc_executor.py:671]   File "/vllm-workspace/vllm/vllm/v1/sample/sampler.py", line 100, in forward
(Worker_TP1_EP1 pid=551) ERROR 10-15 03:21:23 [multiproc_executor.py:671]     sampled, processed_logprobs = self.sample(logits, sampling_metadata)
(Worker_TP1_EP1 pid=551) ERROR 10-15 03:21:23 [multiproc_executor.py:671]                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(Worker_TP1_EP1 pid=551) ERROR 10-15 03:21:23 [multiproc_executor.py:671]   File "/vllm-workspace/vllm/vllm/v1/sample/sampler.py", line 180, in sample
(Worker_TP1_EP1 pid=551) ERROR 10-15 03:21:23 [multiproc_executor.py:671]     random_sampled, processed_logprobs = self.topk_topp_sampler(
(Worker_TP1_EP1 pid=551) ERROR 10-15 03:21:23 [multiproc_executor.py:671]                                          ^^^^^^^^^^^^^^^^^^^^^^^
(Worker_TP1_EP1 pid=551) ERROR 10-15 03:21:23 [multiproc_executor.py:671]   File "/usr/local/python3.11.13/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
(Worker_TP1_EP1 pid=551) ERROR 10-15 03:21:23 [multiproc_executor.py:671]     return self._call_impl(*args, **kwargs)
(Worker_TP1_EP1 pid=551) ERROR 10-15 03:21:23 [multiproc_executor.py:671]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(Worker_TP1_EP1 pid=551) ERROR 10-15 03:21:23 [multiproc_executor.py:671]   File "/usr/local/python3.11.13/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1762, in _call_impl
(Worker_TP1_EP1 pid=551) ERROR 10-15 03:21:23 [multiproc_executor.py:671]     return forward_call(*args, **kwargs)
(Worker_TP1_EP1 pid=551) ERROR 10-15 03:21:23 [multiproc_executor.py:671]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(Worker_TP1_EP1 pid=551) ERROR 10-15 03:21:23 [multiproc_executor.py:671]   File "/vllm-workspace/vllm-ascend/vllm_ascend/sample/sampler.py", line 70, in forward_native
(Worker_TP1_EP1 pid=551) ERROR 10-15 03:21:23 [multiproc_executor.py:671]     logits = self._apply_top_k_top_p(logits, k, p)
(Worker_TP1_EP1 pid=551) ERROR 10-15 03:21:23 [multiproc_executor.py:671]              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(Worker_TP1_EP1 pid=551) ERROR 10-15 03:21:23 [multiproc_executor.py:671]   File "/vllm-workspace/vllm-ascend/vllm_ascend/sample/sampler.py", line 32, in _apply_top_k_top_p
(Worker_TP1_EP1 pid=551) ERROR 10-15 03:21:23 [multiproc_executor.py:671]     if not is_310p() and p is not None and k is not None and 1 <= int(
(Worker_TP1_EP1 pid=551) ERROR 10-15 03:21:23 [multiproc_executor.py:671]                                                                   ^^^^
(Worker_TP1_EP1 pid=551) ERROR 10-15 03:21:23 [multiproc_executor.py:671] RuntimeError: The Inner error is reported as above. The process exits for this inner error, and the current working operator name is aclnnSwiGlu.
(Worker_TP1_EP1 pid=551) ERROR 10-15 03:21:23 [multiproc_executor.py:671] Since the operator is called asynchronously, the stacktrace may be inaccurate. If you want to get the accurate stacktrace, please set the environment variable ASCEND_LAUNCH_BLOCKING=1.
(Worker_TP1_EP1 pid=551) ERROR 10-15 03:21:23 [multiproc_executor.py:671] Note: ASCEND_LAUNCH_BLOCKING=1 will force ops to run in synchronous mode, resulting in performance degradation. Please unset ASCEND_LAUNCH_BLOCKING in time after debugging.
(Worker_TP1_EP1 pid=551) ERROR 10-15 03:21:23 [multiproc_executor.py:671] [ERROR] 2025-10-15-03:21:23 (PID:551, Device:1, RankID:-1) ERR00100 PTA call acl api failed.
(Worker_TP1_EP1 pid=551) ERROR 10-15 03:21:23 [multiproc_executor.py:671]
(Worker_TP1_EP1 pid=551) ERROR 10-15 03:21:23 [multiproc_executor.py:671]
(Worker_TP0_EP0 pid=550) ERROR 10-15 03:21:24 [multiproc_executor.py:671] WorkerProc hit an exception.
(Worker_TP0_EP0 pid=550) ERROR 10-15 03:21:24 [multiproc_executor.py:671] Traceback (most recent call last):
(Worker_TP0_EP0 pid=550) ERROR 10-15 03:21:24 [multiproc_executor.py:671]   File "/vllm-workspace/vllm/vllm/v1/executor/multiproc_executor.py", line 666, in worker_busy_loop
(Worker_TP0_EP0 pid=550) ERROR 10-15 03:21:24 [multiproc_executor.py:671]     output = func(*args, **kwargs)
(Worker_TP0_EP0 pid=550) ERROR 10-15 03:21:24 [multiproc_executor.py:671]              ^^^^^^^^^^^^^^^^^^^^^
(Worker_TP0_EP0 pid=550) ERROR 10-15 03:21:24 [multiproc_executor.py:671]   File "/vllm-workspace/vllm-ascend/vllm_ascend/worker/worker_v1.py", line 254, in execute_model
(Worker_TP0_EP0 pid=550) ERROR 10-15 03:21:24 [multiproc_executor.py:671]     output = self.model_runner.execute_model(scheduler_output,
(Worker_TP0_EP0 pid=550) ERROR 10-15 03:21:24 [multiproc_executor.py:671]              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(Worker_TP0_EP0 pid=550) ERROR 10-15 03:21:24 [multiproc_executor.py:671]   File "/usr/local/python3.11.13/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
(Worker_TP0_EP0 pid=550) ERROR 10-15 03:21:24 [multiproc_executor.py:671]     return func(*args, **kwargs)
(Worker_TP0_EP0 pid=550) ERROR 10-15 03:21:24 [multiproc_executor.py:671]            ^^^^^^^^^^^^^^^^^^^^^
(Worker_TP0_EP0 pid=550) ERROR 10-15 03:21:24 [multiproc_executor.py:671]   File "/vllm-workspace/vllm-ascend/vllm_ascend/worker/model_runner_v1.py", line 2030, in execute_model
(Worker_TP0_EP0 pid=550) ERROR 10-15 03:21:24 [multiproc_executor.py:671]     sampler_output = self.sampler(
(Worker_TP0_EP0 pid=550) ERROR 10-15 03:21:24 [multiproc_executor.py:671]                      ^^^^^^^^^^^^^
(Worker_TP0_EP0 pid=550) ERROR 10-15 03:21:24 [multiproc_executor.py:671]   File "/usr/local/python3.11.13/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
(Worker_TP0_EP0 pid=550) ERROR 10-15 03:21:24 [multiproc_executor.py:671]     return self._call_impl(*args, **kwargs)
(Worker_TP0_EP0 pid=550) ERROR 10-15 03:21:24 [multiproc_executor.py:671]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(Worker_TP0_EP0 pid=550) ERROR 10-15 03:21:24 [multiproc_executor.py:671]   File "/usr/local/python3.11.13/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1762, in _call_impl
(Worker_TP0_EP0 pid=550) ERROR 10-15 03:21:24 [multiproc_executor.py:671]     return forward_call(*args, **kwargs)
(Worker_TP0_EP0 pid=550) ERROR 10-15 03:21:24 [multiproc_executor.py:671]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(Worker_TP0_EP0 pid=550) ERROR 10-15 03:21:24 [multiproc_executor.py:671]   File "/vllm-workspace/vllm/vllm/v1/sample/sampler.py", line 100, in forward
(Worker_TP0_EP0 pid=550) ERROR 10-15 03:21:24 [multiproc_executor.py:671]     sampled, processed_logprobs = self.sample(logits, sampling_metadata)
(Worker_TP0_EP0 pid=550) ERROR 10-15 03:21:24 [multiproc_executor.py:671]                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(Worker_TP0_EP0 pid=550) ERROR 10-15 03:21:24 [multiproc_executor.py:671]   File "/vllm-workspace/vllm/vllm/v1/sample/sampler.py", line 180, in sample
(Worker_TP0_EP0 pid=550) ERROR 10-15 03:21:24 [multiproc_executor.py:671]     random_sampled, processed_logprobs = self.topk_topp_sampler(
(Worker_TP0_EP0 pid=550) ERROR 10-15 03:21:24 [multiproc_executor.py:671]                                          ^^^^^^^^^^^^^^^^^^^^^^^
(Worker_TP0_EP0 pid=550) ERROR 10-15 03:21:24 [multiproc_executor.py:671]   File "/usr/local/python3.11.13/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
(Worker_TP0_EP0 pid=550) ERROR 10-15 03:21:24 [multiproc_executor.py:671]     return self._call_impl(*args, **kwargs)
(Worker_TP0_EP0 pid=550) ERROR 10-15 03:21:24 [multiproc_executor.py:671]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(Worker_TP0_EP0 pid=550) ERROR 10-15 03:21:24 [multiproc_executor.py:671]   File "/usr/local/python3.11.13/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1762, in _call_impl
(Worker_TP0_EP0 pid=550) ERROR 10-15 03:21:24 [multiproc_executor.py:671]     return forward_call(*args, **kwargs)
(Worker_TP0_EP0 pid=550) ERROR 10-15 03:21:24 [multiproc_executor.py:671]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(Worker_TP0_EP0 pid=550) ERROR 10-15 03:21:24 [multiproc_executor.py:671]   File "/vllm-workspace/vllm-ascend/vllm_ascend/sample/sampler.py", line 70, in forward_native
(Worker_TP0_EP0 pid=550) ERROR 10-15 03:21:24 [multiproc_executor.py:671]     logits = self._apply_top_k_top_p(logits, k, p)
(Worker_TP0_EP0 pid=550) ERROR 10-15 03:21:24 [multiproc_executor.py:671]              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(Worker_TP0_EP0 pid=550) ERROR 10-15 03:21:24 [multiproc_executor.py:671]   File "/vllm-workspace/vllm-ascend/vllm_ascend/sample/sampler.py", line 32, in _apply_top_k_top_p
(Worker_TP0_EP0 pid=550) ERROR 10-15 03:21:24 [multiproc_executor.py:671]     if not is_310p() and p is not None and k is not None and 1 <= int(
(Worker_TP0_EP0 pid=550) ERROR 10-15 03:21:24 [multiproc_executor.py:671]                                                                   ^^^^
(Worker_TP0_EP0 pid=550) ERROR 10-15 03:21:24 [multiproc_executor.py:671] RuntimeError: The Inner error is reported as above. The process exits for this inner error, and the current working operator name is aclnnMatmul.
(Worker_TP0_EP0 pid=550) ERROR 10-15 03:21:24 [multiproc_executor.py:671] Since the operator is called asynchronously, the stacktrace may be inaccurate. If you want to get the accurate stacktrace, please set the environment variable ASCEND_LAUNCH_BLOCKING=1.
(Worker_TP0_EP0 pid=550) ERROR 10-15 03:21:24 [multiproc_executor.py:671] Note: ASCEND_LAUNCH_BLOCKING=1 will force ops to run in synchronous mode, resulting in performance degradation. Please unset ASCEND_LAUNCH_BLOCKING in time after debugging.
(Worker_TP0_EP0 pid=550) ERROR 10-15 03:21:24 [multiproc_executor.py:671] [ERROR] 2025-10-15-03:21:24 (PID:550, Device:0, RankID:-1) ERR00100 PTA call acl api failed.
(Worker_TP0_EP0 pid=550) ERROR 10-15 03:21:24 [multiproc_executor.py:671]
(Worker_TP0_EP0 pid=550) ERROR 10-15 03:21:24 [multiproc_executor.py:671] Traceback (most recent call last):
(Worker_TP0_EP0 pid=550) ERROR 10-15 03:21:24 [multiproc_executor.py:671]   File "/vllm-workspace/vllm/vllm/v1/executor/multiproc_executor.py", line 666, in worker_busy_loop
(Worker_TP0_EP0 pid=550) ERROR 10-15 03:21:24 [multiproc_executor.py:671]     output = func(*args, **kwargs)
(Worker_TP0_EP0 pid=550) ERROR 10-15 03:21:24 [multiproc_executor.py:671]              ^^^^^^^^^^^^^^^^^^^^^
(Worker_TP0_EP0 pid=550) ERROR 10-15 03:21:24 [multiproc_executor.py:671]   File "/vllm-workspace/vllm-ascend/vllm_ascend/worker/worker_v1.py", line 254, in execute_model
(Worker_TP0_EP0 pid=550) ERROR 10-15 03:21:24 [multiproc_executor.py:671]     output = self.model_runner.execute_model(scheduler_output,
(Worker_TP0_EP0 pid=550) ERROR 10-15 03:21:24 [multiproc_executor.py:671]              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(Worker_TP0_EP0 pid=550) ERROR 10-15 03:21:24 [multiproc_executor.py:671]   File "/usr/local/python3.11.13/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
(Worker_TP0_EP0 pid=550) ERROR 10-15 03:21:24 [multiproc_executor.py:671]     return func(*args, **kwargs)
(Worker_TP0_EP0 pid=550) ERROR 10-15 03:21:24 [multiproc_executor.py:671]            ^^^^^^^^^^^^^^^^^^^^^
(Worker_TP0_EP0 pid=550) ERROR 10-15 03:21:24 [multiproc_executor.py:671]   File "/vllm-workspace/vllm-ascend/vllm_ascend/worker/model_runner_v1.py", line 2030, in execute_model
(Worker_TP0_EP0 pid=550) ERROR 10-15 03:21:24 [multiproc_executor.py:671]     sampler_output = self.sampler(
(Worker_TP0_EP0 pid=550) ERROR 10-15 03:21:24 [multiproc_executor.py:671]                      ^^^^^^^^^^^^^
(Worker_TP0_EP0 pid=550) ERROR 10-15 03:21:24 [multiproc_executor.py:671]   File "/usr/local/python3.11.13/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
(Worker_TP0_EP0 pid=550) ERROR 10-15 03:21:24 [multiproc_executor.py:671]     return self._call_impl(*args, **kwargs)
(Worker_TP0_EP0 pid=550) ERROR 10-15 03:21:24 [multiproc_executor.py:671]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(Worker_TP0_EP0 pid=550) ERROR 10-15 03:21:24 [multiproc_executor.py:671]   File "/usr/local/python3.11.13/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1762, in _call_impl
(Worker_TP0_EP0 pid=550) ERROR 10-15 03:21:24 [multiproc_executor.py:671]     return forward_call(*args, **kwargs)
(Worker_TP0_EP0 pid=550) ERROR 10-15 03:21:24 [multiproc_executor.py:671]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(Worker_TP0_EP0 pid=550) ERROR 10-15 03:21:24 [multiproc_executor.py:671]   File "/vllm-workspace/vllm/vllm/v1/sample/sampler.py", line 100, in forward
(Worker_TP0_EP0 pid=550) ERROR 10-15 03:21:24 [multiproc_executor.py:671]     sampled, processed_logprobs = self.sample(logits, sampling_metadata)
(Worker_TP0_EP0 pid=550) ERROR 10-15 03:21:24 [multiproc_executor.py:671]                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(Worker_TP0_EP0 pid=550) ERROR 10-15 03:21:24 [multiproc_executor.py:671]   File "/vllm-workspace/vllm/vllm/v1/sample/sampler.py", line 180, in sample
(Worker_TP0_EP0 pid=550) ERROR 10-15 03:21:24 [multiproc_executor.py:671]     random_sampled, processed_logprobs = self.topk_topp_sampler(
(Worker_TP0_EP0 pid=550) ERROR 10-15 03:21:24 [multiproc_executor.py:671]                                          ^^^^^^^^^^^^^^^^^^^^^^^
(Worker_TP0_EP0 pid=550) ERROR 10-15 03:21:24 [multiproc_executor.py:671]   File "/usr/local/python3.11.13/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
(Worker_TP0_EP0 pid=550) ERROR 10-15 03:21:24 [multiproc_executor.py:671]     return self._call_impl(*args, **kwargs)
(Worker_TP0_EP0 pid=550) ERROR 10-15 03:21:24 [multiproc_executor.py:671]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(Worker_TP0_EP0 pid=550) ERROR 10-15 03:21:24 [multiproc_executor.py:671]   File "/usr/local/python3.11.13/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1762, in _call_impl
(Worker_TP0_EP0 pid=550) ERROR 10-15 03:21:24 [multiproc_executor.py:671]     return forward_call(*args, **kwargs)
(Worker_TP0_EP0 pid=550) ERROR 10-15 03:21:24 [multiproc_executor.py:671]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(Worker_TP0_EP0 pid=550) ERROR 10-15 03:21:24 [multiproc_executor.py:671]   File "/vllm-workspace/vllm-ascend/vllm_ascend/sample/sampler.py", line 70, in forward_native
(Worker_TP0_EP0 pid=550) ERROR 10-15 03:21:24 [multiproc_executor.py:671]     logits = self._apply_top_k_top_p(logits, k, p)
(Worker_TP0_EP0 pid=550) ERROR 10-15 03:21:24 [multiproc_executor.py:671]              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(Worker_TP0_EP0 pid=550) ERROR 10-15 03:21:24 [multiproc_executor.py:671]   File "/vllm-workspace/vllm-ascend/vllm_ascend/sample/sampler.py", line 32, in _apply_top_k_top_p
(Worker_TP0_EP0 pid=550) ERROR 10-15 03:21:24 [multiproc_executor.py:671]     if not is_310p() and p is not None and k is not None and 1 <= int(
(Worker_TP0_EP0 pid=550) ERROR 10-15 03:21:24 [multiproc_executor.py:671]                                                                   ^^^^
(Worker_TP0_EP0 pid=550) ERROR 10-15 03:21:24 [multiproc_executor.py:671] RuntimeError: The Inner error is reported as above. The process exits for this inner error, and the current working operator name is aclnnMatmul.
(Worker_TP0_EP0 pid=550) ERROR 10-15 03:21:24 [multiproc_executor.py:671] Since the operator is called asynchronously, the stacktrace may be inaccurate. If you want to get the accurate stacktrace, please set the environment variable ASCEND_LAUNCH_BLOCKING=1.
(Worker_TP0_EP0 pid=550) ERROR 10-15 03:21:24 [multiproc_executor.py:671] Note: ASCEND_LAUNCH_BLOCKING=1 will force ops to run in synchronous mode, resulting in performance degradation. Please unset ASCEND_LAUNCH_BLOCKING in time after debugging.
(Worker_TP0_EP0 pid=550) ERROR 10-15 03:21:24 [multiproc_executor.py:671] [ERROR] 2025-10-15-03:21:24 (PID:550, Device:0, RankID:-1) ERR00100 PTA call acl api failed.
(Worker_TP0_EP0 pid=550) ERROR 10-15 03:21:24 [multiproc_executor.py:671]
(Worker_TP0_EP0 pid=550) ERROR 10-15 03:21:24 [multiproc_executor.py:671]
(EngineCore_DP0 pid=414) ERROR 10-15 03:21:24 [dump_input.py:69] Dumping input data for V1 LLM engine (v0.11.0rc3) with config: model='/root/.cache/models/Qwen/Qwen3-VL-30B-A3B-Instruct', speculative_config=None, tokenizer='/root/.cache/models/Qwen/Qwen3-VL-30B-A3B-Instruct', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, tokenizer_revision=None, trust_remote_code=False, dtype=torch.bfloat16, max_seq_len=40960, download_dir=None, load_format=auto, tensor_parallel_size=2, pipeline_parallel_size=1, data_parallel_size=1, disable_custom_all_reduce=True, quantization=None, enforce_eager=False, kv_cache_dtype=auto, device_config=npu, structured_outputs_config=StructuredOutputsConfig(backend='auto', disable_fallback=False, disable_any_whitespace=False, disable_additional_properties=False, reasoning_parser=''), observability_config=ObservabilityConfig(show_hidden_metrics_for_version=None, otlp_traces_endpoint=None, collect_detailed_traces=None), seed=0, served_model_name=Qwen/Qwen3-VL-30B-A3B-Instruct, enable_prefix_caching=True, chunked_prefill_enabled=True, pooler_config=None, compilation_config={"level":3,"debug_dump_path":"","cache_dir":"","backend":"","custom_ops":["all"],"splitting_ops":["vllm.unified_attention","vllm.unified_attention_with_output","vllm.mamba_mixer2","vllm.mamba_mixer","vllm.short_conv","vllm.linear_attention","vllm.plamo2_mamba_mixer","vllm.gdn_attention","vllm.unified_ascend_attention_with_output","vllm.mla_forward","vllm.unified_ascend_attention_with_output","vllm.mla_forward"],"use_inductor":false,"compile_sizes":[],"inductor_compile_config":{"enable_auto_functionalized_v2":false},"inductor_passes":{},"cudagraph_mode":1,"use_cudagraph":true,"cudagraph_num_of_warmups":1,"cudagraph_capture_sizes":[512,456,408,352,304,248,192,144,88,40,1],"cudagraph_copy_inputs":false,"full_cuda_graph":false,"use_inductor_graph_partition":false,"pass_config":{},"max_capture_size":512,"local_cache_dir":null},
(EngineCore_DP0 pid=414) ERROR 10-15 03:21:24 [dump_input.py:76] Dumping scheduler output for model execution: SchedulerOutput(scheduled_new_reqs=[], scheduled_cached_reqs=CachedRequestData(req_ids=['chatcmpl-ad782189793949998f5b5386d116f4c4'], resumed_from_preemption=[false], new_token_ids=[], new_block_ids=[[[17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32]]], num_computed_tokens=[2048]), num_scheduled_tokens={chatcmpl-ad782189793949998f5b5386d116f4c4: 2048}, total_num_scheduled_tokens=2048, scheduled_spec_decode_tokens={}, scheduled_encoder_inputs={}, num_common_prefix_blocks=[32], finished_req_ids=[], free_encoder_mm_hashes=[], structured_output_request_ids={}, grammar_bitmask=null, kv_connector_metadata=null)
(EngineCore_DP0 pid=414) ERROR 10-15 03:21:24 [dump_input.py:79] Dumping scheduler stats: SchedulerStats(num_running_reqs=1, num_waiting_reqs=0, step_counter=0, current_wave=0, kv_cache_usage=0.00815286624203826, prefix_cache_stats=PrefixCacheStats(reset=False, requests=0, queries=0, hits=0), spec_decoding_stats=None, kv_connector_stats=None, num_corrupted_reqs=0)
(EngineCore_DP0 pid=414) ERROR 10-15 03:21:24 [core.py:710] EngineCore encountered a fatal error.
(EngineCore_DP0 pid=414) ERROR 10-15 03:21:24 [core.py:710] Traceback (most recent call last):
(EngineCore_DP0 pid=414) ERROR 10-15 03:21:24 [core.py:710]   File "/vllm-workspace/vllm/vllm/v1/engine/core.py", line 701, in run_engine_core
(EngineCore_DP0 pid=414) ERROR 10-15 03:21:24 [core.py:710]     engine_core.run_busy_loop()
(EngineCore_DP0 pid=414) ERROR 10-15 03:21:24 [core.py:710]   File "/vllm-workspace/vllm/vllm/v1/engine/core.py", line 728, in run_busy_loop
(EngineCore_DP0 pid=414) ERROR 10-15 03:21:24 [core.py:710]     self._process_engine_step()
(EngineCore_DP0 pid=414) ERROR 10-15 03:21:24 [core.py:710]   File "/vllm-workspace/vllm/vllm/v1/engine/core.py", line 754, in _process_engine_step
(EngineCore_DP0 pid=414) ERROR 10-15 03:21:24 [core.py:710]     outputs, model_executed = self.step_fn()
(EngineCore_DP0 pid=414) ERROR 10-15 03:21:24 [core.py:710]                               ^^^^^^^^^^^^^^
(EngineCore_DP0 pid=414) ERROR 10-15 03:21:24 [core.py:710]   File "/vllm-workspace/vllm/vllm/v1/engine/core.py", line 284, in step
(EngineCore_DP0 pid=414) ERROR 10-15 03:21:24 [core.py:710]     model_output = self.execute_model_with_error_logging(
(EngineCore_DP0 pid=414) ERROR 10-15 03:21:24 [core.py:710]                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(EngineCore_DP0 pid=414) ERROR 10-15 03:21:24 [core.py:710]   File "/vllm-workspace/vllm/vllm/v1/engine/core.py", line 270, in execute_model_with_error_logging
(EngineCore_DP0 pid=414) ERROR 10-15 03:21:24 [core.py:710]     raise err
(EngineCore_DP0 pid=414) ERROR 10-15 03:21:24 [core.py:710]   File "/vllm-workspace/vllm/vllm/v1/engine/core.py", line 261, in execute_model_with_error_logging
(EngineCore_DP0 pid=414) ERROR 10-15 03:21:24 [core.py:710]     return model_fn(scheduler_output)
(EngineCore_DP0 pid=414) ERROR 10-15 03:21:24 [core.py:710]            ^^^^^^^^^^^^^^^^^^^^^^^^^^
(EngineCore_DP0 pid=414) ERROR 10-15 03:21:24 [core.py:710]   File "/vllm-workspace/vllm/vllm/v1/executor/multiproc_executor.py", line 181, in execute_model
(EngineCore_DP0 pid=414) ERROR 10-15 03:21:24 [core.py:710]     (output, ) = self.collective_rpc(
(EngineCore_DP0 pid=414) ERROR 10-15 03:21:24 [core.py:710]                  ^^^^^^^^^^^^^^^^^^^^
(EngineCore_DP0 pid=414) ERROR 10-15 03:21:24 [core.py:710]   File "/vllm-workspace/vllm/vllm/v1/executor/multiproc_executor.py", line 264, in collective_rpc
(EngineCore_DP0 pid=414) ERROR 10-15 03:21:24 [core.py:710]     result = get_response(w, dequeue_timeout,
(EngineCore_DP0 pid=414) ERROR 10-15 03:21:24 [core.py:710]              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(EngineCore_DP0 pid=414) ERROR 10-15 03:21:24 [core.py:710]   File "/vllm-workspace/vllm/vllm/v1/executor/multiproc_executor.py", line 248, in get_response
(EngineCore_DP0 pid=414) ERROR 10-15 03:21:24 [core.py:710]     raise RuntimeError(
(EngineCore_DP0 pid=414) ERROR 10-15 03:21:24 [core.py:710] RuntimeError: Worker failed with error 'The Inner error is reported as above. The process exits for this inner error, and the current working operator name is aclnnMatmul.
(EngineCore_DP0 pid=414) ERROR 10-15 03:21:24 [core.py:710] Since the operator is called asynchronously, the stacktrace may be inaccurate. If you want to get the accurate stacktrace, please set the environment variable ASCEND_LAUNCH_BLOCKING=1.
(EngineCore_DP0 pid=414) ERROR 10-15 03:21:24 [core.py:710] Note: ASCEND_LAUNCH_BLOCKING=1 will force ops to run in synchronous mode, resulting in performance degradation. Please unset ASCEND_LAUNCH_BLOCKING in time after debugging.
(EngineCore_DP0 pid=414) ERROR 10-15 03:21:24 [core.py:710] [ERROR] 2025-10-15-03:21:24 (PID:550, Device:0, RankID:-1) ERR00100 PTA call acl api failed.
(EngineCore_DP0 pid=414) ERROR 10-15 03:21:24 [core.py:710] ', please check the stack trace above for the root cause
(Worker_TP0_EP0 pid=550) INFO 10-15 03:21:24 [multiproc_executor.py:558] Parent process exited, terminating worker
(Worker_TP1_EP1 pid=551) INFO 10-15 03:21:24 [multiproc_executor.py:558] Parent process exited, terminating worker
(APIServer pid=1) ERROR 10-15 03:21:24 [async_llm.py:480] AsyncLLM output_handler failed.
(APIServer pid=1) ERROR 10-15 03:21:24 [async_llm.py:480] Traceback (most recent call last):
(APIServer pid=1) ERROR 10-15 03:21:24 [async_llm.py:480]   File "/vllm-workspace/vllm/vllm/v1/engine/async_llm.py", line 439, in output_handler
(APIServer pid=1) ERROR 10-15 03:21:24 [async_llm.py:480]     outputs = await engine_core.get_output_async()
(APIServer pid=1) ERROR 10-15 03:21:24 [async_llm.py:480]               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(APIServer pid=1) ERROR 10-15 03:21:24 [async_llm.py:480]   File "/vllm-workspace/vllm/vllm/v1/engine/core_client.py", line 846, in get_output_async
(APIServer pid=1) ERROR 10-15 03:21:24 [async_llm.py:480]     raise self._format_exception(outputs) from None
(APIServer pid=1) ERROR 10-15 03:21:24 [async_llm.py:480] vllm.v1.engine.exceptions.EngineDeadError: EngineCore encountered an issue. See stack trace (above) for the root cause.
(APIServer pid=1) ERROR 10-15 03:21:24 [serving_chat.py:1145] Error in chat completion stream generator.
(APIServer pid=1) ERROR 10-15 03:21:24 [serving_chat.py:1145] Traceback (most recent call last):
(APIServer pid=1) ERROR 10-15 03:21:24 [serving_chat.py:1145]   File "/vllm-workspace/vllm/vllm/entrypoints/openai/serving_chat.py", line 574, in chat_completion_stream_generator
(APIServer pid=1) ERROR 10-15 03:21:24 [serving_chat.py:1145]     async for res in result_generator:
(APIServer pid=1) ERROR 10-15 03:21:24 [serving_chat.py:1145]   File "/vllm-workspace/vllm/vllm/v1/engine/async_llm.py", line 387, in generate
(APIServer pid=1) ERROR 10-15 03:21:24 [serving_chat.py:1145]     out = q.get_nowait() or await q.get()
(APIServer pid=1) ERROR 10-15 03:21:24 [serving_chat.py:1145]                             ^^^^^^^^^^^^^
(APIServer pid=1) ERROR 10-15 03:21:24 [serving_chat.py:1145]   File "/vllm-workspace/vllm/vllm/v1/engine/output_processor.py", line 59, in get
(APIServer pid=1) ERROR 10-15 03:21:24 [serving_chat.py:1145]     raise output
(APIServer pid=1) ERROR 10-15 03:21:24 [serving_chat.py:1145]   File "/vllm-workspace/vllm/vllm/v1/engine/async_llm.py", line 439, in output_handler
(APIServer pid=1) ERROR 10-15 03:21:24 [serving_chat.py:1145]     outputs = await engine_core.get_output_async()
(APIServer pid=1) ERROR 10-15 03:21:24 [serving_chat.py:1145]               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(APIServer pid=1) ERROR 10-15 03:21:24 [serving_chat.py:1145]   File "/vllm-workspace/vllm/vllm/v1/engine/core_client.py", line 846, in get_output_async
(APIServer pid=1) ERROR 10-15 03:21:24 [serving_chat.py:1145]     raise self._format_exception(outputs) from None
(APIServer pid=1) ERROR 10-15 03:21:24 [serving_chat.py:1145] vllm.v1.engine.exceptions.EngineDeadError: EngineCore encountered an issue. See stack trace (above) for the root cause.
(EngineCore_DP0 pid=414) Process EngineCore_DP0:
(EngineCore_DP0 pid=414) Traceback (most recent call last):
(EngineCore_DP0 pid=414)   File "/usr/local/python3.11.13/lib/python3.11/multiprocessing/process.py", line 314, in _bootstrap
(EngineCore_DP0 pid=414)     self.run()
(EngineCore_DP0 pid=414)   File "/usr/local/python3.11.13/lib/python3.11/multiprocessing/process.py", line 108, in run
(EngineCore_DP0 pid=414)     self._target(*self._args, **self._kwargs)
(EngineCore_DP0 pid=414)   File "/vllm-workspace/vllm/vllm/v1/engine/core.py", line 712, in run_engine_core
(EngineCore_DP0 pid=414)     raise e
(EngineCore_DP0 pid=414)   File "/vllm-workspace/vllm/vllm/v1/engine/core.py", line 701, in run_engine_core
(EngineCore_DP0 pid=414)     engine_core.run_busy_loop()
(EngineCore_DP0 pid=414)   File "/vllm-workspace/vllm/vllm/v1/engine/core.py", line 728, in run_busy_loop
(EngineCore_DP0 pid=414)     self._process_engine_step()
(EngineCore_DP0 pid=414)   File "/vllm-workspace/vllm/vllm/v1/engine/core.py", line 754, in _process_engine_step
(EngineCore_DP0 pid=414)     outputs, model_executed = self.step_fn()
(EngineCore_DP0 pid=414)                               ^^^^^^^^^^^^^^
(EngineCore_DP0 pid=414)   File "/vllm-workspace/vllm/vllm/v1/engine/core.py", line 284, in step
(EngineCore_DP0 pid=414)     model_output = self.execute_model_with_error_logging(
(EngineCore_DP0 pid=414)                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(EngineCore_DP0 pid=414)   File "/vllm-workspace/vllm/vllm/v1/engine/core.py", line 270, in execute_model_with_error_logging
(EngineCore_DP0 pid=414)     raise err
(EngineCore_DP0 pid=414)   File "/vllm-workspace/vllm/vllm/v1/engine/core.py", line 261, in execute_model_with_error_logging
(EngineCore_DP0 pid=414)     return model_fn(scheduler_output)
(EngineCore_DP0 pid=414)            ^^^^^^^^^^^^^^^^^^^^^^^^^^
(EngineCore_DP0 pid=414)   File "/vllm-workspace/vllm/vllm/v1/executor/multiproc_executor.py", line 181, in execute_model
(EngineCore_DP0 pid=414)     (output, ) = self.collective_rpc(
(EngineCore_DP0 pid=414)                  ^^^^^^^^^^^^^^^^^^^^
(EngineCore_DP0 pid=414)   File "/vllm-workspace/vllm/vllm/v1/executor/multiproc_executor.py", line 264, in collective_rpc
(EngineCore_DP0 pid=414)     result = get_response(w, dequeue_timeout,
(EngineCore_DP0 pid=414)              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(EngineCore_DP0 pid=414)   File "/vllm-workspace/vllm/vllm/v1/executor/multiproc_executor.py", line 248, in get_response
(EngineCore_DP0 pid=414)     raise RuntimeError(
(EngineCore_DP0 pid=414) RuntimeError: Worker failed with error 'The Inner error is reported as above. The process exits for this inner error, and the current working operator name is aclnnMatmul.
(EngineCore_DP0 pid=414) Since the operator is called asynchronously, the stacktrace may be inaccurate. If you want to get the accurate stacktrace, please set the environment variable ASCEND_LAUNCH_BLOCKING=1.
(EngineCore_DP0 pid=414) Note: ASCEND_LAUNCH_BLOCKING=1 will force ops to run in synchronous mode, resulting in performance degradation. Please unset ASCEND_LAUNCH_BLOCKING in time after debugging.
(EngineCore_DP0 pid=414) [ERROR] 2025-10-15-03:21:24 (PID:550, Device:0, RankID:-1) ERR00100 PTA call acl api failed.
(EngineCore_DP0 pid=414) ', please check the stack trace above for the root cause
(APIServer pid=1) INFO:     Shutting down
(APIServer pid=1) INFO:     Waiting for application shutdown.
(APIServer pid=1) INFO:     Application shutdown complete.
(APIServer pid=1) INFO:     Finished server process [1]

**Comment by ChrisKimZHT** [comment]
Qwen3-VL-235B-A22B-Instruct 遇到同样的问题，2 x 8 x Ascend 910B2 TP 并行。

https://github.com/vllm-project/vllm-ascend/issues/3637

```
(APIServer pid=803) ERROR 10-22 11:22:50 [serving_chat.py:1145]     async for res in result_generator:                                                                             
(APIServer pid=803) ERROR 10-22 11:22:50 [serving_chat.py:1145]   File "/vllm-workspace/vllm/vllm/v1/engine/async_llm.py", line 387, in generate                                   
(APIServer pid=803) ERROR 10-22 11:22:50 [serving_chat.py:1145]     out = q.get_nowait() or await q.get()                                                                          
(APIServer pid=803) ERROR 10-22 11:22:50 [serving_chat.py:1145]                             ^^^^^^^^^^^^^                                       
(APIServer pid=803) ERROR 10-22 11:22:50 [serving_chat.py:1145]   File "/vllm-workspace/vllm/vllm/v1/engine/output_processor.py", line 59, in get                                  
(APIServer pid=803) ERROR 10-22 11:22:50 [serving_chat.py:1145]     raise output                                                                                                   
(APIServer pid=803) ERROR 10-22 11:22:50 [serving_chat.py:1145]   File "/vllm-workspace/vllm/vllm/v1/engine/async_llm.py", line 439, in output_handler                             
(APIServer pid=803) ERROR 10-22 11:22:50 [serving_chat.py:1145]     outputs = await engine_core.get_output_async()                                                                 
(APIServer pid=803) ERROR 10-22 11:22:50 [serving_chat.py:1145]               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                 
(APIServer pid=803) ERROR 10-22 11:22:50 [serving_chat.py:1145]   File "/vllm-workspace/vllm/vllm/v1/engine/core_client.py", line 846, in get_output_async                         
(APIServer pid=803) ERROR 10-22 11:22:50 [serving_chat.py:1145]     raise self._format_exception(outputs) from None                                                                
(APIServer pid=803) ERROR 10-22 11:22:50 [serving_chat.py:1145] vllm.v1.engine.exceptions.EngineDeadError: EngineCore encountered an issue. See stack trace (above) for the root cause.                                                                                                                                                                               
(APIServer pid=803) INFO:     Shutting down                                                                                                                                        
(APIServer pid=803) INFO:     Waiting for application shutdown.                                                                                                                    
(APIServer pid=803) INFO:     Application shutdown complete.                                                                                                                       (APIServer pid=803) INFO:     Finished server process [803]                                                                                                                        
*** SIGTERM received at time=1761132170 on cpu 96 ***                                                                                                                              
PC: @     0xffff9eaf9dec  (unknown)  (unknown)                                                                                                                                     
    @     0xfffcf7fe5708        464  absl::lts_20230802::AbslFailureSignalHandler()                                                                                                
    @     0xffff9f23f7c0   53819616  (unknown)                                                                                                                                     
    @     0xffff9eafcc00         64  pthread_cond_timedwait                                                                                                                        
    @     0xfffcf7598f5c        224  ray::core::GetRequest::Wait()                                                                                                                 
    @     0xfffcf759b1a8       1184  ray::core::CoreWorkerMemoryStore::GetImpl()                                                                                                       @     0xfffcf759baf0       1440  ray::core::CoreWorkerMemoryStore::Get()                                                                                                       
    @     0xfffcf759bd54         32  ray::core::CoreWorkerMemoryStore::Get()                                                                                                       
    @     0xfffcf747dc4c        208  ray::core::CoreWorker::GetObjects()                                                                                                           
    @     0xfffcf74827d4       1744  ray::core::CoreWorker::Get()                                                                                                                  
    @     0xfffcf73e0de4        176  __pyx_pw_3ray_7_raylet_10CoreWorker_41get_objects()                                                                                           
    @     0xffff9ed8d448        208  PyObject_Vectorcall                                                                                                                           
    @     0xffff9ed2f278         32  _PyEval_EvalFrameDefault                                                                                                                      
    @     0xffff9ee842ac        432  _PyEval_Vector                                                                                                                                    @     0xffff9ed8cb60         48  _PyObject_Call                                                                                                                                
    @     0xffff9ed32380         96  _PyEval_EvalFrameDefault                                                                                                                      
    @     0xffff9ee842ac        432  _PyEval_Vector                                                                                                                                
    @     0xffff9ed8cb60         48  _PyObject_Call                                                                                                                                
    @     0xffff9ed32380         96  _PyEval_EvalFrameDefault
    @     0xffff9ee842ac        432  _PyEval_Vector                                                                                                                                
    @     0xffff9ed8cb60         48  _PyObject_Call                                                                                                                                
    @     0xffff9ed32380         96  _PyEval_EvalFrameDefault                                                                                                                          @     0xffff9ee8411c        432  PyEval_EvalCode                                                                                                                               
    @     0xffff9eece8bc        144  run_mod                                                                                                                                       
    @     0xffff9eed082c         64  PyRun_StringFlags                                                                                                                             
    @     0xffff9eed08b0         64  PyRun_SimpleStringFlags                                                                                                                       
    @     0xffff9eef12b0         32  Py_RunMain                                                                                                                                    
    @     0xffff9eef1c2c        256  Py_BytesMain                                                                                                                                  
    @     0xffff9eaa73fc        192  (unknown)                                                                                                                                     
    @     0xffff9eaa74cc        272  __libc_start_main                                                                                                                             
[2025-10-22 11:22:50,416 E 1073 1073] logging.cc:474: *** SIGTERM received at time=1761132170 on cpu 96 ***                                                                        
[2025-10-22 11:22:50,417 E 1073 1073] logging.cc:474: PC: @     0xffff9eaf9dec  (unknown)  (unknown)                                                                               
[2025-10-22 11:22:50,423 E 1073 1073] logging.cc:474:     @     0xfffcf7fe5730        464  absl::lts_20230802::AbslFailureSignalHandler()                                          
[2025-10-22 11:22:50,426 E 1073 1073] logging.cc:474:     @     0xffff9f23f7c0   53819616  (unknown)                                                                               
[2025-10-22 11:22:50,426 E 1073 1073] logging.cc:474:     @     0xffff9eafcc00         64  pthread_cond_timedwait                                                                  
[2025-10-22 11:22:50,426 E 1073 1073] logging.cc:474:     @     0xfffcf7598f5c        224  ray::core::GetRequest::Wait()                                                           
[2025-10-22 11:22:50,426 E 1073 1073] logging.cc:474:     @     0xfffcf759b1a8       1184  ray::core::CoreWorkerMemoryStore::GetImpl()                                             
[2025-10-22 11:22:50,426 E 1073 1073] logging.cc:474:     @     0xfffcf759baf0       1440  ray::core::CoreWorkerMemoryStore::Get()                                                 
[2025-10-22 11:22:50,426 E 1073 1073] logging.cc:474:     @     0xfffcf759bd54         32  ray::core::CoreWorkerMemoryStore::Get()                                                 
[2025-10-22 11:22:50,426 E 1073 1073] logging.cc:474:     @     0xfffcf747dc4c        208  ray::core::CoreWorker::GetObjects()                                                     
[2025-10-22 11:22:50,426 E 1073 1073] logging.cc:474:     @     0xfffcf74827d4       1744  ray::core::CoreWorker::Get()                                                            
[2025-10-22 11:22:50,426 E 1073 1073] logging.cc:474:     @     0xfffcf73e0de4        176  __pyx_pw_3ray_7_raylet_10CoreWorker_41get_objects()                                     
[2025-10-22 11:22:50,426 E 1073 1073] logging.cc:474:     @     0xffff9ed8d448        208  PyObject_Vectorcall                                                                     
[2025-10-22 11:22:50,426 E 1073 1073] logging.cc:474:     @     0xffff9ed2f278         32  _PyEval_EvalFrameDefault                                                                
[2025-10-22 11:22:50,426 E 1073 1073] logging.cc:474:     @     0xffff9ee842ac        432  _PyEval_Vector                                                                          
[2025-10-22 11:22:50,426 E 1073 1073] logging.cc:474:     @     0xffff9ed8cb60         48  _PyObject_Call                                                                          
[2025-10-22 11:22:50,426 E 1073 1073] logging.cc:474:     @     0xffff9ed32380         96  _PyEval_EvalFrameDefault                                                                
[2025-10-22 11:22:50,426 E 1073 1073] logging.cc:474:     @     0xffff9ee842ac        432  _PyEval_Vector                                                                          
[2025-10-22 11:22:50,426 E 1073 1073] logging.cc:474:     @     0xffff9ed8cb60         48  _PyObject_Call                                                                          
[2025-10-22 11:22:50,426 E 1073 1073] logging.cc:474:     @     0xffff9ed32380         96  _PyEval_EvalFrameDefault                                                                
[2025-10-22 11:22:50,426 E 1073 1073] logging.cc:474:     @     0xffff9ee842ac        432  _PyEval_Vector                                                                          
[2025-10-22 11:22:50,426 E 1073 1073] logging.cc:474:     @     0xffff9ed8cb60         48  _PyObject_Call                                                                          
[2025-10-22 11:22:50,426 E 1073 1073] logging.cc:474:     @     0xffff9ed32380         96  _PyEval_EvalFrameDefault                                                                
[2025-10-22 11:22:50,426 E 1073 1073] logging.cc:474:     @     0xffff9ee8411c        432  PyEval_EvalCode                                                                         
[2025-10-22 11:22:50,426 E 1073 1073] logging.cc:474:     @     0xffff9eece8bc        144  run_mod                                                                                 
[2025-10-22 11:22:50,426 E 1073 1073] logging.cc:474:     @     0xffff9eed082c         64  PyRun_StringFlags                                                                       
[2025-10-22 11:22:50,426 E 1073 1073] logging.cc:474:     @     0xffff9eed08b0         64  PyRun_SimpleStringFlags                                                                 
[2025-10-22 11:22:50,426 E 1073 1073] logging.cc:474:     @     0xffff9eef12b0         32  Py_RunMain                                                                              
[2025-10-22 11:22:50,426 E 1073 1073] logging.cc:474:     @     0xffff9eef1c2c        256  Py_BytesMain                                                                            
[2025-10-22 11:22:50,429 E 1073 1073] logging.cc:474:     @     0xffff9eaa73fc        192  (unknown)
[2025-10-22 11:22:50,429 E 1073 1073] logging.cc:474:     @     0xffff9eaa74cc        272  __libc_start_main                                                                       
(EngineCore_DP0 pid=1073) 2025-10-22 11:22:50,655       INFO compiled_dag_node.py:2171 -- Tearing down compiled DAG                                                                
(EngineCore_DP0 pid=1073) 2025-10-22 11:22:50,656       INFO compiled_dag_node.py:2176 -- Cancelling compiled worker on actor: Actor(RayWorkerWrapper, f0e473c6d29e3c28f62930ab01000000)                                                                                                                                                                              
(EngineCore_DP0 pid=1073) 2025-10-22 11:22:50,657       INFO compiled_dag_node.py:2176 -- Cancelling compiled worker on actor: Actor(RayWorkerWrapper, 511ccf1430d2a2bc6fc118550100
0000)                                                                                                                                                                              
(EngineCore_DP0 pid=1073) 2025-10-22 11:22:50,657       INFO compiled_dag_node.py:2176 -- Cancelling compiled worker on actor: Actor(RayWorkerWrapper, b80fc22617b5743d4e86497d0100
0000)                                                                                                                                                                              
(EngineCore_DP0 pid=1073) 2025-10-22 11:22:50,657       INFO compiled_dag_node.py:2176 -- Cancelling compiled worker on actor: Actor(RayWorkerWrapper, ede7707243917d9a3d1ad8b10100
0000)                                                                                                                                                                              
(EngineCore_DP0 pid=1073) 2025-10-22 11:22:50,657       INFO compiled_dag_node.py:2176 -- Cancelling compiled worker on actor: Actor(RayWorkerWrapper, af30299946772f9f3a1c523c0100
0000)                                                                                                                                                                              
(EngineCore_DP0 pid=1073) 2025-10-22 11:22:50,657       INFO compiled_dag_node.py:2176 -- Cancelling compiled worker on actor: Actor(RayWorkerWrapper, f3d24aa0af116e16b762ac5f0100
0000)                                                                                                                                                                              
(EngineCore_DP0 pid=1073) 2025-10-22 11:22:50,657       INFO compiled_dag_node.py:2176 -- Cancelling compiled worker on actor: Actor(RayWorkerWrapper, af04f77f1104dd1875a03c5e0100
0000)                                                                                                                                                                              
(EngineCore_DP0 pid=1073) 2025-10-22 11:22:50,657       INFO compiled_dag_node.py:2176 -- Cancelling compiled worker on actor: Actor(RayWorkerWrapper, e6677b92540ef84f81e3dee50100
0000)                                                                                                                                                                              
(EngineCore_DP0 pid=1073) 2025-10-22 11:22:50,657       INFO compiled_dag_node.py:2176 -- Cancelling compiled worker on actor: Actor(RayWorkerWrapper, 50e333441477d4bfc34c5c0c0100
0000)                                                                                                                                                                              
(EngineCore_DP0 pid=1073) 2025-10-22 11:22:50,657       INFO compiled_dag_node.py:2176 -- Cancelling compiled worker on actor: Actor(RayWorkerWrapper, 9d9c75e791ed82c27ced8b4a0100
0000)                                                                                                                                                                              
(EngineCore_DP0 pid=1073) 2025-10-22 11:22:50,657       INFO compiled_dag_node.py:2176 -- Cancelling compiled worker on actor: Actor(RayWorkerWrapper, c072faa339ee0876be3d2ce10100
0000)                                                                                                                                                                              
(EngineCore_DP0 pid=1073) 2025-10-22 11:22:50,657       INFO compiled_dag_node.py:2176 -- Cancelling compiled worker on actor: Actor(RayWorkerWrapper, 359b6c063c9ea48ce645503f01000000)                                                                                                                                                                              
(EngineCore_DP0 pid=1073) 2025-10-22 11:22:50,657       INFO compiled_dag_node.py:2176 -- Cancelling compiled worker on actor: Actor(RayWorkerWrapper, f1b6f18eb5cd2d0ec4b91fc80100
0000)                                                                                                                                                                              
(EngineCore_DP0 pid=1073) 2025-10-22 11:22:50,657       INFO compiled_dag_node.py:2176 -- Cancelling compiled worker on actor: Actor(RayWorkerWrapper, e9da329afa4088c8f860f3a20100
0000)                                                                                                                                                                              
(EngineCore_DP0 pid=1073) 2025-10-22 11:22:50,657       INFO compiled_dag_node.py:2176 -- Cancelling compiled worker on actor: Actor(RayWorkerWrapper, 9b3fb94e875e3bff729857cb0100
0000)                                                                                                                                                                              
(EngineCore_DP0 pid=1073) 2025-10-22 11:22:50,657       INFO compiled_dag_node.py:2176 -- Cancelling compiled worker on actor: Actor(RayWorkerWrapper, 3a4cf7c722569f4f9b6d458f0100
0000)                                                                                                                                                                              
(EngineCore_DP0 pid=1073) 2025-10-22 11:22:50,691       INFO compiled_dag_node.py:2198 -- Waiting for worker tasks to exit
```

**Comment by Yikun** [comment]
@shen-shanshan  Please take a look, seems there are no `qwen3-vl-30b-a3b` doc on https://docs.vllm.ai/projects/ascend/en/latest/tutorials/index.html , would you mind add them?

**Comment by shen-shanshan** [comment]
> [@shen-shanshan](https://github.com/shen-shanshan) Please take a look, seems there are no `qwen3-vl-30b-a3b` doc on https://docs.vllm.ai/projects/ascend/en/latest/tutorials/index.html , would you mind add them?

OK. I will do that tomorrow.

**Comment by shen-shanshan** [comment]
@chenm202501 I have tested the video inference function of `Qwen3-VL-30B-A3B-Instruct` based on vllm `5fbfa8d9ef15948599631baeb91e8220b2ee9bcc` and vllm-ascend `main`, it worker smoothly.

Currently, I'm working with this doc, find more details at https://github.com/vllm-project/vllm-ascend/pull/5331.

**Comment by shen-shanshan** [comment]
@chenm202501 Hello, would you mind verifing your issue with the latest vllm-ascend and give us some feedback? Since your problem has been resolved, and I will close this issue if it worked well for you.

**Comment by Yikun** [comment]
It seems no more reply, I will mark this a resolved, pls let us know if you have more questions.

**Comment by JaneConan** [comment]
i will check

**Comment by JaneConan** [comment]
vllm serve Qwen/Qwen3-VL-30B-A3B-Instruct \
--tensor-parallel-size 2 \
--enable-expert-parallel \
--max-model-len 128000 \
--allowed-local-media-path /media

**Comment by JaneConan** [comment]
<img width="3120" height="2080" alt="Image" src="https://github.com/user-attachments/assets/b00199f3-72c4-4e64-a529-6ea838bc6b96" />

![Image](https://github.com/user-attachments/assets/63883a26-791c-4e8b-b603-7d4eeb6441ed)

the latest version is ok

vllm version 0.15.0

you can follow this tutorials
https://docs.vllm.ai/projects/ascend/zh-cn/latest/tutorials/models/Qwen3-VL-30B-A3B-Instruct.html
