### ISSUE TITLE
[Bug]: RuntimeError: Engine core initialization failed. See root cause above. Failed core proc(s): {}

### ISSUE THREAD

**Issue by caiskk** [vllm-project/vllm-ascend#4454]
### Your current environment

<details>
<summary>The output of `python collect_env.py`</summary>

```text
PyTorch version: 2.7.1+cpu
Is debug build: False

OS: Ubuntu 22.04.5 LTS (x86_64)
GCC version: (Ubuntu 11.4.0-1ubuntu1~22.04.2) 11.4.0
Clang version: Could not collect
CMake version: version 4.2.0
Libc version: glibc-2.35

Python version: 3.11.14 (main, Oct 21 2025, 18:31:21) [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-5.15.0-126-generic-x86_64-with-glibc2.35

CPU:
Architecture:                         x86_64
CPU op-mode(s):                       32-bit, 64-bit
Address sizes:                        39 bits physical, 48 bits virtual
Byte Order:                           Little Endian
CPU(s):                               16
On-line CPU(s) list:                  0-15
Vendor ID:                            GenuineIntel
Model name:                           13th Gen Intel(R) Core(TM) i5-13500H
CPU family:                           6
Model:                                186
Thread(s) per core:                   2
Core(s) per socket:                   12
Socket(s):                            1
Stepping:                             2
CPU max MHz:                          4700.0000
CPU min MHz:                          400.0000
BogoMIPS:                             6374.40
Flags:                                fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf tsc_known_freq pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb invpcid_single ssbd ibrs ibpb stibp ibrs_enhanced tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid rdseed adx smap clflushopt clwb intel_pt sha_ni xsaveopt xsavec xgetbv1 xsaves split_lock_detect avx_vnni dtherm ida arat pln pts hwp hwp_notify hwp_act_window hwp_epp hwp_pkg_req umip pku ospke waitpkg gfni vaes vpclmulqdq rdpid movdiri movdir64b fsrm md_clear serialize arch_lbr flush_l1d arch_capabilities
Virtualization:                       VT-x
L1d cache:                            448 KiB (12 instances)
L1i cache:                            640 KiB (12 instances)
L2 cache:                             9 MiB (6 instances)
L3 cache:                             18 MiB (1 instance)
NUMA node(s):                         1
NUMA node0 CPU(s):                    0-15
Vulnerability Gather data sampling:   Not affected
Vulnerability Itlb multihit:          Not affected
Vulnerability L1tf:                   Not affected
Vulnerability Mds:                    Not affected
Vulnerability Meltdown:               Not affected
Vulnerability Mmio stale data:        Not affected
Vulnerability Reg file data sampling: Mitigation; Clear Register File
Vulnerability Retbleed:               Not affected
Vulnerability Spec rstack overflow:   Not affected
Vulnerability Spec store bypass:      Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:             Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:             Mitigation; Enhanced / Automatic IBRS; IBPB conditional; RSB filling; PBRSB-eIBRS SW sequence; BHI BHI_DIS_S
Vulnerability Srbds:                  Not affected
Vulnerability Tsx async abort:        Not affected

Versions of relevant libraries:
[pip3] numpy==1.26.4
[pip3] optree==0.17.0
[pip3] pyzmq==27.1.0
[pip3] torch==2.7.1+cpu
[pip3] torch_npu==2.7.1
[pip3] torchaudio==2.7.1+cpu
[pip3] torchvision==0.22.1+cpu
[pip3] transformers==4.57.3
[conda] numpy                                1.26.4           pypi_0           pypi
[conda] pyzmq                                27.1.0           pypi_0           pypi
[conda] torch                                2.7.1+cpu        pypi_0           pypi
[conda] torch-npu                            2.7.1            pypi_0           pypi
[conda] torchaudio                           2.7.1+cpu        pypi_0           pypi
[conda] torchvision                          0.22.1+cpu       pypi_0           pypi
[conda] transformers                         4.57.3           pypi_0           pypi
vLLM Version: 0.11.0
vLLM Ascend Version: 0.11.0rc2

ENV Variables:
ATB_OPSRUNNER_KERNEL_CACHE_LOCAL_COUNT=1
ATB_STREAM_SYNC_EVERY_RUNNER_ENABLE=0
ATB_OPSRUNNER_SETUP_CACHE_ENABLE=1
ATB_WORKSPACE_MEM_ALLOC_GLOBAL=1
ATB_DEVICE_TILING_BUFFER_BLOCK_NUM=32
ATB_STREAM_SYNC_EVERY_KERNEL_ENABLE=0
ATB_OPSRUNNER_KERNEL_CACHE_GLOABL_COUNT=5
ASCEND_NNAE_HOME=/usr/local/Ascend/nnae/latest
ATB_HOME_PATH=/usr/local/Ascend/nnal/atb/latest/atb/cxx_abi_1
ASCEND_TOOLKIT_HOME=/usr/local/Ascend/ascend-toolkit/latest
ATB_COMPARE_TILING_EVERY_KERNEL=0
ASCEND_OPP_PATH=/usr/local/Ascend/nnae/latest/opp
LD_LIBRARY_PATH=/usr/local/Ascend/nnal/atb/latest/atb/cxx_abi_1/lib:/usr/local/Ascend/nnal/atb/latest/atb/cxx_abi_1/examples:/usr/local/Ascend/nnal/atb/latest/atb/cxx_abi_1/tests/atbopstest:/usr/local/Ascend/nnae/latest/lib64:/usr/local/Ascend/nnae/latest/lib64/plugin/opskernel:/usr/local/Ascend/nnae/latest/lib64/plugin/nnengine:/usr/local/Ascend/driver/lib64:/usr/local/Ascend/driver/lib64/common:/usr/local/Ascend/driver/lib64/driver:/usr/local/Ascend/ascend-toolkit/latest/tools/aml/lib64:/usr/local/Ascend/ascend-toolkit/latest/tools/aml/lib64/plugin:/usr/local/Ascend/ascend-toolkit/latest/lib64:/usr/local/Ascend/ascend-toolkit/latest/lib64/plugin/opskernel:/usr/local/Ascend/ascend-toolkit/latest/lib64/plugin/nnengine:/usr/local/Ascend/ascend-toolkit/latest/opp/built-in/op_impl/ai_core/tbe/op_tiling/lib/linux/x86_64:/usr/local/Ascend/driver/lib64:/usr/local/Ascend/driver/lib64/common:/usr/local/Ascend/driver/lib64/driver:/usr/local/Ascend/ascend-toolkit/latest/tools/aml/lib64:/usr/local/Ascend/ascend-toolkit/latest/tools/aml/lib64/plugin:/usr/local/Ascend/ascend-toolkit/latest/lib64:/usr/local/Ascend/ascend-toolkit/latest/lib64/plugin/opskernel:/usr/local/Ascend/ascend-toolkit/latest/lib64/plugin/nnengine:/usr/local/Ascend/ascend-toolkit/latest/opp/built-in/op_impl/ai_core/tbe/op_tiling/lib/linux/x86_64:/usr/local/Ascend/driver/lib64:/usr/local/Ascend/driver/lib64/common:/usr/local/Ascend/driver/lib64/driver:
ASCEND_AICPU_PATH=/usr/local/Ascend/nnae/latest
ATB_STREAM_SYNC_EVERY_OPERATION_ENABLE=0
ASCEND_HOME_PATH=/usr/local/Ascend/nnae/latest
ATB_MATMUL_SHUFFLE_K_ENABLE=1
ATB_WORKSPACE_MEM_ALLOC_ALG_TYPE=1
ATB_HOST_TILING_BUFFER_BLOCK_NUM=128
ATB_SHARE_MEMORY_NAME_SUFFIX=
TORCH_DEVICE_BACKEND_AUTOLOAD=1
PYTORCH_NVML_BASED_CUDA_CHECK=1
TORCHINDUCTOR_COMPILE_THREADS=1


NPU:
+--------------------------------------------------------------------------------------------------------+
| npu-smi v1.0                                     Version: 24.1.rc4.b999                                |
+-------------------------------+-----------------+------------------------------------------------------+
| NPU     Name                  | Health          | Power(W)     Temp(C)           Hugepages-Usage(page) |
| Chip    Device                | Bus-Id          | AICore(%)    Memory-Usage(MB)                        |
+===============================+=================+======================================================+
| 768     310P1                 | OK              | NA           51                0     / 0             |
| 0       0                     | 0000:04:00.0    | 0            1441 / 89608                            |
+-------------------------------+-----------------+------------------------------------------------------+
| 768     310P1                 | OK              | NA           48                0     / 0             |
| 1       1                     | 0000:04:00.0    | 0            1626 / 89085                            |
+===============================+=================+======================================================+
+-------------------------------+-----------------+------------------------------------------------------+
| NPU     Chip                  | Process id      | Process name             | Process memory(MB)        |
+===============================+=================+======================================================+
| No running processes found in NPU 768                                                                  |
+===============================+=================+======================================================+

CANN:
package_name=Ascend-cann-toolkit
version=8.5.0.alpha001
innerversion=V100R001C25B039
compatible_version=[V100R001C15],[V100R001C18],[V100R001C19],[V100R001C20],[V100R001C21],[V100R001C23]
arch=x86_64
os=linux
path=/usr/local/Ascend/ascend-toolkit/8.5.0.alpha001/x86_64-linux
```

</details>

### 🐛 Describe the bug

test script
```python
from vllm import LLM, SamplingParams

prompts = [
    "Hello, my name is",
    "The president of the United States is",
    "The capital of France is",
    "The future of AI is",
]

# Create a sampling params object.
sampling_params = SamplingParams(temperature=0.8, top_p=0.95)
# Create an LLM.
llm = LLM(model="/root/.cache/modelscope/hub/models/qwen/Qwen3-8B")

# Generate texts from the prompts.
outputs = llm.generate(prompts, sampling_params)
for output in outputs:
    prompt = output.prompt
    generated_text = output.outputs[0].text
    print(f"Prompt: {prompt!r}, Generated text: {generated_text!r}")
```

log
```output
INFO 11-26 11:42:38 [__init__.py:36] Available plugins for group vllm.platform_plugins:
INFO 11-26 11:42:38 [__init__.py:38] - ascend -> vllm_ascend:register
INFO 11-26 11:42:38 [__init__.py:41] All plugins in this group will be loaded. Set `VLLM_PLUGINS` to control which plugins to load.
INFO 11-26 11:42:38 [__init__.py:207] Platform plugin ascend is activated
/root/miniconda3/envs/vllm/lib/python3.11/site-packages/torch_npu/dynamo/torchair/__init__.py:8: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
  import pkg_resources
WARNING 11-26 11:42:40 [_custom_ops.py:20] Failed to import from vllm._C with ImportError('libcudart.so.12: cannot open shared object file: No such file or directory')
WARNING 11-26 11:42:40 [registry.py:582] Model architecture Qwen2VLForConditionalGeneration is already registered, and will be overwritten by the new model class vllm_ascend.models.qwen2_vl:AscendQwen2VLForConditionalGeneration.
WARNING 11-26 11:42:40 [registry.py:582] Model architecture Qwen3VLMoeForConditionalGeneration is already registered, and will be overwritten by the new model class vllm_ascend.models.qwen2_5_vl_without_padding:AscendQwen3VLMoeForConditionalGeneration.
WARNING 11-26 11:42:40 [registry.py:582] Model architecture Qwen3VLForConditionalGeneration is already registered, and will be overwritten by the new model class vllm_ascend.models.qwen2_5_vl_without_padding:AscendQwen3VLForConditionalGeneration.
WARNING 11-26 11:42:40 [registry.py:582] Model architecture Qwen2_5_VLForConditionalGeneration is already registered, and will be overwritten by the new model class vllm_ascend.models.qwen2_5_vl:AscendQwen2_5_VLForConditionalGeneration.
WARNING 11-26 11:42:40 [registry.py:582] Model architecture Qwen2_5OmniModel is already registered, and will be overwritten by the new model class vllm_ascend.models.qwen2_5_omni_thinker:AscendQwen2_5OmniThinkerForConditionalGeneration.
WARNING 11-26 11:42:40 [registry.py:582] Model architecture DeepseekV32ForCausalLM is already registered, and will be overwritten by the new model class vllm_ascend.models.deepseek_v3_2:CustomDeepseekV3ForCausalLM.
WARNING 11-26 11:42:40 [registry.py:582] Model architecture Qwen3NextForCausalLM is already registered, and will be overwritten by the new model class vllm_ascend.models.qwen3_next:CustomQwen3NextForCausalLM.
INFO 11-26 11:42:40 [utils.py:233] non-default args: {'disable_log_stats': True, 'model': '/root/.cache/modelscope/hub/models/qwen/Qwen3-8B'}
INFO 11-26 11:42:40 [importing.py:43] Triton is installed but 0 active driver(s) found (expected 1). Disabling Triton to prevent runtime errors.
INFO 11-26 11:42:40 [importing.py:63] Triton not installed or not compatible; certain GPU-related functions will not be available.
INFO 11-26 11:42:40 [model.py:547] Resolved architecture: Qwen3ForCausalLM
`torch_dtype` is deprecated! Use `dtype` instead!
INFO 11-26 11:42:40 [model.py:1510] Using max model len 40960
INFO 11-26 11:42:40 [scheduler.py:205] Chunked prefill is enabled with max_num_batched_tokens=8192.
INFO 11-26 11:42:40 [platform.py:213] PIECEWISE compilation enabled on NPU. use_inductor not supported - using only ACL Graph mode
INFO 11-26 11:42:40 [utils.py:441] Calculated maximum supported batch sizes for ACL graph: 48
WARNING 11-26 11:42:40 [utils.py:444] Currently, communication is performed using FFTS+ method, which reduces the number of available streams and, as a result, limits the range of runtime shapes that can be handled. To both improve communication performance and increase the number of supported shapes, set HCCL_OP_EXPANSION_MODE=AIV.
INFO 11-26 11:42:40 [utils.py:463] Adjusted ACL graph batch sizes for Qwen3ForCausalLM model (layers: 36): 67 → 48 sizes
WARNING 11-26 11:42:40 [platform.py:275] If chunked prefill or prefix caching is enabled, block size must be set to 128.
(EngineCore_DP0 pid=1255038) INFO 11-26 11:42:40 [core.py:644] Waiting for init message from front-end.
(EngineCore_DP0 pid=1255038) INFO 11-26 11:42:40 [core.py:77] Initializing a V1 LLM engine (v0.11.0) with config: model='/root/.cache/modelscope/hub/models/qwen/Qwen3-8B', speculative_config=None, tokenizer='/root/.cache/modelscope/hub/models/qwen/Qwen3-8B', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, tokenizer_revision=None, trust_remote_code=False, dtype=torch.bfloat16, max_seq_len=40960, download_dir=None, load_format=auto, tensor_parallel_size=1, pipeline_parallel_size=1, data_parallel_size=1, disable_custom_all_reduce=True, quantization=None, enforce_eager=False, kv_cache_dtype=auto, device_config=npu, structured_outputs_config=StructuredOutputsConfig(backend='auto', disable_fallback=False, disable_any_whitespace=False, disable_additional_properties=False, reasoning_parser=''), observability_config=ObservabilityConfig(show_hidden_metrics_for_version=None, otlp_traces_endpoint=None, collect_detailed_traces=None), seed=0, served_model_name=/root/.cache/modelscope/hub/models/qwen/Qwen3-8B, enable_prefix_caching=True, chunked_prefill_enabled=True, pooler_config=None, compilation_config={"level":3,"debug_dump_path":"","cache_dir":"","backend":"","custom_ops":["all"],"splitting_ops":["vllm.unified_attention","vllm.unified_attention_with_output","vllm.mamba_mixer2","vllm.mamba_mixer","vllm.short_conv","vllm.linear_attention","vllm.plamo2_mamba_mixer","vllm.gdn_attention","vllm.sparse_attn_indexer","vllm.unified_ascend_attention_with_output","vllm.mla_forward"],"use_inductor":false,"compile_sizes":[],"inductor_compile_config":{"enable_auto_functionalized_v2":false},"inductor_passes":{},"cudagraph_mode":1,"use_cudagraph":true,"cudagraph_num_of_warmups":1,"cudagraph_capture_sizes":[512,504,488,480,464,456,448,432,424,408,400,392,376,368,352,344,336,320,312,296,288,280,264,256,240,232,216,208,200,184,176,160,152,144,128,120,104,96,88,72,64,48,40,32,16,8,2,1],"cudagraph_copy_inputs":false,"full_cuda_graph":false,"use_inductor_graph_partition":false,"pass_config":{},"max_capture_size":512,"local_cache_dir":null}
[W1126 11:42:41.179122202 GetCANNInfo.cpp:52] Warning: Version: 8.5.0.alpha001 is invalid. (function operator())
(EngineCore_DP0 pid=1255038) INFO 11-26 11:42:45 [parallel_state.py:1208] rank 0 in world size 1 is assigned as DP rank 0, PP rank 0, TP rank 0, EP rank 0
(EngineCore_DP0 pid=1255038) INFO 11-26 11:42:52 [model_runner_v1.py:2641] Starting to load model /root/.cache/modelscope/hub/models/qwen/Qwen3-8B...
Loading safetensors checkpoint shards:   0% Completed | 0/5 [00:00<?, ?it/s]
Loading safetensors checkpoint shards:  20% Completed | 1/5 [00:02<00:08,  2.11s/it]
Loading safetensors checkpoint shards:  40% Completed | 2/5 [00:02<00:03,  1.32s/it]
Loading safetensors checkpoint shards:  60% Completed | 3/5 [00:05<00:03,  1.75s/it]
Loading safetensors checkpoint shards:  80% Completed | 4/5 [00:07<00:01,  1.95s/it]
Loading safetensors checkpoint shards: 100% Completed | 5/5 [00:09<00:00,  1.92s/it]
Loading safetensors checkpoint shards: 100% Completed | 5/5 [00:09<00:00,  1.85s/it]
(EngineCore_DP0 pid=1255038) 
(EngineCore_DP0 pid=1255038) INFO 11-26 11:43:03 [default_loader.py:267] Loading weights took 9.32 seconds
(EngineCore_DP0 pid=1255038) INFO 11-26 11:43:04 [model_runner_v1.py:2667] Loading model weights took 15.2684 GB
(EngineCore_DP0 pid=1255038) ERROR 11-26 11:43:04 [core.py:708] EngineCore failed to start.
(EngineCore_DP0 pid=1255038) ERROR 11-26 11:43:04 [core.py:708] Traceback (most recent call last):
(EngineCore_DP0 pid=1255038) ERROR 11-26 11:43:04 [core.py:708]   File "/root/miniconda3/envs/vllm/lib/python3.11/site-packages/vllm/v1/engine/core.py", line 699, in run_engine_core
(EngineCore_DP0 pid=1255038) ERROR 11-26 11:43:04 [core.py:708]     engine_core = EngineCoreProc(*args, **kwargs)
(EngineCore_DP0 pid=1255038) ERROR 11-26 11:43:04 [core.py:708]                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(EngineCore_DP0 pid=1255038) ERROR 11-26 11:43:04 [core.py:708]   File "/root/miniconda3/envs/vllm/lib/python3.11/site-packages/vllm/v1/engine/core.py", line 498, in __init__
(EngineCore_DP0 pid=1255038) ERROR 11-26 11:43:04 [core.py:708]     super().__init__(vllm_config, executor_class, log_stats,
(EngineCore_DP0 pid=1255038) ERROR 11-26 11:43:04 [core.py:708]   File "/root/miniconda3/envs/vllm/lib/python3.11/site-packages/vllm/v1/engine/core.py", line 92, in __init__
(EngineCore_DP0 pid=1255038) ERROR 11-26 11:43:04 [core.py:708]     self._initialize_kv_caches(vllm_config)
(EngineCore_DP0 pid=1255038) ERROR 11-26 11:43:04 [core.py:708]   File "/root/miniconda3/envs/vllm/lib/python3.11/site-packages/vllm/v1/engine/core.py", line 190, in _initialize_kv_caches
(EngineCore_DP0 pid=1255038) ERROR 11-26 11:43:04 [core.py:708]     self.model_executor.determine_available_memory())
(EngineCore_DP0 pid=1255038) ERROR 11-26 11:43:04 [core.py:708]     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(EngineCore_DP0 pid=1255038) ERROR 11-26 11:43:04 [core.py:708]   File "/root/miniconda3/envs/vllm/lib/python3.11/site-packages/vllm/v1/executor/abstract.py", line 85, in determine_available_memory
(EngineCore_DP0 pid=1255038) ERROR 11-26 11:43:04 [core.py:708]     return self.collective_rpc("determine_available_memory")
(EngineCore_DP0 pid=1255038) ERROR 11-26 11:43:04 [core.py:708]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(EngineCore_DP0 pid=1255038) ERROR 11-26 11:43:04 [core.py:708]   File "/root/miniconda3/envs/vllm/lib/python3.11/site-packages/vllm/executor/uniproc_executor.py", line 83, in collective_rpc
(EngineCore_DP0 pid=1255038) ERROR 11-26 11:43:04 [core.py:708]     return [run_method(self.driver_worker, method, args, kwargs)]
(EngineCore_DP0 pid=1255038) ERROR 11-26 11:43:04 [core.py:708]             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(EngineCore_DP0 pid=1255038) ERROR 11-26 11:43:04 [core.py:708]   File "/root/miniconda3/envs/vllm/lib/python3.11/site-packages/vllm/utils/__init__.py", line 3122, in run_method
(EngineCore_DP0 pid=1255038) ERROR 11-26 11:43:04 [core.py:708]     return func(*args, **kwargs)
(EngineCore_DP0 pid=1255038) ERROR 11-26 11:43:04 [core.py:708]            ^^^^^^^^^^^^^^^^^^^^^
(EngineCore_DP0 pid=1255038) ERROR 11-26 11:43:04 [core.py:708]   File "/root/miniconda3/envs/vllm/lib/python3.11/site-packages/vllm_ascend/worker/worker_v1.py", line 222, in determine_available_memory
(EngineCore_DP0 pid=1255038) ERROR 11-26 11:43:04 [core.py:708]     NPUPlatform.clear_npu_memory()
(EngineCore_DP0 pid=1255038) ERROR 11-26 11:43:04 [core.py:708]   File "/root/miniconda3/envs/vllm/lib/python3.11/site-packages/vllm_ascend/platform.py", line 118, in clear_npu_memory
(EngineCore_DP0 pid=1255038) ERROR 11-26 11:43:04 [core.py:708]     torch.npu.empty_cache()
(EngineCore_DP0 pid=1255038) ERROR 11-26 11:43:04 [core.py:708]   File "/root/miniconda3/envs/vllm/lib/python3.11/site-packages/torch_npu/npu/memory.py", line 159, in empty_cache
(EngineCore_DP0 pid=1255038) ERROR 11-26 11:43:04 [core.py:708]     torch_npu._C._npu_emptyCache()
(EngineCore_DP0 pid=1255038) ERROR 11-26 11:43:04 [core.py:708] RuntimeError: The Inner error is reported as above. The process exits for this inner error, and the current working operator name is Identity.
(EngineCore_DP0 pid=1255038) ERROR 11-26 11:43:04 [core.py:708] Since the operator is called asynchronously, the stacktrace may be inaccurate. If you want to get the accurate stacktrace, please set the environment variable ASCEND_LAUNCH_BLOCKING=1.
(EngineCore_DP0 pid=1255038) ERROR 11-26 11:43:04 [core.py:708] Note: ASCEND_LAUNCH_BLOCKING=1 will force ops to run in synchronous mode, resulting in performance degradation. Please unset ASCEND_LAUNCH_BLOCKING in time after debugging.
(EngineCore_DP0 pid=1255038) ERROR 11-26 11:43:04 [core.py:708] [ERROR] 2025-11-26-11:43:04 (PID:1255038, Device:0, RankID:-1) ERR00100 PTA call acl api failed.
(EngineCore_DP0 pid=1255038) ERROR 11-26 11:43:04 [core.py:708] [PID: 1255038] 2025-11-26-11:43:03.835.873 Unsupported_Operator(EZ3002): Optype [TransData] of Ops kernel [AIcoreEngine] is unsupported. Reason: [tbe-custom]:op type TransData is not found in this op store.[tbe-custom]:op type TransData is not found in this op store.[Dynamic shape check]: The format and dtype is not precisely equivalent to format and dtype in op information library.[Static shape check]:The format and dtype is not precisely equivalent to format and dtype in op information library..
(EngineCore_DP0 pid=1255038) ERROR 11-26 11:43:04 [core.py:708]         Possible Cause: The operator type is unsupported in the operator information library due to specification mismatch.
(EngineCore_DP0 pid=1255038) ERROR 11-26 11:43:04 [core.py:708]         Solution: Submit an issue to request for support at https://gitee.com/ascend, or remove this type of operators from your model.
(EngineCore_DP0 pid=1255038) ERROR 11-26 11:43:04 [core.py:708]         TraceBack (most recent call last):
(EngineCore_DP0 pid=1255038) ERROR 11-26 11:43:04 [core.py:708]         Optype [TransData] of Ops kernel [DNN_VM_HOST_CPU_OP_STORE] is unsupported. Reason: Transdata op, groups should be greater than 1, but now is 1.
(EngineCore_DP0 pid=1255038) ERROR 11-26 11:43:04 [core.py:708]         Optype [TransData] of Ops kernel [aicpu_ascend_kernel] is unsupported. Reason: Transdata op, groups should be greater than 1, but now is 1.
(EngineCore_DP0 pid=1255038) ERROR 11-26 11:43:04 [core.py:708]         No supported Ops kernel and engine are found for [trans_TransData_4], optype [TransData].
(EngineCore_DP0 pid=1255038) ERROR 11-26 11:43:04 [core.py:708]         Failed to select engine for [trans_TransData_4][TransData].[FUNC:operator()][FILE:engine_place.cc][LINE:150]
(EngineCore_DP0 pid=1255038) ERROR 11-26 11:43:04 [core.py:708]         RunAllSubgraphs failed, graph=online.[FUNC:RunAllSubgraphs][FILE:engine_place.cc][LINE:123]
(EngineCore_DP0 pid=1255038) ERROR 11-26 11:43:04 [core.py:708]         build graph failed, graph id:18, ret:4294967295[FUNC:BuildModelWithGraphId][FILE:ge_generator.cc][LINE:1594]
(EngineCore_DP0 pid=1255038) ERROR 11-26 11:43:04 [core.py:708]         [Build][SingleOpModel]call ge interface generator.BuildSingleOpModel failed. ge result = 4294967295[FUNC:ReportCallError][FILE:log_inner.cpp][LINE:162]
(EngineCore_DP0 pid=1255038) ERROR 11-26 11:43:04 [core.py:708]         [Build][Op]Fail to build op model[FUNC:ReportInnerError][FILE:log_inner.cpp][LINE:146]
(EngineCore_DP0 pid=1255038) ERROR 11-26 11:43:04 [core.py:708]         build op model failed, result = 500002[FUNC:ReportInnerError][FILE:log_inner.cpp][LINE:146]
(EngineCore_DP0 pid=1255038) ERROR 11-26 11:43:04 [core.py:708] 
(EngineCore_DP0 pid=1255038) Process EngineCore_DP0:
(EngineCore_DP0 pid=1255038) Traceback (most recent call last):
(EngineCore_DP0 pid=1255038)   File "/root/miniconda3/envs/vllm/lib/python3.11/multiprocessing/process.py", line 314, in _bootstrap
(EngineCore_DP0 pid=1255038)     self.run()
(EngineCore_DP0 pid=1255038)   File "/root/miniconda3/envs/vllm/lib/python3.11/multiprocessing/process.py", line 108, in run
(EngineCore_DP0 pid=1255038)     self._target(*self._args, **self._kwargs)
(EngineCore_DP0 pid=1255038)   File "/root/miniconda3/envs/vllm/lib/python3.11/site-packages/vllm/v1/engine/core.py", line 712, in run_engine_core
(EngineCore_DP0 pid=1255038)     raise e
(EngineCore_DP0 pid=1255038)   File "/root/miniconda3/envs/vllm/lib/python3.11/site-packages/vllm/v1/engine/core.py", line 699, in run_engine_core
(EngineCore_DP0 pid=1255038)     engine_core = EngineCoreProc(*args, **kwargs)
(EngineCore_DP0 pid=1255038)                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(EngineCore_DP0 pid=1255038)   File "/root/miniconda3/envs/vllm/lib/python3.11/site-packages/vllm/v1/engine/core.py", line 498, in __init__
(EngineCore_DP0 pid=1255038)     super().__init__(vllm_config, executor_class, log_stats,
(EngineCore_DP0 pid=1255038)   File "/root/miniconda3/envs/vllm/lib/python3.11/site-packages/vllm/v1/engine/core.py", line 92, in __init__
(EngineCore_DP0 pid=1255038)     self._initialize_kv_caches(vllm_config)
(EngineCore_DP0 pid=1255038)   File "/root/miniconda3/envs/vllm/lib/python3.11/site-packages/vllm/v1/engine/core.py", line 190, in _initialize_kv_caches
(EngineCore_DP0 pid=1255038)     self.model_executor.determine_available_memory())
(EngineCore_DP0 pid=1255038)     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(EngineCore_DP0 pid=1255038)   File "/root/miniconda3/envs/vllm/lib/python3.11/site-packages/vllm/v1/executor/abstract.py", line 85, in determine_available_memory
(EngineCore_DP0 pid=1255038)     return self.collective_rpc("determine_available_memory")
(EngineCore_DP0 pid=1255038)            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(EngineCore_DP0 pid=1255038)   File "/root/miniconda3/envs/vllm/lib/python3.11/site-packages/vllm/executor/uniproc_executor.py", line 83, in collective_rpc
(EngineCore_DP0 pid=1255038)     return [run_method(self.driver_worker, method, args, kwargs)]
(EngineCore_DP0 pid=1255038)             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(EngineCore_DP0 pid=1255038)   File "/root/miniconda3/envs/vllm/lib/python3.11/site-packages/vllm/utils/__init__.py", line 3122, in run_method
(EngineCore_DP0 pid=1255038)     return func(*args, **kwargs)
(EngineCore_DP0 pid=1255038)            ^^^^^^^^^^^^^^^^^^^^^
(EngineCore_DP0 pid=1255038)   File "/root/miniconda3/envs/vllm/lib/python3.11/site-packages/vllm_ascend/worker/worker_v1.py", line 222, in determine_available_memory
(EngineCore_DP0 pid=1255038)     NPUPlatform.clear_npu_memory()
(EngineCore_DP0 pid=1255038)   File "/root/miniconda3/envs/vllm/lib/python3.11/site-packages/vllm_ascend/platform.py", line 118, in clear_npu_memory
(EngineCore_DP0 pid=1255038)     torch.npu.empty_cache()
(EngineCore_DP0 pid=1255038)   File "/root/miniconda3/envs/vllm/lib/python3.11/site-packages/torch_npu/npu/memory.py", line 159, in empty_cache
(EngineCore_DP0 pid=1255038)     torch_npu._C._npu_emptyCache()
(EngineCore_DP0 pid=1255038) RuntimeError: The Inner error is reported as above. The process exits for this inner error, and the current working operator name is Identity.
(EngineCore_DP0 pid=1255038) Since the operator is called asynchronously, the stacktrace may be inaccurate. If you want to get the accurate stacktrace, please set the environment variable ASCEND_LAUNCH_BLOCKING=1.
(EngineCore_DP0 pid=1255038) Note: ASCEND_LAUNCH_BLOCKING=1 will force ops to run in synchronous mode, resulting in performance degradation. Please unset ASCEND_LAUNCH_BLOCKING in time after debugging.
(EngineCore_DP0 pid=1255038) [ERROR] 2025-11-26-11:43:04 (PID:1255038, Device:0, RankID:-1) ERR00100 PTA call acl api failed.
(EngineCore_DP0 pid=1255038) [PID: 1255038] 2025-11-26-11:43:03.835.873 Unsupported_Operator(EZ3002): Optype [TransData] of Ops kernel [AIcoreEngine] is unsupported. Reason: [tbe-custom]:op type TransData is not found in this op store.[tbe-custom]:op type TransData is not found in this op store.[Dynamic shape check]: The format and dtype is not precisely equivalent to format and dtype in op information library.[Static shape check]:The format and dtype is not precisely equivalent to format and dtype in op information library..
(EngineCore_DP0 pid=1255038)         Possible Cause: The operator type is unsupported in the operator information library due to specification mismatch.
(EngineCore_DP0 pid=1255038)         Solution: Submit an issue to request for support at https://gitee.com/ascend, or remove this type of operators from your model.
(EngineCore_DP0 pid=1255038)         TraceBack (most recent call last):
(EngineCore_DP0 pid=1255038)         Optype [TransData] of Ops kernel [DNN_VM_HOST_CPU_OP_STORE] is unsupported. Reason: Transdata op, groups should be greater than 1, but now is 1.
(EngineCore_DP0 pid=1255038)         Optype [TransData] of Ops kernel [aicpu_ascend_kernel] is unsupported. Reason: Transdata op, groups should be greater than 1, but now is 1.
(EngineCore_DP0 pid=1255038)         No supported Ops kernel and engine are found for [trans_TransData_4], optype [TransData].
(EngineCore_DP0 pid=1255038)         Failed to select engine for [trans_TransData_4][TransData].[FUNC:operator()][FILE:engine_place.cc][LINE:150]
(EngineCore_DP0 pid=1255038)         RunAllSubgraphs failed, graph=online.[FUNC:RunAllSubgraphs][FILE:engine_place.cc][LINE:123]
(EngineCore_DP0 pid=1255038)         build graph failed, graph id:18, ret:4294967295[FUNC:BuildModelWithGraphId][FILE:ge_generator.cc][LINE:1594]
(EngineCore_DP0 pid=1255038)         [Build][SingleOpModel]call ge interface generator.BuildSingleOpModel failed. ge result = 4294967295[FUNC:ReportCallError][FILE:log_inner.cpp][LINE:162]
(EngineCore_DP0 pid=1255038)         [Build][Op]Fail to build op model[FUNC:ReportInnerError][FILE:log_inner.cpp][LINE:146]
(EngineCore_DP0 pid=1255038)         build op model failed, result = 500002[FUNC:ReportInnerError][FILE:log_inner.cpp][LINE:146]
(EngineCore_DP0 pid=1255038) 
Traceback (most recent call last):
  File "/root/workspace/cai/LLM/example.py", line 13, in <module>
    llm = LLM(model="/root/.cache/modelscope/hub/models/qwen/Qwen3-8B")
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/vllm/lib/python3.11/site-packages/vllm/entrypoints/llm.py", line 297, in __init__
    self.llm_engine = LLMEngine.from_engine_args(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/vllm/lib/python3.11/site-packages/vllm/v1/engine/llm_engine.py", line 177, in from_engine_args
    return cls(vllm_config=vllm_config,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/vllm/lib/python3.11/site-packages/vllm/v1/engine/llm_engine.py", line 114, in __init__
    self.engine_core = EngineCoreClient.make_client(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/vllm/lib/python3.11/site-packages/vllm/v1/engine/core_client.py", line 80, in make_client
    return SyncMPClient(vllm_config, executor_class, log_stats)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/miniconda3/envs/vllm/lib/python3.11/site-packages/vllm/v1/engine/core_client.py", line 602, in __init__
    super().__init__(
  File "/root/miniconda3/envs/vllm/lib/python3.11/site-packages/vllm/v1/engine/core_client.py", line 448, in __init__
    with launch_core_engines(vllm_config, executor_class,
  File "/root/miniconda3/envs/vllm/lib/python3.11/contextlib.py", line 144, in __exit__
    next(self.gen)
  File "/root/miniconda3/envs/vllm/lib/python3.11/site-packages/vllm/v1/engine/utils.py", line 732, in launch_core_engines
    wait_for_engine_startup(
  File "/root/miniconda3/envs/vllm/lib/python3.11/site-packages/vllm/v1/engine/utils.py", line 785, in wait_for_engine_startup
    raise RuntimeError("Engine core initialization failed. "
RuntimeError: Engine core initialization failed. See root cause above. Failed core proc(s): {}
[ERROR] 2025-11-26-11:43:04 (PID:1254605, Device:-1, RankID:-1) ERR99999 UNKNOWN applicaiton exception
```

**Comment by zzzhang-ai** [comment]
Did u solve this problem? I encountered the same situation.

**Comment by JeanBaptiste-dlb** [comment]
I have similar problem Qwen3 0.6B being able to load with 1024 tokens of KV cache using vllm 0.11.0 but not even able to load the model weights in vllm 0.11.2. with 16Gb of free space on a L40 GPU running this command.

logs for 0.11.0:
```
stream closed EOF for models-staging/models-staging-qwen0b6-5fc87c465d-8cqt7 (model-download)
model-download ⚠️  Warning: 'huggingface-cli download' is deprecated. Use 'hf download' instead.
model-download 
Fetching 10 files:   0%|          | 0/10 [00:00<?, ?it/s]
Fetching 10 files: 100%|██████████| 10/10 [00:00<00:00, 116832.98it/s]
model-download /root/.cache/huggingface/hub/models--Qwen--Qwen3-0.6B/snapshots/c1899de289a04d12100db370d81485cdf75e47ca
qwen0b6 INFO 11-28 05:12:35 [__init__.py:216] Automatically detected platform cuda.
qwen0b6 (APIServer pid=1) INFO 11-28 05:12:41 [api_server.py:1839] vLLM API server version 0.11.0
qwen0b6 (APIServer pid=1) INFO 11-28 05:12:41 [utils.py:233] non-default args: {'model_tag': 'Qwen/Qwen3-0.6B', 'trust_remote_code': True, 'dtype': 'float16', 'max_model_len': 1024, 'enforce_eager': True, 'gpu_memory_utilization': 0.3, 'max_num_batched_tokens': 1024, 'max_num_seqs': 1, 'enable_chunked_prefill': True}
qwen0b6 (APIServer pid=1) The argument `trust_remote_code` is to be used with Auto classes. It has no effect here and is ignored.
qwen0b6 (APIServer pid=1) `torch_dtype` is deprecated! Use `dtype` instead!
qwen0b6 (APIServer pid=1) INFO 11-28 05:12:48 [model.py:547] Resolved architecture: Qwen3ForCausalLM
qwen0b6 (APIServer pid=1) WARNING 11-28 05:12:48 [model.py:1733] Casting torch.bfloat16 to torch.float16.
qwen0b6 (APIServer pid=1) INFO 11-28 05:12:48 [model.py:1510] Using max model len 1024
qwen0b6 (APIServer pid=1) INFO 11-28 05:12:49 [scheduler.py:205] Chunked prefill is enabled with max_num_batched_tokens=1024.
qwen0b6 (APIServer pid=1) INFO 11-28 05:12:49 [__init__.py:381] Cudagraph is disabled under eager mode
qwen0b6 INFO 11-28 05:12:52 [__init__.py:216] Automatically detected platform cuda.
qwen0b6 (EngineCore_DP0 pid=345) INFO 11-28 05:12:55 [core.py:644] Waiting for init message from front-end.
qwen0b6 (EngineCore_DP0 pid=345) INFO 11-28 05:12:55 [core.py:77] Initializing a V1 LLM engine (v0.11.0) with config: model='Qwen/Qwen3-0.6B', speculative_config=None, tokenizer='Qwen/Qwen3-0.6B', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, tokenizer_revision=None, trust_remote_code=True, dtype=torch.float16, max_seq_len=1024, download_dir=None, load_format=auto, tensor_parallel_size=1, pipeline_parallel_size=1, data_parallel_size=1, disable_custom_all_reduce=False, quantization=None, enforce_eager=True, kv_cache_dtype=auto, device_config=cuda, structured_outputs_config=StructuredOutputsConfig(backend='auto', disable_fallback=False, disable_any_whitespace=False, disable_additional_properties=False, reasoning_parser=''), observability_config=ObservabilityConfig(show_hidden_metrics_for_version=None, otlp_traces_endpoint=None, collect_detailed_traces=None), seed=0, served_model_name=Qwen/Qwen3-0.6B, enable_prefix_caching=True, chunked_prefill_enabled=True, pooler_config=None, compilation_config={"level":0,"debug_dump_path":"","cache_dir":"","backend":"","custom_ops":],"splitting_ops":null,"use_inductor":true,"compile_sizes":],"inductor_compile_config":{"enable_auto_functionalized_v2":false},"inductor_passes":{},"cudagraph_mode":0,"use_cudagraph":true,"cudagraph_num_of_warmups":0,"cudagraph_capture_sizes":],"cudagraph_copy_inputs":false,"full_cuda_graph":false,"use_inductor_graph_partition":false,"pass_config":{},"max_capture_size":0,"local_cache_dir":null}
qwen0b6 (EngineCore_DP0 pid=345) W1128 05:12:55.853000 345 torch/utils/cpp_extension.py:2425] TORCH_CUDA_ARCH_LIST is not set, all archs for visible cards are included for compilation. 
qwen0b6 (EngineCore_DP0 pid=345) W1128 05:12:55.853000 345 torch/utils/cpp_extension.py:2425] If this is not desired, please set os.environ['TORCH_CUDA_ARCH_LIST'] to specific architectures.
qwen0b6 [Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
qwen0b6 [Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
qwen0b6 [Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
qwen0b6 [Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
qwen0b6 [Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
qwen0b6 [Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
qwen0b6 (EngineCore_DP0 pid=345) INFO 11-28 05:12:56 [parallel_state.py:1208] rank 0 in world size 1 is assigned as DP rank 0, PP rank 0, TP rank 0, EP rank 0
qwen0b6 (EngineCore_DP0 pid=345) INFO 11-28 05:12:57 [topk_topp_sampler.py:55] Using FlashInfer for top-p & top-k sampling.
qwen0b6 (EngineCore_DP0 pid=345) INFO 11-28 05:12:57 [gpu_model_runner.py:2602] Starting to load model Qwen/Qwen3-0.6B...
qwen0b6 (EngineCore_DP0 pid=345) INFO 11-28 05:12:57 [gpu_model_runner.py:2634] Loading model from scratch...
qwen0b6 (EngineCore_DP0 pid=345) INFO 11-28 05:12:57 [cuda.py:366] Using Flash Attention backend on V1 engine.
qwen0b6 (EngineCore_DP0 pid=345) INFO 11-28 05:12:58 [weight_utils.py:392] Using model weights format ['*.safetensors']
qwen0b6 (EngineCore_DP0 pid=345) INFO 11-28 05:12:58 [weight_utils.py:450] No model.safetensors.index.json found in remote.
qwen0b6 (EngineCore_DP0 pid=345) 
Loading safetensors checkpoint shards:   0% Completed | 0/1 [00:00<?, ?it/s]
qwen0b6 (EngineCore_DP0 pid=345) 
Loading safetensors checkpoint shards: 100% Completed | 1/1 [00:42<00:00, 42.55s/it]
qwen0b6 (EngineCore_DP0 pid=345) 
Loading safetensors checkpoint shards: 100% Completed | 1/1 [00:42<00:00, 42.55s/it]
qwen0b6 (EngineCore_DP0 pid=345) 
qwen0b6 (EngineCore_DP0 pid=345) INFO 11-28 05:13:41 [default_loader.py:267] Loading weights took 42.96 seconds
qwen0b6 (EngineCore_DP0 pid=345) INFO 11-28 05:13:42 [gpu_model_runner.py:2653] Model loading took 1.1201 GiB and 43.601848 seconds
qwen0b6 (EngineCore_DP0 pid=345) INFO 11-28 05:13:43 [gpu_worker.py:298] Available KV cache memory: 12.13 GiB
qwen0b6 (EngineCore_DP0 pid=345) INFO 11-28 05:13:43 [kv_cache_utils.py:1087] GPU KV cache size: 113,552 tokens
qwen0b6 (EngineCore_DP0 pid=345) INFO 11-28 05:13:43 [kv_cache_utils.py:1091] Maximum concurrency for 1,024 tokens per request: 110.89x
qwen0b6 (EngineCore_DP0 pid=345) WARNING 11-28 05:13:43 [cudagraph_dispatcher.py:106] cudagraph dispatching keys are not initialized. No cudagraph will be used.
qwen0b6 (EngineCore_DP0 pid=345) INFO 11-28 05:13:43 [core.py:210] init engine (profile, create kv cache, warmup model) took 1.40 seconds
qwen0b6 (EngineCore_DP0 pid=345) INFO 11-28 05:13:44 [__init__.py:381] Cudagraph is disabled under eager mode
qwen0b6 (APIServer pid=1) INFO 11-28 05:13:44 [loggers.py:147] Engine 000: vllm cache_config_info with initialization after num_gpu_blocks is: 7097
qwen0b6 (APIServer pid=1) INFO 11-28 05:13:44 [api_server.py:1634] Supported_tasks: ['generate']
qwen0b6 (APIServer pid=1) WARNING 11-28 05:13:44 [model.py:1389] Default sampling parameters have been overridden by the model's Hugging Face generation config recommended from the model creator. If this is not intended, please relaunch vLLM instance with `--generation-config vllm`.
qwen0b6 (APIServer pid=1) INFO 11-28 05:13:44 [serving_responses.py:137] Using default chat sampling params from model: {'temperature': 0.6, 'top_k': 20, 'top_p': 0.95}
qwen0b6 (APIServer pid=1) INFO 11-28 05:13:44 [serving_chat.py:139] Using default chat sampling params from model: {'temperature': 0.6, 'top_k': 20, 'top_p': 0.95}
qwen0b6 (APIServer pid=1) INFO 11-28 05:13:44 [serving_completion.py:76] Using default completion sampling params from model: {'temperature': 0.6, 'top_k': 20, 'top_p': 0.95}
qwen0b6 (APIServer pid=1) INFO 11-28 05:13:44 [api_server.py:1912] Starting vLLM API server 0 on http://0.0.0.0:8000
qwen0b6 (APIServer pid=1) INFO 11-28 05:13:44 [launcher.py:34] Available routes are:
qwen0b6 (APIServer pid=1) INFO 11-28 05:13:44 [launcher.py:42] Route: /openapi.json, Methods: GET, HEAD
qwen0b6 (APIServer pid=1) INFO 11-28 05:13:44 [launcher.py:42] Route: /docs, Methods: GET, HEAD
qwen0b6 (APIServer pid=1) INFO 11-28 05:13:44 [launcher.py:42] Route: /docs/oauth2-redirect, Methods: GET, HEAD
qwen0b6 (APIServer pid=1) INFO 11-28 05:13:44 [launcher.py:42] Route: /redoc, Methods: GET, HEAD
qwen0b6 (APIServer pid=1) INFO 11-28 05:13:44 [launcher.py:42] Route: /health, Methods: GET
qwen0b6 (APIServer pid=1) INFO 11-28 05:13:44 [launcher.py:42] Route: /load, Methods: GET
qwen0b6 (APIServer pid=1) INFO 11-28 05:13:44 [launcher.py:42] Route: /ping, Methods: POST
qwen0b6 (APIServer pid=1) INFO 11-28 05:13:44 [launcher.py:42] Route: /ping, Methods: GET
qwen0b6 (APIServer pid=1) INFO 11-28 05:13:44 [launcher.py:42] Route: /tokenize, Methods: POST
qwen0b6 (APIServer pid=1) INFO 11-28 05:13:44 [launcher.py:42] Route: /detokenize, Methods: POST
qwen0b6 (APIServer pid=1) INFO 11-28 05:13:44 [launcher.py:42] Route: /v1/models, Methods: GET
qwen0b6 (APIServer pid=1) INFO 11-28 05:13:44 [launcher.py:42] Route: /version, Methods: GET
qwen0b6 (APIServer pid=1) INFO 11-28 05:13:44 [launcher.py:42] Route: /v1/responses, Methods: POST
qwen0b6 (APIServer pid=1) INFO 11-28 05:13:44 [launcher.py:42] Route: /v1/responses/{response_id}, Methods: GET
qwen0b6 (APIServer pid=1) INFO 11-28 05:13:44 [launcher.py:42] Route: /v1/responses/{response_id}/cancel, Methods: POST
qwen0b6 (APIServer pid=1) INFO 11-28 05:13:44 [launcher.py:42] Route: /v1/chat/completions, Methods: POST
qwen0b6 (APIServer pid=1) INFO 11-28 05:13:44 [launcher.py:42] Route: /v1/completions, Methods: POST
qwen0b6 (APIServer pid=1) INFO 11-28 05:13:44 [launcher.py:42] Route: /v1/embeddings, Methods: POST
qwen0b6 (APIServer pid=1) INFO 11-28 05:13:44 [launcher.py:42] Route: /pooling, Methods: POST
qwen0b6 (APIServer pid=1) INFO 11-28 05:13:44 [launcher.py:42] Route: /classify, Methods: POST
qwen0b6 (APIServer pid=1) INFO 11-28 05:13:44 [launcher.py:42] Route: /score, Methods: POST
qwen0b6 (APIServer pid=1) INFO 11-28 05:13:44 [launcher.py:42] Route: /v1/score, Methods: POST
qwen0b6 (APIServer pid=1) INFO 11-28 05:13:44 [launcher.py:42] Route: /v1/audio/transcriptions, Methods: POST
qwen0b6 (APIServer pid=1) INFO 11-28 05:13:44 [launcher.py:42] Route: /v1/audio/translations, Methods: POST
qwen0b6 (APIServer pid=1) INFO 11-28 05:13:44 [launcher.py:42] Route: /rerank, Methods: POST
qwen0b6 (APIServer pid=1) INFO 11-28 05:13:44 [launcher.py:42] Route: /v1/rerank, Methods: POST
qwen0b6 (APIServer pid=1) INFO 11-28 05:13:44 [launcher.py:42] Route: /v2/rerank, Methods: POST
qwen0b6 (APIServer pid=1) INFO 11-28 05:13:44 [launcher.py:42] Route: /scale_elastic_ep, Methods: POST
qwen0b6 (APIServer pid=1) INFO 11-28 05:13:44 [launcher.py:42] Route: /is_scaling_elastic_ep, Methods: POST
qwen0b6 (APIServer pid=1) INFO 11-28 05:13:44 [launcher.py:42] Route: /invocations, Methods: POST
qwen0b6 (APIServer pid=1) INFO 11-28 05:13:44 [launcher.py:42] Route: /metrics, Methods: GET
qwen0b6 (APIServer pid=1) INFO:     Started server process [1]
qwen0b6 (APIServer pid=1) INFO:     Waiting for application startup.
qwen0b6 (APIServer pid=1) INFO:     Application startup complete.
qwen0b6 (APIServer pid=1) INFO:     10.10.0.30:8756 - "GET /health HTTP/1.1" 200 OK
stream closed EOF for models-staging/models-staging-qwen0b6-5fc87c465d-8cqt7 (mount-permissions)
qwen0b6 (APIServer pid=1) INFO:     10.10.0.30:24770 - "GET /health HTTP/1.1" 200 OK
```

logs for 0.11.2 exact same config and same space available on gpu:

```
models-staging-qwen0b6-6bb7684b4-vqnff model-download ⚠️  Warning: 'huggingface-cli download' is deprecated. Use 'hf download' instead.
models-staging-qwen0b6-6bb7684b4-vqnff model-download 
Fetching 10 files:   0%|          | 0/10 [00:00<?, ?it/s]
Fetching 10 files: 100%|██████████| 10/10 [00:00<00:00, 151418.92it/s]
models-staging-qwen0b6-6bb7684b4-vqnff model-download /root/.cache/huggingface/hub/models--Qwen--Qwen3-0.6B/snapshots/c1899de289a04d12100db370d81485cdf75e47ca
stream closed EOF for models-staging/models-staging-qwen0b6-6bb7684b4-vqnff (model-download)
stream closed EOF for models-staging/models-staging-qwen0b6-6bb7684b4-vqnff (mount-permissions)
models-staging-qwen0b6-6bb7684b4-vqnff qwen0b6 INFO 11-28 05:15:48 [scheduler.py:216] Chunked prefill is enabled with max_num_batched_tokens=2048.
models-staging-qwen0b6-6bb7684b4-vqnff qwen0b6 (APIServer pid=1) INFO 11-28 05:15:49 [api_server.py:1977] vLLM API server version 0.11.2
models-staging-qwen0b6-6bb7684b4-vqnff qwen0b6 (APIServer pid=1) INFO 11-28 05:15:49 [utils.py:253] non-default args: {'model_tag': 'Qwen/Qwen3-0.6B', 'trust_remote_code': True, 'dtype': 'float16', 'max_model_len': 1024, 'enforce_eager': True, 'gpu_memory_utilization': 0.3, 'max_num_batched_tokens': 1024, 'max_num_seqs': 1, 'enable_chunked_prefill': True}
models-staging-qwen0b6-6bb7684b4-vqnff qwen0b6 (APIServer pid=1) The argument `trust_remote_code` is to be used with Auto classes. It has no effect here and is ignored.
models-staging-qwen0b6-6bb7684b4-vqnff qwen0b6 (APIServer pid=1) INFO 11-28 05:15:55 [model.py:631] Resolved architecture: Qwen3ForCausalLM
models-staging-qwen0b6-6bb7684b4-vqnff qwen0b6 (APIServer pid=1) WARNING 11-28 05:15:55 [model.py:1971] Casting torch.bfloat16 to torch.float16.
models-staging-qwen0b6-6bb7684b4-vqnff qwen0b6 (APIServer pid=1) INFO 11-28 05:15:55 [model.py:1745] Using max model len 1024
models-staging-qwen0b6-6bb7684b4-vqnff qwen0b6 (APIServer pid=1) INFO 11-28 05:15:56 [scheduler.py:216] Chunked prefill is enabled with max_num_batched_tokens=1024.
models-staging-qwen0b6-6bb7684b4-vqnff qwen0b6 (APIServer pid=1) INFO 11-28 05:15:56 [vllm.py:500] Cudagraph is disabled under eager mode
models-staging-qwen0b6-6bb7684b4-vqnff qwen0b6 (EngineCore_DP0 pid=346) INFO 11-28 05:16:02 [core.py:93] Initializing a V1 LLM engine (v0.11.2) with config: model='Qwen/Qwen3-0.6B', speculative_config=None, tokenizer='Qwen/Qwen3-0.6B', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, tokenizer_revision=None, trust_remote_code=True, dtype=torch.float16, max_seq_len=1024, download_dir=None, load_format=auto, tensor_parallel_size=1, pipeline_parallel_size=1, data_parallel_size=1, disable_custom_all_reduce=False, quantization=None, enforce_eager=True, kv_cache_dtype=auto, device_config=cuda, structured_outputs_config=StructuredOutputsConfig(backend='auto', disable_fallback=False, disable_any_whitespace=False, disable_additional_properties=False, reasoning_parser='', reasoning_parser_plugin='', enable_in_reasoning=False), observability_config=ObservabilityConfig(show_hidden_metrics_for_version=None, otlp_traces_endpoint=None, collect_detailed_traces=None), seed=0, served_model_name=Qwen/Qwen3-0.6B, enable_prefix_caching=True, enable_chunked_prefill=True, pooler_config=None, compilation_config={'level': None, 'mode': <CompilationMode.NONE: 0>, 'debug_dump_path': None, 'cache_dir': '', 'compile_cache_save_format': 'binary', 'backend': 'inductor', 'custom_ops': ['all'], 'splitting_ops': None, 'compile_mm_encoder': False, 'use_inductor': None, 'compile_sizes': ], 'inductor_compile_config': {'enable_auto_functionalized_v2': False, 'combo_kernels': True, 'benchmark_combo_kernel': True}, 'inductor_passes': {}, 'cudagraph_mode': <CUDAGraphMode.NONE: 0>, 'cudagraph_num_of_warmups': 0, 'cudagraph_capture_sizes': ], 'cudagraph_copy_inputs': False, 'cudagraph_specialize_lora': True, 'use_inductor_graph_partition': False, 'pass_config': {}, 'max_cudagraph_capture_size': 0, 'local_cache_dir': None}
models-staging-qwen0b6-6bb7684b4-vqnff qwen0b6 (EngineCore_DP0 pid=346) INFO 11-28 05:16:03 [parallel_state.py:1208] world_size=1 rank=0 local_rank=0 distributed_init_method=tcp://172.18.31.163:36471 backend=nccl
models-staging-qwen0b6-6bb7684b4-vqnff qwen0b6 [Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
models-staging-qwen0b6-6bb7684b4-vqnff qwen0b6 [Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
models-staging-qwen0b6-6bb7684b4-vqnff qwen0b6 [Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
models-staging-qwen0b6-6bb7684b4-vqnff qwen0b6 [Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
models-staging-qwen0b6-6bb7684b4-vqnff qwen0b6 [Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
models-staging-qwen0b6-6bb7684b4-vqnff qwen0b6 [Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
models-staging-qwen0b6-6bb7684b4-vqnff qwen0b6 (EngineCore_DP0 pid=346) INFO 11-28 05:16:03 [parallel_state.py:1394] rank 0 in world size 1 is assigned as DP rank 0, PP rank 0, TP rank 0, EP rank 0
models-staging-qwen0b6-6bb7684b4-vqnff qwen0b6 (EngineCore_DP0 pid=346) INFO 11-28 05:16:03 [gpu_model_runner.py:3259] Starting to load model Qwen/Qwen3-0.6B...
models-staging-qwen0b6-6bb7684b4-vqnff qwen0b6 (APIServer pid=1) Traceback (most recent call last):
models-staging-qwen0b6-6bb7684b4-vqnff qwen0b6 (APIServer pid=1)   File "/usr/local/bin/vllm", line 10, in <module>
models-staging-qwen0b6-6bb7684b4-vqnff qwen0b6 (APIServer pid=1)     sys.exit(main())
models-staging-qwen0b6-6bb7684b4-vqnff qwen0b6 (APIServer pid=1)              ^^^^^^
models-staging-qwen0b6-6bb7684b4-vqnff qwen0b6 (APIServer pid=1)   File "/usr/local/lib/python3.12/dist-packages/vllm/entrypoints/cli/main.py", line 73, in main
models-staging-qwen0b6-6bb7684b4-vqnff qwen0b6 (APIServer pid=1)     args.dispatch_function(args)
models-staging-qwen0b6-6bb7684b4-vqnff qwen0b6 (APIServer pid=1)   File "/usr/local/lib/python3.12/dist-packages/vllm/entrypoints/cli/serve.py", line 60, in cmd
models-staging-qwen0b6-6bb7684b4-vqnff qwen0b6 (APIServer pid=1)     uvloop.run(run_server(args))
models-staging-qwen0b6-6bb7684b4-vqnff qwen0b6 (APIServer pid=1)   File "/usr/local/lib/python3.12/dist-packages/uvloop/__init__.py", line 96, in run
models-staging-qwen0b6-6bb7684b4-vqnff qwen0b6 (APIServer pid=1)     return __asyncio.run(
models-staging-qwen0b6-6bb7684b4-vqnff qwen0b6 (APIServer pid=1)            ^^^^^^^^^^^^^^
models-staging-qwen0b6-6bb7684b4-vqnff qwen0b6 (APIServer pid=1)   File "/usr/lib/python3.12/asyncio/runners.py", line 195, in run
models-staging-qwen0b6-6bb7684b4-vqnff qwen0b6 (APIServer pid=1)     return runner.run(main)
models-staging-qwen0b6-6bb7684b4-vqnff qwen0b6 (APIServer pid=1)            ^^^^^^^^^^^^^^^^
models-staging-qwen0b6-6bb7684b4-vqnff qwen0b6 (APIServer pid=1)   File "/usr/lib/python3.12/asyncio/runners.py", line 118, in run
models-staging-qwen0b6-6bb7684b4-vqnff qwen0b6 (APIServer pid=1)     return self._loop.run_until_complete(task)
models-staging-qwen0b6-6bb7684b4-vqnff qwen0b6 (APIServer pid=1)            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
models-staging-qwen0b6-6bb7684b4-vqnff qwen0b6 (APIServer pid=1)   File "uvloop/loop.pyx", line 1518, in uvloop.loop.Loop.run_until_complete
models-staging-qwen0b6-6bb7684b4-vqnff qwen0b6 (APIServer pid=1)   File "/usr/local/lib/python3.12/dist-packages/uvloop/__init__.py", line 48, in wrapper
models-staging-qwen0b6-6bb7684b4-vqnff qwen0b6 (APIServer pid=1)     return await main
models-staging-qwen0b6-6bb7684b4-vqnff qwen0b6 (APIServer pid=1)            ^^^^^^^^^^
models-staging-qwen0b6-6bb7684b4-vqnff qwen0b6 (APIServer pid=1)   File "/usr/local/lib/python3.12/dist-packages/vllm/entrypoints/openai/api_server.py", line 2024, in run_server
models-staging-qwen0b6-6bb7684b4-vqnff qwen0b6 (APIServer pid=1)     await run_server_worker(listen_address, sock, args, **uvicorn_kwargs)
models-staging-qwen0b6-6bb7684b4-vqnff qwen0b6 (APIServer pid=1)   File "/usr/local/lib/python3.12/dist-packages/vllm/entrypoints/openai/api_server.py", line 2043, in run_server_worker
models-staging-qwen0b6-6bb7684b4-vqnff qwen0b6 (APIServer pid=1)     async with build_async_engine_client(
models-staging-qwen0b6-6bb7684b4-vqnff qwen0b6 (APIServer pid=1)                ^^^^^^^^^^^^^^^^^^^^^^^^^^
models-staging-qwen0b6-6bb7684b4-vqnff qwen0b6 (APIServer pid=1)   File "/usr/lib/python3.12/contextlib.py", line 210, in __aenter__
models-staging-qwen0b6-6bb7684b4-vqnff qwen0b6 (APIServer pid=1)     return await anext(self.gen)
models-staging-qwen0b6-6bb7684b4-vqnff qwen0b6 (APIServer pid=1)            ^^^^^^^^^^^^^^^^^^^^^
models-staging-qwen0b6-6bb7684b4-vqnff qwen0b6 (APIServer pid=1)   File "/usr/local/lib/python3.12/dist-packages/vllm/entrypoints/openai/api_server.py", line 195, in build_async_engine_client
models-staging-qwen0b6-6bb7684b4-vqnff qwen0b6 (APIServer pid=1)     async with build_async_engine_client_from_engine_args(
models-staging-qwen0b6-6bb7684b4-vqnff qwen0b6 (APIServer pid=1)                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
models-staging-qwen0b6-6bb7684b4-vqnff qwen0b6 (APIServer pid=1)   File "/usr/lib/python3.12/contextlib.py", line 210, in __aenter__
models-staging-qwen0b6-6bb7684b4-vqnff qwen0b6 (APIServer pid=1)     return await anext(self.gen)
models-staging-qwen0b6-6bb7684b4-vqnff qwen0b6 (APIServer pid=1)            ^^^^^^^^^^^^^^^^^^^^^
models-staging-qwen0b6-6bb7684b4-vqnff qwen0b6 (APIServer pid=1)   File "/usr/local/lib/python3.12/dist-packages/vllm/entrypoints/openai/api_server.py", line 236, in build_async_engine_client_from_engine_args
models-staging-qwen0b6-6bb7684b4-vqnff qwen0b6 (APIServer pid=1)     async_llm = AsyncLLM.from_vllm_config(
models-staging-qwen0b6-6bb7684b4-vqnff qwen0b6 (APIServer pid=1)                 ^^^^^^^^^^^^^^^^^^^^^^^^^^
models-staging-qwen0b6-6bb7684b4-vqnff qwen0b6 (APIServer pid=1)   File "/usr/local/lib/python3.12/dist-packages/vllm/utils/func_utils.py", line 116, in inner
models-staging-qwen0b6-6bb7684b4-vqnff qwen0b6 (APIServer pid=1)     return fn(*args, **kwargs)
models-staging-qwen0b6-6bb7684b4-vqnff qwen0b6 (APIServer pid=1)            ^^^^^^^^^^^^^^^^^^^
models-staging-qwen0b6-6bb7684b4-vqnff qwen0b6 (APIServer pid=1)   File "/usr/local/lib/python3.12/dist-packages/vllm/v1/engine/async_llm.py", line 203, in from_vllm_config
models-staging-qwen0b6-6bb7684b4-vqnff qwen0b6 (APIServer pid=1)     return cls(
models-staging-qwen0b6-6bb7684b4-vqnff qwen0b6 (APIServer pid=1)            ^^^^
models-staging-qwen0b6-6bb7684b4-vqnff qwen0b6 (APIServer pid=1)   File "/usr/local/lib/python3.12/dist-packages/vllm/v1/engine/async_llm.py", line 133, in __init__
models-staging-qwen0b6-6bb7684b4-vqnff qwen0b6 (APIServer pid=1)     self.engine_core = EngineCoreClient.make_async_mp_client(
models-staging-qwen0b6-6bb7684b4-vqnff qwen0b6 (APIServer pid=1)                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
models-staging-qwen0b6-6bb7684b4-vqnff qwen0b6 (APIServer pid=1)   File "/usr/local/lib/python3.12/dist-packages/vllm/v1/engine/core_client.py", line 121, in make_async_mp_client
models-staging-qwen0b6-6bb7684b4-vqnff qwen0b6 (APIServer pid=1)     return AsyncMPClient(*client_args)
models-staging-qwen0b6-6bb7684b4-vqnff qwen0b6 (APIServer pid=1)            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
models-staging-qwen0b6-6bb7684b4-vqnff qwen0b6 (APIServer pid=1)   File "/usr/local/lib/python3.12/dist-packages/vllm/v1/engine/core_client.py", line 808, in __init__
models-staging-qwen0b6-6bb7684b4-vqnff qwen0b6 (APIServer pid=1)     super().__init__(
models-staging-qwen0b6-6bb7684b4-vqnff qwen0b6 (APIServer pid=1)   File "/usr/local/lib/python3.12/dist-packages/vllm/v1/engine/core_client.py", line 469, in __init__
models-staging-qwen0b6-6bb7684b4-vqnff qwen0b6 (APIServer pid=1)     with launch_core_engines(vllm_config, executor_class, log_stats) as (
models-staging-qwen0b6-6bb7684b4-vqnff qwen0b6 (APIServer pid=1)          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
models-staging-qwen0b6-6bb7684b4-vqnff qwen0b6 (APIServer pid=1)   File "/usr/lib/python3.12/contextlib.py", line 144, in __exit__
models-staging-qwen0b6-6bb7684b4-vqnff qwen0b6 (APIServer pid=1)     next(self.gen)
models-staging-qwen0b6-6bb7684b4-vqnff qwen0b6 (APIServer pid=1)   File "/usr/local/lib/python3.12/dist-packages/vllm/v1/engine/utils.py", line 907, in launch_core_engines
models-staging-qwen0b6-6bb7684b4-vqnff qwen0b6 (APIServer pid=1)     wait_for_engine_startup(
models-staging-qwen0b6-6bb7684b4-vqnff qwen0b6 (APIServer pid=1)   File "/usr/local/lib/python3.12/dist-packages/vllm/v1/engine/utils.py", line 964, in wait_for_engine_startup
models-staging-qwen0b6-6bb7684b4-vqnff qwen0b6 (APIServer pid=1)     raise RuntimeError(
models-staging-qwen0b6-6bb7684b4-vqnff qwen0b6 (APIServer pid=1) RuntimeError: Engine core initialization failed. See root cause above. Failed core proc(s): {}
```

**Comment by AJF-cmd** [comment]
This issue has been resolved in the latest version. Please use the latest release or rc version (https://github.com/vllm-project/vllm-ascend/releases). If the issue persists, feel free to submit a new issue.
