### ISSUE TITLE
[Bug]:cos or sin batchSize must same as x batchSize.

### ISSUE THREAD

**Issue by shaojun0** [vllm-project/vllm-ascend#4769]
### Your current environment

docker image:vllm-ascend:v0.11.0rc0-deepseek-v3.2-exp
npu-version:24.1.0
```yaml
services:
  vllm-ascend-head:
    image: quay.io/ascend/vllm-ascend:v0.11.0rc0-deepseek-v3.2-exp
    container_name: vllm-ascend-head
    network_mode: host
    privileged: true
    ipc: host
    environment:
      - HCCL_IF_IP=10.48.205.242
      - ATB_LLM_HCCL_ENABLE=1
      - GLOO_SOCKET_IFNAME=bond4
      - ATB_LLM_COMM_BACKEND=hccl
      - TP_SOCKET_IFNAME=bond4
      - HCCL_SOCKET_IFNAME=bond4
      - ASCEND_RT_VISIBLE_DEVICES=0,1,2,3,4,5,6,7
      - OMP_PROC_BIND=false
      - OMP_NUM_THREADS=100
      - VLLM_USE_MODELSCOPE=True
      - HCCL_BUFFSIZE=1024
      - HCCL_OP_EXPANSION_MODE=AIV
      - HCCL_CONNECT_TIMEOUT=7200
      - HCCL_EXEC_TIMEOUT=0
      - PYTORCH_NPU_ALLOC_CONF=expandable_segments:True
    devices:
      - /dev/davinci0
      - /dev/davinci1
      - /dev/davinci2
      - /dev/davinci3
      - /dev/davinci4
      - /dev/davinci5
      - /dev/davinci6
      - /dev/davinci7
      - /dev/davinci_manager
      - /dev/devmm_svm
      - /dev/hisi_hdc
    volumes:
      - /usr/local/dcmi:/usr/local/dcmi
      - /usr/local/sbin/npu-smi:/usr/local/sbin/npu-smi
      - /usr/local/Ascend/driver/lib64:/usr/local/Ascend/driver/lib64
      - /usr/local/Ascend/driver/version.info:/usr/local/Ascend/driver/version.info
      - /etc/ascend_install.info:/etc/ascend_install.info
      - /data:/data
    command: >
      vllm serve /data/DeepSeek-V3.2-W8A8
      --host 0.0.0.0
      --port 1025
      --data-parallel-size 2
      --data-parallel-size-local 1
      --data-parallel-address 10.48.205.242
      --data-parallel-rpc-port 13389
      --tensor-parallel-size 8
      --seed 1024
      --served-model-name DeepSeek-r1-32k_token
      --enable-expert-parallel
      --max-num-seqs 16
      --max-model-len 17450
      --quantization ascend
      --max-num-batched-tokens 17450
      --trust-remote-code
      --no-enable-prefix-caching
      --gpu-memory-utilization 0.92
      --additional-config '{"torchair_graph_config":{"enabled":true,"graph_batch_sizes":[16]}}'
```

```yaml
services:
  vllm-ascend-head:
    image: quay.io/ascend/vllm-ascend:v0.11.0rc0-deepseek-v3.2-exp
    container_name: vllm-ascend-head
    network_mode: host
    privileged: true
    ipc: host
    environment:
      - HCCL_IF_IP=10.48.205.243
      - ATB_LLM_HCCL_ENABLE=1
      - ATB_LLM_COMM_BACKEND=hccl
      - GLOO_SOCKET_IFNAME=bond4
      - TP_SOCKET_IFNAME=bond4
      - HCCL_SOCKET_IFNAME=bond4
      - ASCEND_RT_VISIBLE_DEVICES=0,1,2,3,4,5,6,7
      - OMP_PROC_BIND=false
      - OMP_NUM_THREADS=100
      - VLLM_USE_MODELSCOPE=True
      - HCCL_BUFFSIZE=1024
      - HCCL_OP_EXPANSION_MODE=AIV
      - HCCL_CONNECT_TIMEOUT=7200
      - HCCL_EXEC_TIMEOUT=0
      - PYTORCH_NPU_ALLOC_CONF=expandable_segments:True
    devices:
      - /dev/davinci0
      - /dev/davinci1
      - /dev/davinci2
      - /dev/davinci3
      - /dev/davinci4
      - /dev/davinci5
      - /dev/davinci6
      - /dev/davinci7
      - /dev/davinci_manager
      - /dev/devmm_svm
      - /dev/hisi_hdc
    volumes:
      - /usr/local/dcmi:/usr/local/dcmi
      - /usr/local/sbin/npu-smi:/usr/local/sbin/npu-smi
      - /usr/local/Ascend/driver/lib64:/usr/local/Ascend/driver/lib64
      - /usr/local/Ascend/driver/version.info:/usr/local/Ascend/driver/version.info
      - /etc/ascend_install.info:/etc/ascend_install.info
      - /data:/data
    command: >
      vllm serve /data/DeepSeek-V3.2-W8A8
      --host 0.0.0.0
      --port 1025
      --headless
      --data-parallel-size 2
      --data-parallel-size-local 1
      --data-parallel-start-rank 1
      --data-parallel-address 10.48.205.242
      --data-parallel-rpc-port 13389
      --tensor-parallel-size 8
      --seed 1024
      --quantization ascend
      --served-model-name DeepSeek-r1-32k_token
      --enable-expert-parallel
      --max-num-seqs 16
      --max-model-len 17450
      --max-num-batched-tokens 17450
      --trust-remote-code
      --no-enable-prefix-caching
      --gpu-memory-utilization 0.92
      --additional-config '{"torchair_graph_config":{"enabled":true,"graph_batch_sizes":[16]}}'
```
### 🐛 Describe the bug

```shell
(Worker_DP0_TP4_EP4 pid=1698) ERROR 12-08 01:15:45 [multiproc_executor.py:671] WorkerProc hit an exception.
(Worker_DP0_TP4_EP4 pid=1698) ERROR 12-08 01:15:45 [multiproc_executor.py:671] Traceback (most recent call last):
(Worker_DP0_TP4_EP4 pid=1698) ERROR 12-08 01:15:45 [multiproc_executor.py:671]   File "/vllm-workspace/vllm/vllm/v1/executor/multiproc_executor.py", line 666, in worker_busy_loop
(Worker_DP0_TP4_EP4 pid=1698) ERROR 12-08 01:15:45 [multiproc_executor.py:671]     output = func(*args, **kwargs)
(Worker_DP0_TP4_EP4 pid=1698) ERROR 12-08 01:15:45 [multiproc_executor.py:671]              ^^^^^^^^^^^^^^^^^^^^^
(Worker_DP0_TP4_EP4 pid=1698) ERROR 12-08 01:15:45 [multiproc_executor.py:671]   File "/vllm-workspace/vllm-ascend/vllm_ascend/worker/worker_v1.py", line 254, in execute_model
(Worker_DP0_TP4_EP4 pid=1698) ERROR 12-08 01:15:45 [multiproc_executor.py:671]     output = self.model_runner.execute_model(scheduler_output,
(Worker_DP0_TP4_EP4 pid=1698) ERROR 12-08 01:15:45 [multiproc_executor.py:671]              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(Worker_DP0_TP4_EP4 pid=1698) ERROR 12-08 01:15:45 [multiproc_executor.py:671]   File "/usr/local/python3.11.13/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
(Worker_DP0_TP4_EP4 pid=1698) ERROR 12-08 01:15:45 [multiproc_executor.py:671]     return func(*args, **kwargs)
(Worker_DP0_TP4_EP4 pid=1698) ERROR 12-08 01:15:45 [multiproc_executor.py:671]            ^^^^^^^^^^^^^^^^^^^^^
(Worker_DP0_TP4_EP4 pid=1698) ERROR 12-08 01:15:45 [multiproc_executor.py:671]   File "/vllm-workspace/vllm-ascend/vllm_ascend/worker/model_runner_v1.py", line 1967, in execute_model
(Worker_DP0_TP4_EP4 pid=1698) ERROR 12-08 01:15:45 [multiproc_executor.py:671]     hidden_states = self._generate_process_reqs_hidden_states(
(Worker_DP0_TP4_EP4 pid=1698) ERROR 12-08 01:15:45 [multiproc_executor.py:671]                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(Worker_DP0_TP4_EP4 pid=1698) ERROR 12-08 01:15:45 [multiproc_executor.py:671]   File "/vllm-workspace/vllm-ascend/vllm_ascend/torchair/torchair_model_runner.py", line 330, in _generate_process_reqs_hidden_states
(Worker_DP0_TP4_EP4 pid=1698) ERROR 12-08 01:15:45 [multiproc_executor.py:671]     hidden_states = self.model(
(Worker_DP0_TP4_EP4 pid=1698) ERROR 12-08 01:15:45 [multiproc_executor.py:671]                     ^^^^^^^^^^^
(Worker_DP0_TP4_EP4 pid=1698) ERROR 12-08 01:15:45 [multiproc_executor.py:671]   File "/usr/local/python3.11.13/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
(Worker_DP0_TP4_EP4 pid=1698) ERROR 12-08 01:15:45 [multiproc_executor.py:671]     return self._call_impl(*args, **kwargs)
(Worker_DP0_TP4_EP4 pid=1698) ERROR 12-08 01:15:45 [multiproc_executor.py:671]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(Worker_DP0_TP4_EP4 pid=1698) ERROR 12-08 01:15:45 [multiproc_executor.py:671]   File "/usr/local/python3.11.13/lib/ python3.11/site-packages/torch/nn/modules/module.py", line 1762, in _call_impl
(Worker_DP0_TP4_EP4 pid=1698) ERROR 12-08 01:15:45 [multiproc_executor.py:671]     return forward_call(*args, **kwargs)
(Worker_DP0_TP4_EP4 pid=1698) ERROR 12-08 01:15:45 [multiproc_executor.py:671]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(Worker_DP0_TP4_EP4 pid=1698) ERROR 12-08 01:15:45 [multiproc_executor.py:671]   File "/vllm-workspace/vllm-ascend/vllm_ascend/torchair/models/torchair_deepseek_v2.py", line 1287, in forward
(Worker_DP0_TP4_EP4 pid=1698) ERROR 12-08 01:15:45 [multiproc_executor.py:671]     hidden_states = self.model(input_ids, positions, kv_caches,
(Worker_DP0_TP4_EP4 pid=1698) ERROR 12-08 01:15:45 [multiproc_executor.py:671]                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(Worker_DP0_TP4_EP4 pid=1698) ERROR 12-08 01:15:45 [multiproc_executor.py:671]   File "/usr/local/python3.11.13/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
(Worker_DP0_TP4_EP4 pid=1698) ERROR 12-08 01:15:45 [multiproc_executor.py:671]     return self._call_impl(*args, **kwargs)
(Worker_DP0_TP4_EP4 pid=1698) ERROR 12-08 01:15:45 [multiproc_executor.py:671]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(Worker_DP0_TP4_EP4 pid=1698) ERROR 12-08 01:15:45 [multiproc_executor.py:671]   File "/usr/local/python3.11.13/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1762, in _call_impl
(Worker_DP0_TP4_EP4 pid=1698) ERROR 12-08 01:15:45 [multiproc_executor.py:671]     return forward_call(*args, **kwargs)
(Worker_DP0_TP4_EP4 pid=1698) ERROR 12-08 01:15:45 [multiproc_executor.py:671]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(Worker_DP0_TP4_EP4 pid=1698) ERROR 12-08 01:15:45 [multiproc_executor.py:671]   File "/vllm-workspace/vllm-ascend/vllm_ascend/torchair/models/torchair_deepseek_v2.py", line 1132, in forward
(Worker_DP0_TP4_EP4 pid=1698) ERROR 12-08 01:15:45 [multiproc_executor.py:671]     hidden_states, residual = layer(
(Worker_DP0_TP4_EP4 pid=1698) ERROR 12-08 01:15:45 [multiproc_executor.py:671]                               ^^^^^^
(Worker_DP0_TP4_EP4 pid=1698) ERROR 12-08 01:15:45 [multiproc_executor.py:671]   File "/usr/local/python3.11.13/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
(Worker_DP0_TP4_EP4 pid=1698) ERROR 12-08 01:15:45 [multiproc_executor.py:671]     return self._call_impl(*args, **kwargs)
(Worker_DP0_TP4_EP4 pid=1698) ERROR 12-08 01:15:45 [multiproc_executor.py:671]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(Worker_DP0_TP4_EP4 pid=1698) ERROR 12-08 01:15:45 [multiproc_executor.py:671]   File "/usr/local/python3.11.13/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1762, in _call_impl
(Worker_DP0_TP4_EP4 pid=1698) ERROR 12-08 01:15:45 [multiproc_executor.py:671]     return forward_call(*args, **kwargs)
(Worker_DP0_TP4_EP4 pid=1698) ERROR 12-08 01:15:45 [multiproc_executor.py:671]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(Worker_DP0_TP4_EP4 pid=1698) ERROR 12-08 01:15:45 [multiproc_executor.py:671]   File "/vllm-workspace/vllm-ascend/vllm_ascend/torchair/models/torchair_deepseek_v2.py", line 980, in forward
(Worker_DP0_TP4_EP4 pid=1698) ERROR 12-08 01:15:45 [multiproc_executor.py:671]     hidden_states = self.self_attn(
(Worker_DP0_TP4_EP4 pid=1698) ERROR 12-08 01:15:45 [multiproc_executor.py:671]                     ^^^^^^^^^^^^^^^
(Worker_DP0_TP4_EP4 pid=1698) ERROR 12-08 01:15:45 [multiproc_executor.py:671]   File "/usr/local/python3.11.13/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
(Worker_DP0_TP4_EP4 pid=1698) ERROR 12-08 01:15:45 [multiproc_executor.py:671]     return self._call_impl(*args, **kwargs)
(Worker_DP0_TP4_EP4 pid=1698) ERROR 12-08 01:15:45 [multiproc_executor.py:671]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(Worker_DP0_TP4_EP4 pid=1698) ERROR 12-08 01:15:45 [multiproc_executor.py:671]   File "/usr/local/python3.11.13/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1762, in _call_impl
(Worker_DP0_TP4_EP4 pid=1698) ERROR 12-08 01:15:45 [multiproc_executor.py:671]     return forward_call(*args, **kwargs)
(Worker_DP0_TP4_EP4 pid=1698) ERROR 12-08 01:15:45 [multiproc_executor.py:671]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(Worker_DP0_TP4_EP4 pid=1698) ERROR 12-08 01:15:45 [multiproc_executor.py:671]   File "/vllm-workspace/vllm-ascend/vllm_ascend/torchair/models/torchair_deepseek_v2.py", line 849, in forward
(Worker_DP0_TP4_EP4 pid=1698) ERROR 12-08 01:15:45 [multiproc_executor.py:671]     self.sfa_attn.impl.forward(hidden_states, kv_cache, attn_metadata,
(Worker_DP0_TP4_EP4 pid=1698) ERROR 12-08 01:15:45 [multiproc_executor.py:671]   File "/vllm-workspace/vllm-ascend/vllm_ascend/torchair/torchair_sfa.py", line 1039, in forward
(Worker_DP0_TP4_EP4 pid=1698) ERROR 12-08 01:15:45 [multiproc_executor.py:671]     prefill_q_pe = torch_npu.npu_interleave_rope(
(Worker_DP0_TP4_EP4 pid=1698) ERROR 12-08 01:15:45 [multiproc_executor.py:671]                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(Worker_DP0_TP4_EP4 pid=1698) ERROR 12-08 01:15:45 [multiproc_executor.py:671]   File "/usr/local/python3.11.13/lib/python3.11/site-packages/torch/_ops.py", line 1158, in __call__
(Worker_DP0_TP4_EP4 pid=1698) ERROR 12-08 01:15:45 [multiproc_executor.py:671]     return self._op(*args, **(kwargs or {}))
(Worker_DP0_TP4_EP4 pid=1698) ERROR 12-08 01:15:45 [multiproc_executor.py:671]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(Worker_DP0_TP4_EP4 pid=1698) ERROR 12-08 01:15:45 [multiproc_executor.py:671] RuntimeError: call aclnnInterleaveRope failed, detail: EZ9999: Inner Error!
(Worker_DP0_TP4_EP4 pid=1698) ERROR 12-08 01:15:45 [multiproc_executor.py:671] EZ9999: [PID: 1698] 2025-12-08-01:15:45.085.263 cos or sin batchSize must same as x batchSize.[FUNC:GetShapeAttrsInfo][FILE:interleave_rope_tiling.cpp][LINE:124]
(Worker_DP0_TP4_EP4 pid=1698) ERROR 12-08 01:15:45 [multiproc_executor.py:671]         TraceBack (most recent call last):
(Worker_DP0_TP4_EP4 pid=1698) ERROR 12-08 01:15:45 [multiproc_executor.py:671]        InterleaveRope do tiling failed, ret is -1.
(Worker_DP0_TP4_EP4 pid=1698) ERROR 12-08 01:15:45 [multiproc_executor.py:671]        Check NnopbaseExecutorDoTiling(executor) failed
(Worker_DP0_TP4_EP4 pid=1698) ERROR 12-08 01:15:45 [multiproc_executor.py:671]        Check NnopbaseExecutorTilingAndUpdateBinInfo(executor) failed
(Worker_DP0_TP4_EP4 pid=1698) ERROR 12-08 01:15:45 [multiproc_executor.py:671]        Check NnopbaseExecutorMatchCache(executor) failed
(Worker_DP0_TP4_EP4 pid=1698) ERROR 12-08 01:15:45 [multiproc_executor.py:671]        Check NnopbaseRunForWorkspace(*executor, workspaceSize) failed
```

**Comment by shaojun0** [comment]
```python
# https://github.com/vllm-project/vllm-ascend/blob/00ba07102212c7c7a40de427f09848f2e203c498/vllm_ascend/torchair/torchair_sfa.py#L1033-L1040
            nope_cache = kv_cache[0]
            rope_cache = kv_cache[1]
            cos = attn_metadata.prefill.cos
            sin = attn_metadata.prefill.sin
            cos_q, sin_q = cos, sin


            prefill_q_pe = torch_npu.npu_interleave_rope(
                prefill_q_pe, cos_q, sin_q)  # BNSD
```
Based on the error prompt in the file `torchair_sfa.py`, locate the file `model_runner_v1.py`.
```python
# https://github.com/vllm-project/vllm-ascend/blob/00ba07102212c7c7a40de427f09848f2e203c498/vllm_ascend/worker/model_runner_v1.py#L1595-L1619
    def _build_attn_state(self, num_reqs, num_scheduled_tokens,
                          num_valid_tokens):
        ascend_config = get_ascend_config()
        if np.array_equal(self.seq_lens_np[:num_reqs], num_scheduled_tokens):
            attn_state = AscendAttentionState.PrefillNoCache
        # We assume it is the decode stage, where prefill occurs but only one token is not hit in cache.
        elif np.all(num_scheduled_tokens == 1):
            attn_state = AscendAttentionState.DecodeOnly
            if self.speculative_config and self.speculative_config.method == 'deepseek_mtp':
                # SpecDecoding now supports seq_len=1 and seq_len=2
                # In Prefilling Decoding Disaggregation scenario, SpecDecoding need to supports seq_len=1
                attn_state = AscendAttentionState.SpecDecoding
        # Speculative decoding.
        elif np.all(num_valid_tokens == 1):
            if self.drafter and (self.drafter.name == SpecDcodeType.EAGLE
                                 or self.drafter.name == SpecDcodeType.EAGLE3):
                attn_state = AscendAttentionState.ChunkedPrefill
            else:
                attn_state = AscendAttentionState.SpecDecoding
        # splitfuse
        elif not ascend_config.ascend_scheduler_config.enabled or self.chunked_prefill_enabled:
            attn_state = AscendAttentionState.ChunkedPrefill
        else:
            attn_state = AscendAttentionState.PrefillCacheHit
        return attn_state
```
When some requests require computed cos/sin, and others require pre-filled cos/sin, and when these two types of requests occur simultaneously, could this cause issues?
I understand the logic here is that it can either be in prefill mode (no cache), decode-only mode, or prefill mode (with cache). When a request contains both prefill mode and decode-only mode requests, can this function still handle it?
@Yikun Hey dude, Could you possibly help me with this?

**Comment by fangtaosong** [comment]
I also encountered this issue.

**Comment by shaojun0** [comment]
> I also encountered this issue.

I think this is a bug that occurred after adapting to PD separation. I'm not sure if it can be fixed by changing the vllm-ascend version—for example, by switching to version 0.9.1.Unfortunately, due to limited resources, I can only conduct deployment tests on weekends.

**Comment by shaojun0** [comment]
> I also encountered this issue.

Anyway, the problem is clearly concurrency. The regular chat works fine – I tested it myself.

**Comment by LoganJane** [comment]
This issue has been resolved in the latest version. Please use the latest release or rc version (https://github.com/vllm-project/vllm-ascend/releases). If the issue persists, feel free to submit a new issue.
@shaojun0
