### ISSUE TITLE
[Bug]: Qwen2.5-32B-Instruct encountered an exception for the second request using its own trained eagle3 draft model

### ISSUE THREAD

**Issue by haibenben** [vllm-project/vllm-ascend#4771]
### Your current environment

<details>
<summary>The output of `python collect_env.py`</summary>

```text
Collecting environment information...
PyTorch version: 2.7.1+cpu
Is debug build: False

OS: Ubuntu 22.04.5 LTS (x86_64)
GCC version: (Ubuntu 11.4.0-1ubuntu1~22.04.2) 11.4.0
Clang version: Could not collect
CMake version: version 4.2.0
Libc version: glibc-2.35

Python version: 3.11.13 (main, Nov 20 2025, 16:03:05) [GCC 11.4.0] (64-bit runtime)
Python platform: Linux-5.15.0-60-generic-x86_64-with-glibc2.35

CPU:
Architecture:                    x86_64
CPU op-mode(s):                  32-bit, 64-bit
Address sizes:                   46 bits physical, 57 bits virtual
Byte Order:                      Little Endian
CPU(s):                          176
On-line CPU(s) list:             0-175
Vendor ID:                       GenuineIntel
Model name:                      Intel(R) Xeon(R) Platinum 8458P
CPU family:                      6
Model:                           143
Thread(s) per core:              2
Core(s) per socket:              44
Socket(s):                       2
Stepping:                        8
Frequency boost:                 enabled
CPU max MHz:                     2701.0000
CPU min MHz:                     800.0000
BogoMIPS:                        5400.00
Flags:                           fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc art arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf tsc_known_freq pni pclmulqdq dtes64 ds_cpl vmx smx est tm2 ssse3 sdbg fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm 3dnowprefetch cpuid_fault epb cat_l3 cat_l2 cdp_l3 invpcid_single intel_ppin cdp_l2 ssbd mba ibrs ibpb stibp ibrs_enhanced tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid cqm rdt_a avx512f avx512dq rdseed adx smap avx512ifma clflushopt clwb intel_pt avx512cd sha_ni avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local split_lock_detect avx_vnni avx512_bf16 wbnoinvd dtherm ida arat pln pts hwp hwp_act_window hwp_epp hwp_pkg_req avx512vbmi umip pku ospke waitpkg avx512_vbmi2 gfni vaes vpclmulqdq avx512_vnni avx512_bitalg tme avx512_vpopcntdq la57 rdpid bus_lock_detect cldemote movdiri movdir64b enqcmd fsrm md_clear serialize tsxldtrk pconfig arch_lbr amx_bf16 avx512_fp16 amx_tile amx_int8 flush_l1d arch_capabilities
Virtualization:                  VT-x
L1d cache:                       4.1 MiB (88 instances)
L1i cache:                       2.8 MiB (88 instances)
L2 cache:                        176 MiB (88 instances)
L3 cache:                        165 MiB (2 instances)
NUMA node(s):                    2
NUMA node0 CPU(s):               0-43,88-131
NUMA node1 CPU(s):               44-87,132-175
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Mmio stale data:   Not affected
Vulnerability Retbleed:          Not affected
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl and seccomp
Vulnerability Spectre v1:        Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:        Mitigation; Enhanced IBRS, IBPB conditional, RSB filling, PBRSB-eIBRS SW sequence
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected

Versions of relevant libraries:
[pip3] numpy==1.26.4
[pip3] pyzmq==27.1.0
[pip3] torch==2.7.1+cpu
[pip3] torch_npu==2.7.1
[pip3] torchvision==0.22.1+cpu
[pip3] transformers==4.57.1
[conda] Could not collect
vLLM Version: 0.11.0
vLLM Ascend Version: 0.11.0rc2

ENV Variables:
ATB_OPSRUNNER_KERNEL_CACHE_LOCAL_COUNT=1
ATB_STREAM_SYNC_EVERY_RUNNER_ENABLE=0
ATB_OPSRUNNER_SETUP_CACHE_ENABLE=1
ATB_WORKSPACE_MEM_ALLOC_GLOBAL=0
ATB_DEVICE_TILING_BUFFER_BLOCK_NUM=32
ATB_STREAM_SYNC_EVERY_KERNEL_ENABLE=0
ATB_OPSRUNNER_KERNEL_CACHE_GLOABL_COUNT=5
ATB_HOME_PATH=/usr/local/Ascend/nnal/atb/latest/atb/cxx_abi_1
ASCEND_TOOLKIT_HOME=/usr/local/Ascend/ascend-toolkit/latest
ATB_COMPARE_TILING_EVERY_KERNEL=0
ASCEND_OPP_PATH=/usr/local/Ascend/ascend-toolkit/latest/opp
LD_LIBRARY_PATH=/usr/local/Ascend/nnal/atb/latest/atb/cxx_abi_1/lib:/usr/local/Ascend/nnal/atb/latest/atb/cxx_abi_1/examples:/usr/local/Ascend/nnal/atb/latest/atb/cxx_abi_1/tests/atbopstest:/usr/local/Ascend/ascend-toolkit/latest/tools/aml/lib64:/usr/local/Ascend/ascend-toolkit/latest/tools/aml/lib64/plugin:/usr/local/Ascend/ascend-toolkit/latest/lib64:/usr/local/Ascend/ascend-toolkit/latest/lib64/plugin/opskernel:/usr/local/Ascend/ascend-toolkit/latest/lib64/plugin/nnengine:/usr/local/Ascend/ascend-toolkit/latest/opp/built-in/op_impl/ai_core/tbe/op_tiling/lib/linux/x86_64:/usr/local/Ascend/nnal/atb/latest/atb/cxx_abi_0/lib:/usr/local/Ascend/nnal/atb/latest/atb/cxx_abi_0/examples:/usr/local/Ascend/nnal/atb/latest/atb/cxx_abi_0/tests/atbopstest:/usr/local/Ascend/ascend-toolkit/latest/tools/aml/lib64:/usr/local/Ascend/ascend-toolkit/latest/tools/aml/lib64/plugin:/usr/local/Ascend/ascend-toolkit/latest/lib64:/usr/local/Ascend/ascend-toolkit/latest/lib64/plugin/opskernel:/usr/local/Ascend/ascend-toolkit/latest/lib64/plugin/nnengine:/usr/local/Ascend/ascend-toolkit/latest/opp/built-in/op_impl/ai_core/tbe/op_tiling:/usr/local/Ascend/driver/lib64/common/:/usr/local/Ascend/driver/lib64/driver/:
ASCEND_AICPU_PATH=/usr/local/Ascend/ascend-toolkit/latest
ATB_STREAM_SYNC_EVERY_OPERATION_ENABLE=0
ASCEND_HOME_PATH=/usr/local/Ascend/ascend-toolkit/latest
ATB_MATMUL_SHUFFLE_K_ENABLE=1
ATB_WORKSPACE_MEM_ALLOC_ALG_TYPE=1
ATB_HOST_TILING_BUFFER_BLOCK_NUM=128
ATB_SHARE_MEMORY_NAME_SUFFIX=
TORCH_DEVICE_BACKEND_AUTOLOAD=1
PYTORCH_NVML_BASED_CUDA_CHECK=1
TORCHINDUCTOR_COMPILE_THREADS=1


NPU:
+------------------------------------------------------------------------------------------------+
| npu-smi 24.1.0                   Version: 24.1.0                                               |
+---------------------------+---------------+----------------------------------------------------+
| NPU   Name                | Health        | Power(W)    Temp(C)           Hugepages-Usage(page)|
| Chip                      | Bus-Id        | AICore(%)   Memory-Usage(MB)  HBM-Usage(MB)        |
+===========================+===============+====================================================+
| 0     910B2C              | OK            | 93.0        48                0    / 0             |
| 0                         | 0000:5A:00.0  | 0           0    / 0          3425 / 65536         |
+===========================+===============+====================================================+
| 1     910B2C              | OK            | 94.8        51                0    / 0             |
| 0                         | 0000:19:00.0  | 0           0    / 0          3417 / 65536         |
+===========================+===============+====================================================+
| 2     910B2C              | OK            | 93.5        49                0    / 0             |
| 0                         | 0000:49:00.0  | 0           0    / 0          34130/ 65536         |
+===========================+===============+====================================================+
| 3     910B2C              | OK            | 98.2        51                0    / 0             |
| 0                         | 0000:39:00.0  | 0           0    / 0          60364/ 65536         |
+===========================+===============+====================================================+
| 4     910B2C              | OK            | 96.0        49                0    / 0             |
| 0                         | 0000:DA:00.0  | 0           0    / 0          3419 / 65536         |
+===========================+===============+====================================================+
| 5     910B2C              | OK            | 97.5        50                0    / 0             |
| 0                         | 0000:99:00.0  | 0           0    / 0          3418 / 65536         |
+===========================+===============+====================================================+
| 6     910B2C              | OK            | 92.7        50                0    / 0             |
| 0                         | 0000:B8:00.0  | 0           0    / 0          3417 / 65536         |
+===========================+===============+====================================================+
| 7     910B2C              | OK            | 100.8       51                0    / 0             |
| 0                         | 0000:C8:00.0  | 0           0    / 0          3411 / 65536         |
+===========================+===============+====================================================+
| 8     910B2C              | OK            | 99.3        49                0    / 0             |
| 0                         | 0000:59:00.0  | 0           0    / 0          3400 / 65536         |
+===========================+===============+====================================================+
| 9     910B2C              | OK            | 99.1        50                0    / 0             |
| 0                         | 0000:18:00.0  | 0           0    / 0          59539/ 65536         |
+===========================+===============+====================================================+
| 10    910B2C              | OK            | 100.6       49                0    / 0             |
| 0                         | 0000:48:00.0  | 0           0    / 0          60365/ 65536         |
+===========================+===============+====================================================+
| 11    910B2C              | OK            | 92.7        51                0    / 0             |
| 0                         | 0000:38:00.0  | 0           0    / 0          3412 / 65536         |
+===========================+===============+====================================================+
| 12    910B2C              | OK            | 93.6        49                0    / 0             |
| 0                         | 0000:D9:00.0  | 0           0    / 0          3404 / 65536         |
+===========================+===============+====================================================+
| 13    910B2C              | OK            | 99.0        49                0    / 0             |
| 0                         | 0000:98:00.0  | 0           0    / 0          3402 / 65536         |
+===========================+===============+====================================================+
| 14    910B2C              | OK            | 93.6        49                0    / 0             |
| 0                         | 0000:B9:00.0  | 0           0    / 0          59530/ 65536         |
+===========================+===============+====================================================+
| 15    910B2C              | OK            | 99.4        51                0    / 0             |
| 0                         | 0000:C9:00.0  | 0           0    / 0          3406 / 65536         |
+===========================+===============+====================================================+
+---------------------------+---------------+----------------------------------------------------+
| NPU     Chip              | Process id    | Process name             | Process memory(MB)      |
+===========================+===============+====================================================+
| No running processes found in NPU 0                                                            |
+===========================+===============+====================================================+
| No running processes found in NPU 1                                                            |
+===========================+===============+====================================================+
| 2       0                 | 1079968       |                          | 30781                   |
+===========================+===============+====================================================+
| 3       0                 | 959041        |                          | 56627                   |
+===========================+===============+====================================================+
| No running processes found in NPU 4                                                            |
+===========================+===============+====================================================+
| No running processes found in NPU 5                                                            |
+===========================+===============+====================================================+
| No running processes found in NPU 6                                                            |
+===========================+===============+====================================================+
| No running processes found in NPU 7                                                            |
+===========================+===============+====================================================+
| No running processes found in NPU 8                                                            |
+===========================+===============+====================================================+
| 9       0                 | 3042741       |                          | 56171                   |
+===========================+===============+====================================================+
| 10      0                 | 961790        |                          | 56627                   |
+===========================+===============+====================================================+
| No running processes found in NPU 11                                                           |
+===========================+===============+====================================================+
| No running processes found in NPU 12                                                           |
+===========================+===============+====================================================+
| No running processes found in NPU 13                                                           |
+===========================+===============+====================================================+
| 14      0                 | 3045955       |                          | 56171                   |
+===========================+===============+====================================================+
| No running processes found in NPU 15                                                           |
+===========================+===============+====================================================+

CANN:
package_name=Ascend-cann-toolkit
version=8.3.RC2
innerversion=V100R001C23SPC002B210
compatible_version=[V100R001C15],[V100R001C18],[V100R001C19],[V100R001C20],[V100R001C21],[V100R001C23]
arch=x86_64
os=linux
path=/usr/local/Ascend/ascend-toolkit/8.3.RC2/x86_64-linux

```

</details>

### 🐛 Describe the bug

Qwen2.5-32B-Instruct uses its own trained eagle3 draft model. The first request was normal, but the second request was abnormal.

vLLM Version: 0.11.0
vLLM Ascend Version: 0.11.0rc2

Use this Fixes https://github.com/vllm-project/vllm-ascend/issues/4323

start command: 
```python3 -m vllm.entrypoints.openai.api_server --served-model-name qwen2.5_32b --host 0.0.0.0 --port 8080 --trust-remote-code --model /data/model/Qwen2.5-32B-Instruct --tensor-parallel-size 2 --speculative-config '{"model":"benben888/Qwen2.5-32B-Instruct-Eagle3","draft_tensor_parallel_size":1,"num_speculative_tokens":5,"method":"eagle3"}' --max-num-batched-tokens 4096```

test request：
``` 
curl -s http://0.0.0.0:8080/v1/chat/completions \
  -H "Content-Type: application/json" \
  -d '{
    "model": "qwen2.5_32b",
    "messages": [
      {"role":"user","content":"1+1=?"}
    ],
    "max_tokens": 512,
    "temperature": 0.7
  }' 
```

error log:
```
(APIServer pid=39563) INFO:     Started server process [39563]
(APIServer pid=39563) INFO:     Waiting for application startup.
(APIServer pid=39563) INFO:     Application startup complete.
(APIServer pid=39563) INFO 12-08 03:17:23 [chat_utils.py:560] Detected the chat template content format to be 'string'. You can set `--chat-template-content-format` to override this.
[rank1]:[W1208 03:17:23.669980051 GetCANNInfo.cpp:117] Warning: Driver Version:  is invalid or not supported yet. (function operator())
[rank0]:[W1208 03:17:23.669990938 GetCANNInfo.cpp:117] Warning: Driver Version:  is invalid or not supported yet. (function operator())
(Worker_TP1 pid=39839) INFO 12-08 03:17:23 [acl_graph.py:187] Replaying aclgraph
(Worker_TP0 pid=39838) INFO 12-08 03:17:23 [acl_graph.py:187] Replaying aclgraph
(APIServer pid=39563) INFO:     127.0.0.1:45718 - "POST /v1/chat/completions HTTP/1.1" 200 OK
(APIServer pid=39563) INFO 12-08 03:17:28 [loggers.py:127] Engine 000: Avg prompt throughput: 3.3 tokens/s, Avg generation throughput: 0.6 tokens/s, Running: 0 reqs, Waiting: 0 reqs, GPU KV cache usage: 0.0%, Prefix cache hit rate: 0.0%
(APIServer pid=39563) INFO 12-08 03:17:28 [metrics.py:96] SpecDecoding metrics: Mean acceptance length: 1.67, Accepted throughput: 0.02 tokens/s, Drafted throughput: 0.12 tokens/s, Accepted: 2 tokens, Drafted: 15 tokens, Per-position acceptance rate: 0.667, 0.000, 0.000, 0.000, 0.000, Avg Draft acceptance rate: 13.3%
(Worker_TP1 pid=39839) ERROR 12-08 03:17:31 [multiproc_executor.py:671] WorkerProc hit an exception.
(Worker_TP1 pid=39839) ERROR 12-08 03:17:31 [multiproc_executor.py:671] Traceback (most recent call last):
(Worker_TP1 pid=39839) ERROR 12-08 03:17:31 [multiproc_executor.py:671]   File "/vllm-workspace/vllm/vllm/v1/executor/multiproc_executor.py", line 666, in worker_busy_loop
(Worker_TP1 pid=39839) ERROR 12-08 03:17:31 [multiproc_executor.py:671]     output = func(*args, **kwargs)
(Worker_TP1 pid=39839) ERROR 12-08 03:17:31 [multiproc_executor.py:671]              ^^^^^^^^^^^^^^^^^^^^^
(Worker_TP1 pid=39839) ERROR 12-08 03:17:31 [multiproc_executor.py:671]   File "/vllm-workspace/vllm-ascend/vllm_ascend/worker/worker_v1.py", line 276, in execute_model
(Worker_TP1 pid=39839) ERROR 12-08 03:17:31 [multiproc_executor.py:671]     output = self.model_runner.execute_model(scheduler_output,
(Worker_TP1 pid=39839) ERROR 12-08 03:17:31 [multiproc_executor.py:671]              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(Worker_TP1 pid=39839) ERROR 12-08 03:17:31 [multiproc_executor.py:671]   File "/usr/local/python3.11.13/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
(Worker_TP1 pid=39839) ERROR 12-08 03:17:31 [multiproc_executor.py:671]     return func(*args, **kwargs)
(Worker_TP1 pid=39839) ERROR 12-08 03:17:31 [multiproc_executor.py:671]            ^^^^^^^^^^^^^^^^^^^^^
(Worker_TP1 pid=39839) ERROR 12-08 03:17:31 [multiproc_executor.py:671]   File "/vllm-workspace/vllm-ascend/vllm_ascend/worker/model_runner_v1.py", line 2021, in execute_model
(Worker_TP1 pid=39839) ERROR 12-08 03:17:31 [multiproc_executor.py:671]     sampler_output = self.sampler(
(Worker_TP1 pid=39839) ERROR 12-08 03:17:31 [multiproc_executor.py:671]                      ^^^^^^^^^^^^^
(Worker_TP1 pid=39839) ERROR 12-08 03:17:31 [multiproc_executor.py:671]   File "/usr/local/python3.11.13/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
(Worker_TP1 pid=39839) ERROR 12-08 03:17:31 [multiproc_executor.py:671]     return self._call_impl(*args, **kwargs)
(Worker_TP1 pid=39839) ERROR 12-08 03:17:31 [multiproc_executor.py:671]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(Worker_TP1 pid=39839) ERROR 12-08 03:17:31 [multiproc_executor.py:671]   File "/usr/local/python3.11.13/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1762, in _call_impl
(Worker_TP1 pid=39839) ERROR 12-08 03:17:31 [multiproc_executor.py:671]     return forward_call(*args, **kwargs)
(Worker_TP1 pid=39839) ERROR 12-08 03:17:31 [multiproc_executor.py:671]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(Worker_TP1 pid=39839) ERROR 12-08 03:17:31 [multiproc_executor.py:671]   File "/vllm-workspace/vllm/vllm/v1/sample/sampler.py", line 100, in forward
(Worker_TP1 pid=39839) ERROR 12-08 03:17:31 [multiproc_executor.py:671]     sampled, processed_logprobs = self.sample(logits, sampling_metadata)
(Worker_TP1 pid=39839) ERROR 12-08 03:17:31 [multiproc_executor.py:671]                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(Worker_TP1 pid=39839) ERROR 12-08 03:17:31 [multiproc_executor.py:671]   File "/vllm-workspace/vllm/vllm/v1/sample/sampler.py", line 180, in sample
(Worker_TP1 pid=39839) ERROR 12-08 03:17:31 [multiproc_executor.py:671]     random_sampled, processed_logprobs = self.topk_topp_sampler(
(Worker_TP1 pid=39839) ERROR 12-08 03:17:31 [multiproc_executor.py:671]                                          ^^^^^^^^^^^^^^^^^^^^^^^
(Worker_TP1 pid=39839) ERROR 12-08 03:17:31 [multiproc_executor.py:671]   File "/usr/local/python3.11.13/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
(Worker_TP1 pid=39839) ERROR 12-08 03:17:31 [multiproc_executor.py:671]     return self._call_impl(*args, **kwargs)
(Worker_TP1 pid=39839) ERROR 12-08 03:17:31 [multiproc_executor.py:671]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(Worker_TP1 pid=39839) ERROR 12-08 03:17:31 [multiproc_executor.py:671]   File "/usr/local/python3.11.13/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1762, in _call_impl
(Worker_TP1 pid=39839) ERROR 12-08 03:17:31 [multiproc_executor.py:671]     return forward_call(*args, **kwargs)
(Worker_TP1 pid=39839) ERROR 12-08 03:17:31 [multiproc_executor.py:671]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(Worker_TP1 pid=39839) ERROR 12-08 03:17:31 [multiproc_executor.py:671]   File "/vllm-workspace/vllm-ascend/vllm_ascend/sample/sampler.py", line 66, in forward_native
(Worker_TP1 pid=39839) ERROR 12-08 03:17:31 [multiproc_executor.py:671]     logits = self._apply_top_k_top_p(logits, k, p)
(Worker_TP1 pid=39839) ERROR 12-08 03:17:31 [multiproc_executor.py:671]              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(Worker_TP1 pid=39839) ERROR 12-08 03:17:31 [multiproc_executor.py:671]   File "/vllm-workspace/vllm-ascend/vllm_ascend/sample/sampler.py", line 28, in _apply_top_k_top_p
(Worker_TP1 pid=39839) ERROR 12-08 03:17:31 [multiproc_executor.py:671]     if not is_310p() and p is not None and k is not None and 1 <= int(
(Worker_TP1 pid=39839) ERROR 12-08 03:17:31 [multiproc_executor.py:671]                                                                   ^^^^
(Worker_TP1 pid=39839) ERROR 12-08 03:17:31 [multiproc_executor.py:671] RuntimeError: operator():torch_npu/csrc/aten/common/LocalScalarDenseNpu.cpp:47 NPU function error: c10_npu::acl::AclrtSynchronizeStreamWithTimeout(copy_stream), error code is 507018
(Worker_TP1 pid=39839) ERROR 12-08 03:17:31 [multiproc_executor.py:671] [ERROR] 2025-12-08-03:17:31 (PID:39839, Device:1, RankID:-1) ERR00100 PTA call acl api failed
(Worker_TP1 pid=39839) ERROR 12-08 03:17:31 [multiproc_executor.py:671] [Error]: The aicpu execution is abnormal.
(Worker_TP1 pid=39839) ERROR 12-08 03:17:31 [multiproc_executor.py:671]         Rectify the fault based on the error information in the ascend log.
(Worker_TP1 pid=39839) ERROR 12-08 03:17:31 [multiproc_executor.py:671] E89999: Inner Error!
(Worker_TP1 pid=39839) ERROR 12-08 03:17:31 [multiproc_executor.py:671] E89999[PID: 39839] 2025-12-08-03:17:23.250.718 (E89999):  When layout is TND, queryT(1) must be equal to the last element of actualSequenceLengthQ(33)[FUNC:CheckFAISeqlenDataInTND][FILE:fused_infer_attention_score_tiling.cpp][LINE:880]
(Worker_TP1 pid=39839) ERROR 12-08 03:17:31 [multiproc_executor.py:671]         TraceBack (most recent call last):
(Worker_TP1 pid=39839) ERROR 12-08 03:17:31 [multiproc_executor.py:671]        When layout is TND, queryT(1) must be equal to the last element of actualSequenceLengthQ(2)[FUNC:CheckFAISeqlenDataInTND][FILE:fused_infer_attention_score_tiling.cpp][LINE:880]
(Worker_TP1 pid=39839) ERROR 12-08 03:17:31 [multiproc_executor.py:671]        The error from device(chipId:1, dieId:0), serial number is 9, an exception occurred during AICPU execution, stream_id:2, task_id:7315, errcode:21008, msg:inner error.[FUNC:ProcessStarsAicpuErrorInfo][FILE:device_error_proc.cc][LINE:1483]
(Worker_TP1 pid=39839) ERROR 12-08 03:17:31 [multiproc_executor.py:671]        Kernel task happen error, retCode=0x2a, [aicpu exception].[FUNC:PreCheckTaskErr][FILE:davinci_kernel_task.cc][LINE:1555]
(Worker_TP1 pid=39839) ERROR 12-08 03:17:31 [multiproc_executor.py:671]        AICPU Kernel task happen error, retCode=0x2a.[FUNC:GetError][FILE:stream.cc][LINE:1191]
(Worker_TP1 pid=39839) ERROR 12-08 03:17:31 [multiproc_executor.py:671]        Aicpu kernel execute failed, device_id=1, stream_id=2, task_id=7315, soName=libcpu_kernels.so, funcName=RunCpuKernel, kernelName=ScatterElements, errorCode=0x2a.[FUNC:PrintAicpuErrorInfo][FILE:davinci_kernel_task.cc][LINE:1308]
(Worker_TP1 pid=39839) ERROR 12-08 03:17:31 [multiproc_executor.py:671]        rtStreamSynchronizeWithTimeout execute failed, reason=[aicpu exception][FUNC:FuncErrorReason][FILE:error_message_manage.cc][LINE:53]
(Worker_TP1 pid=39839) ERROR 12-08 03:17:31 [multiproc_executor.py:671]        synchronize stream with timeout failed, runtime result = 507018[FUNC:ReportCallError][FILE:log_inner.cpp][LINE:162]
(Worker_TP1 pid=39839) ERROR 12-08 03:17:31 [multiproc_executor.py:671]
```

**Comment by LoganJane** [comment]
This issue has been resolved in the latest version. Please use the latest release or rc version (https://github.com/vllm-project/vllm-ascend/releases). If the issue persists, feel free to submit a new issue.
@haibenben
