### ISSUE TITLE
[Bug]: Encountered "call aclnnInplaceZero failed, error code is 561103" when running example inference test

### ISSUE THREAD

**Issue by CharlieVinnie** [vllm-project/vllm-ascend#4859]
### Your current environment

<details>
<summary>The output of `python collect_env.py`</summary>

```text
Collecting environment information...
PyTorch version: 2.7.1+cpu
Is debug build: False

OS: Ubuntu 22.04.5 LTS (aarch64)
GCC version: (Ubuntu 11.4.0-1ubuntu1~22.04.2) 11.4.0
Clang version: Could not collect
CMake version: version 4.2.0
Libc version: glibc-2.35

Python version: 3.10.12 (main, Nov  4 2025, 08:48:33) [GCC 11.4.0] (64-bit runtime)
Python platform: Linux-5.15.0-91-generic-aarch64-with-glibc2.35

CPU:
Architecture:                       aarch64
CPU op-mode(s):                     64-bit
Byte Order:                         Little Endian
CPU(s):                             192
On-line CPU(s) list:                0-191
Vendor ID:                          HiSilicon
Model name:                         Kunpeng-920
Model:                              0
Thread(s) per core:                 1
Core(s) per socket:                 48
Socket(s):                          4
Stepping:                           0x1
BogoMIPS:                           200.00
Flags:                              fp asimd evtstrm aes pmull sha1 sha2 crc32 atomics fphp asimdhp cpuid asimdrdm jscvt fcma dcpop asimddp asimdfhm ssbs
L1d cache:                          12 MiB (192 instances)
L1i cache:                          12 MiB (192 instances)
L2 cache:                           96 MiB (192 instances)
L3 cache:                           192 MiB (8 instances)
NUMA node(s):                       8
NUMA node0 CPU(s):                  0-23
NUMA node1 CPU(s):                  24-47
NUMA node2 CPU(s):                  48-71
NUMA node3 CPU(s):                  72-95
NUMA node4 CPU(s):                  96-119
NUMA node5 CPU(s):                  120-143
NUMA node6 CPU(s):                  144-167
NUMA node7 CPU(s):                  168-191
Vulnerability Gather data sampling: Not affected
Vulnerability Itlb multihit:        Not affected
Vulnerability L1tf:                 Not affected
Vulnerability Mds:                  Not affected
Vulnerability Meltdown:             Not affected
Vulnerability Mmio stale data:      Not affected
Vulnerability Retbleed:             Not affected
Vulnerability Spec rstack overflow: Not affected
Vulnerability Spec store bypass:    Mitigation; Speculative Store Bypass disabled via prctl
Vulnerability Spectre v1:           Mitigation; __user pointer sanitization
Vulnerability Spectre v2:           Not affected
Vulnerability Srbds:                Not affected
Vulnerability Tsx async abort:      Not affected

Versions of relevant libraries:
[pip3] numpy==1.26.4
[pip3] pyzmq==27.1.0
[pip3] torch==2.7.1+cpu
[pip3] torch_npu==2.7.1
[pip3] torchvision==0.22.1
[pip3] transformers==4.57.3
[conda] Could not collect
vLLM Version: 0.11.0
vLLM Ascend Version: 0.11.0rc4.dev0+gb6d63bbd5.d20251210 (git sha: b6d63bbd5, date: 20251210)

ENV Variables:
ATB_OPSRUNNER_KERNEL_CACHE_LOCAL_COUNT=1
ATB_STREAM_SYNC_EVERY_RUNNER_ENABLE=0
ATB_OPSRUNNER_SETUP_CACHE_ENABLE=1
ATB_WORKSPACE_MEM_ALLOC_GLOBAL=1
ATB_DEVICE_TILING_BUFFER_BLOCK_NUM=32
ATB_STREAM_SYNC_EVERY_KERNEL_ENABLE=0
ATB_OPSRUNNER_KERNEL_CACHE_GLOABL_COUNT=5
VLLM_USE_MODELSCOPE=true
ATB_HOME_PATH=/usr/local/Ascend/nnal/atb/latest/atb/cxx_abi_1
ASCEND_TOOLKIT_HOME=/usr/local/Ascend/ascend-toolkit/latest
ATB_COMPARE_TILING_EVERY_KERNEL=0
ASCEND_OPP_PATH=/usr/local/Ascend/ascend-toolkit/latest/opp
LD_LIBRARY_PATH=/usr/local/Ascend/ascend-toolkit/latest/acllib/lib64:/usr/local/Ascend/ascend-toolkit/latest/acllib/lib64:/usr/local/Ascend/nnal/atb/latest/atb/cxx_abi_1/lib:/usr/local/Ascend/nnal/atb/latest/atb/cxx_abi_1/examples:/usr/local/Ascend/nnal/atb/latest/atb/cxx_abi_1/tests/atbopstest:/usr/local/Ascend/ascend-toolkit/latest/tools/aml/lib64:/usr/local/Ascend/ascend-toolkit/latest/tools/aml/lib64/plugin:/usr/local/Ascend/ascend-toolkit/latest/lib64:/usr/local/Ascend/ascend-toolkit/latest/lib64/plugin/opskernel:/usr/local/Ascend/ascend-toolkit/latest/lib64/plugin/nnengine:/usr/local/Ascend/ascend-toolkit/latest/opp/built-in/op_impl/ai_core/tbe/op_tiling/lib/linux/aarch64:/usr/local/Ascend/driver/lib64:/usr/local/Ascend/driver/lib64/common:/usr/local/Ascend/driver/lib64/driver:/home/mpich/lib/:/usr/local/Ascend/ascend-toolkit/latest/tools/aml/lib64:/usr/local/Ascend/ascend-toolkit/latest/tools/aml/lib64/plugin:/usr/local/Ascend/ascend-toolkit/latest/lib64:/usr/local/Ascend/ascend-toolkit/latest/lib64/plugin/opskernel:/usr/local/Ascend/ascend-toolkit/latest/lib64/plugin/nnengine:/usr/local/Ascend/ascend-toolkit/latest/opp/built-in/op_impl/ai_core/tbe/op_tiling/lib/linux/aarch64:/usr/local/Ascend/driver/lib64:/usr/local/Ascend/driver/lib64/common:/usr/local/Ascend/driver/lib64/driver:/usr/local/Ascend/ascend-toolkit/latest/tools/aml/lib64:/usr/local/Ascend/ascend-toolkit/latest/tools/aml/lib64/plugin:/usr/local/Ascend/ascend-toolkit/latest/lib64:/usr/local/Ascend/ascend-toolkit/latest/lib64/plugin/opskernel:/usr/local/Ascend/ascend-toolkit/latest/lib64/plugin/nnengine:/usr/local/Ascend/ascend-toolkit/latest/opp/built-in/op_impl/ai_core/tbe/op_tiling/lib/linux/aarch64:/usr/local/Ascend/driver/lib64:/usr/local/Ascend/driver/lib64/common:/usr/local/Ascend/driver/lib64/driver::/usr/local/dcmi:/usr/local/Ascend/driver/lib64:/usr/local/Ascend/driver/lib64/driver
ASCEND_AICPU_PATH=/usr/local/Ascend/ascend-toolkit/latest
ATB_STREAM_SYNC_EVERY_OPERATION_ENABLE=0
ASCEND_HOME_PATH=/usr/local/Ascend/ascend-toolkit/latest
ATB_MATMUL_SHUFFLE_K_ENABLE=1
ATB_WORKSPACE_MEM_ALLOC_ALG_TYPE=1
ATB_HOST_TILING_BUFFER_BLOCK_NUM=128
ATB_SHARE_MEMORY_NAME_SUFFIX=
TORCH_DEVICE_BACKEND_AUTOLOAD=1
PYTORCH_NVML_BASED_CUDA_CHECK=1
TORCHINDUCTOR_COMPILE_THREADS=1


NPU:
+------------------------------------------------------------------------------------------------+
| npu-smi 25.3.rc1                 Version: 25.3.rc1                                             |
+---------------------------+---------------+----------------------------------------------------+
| NPU   Name                | Health        | Power(W)    Temp(C)           Hugepages-Usage(page)|
| Chip                      | Bus-Id        | AICore(%)   Memory-Usage(MB)  HBM-Usage(MB)        |
+===========================+===============+====================================================+
| 0     910B4               | OK            | 92.1        43                0    / 0             |
| 0                         | 0000:C1:00.0  | 0           0    / 0          2897 / 32768         |
+===========================+===============+====================================================+
| 1     910B4               | OK            | 87.3        42                0    / 0             |
| 0                         | 0000:01:00.0  | 0           0    / 0          2659 / 32768         |
+===========================+===============+====================================================+
| 2     910B4               | OK            | 85.9        43                0    / 0             |
| 0                         | 0000:C2:00.0  | 0           0    / 0          2659 / 32768         |
+===========================+===============+====================================================+
| 3     910B4               | OK            | 92.7        44                0    / 0             |
| 0                         | 0000:02:00.0  | 0           0    / 0          2659 / 32768         |
+===========================+===============+====================================================+
| 4     910B4               | OK            | 92.6        42                0    / 0             |
| 0                         | 0000:81:00.0  | 0           0    / 0          2658 / 32768         |
+===========================+===============+====================================================+
| 5     910B4               | OK            | 91.1        43                0    / 0             |
| 0                         | 0000:41:00.0  | 0           0    / 0          2658 / 32768         |
+===========================+===============+====================================================+
| 6     910B4               | OK            | 83.7        41                0    / 0             |
| 0                         | 0000:82:00.0  | 0           0    / 0          2658 / 32768         |
+===========================+===============+====================================================+
| 7     910B4               | OK            | 87.1        43                0    / 0             |
| 0                         | 0000:42:00.0  | 0           0    / 0          2658 / 32768         |
+===========================+===============+====================================================+
+---------------------------+---------------+----------------------------------------------------+
| NPU     Chip              | Process id    | Process name             | Process memory(MB)      |
+===========================+===============+====================================================+
| No running processes found in NPU 0                                                            |
+===========================+===============+====================================================+
| No running processes found in NPU 1                                                            |
+===========================+===============+====================================================+
| No running processes found in NPU 2                                                            |
+===========================+===============+====================================================+
| No running processes found in NPU 3                                                            |
+===========================+===============+====================================================+
| No running processes found in NPU 4                                                            |
+===========================+===============+====================================================+
| No running processes found in NPU 5                                                            |
+===========================+===============+====================================================+
| No running processes found in NPU 6                                                            |
+===========================+===============+====================================================+
| No running processes found in NPU 7                                                            |
+===========================+===============+====================================================+

CANN:
package_name=Ascend-cann-toolkit
version=8.3.RC2
innerversion=V100R001C23SPC002B210
compatible_version=[V100R001C15],[V100R001C18],[V100R001C19],[V100R001C20],[V100R001C21],[V100R001C23]
arch=aarch64
os=linux
path=/usr/local/Ascend/ascend-toolkit/8.3.RC2/aarch64-linux
```

</details>

### 🐛 Describe the bug

Hi, I followed the installation steps in [https://docs.vllm.ai/projects/ascend/en/latest/installation.html](https://docs.vllm.ai/projects/ascend/en/latest/installation.html). I set up the environment manually instead of with an image because I need to make changes to the vllm-ascend code later. However, after installation succeeded, I encountered this error when running the `example.py` given in "Verify Installation":

```python
from vllm import LLM, SamplingParams

prompts = [
    "Hello, my name is",
    "The president of the United States is",
    "The capital of France is",
    "The future of AI is",
]

# Create a sampling params object.
sampling_params = SamplingParams(temperature=0.8, top_p=0.95)
# Create an LLM.
llm = LLM(model="Qwen/Qwen2.5-0.5B-Instruct")

# Generate texts from the prompts.
outputs = llm.generate(prompts, sampling_params)
for output in outputs:
    prompt = output.prompt
    generated_text = output.outputs[0].text
    print(f"Prompt: {prompt!r}, Generated text: {generated_text!r}")
```

<details>
<summary>Error log</summary>
(EngineCore_DP0 pid=3473945) INFO 12-10 10:52:07 [core.py:644] Waiting for init message from front-end.
(EngineCore_DP0 pid=3473945) INFO 12-10 10:52:07 [core.py:77] Initializing a V1 LLM engine (v0.11.0) with config: model='Qwen/Qwen2.5-0.5B-Instruct', speculative_config=None, tokenizer='Qwen/Qwen2.5-0.5B-Instruct', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, tokenizer_revision=None, trust_remote_code=False, dtype=torch.bfloat16, max_seq_len=32768, download_dir=None, load_format=auto, tensor_parallel_size=1, pipeline_parallel_size=1, data_parallel_size=1, disable_custom_all_reduce=True, quantization=None, enforce_eager=False, kv_cache_dtype=auto, device_config=npu, structured_outputs_config=StructuredOutputsConfig(backend='auto', disable_fallback=False, disable_any_whitespace=False, disable_additional_properties=False, reasoning_parser=''), observability_config=ObservabilityConfig(show_hidden_metrics_for_version=None, otlp_traces_endpoint=None, collect_detailed_traces=None), seed=0, served_model_name=Qwen/Qwen2.5-0.5B-Instruct, enable_prefix_caching=True, chunked_prefill_enabled=True, pooler_config=None, compilation_config={"level":3,"debug_dump_path":"","cache_dir":"","backend":"","custom_ops":["all"],"splitting_ops":["vllm.unified_attention","vllm.unified_attention_with_output","vllm.mamba_mixer2","vllm.mamba_mixer","vllm.short_conv","vllm.linear_attention","vllm.plamo2_mamba_mixer","vllm.gdn_attention","vllm.sparse_attn_indexer","vllm.unified_ascend_attention_with_output","vllm.mla_forward"],"use_inductor":false,"compile_sizes":[],"inductor_compile_config":{"enable_auto_functionalized_v2":false},"inductor_passes":{},"cudagraph_mode":1,"use_cudagraph":true,"cudagraph_num_of_warmups":1,"cudagraph_capture_sizes":[512,504,496,488,480,472,464,456,448,440,432,424,416,408,400,392,384,376,368,360,352,344,336,328,320,312,304,296,288,280,272,264,256,248,240,232,224,216,208,200,192,184,176,168,160,152,144,136,128,120,112,104,96,88,80,72,64,56,48,40,32,24,16,8,4,2,1],"cudagraph_copy_inputs":false,"full_cuda_graph":false,"use_inductor_graph_partition":false,"pass_config":{},"max_capture_size":512,"local_cache_dir":null}
(EngineCore_DP0 pid=3473945) INFO 12-10 10:52:09 [parallel_state.py:1208] rank 0 in world size 1 is assigned as DP rank 0, PP rank 0, TP rank 0, EP rank 0
(EngineCore_DP0 pid=3473945) ERROR 12-10 10:52:09 [patch_core.py:58] EngineCore failed to start.
(EngineCore_DP0 pid=3473945) ERROR 12-10 10:52:09 [patch_core.py:58] Traceback (most recent call last):
(EngineCore_DP0 pid=3473945) ERROR 12-10 10:52:09 [patch_core.py:58]   File "/root/Charlie/vllm-ascend/vllm_ascend/patch/platform/patch_core.py", line 49, in run_engine_core
(EngineCore_DP0 pid=3473945) ERROR 12-10 10:52:09 [patch_core.py:58]     engine_core = EngineCoreProc(*args, **kwargs)
(EngineCore_DP0 pid=3473945) ERROR 12-10 10:52:09 [patch_core.py:58]   File "/root/Charlie/vllm/vllm/v1/engine/core.py", line 498, in __init__
(EngineCore_DP0 pid=3473945) ERROR 12-10 10:52:09 [patch_core.py:58]     super().__init__(vllm_config, executor_class, log_stats,
(EngineCore_DP0 pid=3473945) ERROR 12-10 10:52:09 [patch_core.py:58]   File "/root/Charlie/vllm/vllm/v1/engine/core.py", line 83, in __init__
(EngineCore_DP0 pid=3473945) ERROR 12-10 10:52:09 [patch_core.py:58]     self.model_executor = executor_class(vllm_config)
(EngineCore_DP0 pid=3473945) ERROR 12-10 10:52:09 [patch_core.py:58]   File "/root/Charlie/vllm/vllm/executor/executor_base.py", line 54, in __init__
(EngineCore_DP0 pid=3473945) ERROR 12-10 10:52:09 [patch_core.py:58]     self._init_executor()
(EngineCore_DP0 pid=3473945) ERROR 12-10 10:52:09 [patch_core.py:58]   File "/root/Charlie/vllm/vllm/executor/uniproc_executor.py", line 54, in _init_executor
(EngineCore_DP0 pid=3473945) ERROR 12-10 10:52:09 [patch_core.py:58]     self.collective_rpc("init_device")
(EngineCore_DP0 pid=3473945) ERROR 12-10 10:52:09 [patch_core.py:58]   File "/root/Charlie/vllm/vllm/executor/uniproc_executor.py", line 83, in collective_rpc
(EngineCore_DP0 pid=3473945) ERROR 12-10 10:52:09 [patch_core.py:58]     return [run_method(self.driver_worker, method, args, kwargs)]
(EngineCore_DP0 pid=3473945) ERROR 12-10 10:52:09 [patch_core.py:58]   File "/root/Charlie/vllm/vllm/utils/__init__.py", line 3122, in run_method
(EngineCore_DP0 pid=3473945) ERROR 12-10 10:52:09 [patch_core.py:58]     return func(*args, **kwargs)
(EngineCore_DP0 pid=3473945) ERROR 12-10 10:52:09 [patch_core.py:58]   File "/root/Charlie/vllm/vllm/worker/worker_base.py", line 259, in init_device
(EngineCore_DP0 pid=3473945) ERROR 12-10 10:52:09 [patch_core.py:58]     self.worker.init_device()  # type: ignore
(EngineCore_DP0 pid=3473945) ERROR 12-10 10:52:09 [patch_core.py:58]   File "/root/Charlie/vllm-ascend/vllm_ascend/worker/worker_v1.py", line 217, in init_device
(EngineCore_DP0 pid=3473945) ERROR 12-10 10:52:09 [patch_core.py:58]     self.model_runner = NPUModelRunner(self.vllm_config, device)
(EngineCore_DP0 pid=3473945) ERROR 12-10 10:52:09 [patch_core.py:58]   File "/root/Charlie/vllm-ascend/vllm_ascend/worker/model_runner_v1.py", line 360, in __init__
(EngineCore_DP0 pid=3473945) ERROR 12-10 10:52:09 [patch_core.py:58]     self.input_ids = torch.zeros(self.max_num_tokens,
(EngineCore_DP0 pid=3473945) ERROR 12-10 10:52:09 [patch_core.py:58] RuntimeError: zero_:build/CMakeFiles/torch_npu.dir/compiler_depend.ts:26 NPU function error: call aclnnInplaceZero failed, error code is 561103
(EngineCore_DP0 pid=3473945) ERROR 12-10 10:52:09 [patch_core.py:58] [ERROR] 2025-12-10-10:52:09 (PID:3473945, Device:0, RankID:-1) ERR00100 PTA call acl api failed.
(EngineCore_DP0 pid=3473945) ERROR 12-10 10:52:09 [patch_core.py:58] EZ9999: Inner Error!
(EngineCore_DP0 pid=3473945) ERROR 12-10 10:52:09 [patch_core.py:58] EZ9999[PID: 3473945] 2025-12-10-10:52:09.632.838 AclNN_Inner_Error(EZ9999):  Parse dynamic kernel config fail.
(EngineCore_DP0 pid=3473945) ERROR 12-10 10:52:09 [patch_core.py:58]         TraceBack (most recent call last):
(EngineCore_DP0 pid=3473945) ERROR 12-10 10:52:09 [patch_core.py:58]        Failed to ParseDynamicKernels.
(EngineCore_DP0 pid=3473945) ERROR 12-10 10:52:09 [patch_core.py:58]        AclOpKernelInit failed opType
(EngineCore_DP0 pid=3473945) ERROR 12-10 10:52:09 [patch_core.py:58]        ZerosLike ADD_TO_LAUNCHER_LIST_AICORE failed.
(EngineCore_DP0 pid=3473945) ERROR 12-10 10:52:09 [patch_core.py:58]
(EngineCore_DP0 pid=3473945) Process EngineCore_DP0:
(EngineCore_DP0 pid=3473945) Traceback (most recent call last):
(EngineCore_DP0 pid=3473945)   File "/usr/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
(EngineCore_DP0 pid=3473945)     self.run()
(EngineCore_DP0 pid=3473945)   File "/usr/lib/python3.10/multiprocessing/process.py", line 108, in run
(EngineCore_DP0 pid=3473945)     self._target(*self._args, **self._kwargs)
(EngineCore_DP0 pid=3473945)   File "/root/Charlie/vllm-ascend/vllm_ascend/patch/platform/patch_core.py", line 62, in run_engine_core
(EngineCore_DP0 pid=3473945)     raise e
(EngineCore_DP0 pid=3473945)   File "/root/Charlie/vllm-ascend/vllm_ascend/patch/platform/patch_core.py", line 49, in run_engine_core
(EngineCore_DP0 pid=3473945)     engine_core = EngineCoreProc(*args, **kwargs)
(EngineCore_DP0 pid=3473945)   File "/root/Charlie/vllm/vllm/v1/engine/core.py", line 498, in __init__
(EngineCore_DP0 pid=3473945)     super().__init__(vllm_config, executor_class, log_stats,
(EngineCore_DP0 pid=3473945)   File "/root/Charlie/vllm/vllm/v1/engine/core.py", line 83, in __init__
(EngineCore_DP0 pid=3473945)     self.model_executor = executor_class(vllm_config)
(EngineCore_DP0 pid=3473945)   File "/root/Charlie/vllm/vllm/executor/executor_base.py", line 54, in __init__
(EngineCore_DP0 pid=3473945)     self._init_executor()
(EngineCore_DP0 pid=3473945)   File "/root/Charlie/vllm/vllm/executor/uniproc_executor.py", line 54, in _init_executor
(EngineCore_DP0 pid=3473945)     self.collective_rpc("init_device")
(EngineCore_DP0 pid=3473945)   File "/root/Charlie/vllm/vllm/executor/uniproc_executor.py", line 83, in collective_rpc
(EngineCore_DP0 pid=3473945)     return [run_method(self.driver_worker, method, args, kwargs)]
(EngineCore_DP0 pid=3473945)   File "/root/Charlie/vllm/vllm/utils/__init__.py", line 3122, in run_method
(EngineCore_DP0 pid=3473945)     return func(*args, **kwargs)
(EngineCore_DP0 pid=3473945)   File "/root/Charlie/vllm/vllm/worker/worker_base.py", line 259, in init_device
(EngineCore_DP0 pid=3473945)     self.worker.init_device()  # type: ignore
(EngineCore_DP0 pid=3473945)   File "/root/Charlie/vllm-ascend/vllm_ascend/worker/worker_v1.py", line 217, in init_device
(EngineCore_DP0 pid=3473945)     self.model_runner = NPUModelRunner(self.vllm_config, device)
(EngineCore_DP0 pid=3473945)   File "/root/Charlie/vllm-ascend/vllm_ascend/worker/model_runner_v1.py", line 360, in __init__
(EngineCore_DP0 pid=3473945)     self.input_ids = torch.zeros(self.max_num_tokens,
(EngineCore_DP0 pid=3473945) RuntimeError: zero_:build/CMakeFiles/torch_npu.dir/compiler_depend.ts:26 NPU function error: call aclnnInplaceZero failed, error code is 561103
(EngineCore_DP0 pid=3473945) [ERROR] 2025-12-10-10:52:09 (PID:3473945, Device:0, RankID:-1) ERR00100 PTA call acl api failed.
(EngineCore_DP0 pid=3473945) EZ9999: Inner Error!
(EngineCore_DP0 pid=3473945) EZ9999[PID: 3473945] 2025-12-10-10:52:09.632.838 AclNN_Inner_Error(EZ9999):  Parse dynamic kernel config fail.
(EngineCore_DP0 pid=3473945)         TraceBack (most recent call last):
(EngineCore_DP0 pid=3473945)        Failed to ParseDynamicKernels.
(EngineCore_DP0 pid=3473945)        AclOpKernelInit failed opType
(EngineCore_DP0 pid=3473945)        ZerosLike ADD_TO_LAUNCHER_LIST_AICORE failed.
(EngineCore_DP0 pid=3473945)
Traceback (most recent call last):
  File "/root/Charlie/test/test.py", line 13, in <module>
    llm = LLM(model="Qwen/Qwen2.5-0.5B-Instruct")
  File "/root/Charlie/vllm/vllm/entrypoints/llm.py", line 297, in __init__
    self.llm_engine = LLMEngine.from_engine_args(
  File "/root/Charlie/vllm/vllm/v1/engine/llm_engine.py", line 177, in from_engine_args
    return cls(vllm_config=vllm_config,
  File "/root/Charlie/vllm/vllm/v1/engine/llm_engine.py", line 114, in __init__
    self.engine_core = EngineCoreClient.make_client(
  File "/root/Charlie/vllm/vllm/v1/engine/core_client.py", line 80, in make_client
    return SyncMPClient(vllm_config, executor_class, log_stats)
  File "/root/Charlie/vllm/vllm/v1/engine/core_client.py", line 602, in __init__
    super().__init__(
  File "/root/Charlie/vllm/vllm/v1/engine/core_client.py", line 448, in __init__
    with launch_core_engines(vllm_config, executor_class,
  File "/usr/lib/python3.10/contextlib.py", line 142, in __exit__
    next(self.gen)
  File "/root/Charlie/vllm/vllm/v1/engine/utils.py", line 732, in launch_core_engines
    wait_for_engine_startup(
  File "/root/Charlie/vllm/vllm/v1/engine/utils.py", line 785, in wait_for_engine_startup
    raise RuntimeError("Engine core initialization failed. "
RuntimeError: Engine core initialization failed. See root cause above. Failed core proc(s): {}
[ERROR] 2025-12-10-10:52:09 (PID:3466677, Device:-1, RankID:-1) ERR99999 UNKNOWN applicaiton exception
</details>

The core error are these two lines:
```text
(EngineCore_DP0 pid=3473945) ERROR 12-10 10:52:09 [patch_core.py:58] RuntimeError: zero_:build/CMakeFiles/torch_npu.dir/compiler_depend.ts:26 NPU function error: call aclnnInplaceZero failed, error code is 561103
(EngineCore_DP0 pid=3473945) ERROR 12-10 10:52:09 [patch_core.py:58] [ERROR] 2025-12-10-10:52:09 (PID:3473945, Device:0, RankID:-1) ERR00100 PTA call acl api failed.
```

I see that there were issues before this one that talked about the same error, but they mostly occurred in an image, so I can't use their solution.

**Comment by shaojun0** [comment]
It is best to use Docker images to standardize the environment, as this is most likely an environmental issue that is difficult to troubleshoot.

**Comment by shenofusc** [comment]
I occurred the same problem, you can check if your CANN and device versions match, CANN version needs to match device version.

**Comment by Nagisa125** [comment]
Thank you for your feedback. How is the situation now? Has the issue been resolved?

**Comment by Charliewzy** [comment]
> Thank you for your feedback. How is the situation now? Has the issue been resolved?

I worked around this somehow. Thanks for the follow-up.
