### ISSUE TITLE
[Bug]: HCCL communication failure with tensor_parallel_size=2 on Ascend 300I NPU

### ISSUE THREAD

**Issue by zhima771** [vllm-project/vllm-ascend#5135]
### Your current environment

<details>
<summary>The output of `python collect_env.py`</summary>

```text
INFO 12-17 10:21:21 [importing.py:17] Triton not installed or not compatible; certain GPU-related functions will not be available.
WARNING 12-17 10:21:21 [importing.py:29] Triton is not installed. Using dummy decorators. Install it via `pip install triton` to enable kernel compilation.
INFO 12-17 10:21:22 [__init__.py:39] Available plugins for group vllm.platform_plugins:
INFO 12-17 10:21:22 [__init__.py:41] - ascend -> vllm_ascend:register
INFO 12-17 10:21:22 [__init__.py:44] All plugins in this group will be loaded. Set `VLLM_PLUGINS` to control which plugins to load.
INFO 12-17 10:21:22 [__init__.py:235] Platform plugin ascend is activated
WARNING 12-17 10:21:25 [_custom_ops.py:22] Failed to import from vllm._C with ModuleNotFoundError("No module named 'vllm._C'")
Collecting environment information...
PyTorch version: 2.5.1
Is debug build: False

OS: Ubuntu 22.04.5 LTS (aarch64)
GCC version: (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
Clang version: Could not collect
CMake version: version 4.0.3
Libc version: glibc-2.35

Python version: 3.10.17 (main, May  8 2025, 07:18:04) [GCC 11.4.0] (64-bit runtime)
Python platform: Linux-4.19.90-89.11.v2401.ky10.aarch64-aarch64-with-glibc2.35

CPU:
Architecture:                       aarch64
CPU op-mode(s):                     64-bit
Byte Order:                         Little Endian
CPU(s):                             32
On-line CPU(s) list:                0-31
Vendor ID:                          HiSilicon
Model name:                         Kunpeng-920
Model:                              0
Thread(s) per core:                 1
Core(s) per cluster:                1
Socket(s):                          -
Cluster(s):                         32
Stepping:                           0x1
Frequency boost:                    disabled
CPU max MHz:                        2600.0000
CPU min MHz:                        2600.0000
BogoMIPS:                           200.00
Flags:                              fp asimd evtstrm aes pmull sha1 sha2 crc32 atomics fphp asimdhp cpuid asimdrdm jscvt fcma dcpop asimddp asimdfhm ssbs
L1d cache:                          2 MiB (32 instances)
L1i cache:                          2 MiB (32 instances)
L2 cache:                           16 MiB (32 instances)
L3 cache:                           1 GiB (32 instances)
NUMA node(s):                       2
NUMA node0 CPU(s):                  0,2,4,6,8,10,12,14,16,18,20,22,24,26,28,30
NUMA node1 CPU(s):                  1,3,5,7,9,11,13,15,17,19,21,23,25,27,29,31
Vulnerability Gather data sampling: Not affected
Vulnerability Itlb multihit:        Not affected
Vulnerability L1tf:                 Not affected
Vulnerability Mds:                  Not affected
Vulnerability Meltdown:             Not affected
Vulnerability Mmio stale data:      Not affected
Vulnerability Retbleed:             Not affected
Vulnerability Spec store bypass:    Mitigation; Speculative Store Bypass disabled via prctl
Vulnerability Spectre v1:           Mitigation; __user pointer sanitization
Vulnerability Spectre v2:           Not affected
Vulnerability Srbds:                Not affected
Vulnerability Tsx async abort:      Not affected

Versions of relevant libraries:
[pip3] numpy==1.26.4
[pip3] pyzmq==27.0.0
[pip3] torch==2.5.1
[pip3] torch-npu==2.5.1.post1.dev20250528
[pip3] torchvision==0.20.1
[pip3] transformers==4.52.4
[conda] Could not collect
vLLM Version: 0.9.1
vLLM Ascend Version: 0.9.1rc1

ENV Variables:
ATB_OPSRUNNER_KERNEL_CACHE_TILING_SIZE=10240
ATB_OPSRUNNER_KERNEL_CACHE_LOCAL_COUNT=1
ATB_STREAM_SYNC_EVERY_RUNNER_ENABLE=0
ATB_OPSRUNNER_SETUP_CACHE_ENABLE=1
ATB_WORKSPACE_MEM_ALLOC_GLOBAL=0
ATB_DEVICE_TILING_BUFFER_BLOCK_NUM=32
ATB_STREAM_SYNC_EVERY_KERNEL_ENABLE=0
ATB_OPSRUNNER_KERNEL_CACHE_GLOABL_COUNT=5
ATB_HOME_PATH=/usr/local/Ascend/nnal/atb/latest/atb/cxx_abi_0
ASCEND_TOOLKIT_HOME=/usr/local/Ascend/ascend-toolkit/latest
ATB_COMPARE_TILING_EVERY_KERNEL=0
ASCEND_OPP_PATH=/usr/local/Ascend/ascend-toolkit/latest/opp
LD_LIBRARY_PATH=/usr/local/Ascend/nnal/atb/latest/atb/cxx_abi_0/lib:/usr/local/Ascend/nnal/atb/latest/atb/cxx_abi_0/examples:/usr/local/Ascend/nnal/atb/latest/atb/cxx_abi_0/tests/atbopstest:/usr/local/Ascend/ascend-toolkit/latest/tools/aml/lib64:/usr/local/Ascend/ascend-toolkit/latest/tools/aml/lib64/plugin:/usr/local/Ascend/ascend-toolkit/latest/lib64:/usr/local/Ascend/ascend-toolkit/latest/lib64/plugin/opskernel:/usr/local/Ascend/ascend-toolkit/latest/lib64/plugin/nnengine:/usr/local/Ascend/ascend-toolkit/latest/opp/built-in/op_impl/ai_core/tbe/op_tiling/lib/linux/aarch64:/usr/local/Ascend/nnal/atb/latest/atb/cxx_abi_0/lib:/usr/local/Ascend/nnal/atb/latest/atb/cxx_abi_0/examples:/usr/local/Ascend/nnal/atb/latest/atb/cxx_abi_0/tests/atbopstest:/usr/local/Ascend/ascend-toolkit/latest/tools/aml/lib64:/usr/local/Ascend/ascend-toolkit/latest/tools/aml/lib64/plugin:/usr/local/Ascend/ascend-toolkit/latest/lib64:/usr/local/Ascend/ascend-toolkit/latest/lib64/plugin/opskernel:/usr/local/Ascend/ascend-toolkit/latest/lib64/plugin/nnengine:/usr/local/Ascend/ascend-toolkit/latest/opp/built-in/op_impl/ai_core/tbe/op_tiling:/usr/local/Ascend/driver/lib64/common/:/usr/local/Ascend/driver/lib64/driver/:
ASCEND_AICPU_PATH=/usr/local/Ascend/ascend-toolkit/latest
ATB_OPSRUNNER_KERNEL_CACHE_TYPE=3
ATB_RUNNER_POOL_SIZE=64
ATB_STREAM_SYNC_EVERY_OPERATION_ENABLE=0
ASCEND_HOME_PATH=/usr/local/Ascend/ascend-toolkit/latest
ATB_MATMUL_SHUFFLE_K_ENABLE=1
ATB_LAUNCH_KERNEL_WITH_TILING=1
ATB_WORKSPACE_MEM_ALLOC_ALG_TYPE=1
ATB_HOST_TILING_BUFFER_BLOCK_NUM=128
ATB_SHARE_MEMORY_NAME_SUFFIX=
TORCH_DEVICE_BACKEND_AUTOLOAD=1
PYTORCH_NVML_BASED_CUDA_CHECK=1
TORCHINDUCTOR_COMPILE_THREADS=1


NPU:
+--------------------------------------------------------------------------------------------------------+
| npu-smi 22.0.4.2                                 Version: 22.0.4.2                                     |
+-------------------------------+-----------------+------------------------------------------------------+
| NPU     Name                  | Health          | Power(W)     Temp(C)           Hugepages-Usage(page) |
| Chip    Device                | Bus-Id          | AICore(%)    Memory-Usage(MB)                        |
+===============================+=================+======================================================+
| 1       310P3                 | OK              | NA           50                0    / 0              |
| 0       0                     | 0000:05:00.0    | 0            1731 / 21527                            |
+-------------------------------+-----------------+------------------------------------------------------+
| 1       310P3                 | OK              | NA           51                458  / 458            |
| 1       1                     | 0000:06:00.0    | 0            2655 / 21527                            |
+===============================+=================+======================================================+

CANN:
package_name=Ascend-cann-toolkit
version=8.1.RC1
innerversion=V100R001C21SPC001B238
compatible_version=[V100R001C15],[V100R001C18],[V100R001C19],[V100R001C20],[V100R001C21]
arch=aarch64
os=linux
path=/usr/local/Ascend/ascend-toolkit/8.1.RC1/aarch64-linux
```

</details>

### Describe
When deploying vLLM with `tensor_parallel_size=2` on Ascend 300I NPU, the engine fails to start due to HCCL communication errors during the model initialization phase.

### Command

```bash
vllm serve /models/Qwen3-0.6B \
    --tensor-parallel-size 2 \
    --enforce-eager \
    --dtype float16 \
    --compilation-config '{"custom_ops":["none", "+rms_norm", "+rotary_embedding"]}'
```

### Error Message

```
INFO 12-17 09:30:18 [importing.py:17] Triton not installed or not compatible; certain GPU-related functions will not be available.
WARNING 12-17 09:30:18 [importing.py:29] Triton is not installed. Using dummy decorators. Install it via `pip install triton` to enable kernel compilation.
INFO 12-17 09:30:19 [__init__.py:39] Available plugins for group vllm.platform_plugins:
INFO 12-17 09:30:19 [__init__.py:41] - ascend -> vllm_ascend:register
INFO 12-17 09:30:19 [__init__.py:44] All plugins in this group will be loaded. Set `VLLM_PLUGINS` to control which plugins to load.
INFO 12-17 09:30:19 [__init__.py:235] Platform plugin ascend is activated
WARNING 12-17 09:30:23 [_custom_ops.py:22] Failed to import from vllm._C with ModuleNotFoundError("No module named 'vllm._C'")
WARNING 12-17 09:30:26 [registry.py:401] Model architecture DeepSeekMTPModel is already registered, and will be overwritten by the new model class vllm_ascend.models.deepseek_mtp:CustomDeepSeekMTP.
WARNING 12-17 09:30:26 [registry.py:401] Model architecture Qwen2VLForConditionalGeneration is already registered, and will be overwritten by the new model class vllm_ascend.models.qwen2_vl:AscendQwen2VLForConditionalGeneration.
WARNING 12-17 09:30:26 [registry.py:401] Model architecture Qwen2_5_VLForConditionalGeneration is already registered, and will be overwritten by the new model class vllm_ascend.models.qwen2_5_vl:AscendQwen2_5_VLForConditionalGeneration.
WARNING 12-17 09:30:26 [registry.py:401] Model architecture DeepseekV2ForCausalLM is already registered, and will be overwritten by the new model class vllm_ascend.models.deepseek_v2:CustomDeepseekV2ForCausalLM.
WARNING 12-17 09:30:26 [registry.py:401] Model architecture DeepseekV3ForCausalLM is already registered, and will be overwritten by the new model class vllm_ascend.models.deepseek_v2:CustomDeepseekV3ForCausalLM.
WARNING 12-17 09:30:26 [registry.py:401] Model architecture Qwen3MoeForCausalLM is already registered, and will be overwritten by the new model class vllm_ascend.models.qwen3_moe:CustomQwen3MoeForCausalLM.
INFO 12-17 09:30:28 [config.py:1980] Disabled the custom all-reduce kernel because it is not supported on current platform.
INFO 12-17 09:30:29 [config.py:1980] Disabled the custom all-reduce kernel because it is not supported on current platform.
INFO 12-17 09:30:31 [config.py:1980] Disabled the custom all-reduce kernel because it is not supported on current platform.
INFO 12-17 09:30:32 [config.py:1980] Disabled the custom all-reduce kernel because it is not supported on current platform.
INFO 12-17 09:30:32 [api_server.py:1287] vLLM API server version 0.9.1
INFO 12-17 09:30:33 [config.py:1980] Disabled the custom all-reduce kernel because it is not supported on current platform.
INFO 12-17 09:30:33 [cli_args.py:309] non-default args: {'model': '/models/Qwen3-0.6B', 'dtype': 'float16', 'enforce_eager': True, 'tensor_parallel_size': 2, 'compilation_config': {"level":0,"debug_dump_path":"","cache_dir":"","backend":"","custom_ops":["none","+rms_norm","+rotary_embedding"],"splitting_ops":[],"use_inductor":true,"compile_sizes":null,"inductor_compile_config":{},"inductor_passes":{},"use_cudagraph":true,"cudagraph_num_of_warmups":0,"cudagraph_capture_sizes":null,"cudagraph_copy_inputs":false,"full_cuda_graph":false,"max_capture_size":null,"local_cache_dir":null}}
INFO 12-17 09:30:48 [config.py:823] This model supports multiple tasks: {'generate', 'classify', 'embed', 'score', 'reward'}. Defaulting to 'generate'.
WARNING 12-17 09:30:48 [config.py:3271] Casting torch.bfloat16 to torch.float16.
INFO 12-17 09:30:48 [arg_utils.py:1653] npu is experimental on VLLM_USE_V1=1. Falling back to V0 Engine.
WARNING 12-17 09:30:48 [arg_utils.py:1490] The model has a long context length (40960). This may causeOOM during the initial memory profiling phase, or result in low performance due to small KV cache size. Consider setting --max-model-len to a smaller value.
INFO 12-17 09:30:48 [config.py:1946] Defaulting to use mp for distributed inference
INFO 12-17 09:30:48 [config.py:1980] Disabled the custom all-reduce kernel because it is not supported on current platform.
INFO 12-17 09:30:48 [platform.py:164] Compilation disabled, using eager mode by default
INFO 12-17 09:30:48 [api_server.py:265] Started engine process with PID 53769
WARNING 12-17 09:30:52 [env_override.py:17] NCCL_CUMEM_ENABLE is set to 0, skipping override. This may increase memory overhead with cudagraph+allreduce: https://github.com/NVIDIA/nccl/issues/1234
INFO 12-17 09:30:53 [importing.py:17] Triton not installed or not compatible; certain GPU-related functions will not be available.
WARNING 12-17 09:30:53 [importing.py:29] Triton is not installed. Using dummy decorators. Install it via `pip install triton` to enable kernel compilation.
INFO 12-17 09:30:54 [__init__.py:39] Available plugins for group vllm.platform_plugins:
INFO 12-17 09:30:54 [__init__.py:41] - ascend -> vllm_ascend:register
INFO 12-17 09:30:54 [__init__.py:44] All plugins in this group will be loaded. Set `VLLM_PLUGINS` to control which plugins to load.
INFO 12-17 09:30:54 [__init__.py:235] Platform plugin ascend is activated
WARNING 12-17 09:30:58 [_custom_ops.py:22] Failed to import from vllm._C with ModuleNotFoundError("No module named 'vllm._C'")
WARNING 12-17 09:31:02 [registry.py:401] Model architecture DeepSeekMTPModel is already registered, and will be overwritten by the new model class vllm_ascend.models.deepseek_mtp:CustomDeepSeekMTP.
WARNING 12-17 09:31:02 [registry.py:401] Model architecture Qwen2VLForConditionalGeneration is already registered, and will be overwritten by the new model class vllm_ascend.models.qwen2_vl:AscendQwen2VLForConditionalGeneration.
WARNING 12-17 09:31:02 [registry.py:401] Model architecture Qwen2_5_VLForConditionalGeneration is already registered, and will be overwritten by the new model class vllm_ascend.models.qwen2_5_vl:AscendQwen2_5_VLForConditionalGeneration.
WARNING 12-17 09:31:02 [registry.py:401] Model architecture DeepseekV2ForCausalLM is already registered, and will be overwritten by the new model class vllm_ascend.models.deepseek_v2:CustomDeepseekV2ForCausalLM.
WARNING 12-17 09:31:02 [registry.py:401] Model architecture DeepseekV3ForCausalLM is already registered, and will be overwritten by the new model class vllm_ascend.models.deepseek_v2:CustomDeepseekV3ForCausalLM.
WARNING 12-17 09:31:02 [registry.py:401] Model architecture Qwen3MoeForCausalLM is already registered, and will be overwritten by the new model class vllm_ascend.models.qwen3_moe:CustomQwen3MoeForCausalLM.
INFO 12-17 09:31:02 [llm_engine.py:230] Initializing a V0 LLM engine (v0.9.1) with config: model='/models/Qwen3-0.6B', speculative_config=None, tokenizer='/models/Qwen3-0.6B', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, override_neuron_config={}, tokenizer_revision=None, trust_remote_code=False, dtype=torch.float16, max_seq_len=40960, download_dir=None, load_format=auto, tensor_parallel_size=2, pipeline_parallel_size=1, disable_custom_all_reduce=True, quantization=None, enforce_eager=True, kv_cache_dtype=auto,  device_config=npu, decoding_config=DecodingConfig(backend='auto', disable_fallback=False, disable_any_whitespace=False, disable_additional_properties=False, reasoning_backend=''), observability_config=ObservabilityConfig(show_hidden_metrics_for_version=None, otlp_traces_endpoint=None, collect_detailed_traces=None), seed=0, served_model_name=/models/Qwen3-0.6B, num_scheduler_steps=1, multi_step_stream_outputs=True, enable_prefix_caching=None, chunked_prefill_enabled=False, use_async_output_proc=True, pooler_config=None, compilation_config={"level":0,"debug_dump_path":"","cache_dir":"","backend":"","custom_ops":["none","+rms_norm","+rotary_embedding"],"splitting_ops":[],"use_inductor":true,"compile_sizes":[],"inductor_compile_config":{},"inductor_passes":{},"use_cudagraph":true,"cudagraph_num_of_warmups":0,"cudagraph_capture_sizes":[],"cudagraph_copy_inputs":false,"full_cuda_graph":false,"max_capture_size":0,"local_cache_dir":null}, use_cached_outputs=True, 
WARNING 12-17 09:31:02 [multiproc_worker_utils.py:307] Reducing Torch parallelism from 32 threads to 1 to avoid unnecessary CPU contention. Set OMP_NUM_THREADS in the external environment to tune this value as needed.
WARNING 12-17 09:31:02 [utils.py:2737] Methods add_prompt_adapter,cache_config,compilation_config,current_platform,list_prompt_adapters,load_config,pin_prompt_adapter,remove_prompt_adapter not implemented in <vllm_ascend.worker.worker.NPUWorker object at 0xfffd63f82b30>
WARNING 12-17 09:31:06 [env_override.py:17] NCCL_CUMEM_ENABLE is set to 0, skipping override. This may increase memory overhead with cudagraph+allreduce: https://github.com/NVIDIA/nccl/issues/1234
INFO 12-17 09:31:08 [importing.py:17] Triton not installed or not compatible; certain GPU-related functions will not be available.
WARNING 12-17 09:31:08 [importing.py:29] Triton is not installed. Using dummy decorators. Install it via `pip install triton` to enable kernel compilation.
INFO 12-17 09:31:09 [__init__.py:39] Available plugins for group vllm.platform_plugins:
INFO 12-17 09:31:09 [__init__.py:41] - ascend -> vllm_ascend:register
INFO 12-17 09:31:09 [__init__.py:44] All plugins in this group will be loaded. Set `VLLM_PLUGINS` to control which plugins to load.
INFO 12-17 09:31:09 [__init__.py:235] Platform plugin ascend is activated
WARNING 12-17 09:31:12 [_custom_ops.py:22] Failed to import from vllm._C with ModuleNotFoundError("No module named 'vllm._C'")
[1;36m(VllmWorkerProcess pid=53843)[0;0m INFO 12-17 09:31:14 [multiproc_worker_utils.py:226] Worker ready; awaiting tasks
[1;36m(VllmWorkerProcess pid=53843)[0;0m WARNING 12-17 09:31:16 [registry.py:401] Model architecture DeepSeekMTPModel is already registered, and will be overwritten by the new model class vllm_ascend.models.deepseek_mtp:CustomDeepSeekMTP.
[1;36m(VllmWorkerProcess pid=53843)[0;0m WARNING 12-17 09:31:16 [registry.py:401] Model architecture Qwen2VLForConditionalGeneration is already registered, and will be overwritten by the new model class vllm_ascend.models.qwen2_vl:AscendQwen2VLForConditionalGeneration.
[1;36m(VllmWorkerProcess pid=53843)[0;0m WARNING 12-17 09:31:16 [registry.py:401] Model architecture Qwen2_5_VLForConditionalGeneration is already registered, and will be overwritten by the new model class vllm_ascend.models.qwen2_5_vl:AscendQwen2_5_VLForConditionalGeneration.
[1;36m(VllmWorkerProcess pid=53843)[0;0m WARNING 12-17 09:31:16 [registry.py:401] Model architecture DeepseekV2ForCausalLM is already registered, and will be overwritten by the new model class vllm_ascend.models.deepseek_v2:CustomDeepseekV2ForCausalLM.
[1;36m(VllmWorkerProcess pid=53843)[0;0m WARNING 12-17 09:31:16 [registry.py:401] Model architecture DeepseekV3ForCausalLM is already registered, and will be overwritten by the new model class vllm_ascend.models.deepseek_v2:CustomDeepseekV3ForCausalLM.
[1;36m(VllmWorkerProcess pid=53843)[0;0m WARNING 12-17 09:31:16 [registry.py:401] Model architecture Qwen3MoeForCausalLM is already registered, and will be overwritten by the new model class vllm_ascend.models.qwen3_moe:CustomQwen3MoeForCausalLM.
[1;36m(VllmWorkerProcess pid=53843)[0;0m WARNING 12-17 09:31:16 [utils.py:2737] Methods add_prompt_adapter,cache_config,compilation_config,current_platform,list_prompt_adapters,load_config,pin_prompt_adapter,remove_prompt_adapter not implemented in <vllm_ascend.worker.worker.NPUWorker object at 0xfffba8737af0>
WARNING 12-17 09:31:23 [env_override.py:17] NCCL_CUMEM_ENABLE is set to 0, skipping override. This may increase memory overhead with cudagraph+allreduce: https://github.com/NVIDIA/nccl/issues/1234
WARNING 12-17 09:31:23 [env_override.py:17] NCCL_CUMEM_ENABLE is set to 0, skipping override. This may increase memory overhead with cudagraph+allreduce: https://github.com/NVIDIA/nccl/issues/1234
INFO 12-17 09:31:24 [importing.py:17] Triton not installed or not compatible; certain GPU-related functions will not be available.
WARNING 12-17 09:31:24 [importing.py:29] Triton is not installed. Using dummy decorators. Install it via `pip install triton` to enable kernel compilation.
INFO 12-17 09:31:25 [importing.py:17] Triton not installed or not compatible; certain GPU-related functions will not be available.
WARNING 12-17 09:31:25 [importing.py:29] Triton is not installed. Using dummy decorators. Install it via `pip install triton` to enable kernel compilation.
INFO 12-17 09:31:25 [__init__.py:39] Available plugins for group vllm.platform_plugins:
INFO 12-17 09:31:25 [__init__.py:41] - ascend -> vllm_ascend:register
INFO 12-17 09:31:25 [__init__.py:44] All plugins in this group will be loaded. Set `VLLM_PLUGINS` to control which plugins to load.
INFO 12-17 09:31:25 [__init__.py:235] Platform plugin ascend is activated
INFO 12-17 09:31:26 [__init__.py:39] Available plugins for group vllm.platform_plugins:
INFO 12-17 09:31:26 [__init__.py:41] - ascend -> vllm_ascend:register
INFO 12-17 09:31:26 [__init__.py:44] All plugins in this group will be loaded. Set `VLLM_PLUGINS` to control which plugins to load.
INFO 12-17 09:31:26 [__init__.py:235] Platform plugin ascend is activated
WARNING 12-17 09:31:29 [_custom_ops.py:22] Failed to import from vllm._C with ModuleNotFoundError("No module named 'vllm._C'")
WARNING 12-17 09:31:29 [_custom_ops.py:22] Failed to import from vllm._C with ModuleNotFoundError("No module named 'vllm._C'")
INFO 12-17 09:31:39 [shm_broadcast.py:289] vLLM message queue communication handle: Handle(local_reader_ranks=[1], buffer_handle=(1, 4194304, 6, 'psm_7ea445a3'), local_subscribe_addr='ipc:///tmp/eeb22c1b-6c4f-470f-99d1-5bf5bb7e5067', remote_subscribe_addr=None, remote_addr_ipv6=False)
[1;36m(VllmWorkerProcess pid=53843)[0;0m INFO 12-17 09:31:39 [parallel_state.py:1065] rank 1 in world size 2 is assigned as DP rank 0, PP rank 0, TP rank 1, EP rank 1
INFO 12-17 09:31:39 [parallel_state.py:1065] rank 0 in world size 2 is assigned as DP rank 0, PP rank 0, TP rank 0, EP rank 0
INFO 12-17 09:31:39 [model_runner.py:995] Starting to load model /models/Qwen3-0.6B...
[1;36m(VllmWorkerProcess pid=53843)[0;0m INFO 12-17 09:31:39 [model_runner.py:995] Starting to load model /models/Qwen3-0.6B...
Loading safetensors checkpoint shards:   0% Completed | 0/1 [00:00<?, ?it/s]
Loading safetensors checkpoint shards: 100% Completed | 1/1 [00:00<00:00,  1.40it/s]
Loading safetensors checkpoint shards: 100% Completed | 1/1 [00:00<00:00,  1.40it/s]

INFO 12-17 09:31:50 [default_loader.py:272] Loading weights took 0.72 seconds
[WARN]operator(),compiler_depend.ts:831:Feature is not supportted and the possible cause is that driver and firmware packages do not match.
[WARN]operator(),compiler_depend.ts:200:Feature is not supportted and the possible cause is that driver and firmware packages do not match.
[WARN]operator(),compiler_depend.ts:208:Feature is not supportted and the possible cause is that driver and firmware packages do not match.
.[1;36m(VllmWorkerProcess pid=53843)[0;0m INFO 12-17 09:31:51 [default_loader.py:272] Loading weights took 0.74 seconds
INFO 12-17 09:31:52 [model_runner.py:1000] Loading model weights took 0.5797 GB
[1;36m(VllmWorkerProcess pid=53843)[0;0m INFO 12-17 09:31:53 [model_runner.py:1000] Loading model weights took 0.5797 GB
[WARN]operator(),compiler_depend.ts:831:Feature is not supportted and the possible cause is that driver and firmware packages do not match.
[WARN]operator(),compiler_depend.ts:200:Feature is not supportted and the possible cause is that driver and firmware packages do not match.
[WARN]operator(),compiler_depend.ts:208:Feature is not supportted and the possible cause is that driver and firmware packages do not match.
[rank0]:[W1217 09:31:53.470190800 compiler_depend.ts:82] Warning: The oprator of add is executed, Currently High Accuracy but Low Performance OP with 64-bit has been used, Please Do Some Cast at Python Functions with 32-bit for Better Performance! (function operator())
[rank1]:[W1217 09:31:53.484627090 compiler_depend.ts:82] Warning: The oprator of add is executed, Currently High Accuracy but Low Performance OP with 64-bit has been used, Please Do Some Cast at Python Functions with 32-bit for Better Performance! (function operator())
.[rank0]:[W1217 09:31:57.528251500 compiler_depend.ts:159] Warning: Warning: Device do not support double dtype now, dtype cast repalce with float. (function operator())
ERROR 12-17 09:31:58 [engine.py:458] createHCCLComm:build/CMakeFiles/torch_npu.dir/compiler_depend.ts:1550 HCCL function error: HcclGetRootInfo(&hcclID), error code is 2
ERROR 12-17 09:31:58 [engine.py:458] [ERROR] 2025-12-17-09:31:53 (PID:53769, Device:0, RankID:-1) ERR02200 DIST call hccl api failed.
ERROR 12-17 09:31:58 [engine.py:458] EH9999: Inner Error!
ERROR 12-17 09:31:58 [engine.py:458] EH9999: [PID: 53769] 2025-12-17-09:31:39.804.969 rtSetStreamFailureMode failed, runtime result = 207000.[FUNC:ReportCallError][FILE:log_inner.cpp][LINE:161]
ERROR 12-17 09:31:58 [engine.py:458]         TraceBack (most recent call last):
ERROR 12-17 09:31:58 [engine.py:458] Traceback (most recent call last):
ERROR 12-17 09:31:58 [engine.py:458]   File "/vllm-workspace/vllm/vllm/engine/multiprocessing/engine.py", line 446, in run_mp_engine
ERROR 12-17 09:31:58 [engine.py:458]     engine = MQLLMEngine.from_vllm_config(
ERROR 12-17 09:31:58 [engine.py:458]   File "/vllm-workspace/vllm/vllm/engine/multiprocessing/engine.py", line 133, in from_vllm_config
ERROR 12-17 09:31:58 [engine.py:458]     return cls(
ERROR 12-17 09:31:58 [engine.py:458]   File "/vllm-workspace/vllm/vllm/engine/multiprocessing/engine.py", line 87, in __init__
ERROR 12-17 09:31:58 [engine.py:458]     self.engine = LLMEngine(*args, **kwargs)
ERROR 12-17 09:31:58 [engine.py:458]   File "/vllm-workspace/vllm/vllm/engine/llm_engine.py", line 268, in __init__
ERROR 12-17 09:31:58 [engine.py:458]     self._initialize_kv_caches()
ERROR 12-17 09:31:58 [engine.py:458]   File "/vllm-workspace/vllm/vllm/engine/llm_engine.py", line 413, in _initialize_kv_caches
ERROR 12-17 09:31:58 [engine.py:458]     self.model_executor.determine_num_available_blocks())
ERROR 12-17 09:31:58 [engine.py:458]   File "/vllm-workspace/vllm/vllm/executor/executor_base.py", line 104, in determine_num_available_blocks
ERROR 12-17 09:31:58 [engine.py:458]     results = self.collective_rpc("determine_num_available_blocks")
ERROR 12-17 09:31:58 [engine.py:458]   File "/vllm-workspace/vllm/vllm/executor/executor_base.py", line 332, in collective_rpc
ERROR 12-17 09:31:58 [engine.py:458]     return self._run_workers(method, *args, **(kwargs or {}))
ERROR 12-17 09:31:58 [engine.py:458]   File "/vllm-workspace/vllm/vllm/executor/mp_distributed_executor.py", line 186, in _run_workers
ERROR 12-17 09:31:58 [engine.py:458]     driver_worker_output = run_method(self.driver_worker, sent_method,
ERROR 12-17 09:31:58 [engine.py:458]   File "/vllm-workspace/vllm/vllm/utils.py", line 2671, in run_method
ERROR 12-17 09:31:58 [engine.py:458]     return func(*args, **kwargs)
ERROR 12-17 09:31:58 [engine.py:458]   File "/usr/local/python3.10.17/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
ERROR 12-17 09:31:58 [engine.py:458]     return func(*args, **kwargs)
ERROR 12-17 09:31:58 [engine.py:458]   File "/vllm-workspace/vllm-ascend/vllm_ascend/worker/worker.py", line 288, in determine_num_available_blocks
ERROR 12-17 09:31:58 [engine.py:458]     self.model_runner.profile_run()
ERROR 12-17 09:31:58 [engine.py:458]   File "/usr/local/python3.10.17/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
ERROR 12-17 09:31:58 [engine.py:458]     return func(*args, **kwargs)
ERROR 12-17 09:31:58 [engine.py:458]   File "/vllm-workspace/vllm-ascend/vllm_ascend/worker/model_runner.py", line 1205, in profile_run
ERROR 12-17 09:31:58 [engine.py:458]     self.execute_model(model_input, kv_caches, intermediate_tensors)
ERROR 12-17 09:31:58 [engine.py:458]   File "/usr/local/python3.10.17/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
ERROR 12-17 09:31:58 [engine.py:458]     return func(*args, **kwargs)
ERROR 12-17 09:31:58 [engine.py:458]   File "/vllm-workspace/vllm-ascend/vllm_ascend/worker/model_runner.py", line 1441, in execute_model
ERROR 12-17 09:31:58 [engine.py:458]     hidden_or_intermediate_states = model_executable(
ERROR 12-17 09:31:58 [engine.py:458]   File "/usr/local/python3.10.17/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
ERROR 12-17 09:31:58 [engine.py:458]     return self._call_impl(*args, **kwargs)
ERROR 12-17 09:31:58 [engine.py:458]   File "/usr/local/python3.10.17/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
ERROR 12-17 09:31:58 [engine.py:458]     return forward_call(*args, **kwargs)
ERROR 12-17 09:31:58 [engine.py:458]   File "/vllm-workspace/vllm/vllm/model_executor/models/qwen3.py", line 301, in forward
ERROR 12-17 09:31:58 [engine.py:458]     hidden_states = self.model(input_ids, positions, intermediate_tensors,
ERROR 12-17 09:31:58 [engine.py:458]   File "/vllm-workspace/vllm/vllm/compilation/decorators.py", line 173, in __call__
ERROR 12-17 09:31:58 [engine.py:458]     return self.forward(*args, **kwargs)
ERROR 12-17 09:31:58 [engine.py:458]   File "/vllm-workspace/vllm/vllm/model_executor/models/qwen2.py", line 347, in forward
ERROR 12-17 09:31:58 [engine.py:458]     hidden_states = self.get_input_embeddings(input_ids)
ERROR 12-17 09:31:58 [engine.py:458]   File "/vllm-workspace/vllm/vllm/model_executor/models/qwen2.py", line 334, in get_input_embeddings
ERROR 12-17 09:31:58 [engine.py:458]     return self.embed_tokens(input_ids)
ERROR 12-17 09:31:58 [engine.py:458]   File "/usr/local/python3.10.17/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
ERROR 12-17 09:31:58 [engine.py:458]     return self._call_impl(*args, **kwargs)
ERROR 12-17 09:31:58 [engine.py:458]   File "/usr/local/python3.10.17/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
ERROR 12-17 09:31:58 [engine.py:458]     return forward_call(*args, **kwargs)
ERROR 12-17 09:31:58 [engine.py:458]   File "/vllm-workspace/vllm-ascend/vllm_ascend/ops/vocab_parallel_embedding.py", line 63, in vocab_parallel_embedding_forward
ERROR 12-17 09:31:58 [engine.py:458]     output = tensor_model_parallel_all_reduce(output_parallel)
ERROR 12-17 09:31:58 [engine.py:458]   File "/vllm-workspace/vllm/vllm/distributed/communication_op.py", line 14, in tensor_model_parallel_all_reduce
ERROR 12-17 09:31:58 [engine.py:458]     return get_tp_group().all_reduce(input_)
ERROR 12-17 09:31:58 [engine.py:458]   File "/vllm-workspace/vllm/vllm/distributed/parallel_state.py", line 359, in all_reduce
ERROR 12-17 09:31:58 [engine.py:458]     return self._all_reduce_out_place(input_)
ERROR 12-17 09:31:58 [engine.py:458]   File "/vllm-workspace/vllm/vllm/distributed/parallel_state.py", line 362, in _all_reduce_out_place
ERROR 12-17 09:31:58 [engine.py:458]     return self.device_communicator.all_reduce(input_)
ERROR 12-17 09:31:58 [engine.py:458]   File "/vllm-workspace/vllm/vllm/distributed/device_communicators/base_device_communicator.py", line 112, in all_reduce
ERROR 12-17 09:31:58 [engine.py:458]     dist.all_reduce(input_, group=self.device_group)
ERROR 12-17 09:31:58 [engine.py:458]   File "/usr/local/python3.10.17/lib/python3.10/site-packages/torch/distributed/c10d_logger.py", line 83, in wrapper
ERROR 12-17 09:31:58 [engine.py:458]     return func(*args, **kwargs)
ERROR 12-17 09:31:58 [engine.py:458]   File "/usr/local/python3.10.17/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py", line 2501, in all_reduce
ERROR 12-17 09:31:58 [engine.py:458]     work = group.allreduce([tensor], opts)
ERROR 12-17 09:31:58 [engine.py:458] RuntimeError: createHCCLComm:build/CMakeFiles/torch_npu.dir/compiler_depend.ts:1550 HCCL function error: HcclGetRootInfo(&hcclID), error code is 2
ERROR 12-17 09:31:58 [engine.py:458] [ERROR] 2025-12-17-09:31:53 (PID:53769, Device:0, RankID:-1) ERR02200 DIST call hccl api failed.
ERROR 12-17 09:31:58 [engine.py:458] EH9999: Inner Error!
ERROR 12-17 09:31:58 [engine.py:458] EH9999: [PID: 53769] 2025-12-17-09:31:39.804.969 rtSetStreamFailureMode failed, runtime result = 207000.[FUNC:ReportCallError][FILE:log_inner.cpp][LINE:161]
ERROR 12-17 09:31:58 [engine.py:458]         TraceBack (most recent call last):
ERROR 12-17 09:31:58 [engine.py:458] 
Traceback (most recent call last):
  File "/usr/local/python3.10.17/bin/vllm", line 8, in <module>
    sys.exit(main())
  File "/vllm-workspace/vllm/vllm/entrypoints/cli/main.py", line 59, in main
    args.dispatch_function(args)
  File "/vllm-workspace/vllm/vllm/entrypoints/cli/serve.py", line 58, in cmd
    uvloop.run(run_server(args))
  File "/usr/local/python3.10.17/lib/python3.10/site-packages/uvloop/__init__.py", line 82, in run
    return loop.run_until_complete(wrapper())
  File "uvloop/loop.pyx", line 1518, in uvloop.loop.Loop.run_until_complete
  File "/usr/local/python3.10.17/lib/python3.10/site-packages/uvloop/__init__.py", line 61, in wrapper
    return await main
  File "/vllm-workspace/vllm/vllm/entrypoints/openai/api_server.py", line 1323, in run_server
    await run_server_worker(listen_address, sock, args, **uvicorn_kwargs)
  File "/vllm-workspace/vllm/vllm/entrypoints/openai/api_server.py", line 1343, in run_server_worker
    async with build_async_engine_client(args, client_config) as engine_client:
  File "/usr/local/python3.10.17/lib/python3.10/contextlib.py", line 199, in __aenter__
    return await anext(self.gen)
  File "/vllm-workspace/vllm/vllm/entrypoints/openai/api_server.py", line 155, in build_async_engine_client
    async with build_async_engine_client_from_engine_args(
  File "/usr/local/python3.10.17/lib/python3.10/contextlib.py", line 199, in __aenter__
    return await anext(self.gen)
  File "/vllm-workspace/vllm/vllm/entrypoints/openai/api_server.py", line 288, in build_async_engine_client_from_engine_args
    raise RuntimeError(
RuntimeError: Engine process failed to start. See stack trace for the root cause.
[ERROR] 2025-12-17-09:32:02 (PID:53688, Device:-1, RankID:-1) ERR99999 UNKNOWN applicaiton exception
.[1;36m(VllmWorkerProcess pid=53843)[0;0m ERROR 12-17 09:32:03 [multiproc_worker_utils.py:239] Exception in worker VllmWorkerProcess while processing method determine_num_available_blocks.
[1;36m(VllmWorkerProcess pid=53843)[0;0m ERROR 12-17 09:32:03 [multiproc_worker_utils.py:239] Traceback (most recent call last):
[1;36m(VllmWorkerProcess pid=53843)[0;0m ERROR 12-17 09:32:03 [multiproc_worker_utils.py:239]   File "/vllm-workspace/vllm/vllm/executor/multiproc_worker_utils.py", line 233, in _run_worker_process
[1;36m(VllmWorkerProcess pid=53843)[0;0m ERROR 12-17 09:32:03 [multiproc_worker_utils.py:239]     output = run_method(worker, method, args, kwargs)
[1;36m(VllmWorkerProcess pid=53843)[0;0m ERROR 12-17 09:32:03 [multiproc_worker_utils.py:239]   File "/vllm-workspace/vllm/vllm/utils.py", line 2671, in run_method
[1;36m(VllmWorkerProcess pid=53843)[0;0m ERROR 12-17 09:32:03 [multiproc_worker_utils.py:239]     return func(*args, **kwargs)
[1;36m(VllmWorkerProcess pid=53843)[0;0m ERROR 12-17 09:32:03 [multiproc_worker_utils.py:239]   File "/usr/local/python3.10.17/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
[1;36m(VllmWorkerProcess pid=53843)[0;0m ERROR 12-17 09:32:03 [multiproc_worker_utils.py:239]     return func(*args, **kwargs)
[1;36m(VllmWorkerProcess pid=53843)[0;0m ERROR 12-17 09:32:03 [multiproc_worker_utils.py:239]   File "/vllm-workspace/vllm-ascend/vllm_ascend/worker/worker.py", line 288, in determine_num_available_blocks
[1;36m(VllmWorkerProcess pid=53843)[0;0m ERROR 12-17 09:32:03 [multiproc_worker_utils.py:239]     self.model_runner.profile_run()
[1;36m(VllmWorkerProcess pid=53843)[0;0m ERROR 12-17 09:32:03 [multiproc_worker_utils.py:239]   File "/usr/local/python3.10.17/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
[1;36m(VllmWorkerProcess pid=53843)[0;0m ERROR 12-17 09:32:03 [multiproc_worker_utils.py:239]     return func(*args, **kwargs)
[1;36m(VllmWorkerProcess pid=53843)[0;0m ERROR 12-17 09:32:03 [multiproc_worker_utils.py:239]   File "/vllm-workspace/vllm-ascend/vllm_ascend/worker/model_runner.py", line 1205, in profile_run
[1;36m(VllmWorkerProcess pid=53843)[0;0m ERROR 12-17 09:32:03 [multiproc_worker_utils.py:239]     self.execute_model(model_input, kv_caches, intermediate_tensors)
[1;36m(VllmWorkerProcess pid=53843)[0;0m ERROR 12-17 09:32:03 [multiproc_worker_utils.py:239]   File "/usr/local/python3.10.17/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
[1;36m(VllmWorkerProcess pid=53843)[0;0m ERROR 12-17 09:32:03 [multiproc_worker_utils.py:239]     return func(*args, **kwargs)
[1;36m(VllmWorkerProcess pid=53843)[0;0m ERROR 12-17 09:32:03 [multiproc_worker_utils.py:239]   File "/vllm-workspace/vllm-ascend/vllm_ascend/worker/model_runner.py", line 1441, in execute_model
[1;36m(VllmWorkerProcess pid=53843)[0;0m ERROR 12-17 09:32:03 [multiproc_worker_utils.py:239]     hidden_or_intermediate_states = model_executable(
[1;36m(VllmWorkerProcess pid=53843)[0;0m ERROR 12-17 09:32:03 [multiproc_worker_utils.py:239]   File "/usr/local/python3.10.17/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
[1;36m(VllmWorkerProcess pid=53843)[0;0m ERROR 12-17 09:32:03 [multiproc_worker_utils.py:239]     return self._call_impl(*args, **kwargs)
[1;36m(VllmWorkerProcess pid=53843)[0;0m ERROR 12-17 09:32:03 [multiproc_worker_utils.py:239]   File "/usr/local/python3.10.17/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
[1;36m(VllmWorkerProcess pid=53843)[0;0m ERROR 12-17 09:32:03 [multiproc_worker_utils.py:239]     return forward_call(*args, **kwargs)
[1;36m(VllmWorkerProcess pid=53843)[0;0m ERROR 12-17 09:32:03 [multiproc_worker_utils.py:239]   File "/vllm-workspace/vllm/vllm/model_executor/models/qwen3.py", line 301, in forward
[1;36m(VllmWorkerProcess pid=53843)[0;0m ERROR 12-17 09:32:03 [multiproc_worker_utils.py:239]     hidden_states = self.model(input_ids, positions, intermediate_tensors,
[1;36m(VllmWorkerProcess pid=53843)[0;0m ERROR 12-17 09:32:03 [multiproc_worker_utils.py:239]   File "/vllm-workspace/vllm/vllm/compilation/decorators.py", line 173, in __call__
[1;36m(VllmWorkerProcess pid=53843)[0;0m ERROR 12-17 09:32:03 [multiproc_worker_utils.py:239]     return self.forward(*args, **kwargs)
[1;36m(VllmWorkerProcess pid=53843)[0;0m ERROR 12-17 09:32:03 [multiproc_worker_utils.py:239]   File "/vllm-workspace/vllm/vllm/model_executor/models/qwen2.py", line 347, in forward
[1;36m(VllmWorkerProcess pid=53843)[0;0m ERROR 12-17 09:32:03 [multiproc_worker_utils.py:239]     hidden_states = self.get_input_embeddings(input_ids)
[1;36m(VllmWorkerProcess pid=53843)[0;0m ERROR 12-17 09:32:03 [multiproc_worker_utils.py:239]   File "/vllm-workspace/vllm/vllm/model_executor/models/qwen2.py", line 334, in get_input_embeddings
[1;36m(VllmWorkerProcess pid=53843)[0;0m ERROR 12-17 09:32:03 [multiproc_worker_utils.py:239]     return self.embed_tokens(input_ids)
[1;36m(VllmWorkerProcess pid=53843)[0;0m ERROR 12-17 09:32:03 [multiproc_worker_utils.py:239]   File "/usr/local/python3.10.17/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1736, in _wrapped_call_impl
[1;36m(VllmWorkerProcess pid=53843)[0;0m ERROR 12-17 09:32:03 [multiproc_worker_utils.py:239]     return self._call_impl(*args, **kwargs)
[1;36m(VllmWorkerProcess pid=53843)[0;0m ERROR 12-17 09:32:03 [multiproc_worker_utils.py:239]   File "/usr/local/python3.10.17/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1747, in _call_impl
[1;36m(VllmWorkerProcess pid=53843)[0;0m ERROR 12-17 09:32:03 [multiproc_worker_utils.py:239]     return forward_call(*args, **kwargs)
[1;36m(VllmWorkerProcess pid=53843)[0;0m ERROR 12-17 09:32:03 [multiproc_worker_utils.py:239]   File "/vllm-workspace/vllm-ascend/vllm_ascend/ops/vocab_parallel_embedding.py", line 63, in vocab_parallel_embedding_forward
[1;36m(VllmWorkerProcess pid=53843)[0;0m ERROR 12-17 09:32:03 [multiproc_worker_utils.py:239]     output = tensor_model_parallel_all_reduce(output_parallel)
[1;36m(VllmWorkerProcess pid=53843)[0;0m ERROR 12-17 09:32:03 [multiproc_worker_utils.py:239]   File "/vllm-workspace/vllm/vllm/distributed/communication_op.py", line 14, in tensor_model_parallel_all_reduce
[1;36m(VllmWorkerProcess pid=53843)[0;0m ERROR 12-17 09:32:03 [multiproc_worker_utils.py:239]     return get_tp_group().all_reduce(input_)
[1;36m(VllmWorkerProcess pid=53843)[0;0m ERROR 12-17 09:32:03 [multiproc_worker_utils.py:239]   File "/vllm-workspace/vllm/vllm/distributed/parallel_state.py", line 359, in all_reduce
[1;36m(VllmWorkerProcess pid=53843)[0;0m ERROR 12-17 09:32:03 [multiproc_worker_utils.py:239]     return self._all_reduce_out_place(input_)
[1;36m(VllmWorkerProcess pid=53843)[0;0m ERROR 12-17 09:32:03 [multiproc_worker_utils.py:239]   File "/vllm-workspace/vllm/vllm/distributed/parallel_state.py", line 362, in _all_reduce_out_place
[1;36m(VllmWorkerProcess pid=53843)[0;0m ERROR 12-17 09:32:03 [multiproc_worker_utils.py:239]     return self.device_communicator.all_reduce(input_)
[1;36m(VllmWorkerProcess pid=53843)[0;0m ERROR 12-17 09:32:03 [multiproc_worker_utils.py:239]   File "/vllm-workspace/vllm/vllm/distributed/device_communicators/base_device_communicator.py", line 112, in all_reduce
[1;36m(VllmWorkerProcess pid=53843)[0;0m ERROR 12-17 09:32:03 [multiproc_worker_utils.py:239]     dist.all_reduce(input_, group=self.device_group)
[1;36m(VllmWorkerProcess pid=53843)[0;0m ERROR 12-17 09:32:03 [multiproc_worker_utils.py:239]   File "/usr/local/python3.10.17/lib/python3.10/site-packages/torch/distributed/c10d_logger.py", line 83, in wrapper
[1;36m(VllmWorkerProcess pid=53843)[0;0m ERROR 12-17 09:32:03 [multiproc_worker_utils.py:239]     return func(*args, **kwargs)
[1;36m(VllmWorkerProcess pid=53843)[0;0m ERROR 12-17 09:32:03 [multiproc_worker_utils.py:239]   File "/usr/local/python3.10.17/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py", line 2501, in all_reduce
[1;36m(VllmWorkerProcess pid=53843)[0;0m ERROR 12-17 09:32:03 [multiproc_worker_utils.py:239]     work = group.allreduce([tensor], opts)
[1;36m(VllmWorkerProcess pid=53843)[0;0m ERROR 12-17 09:32:03 [multiproc_worker_utils.py:239] RuntimeError: [1] is setting up HCCL communicator and retrieving hcclUniqueId from [0] via c10d key-value store by key '0', but store->get('0') got error: failed to recv, got 0 bytes
[1;36m(VllmWorkerProcess pid=53843)[0;0m ERROR 12-17 09:32:03 [multiproc_worker_utils.py:239] Exception raised from recvBytes at /pytorch/torch/csrc/distributed/c10d/Utils.hpp:670 (most recent call first):
[1;36m(VllmWorkerProcess pid=53843)[0;0m ERROR 12-17 09:32:03 [multiproc_worker_utils.py:239] frame #0: c10::Error::Error(c10::SourceLocation, std::string) + 0xb8 (0xfffbd6eec908 in /usr/local/python3.10.17/lib/python3.10/site-packages/torch/lib/libc10.so)
[1;36m(VllmWorkerProcess pid=53843)[0;0m ERROR 12-17 09:32:03 [multiproc_worker_utils.py:239] frame #1: <unknown function> + 0x4e5ecf0 (0xfffbdb9decf0 in /usr/local/python3.10.17/lib/python3.10/site-packages/torch/lib/libtorch_cpu.so)
[1;36m(VllmWorkerProcess pid=53843)[0;0m ERROR 12-17 09:32:03 [multiproc_worker_utils.py:239] frame #2: <unknown function> + 0x4e61c4c (0xfffbdb9e1c4c in /usr/local/python3.10.17/lib/python3.10/site-packages/torch/lib/libtorch_cpu.so)
[1;36m(VllmWorkerProcess pid=53843)[0;0m ERROR 12-17 09:32:03 [multiproc_worker_utils.py:239] frame #3: c10d::TCPStore::doWait(c10::ArrayRef<std::string>, std::chrono::duration<long, std::ratio<1l, 1000l> >) + 0x288 (0xfffbdb9e4778 in /usr/local/python3.10.17/lib/python3.10/site-packages/torch/lib/libtorch_cpu.so)
[1;36m(VllmWorkerProcess pid=53843)[0;0m ERROR 12-17 09:32:03 [multiproc_worker_utils.py:239] frame #4: c10d::TCPStore::doGet(std::string const&) + 0x2c (0xfffbdb9e5a6c in /usr/local/python3.10.17/lib/python3.10/site-packages/torch/lib/libtorch_cpu.so)
[1;36m(VllmWorkerProcess pid=53843)[0;0m ERROR 12-17 09:32:03 [multiproc_worker_utils.py:239] frame #5: c10d::TCPStore::get(std::string const&) + 0x90 (0xfffbdb9e5c70 in /usr/local/python3.10.17/lib/python3.10/site-packages/torch/lib/libtorch_cpu.so)
[1;36m(VllmWorkerProcess pid=53843)[0;0m ERROR 12-17 09:32:03 [multiproc_worker_utils.py:239] frame #6: c10d::PrefixStore::get(std::string const&) + 0x3c (0xfffbdb99a99c in /usr/local/python3.10.17/lib/python3.10/site-packages/torch/lib/libtorch_cpu.so)
[1;36m(VllmWorkerProcess pid=53843)[0;0m ERROR 12-17 09:32:03 [multiproc_worker_utils.py:239] frame #7: c10d::PrefixStore::get(std::string const&) + 0x3c (0xfffbdb99a99c in /usr/local/python3.10.17/lib/python3.10/site-packages/torch/lib/libtorch_cpu.so)
[1;36m(VllmWorkerProcess pid=53843)[0;0m ERROR 12-17 09:32:03 [multiproc_worker_utils.py:239] frame #8: c10d::PrefixStore::get(std::string const&) + 0x3c (0xfffbdb99a99c in /usr/local/python3.10.17/lib/python3.10/site-packages/torch/lib/libtorch_cpu.so)
[1;36m(VllmWorkerProcess pid=53843)[0;0m ERROR 12-17 09:32:03 [multiproc_worker_utils.py:239] frame #9: c10d::PrefixStore::get(std::string const&) + 0x3c (0xfffbdb99a99c in /usr/local/python3.10.17/lib/python3.10/site-packages/torch/lib/libtorch_cpu.so)
[1;36m(VllmWorkerProcess pid=53843)[0;0m ERROR 12-17 09:32:03 [multiproc_worker_utils.py:239] frame #10: c10d_npu::ProcessGroupHCCL::broadcastMasterID(HcclRootInfoDef*, bool, std::string const&, int) + 0x220 (0xfffbcabc6650 in /usr/local/python3.10.17/lib/python3.10/site-packages/torch_npu/lib/libtorch_npu.so)
[1;36m(VllmWorkerProcess pid=53843)[0;0m ERROR 12-17 09:32:03 [multiproc_worker_utils.py:239] frame #11: c10d_npu::ProcessGroupHCCL::createHCCLComm(std::string const&, std::vector<c10::Device, std::allocator<c10::Device> > const&, c10d_npu::HcclCommType, HcclCommConfigDef*, std::vector<std::shared_ptr<c10d_npu::HCCLComm>, std::allocator<std::shared_ptr<c10d_npu::HCCLComm> > >&, std::vector<c10_npu::NPUStream, std::allocator<c10_npu::NPUStream> >&, int) + 0xa8 (0xfffbcabd68ec in /usr/local/python3.10.17/lib/python3.10/site-packages/torch_npu/lib/libtorch_npu.so)
[1;36m(VllmWorkerProcess pid=53843)[0;0m ERROR 12-17 09:32:03 [multiproc_worker_utils.py:239] frame #12: c10d_npu::ProcessGroupHCCL::createHCCLComm(std::string const&, std::vector<c10::Device, std::allocator<c10::Device> > const&, c10d_npu::HcclCommType, HcclCommConfigDef*, int) + 0x534 (0xfffbcabdc724 in /usr/local/python3.10.17/lib/python3.10/site-packages/torch_npu/lib/libtorch_npu.so)
[1;36m(VllmWorkerProcess pid=53843)[0;0m ERROR 12-17 09:32:03 [multiproc_worker_utils.py:239] frame #13: <unknown function> + 0x17dea04 (0xfffbcabdea04 in /usr/local/python3.10.17/lib/python3.10/site-packages/torch_npu/lib/libtorch_npu.so)
[1;36m(VllmWorkerProcess pid=53843)[0;0m ERROR 12-17 09:32:03 [multiproc_worker_utils.py:239] frame #14: c10d_npu::ProcessGroupHCCL::allreduce(std::vector<at::Tensor, std::allocator<at::Tensor> >&, c10d::AllreduceOptions const&) + 0x16c (0xfffbcabe029c in /usr/local/python3.10.17/lib/python3.10/site-packages/torch_npu/lib/libtorch_npu.so)
[1;36m(VllmWorkerProcess pid=53843)[0;0m ERROR 12-17 09:32:03 [multiproc_worker_utils.py:239] frame #15: <unknown function> + 0x4e0cafc (0xfffbdb98cafc in /usr/local/python3.10.17/lib/python3.10/site-packages/torch/lib/libtorch_cpu.so)
[1;36m(VllmWorkerProcess pid=53843)[0;0m ERROR 12-17 09:32:03 [multiproc_worker_utils.py:239] frame #16: <unknown function> + 0x4e08884 (0xfffbdb988884 in /usr/local/python3.10.17/lib/python3.10/site-packages/torch/lib/libtorch_cpu.so)
[1;36m(VllmWorkerProcess pid=53843)[0;0m ERROR 12-17 09:32:03 [multiproc_worker_utils.py:239] frame #17: <unknown function> + 0x4e2c930 (0xfffbdb9ac930 in /usr/local/python3.10.17/lib/python3.10/site-packages/torch/lib/libtorch_cpu.so)
[1;36m(VllmWorkerProcess pid=53843)[0;0m ERROR 12-17 09:32:03 [multiproc_worker_utils.py:239] frame #18: <unknown function> + 0x1094778 (0xfffbe07f4778 in /usr/local/python3.10.17/lib/python3.10/site-packages/torch/lib/libtorch_python.so)
[1;36m(VllmWorkerProcess pid=53843)[0;0m ERROR 12-17 09:32:03 [multiproc_worker_utils.py:239] frame #19: <unknown function> + 0x6129d4 (0xfffbdfd729d4 in /usr/local/python3.10.17/lib/python3.10/site-packages/torch/lib/libtorch_python.so)
[1;36m(VllmWorkerProcess pid=53843)[0;0m ERROR 12-17 09:32:03 [multiproc_worker_utils.py:239] <omitting python frames>
[1;36m(VllmWorkerProcess pid=53843)[0;0m ERROR 12-17 09:32:03 [multiproc_worker_utils.py:239] . This may indicate a possible application crash on rank 0 or a network set up issue.
[1;36m(VllmWorkerProcess pid=53843)[0;0m ERROR 12-17 09:32:03 [multiproc_worker_utils.py:239] [ERROR] 2025-12-17-09:32:02 (PID:53843, Device:1, RankID:-1) ERR02005 DIST internal error
```

**Comment by LoganJane** [comment]
@zhima771 This issue has been resolved in the latest version. Please use the latest release or rc version (https://github.com/vllm-project/vllm-ascend/releases). If the issue persists, feel free to submit a new issue.
