### ISSUE TITLE
[Bug]: OOM problem occurs when deploy Qwen3-8B on v0.11.0rc3 

### ISSUE THREAD

**Issue by yangqinj** [vllm-project/vllm-ascend#5139]
### Your current environment

<details>
<summary>The output of `python collect_env.py`</summary>

```text
Collecting environment information...
PyTorch version: 2.7.1+cpu
Is debug build: False

OS: Ubuntu 22.04.5 LTS (aarch64)
GCC version: (Ubuntu 11.4.0-1ubuntu1~22.04.2) 11.4.0
Clang version: Could not collect
CMake version: version 4.2.0
Libc version: glibc-2.35

Python version: 3.11.13 (main, Nov 20 2025, 16:02:27) [GCC 11.4.0] (64-bit runtime)
Python platform: Linux-5.10.0-136.12.0.86.r1526_92.hce2.aarch64-aarch64-with-glibc2.35

CPU:
Architecture:                       aarch64
CPU op-mode(s):                     64-bit
Byte Order:                         Little Endian
CPU(s):                             192
On-line CPU(s) list:                0-191
Vendor ID:                          HiSilicon
BIOS Vendor ID:                     HiSilicon
Model name:                         Kunpeng-920
BIOS Model name:                    HUAWEI Kunpeng 920 5250
Model:                              0
Thread(s) per core:                 1
Core(s) per socket:                 48
Socket(s):                          4
Stepping:                           0x1
BogoMIPS:                           200.00
Flags:                              fp asimd evtstrm aes pmull sha1 sha2 crc32 atomics fphp asimdhp cpuid asimdrdm jscvt fcma dcpop asimddp asimdfhm ssbs
L1d cache:                          12 MiB (192 instances)
L1i cache:                          12 MiB (192 instances)
L2 cache:                           96 MiB (192 instances)
L3 cache:                           192 MiB (8 instances)
NUMA node(s):                       8
NUMA node0 CPU(s):                  0-23
NUMA node1 CPU(s):                  24-47
NUMA node2 CPU(s):                  48-71
NUMA node3 CPU(s):                  72-95
NUMA node4 CPU(s):                  96-119
NUMA node5 CPU(s):                  120-143
NUMA node6 CPU(s):                  144-167
NUMA node7 CPU(s):                  168-191
Vulnerability Gather data sampling: Not affected
Vulnerability Itlb multihit:        Not affected
Vulnerability L1tf:                 Not affected
Vulnerability Mds:                  Not affected
Vulnerability Meltdown:             Not affected
Vulnerability Mmio stale data:      Not affected
Vulnerability Retbleed:             Not affected
Vulnerability Spec rstack overflow: Not affected
Vulnerability Spec store bypass:    Mitigation; Speculative Store Bypass disabled via prctl
Vulnerability Spectre v1:           Mitigation; __user pointer sanitization
Vulnerability Spectre v2:           Not affected
Vulnerability Srbds:                Not affected
Vulnerability Tsx async abort:      Not affected

Versions of relevant libraries:
[pip3] numpy==1.26.4
[pip3] pyzmq==27.1.0
[pip3] torch==2.7.1+cpu
[pip3] torch_npu==2.7.1
[pip3] torchvision==0.22.1
[pip3] transformers==4.57.1
[conda] Could not collect
vLLM Version: 0.11.0
vLLM Ascend Version: 0.11.0rc3

ENV Variables:
ATB_OPSRUNNER_KERNEL_CACHE_LOCAL_COUNT=1
ATB_STREAM_SYNC_EVERY_RUNNER_ENABLE=0
ATB_OPSRUNNER_SETUP_CACHE_ENABLE=1
ATB_WORKSPACE_MEM_ALLOC_GLOBAL=1
ATB_DEVICE_TILING_BUFFER_BLOCK_NUM=32
ATB_STREAM_SYNC_EVERY_KERNEL_ENABLE=0
ATB_OPSRUNNER_KERNEL_CACHE_GLOABL_COUNT=5
ATB_HOME_PATH=/usr/local/Ascend/nnal/atb/latest/atb/cxx_abi_1
ASCEND_TOOLKIT_HOME=/usr/local/Ascend/ascend-toolkit/latest
ATB_COMPARE_TILING_EVERY_KERNEL=0
ASCEND_OPP_PATH=/usr/local/Ascend/ascend-toolkit/latest/opp
LD_LIBRARY_PATH=/usr/local/Ascend/nnal/atb/latest/atb/cxx_abi_1/lib:/usr/local/Ascend/nnal/atb/latest/atb/cxx_abi_1/examples:/usr/local/Ascend/nnal/atb/latest/atb/cxx_abi_1/tests/atbopstest:/usr/local/Ascend/ascend-toolkit/latest/tools/aml/lib64:/usr/local/Ascend/ascend-toolkit/latest/tools/aml/lib64/plugin:/usr/local/Ascend/ascend-toolkit/latest/lib64:/usr/local/Ascend/ascend-toolkit/latest/lib64/plugin/opskernel:/usr/local/Ascend/ascend-toolkit/latest/lib64/plugin/nnengine:/usr/local/Ascend/ascend-toolkit/latest/opp/built-in/op_impl/ai_core/tbe/op_tiling/lib/linux/aarch64:/usr/local/Ascend/nnal/atb/latest/atb/cxx_abi_0/lib:/usr/local/Ascend/nnal/atb/latest/atb/cxx_abi_0/examples:/usr/local/Ascend/nnal/atb/latest/atb/cxx_abi_0/tests/atbopstest:/usr/local/Ascend/ascend-toolkit/latest/tools/aml/lib64:/usr/local/Ascend/ascend-toolkit/latest/tools/aml/lib64/plugin:/usr/local/Ascend/ascend-toolkit/latest/lib64:/usr/local/Ascend/ascend-toolkit/latest/lib64/plugin/opskernel:/usr/local/Ascend/ascend-toolkit/latest/lib64/plugin/nnengine:/usr/local/Ascend/ascend-toolkit/latest/opp/built-in/op_impl/ai_core/tbe/op_tiling:/usr/local/Ascend/driver/lib64/common/:/usr/local/Ascend/driver/lib64/driver/:
ASCEND_AICPU_PATH=/usr/local/Ascend/ascend-toolkit/latest
ATB_STREAM_SYNC_EVERY_OPERATION_ENABLE=0
ASCEND_HOME_PATH=/usr/local/Ascend/ascend-toolkit/latest
ATB_MATMUL_SHUFFLE_K_ENABLE=1
ATB_WORKSPACE_MEM_ALLOC_ALG_TYPE=1
ATB_HOST_TILING_BUFFER_BLOCK_NUM=128
ATB_SHARE_MEMORY_NAME_SUFFIX=
TORCH_DEVICE_BACKEND_AUTOLOAD=1
PYTORCH_NVML_BASED_CUDA_CHECK=1
TORCHINDUCTOR_COMPILE_THREADS=1


NPU:
+------------------------------------------------------------------------------------------------+
| npu-smi 25.2.0                   Version: 25.2.0                                               |
+---------------------------+---------------+----------------------------------------------------+
| NPU   Name                | Health        | Power(W)    Temp(C)           Hugepages-Usage(page)|
| Chip                      | Bus-Id        | AICore(%)   Memory-Usage(MB)  HBM-Usage(MB)        |
+===========================+===============+====================================================+
| 0     910B4               | OK            | 144.3       53                0    / 0             |
| 0                         | 0000:C1:00.0  | 51          0    / 0          30551/ 32768         |
+===========================+===============+====================================================+
| 1     910B4               | OK            | 148.2       56                0    / 0             |
| 0                         | 0000:01:00.0  | 52          0    / 0          30544/ 32768         |
+===========================+===============+====================================================+
| 2     910B4               | OK            | 135.4       53                0    / 0             |
| 0                         | 0000:C2:00.0  | 54          0    / 0          28583/ 32768         |
+===========================+===============+====================================================+
| 3     910B4               | OK            | 137.9       53                0    / 0             |
| 0                         | 0000:02:00.0  | 54          0    / 0          28581/ 32768         |
+===========================+===============+====================================================+
| 4     910B4               | OK            | 93.7        49                0    / 0             |
| 0                         | 0000:81:00.0  | 0           0    / 0          2858 / 32768         |
+===========================+===============+====================================================+
| 5     910B4               | OK            | 89.3        46                0    / 0             |
| 0                         | 0000:41:00.0  | 0           0    / 0          2857 / 32768         |
+===========================+===============+====================================================+
| 6     910B4               | OK            | 86.0        45                0    / 0             |
| 0                         | 0000:82:00.0  | 0           0    / 0          2857 / 32768         |
+===========================+===============+====================================================+
| 7     910B4               | OK            | 89.4        46                0    / 0             |
| 0                         | 0000:42:00.0  | 0           0    / 0          2857 / 32768         |
+===========================+===============+====================================================+
+---------------------------+---------------+----------------------------------------------------+
| NPU     Chip              | Process id    | Process name             | Process memory(MB)      |
+===========================+===============+====================================================+
| 0       0                 | 3505467       |                          | 27754                   |
+===========================+===============+====================================================+
| 1       0                 | 3505468       |                          | 27754                   |
+===========================+===============+====================================================+
| 2       0                 | 3459913       |                          | 25788                   |
+===========================+===============+====================================================+
| 3       0                 | 3459917       |                          | 25786                   |
+===========================+===============+====================================================+
| No running processes found in NPU 4                                                            |
+===========================+===============+====================================================+
| No running processes found in NPU 5                                                            |
+===========================+===============+====================================================+
| No running processes found in NPU 6                                                            |
+===========================+===============+====================================================+
| No running processes found in NPU 7                                                            |
+===========================+===============+====================================================+

CANN:
package_name=Ascend-cann-toolkit
version=8.3.RC2
innerversion=V100R001C23SPC002B210
compatible_version=[V100R001C15],[V100R001C18],[V100R001C19],[V100R001C20],[V100R001C21],[V100R001C23]
arch=aarch64
os=linux
path=/usr/local/Ascend/ascend-toolkit/8.3.RC2/aarch64-linux

```

</details>

### 🐛 Describe the bug

Deploy Qwen3-8B with v0.11.0rc3 and BF16 data type on 2*910B4-32GB devices. To support 128K context, YARN is open:
```json

"max_position_embeddings": 131072,
"rope_scaling": {
  "factor": 4.0,
  "original_max_position_embeddings": 32768,
  "type": "yarn"
}
``` 

Deploy command:

```bash
# set the NPU device number
export ASCEND_RT_VISIBLE_DEVICES=0,1

# Set the operator dispatch pipeline level to 1 and disable manual memory control in ACLGraph
export TASK_QUEUE_ENABLE=1

# [Optional] jemalloc
# jemalloc is for better performance, if `libjemalloc.so` is install on your machine, you can turn it on.
# if os is Ubuntu
# export LD_PRELOAD=/usr/lib/aarch64-linux-gnu/libjemalloc.so.2:$LD_PRELOAD
# if os is openEuler
# export LD_PRELOAD=/usr/lib64/libjemalloc.so.2:$LD_PRELOAD


# Enable the AIVector core to directly schedule ROCE communication
export HCCL_OP_EXPANSION_MODE="AIV"

# Enable dense model and general optimizations for better performance.
export VLLM_ASCEND_ENABLE_DENSE_OPTIMIZE=1

# Enable FlashComm_v1 optimization when tensor parallel is enabled.
export VLLM_ASCEND_ENABLE_FLASHCOMM1=1

vllm serve /model/Qwen3-8B\
  --served-model-name qwen3 \
  --trust-remote-code \
  --async-scheduling \
  --quantization ascend \
  --distributed-executor-backend mp \
  --tensor-parallel-size 2 \
  --max-model-len 131072 \
  --max-num-batched-tokens 65536 \
  --compilation-config '{"cudagraph_mode": "FULL_DECODE_ONLY"}' \
  --port 8080 \
  --block-size 128 \
  --gpu-memory-utilization 0.9
```

Service deploy successfully, but got OOM problem when making requests with 127K input tokens:
```bash
[1;36m(Worker_TP0 pid=5400)[0;0m ERROR 12-17 02:30:54 [multiproc_executor.py:671] WorkerProc hit an exception.
[1;36m(Worker_TP0 pid=5400)[0;0m ERROR 12-17 02:30:54 [multiproc_executor.py:671] Traceback (most recent call last):
[1;36m(Worker_TP0 pid=5400)[0;0m ERROR 12-17 02:30:54 [multiproc_executor.py:671]   File "/vllm-workspace/vllm/vllm/v1/executor/multiproc_executor.py", line 666, in worker_busy_loop
[1;36m(Worker_TP0 pid=5400)[0;0m ERROR 12-17 02:30:54 [multiproc_executor.py:671]     output = func(*args, **kwargs)
[1;36m(Worker_TP0 pid=5400)[0;0m ERROR 12-17 02:30:54 [multiproc_executor.py:671]              ^^^^^^^^^^^^^^^^^^^^^
[1;36m(Worker_TP0 pid=5400)[0;0m ERROR 12-17 02:30:54 [multiproc_executor.py:671]   File "/vllm-workspace/vllm-ascend/vllm_ascend/worker/worker_v1.py", line 276, in execute_model
[1;36m(Worker_TP0 pid=5400)[0;0m ERROR 12-17 02:30:54 [multiproc_executor.py:671]     output = self.model_runner.execute_model(scheduler_output,
[1;36m(Worker_TP0 pid=5400)[0;0m ERROR 12-17 02:30:54 [multiproc_executor.py:671]              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[1;36m(Worker_TP0 pid=5400)[0;0m ERROR 12-17 02:30:54 [multiproc_executor.py:671]   File "/usr/local/python3.11.13/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
[1;36m(Worker_TP0 pid=5400)[0;0m ERROR 12-17 02:30:54 [multiproc_executor.py:671]     return func(*args, **kwargs)
[1;36m(Worker_TP0 pid=5400)[0;0m ERROR 12-17 02:30:54 [multiproc_executor.py:671]            ^^^^^^^^^^^^^^^^^^^^^
[1;36m(Worker_TP0 pid=5400)[0;0m ERROR 12-17 02:30:54 [multiproc_executor.py:671]   File "/vllm-workspace/vllm-ascend/vllm_ascend/worker/model_runner_v1.py", line 1944, in execute_model
[1;36m(Worker_TP0 pid=5400)[0;0m ERROR 12-17 02:30:54 [multiproc_executor.py:671]     max_query_len) = (self._prepare_inputs(scheduler_output,
[1;36m(Worker_TP0 pid=5400)[0;0m ERROR 12-17 02:30:54 [multiproc_executor.py:671]                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[1;36m(Worker_TP0 pid=5400)[0;0m ERROR 12-17 02:30:54 [multiproc_executor.py:671]   File "/vllm-workspace/vllm-ascend/vllm_ascend/worker/model_runner_v1.py", line 1376, in _prepare_inputs
[1;36m(Worker_TP0 pid=5400)[0;0m ERROR 12-17 02:30:54 [multiproc_executor.py:671]     self.attn_mask = self._make_attention_mask(seq_lens=seq_lens_cpu,
[1;36m(Worker_TP0 pid=5400)[0;0m ERROR 12-17 02:30:54 [multiproc_executor.py:671]                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[1;36m(Worker_TP0 pid=5400)[0;0m ERROR 12-17 02:30:54 [multiproc_executor.py:671]   File "/vllm-workspace/vllm-ascend/vllm_ascend/worker/model_runner_v1.py", line 912, in _make_attention_mask
[1;36m(Worker_TP0 pid=5400)[0;0m ERROR 12-17 02:30:54 [multiproc_executor.py:671]     return self.attn_mask_builder.get_attn_mask(
[1;36m(Worker_TP0 pid=5400)[0;0m ERROR 12-17 02:30:54 [multiproc_executor.py:671]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[1;36m(Worker_TP0 pid=5400)[0;0m ERROR 12-17 02:30:54 [multiproc_executor.py:671]   File "/vllm-workspace/vllm-ascend/vllm_ascend/attention/attention_mask.py", line 72, in get_attn_mask
[1;36m(Worker_TP0 pid=5400)[0;0m ERROR 12-17 02:30:54 [multiproc_executor.py:671]     ).to(device, non_blocking=True)
[1;36m(Worker_TP0 pid=5400)[0;0m ERROR 12-17 02:30:54 [multiproc_executor.py:671]       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[1;36m(Worker_TP0 pid=5400)[0;0m ERROR 12-17 02:30:54 [multiproc_executor.py:671] RuntimeError: NPU out of memory. Tried to allocate 7.75 GiB (NPU 0; 29.49 GiB total capacity; 22.35 GiB already allocated; 22.35 GiB current active; 5.32 GiB free; 22.98 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.
[1;36m(Worker_TP0 pid=5400)[0;0m ERROR 12-17 02:30:54 [multiproc_executor.py:671] Traceback (most recent call last):
[1;36m(Worker_TP0 pid=5400)[0;0m ERROR 12-17 02:30:54 [multiproc_executor.py:671]   File "/vllm-workspace/vllm/vllm/v1/executor/multiproc_executor.py", line 666, in worker_busy_loop
[1;36m(Worker_TP0 pid=5400)[0;0m ERROR 12-17 02:30:54 [multiproc_executor.py:671]     output = func(*args, **kwargs)
[1;36m(Worker_TP0 pid=5400)[0;0m ERROR 12-17 02:30:54 [multiproc_executor.py:671]              ^^^^^^^^^^^^^^^^^^^^^
[1;36m(Worker_TP0 pid=5400)[0;0m ERROR 12-17 02:30:54 [multiproc_executor.py:671]   File "/vllm-workspace/vllm-ascend/vllm_ascend/worker/worker_v1.py", line 276, in execute_model
[1;36m(Worker_TP0 pid=5400)[0;0m ERROR 12-17 02:30:54 [multiproc_executor.py:671]     output = self.model_runner.execute_model(scheduler_output,
[1;36m(Worker_TP0 pid=5400)[0;0m ERROR 12-17 02:30:54 [multiproc_executor.py:671]              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[1;36m(Worker_TP0 pid=5400)[0;0m ERROR 12-17 02:30:54 [multiproc_executor.py:671]   File "/usr/local/python3.11.13/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
[1;36m(Worker_TP0 pid=5400)[0;0m ERROR 12-17 02:30:54 [multiproc_executor.py:671]     return func(*args, **kwargs)
[1;36m(Worker_TP0 pid=5400)[0;0m ERROR 12-17 02:30:54 [multiproc_executor.py:671]            ^^^^^^^^^^^^^^^^^^^^^
[1;36m(Worker_TP0 pid=5400)[0;0m ERROR 12-17 02:30:54 [multiproc_executor.py:671]   File "/vllm-workspace/vllm-ascend/vllm_ascend/worker/model_runner_v1.py", line 1944, in execute_model
[1;36m(Worker_TP0 pid=5400)[0;0m ERROR 12-17 02:30:54 [multiproc_executor.py:671]     max_query_len) = (self._prepare_inputs(scheduler_output,
[1;36m(Worker_TP0 pid=5400)[0;0m ERROR 12-17 02:30:54 [multiproc_executor.py:671]                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[1;36m(Worker_TP0 pid=5400)[0;0m ERROR 12-17 02:30:54 [multiproc_executor.py:671]   File "/vllm-workspace/vllm-ascend/vllm_ascend/worker/model_runner_v1.py", line 1376, in _prepare_inputs
[1;36m(Worker_TP0 pid=5400)[0;0m ERROR 12-17 02:30:54 [multiproc_executor.py:671]     self.attn_mask = self._make_attention_mask(seq_lens=seq_lens_cpu,
[1;36m(Worker_TP0 pid=5400)[0;0m ERROR 12-17 02:30:54 [multiproc_executor.py:671]                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[1;36m(Worker_TP0 pid=5400)[0;0m ERROR 12-17 02:30:54 [multiproc_executor.py:671]   File "/vllm-workspace/vllm-ascend/vllm_ascend/worker/model_runner_v1.py", line 912, in _make_attention_mask
[1;36m(Worker_TP0 pid=5400)[0;0m ERROR 12-17 02:30:54 [multiproc_executor.py:671]     return self.attn_mask_builder.get_attn_mask(
[1;36m(Worker_TP0 pid=5400)[0;0m ERROR 12-17 02:30:54 [multiproc_executor.py:671]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[1;36m(Worker_TP0 pid=5400)[0;0m ERROR 12-17 02:30:54 [multiproc_executor.py:671]   File "/vllm-workspace/vllm-ascend/vllm_ascend/attention/attention_mask.py", line 72, in get_attn_mask
[1;36m(Worker_TP0 pid=5400)[0;0m ERROR 12-17 02:30:54 [multiproc_executor.py:671]     ).to(device, non_blocking=True)
[1;36m(Worker_TP0 pid=5400)[0;0m ERROR 12-17 02:30:54 [multiproc_executor.py:671]       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[1;36m(Worker_TP0 pid=5400)[0;0m ERROR 12-17 02:30:54 [multiproc_executor.py:671] RuntimeError: NPU out of memory. Tried to allocate 7.75 GiB (NPU 0; 29.49 GiB total capacity; 22.35 GiB already allocated; 22.35 GiB current active; 5.32 GiB free; 22.98 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.
[1;36m(Worker_TP0 pid=5400)[0;0m ERROR 12-17 02:30:54 [multiproc_executor.py:671] 
```

I have tried the following methods, bug none of them works:
+ reduce `gpu_memory_utilization` to 0.75
+ set `cudagraph_capture_sizes` to [2,4,8]
+ add devices to 4 and deloy with TP4

**Comment by yangqinj** [comment]
"When layout is TND, queryT(2) must be equal to the last element of actualSequenceLengthQ(65536)" error raised when update vllm-ascend to v0.12.0rc1

```bash
[0;36m(APIServer pid=6665)[0;0m INFO:     7.193.130.185:38694 - "POST /v1/chat/completions HTTP/1.1" 200 OK
[0;36m(APIServer pid=6665)[0;0m INFO 12-17 11:22:05 [loggers.py:236] Engine 000: Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 6.2 tokens/s, Running: 1 reqs, Waiting: 2 reqs, GPU KV cache usage: 40.3%, Prefix cache hit rate: 0.0%
[0;36m(APIServer pid=6665)[0;0m INFO 12-17 11:22:15 [loggers.py:236] Engine 000: Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 0.0 tokens/s, Running: 2 reqs, Waiting: 1 reqs, GPU KV cache usage: 80.5%, Prefix cache hit rate: 0.0%
[6948] [2025-12-17 11:22:41:647] torch.distributed: [ERROR] [6992] Find exception when finishedNPUExecutionInternal, query:build/CMakeFiles/torch_npu.dir/compiler_depend.ts:59 NPU function error: acl::AclQueryEventRecordedStatus(event_, &currStatus), error code is 507011
[ERROR] 2025-12-17-11:22:41 (PID:6948, Device:1, RankID:-1) ERR00100 PTA call acl api failed
[Error]: Model execution failed. 
        Rectify the fault based on the error information in the ascend log.
EH9999: Inner Error!
        rtEventQueryStatus execute failed, reason=[the model stream execute failed][FUNC:FuncErrorReason][FILE:error_message_manage.cc][LINE:53]
EH9999[PID: 6948] 2025-12-17-11:22:41.633.261 (EH9999):  [Query][Status]query event recorded status failed, runtime result = 507011[FUNC:ReportCallError][FILE:log_inner.cpp][LINE:162]
        TraceBack (most recent call last):

Exception raised from query at build/CMakeFiles/torch_npu.dir/compiler_depend.ts:59 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::__cxx11::basic_string<char, std::char_traits<char>, std::
[rank1]:[E1217 11:22:41.417841148 compiler_depend.ts:1675] [Rank 1] HCCL watchdog thread terminated with exception: 
[ERROR] 2025-12-17-11:22:41 (PID:6948, Device:1, RankID:-1) ERR02005 DIST internal error
terminate called after throwing an instance of 'std::runtime_error'
  what():  [Rank 1] HCCL watchdog thread terminated with exception: 
[ERROR] 2025-12-17-11:22:41 (PID:6948, Device:1, RankID:-1) ERR02005 DIST internal error
[0;36m(Worker_TP0 pid=6947)[0;0m Exception in thread WorkerAsyncOutputCopy:
[0;36m(Worker_TP0 pid=6947)[0;0m Traceback (most recent call last):
[0;36m(Worker_TP0 pid=6947)[0;0m   File "/usr/local/python3.11.13/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
[0;36m(Worker_TP0 pid=6947)[0;0m     self.run()
[0;36m(Worker_TP0 pid=6947)[0;0m   File "/usr/local/python3.11.13/lib/python3.11/threading.py", line 982, in run
[0;36m(Worker_TP0 pid=6947)[0;0m     self._target(*self._args, **self._kwargs)
[0;36m(Worker_TP0 pid=6947)[0;0m   File "/vllm-workspace/vllm/vllm/v1/executor/multiproc_executor.py", line 803, in async_output_busy_loop
[0;36m(Worker_TP0 pid=6947)[0;0m     self.enqueue_output(output)
[0;36m(Worker_TP0 pid=6947)[0;0m   File "/vllm-workspace/vllm/vllm/v1/executor/multiproc_executor.py", line 780, in enqueue_output
[0;36m(Worker_TP0 pid=6947)[0;0m     output = output.get_output()
[0;36m(Worker_TP0 pid=6947)[0;0m              ^^^^^^^^^^^^^^^^^^^
[0;36m(Worker_TP0 pid=6947)[0;0m   File "/vllm-workspace/vllm/vllm/v1/worker/gpu_model_runner.py", line 223, in get_output
[0;36m(Worker_TP0 pid=6947)[0;0m     self.async_copy_ready_event.synchronize()
[0;36m(Worker_TP0 pid=6947)[0;0m RuntimeError: synchronizeEvent:build/CMakeFiles/torch_npu.dir/compiler_depend.ts:198 NPU function error: aclrtSynchronizeEvent(npu_event), error code is 507011
[0;36m(Worker_TP0 pid=6947)[0;0m [ERROR] 2025-12-17-11:22:41 (PID:6947, Device:0, RankID:-1) ERR00100 PTA call acl api failed
[0;36m(Worker_TP0 pid=6947)[0;0m [Error]: Model execution failed. 
[0;36m(Worker_TP0 pid=6947)[0;0m         Rectify the fault based on the error information in the ascend log.
[0;36m(Worker_TP0 pid=6947)[0;0m EH9999: Inner Error!
[0;36m(Worker_TP0 pid=6947)[0;0m         rtEventSynchronize execute failed, reason=[the model stream execute failed][FUNC:FuncErrorReason][FILE:error_message_manage.cc][LINE:53]
[0;36m(Worker_TP0 pid=6947)[0;0m EH9999[PID: 6947] 2025-12-17-11:22:41.651.687 (EH9999):  wait event to be complete failed, runtime result = 507011[FUNC:ReportCallError][FILE:log_inner.cpp][LINE:162]
[0;36m(Worker_TP0 pid=6947)[0;0m         TraceBack (most recent call last):
[0;36m(Worker_TP0 pid=6947)[0;0m 
[6947] [2025-12-17 11:22:42:193] torch.distributed: [ERROR] [6993] Find exception when finishedNPUExecutionInternal, query:build/CMakeFiles/torch_npu.dir/compiler_depend.ts:59 NPU function error: acl::AclQueryEventRecordedStatus(event_, &currStatus), error code is 507011
[ERROR] 2025-12-17-11:22:42 (PID:6947, Device:0, RankID:-1) ERR00100 PTA call acl api failed
[Error]: Model execution failed. 
        Rectify the fault based on the error information in the ascend log.
EH9999: Inner Error!
        rtEventQueryStatus execute failed, reason=[the model stream execute failed][FUNC:FuncErrorReason][FILE:error_message_manage.cc][LINE:53]
EH9999[PID: 6947] 2025-12-17-11:22:42.190.141 (EH9999):  [Query][Status]query event recorded status failed, runtime result = 507011[FUNC:ReportCallError][FILE:log_inner.cpp][LINE:162]
        TraceBack (most recent call last):

Exception raised from query at build/CMakeFiles/torch_npu.dir/compiler_depend.ts:59 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::__cxx11::basic_string<char, std::char_traits<char>, std::
[rank0]:[E1217 11:22:42.963771662 compiler_depend.ts:1675] [Rank 0] HCCL watchdog thread terminated with exception: 
[ERROR] 2025-12-17-11:22:42 (PID:6947, Device:0, RankID:-1) ERR02005 DIST internal error
terminate called after throwing an instance of 'std::runtime_error'
  what():  [Rank 0] HCCL watchdog thread terminated with exception: 
[ERROR] 2025-12-17-11:22:42 (PID:6947, Device:0, RankID:-1) ERR02005 DIST internal error
[0;36m(Worker_TP0 pid=6947)[0;0m ERROR 12-17 11:22:42 [multiproc_executor.py:822] WorkerProc hit an exception.
[0;36m(Worker_TP0 pid=6947)[0;0m ERROR 12-17 11:22:42 [multiproc_executor.py:822] Traceback (most recent call last):
[0;36m(Worker_TP0 pid=6947)[0;0m ERROR 12-17 11:22:42 [multiproc_executor.py:822]   File "/vllm-workspace/vllm/vllm/v1/executor/multiproc_executor.py", line 817, in worker_busy_loop
[0;36m(Worker_TP0 pid=6947)[0;0m ERROR 12-17 11:22:42 [multiproc_executor.py:822]     output = func(*args, **kwargs)
[0;36m(Worker_TP0 pid=6947)[0;0m ERROR 12-17 11:22:42 [multiproc_executor.py:822]              ^^^^^^^^^^^^^^^^^^^^^
[0;36m(Worker_TP0 pid=6947)[0;0m ERROR 12-17 11:22:42 [multiproc_executor.py:822]   File "/vllm-workspace/vllm/vllm/v1/worker/worker_base.py", line 369, in execute_model
[0;36m(Worker_TP0 pid=6947)[0;0m ERROR 12-17 11:22:42 [multiproc_executor.py:822]     return self.worker.execute_model(scheduler_output, *args, **kwargs)
[0;36m(Worker_TP0 pid=6947)[0;0m ERROR 12-17 11:22:42 [multiproc_executor.py:822]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[0;36m(Worker_TP0 pid=6947)[0;0m ERROR 12-17 11:22:42 [multiproc_executor.py:822]   File "/vllm-workspace/vllm-ascend/vllm_ascend/worker/worker_v1.py", line 295, in execute_model
[0;36m(Worker_TP0 pid=6947)[0;0m ERROR 12-17 11:22:42 [multiproc_executor.py:822]     output = self.model_runner.execute_model(scheduler_output,
[0;36m(Worker_TP0 pid=6947)[0;0m ERROR 12-17 11:22:42 [multiproc_executor.py:822]              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[0;36m(Worker_TP0 pid=6947)[0;0m ERROR 12-17 11:22:42 [multiproc_executor.py:822]   File "/usr/local/python3.11.13/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 120, in decorate_context
[0;36m(Worker_TP0 pid=6947)[0;0m ERROR 12-17 11:22:42 [multiproc_executor.py:822]     return func(*args, **kwargs)
[0;36m(Worker_TP0 pid=6947)[0;0m ERROR 12-17 11:22:42 [multiproc_executor.py:822]            ^^^^^^^^^^^^^^^^^^^^^
[0;36m(Worker_TP0 pid=6947)[0;0m ERROR 12-17 11:22:42 [multiproc_executor.py:822]   File "/vllm-workspace/vllm-ascend/vllm_ascend/worker/model_runner_v1.py", line 1529, in execute_model
[0;36m(Worker_TP0 pid=6947)[0;0m ERROR 12-17 11:22:42 [multiproc_executor.py:822]     hidden_states = self._generate_process_reqs_hidden_states(
[0;36m(Worker_TP0 pid=6947)[0;0m ERROR 12-17 11:22:42 [multiproc_executor.py:822]                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[0;36m(Worker_TP0 pid=6947)[0;0m ERROR 12-17 11:22:42 [multiproc_executor.py:822]   File "/vllm-workspace/vllm-ascend/vllm_ascend/worker/model_runner_v1.py", line 1178, in _generate_process_reqs_hidden_states
[0;36m(Worker_TP0 pid=6947)[0;0m ERROR 12-17 11:22:42 [multiproc_executor.py:822]     hidden_states = self.model(input_ids=input_ids,
[0;36m(Worker_TP0 pid=6947)[0;0m ERROR 12-17 11:22:42 [multiproc_executor.py:822]                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[0;36m(Worker_TP0 pid=6947)[0;0m ERROR 12-17 11:22:42 [multiproc_executor.py:822]   File "/vllm-workspace/vllm-ascend/vllm_ascend/compilation/acl_graph.py", line 191, in __call__
[0;36m(Worker_TP0 pid=6947)[0;0m ERROR 12-17 11:22:42 [multiproc_executor.py:822]     torch.npu.synchronize()
[0;36m(Worker_TP0 pid=6947)[0;0m ERROR 12-17 11:22:42 [multiproc_executor.py:822]   File "/usr/local/python3.11.13/lib/python3.11/site-packages/torch_npu/npu/utils.py", line 72, in synchronize
[0;36m(Worker_TP0 pid=6947)[0;0m ERROR 12-17 11:22:42 [multiproc_executor.py:822]     return torch_npu._C._npu_synchronize()
[0;36m(Worker_TP0 pid=6947)[0;0m ERROR 12-17 11:22:42 [multiproc_executor.py:822]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[0;36m(Worker_TP0 pid=6947)[0;0m ERROR 12-17 11:22:42 [multiproc_executor.py:822] RuntimeError: npuSynchronizeDevice:build/CMakeFiles/torch_npu.dir/compiler_depend.ts:525 NPU function error: AclrtSynchronizeDeviceWithTimeout, error code is 507011
[0;36m(Worker_TP0 pid=6947)[0;0m ERROR 12-17 11:22:42 [multiproc_executor.py:822] [ERROR] 2025-12-17-11:22:42 (PID:6947, Device:0, RankID:-1) ERR00100 PTA call acl api failed
[0;36m(Worker_TP0 pid=6947)[0;0m ERROR 12-17 11:22:42 [multiproc_executor.py:822] [Error]: Model execution failed. 
[0;36m(Worker_TP0 pid=6947)[0;0m ERROR 12-17 11:22:42 [multiproc_executor.py:822]         Rectify the fault based on the error information in the ascend log.
[0;36m(Worker_TP0 pid=6947)[0;0m ERROR 12-17 11:22:42 [multiproc_executor.py:822] E89999: Inner Error!
[0;36m(Worker_TP0 pid=6947)[0;0m ERROR 12-17 11:22:42 [multiproc_executor.py:822] E89999[PID: 6947] 2025-12-17-07:39:38.418.778 (E89999):  When layout is TND, queryT(2) must be equal to the last element of actualSequenceLengthQ(1024)[FUNC:CheckFAISeqlenDataInTND][FILE:fused_infer_attention_score_tiling.cpp][LINE:880]
[0;36m(Worker_TP0 pid=6947)[0;0m ERROR 12-17 11:22:42 [multiproc_executor.py:822]         TraceBack (most recent call last):
[0;36m(Worker_TP0 pid=6947)[0;0m ERROR 12-17 11:22:42 [multiproc_executor.py:822]        When layout is TND, queryT(2) must be equal to the last element of actualSequenceLengthQ(65536)[FUNC:CheckFAISeqlenDataInTND][FILE:fused_infer_attention_score_tiling.cpp][LINE:880]
[0;36m(Worker_TP0 pid=6947)[0;0m ERROR 12-17 11:22:42 [multiproc_executor.py:822]        The error from device(chipId:0, dieId:0), serial number is 2, there is an exception of fftsplus aicore error, core id is 1, error code = 0x800000, dump info: pc start: 0x12c36ff1a1c4, current: 0x12c36ff1ba34, vec error info: 0, mte error info: 0x6c0300007d, ifu error info: 0xd9115c304800, ccu error info: 0x42ef788e3300c003, cube error info: 0, biu error info: 0, aic error mask: 0x6500020bd00028c, para base: 0x12c125a10000.[FUNC:ProcessStarsCoreErrorInfo][FILE:device_error_core_proc.cc][LINE:333]
[0;36m(Worker_TP0 pid=6947)[0;0m ERROR 12-17 11:22:42 [multiproc_executor.py:822]        The extend info: errcode:(0x800000, 0, 0) errorStr: The DDR address of the MTE instruction is out of range. fixp_error0 info: 0x300007d, fixp_error1 info: 0x6c, fsmId:0, tslot:0, thread:0, ctxid:0, blk:10, sublk:0, subErrType:4.[FUNC:ProcessStarsCoreErrorInfo][FILE:device_error_core_proc.cc][LINE:353]
[0;36m(Worker_TP0 pid=6947)[0;0m ERROR 12-17 11:22:42 [multiproc_executor.py:822]        [AIC_INFO] after execute:args print end[FUNC:GetError][FILE:stream.cc][LINE:1191]
[0;36m(Worker_TP0 pid=6947)[0;0m ERROR 12-17 11:22:42 [multiproc_executor.py:822]        [AIC_INFO] after execute:mixCtx print end[FUNC:GetError][FILE:stream.cc][LINE:1191]
[0;36m(Worker_TP0 pid=6947)[0;0m ERROR 12-17 11:22:42 [multiproc_executor.py:822]        Aicore kernel execute failed, device_id=0, stream_id=106, report_stream_id=2, task_id=41, flip_num=0, fault kernel_name=FusedInferAttentionScore_3b093497fc536d61a77a7a3293a524da_5000000000010200203, fault kernel info ext=none, program id=337, hash=15249908973055425140.[FUNC:GetError][FILE:stream.cc][LINE:1191]
[0;36m(Worker_TP0 pid=6947)[0;0m ERROR 12-17 11:22:42 [multiproc_executor.py:822]        rtDeviceSynchronizeWithTimeout execute failed, reason=[the model stream execute failed][FUNC:FuncErrorReason][FILE:error_message_manage.cc][LINE:53]
[0;36m(Worker_TP0 pid=6947)[0;0m ERROR 12-17 11:22:42 [multiproc_executor.py:822]        wait for compute device to finish failed, runtime result = 507011.[FUNC:ReportCallError][FILE:log_inner.cpp][LINE:162]
[0;36m(Worker_TP0 pid=6947)[0;0m ERROR 12-17 11:22:42 [multiproc_executor.py:822] 
[0;36m(Worker_TP0 pid=6947)[0;0m ERROR 12-17 11:22:42 [multiproc_executor.py:822] Traceback (most recent call last):
[0;36m(Worker_TP0 pid=6947)[0;0m ERROR 12-17 11:22:42 [multiproc_executor.py:822]   File "/vllm-workspace/vllm/vllm/v1/executor/multiproc_executor.py", line 817, in worker_busy_loop
[0;36m(Worker_TP0 pid=6947)[0;0m ERROR 12-17 11:22:42 [multiproc_executor.py:822]     output = func(*args, **kwargs)
[0;36m(Worker_TP0 pid=6947)[0;0m ERROR 12-17 11:22:42 [multiproc_executor.py:822]              ^^^^^^^^^^^^^^^^^^^^^
[0;36m(Worker_TP0 pid=6947)[0;0m ERROR 12-17 11:22:42 [multiproc_executor.py:822]   File "/vllm-workspace/vllm/vllm/v1/worker/worker_base.py", line 369, in execute_model
[0;36m(Worker_TP0 pid=6947)[0;0m ERROR 12-17 11:22:42 [multiproc_executor.py:822]     return self.worker.execute_model(scheduler_output, *args, **kwargs)
[0;36m(Worker_TP0 pid=6947)[0;0m ERROR 12-17 11:22:42 [multiproc_executor.py:822]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[0;36m(Worker_TP0 pid=6947)[0;0m ERROR 12-17 11:22:42 [multiproc_executor.py:822]   File "/vllm-workspace/vllm-ascend/vllm_ascend/worker/worker_v1.py", line 295, in execute_model
[0;36m(Worker_TP0 pid=6947)[0;0m ERROR 12-17 11:22:42 [multiproc_executor.py:822]     output = self.model_runner.execute_model(scheduler_output,
[0;36m(Worker_TP0 pid=6947)[0;0m ERROR 12-17 11:22:42 [multiproc_executor.py:822]              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[0;36m(Worker_TP0 pid=6947)[0;0m ERROR 12-17 11:22:42 [multiproc_executor.py:822]   File "/usr/local/python3.11.13/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 120, in decorate_context
[0;36m(Worker_TP0 pid=6947)[0;0m ERROR 12-17 11:22:42 [multiproc_executor.py:822]     return func(*args, **kwargs)
[0;36m(Worker_TP0 pid=6947)[0;0m ERROR 12-17 11:22:42 [multiproc_executor.py:822]            ^^^^^^^^^^^^^^^^^^^^^
[0;36m(Worker_TP0 pid=6947)[0;0m ERROR 12-17 11:22:42 [multiproc_executor.py:822]   File "/vllm-workspace/vllm-ascend/vllm_ascend/worker/model_runner_v1.py", line 1529, in execute_model
[0;36m(Worker_TP0 pid=6947)[0;0m ERROR 12-17 11:22:42 [multiproc_executor.py:822]     hidden_states = self._generate_process_reqs_hidden_states(
[0;36m(Worker_TP0 pid=6947)[0;0m ERROR 12-17 11:22:42 [multiproc_executor.py:822]                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[0;36m(Worker_TP0 pid=6947)[0;0m ERROR 12-17 11:22:42 [multiproc_executor.py:822]   File "/vllm-workspace/vllm-ascend/vllm_ascend/worker/model_runner_v1.py", line 1178, in _generate_process_reqs_hidden_states
[0;36m(Worker_TP0 pid=6947)[0;0m ERROR 12-17 11:22:42 [multiproc_executor.py:822]     hidden_states = self.model(input_ids=input_ids,
[0;36m(Worker_TP0 pid=6947)[0;0m ERROR 12-17 11:22:42 [multiproc_executor.py:822]                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[0;36m(Worker_TP0 pid=6947)[0;0m ERROR 12-17 11:22:42 [multiproc_executor.py:822]   File "/vllm-workspace/vllm-ascend/vllm_ascend/compilation/acl_graph.py", line 191, in __call__
[0;36m(Worker_TP0 pid=6947)[0;0m ERROR 12-17 11:22:42 [multiproc_executor.py:822]     torch.npu.synchronize()
[0;36m(Worker_TP0 pid=6947)[0;0m ERROR 12-17 11:22:42 [multiproc_executor.py:822]   File "/usr/local/python3.11.13/lib/python3.11/site-packages/torch_npu/npu/utils.py", line 72, in synchronize
[0;36m(Worker_TP0 pid=6947)[0;0m ERROR 12-17 11:22:42 [multiproc_executor.py:822]     return torch_npu._C._npu_synchronize()
[0;36m(Worker_TP0 pid=6947)[0;0m ERROR 12-17 11:22:42 [multiproc_executor.py:822]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[0;36m(Worker_TP0 pid=6947)[0;0m ERROR 12-17 11:22:42 [multiproc_executor.py:822] RuntimeError: npuSynchronizeDevice:build/CMakeFiles/torch_npu.dir/compiler_depend.ts:525 NPU function error: AclrtSynchronizeDeviceWithTimeout, error code is 507011
[0;36m(Worker_TP0 pid=6947)[0;0m ERROR 12-17 11:22:42 [multiproc_executor.py:822] [ERROR] 2025-12-17-11:22:42 (PID:6947, Device:0, RankID:-1) ERR00100 PTA call acl api failed
[0;36m(Worker_TP0 pid=6947)[0;0m ERROR 12-17 11:22:42 [multiproc_executor.py:822] [Error]: Model execution failed. 
[0;36m(Worker_TP0 pid=6947)[0;0m ERROR 12-17 11:22:42 [multiproc_executor.py:822]         Rectify the fault based on the error information in the ascend log.
[0;36m(Worker_TP0 pid=6947)[0;0m ERROR 12-17 11:22:42 [multiproc_executor.py:822] E89999: Inner Error!
[0;36m(Worker_TP0 pid=6947)[0;0m ERROR 12-17 11:22:42 [multiproc_executor.py:822] E89999[PID: 6947] 2025-12-17-07:39:38.418.778 (E89999):  When layout is TND, queryT(2) must be equal to the last element of actualSequenceLengthQ(1024)[FUNC:CheckFAISeqlenDataInTND][FILE:fused_infer_attention_score_tiling.cpp][LINE:880]
[0;36m(Worker_TP0 pid=6947)[0;0m ERROR 12-17 11:22:42 [multiproc_executor.py:822]         TraceBack (most recent call last):
[0;36m(Worker_TP0 pid=6947)[0;0m ERROR 12-17 11:22:42 [multiproc_executor.py:822]        When layout is TND, queryT(2) must be equal to the last element of actualSequenceLengthQ(65536)[FUNC:CheckFAISeqlenDataInTND][FILE:fused_infer_attention_score_tiling.cpp][LINE:880]
[0;36m(Worker_TP0 pid=6947)[0;0m ERROR 12-17 11:22:42 [multiproc_executor.py:822]        The error from device(chipId:0, dieId:0), serial number is 2, there is an exception of fftsplus aicore error, core id is 1, error code = 0x800000, dump info: pc start: 0x12c36ff1a1c4, current: 0x12c36ff1ba34, vec error info: 0, mte error info: 0x6c0300007d, ifu error info: 0xd9115c304800, ccu error info: 0x42ef788e3300c003, cube error info: 0, biu error info: 0, aic error mask: 0x6500020bd00028c, para base: 0x12c125a10000.[FUNC:ProcessStarsCoreErrorInfo][FILE:device_error_core_proc.cc][LINE:333]
[0;36m(Worker_TP0 pid=6947)[0;0m ERROR 12-17 11:22:42 [multiproc_executor.py:822]        The extend info: errcode:(0x800000, 0, 0) errorStr: The DDR address of the MTE instruction is out of range. fixp_error0 info: 0x300007d, fixp_error1 info: 0x6c, fsmId:0, tslot:0, thread:0, ctxid:0, blk:10, sublk:0, subErrType:4.[FUNC:ProcessStarsCoreErrorInfo][FILE:device_error_core_proc.cc][LINE:353]
[0;36m(Worker_TP0 pid=6947)[0;0m ERROR 12-17 11:22:42 [multiproc_executor.py:822]        [AIC_INFO] after execute:args print end[FUNC:GetError][FILE:stream.cc][LINE:1191]
[0;36m(Worker_TP0 pid=6947)[0;0m ERROR 12-17 11:22:42 [multiproc_executor.py:822]        [AIC_INFO] after execute:mixCtx print end[FUNC:GetError][FILE:stream.cc][LINE:1191]
[0;36m(Worker_TP0 pid=6947)[0;0m ERROR 12-17 11:22:42 [multiproc_executor.py:822]        Aicore kernel execute failed, device_id=0, stream_id=106, report_stream_id=2, task_id=41, flip_num=0, fault kernel_name=FusedInferAttentionScore_3b093497fc536d61a77a7a3293a524da_5000000000010200203, fault kernel info ext=none, program id=337, hash=15249908973055425140.[FUNC:GetError][FILE:stream.cc][LINE:1191]
[0;36m(Worker_TP0 pid=6947)[0;0m ERROR 12-17 11:22:42 [multiproc_executor.py:822]        rtDeviceSynchronizeWithTimeout execute failed, reason=[the model stream execute failed][FUNC:FuncErrorReason][FILE:error_message_manage.cc][LINE:53]
[0;36m(Worker_TP0 pid=6947)[0;0m ERROR 12-17 11:22:42 [multiproc_executor.py:822]        wait for compute device to finish failed, runtime result = 507011.[FUNC:ReportCallError][FILE:log_inner.cpp][LINE:162]
[0;36m(Worker_TP0 pid=6947)[0;0m ERROR 12-17 11:22:42 [multiproc_executor.py:822] 
[0;36m(Worker_TP0 pid=6947)[0;0m ERROR 12-17 11:22:42 [multiproc_executor.py:822] 
[0;36m(APIServer pid=6665)[0;0m INFO 12-17 11:22:45 [loggers.py:236] Engine 000: Avg prompt throughput: 13004.1 tokens/s, Avg generation throughput: 0.1 tokens/s, Running: 1 reqs, Waiting: 3 reqs, GPU KV cache usage: 80.0%, Prefix cache hit rate: 0.0%
[0;36m(EngineCore_DP0 pid=6807)[0;0m ERROR 12-17 11:22:53 [multiproc_executor.py:233] Worker proc VllmWorker-0 died unexpectedly, shutting down executor.
[ERROR] TBE Subprocess[task_distribute] raise error[], main process disappeared!
[ERROR] TBE Subprocess[task_distribute] raise error[], main process disappeared!
[ERROR] TBE Subprocess[task_distribute] raise error[], main process disappeared!
[ERROR] TBE Subprocess[task_distribute] raise error[], main process disappeared!
[ERROR] TBE Subprocess[task_distribute] raise error[], main process disappeared!
[ERROR] TBE Subprocess[task_distribute] raise error[], main process disappeared!
[ERROR] TBE Subprocess[task_distribute] raise error[], main process disappeared!
[ERROR] TBE Subprocess[task_distribute] raise error[], main process disappeared!
[0;36m(APIServer pid=6665)[0;0m INFO 12-17 11:22:55 [loggers.py:236] Engine 000: Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 0.0 tokens/s, Running: 1 reqs, Waiting: 3 reqs, GPU KV cache usage: 80.0%, Prefix cache hit rate: 0.0%
[0;36m(EngineCore_DP0 pid=6807)[0;0m ERROR 12-17 11:22:55 [dump_input.py:72] Dumping input data for V1 LLM engine (v0.12.0) with config: model='/home/models/Qwen3-8B-128K', speculative_config=None, tokenizer='/home/models/Qwen3-8B-128K', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, tokenizer_revision=None, trust_remote_code=True, dtype=torch.bfloat16, max_seq_len=131072, download_dir=None, load_format=auto, tensor_parallel_size=2, pipeline_parallel_size=1, data_parallel_size=1, disable_custom_all_reduce=True, quantization=None, enforce_eager=False, kv_cache_dtype=auto, device_config=npu, structured_outputs_config=StructuredOutputsConfig(backend='auto', disable_fallback=False, disable_any_whitespace=False, disable_additional_properties=False, reasoning_parser='', reasoning_parser_plugin='', enable_in_reasoning=False), observability_config=ObservabilityConfig(show_hidden_metrics_for_version=None, otlp_traces_endpoint=None, collect_detailed_traces=None, kv_cache_metrics=False, kv_cache_metrics_sample=0.01), seed=0, served_model_name=Qwen3-8B, enable_prefix_caching=False, enable_chunked_prefill=True, pooler_config=None, compilation_config={'level': None, 'mode': <CompilationMode.VLLM_COMPILE: 3>, 'debug_dump_path': None, 'cache_dir': '', 'compile_cache_save_format': 'binary', 'backend': 'vllm_ascend.compilation.compiler_interface.AscendCompiler', 'custom_ops': ['all'], 'splitting_ops': [], 'compile_mm_encoder': False, 'compile_sizes': [], 'inductor_compile_config': {'enable_auto_functionalized_v2': False}, 'inductor_passes': {}, 'cudagraph_mode': <CUDAGraphMode.FULL_DECODE_ONLY: (2, 0)>, 'cudagraph_num_of_warmups': 1, 'cudagraph_capture_sizes': [2, 4, 8, 16, 24, 32, 40, 48, 56, 64, 72, 80, 88, 96, 104, 112, 120, 128, 136, 144, 152, 160, 168, 176, 184, 192, 200, 208, 216, 224, 232, 240, 248, 256, 272, 288, 304, 320, 336, 352, 368, 384, 400, 416, 432, 448, 464, 480, 496, 512], 'cudagraph_copy_inputs': False, 'cudagraph_specialize_lora': True, 'use_inductor_graph_partition': False, 'pass_config': {'fuse_norm_quant': False, 'fuse_act_quant': False, 'fuse_attn_quant': False, 'eliminate_noops': True, 'enable_sp': False, 'fuse_gemm_comms': False, 'fuse_allreduce_rms': False}, 'max_cudagraph_capture_size': 512, 'dynamic_shapes_config': {'type': <DynamicShapesType.BACKED: 'backed'>}, 'local_cache_dir': None}, 
[0;36m(EngineCore_DP0 pid=6807)[0;0m ERROR 12-17 11:22:55 [dump_input.py:79] Dumping scheduler output for model execution: SchedulerOutput(scheduled_new_reqs=[], scheduled_cached_reqs=CachedRequestData(req_ids=['chatcmpl-9a2e7a561ead1ef8'], resumed_req_ids=[], new_token_ids=[], all_token_ids={}, new_block_ids=[[[658]]], num_computed_tokens=[130048], num_output_tokens=[1]), num_scheduled_tokens={chatcmpl-9a2e7a561ead1ef8: 1}, total_num_scheduled_tokens=1, scheduled_spec_decode_tokens={}, scheduled_encoder_inputs={}, num_common_prefix_blocks=[0], finished_req_ids=[], free_encoder_mm_hashes=[], preempted_req_ids=['chatcmpl-9b0207e3fee52806'], pending_structured_output_tokens=false, kv_connector_metadata=null, ec_connector_metadata=null)
[0;36m(EngineCore_DP0 pid=6807)[0;0m ERROR 12-17 11:22:55 [dump_input.py:81] Dumping scheduler stats: SchedulerStats(num_running_reqs=1, num_waiting_reqs=3, step_counter=0, current_wave=0, kv_cache_usage=0.7995283018867925, prefix_cache_stats=PrefixCacheStats(reset=False, requests=0, queries=0, hits=0, preempted_requests=0, preempted_queries=0, preempted_hits=0), connector_prefix_cache_stats=None, kv_cache_eviction_events=[], spec_decoding_stats=None, kv_connector_stats=None, waiting_lora_adapters={}, running_lora_adapters={})
```

**Comment by wanlongze** [comment]
RuntimeError: NPU out of memory. Tried to allocate 7.75 GiB (NPU 0; 29.49 GiB total capacity; 22.35 GiB already allocated; 22.35 GiB current active; 5.32 GiB free; 22.98 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation. 看起来你需要进一步降低gpu_memory_utilization 大约再降低10%左右 因为3G缺失

**Comment by wangxiyuan** [comment]
@Angazenn please take a look at this issue. Thanks.

**Comment by Angazenn** [comment]
on v0.11.0rc3, since we still use `_npu_flash_attention`, the mask is transfered via h2d in runtime. This is why there might be huge hbm consumption in forward. on v0.11.0rc3, it is suggest to reduce `--max-num-batched-tokens` or `gpu-memory-utilization`. Or you can consider to use v0.13.0rc1, where we already unify attention with `npu_fused_infer_attention_score`. This attention op used a fixed mask of which shape is `[2048, 2048]` so that it will not introduce too much hbm consumption.

**Comment by yangqinj** [comment]
Update to v0.11.0rc3 and change device to 910B2, the problem solved. Thanks. Besides, `npu_fused_infer_attention_score` uses fixed shape `[2048, 2048]`, then how can it process sequence with length larger than 2048?
