### ISSUE TITLE
[Bug]: dp attention failed when use hccl backend in dist.all_reduce

### ISSUE THREAD

**Issue by gao12312** [vllm-project/vllm-ascend#541]
### Your current environment

<details>
<summary>The output of `python collect_env.py`</summary>

```text
Your output of above commands here
Collecting environment information...
PyTorch version: 2.5.1
Is debug build: False

OS: Ubuntu 22.04.5 LTS (aarch64)
GCC version: (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
Clang version: Could not collect
CMake version: Could not collect
Libc version: glibc-2.35

Python version: 3.10.15 (main, Nov 27 2024, 06:51:55) [GCC 11.4.0] (64-bit runtime)
Python platform: Linux-4.19.90-2107.6.0.0192.8.oe1.bclinux.aarch64-aarch64-with-glibc2.35

CPU:
Architecture:                    aarch64
CPU op-mode(s):                  64-bit
Byte Order:                      Little Endian
CPU(s):                          192
On-line CPU(s) list:             0-191
Vendor ID:                       HiSilicon
Model name:                      Kunpeng-920
Model:                           0
Thread(s) per core:              1
Core(s) per cluster:             48
Socket(s):                       -
Cluster(s):                      4
Stepping:                        0x1
BogoMIPS:                        200.00
Flags:                           fp asimd evtstrm aes pmull sha1 sha2 crc32 atomics fphp asimdhp cpuid asimdrdm jscvt fcma dcpop asimddp asimdfhm ssbs
L1d cache:                       12 MiB (192 instances)
L1i cache:                       12 MiB (192 instances)
L2 cache:                        96 MiB (192 instances)
L3 cache:                        192 MiB (8 instances)
NUMA node(s):                    8
NUMA node0 CPU(s):               0-23
NUMA node1 CPU(s):               24-47
NUMA node2 CPU(s):               48-71
NUMA node3 CPU(s):               72-95
NUMA node4 CPU(s):               96-119
NUMA node5 CPU(s):               120-143
NUMA node6 CPU(s):               144-167
NUMA node7 CPU(s):               168-191
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Mmio stale data:   Not affected
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl
Vulnerability Spectre v1:        Mitigation; __user pointer sanitization
Vulnerability Spectre v2:        Not affected
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected

Versions of relevant libraries:
[pip3] numpy==1.26.4
[pip3] pyzmq==26.3.0
[pip3] torch==2.5.1
[pip3] torch-npu==2.5.1.dev20250308
[pip3] transformers==4.49.0
[conda] Could not collect
vLLM Version: 0.7.3
vLLM Ascend Version: 0.7.3rc1

ENV Variables:
ATB_OPSRUNNER_KERNEL_CACHE_TILING_SIZE=10240
ATB_OPSRUNNER_KERNEL_CACHE_LOCAL_COUNT=1
ATB_STREAM_SYNC_EVERY_RUNNER_ENABLE=0
ATB_OPSRUNNER_SETUP_CACHE_ENABLE=1
ATB_WORKSPACE_MEM_ALLOC_GLOBAL=0
ATB_DEVICE_TILING_BUFFER_BLOCK_NUM=32
ATB_STREAM_SYNC_EVERY_KERNEL_ENABLE=0
ATB_OPSRUNNER_KERNEL_CACHE_GLOABL_COUNT=5
PYTORCH_NPU_ALLOC_CONF=max_split_size_mb:256
ATB_HOME_PATH=/usr/local/Ascend/nnal/atb/latest/atb/cxx_abi_0
ASCEND_TOOLKIT_HOME=/usr/local/Ascend/ascend-toolkit/latest
ATB_COMPARE_TILING_EVERY_KERNEL=0
ASCEND_OPP_PATH=/usr/local/Ascend/ascend-toolkit/latest/opp
LD_LIBRARY_PATH=/usr/local/python3.10/lib/python3.10/site-packages/cv2/../../lib64:/usr/local/Ascend/nnal/atb/latest/atb/cxx_abi_0/lib:/usr/local/Ascend/nnal/atb/latest/atb/cxx_abi_0/examples:/usr/local/Ascend/nnal/atb/latest/atb/cxx_abi_0/tests/atbopstest:/usr/local/Ascend/ascend-toolkit/latest/tools/aml/lib64:/usr/local/Ascend/ascend-toolkit/latest/tools/aml/lib64/plugin:/usr/local/Ascend/ascend-toolkit/latest/lib64:/usr/local/Ascend/ascend-toolkit/latest/lib64/plugin/opskernel:/usr/local/Ascend/ascend-toolkit/latest/lib64/plugin/nnengine:/usr/local/Ascend/ascend-toolkit/latest/opp/built-in/op_impl/ai_core/tbe/op_tiling/lib/linux/aarch64:/usr/local/Ascend/driver/lib64/common:/usr/local/Ascend/driver/lib64/driver:/usr/local/Ascend/driver/lib64/common:/usr/local/Ascend/driver/lib64/driver:
ASCEND_AICPU_PATH=/usr/local/Ascend/ascend-toolkit/latest
ATB_OPSRUNNER_KERNEL_CACHE_TYPE=3
ATB_RUNNER_POOL_SIZE=64
ATB_STREAM_SYNC_EVERY_OPERATION_ENABLE=0
ASCEND_HOME_PATH=/usr/local/Ascend/ascend-toolkit/latest
ATB_MATMUL_SHUFFLE_K_ENABLE=1
ATB_LAUNCH_KERNEL_WITH_TILING=1
ATB_WORKSPACE_MEM_ALLOC_ALG_TYPE=1
ATB_HOST_TILING_BUFFER_BLOCK_NUM=128
ATB_SHARE_MEMORY_NAME_SUFFIX=
TORCH_DEVICE_BACKEND_AUTOLOAD=1
TORCHINDUCTOR_COMPILE_THREADS=1


NPU:
+------------------------------------------------------------------------------------------------+
| npu-smi 23.0.3                   Version: 23.0.3                                               |
+---------------------------+---------------+----------------------------------------------------+
| NPU   Name                | Health        | Power(W)    Temp(C)           Hugepages-Usage(page)|
| Chip                      | Bus-Id        | AICore(%)   Memory-Usage(MB)  HBM-Usage(MB)        |
+===========================+===============+====================================================+
| 2     910B2               | OK            | 90.3        39                0    / 0             |
| 0                         | 0000:81:00.0  | 0           0    / 0          3334 / 65536         |
+===========================+===============+====================================================+
| 3     910B2               | OK            | 93.0        39                0    / 0             |
| 0                         | 0000:82:00.0  | 0           0    / 0          3331 / 65536         |
+===========================+===============+====================================================+
+---------------------------+---------------+----------------------------------------------------+
| NPU     Chip              | Process id    | Process name             | Process memory(MB)      |
+===========================+===============+====================================================+
| No running processes found in NPU 2                                                            |
+===========================+===============+====================================================+
| No running processes found in NPU 3                                                            |
+===========================+===============+====================================================+

CANN:
package_name=Ascend-cann-toolkit
version=8.0.0
innerversion=V100R001C20SPC001B251
compatible_version=[V100R001C15],[V100R001C17],[V100R001C18],[V100R001C19],[V100R001C20]
arch=aarch64
os=linux
path=/usr/local/Ascend/ascend-toolkit/8.0.0/aarch64-linux
```

</details>

### 🐛 Describe the bug

example:
```python
import os
from time import sleep

from vllm import LLM, SamplingParams
from vllm.utils import get_open_port


def main(model, dp_size, local_dp_rank, global_dp_rank, dp_master_ip,
         dp_master_port, GPUs_per_dp_rank):
    os.environ["VLLM_DP_RANK"] = str(global_dp_rank)
    os.environ["VLLM_DP_RANK_LOCAL"] = str(local_dp_rank)
    os.environ["VLLM_DP_SIZE"] = str(dp_size)
    os.environ["VLLM_DP_MASTER_IP"] = dp_master_ip
    os.environ["VLLM_DP_MASTER_PORT"] = str(dp_master_port)
    os.environ["ASCEND_RT_VISIBLE_DEVICES"] = str(2 + local_dp_rank)  # local_dp_rank=0→设备2，1→设备3

    #npu_devices = ["2", "3"]  # 根据 npu-smi 输出选择可用设备
    #os.environ["ASCEND_RT_VISIBLE_DEVICES"] = npu_devices[local_dp_rank]

    # CUDA_VISIBLE_DEVICES for each DP rank is set automatically inside the
    # engine processes.

    # Sample prompts.
    prompts = [
        "Hello, my name is",
        "The president of the United States is",
    ] * 2

    # with DP, each rank should process different prompts.
    # usually all the DP ranks process a full dataset,
    # and each rank processes a different part of the dataset.
    promts_per_rank = len(prompts) // dp_size
    #print(promts_per_rank)

    start = global_dp_rank * promts_per_rank
    print(start)

    end = start + promts_per_rank
    print(end)

    prompts = prompts[start:end]
    print(prompts)

    if len(prompts) == 0:
        # if any rank has no prompts to process,
        # we need to set a placeholder prompt
        prompts = ["Placeholder"]
    print(f"DP rank {global_dp_rank} needs to process {len(prompts)} prompts")

    # Create a sampling params object.
    # since we are doing data parallel, every rank can have different
    # sampling params. here we set different max_tokens for different
    # ranks for demonstration.
    sampling_params = SamplingParams(temperature=0.8,
                                     top_p=0.95,
                                     max_tokens=[16, 20][global_dp_rank % 2])

    # Create an LLM.
    llm = LLM(model=model,
              tensor_parallel_size=GPUs_per_dp_rank,
              enforce_eager=True,
              gpu_memory_utilization=0.95,
              max_model_len=4096,
              device=f"npu:{local_dp_rank}"
              )
    outputs = llm.generate(prompts, sampling_params)
    # Print the outputs.
    for i, output in enumerate(outputs):
        if i >= 5:
            # print only 5 outputs
            break
        prompt = output.prompt
        generated_text = output.outputs[0].text
        print(f"DP rank {global_dp_rank}, Prompt: {prompt!r}, "
              f"Generated text: {generated_text!r}")

    # Give engines time to pause their processing loops before exiting.
    sleep(1)


if __name__ == "__main__":
    import argparse
    parser = argparse.ArgumentParser(description="Data Parallel Inference")
    parser.add_argument("--model",
                        type=str,
                        default="/root/models/DeepSeek-R1-Distill-Qwen-7b",
                        help="Model name or path")
    parser.add_argument("--dp-size",
                        type=int,
                        default=2,
                        help="Data parallel size")
    parser.add_argument("--tp-size",
                        type=int,
                        default=1,
                        help="Tensor parallel size")
    parser.add_argument("--node-size",
                        type=int,
                        default=1,
                        help="Total number of nodes")
    parser.add_argument("--node-rank",
                        type=int,
                        default=0,
                        help="Rank of the current node")
    parser.add_argument("--master-addr",
                        type=str,
                        default="",
                        help="Master node IP address")
    parser.add_argument("--master-port",
                        type=int,
                        default=0,
                        help="Master node port")
    


    args = parser.parse_args()

    dp_size = args.dp_size
    tp_size = args.tp_size
    node_size = args.node_size
    node_rank = args.node_rank

    if node_size == 1:
        dp_master_ip = "127.0.0.1"
        dp_master_port = get_open_port()
    else:
        dp_master_ip = args.master_addr
        dp_master_port = args.master_port

    assert dp_size % node_size == 0, "dp_size should be divisible by node_size"
    dp_per_node = dp_size // node_size

    from multiprocessing import Process

    procs = []
    for local_dp_rank, global_dp_rank in enumerate(
            range(node_rank * dp_per_node, (node_rank + 1) * dp_per_node)):
        
        print("local_dp_rank is ",local_dp_rank)
        print("global_dp_rank is ",global_dp_rank)

        proc = Process(target=main,
                       args=(args.model, dp_size, local_dp_rank,
                             global_dp_rank, dp_master_ip, dp_master_port,
                             tp_size))
        proc.start()
        procs.append(proc)
    #print(procs)
    exit_code = 0
    for proc in procs:
        proc.join(timeout=300)
        if proc.exitcode is None:
            print(f"Killing process {proc.pid} that "
                  f"didn't stop within 5 minutes.")
            proc.kill()
            exit_code = 1
        elif proc.exitcode:
            exit_code = proc.exitcode

    exit(exit_code)

```

result：
```python
root@0034f19cd7c6:/workspace/vllm# python /workspace/vllm/examples/offline_inference/data_parallel.py
local_dp_rank is  0
global_dp_rank is  0
local_dp_rank is  1
global_dp_rank is  1
0
2
['Hello, my name is', 'The president of the United States is']
DP rank 0 needs to process 2 prompts
2
4
['Hello, my name is', 'The president of the United States is']
DP rank 1 needs to process 2 prompts
INFO 04-16 06:16:01 __init__.py:30] Available plugins for group vllm.platform_plugins:
INFO 04-16 06:16:01 __init__.py:32] name=ascend, value=vllm_ascend:register
INFO 04-16 06:16:01 __init__.py:34] all available plugins for group vllm.platform_plugins will be loaded.
INFO 04-16 06:16:01 __init__.py:36] set environment variable VLLM_PLUGINS to control which plugins to load.
INFO 04-16 06:16:01 __init__.py:44] plugin ascend loaded.
INFO 04-16 06:16:01 __init__.py:30] Available plugins for group vllm.platform_plugins:
INFO 04-16 06:16:01 __init__.py:32] name=ascend, value=vllm_ascend:register
INFO 04-16 06:16:01 __init__.py:34] all available plugins for group vllm.platform_plugins will be loaded.
INFO 04-16 06:16:01 __init__.py:36] set environment variable VLLM_PLUGINS to control which plugins to load.
INFO 04-16 06:16:01 __init__.py:44] plugin ascend loaded.
INFO 04-16 06:16:01 __init__.py:198] Platform plugin ascend is activated
INFO 04-16 06:16:01 __init__.py:198] Platform plugin ascend is activated
INFO 04-16 06:16:01 __init__.py:30] Available plugins for group vllm.general_plugins:
INFO 04-16 06:16:01 __init__.py:32] name=ascend_enhanced_model, value=vllm_ascend:register_model
INFO 04-16 06:16:01 __init__.py:34] all available plugins for group vllm.general_plugins will be loaded.
INFO 04-16 06:16:01 __init__.py:36] set environment variable VLLM_PLUGINS to control which plugins to load.
INFO 04-16 06:16:01 __init__.py:44] plugin ascend_enhanced_model loaded.
INFO 04-16 06:16:01 __init__.py:30] Available plugins for group vllm.general_plugins:
INFO 04-16 06:16:01 __init__.py:32] name=ascend_enhanced_model, value=vllm_ascend:register_model
INFO 04-16 06:16:01 __init__.py:34] all available plugins for group vllm.general_plugins will be loaded.
INFO 04-16 06:16:01 __init__.py:36] set environment variable VLLM_PLUGINS to control which plugins to load.
INFO 04-16 06:16:01 __init__.py:44] plugin ascend_enhanced_model loaded.
WARNING 04-16 06:16:01 _custom_ops.py:21] Failed to import from vllm._C with ModuleNotFoundError("No module named 'vllm._C'")
WARNING 04-16 06:16:01 _custom_ops.py:21] Failed to import from vllm._C with ModuleNotFoundError("No module named 'vllm._C'")
INFO 04-16 06:16:02 importing.py:16] Triton not installed or not compatible; certain GPU-related functions will not be available.
INFO 04-16 06:16:02 importing.py:16] Triton not installed or not compatible; certain GPU-related functions will not be available.
WARNING 04-16 06:16:03 registry.py:351] Model architecture Qwen2VLForConditionalGeneration is already registered, and will be overwritten by the new model class vllm_ascend.models.qwen2_vl:CustomQwen2VLForConditionalGeneration.
WARNING 04-16 06:16:03 registry.py:351] Model architecture Qwen2VLForConditionalGeneration is already registered, and will be overwritten by the new model class vllm_ascend.models.qwen2_vl:CustomQwen2VLForConditionalGeneration.
INFO 04-16 06:16:14 config.py:550] This model supports multiple tasks: {'generate', 'score', 'embed', 'reward', 'classify'}. Defaulting to 'generate'.
INFO 04-16 06:16:14 llm_engine.py:233] Initializing a V0 LLM engine (v0.7.3) with config: model='/root/models/DeepSeek-R1-Distill-Qwen-7b', speculative_config=None, tokenizer='/root/models/DeepSeek-R1-Distill-Qwen-7b', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, override_neuron_config=None, tokenizer_revision=None, trust_remote_code=False, dtype=torch.bfloat16, max_seq_len=4096, download_dir=None, load_format=auto, tensor_parallel_size=1, pipeline_parallel_size=1, disable_custom_all_reduce=False, quantization=None, enforce_eager=True, kv_cache_dtype=auto,  device_config=npu:0, decoding_config=DecodingConfig(guided_decoding_backend='xgrammar'), observability_config=ObservabilityConfig(otlp_traces_endpoint=None, collect_model_forward_time=False, collect_model_execute_time=False), seed=0, served_model_name=/root/models/DeepSeek-R1-Distill-Qwen-7b, num_scheduler_steps=1, multi_step_stream_outputs=True, enable_prefix_caching=False, chunked_prefill_enabled=False, use_async_output_proc=True, disable_mm_preprocessor_cache=False, mm_processor_kwargs=None, pooler_config=None, compilation_config={"splitting_ops":[],"compile_sizes":[],"cudagraph_capture_sizes":[],"max_capture_size":0}, use_cached_outputs=False, 
INFO 04-16 06:16:14 config.py:550] This model supports multiple tasks: {'generate', 'score', 'embed', 'reward', 'classify'}. Defaulting to 'generate'.
INFO 04-16 06:16:14 llm_engine.py:233] Initializing a V0 LLM engine (v0.7.3) with config: model='/root/models/DeepSeek-R1-Distill-Qwen-7b', speculative_config=None, tokenizer='/root/models/DeepSeek-R1-Distill-Qwen-7b', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, override_neuron_config=None, tokenizer_revision=None, trust_remote_code=False, dtype=torch.bfloat16, max_seq_len=4096, download_dir=None, load_format=auto, tensor_parallel_size=1, pipeline_parallel_size=1, disable_custom_all_reduce=False, quantization=None, enforce_eager=True, kv_cache_dtype=auto,  device_config=npu:1, decoding_config=DecodingConfig(guided_decoding_backend='xgrammar'), observability_config=ObservabilityConfig(otlp_traces_endpoint=None, collect_model_forward_time=False, collect_model_execute_time=False), seed=0, served_model_name=/root/models/DeepSeek-R1-Distill-Qwen-7b, num_scheduler_steps=1, multi_step_stream_outputs=True, enable_prefix_caching=False, chunked_prefill_enabled=False, use_async_output_proc=True, disable_mm_preprocessor_cache=False, mm_processor_kwargs=None, pooler_config=None, compilation_config={"splitting_ops":[],"compile_sizes":[],"cudagraph_capture_sizes":[],"max_capture_size":0}, use_cached_outputs=False, 
/usr/local/python3.10/lib/python3.10/site-packages/torch_npu/contrib/transfer_to_npu.py:292: ImportWarning: 
    *************************************************************************************************************
    The torch.Tensor.cuda and torch.nn.Module.cuda are replaced with torch.Tensor.npu and torch.nn.Module.npu now..
    The torch.cuda.DoubleTensor is replaced with torch.npu.FloatTensor cause the double type is not supported now..
    The backend in torch.distributed.init_process_group set to hccl now..
    The torch.cuda.* and torch.cuda.amp.* are replaced with torch.npu.* and torch.npu.amp.* now..
    The device parameters have been replaced with npu in the function below:
    torch.logspace, torch.randint, torch.hann_window, torch.rand, torch.full_like, torch.ones_like, torch.rand_like, torch.randperm, torch.arange, torch.frombuffer, torch.normal, torch._empty_per_channel_affine_quantized, torch.empty_strided, torch.empty_like, torch.scalar_tensor, torch.tril_indices, torch.bartlett_window, torch.ones, torch.sparse_coo_tensor, torch.randn, torch.kaiser_window, torch.tensor, torch.triu_indices, torch.as_tensor, torch.zeros, torch.randint_like, torch.full, torch.eye, torch._sparse_csr_tensor_unsafe, torch.empty, torch._sparse_coo_tensor_unsafe, torch.blackman_window, torch.zeros_like, torch.range, torch.sparse_csr_tensor, torch.randn_like, torch.from_file, torch._cudnn_init_dropout_state, torch._empty_affine_quantized, torch.linspace, torch.hamming_window, torch.empty_quantized, torch._pin_memory, torch.autocast, torch.load, torch.Generator, torch.set_default_device, torch.Tensor.new_empty, torch.Tensor.new_empty_strided, torch.Tensor.new_full, torch.Tensor.new_ones, torch.Tensor.new_tensor, torch.Tensor.new_zeros, torch.Tensor.to, torch.Tensor.pin_memory, torch.nn.Module.to, torch.nn.Module.to_empty
    *************************************************************************************************************
    
  warnings.warn(msg, ImportWarning)
/usr/local/python3.10/lib/python3.10/site-packages/torch_npu/contrib/transfer_to_npu.py:247: RuntimeWarning: torch.jit.script and torch.jit.script_method will be disabled by transfer_to_npu, which currently does not support them, if you need to enable them, please do not use transfer_to_npu.
  warnings.warn(msg, RuntimeWarning)
WARNING 04-16 06:16:15 utils.py:2281] Methods add_lora,add_prompt_adapter,cache_config,compilation_config,current_platform,list_loras,list_prompt_adapters,load_config,pin_lora,pin_prompt_adapter,remove_lora,remove_prompt_adapter not implemented in <vllm_ascend.worker.worker.NPUWorker object at 0xfffd644a5e10>
/usr/local/python3.10/lib/python3.10/site-packages/torch_npu/contrib/transfer_to_npu.py:292: ImportWarning: 
    *************************************************************************************************************
    The torch.Tensor.cuda and torch.nn.Module.cuda are replaced with torch.Tensor.npu and torch.nn.Module.npu now..
    The torch.cuda.DoubleTensor is replaced with torch.npu.FloatTensor cause the double type is not supported now..
    The backend in torch.distributed.init_process_group set to hccl now..
    The torch.cuda.* and torch.cuda.amp.* are replaced with torch.npu.* and torch.npu.amp.* now..
    The device parameters have been replaced with npu in the function below:
    torch.logspace, torch.randint, torch.hann_window, torch.rand, torch.full_like, torch.ones_like, torch.rand_like, torch.randperm, torch.arange, torch.frombuffer, torch.normal, torch._empty_per_channel_affine_quantized, torch.empty_strided, torch.empty_like, torch.scalar_tensor, torch.tril_indices, torch.bartlett_window, torch.ones, torch.sparse_coo_tensor, torch.randn, torch.kaiser_window, torch.tensor, torch.triu_indices, torch.as_tensor, torch.zeros, torch.randint_like, torch.full, torch.eye, torch._sparse_csr_tensor_unsafe, torch.empty, torch._sparse_coo_tensor_unsafe, torch.blackman_window, torch.zeros_like, torch.range, torch.sparse_csr_tensor, torch.randn_like, torch.from_file, torch._cudnn_init_dropout_state, torch._empty_affine_quantized, torch.linspace, torch.hamming_window, torch.empty_quantized, torch._pin_memory, torch.autocast, torch.load, torch.Generator, torch.set_default_device, torch.Tensor.new_empty, torch.Tensor.new_empty_strided, torch.Tensor.new_full, torch.Tensor.new_ones, torch.Tensor.new_tensor, torch.Tensor.new_zeros, torch.Tensor.to, torch.Tensor.pin_memory, torch.nn.Module.to, torch.nn.Module.to_empty
    *************************************************************************************************************
    
  warnings.warn(msg, ImportWarning)
/usr/local/python3.10/lib/python3.10/site-packages/torch_npu/contrib/transfer_to_npu.py:247: RuntimeWarning: torch.jit.script and torch.jit.script_method will be disabled by transfer_to_npu, which currently does not support them, if you need to enable them, please do not use transfer_to_npu.
  warnings.warn(msg, RuntimeWarning)
WARNING 04-16 06:16:15 utils.py:2281] Methods add_lora,add_prompt_adapter,cache_config,compilation_config,current_platform,list_loras,list_prompt_adapters,load_config,pin_lora,pin_prompt_adapter,remove_lora,remove_prompt_adapter not implemented in <vllm_ascend.worker.worker.NPUWorker object at 0xfffd644a5f00>
INFO 04-16 06:16:21 parallel_state.py:834] Adjusting world_size=2 rank=0 distributed_init_method=tcp://127.0.0.1:41757 for DP
INFO 04-16 06:16:21 parallel_state.py:834] Adjusting world_size=2 rank=1 distributed_init_method=tcp://127.0.0.1:41757 for DP
INFO 04-16 06:16:31 parallel_state.py:849] backend=hccl
INFO 04-16 06:16:31 parallel_state.py:849] backend=hccl
[rank1]:[W416 06:16:41.948075703 ProcessGroupGloo.cpp:715] Warning: Unable to resolve hostname to a (local) address. Using the loopback address as fallback. Manually set the network interface to bind to with GLOO_SOCKET_IFNAME. (function operator())
[rank0]:[W416 06:16:41.952070243 ProcessGroupGloo.cpp:715] Warning: Unable to resolve hostname to a (local) address. Using the loopback address as fallback. Manually set the network interface to bind to with GLOO_SOCKET_IFNAME. (function operator())
INFO 04-16 06:17:11 parallel_state.py:970] rank 0 in world size 2 is assigned as DP rank 0, PP rank 0, TP rank 0
INFO 04-16 06:17:11 parallel_state.py:970] rank 1 in world size 2 is assigned as DP rank 1, PP rank 0, TP rank 0
Loading safetensors checkpoint shards:   0% Completed | 0/2 [00:00<?, ?it/s]
Loading safetensors checkpoint shards:  50% Completed | 1/2 [00:01<00:01,  1.56s/it]
Loading safetensors checkpoint shards: 100% Completed | 2/2 [00:02<00:00,  1.47s/it]
Loading safetensors checkpoint shards: 100% Completed | 2/2 [00:02<00:00,  1.48s/it]

INFO 04-16 06:17:30 executor_base.py:111] # npu blocks: 5862, # CPU blocks: 585
INFO 04-16 06:17:30 executor_base.py:116] Maximum concurrency for 4096 tokens per request: 183.19x
INFO 04-16 06:17:30 llm_engine.py:435] init engine (profile, create kv cache, warmup model) took 14.98 seconds
Processed prompts:   0%|                                                                            | 0/2 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]INFO 04-16 06:17:32 executor_base.py:111] # npu blocks: 5862, # CPU blocks: 585
INFO 04-16 06:17:32 executor_base.py:116] Maximum concurrency for 4096 tokens per request: 183.19x
INFO 04-16 06:17:32 llm_engine.py:435] init engine (profile, create kv cache, warmup model) took 17.27 seconds
Processed prompts: 100%|██████████████████████████████████████████████████████████████████| 2/2 [00:00<00:00,  2.92it/s, est. speed input: 20.44 toks/s, output: 46.72 toks/s]
DP rank 0, Prompt: 'Hello, my name is', Generated text: ' \n</think>\n\nHello! It seems like your name is incomplete. Could you'
DP rank 0, Prompt: 'The president of the United States is', Generated text: ' seeking to organize a committee of \\( n \\65555\\) peppers'
Process Process-2:
Traceback (most recent call last):
  File "/usr/local/python3.10/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/local/python3.10/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/workspace/vllm/examples/offline_inference/data_parallel.py", line 95, in main
    outputs = llm.generate(prompts, sampling_params)
  File "/workspace/vllm/vllm/utils.py", line 1076, in inner
    return fn(*args, **kwargs)
  File "/workspace/vllm/vllm/entrypoints/llm.py", line 469, in generate
    outputs = self._run_engine(use_tqdm=use_tqdm)
  File "/workspace/vllm/vllm/entrypoints/llm.py", line 1397, in _run_engine
    step_outputs = self.llm_engine.step()
  File "/workspace/vllm/vllm/engine/llm_engine.py", line 1390, in step
    outputs = self.model_executor.execute_model(
  File "/workspace/vllm/vllm/executor/executor_base.py", line 139, in execute_model
    output = self.collective_rpc("execute_model",
  File "/workspace/vllm/vllm/executor/uniproc_executor.py", line 56, in collective_rpc
    answer = run_method(self.driver_worker, method, args, kwargs)
  File "/workspace/vllm/vllm/utils.py", line 2215, in run_method
    return func(*args, **kwargs)
  File "/workspace/vllm/vllm/worker/worker_base.py", line 420, in execute_model
    output = self.model_runner.execute_model(
  File "/usr/local/python3.10/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/usr/local/python3.10/lib/python3.10/site-packages/vllm_ascend/worker/model_runner.py", line 1136, in execute_model
    with set_forward_context(model_input.attn_metadata,
  File "/usr/local/python3.10/lib/python3.10/contextlib.py", line 135, in __enter__
    return next(self.gen)
  File "/workspace/vllm/vllm/forward_context.py", line 92, in set_forward_context
    dist.all_reduce(num_tokens_tensor, group=get_dp_group().cpu_group)
  File "/usr/local/python3.10/lib/python3.10/site-packages/torch/distributed/c10d_logger.py", line 83, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/python3.10/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py", line 2506, in all_reduce
    work.wait()
RuntimeError: [/pytorch/third_party/gloo/gloo/transport/tcp/pair.cc:534] Connection closed by peer [127.0.0.1]:21428
Processed prompts:   0%|                                                                            | 0/2 [00:08<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]
```

**Comment by gao12312** [comment]
作为比较，torch_npu的distributed没有实现all_reduce方法 


 ```python
model class vllm_ascend.models.qwen2_vl:CustomQwen2VLForConditionalGeneration.
(VllmWorkerProcess pid=354371) /usr/local/python3.10/lib/python3.10/site-packages/torch_npu/contrib/transfer_to_npu.py:292: ImportWarning: 
(VllmWorkerProcess pid=354371)     *************************************************************************************************************
(VllmWorkerProcess pid=354371)     The torch.Tensor.cuda and torch.nn.Module.cuda are replaced with torch.Tensor.npu and torch.nn.Module.npu now..
(VllmWorkerProcess pid=354371)     The torch.cuda.DoubleTensor is replaced with torch.npu.FloatTensor cause the double type is not supported now..
(VllmWorkerProcess pid=354371)     The backend in torch.distributed.init_process_group set to hccl now..
(VllmWorkerProcess pid=354371)     The torch.cuda.* and torch.cuda.amp.* are replaced with torch.npu.* and torch.npu.amp.* now..
(VllmWorkerProcess pid=354371)     The device parameters have been replaced with npu in the function below:
(VllmWorkerProcess pid=354371)     torch.logspace, torch.randint, torch.hann_window, torch.rand, torch.full_like, torch.ones_like, torch.rand_like, torch.randperm, torch.arange, torch.frombuffer, torch.normal, torch._empty_per_channel_affine_quantized, torch.empty_strided, torch.empty_like, torch.scalar_tensor, torch.tril_indices, torch.bartlett_window, torch.ones, torch.sparse_coo_tensor, torch.randn, torch.kaiser_window, torch.tensor, torch.triu_indices, torch.as_tensor, torch.zeros, torch.randint_like, torch.full, torch.eye, torch._sparse_csr_tensor_unsafe, torch.empty, torch._sparse_coo_tensor_unsafe, torch.blackman_window, torch.zeros_like, torch.range, torch.sparse_csr_tensor, torch.randn_like, torch.from_file, torch._cudnn_init_dropout_state, torch._empty_affine_quantized, torch.linspace, torch.hamming_window, torch.empty_quantized, torch._pin_memory, torch.autocast, torch.load, torch.Generator, torch.set_default_device, torch.Tensor.new_empty, torch.Tensor.new_empty_strided, torch.Tensor.new_full, torch.Tensor.new_ones, torch.Tensor.new_tensor, torch.Tensor.new_zeros, torch.Tensor.to, torch.Tensor.pin_memory, torch.nn.Module.to, torch.nn.Module.to_empty
(VllmWorkerProcess pid=354371)     *************************************************************************************************************
(VllmWorkerProcess pid=354371)     
(VllmWorkerProcess pid=354371)   warnings.warn(msg, ImportWarning)
(VllmWorkerProcess pid=354371) /usr/local/python3.10/lib/python3.10/site-packages/torch_npu/contrib/transfer_to_npu.py:247: RuntimeWarning: torch.jit.script and torch.jit.script_method will be disabled by transfer_to_npu, which currently does not support them, if you need to enable them, please do not use transfer_to_npu.
(VllmWorkerProcess pid=354371)   warnings.warn(msg, RuntimeWarning)
(VllmWorkerProcess pid=354371) WARNING 04-11 08:11:17 utils.py:2262] Methods add_lora,add_prompt_adapter,cache_config,compilation_config,current_platform,list_loras,list_prompt_adapters,load_config,pin_lora,pin_prompt_adapter,remove_lora,remove_prompt_adapter not implemented in <vllm_ascend.worker.worker.NPUWorker object at 0xffff568de920>
[rank1]:[W411 08:11:52.740118003 ProcessGroupGloo.cpp:715] Warning: Unable to resolve hostname to a (local) address. Using the loopback address as fallback. Manually set the network interface to bind to with GLOO_SOCKET_IFNAME. (function operator())
[rank0]:[W411 08:11:52.780121655 ProcessGroupGloo.cpp:715] Warning: Unable to resolve hostname to a (local) address. Using the loopback address as fallback. Manually set the network interface to bind to with GLOO_SOCKET_IFNAME. (function operator())
INFO 04-11 08:12:02 shm_broadcast.py:258] vLLM message queue communication handle: Handle(connect_ip='127.0.0.1', local_reader_ranks=[1], buffer_handle=(1, 4194304, 6, 'psm_45b4e78f'), local_subscribe_port=39369, remote_subscribe_port=None)
Loading safetensors checkpoint shards:   0% Completed | 0/2 [00:00<?, ?it/s]
Loading safetensors checkpoint shards:  50% Completed | 1/2 [00:01<00:01,  1.30s/it]
Loading safetensors checkpoint shards: 100% Completed | 2/2 [00:02<00:00,  1.23s/it]
Loading safetensors checkpoint shards: 100% Completed | 2/2 [00:02<00:00,  1.24s/it]

/usr/local/python3.10/lib/python3.10/site-packages/torch_npu/distributed/distributed_c10d.py:112: UserWarning: HCCL doesn't support gather at the moment. Implemented with allgather instead.
  warnings.warn("HCCL doesn't support gather at the moment. Implemented with allgather instead.")
INFO 04-11 08:12:36 executor_base.py:111] # npu blocks: 12908, # CPU blocks: 1170
INFO 04-11 08:12:36 executor_base.py:116] Maximum concurrency for 4096 tokens per request: 403.38x
INFO 04-11 08:12:38 llm_engine.py:436] init engine (profile, create kv cache, warmup model) took 22.61 seconds
INFO 04-11 08:12:38 api_server.py:958] Starting vLLM API server on http://0.0.0.0:8000
 ```

**Comment by gao12312** [comment]
经过调试，demo可以运行，但multiprocess_mode推理只在V1版本支持
```python
root@0034f19cd7c6:/workspace/vllm# python examples/offline_inference/data_parallel.py
local_dp_rank is  0
global_dp_rank is  0
local_dp_rank is  1
global_dp_rank is  1
0
8
['Hello, my name is', 'The president of the United States is', 'The capital of France is', 'The future of AI is', 'Hello, my name is', 'The president of the United States is', 'The capital of France is', 'The future of AI is']
DP rank 0 needs to process 8 prompts
8
16
['Hello, my name is', 'The president of the United States is', 'The capital of France is', 'The future of AI is', 'Hello, my name is', 'The president of the United States is', 'The capital of France is', 'The future of AI is']
DP rank 1 needs to process 8 prompts
INFO 04-18 06:03:31 __init__.py:30] Available plugins for group vllm.platform_plugins:
INFO 04-18 06:03:31 __init__.py:32] name=ascend, value=vllm_ascend:register
INFO 04-18 06:03:31 __init__.py:34] all available plugins for group vllm.platform_plugins will be loaded.
INFO 04-18 06:03:31 __init__.py:36] set environment variable VLLM_PLUGINS to control which plugins to load.
INFO 04-18 06:03:31 __init__.py:44] plugin ascend loaded.
INFO 04-18 06:03:31 __init__.py:30] Available plugins for group vllm.platform_plugins:
INFO 04-18 06:03:31 __init__.py:32] name=ascend, value=vllm_ascend:register
INFO 04-18 06:03:31 __init__.py:34] all available plugins for group vllm.platform_plugins will be loaded.
INFO 04-18 06:03:31 __init__.py:36] set environment variable VLLM_PLUGINS to control which plugins to load.
INFO 04-18 06:03:31 __init__.py:44] plugin ascend loaded.
INFO 04-18 06:03:31 __init__.py:198] Platform plugin ascend is activated
INFO 04-18 06:03:31 __init__.py:198] Platform plugin ascend is activated
INFO 04-18 06:03:31 __init__.py:30] Available plugins for group vllm.general_plugins:
INFO 04-18 06:03:31 __init__.py:32] name=ascend_enhanced_model, value=vllm_ascend:register_model
INFO 04-18 06:03:31 __init__.py:34] all available plugins for group vllm.general_plugins will be loaded.
INFO 04-18 06:03:31 __init__.py:36] set environment variable VLLM_PLUGINS to control which plugins to load.
INFO 04-18 06:03:31 __init__.py:44] plugin ascend_enhanced_model loaded.
INFO 04-18 06:03:31 __init__.py:30] Available plugins for group vllm.general_plugins:
INFO 04-18 06:03:31 __init__.py:32] name=ascend_enhanced_model, value=vllm_ascend:register_model
INFO 04-18 06:03:31 __init__.py:34] all available plugins for group vllm.general_plugins will be loaded.
INFO 04-18 06:03:31 __init__.py:36] set environment variable VLLM_PLUGINS to control which plugins to load.
INFO 04-18 06:03:31 __init__.py:44] plugin ascend_enhanced_model loaded.
WARNING 04-18 06:03:31 _custom_ops.py:21] Failed to import from vllm._C with ModuleNotFoundError("No module named 'vllm._C'")
WARNING 04-18 06:03:31 _custom_ops.py:21] Failed to import from vllm._C with ModuleNotFoundError("No module named 'vllm._C'")
INFO 04-18 06:03:32 importing.py:16] Triton not installed or not compatible; certain GPU-related functions will not be available.
INFO 04-18 06:03:32 importing.py:16] Triton not installed or not compatible; certain GPU-related functions will not be available.
WARNING 04-18 06:03:33 registry.py:351] Model architecture Qwen2VLForConditionalGeneration is already registered, and will be overwritten by the new model class vllm_ascend.models.qwen2_vl:CustomQwen2VLForConditionalGeneration.
WARNING 04-18 06:03:33 registry.py:351] Model architecture Qwen2VLForConditionalGeneration is already registered, and will be overwritten by the new model class vllm_ascend.models.qwen2_vl:CustomQwen2VLForConditionalGeneration.
INFO 04-18 06:03:45 config.py:550] This model supports multiple tasks: {'score', 'classify', 'embed', 'reward', 'generate'}. Defaulting to 'generate'.
INFO 04-18 06:03:45 llm_engine.py:233] Initializing a V0 LLM engine (v0.7.3) with config: model='/root/models/DeepSeek-R1-Distill-Qwen-7b', speculative_config=None, tokenizer='/root/models/DeepSeek-R1-Distill-Qwen-7b', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, override_neuron_config=None, tokenizer_revision=None, trust_remote_code=False, dtype=torch.bfloat16, max_seq_len=4096, download_dir=None, load_format=auto, tensor_parallel_size=1, pipeline_parallel_size=1, disable_custom_all_reduce=False, quantization=None, enforce_eager=True, kv_cache_dtype=auto,  device_config=npu:0, decoding_config=DecodingConfig(guided_decoding_backend='xgrammar'), observability_config=ObservabilityConfig(otlp_traces_endpoint=None, collect_model_forward_time=False, collect_model_execute_time=False), seed=0, served_model_name=/root/models/DeepSeek-R1-Distill-Qwen-7b, num_scheduler_steps=1, multi_step_stream_outputs=True, enable_prefix_caching=False, chunked_prefill_enabled=False, use_async_output_proc=True, disable_mm_preprocessor_cache=False, mm_processor_kwargs=None, pooler_config=None, compilation_config={"splitting_ops":[],"compile_sizes":[],"cudagraph_capture_sizes":[],"max_capture_size":0}, use_cached_outputs=False, 
INFO 04-18 06:03:45 config.py:550] This model supports multiple tasks: {'score', 'classify', 'embed', 'reward', 'generate'}. Defaulting to 'generate'.
INFO 04-18 06:03:45 llm_engine.py:233] Initializing a V0 LLM engine (v0.7.3) with config: model='/root/models/DeepSeek-R1-Distill-Qwen-7b', speculative_config=None, tokenizer='/root/models/DeepSeek-R1-Distill-Qwen-7b', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, override_neuron_config=None, tokenizer_revision=None, trust_remote_code=False, dtype=torch.bfloat16, max_seq_len=4096, download_dir=None, load_format=auto, tensor_parallel_size=1, pipeline_parallel_size=1, disable_custom_all_reduce=False, quantization=None, enforce_eager=True, kv_cache_dtype=auto,  device_config=npu:1, decoding_config=DecodingConfig(guided_decoding_backend='xgrammar'), observability_config=ObservabilityConfig(otlp_traces_endpoint=None, collect_model_forward_time=False, collect_model_execute_time=False), seed=0, served_model_name=/root/models/DeepSeek-R1-Distill-Qwen-7b, num_scheduler_steps=1, multi_step_stream_outputs=True, enable_prefix_caching=False, chunked_prefill_enabled=False, use_async_output_proc=True, disable_mm_preprocessor_cache=False, mm_processor_kwargs=None, pooler_config=None, compilation_config={"splitting_ops":[],"compile_sizes":[],"cudagraph_capture_sizes":[],"max_capture_size":0}, use_cached_outputs=False, 
/usr/local/python3.10/lib/python3.10/site-packages/torch_npu/contrib/transfer_to_npu.py:292: ImportWarning: 
    *************************************************************************************************************
    The torch.Tensor.cuda and torch.nn.Module.cuda are replaced with torch.Tensor.npu and torch.nn.Module.npu now..
    The torch.cuda.DoubleTensor is replaced with torch.npu.FloatTensor cause the double type is not supported now..
    The backend in torch.distributed.init_process_group set to hccl now..
    The torch.cuda.* and torch.cuda.amp.* are replaced with torch.npu.* and torch.npu.amp.* now..
    The device parameters have been replaced with npu in the function below:
    torch.logspace, torch.randint, torch.hann_window, torch.rand, torch.full_like, torch.ones_like, torch.rand_like, torch.randperm, torch.arange, torch.frombuffer, torch.normal, torch._empty_per_channel_affine_quantized, torch.empty_strided, torch.empty_like, torch.scalar_tensor, torch.tril_indices, torch.bartlett_window, torch.ones, torch.sparse_coo_tensor, torch.randn, torch.kaiser_window, torch.tensor, torch.triu_indices, torch.as_tensor, torch.zeros, torch.randint_like, torch.full, torch.eye, torch._sparse_csr_tensor_unsafe, torch.empty, torch._sparse_coo_tensor_unsafe, torch.blackman_window, torch.zeros_like, torch.range, torch.sparse_csr_tensor, torch.randn_like, torch.from_file, torch._cudnn_init_dropout_state, torch._empty_affine_quantized, torch.linspace, torch.hamming_window, torch.empty_quantized, torch._pin_memory, torch.autocast, torch.load, torch.Generator, torch.set_default_device, torch.Tensor.new_empty, torch.Tensor.new_empty_strided, torch.Tensor.new_full, torch.Tensor.new_ones, torch.Tensor.new_tensor, torch.Tensor.new_zeros, torch.Tensor.to, torch.Tensor.pin_memory, torch.nn.Module.to, torch.nn.Module.to_empty
    *************************************************************************************************************
    
  warnings.warn(msg, ImportWarning)
/usr/local/python3.10/lib/python3.10/site-packages/torch_npu/contrib/transfer_to_npu.py:247: RuntimeWarning: torch.jit.script and torch.jit.script_method will be disabled by transfer_to_npu, which currently does not support them, if you need to enable them, please do not use transfer_to_npu.
  warnings.warn(msg, RuntimeWarning)
WARNING 04-18 06:03:45 utils.py:2281] Methods add_lora,add_prompt_adapter,cache_config,compilation_config,current_platform,list_loras,list_prompt_adapters,load_config,pin_lora,pin_prompt_adapter,remove_lora,remove_prompt_adapter not implemented in <vllm_ascend.worker.worker.NPUWorker object at 0xfffd43f9e6e0>
/usr/local/python3.10/lib/python3.10/site-packages/torch_npu/contrib/transfer_to_npu.py:292: ImportWarning: 
    *************************************************************************************************************
    The torch.Tensor.cuda and torch.nn.Module.cuda are replaced with torch.Tensor.npu and torch.nn.Module.npu now..
    The torch.cuda.DoubleTensor is replaced with torch.npu.FloatTensor cause the double type is not supported now..
    The backend in torch.distributed.init_process_group set to hccl now..
    The torch.cuda.* and torch.cuda.amp.* are replaced with torch.npu.* and torch.npu.amp.* now..
    The device parameters have been replaced with npu in the function below:
    torch.logspace, torch.randint, torch.hann_window, torch.rand, torch.full_like, torch.ones_like, torch.rand_like, torch.randperm, torch.arange, torch.frombuffer, torch.normal, torch._empty_per_channel_affine_quantized, torch.empty_strided, torch.empty_like, torch.scalar_tensor, torch.tril_indices, torch.bartlett_window, torch.ones, torch.sparse_coo_tensor, torch.randn, torch.kaiser_window, torch.tensor, torch.triu_indices, torch.as_tensor, torch.zeros, torch.randint_like, torch.full, torch.eye, torch._sparse_csr_tensor_unsafe, torch.empty, torch._sparse_coo_tensor_unsafe, torch.blackman_window, torch.zeros_like, torch.range, torch.sparse_csr_tensor, torch.randn_like, torch.from_file, torch._cudnn_init_dropout_state, torch._empty_affine_quantized, torch.linspace, torch.hamming_window, torch.empty_quantized, torch._pin_memory, torch.autocast, torch.load, torch.Generator, torch.set_default_device, torch.Tensor.new_empty, torch.Tensor.new_empty_strided, torch.Tensor.new_full, torch.Tensor.new_ones, torch.Tensor.new_tensor, torch.Tensor.new_zeros, torch.Tensor.to, torch.Tensor.pin_memory, torch.nn.Module.to, torch.nn.Module.to_empty
    *************************************************************************************************************
    
  warnings.warn(msg, ImportWarning)
/usr/local/python3.10/lib/python3.10/site-packages/torch_npu/contrib/transfer_to_npu.py:247: RuntimeWarning: torch.jit.script and torch.jit.script_method will be disabled by transfer_to_npu, which currently does not support them, if you need to enable them, please do not use transfer_to_npu.
  warnings.warn(msg, RuntimeWarning)
WARNING 04-18 06:03:46 utils.py:2281] Methods add_lora,add_prompt_adapter,cache_config,compilation_config,current_platform,list_loras,list_prompt_adapters,load_config,pin_lora,pin_prompt_adapter,remove_lora,remove_prompt_adapter not implemented in <vllm_ascend.worker.worker.NPUWorker object at 0xfffd43f9a7d0>

INFO 04-18 08:10:35 parallel_state.py:828] world_size=1 rank=0 local_rank=0 distributed_init_method=tcp://172.17.0.3:52955 backend=hccl
INFO 04-18 08:10:35 parallel_state.py:835] config.parallel_config.data_parallel_size is 2
INFO 04-18 08:10:35 parallel_state.py:838] init_distributed_environment start adjust.....
INFO 04-18 08:10:35 parallel_state.py:848] Adjusting world_size=2 rank=0 distributed_init_method=tcp://127.0.0.1:35259 for DP
INFO 04-18 08:10:36 parallel_state.py:828] world_size=1 rank=0 local_rank=1 distributed_init_method=tcp://172.17.0.3:43511 backend=hccl
INFO 04-18 08:10:36 parallel_state.py:835] config.parallel_config.data_parallel_size is 2
INFO 04-18 08:10:36 parallel_state.py:838] init_distributed_environment start adjust.....
INFO 04-18 08:10:36 parallel_state.py:848] Adjusting world_size=2 rank=1 distributed_init_method=tcp://127.0.0.1:35259 for DP
INFO 04-18 08:10:46 parallel_state.py:863] backend=hccl
INFO 04-18 08:10:46 parallel_state.py:863] backend=hccl

[rank0]:[W418 06:04:11.444108079 ProcessGroupGloo.cpp:715] Warning: Unable to resolve hostname to a (local) address. Using the loopback address as fallback. Manually set the network interface to bind to with GLOO_SOCKET_IFNAME. (function operator())
[rank1]:[W418 06:04:11.444128869 ProcessGroupGloo.cpp:715] Warning: Unable to resolve hostname to a (local) address. Using the loopback address as fallback. Manually set the network interface to bind to with GLOO_SOCKET_IFNAME. (function operator())
INFO 04-18 06:04:11 parallel_state.py:200] test current_platform.device_name
INFO 04-18 06:04:11 parallel_state.py:200] test current_platform.device_name
INFO 04-18 06:04:22 parallel_state.py:200] test current_platform.device_name
INFO 04-18 06:04:22 parallel_state.py:200] test current_platform.device_name
INFO 04-18 06:04:32 parallel_state.py:200] test current_platform.device_name
INFO 04-18 06:04:32 parallel_state.py:200] test current_platform.device_name
INFO 04-18 06:04:42 parallel_state.py:200] test current_platform.device_name
INFO 04-18 06:04:42 parallel_state.py:200] test current_platform.device_name
INFO 04-18 06:04:42 parallel_state.py:213] device_comm_cls is: <class 'vllm_ascend.communicator.NPUCommunicator'>
INFO 04-18 06:04:42 parallel_state.py:213] device_comm_cls is: <class 'vllm_ascend.communicator.NPUCommunicator'>
INFO 04-18 06:04:42 parallel_state.py:981] rank 1 in world size 2 is assigned as DP rank 1, PP rank 0, TP rank 0
INFO 04-18 06:04:42 parallel_state.py:981] rank 0 in world size 2 is assigned as DP rank 0, PP rank 0, TP rank 0
Loading safetensors checkpoint shards:   0% Completed | 0/2 [00:00<?, ?it/s]
Loading safetensors checkpoint shards:  50% Completed | 1/2 [00:01<00:01,  1.84s/it]
Loading safetensors checkpoint shards: 100% Completed | 2/2 [00:03<00:00,  1.82s/it]
Loading safetensors checkpoint shards: 100% Completed | 2/2 [00:03<00:00,  1.82s/it]

INFO 04-18 06:05:01 executor_base.py:111] # npu blocks: 5862, # CPU blocks: 585
INFO 04-18 06:05:01 executor_base.py:116] Maximum concurrency for 4096 tokens per request: 183.19x
INFO 04-18 06:05:01 llm_engine.py:435] init engine (profile, create kv cache, warmup model) took 15.04 seconds
Processed prompts:   0%|                                                                                          | 0/8 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]INFO 04-18 06:05:02 executor_base.py:111] # npu blocks: 5862, # CPU blocks: 585
INFO 04-18 06:05:02 executor_base.py:116] Maximum concurrency for 4096 tokens per request: 183.19x
INFO 04-18 06:05:02 llm_engine.py:435] init engine (profile, create kv cache, warmup model) took 16.35 seconds
Processed prompts: 100%|███████████████████████████████████████████████████████████████████████████████| 8/8 [00:00<00:00, 10.23it/s, est. speed input: 66.49 toks/s, output: 163.65 toks/s]
DP rank 0, Prompt: 'Hello, my name is', Generated text: " Daniel!\n\nI'm trying to solve for \\( x \\) in the equation \\("
DP rank 0, Prompt: 'The president of the United States is', Generated text: ' seeking to find the number of points with integer coordinates in !$\\text{SAT'
DP rank 0, Prompt: 'The capital of France is', Generated text: ' Paris.\n\nThat is correct.\n\nBut wait, sometimes in the real world, when'
DP rank 0, Prompt: 'The future of AI is', Generated text: ' now an important question.\nAlright, so I need to figure out what the'
DP rank 0, Prompt: 'Hello, my name is', Generated text: " Smith, and today I'm trying to figure out how to calculate the area of"
Processed prompts: 100%|███████████████████████████████████████████████████████████████████████████████| 8/8 [00:00<00:00,  9.16it/s, est. speed input: 59.56 toks/s, output: 183.25 toks/s]
DP rank 1, Prompt: 'Hello, my name is', Generated text: " Daniel!\n\nI'm trying to solve for \\( x \\) in the equation \\( x = 7"
DP rank 1, Prompt: 'The president of the United States is', Generated text: ' seeking to find the number of points with integer coordinates in !$\\text{SAT}_{(2)}'
DP rank 1, Prompt: 'The capital of France is', Generated text: ' Paris.\n\nThat is correct.\n\nBut wait, sometimes in the real world, when you write code or'
DP rank 1, Prompt: 'The future of AI is', Generated text: ' now an important question.\nAlright, so I need to figure out what the future of AI looks'
DP rank 1, Prompt: 'Hello, my name is', Generated text: " Smith, and today I'm trying to figure out how to calculate the area of a regular polygon with"
```

**Comment by zhaomingyu13** [comment]
@gao12312 So your problem has been solved？If there is still any bug, please reply me or submit a new issue.
