### ISSUE TITLE
[Feature]: Needs to support switching to MoEComm.ALLGATHER communication to adapt to the A2 dual-machine back-to-back networking scenario

### ISSUE THREAD

**Issue by Mitchellax** [vllm-project/vllm-ascend#5674]
### 🚀 The feature, motivation and pitch

Needs to support switching to MoEComm.ALLGATHER communication to adapt to the A2 dual-machine back-to-back networking scenario.

In a A2 dual-machine back-to-back network, two machines directly connected without a switch. HCCL does not support full-mesh connection establishment. When deploying vLLM-ascend with 16 cards, configuration for Qwen3-235B in a dual-machine PD-mixed deployment scenario, MoECommType.MC2 communication is used, leading to connection failures. 

It is recommended that the framework support automatic or manual switching to MoECommType.ALLGATHER in this scenario to avoid the issue.

双机背靠背组网时，HCCL不支持全互联建链。vLLM-ascend双机混部十六卡拉起Qwen3-235B时，会使用MoECommType.MC2通信导致建链失败。

建议框架在这个场景下支持自动或手动切换到MoECommType.ALLGATHER规避这个问题。

### Alternatives

The LLDP interface of the HCCN tool can detect whether dual machines are directly connected without a switch. The `msprechecker` pre-checking tool has already integrated the relevant checking logic. However, the HCCL interface does not provide the capability to query this kind of connectivity.

**v0.11.0:**  
Manually modify `vllm_ascend/worker/model_runner_v1.py`, and insert the following line before returning in the `_select_moe_comm_method` method:

```python
moe_comm_type = MoECommType.ALLGATHER
```

**v0.13.0:**  
Manually modify `vllm_ascend/ascend_forward_context.py`, and insert the following line before returning in the `select_moe_comm_method` method:

```python
moe_comm_type = MoECommType.ALLGATHER
```

Forcing a switch to the communication operator can temporarily workaround this issue. While this may introduce performance degradation, it at least ensures that the model service can be successfully launched. A more elegant and sustainable solution is still needed.

HCCN tool的LLDP接口可以查询是否双机直连，msprechecker预检工具已合入相关逻辑。HCCL接口无法查询是否双机直连。

v0.11.0：
手动在vllm_ascend/worker/model_runner_v1.py中，_select_moe_comm_method方法返回前加入：

```python
moe_comm_type=MoECommType.ALLGATHER
```

v0.13.0：
手动在vllm_ascend/ascend_forward_context.py中，select_moe_comm_method方法返回前加入：
```python
moe_comm_type=MoECommType.ALLGATHER
```

强行切换通信算子可以临时规避这个问题。可能引入性能劣化，但至少模型服务能够拉起。需要更优雅的解决方案。

**Comment by BigCousin-z** [comment]
有其他的好的方案吗？

**Comment by Tflowers-0129** [comment]
此问题是否已经解决？

**Comment by Mitchellax** [comment]
> 此问题是否已经解决？

0.21版本还是这么改，MoE模型开启专家并行后，A2背靠背组网下都需要修改通信算子。A3的组网场景比较复杂，需要额外配置。
