### ISSUE TITLE
[Usage]: deploy GME-Qwen2-VL-2B-Instruct with vllm ascend error, error no is 561103 & error msg is ERR00100 PTA call acl api failed. EZ9999: Inner Error!

### ISSUE THREAD

**Issue by TaoZC1996** [vllm-project/vllm-ascend#5695]
### Your current environment

```text
[root@gpu-node-k8s-ascend910b1 gme-Qwen2-VL-2B-Instruct]# npu-smi info
+------------------------------------------------------------------------------------------------+
| npu-smi 25.3.rc1                 Version: 25.3.rc1                                             |
+---------------------------+---------------+----------------------------------------------------+
| NPU   Name                | Health        | Power(W)    Temp(C)           Hugepages-Usage(page)|
| Chip                      | Bus-Id        | AICore(%)   Memory-Usage(MB)  HBM-Usage(MB)        |
+===========================+===============+====================================================+
| 2     910B2               | OK            | 88.0        33                0    / 0             |
| 0                         | 0000:81:00.0  | 0           0    / 0          3437 / 65536         |
+===========================+===============+====================================================+
+---------------------------+---------------+----------------------------------------------------+
| NPU     Chip              | Process id    | Process name             | Process memory(MB)      |
+===========================+===============+====================================================+
| No running processes found in NPU 2                                                            |
+===========================+===============+====================================================+


[root@gpu-node-k8s-ascend910b1 workspace]# cat /usr/local/Ascend/ascend-toolkit/latest/"$(uname -i)"-linux/ascend_toolkit_install.info
package_name=Ascend-cann-toolkit
version=8.3.RC2
innerversion=V100R001C23SPC002B210
compatible_version=[V100R001C15],[V100R001C18],[V100R001C19],[V100R001C20],[V100R001C21],[V100R001C23]
arch=aarch64
os=linux
path=/usr/local/Ascend/ascend-toolkit/8.3.RC2/aarch64-linux


[root@gpu-node-k8s-ascend910b1 vllm-ascend]# python3 collect_env.py 
Collecting environment information...
PyTorch version: 2.7.1+cpu
Is debug build: False

OS: openEuler 24.03 (LTS-SP2) (aarch64)
GCC version: (GCC) 12.3.1 (openEuler 12.3.1-99.oe2403sp2)
Clang version: Could not collect
CMake version: version 4.2.1
Libc version: glibc-2.38

Python version: 3.11.13 (main, Nov 20 2025, 16:58:42) [GCC 12.3.1 (openEuler 12.3.1-98.oe2403sp2)] (64-bit runtime)
Python platform: Linux-4.19.90-89.11.v2401.ky10.aarch64-aarch64-with-glibc2.38

CPU:
Architecture:                       aarch64
CPU op-mode(s):                     64-bit
Byte Order:                         Little Endian
CPU(s):                             192
On-line CPU(s) list:                0-191
Vendor ID:                          HiSilicon
BIOS Vendor ID:                     HiSilicon
Model name:                         Kunpeng-920
BIOS Model name:                    HUAWEI Kunpeng 920 5250 To be filled by O.E.M. CPU @ 2.6GHz
BIOS CPU family:                    280
Model:                              0
Thread(s) per core:                 1
Core(s) per socket:                 48
Socket(s):                          4
Stepping:                           0x1
BogoMIPS:                           200.00
Flags:                              fp asimd evtstrm aes pmull sha1 sha2 crc32 atomics fphp asimdhp cpuid asimdrdm jscvt fcma dcpop asimddp asimdfhm ssbs
L1d cache:                          12 MiB (192 instances)
L1i cache:                          12 MiB (192 instances)
L2 cache:                           96 MiB (192 instances)
L3 cache:                           192 MiB (8 instances)
NUMA node(s):                       8
NUMA node0 CPU(s):                  0-23
NUMA node1 CPU(s):                  24-47
NUMA node2 CPU(s):                  48-71
NUMA node3 CPU(s):                  72-95
NUMA node4 CPU(s):                  96-119
NUMA node5 CPU(s):                  120-143
NUMA node6 CPU(s):                  144-167
NUMA node7 CPU(s):                  168-191
Vulnerability Gather data sampling: Not affected
Vulnerability Itlb multihit:        Not affected
Vulnerability L1tf:                 Not affected
Vulnerability Mds:                  Not affected
Vulnerability Meltdown:             Not affected
Vulnerability Mmio stale data:      Not affected
Vulnerability Retbleed:             Not affected
Vulnerability Spec store bypass:    Mitigation; Speculative Store Bypass disabled via prctl
Vulnerability Spectre v1:           Mitigation; __user pointer sanitization
Vulnerability Spectre v2:           Not affected
Vulnerability Srbds:                Not affected
Vulnerability Tsx async abort:      Not affected

Versions of relevant libraries:
[pip3] numpy==1.26.4
[pip3] pyzmq==27.1.0
[pip3] torch==2.7.1+cpu
[pip3] torch_npu==2.7.1
[pip3] torchvision==0.22.1
[pip3] transformers==4.57.1
[conda] Could not collect
vLLM Version: 0.11.0
vLLM Ascend Version: 0.11.1.dev5+g56c87a016 (git sha: 56c87a016)

ENV Var iables:
ATB_OPSRUNNER_KERNEL_CACHE_LOCAL_COUNT=1
ATB_STREAM_SYNC_EVERY_RUNNER_ENABLE=0
ATB_OPSRUNNER_SETUP_CACHE_ENABLE=1
ATB_WORKSPACE_MEM_ALLOC_GLOBAL=1
ATB_DEVICE_TILING_BUFFER_BLOCK_NUM=32
ATB_STREAM_SYNC_EVERY_KERNEL_ENABLE=0
ATB_OPSRUNNER_KERNEL_CACHE_GLOABL_COUNT=5
ATB_HOME_PATH=/usr/local/Ascend/nnal/atb/latest/atb/cxx_abi_1
ASCEND_TOOLKIT_HOME=/usr/local/Ascend/ascend-toolkit/latest
ATB_COMPARE_TILING_EVERY_KERNEL=0
ASCEND_OPP_PATH=/usr/local/Ascend/ascend-toolkit/latest/opp
LD_LIBRARY_PATH=/usr/local/Ascend/nnal/atb/latest/atb/cxx_abi_1/lib:/usr/local/Ascend/nnal/atb/latest/atb/cxx_abi_1/examples:/usr/local/Ascend/nnal/atb/latest/atb/cxx_abi_1/tests/atbopstest:/usr/local/Ascend/ascend-toolkit/latest/tools/aml/lib64:/usr/local/Ascend/ascend-toolkit/latest/tools/aml/lib64/plugin:/usr/local/Ascend/ascend-toolkit/latest/lib64:/usr/local/Ascend/ascend-toolkit/latest/lib64/plugin/opskernel:/usr/local/Ascend/ascend-toolkit/latest/lib64/plugin/nnengine:/usr/local/Ascend/ascend-toolkit/latest/opp/built-in/op_impl/ai_core/tbe/op_tiling/lib/linux/aarch64:/usr/local/Ascend/nnal/atb/latest/atb/cxx_abi_0/lib:/usr/local/Ascend/nnal/atb/latest/atb/cxx_abi_0/examples:/usr/local/Ascend/nnal/atb/latest/atb/cxx_abi_0/tests/atbopstest:/usr/local/Ascend/ascend-toolkit/latest/tools/aml/lib64:/usr/local/Ascend/ascend-toolkit/latest/tools/aml/lib64/plugin:/usr/local/Ascend/ascend-toolkit/latest/lib64:/usr/local/Ascend/ascend-toolkit/latest/lib64/plugin/opskernel:/usr/local/Ascend/ascend-toolkit/latest/lib64/plugin/nnengine:/usr/local/Ascend/ascend-toolkit/latest/opp/built-in/op_impl/ai_core/tbe/op_tiling:/usr/local/Ascend/driver/lib64/common/:/usr/local/Ascend/driver/lib64/driver/:
ASCEND_AICPU_PATH=/usr/local/Ascend/ascend-toolkit/latest
ATB_STREAM_SYNC_EVERY_OPERATION_ENABLE=0
ASCEND_HOME_PATH=/usr/local/Ascend/ascend-toolkit/latest
ATB_MATMUL_SHUFFLE_K_ENABLE=1
ATB_WORKSPACE_MEM_ALLOC_ALG_TYPE=1
ATB_HOST_TILING_BUFFER_BLOCK_NUM=128
ATB_SHARE_MEMORY_NAME_SUFFIX=
TORCH_DEVICE_BACKEND_AUTOLOAD=1
PYTORCH_NVML_BASED_CUDA_CHECK=1
TORCHINDUCTOR_COMPILE_THREADS=1


NPU:
+------------------------------------------------------------------------------------------------+
| npu-smi 25.3.rc1                 Version: 25.3.rc1                                             |
+---------------------------+---------------+----------------------------------------------------+
| NPU   Name                | Health        | Power(W)    Temp(C)           Hugepages-Usage(page)|
| Chip                      | Bus-Id        | AICore(%)   Memory-Usage(MB)  HBM-Usage(MB)        |
+===========================+===============+====================================================+
| 0     910B2               | OK            | 95.7        37                0    / 0             |
| 0                         | 0000:C1:00.0  | 0           0    / 0          59976/ 65536         |
+===========================+===============+====================================================+
| 1     910B2               | OK            | 91.2        34                0    / 0             |
| 0                         | 0000:C2:00.0  | 0           0    / 0          19701/ 65536         |
+===========================+===============+====================================================+
| 2     910B2               | OK            | 87.7        35                0    / 0             |
| 0                         | 0000:81:00.0  | 0           0    / 0          13483/ 65536         |
+===========================+===============+====================================================+
| 3     910B2               | OK            | 97.5        38                0    / 0             |
| 0                         | 0000:82:00.0  | 0           0    / 0          5729 / 65536         |
+===========================+===============+====================================================+
| 4     910B2               | OK            | 126.5       44                0    / 0             |
| 0                         | 0000:01:00.0  | 19          0    / 0          61507/ 65536         |
+===========================+===============+====================================================+
| 5     910B2               | OK            | 119.1       45                0    / 0             |
| 0                         | 0000:02:00.0  | 20          0    / 0          61507/ 65536         |
+===========================+===============+====================================================+
| 6     910B2               | OK            | 132.1       45                0    / 0             |
| 0                         | 0000:41:00.0  | 17          0    / 0          61507/ 65536         |
+===========================+===============+====================================================+
| 7     910B2               | OK            | 123.4       46                0    / 0             |
| 0                         | 0000:42:00.0  | 19          0    / 0          61507/ 65536         |
+===========================+===============+====================================================+
+---------------------------+---------------+----------------------------------------------------+
| NPU     Chip              | Process id    | Process name             | Process memory(MB)      |
+===========================+===============+====================================================+
| 0       0                 | 3367087       |                          | 56592                   |
+===========================+===============+====================================================+
| 1       0                 | 1525041       |                          | 16321                   |
+===========================+===============+====================================================+
| 2       0                 | 2436328       |                          | 395                     |
| 2       0                 | 2442888       |                          | 163                     |
| 2       0                 | 2437552       |                          | 873                     |
| 2       0                 | 2437520       |                          | 873                     |
| 2       0                 | 2433744       |                          | 145                     |
| 2       0                 | 2434728       |                          | 157                     |
| 2       0                 | 2433448       |                          | 581                     |
| 2       0                 | 2438929       |                          | 274                     |
+===========================+===============+====================================================+
| 3       0                 | 1500268       |                          | 2351                    |
+===========================+===============+====================================================+
| 4       0                 | 374514        |                          | 58122                   |
+===========================+===============+====================================================+
| 5       0                 | 374515        |                          | 58123                   |
+===========================+===============+====================================================+
| 6       0                 | 374516        |                          | 58123                   |
+===========================+===============+====================================================+
| 7       0                 | 374517        |                          | 58123                   |
+===========================+===============+====================================================+

CANN:
package_name=Ascend-cann-toolkit
version=8.3.RC2
innerversion=V100R001C23SPC002B210
compatible_version=[V100R001C15],[V100R001C18],[V100R001C19],[V100R001C20],[V100R001C21],[V100R001C23]
arch=aarch64
os=linux
path=/usr/local/Ascend/ascend-toolkit/8.3.RC2/aarch64-linux
```

### How would you like to use vllm on ascend

I want to run inference of a [gme-Qwen2-VL-2B-Instruct](https://modelscope.cn/models/iic/gme-Qwen2-VL-2B-Instruct). I don't know how to integrate it with vllm ascend.
The complete error message is as follows: 
-------------------------------------
(EngineCore_DP0 pid=791) INFO 01-07 02:37:52 [importing.py:63] Triton not installed or not compatible; certain GPU-related functions will not be available.
(EngineCore_DP0 pid=791) INFO 01-07 02:37:54 [parallel_state.py:1208] rank 0 in world size 1 is assigned as DP rank 0, PP rank 0, TP rank 0, EP rank 0
(EngineCore_DP0 pid=791) ERROR 01-07 02:37:55 [patch_core.py:58] EngineCore failed to start.
(EngineCore_DP0 pid=791) ERROR 01-07 02:37:55 [patch_core.py:58] Traceback (most recent call last):
(EngineCore_DP0 pid=791) ERROR 01-07 02:37:55 [patch_core.py:58]   File "/vllm-workspace/vllm-ascend/vllm_ascend/patch/platform/patch_core.py", line 49, in run_engine_core
(EngineCore_DP0 pid=791) ERROR 01-07 02:37:55 [patch_core.py:58]     engine_core = EngineCoreProc(*args, **kwargs)
(EngineCore_DP0 pid=791) ERROR 01-07 02:37:55 [patch_core.py:58]                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(EngineCore_DP0 pid=791) ERROR 01-07 02:37:55 [patch_core.py:58]   File "/vllm-workspace/vllm/vllm/v1/engine/core.py", line 498, in __init__
(EngineCore_DP0 pid=791) ERROR 01-07 02:37:55 [patch_core.py:58]     super().__init__(vllm_config, executor_class, log_stats,
(EngineCore_DP0 pid=791) ERROR 01-07 02:37:55 [patch_core.py:58]   File "/vllm-workspace/vllm/vllm/v1/engine/core.py", line 83, in __init__
(EngineCore_DP0 pid=791) ERROR 01-07 02:37:55 [patch_core.py:58]     self.model_executor = executor_class(vllm_config)
(EngineCore_DP0 pid=791) ERROR 01-07 02:37:55 [patch_core.py:58]                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
(EngineCore_DP0 pid=791) ERROR 01-07 02:37:55 [patch_core.py:58]   File "/vllm-workspace/vllm/vllm/executor/executor_base.py", line 54, in __init__
(EngineCore_DP0 pid=791) ERROR 01-07 02:37:55 [patch_core.py:58]     self._init_executor()
(EngineCore_DP0 pid=791) ERROR 01-07 02:37:55 [patch_core.py:58]   File "/vllm-workspace/vllm/vllm/executor/uniproc_executor.py", line 54, in _init_executor
(EngineCore_DP0 pid=791) ERROR 01-07 02:37:55 [patch_core.py:58]     self.collective_rpc("init_device")
(EngineCore_DP0 pid=791) ERROR 01-07 02:37:55 [patch_core.py:58]   File "/vllm-workspace/vllm/vllm/executor/uniproc_executor.py", line 83, in collective_rpc
(EngineCore_DP0 pid=791) ERROR 01-07 02:37:55 [patch_core.py:58]     return [run_method(self.driver_worker, method, args, kwargs)]
(EngineCore_DP0 pid=791) ERROR 01-07 02:37:55 [patch_core.py:58]             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(EngineCore_DP0 pid=791) ERROR 01-07 02:37:55 [patch_core.py:58]   File "/vllm-workspace/vllm/vllm/utils/__init__.py", line 3122, in run_method
(EngineCore_DP0 pid=791) ERROR 01-07 02:37:55 [patch_core.py:58]     return func(*args, **kwargs)
(EngineCore_DP0 pid=791) ERROR 01-07 02:37:55 [patch_core.py:58]            ^^^^^^^^^^^^^^^^^^^^^
(EngineCore_DP0 pid=791) ERROR 01-07 02:37:55 [patch_core.py:58]   File "/vllm-workspace/vllm/vllm/worker/worker_base.py", line 259, in init_device
(EngineCore_DP0 pid=791) ERROR 01-07 02:37:55 [patch_core.py:58]     self.worker.init_device()  # type: ignore
(EngineCore_DP0 pid=791) ERROR 01-07 02:37:55 [patch_core.py:58]     ^^^^^^^^^^^^^^^^^^^^^^^^^
(EngineCore_DP0 pid=791) ERROR 01-07 02:37:55 [patch_core.py:58]   File "/vllm-workspace/vllm-ascend/vllm_ascend/worker/worker_v1.py", line 217, in init_device
(EngineCore_DP0 pid=791) ERROR 01-07 02:37:55 [patch_core.py:58]     self.model_runner = NPUModelRunner(self.vllm_config, device)
(EngineCore_DP0 pid=791) ERROR 01-07 02:37:55 [patch_core.py:58]                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(EngineCore_DP0 pid=791) ERROR 01-07 02:37:55 [patch_core.py:58]   File "/vllm-workspace/vllm-ascend/vllm_ascend/worker/model_runner_v1.py", line 310, in __init__
(EngineCore_DP0 pid=791) ERROR 01-07 02:37:55 [patch_core.py:58]     self.inputs_embeds = torch.zeros(
(EngineCore_DP0 pid=791) ERROR 01-07 02:37:55 [patch_core.py:58]                          ^^^^^^^^^^^^
(EngineCore_DP0 pid=791) ERROR 01-07 02:37:55 [patch_core.py:58] RuntimeError: zero_:build/CMakeFiles/torch_npu.dir/compiler_depend.ts:26 NPU function error: call aclnnInplaceZero failed, error code is 561103
(EngineCore_DP0 pid=791) ERROR 01-07 02:37:55 [patch_core.py:58] [ERROR] 2026-01-07-02:37:55 (PID:791, Device:0, RankID:-1) ERR00100 PTA call acl api failed.
(EngineCore_DP0 pid=791) ERROR 01-07 02:37:55 [patch_core.py:58] EZ9999: Inner Error!
(EngineCore_DP0 pid=791) ERROR 01-07 02:37:55 [patch_core.py:58] EZ9999[PID: 791] 2026-01-07-02:37:55.044.805 AclNN_Inner_Error(EZ9999):  Parse dynamic kernel config fail.
(EngineCore_DP0 pid=791) ERROR 01-07 02:37:55 [patch_core.py:58]         TraceBack (most recent call last):
(EngineCore_DP0 pid=791) ERROR 01-07 02:37:55 [patch_core.py:58]        Failed to ParseDynamicKernels.
(EngineCore_DP0 pid=791) ERROR 01-07 02:37:55 [patch_core.py:58]        AclOpKernelInit failed opType
(EngineCore_DP0 pid=791) ERROR 01-07 02:37:55 [patch_core.py:58]        ZerosLike ADD_TO_LAUNCHER_LIST_AICORE failed.
(EngineCore_DP0 pid=791) ERROR 01-07 02:37:55 [patch_core.py:58] 
(EngineCore_DP0 pid=791) Process EngineCore_DP0:
(EngineCore_DP0 pid=791) Traceback (most recent call last):
(EngineCore_DP0 pid=791)   File "/usr/local/python3.11.13/lib/python3.11/multiprocessing/process.py", line 314, in _bootstrap
(EngineCore_DP0 pid=791)     self.run()
(EngineCore_DP0 pid=791)   File "/usr/local/python3.11.13/lib/python3.11/multiprocessing/process.py", line 108, in run
(EngineCore_DP0 pid=791)     self._target(*self._args, **self._kwargs)
(EngineCore_DP0 pid=791)   File "/vllm-workspace/vllm-ascend/vllm_ascend/patch/platform/patch_core.py", line 62, in run_engine_core
(EngineCore_DP0 pid=791)     raise e
(EngineCore_DP0 pid=791)   File "/vllm-workspace/vllm-ascend/vllm_ascend/patch/platform/patch_core.py", line 49, in run_engine_core
(EngineCore_DP0 pid=791)     engine_core = EngineCoreProc(*args, **kwargs)
(EngineCore_DP0 pid=791)                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(EngineCore_DP0 pid=791)   File "/vllm-workspace/vllm/vllm/v1/engine/core.py", line 498, in __init__
(EngineCore_DP0 pid=791)     super().__init__(vllm_config, executor_class, log_stats,
(EngineCore_DP0 pid=791)   File "/vllm-workspace/vllm/vllm/v1/engine/core.py", line 83, in __init__
(EngineCore_DP0 pid=791)     self.model_executor = executor_class(vllm_config)
(EngineCore_DP0 pid=791)                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
(EngineCore_DP0 pid=791)   File "/vllm-workspace/vllm/vllm/executor/executor_base.py", line 54, in __init__
(EngineCore_DP0 pid=791)     self._init_executor()
(EngineCore_DP0 pid=791)   File "/vllm-workspace/vllm/vllm/executor/uniproc_executor.py", line 54, in _init_executor
(EngineCore_DP0 pid=791)     self.collective_rpc("init_device")
(EngineCore_DP0 pid=791)   File "/vllm-workspace/vllm/vllm/executor/uniproc_executor.py", line 83, in collective_rpc
(EngineCore_DP0 pid=791)     return [run_method(self.driver_worker, method, args, kwargs)]
(EngineCore_DP0 pid=791)             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(EngineCore_DP0 pid=791)   File "/vllm-workspace/vllm/vllm/utils/__init__.py", line 3122, in run_method
(EngineCore_DP0 pid=791)     return func(*args, **kwargs)
(EngineCore_DP0 pid=791)            ^^^^^^^^^^^^^^^^^^^^^
(EngineCore_DP0 pid=791)   File "/vllm-workspace/vllm/vllm/worker/worker_base.py", line 259, in init_device
(EngineCore_DP0 pid=791)     self.worker.init_device()  # type: ignore
(EngineCore_DP0 pid=791)     ^^^^^^^^^^^^^^^^^^^^^^^^^
(EngineCore_DP0 pid=791)   File "/vllm-workspace/vllm-ascend/vllm_ascend/worker/worker_v1.py", line 217, in init_device
(EngineCore_DP0 pid=791)     self.model_runner = NPUModelRunner(self.vllm_config, device)
(EngineCore_DP0 pid=791)                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(EngineCore_DP0 pid=791)   File "/vllm-workspace/vllm-ascend/vllm_ascend/worker/model_runner_v1.py", line 310, in __init__
(EngineCore_DP0 pid=791)     self.inputs_embeds = torch.zeros(
(EngineCore_DP0 pid=791)                          ^^^^^^^^^^^^
(EngineCore_DP0 pid=791) RuntimeError: zero_:build/CMakeFiles/torch_npu.dir/compiler_depend.ts:26 NPU function error: call aclnnInplaceZero failed, error code is 561103
(EngineCore_DP0 pid=791) [ERROR] 2026-01-07-02:37:55 (PID:791, Device:0, RankID:-1) ERR00100 PTA call acl api failed.
(EngineCore_DP0 pid=791) EZ9999: Inner Error!
(EngineCore_DP0 pid=791) EZ9999[PID: 791] 2026-01-07-02:37:55.044.805 AclNN_Inner_Error(EZ9999):  Parse dynamic kernel config fail.
(EngineCore_DP0 pid=791)         TraceBack (most recent call last):
(EngineCore_DP0 pid=791)        Failed to ParseDynamicKernels.
(EngineCore_DP0 pid=791)        AclOpKernelInit failed opType
(EngineCore_DP0 pid=791)        ZerosLike ADD_TO_LAUNCHER_LIST_AICORE failed.
(EngineCore_DP0 pid=791) 
(APIServer pid=523) Traceback (most recent call last):
(APIServer pid=523)   File "<frozen runpy>", line 198, in _run_module_as_main
(APIServer pid=523)   File "<frozen runpy>", line 88, in _run_code
(APIServer pid=523)   File "/vllm-workspace/vllm/vllm/entrypoints/openai/api_server.py", line 2059, in <module>
(APIServer pid=523)     uvloop.run(run_server(args))
(APIServer pid=523)   File "/usr/local/python3.11.13/lib/python3.11/site-packages/uvloop/__init__.py", line 92, in run
(APIServer pid=523)     return runner.run(wrapper())
(APIServer pid=523)            ^^^^^^^^^^^^^^^^^^^^^
(APIServer pid=523)   File "/usr/local/python3.11.13/lib/python3.11/asyncio/runners.py", line 118, in run
(APIServer pid=523)     return self._loop.run_until_complete(task)
(APIServer pid=523)            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(APIServer pid=523)   File "uvloop/loop.pyx", line 1518, in uvloop.loop.Loop.run_until_complete
(APIServer pid=523)   File "/usr/local/python3.11.13/lib/python3.11/site-packages/uvloop/__init__.py", line 48, in wrapper
(APIServer pid=523)     return await main
(APIServer pid=523)            ^^^^^^^^^^
(APIServer pid=523)   File "/vllm-workspace/vllm/vllm/entrypoints/openai/api_server.py", line 1990, in run_server
(APIServer pid=523)     await run_server_worker(listen_address, sock, args, **uvicorn_kwargs)
(APIServer pid=523)   File "/vllm-workspace/vllm/vllm/entrypoints/openai/api_server.py", line 2008, in run_server_worker
(APIServer pid=523)     async with build_async_engine_client(
(APIServer pid=523)   File "/usr/local/python3.11.13/lib/python3.11/contextlib.py", line 210, in __aenter__
(APIServer pid=523)     return await anext(self.gen)
(APIServer pid=523)            ^^^^^^^^^^^^^^^^^^^^^
(APIServer pid=523)   File "/vllm-workspace/vllm/vllm/entrypoints/openai/api_server.py", line 184, in build_async_engine_client
(APIServer pid=523)     async with build_async_engine_client_from_engine_args(
(APIServer pid=523)   File "/usr/local/python3.11.13/lib/python3.11/contextlib.py", line 210, in __aenter__
(APIServer pid=523)     return await anext(self.gen)
(APIServer pid=523)            ^^^^^^^^^^^^^^^^^^^^^
(APIServer pid=523)   File "/vllm-workspace/vllm/vllm/entrypoints/openai/api_server.py", line 229, in build_async_engine_client_from_engine_args
(APIServer pid=523)     async_llm = AsyncLLM.from_vllm_config(
(APIServer pid=523)                 ^^^^^^^^^^^^^^^^^^^^^^^^^^
(APIServer pid=523)   File "/vllm-workspace/vllm/vllm/utils/__init__.py", line 1572, in inner
(APIServer pid=523)     return fn(*args, **kwargs)
(APIServer pid=523)            ^^^^^^^^^^^^^^^^^^^
(APIServer pid=523)   File "/vllm-workspace/vllm/vllm/v1/engine/async_llm.py", line 207, in from_vllm_config
(APIServer pid=523)     return cls(
(APIServer pid=523)            ^^^^
(APIServer pid=523)   File "/vllm-workspace/vllm/vllm/v1/engine/async_llm.py", line 134, in __init__
(APIServer pid=523)     self.engine_core = EngineCoreClient.make_async_mp_client(
(APIServer pid=523)                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(APIServer pid=523)   File "/vllm-workspace/vllm/vllm/v1/engine/core_client.py", line 102, in make_async_mp_client
(APIServer pid=523)     return AsyncMPClient(*client_args)
(APIServer pid=523)            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
(APIServer pid=523)   File "/vllm-workspace/vllm/vllm/v1/engine/core_client.py", line 769, in __init__
(APIServer pid=523)     super().__init__(
(APIServer pid=523)   File "/vllm-workspace/vllm/vllm/v1/engine/core_client.py", line 448, in __init__
(APIServer pid=523)     with launch_core_engines(vllm_config, executor_class,
(APIServer pid=523)   File "/usr/local/python3.11.13/lib/python3.11/contextlib.py", line 144, in __exit__
(APIServer pid=523)     next(self.gen)
(APIServer pid=523)   File "/vllm-workspace/vllm/vllm/v1/engine/utils.py", line 732, in launch_core_engines
(APIServer pid=523)     wait_for_engine_startup(
(APIServer pid=523)   File "/vllm-workspace/vllm/vllm/v1/engine/utils.py", line 785, in wait_for_engine_startup
(APIServer pid=523)     raise RuntimeError("Engine core initialization failed. "
(APIServer pid=523) RuntimeError: Engine core initialization failed. See root cause above. Failed core proc(s): {}
(APIServer pid=523) [ERROR] 2026-01-07-02:38:00 (PID:523, Device:-1, RankID:-1) ERR99999 UNKNOWN applicaiton exception
-------------------------------------

I need help, thank you.

**Comment by TaoZC1996** [comment]
The model deploy command is: 
python3 -m vllm.entrypoints.openai.api_server --model /root/cx/gme-Qwen2-VL-2B-Instruct --port 9080

The container running command is:
docker run -it \
    --name vllm-ascend-test \
    --shm-size=1g \
    --privileged=true \
    --net=host \
    --device /dev/davinci2 \
    --device /dev/davinci_manager \
    --device /dev/devmm_svm \
    --device /dev/hisi_hdc \
    -v /usr/local/dcmi:/usr/local/dcmi \
    -v /usr/local/Ascend/driver/tools/hccn_tool:/usr/local/Ascend/driver/tools/hccn_tool \
    -v /usr/local/bin/npu-smi:/usr/local/bin/npu-smi \
    -v /usr/local/Ascend/driver/lib64/:/usr/local/Ascend/driver/lib64/ \
    -v /usr/local/Ascend/driver/version.info:/usr/local/Ascend/driver/version.info \
    -v /etc/ascend_install.info:/etc/ascend_install.info \
    -v /root/.cache:/root/.cache \
    -v /root/cx:/root/cx \
    -v /usr/local/Ascend/driver:/usr/local/Ascend/driver \
    m.daocloud.io/quay.io/ascend/vllm-ascend:v0.11.0-dev-a3-openeuler-new bash

**Comment by shaojun0** [comment]
The information provided is insufficient to investigate the issue

**Comment by ClientHello-PSK** [comment]
@TaoZC1996 his issue has been resolved in the latest version. Please use the latest release or rc version (https://github.com/vllm-project/vllm-ascend/releases). If the issue persists, feel free to submit a new issue.
