### ISSUE TITLE
[Bug]: qwen3 coder 235b failed to start and get HCCL function error

### ISSUE THREAD

**Issue by gao12312** [vllm-project/vllm-ascend#5748]
### Your current environment

<details>
<summary>The output of `python collect_env.py`</summary>

```text
Your output of above commands here
```

</details>

### 🐛 Describe the bug

A2+VLLM 0.13.0rc1

NODE0:
```python  
nic_name="eth0"
local_ip="XXXX"

export HCCL_IF_IP=$local_ip
export GLOO_SOCKET_IFNAME=$nic_name
export TP_SOCKET_IFNAME=$nic_name
export HCCL_SOCKET_IFNAME=$nic_name
#export HCCL_CONNECT_TIMEOUT=360
export OMP_PROC_BIND=false
export OMP_NUM_THREADS=1
export VLLM_USE_V1=1
export HCCL_BUFFSIZE=1024
export PYTORCH_NPU_ALLOC_CONF=expandable_segments:True
export HCCL_OP_EXPANSION_MODE="AIV"
export TASK_QUEUE_ENABLE=1
# export CPU_AFFINITY_CONF=2
# export VLLM_ASCEND_ENABLE_FLASHCOMM1=1
# export VLLM_ASCEND_ENABLE_FUSED_MC2=1  
# export VLLM_ALLOW_LONG_MAX_MODEL_LEN=1
# export HCCL_INTRA_PCIE_ENABLE=1
# export HCCL_INTRA_ROCE_ENABLE=0

vllm serve /models/Qwen3-Coder-480B-A35B-Instruct-w8a8 \
--host 0.0.0.0 \
--port 8000 \
--data-parallel-size 2 \
--data-parallel-size-local 1 \
--data-parallel-address $local_ip \
--data-parallel-rpc-port 13389 \
--seed 1024 \
--served-model-name qwen3_coder \
--enable-expert-parallel  \
--tensor-parallel-size 8 \
--max-num-seqs 16 \
--max-model-len 32768 \
--max-num-batched-tokens 8192 \
--trust-remote-code \
--gpu-memory-utilization 0.9 \
--async-scheduling \
```

NODE1:
```python  
#!/bin/sh

# this obtained through ifconfig
# nic_name is the network interface name corresponding to local_ip

nic_name="eth0"
local_ip="XXX"
node0_ip="XXX"

export HCCL_IF_IP=$local_ip
export GLOO_SOCKET_IFNAME=$nic_name
export TP_SOCKET_IFNAME=$nic_name
export HCCL_SOCKET_IFNAME=$nic_name

export OMP_PROC_BIND=false
export OMP_NUM_THREADS=1
export VLLM_USE_V1=1
export HCCL_BUFFSIZE=1024
export PYTORCH_NPU_ALLOC_CONF=expandable_segments:True
export HCCL_OP_EXPANSION_MODE="AIV"
export TASK_QUEUE_ENABLE=1

vllm serve /workspace/cache/aiops-sh2/models/Qwen3-Coder-480B-A35B-Instruct-w8a8 \
--host 0.0.0.0 \
--port 8000 \
--headless \
--data-parallel-size 2 \
--data-parallel-size-local 1 \
--data-parallel-start-rank 1 \
--data-parallel-address  $node0_ip \
--data-parallel-rpc-port 13389 \
--seed 1024 \
--tensor-parallel-size 8 \
--served-model-name qwen3-coder \
--quantization ascend  \
--enable-expert-parallel  \
--max-num-seqs 16 \
--max-model-len 32768 \
--max-num-batched-tokens 8192 \
--tool-call-parser qwen3_coder \
--gpu-memory-utilization 0.9 \
```

failed logs:
```python 
(Worker_DP0_TP0_EP0 pid=8457) ERROR 01-09 10:21:59 [multiproc_executor.py:751] WorkerProc failed to start.
(Worker_DP0_TP0_EP0 pid=8457) ERROR 01-09 10:21:59 [multiproc_executor.py:751] Traceback (most recent call last):
(Worker_DP0_TP0_EP0 pid=8457) ERROR 01-09 10:21:59 [multiproc_executor.py:751]   File "/vllm-workspace/vllm/vllm/v1/executor/multiproc_executor.py", line 722, in worker_main
(Worker_DP0_TP0_EP0 pid=8457) ERROR 01-09 10:21:59 [multiproc_executor.py:751]     worker = WorkerProc(*args, **kwargs)
(Worker_DP0_TP0_EP0 pid=8457) ERROR 01-09 10:21:59 [multiproc_executor.py:751]              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
(Worker_DP0_TP0_EP0 pid=8457) ERROR 01-09 10:21:59 [multiproc_executor.py:751]   File "/vllm-workspace/vllm/vllm/v1/executor/multiproc_executor.py", line 562, in __init__
(Worker_DP0_TP0_EP0 pid=8457) ERROR 01-09 10:21:59 [multiproc_executor.py:751]     self.worker.load_model()
(Worker_DP0_TP0_EP0 pid=8457) ERROR 01-09 10:21:59 [multiproc_executor.py:751]   File "/vllm-workspace/vllm-ascend/vllm_ascend/worker/worker.py", line 355, in load_model
(Worker_DP0_TP0_EP0 pid=8457) ERROR 01-09 10:21:59 [multiproc_executor.py:751]     self.model_runner.load_model()
(Worker_DP0_TP0_EP0 pid=8457) ERROR 01-09 10:21:59 [multiproc_executor.py:751]   File "/vllm-workspace/vllm-ascend/vllm_ascend/worker/model_runner_v1.py", line 2230, in load_model
(Worker_DP0_TP0_EP0 pid=8457) ERROR 01-09 10:21:59 [multiproc_executor.py:751]     self.model = get_model(vllm_config=self.vllm_config)
(Worker_DP0_TP0_EP0 pid=8457) ERROR 01-09 10:21:59 [multiproc_executor.py:751]                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(Worker_DP0_TP0_EP0 pid=8457) ERROR 01-09 10:21:59 [multiproc_executor.py:751]   File "/vllm-workspace/vllm/vllm/model_executor/model_loader/__init__.py", line 132, in get_model
(Worker_DP0_TP0_EP0 pid=8457) ERROR 01-09 10:21:59 [multiproc_executor.py:751]     return loader.load_model(vllm_config=vllm_config, model_config=model_config)
(Worker_DP0_TP0_EP0 pid=8457) ERROR 01-09 10:21:59 [multiproc_executor.py:751]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(Worker_DP0_TP0_EP0 pid=8457) ERROR 01-09 10:21:59 [multiproc_executor.py:751]   File "/vllm-workspace/vllm/vllm/model_executor/model_loader/base_loader.py", line 49, in load_model
(Worker_DP0_TP0_EP0 pid=8457) ERROR 01-09 10:21:59 [multiproc_executor.py:751]     model = initialize_model(
(Worker_DP0_TP0_EP0 pid=8457) ERROR 01-09 10:21:59 [multiproc_executor.py:751]             ^^^^^^^^^^^^^^^^^
(Worker_DP0_TP0_EP0 pid=8457) ERROR 01-09 10:21:59 [multiproc_executor.py:751]   File "/vllm-workspace/vllm/vllm/model_executor/model_loader/utils.py", line 48, in initialize_model
(Worker_DP0_TP0_EP0 pid=8457) ERROR 01-09 10:21:59 [multiproc_executor.py:751]     return model_class(vllm_config=vllm_config, prefix=prefix)
(Worker_DP0_TP0_EP0 pid=8457) ERROR 01-09 10:21:59 [multiproc_executor.py:751]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(Worker_DP0_TP0_EP0 pid=8457) ERROR 01-09 10:21:59 [multiproc_executor.py:751]   File "/vllm-workspace/vllm/vllm/model_executor/models/qwen3_moe.py", line 658, in __init__
(Worker_DP0_TP0_EP0 pid=8457) ERROR 01-09 10:21:59 [multiproc_executor.py:751]     self.model = Qwen3MoeModel(
(Worker_DP0_TP0_EP0 pid=8457) ERROR 01-09 10:21:59 [multiproc_executor.py:751]                  ^^^^^^^^^^^^^^
(Worker_DP0_TP0_EP0 pid=8457) ERROR 01-09 10:21:59 [multiproc_executor.py:751]   File "/vllm-workspace/vllm/vllm/compilation/decorators.py", line 291, in __init__
(Worker_DP0_TP0_EP0 pid=8457) ERROR 01-09 10:21:59 [multiproc_executor.py:751]     old_init(self, **kwargs)
(Worker_DP0_TP0_EP0 pid=8457) ERROR 01-09 10:21:59 [multiproc_executor.py:751]   File "/vllm-workspace/vllm/vllm/model_executor/models/qwen3_moe.py", line 412, in __init__
(Worker_DP0_TP0_EP0 pid=8457) ERROR 01-09 10:21:59 [multiproc_executor.py:751]     self.start_layer, self.end_layer, self.layers = make_layers(
(Worker_DP0_TP0_EP0 pid=8457) ERROR 01-09 10:21:59 [multiproc_executor.py:751]                                                     ^^^^^^^^^^^^
(Worker_DP0_TP0_EP0 pid=8457) ERROR 01-09 10:21:59 [multiproc_executor.py:751]   File "/vllm-workspace/vllm/vllm/model_executor/models/utils.py", line 605, in make_layers
(Worker_DP0_TP0_EP0 pid=8457) ERROR 01-09 10:21:59 [multiproc_executor.py:751]     + [
(Worker_DP0_TP0_EP0 pid=8457) ERROR 01-09 10:21:59 [multiproc_executor.py:751]       ^
(Worker_DP0_TP0_EP0 pid=8457) ERROR 01-09 10:21:59 [multiproc_executor.py:751]   File "/vllm-workspace/vllm/vllm/model_executor/models/utils.py", line 606, in <listcomp>
(Worker_DP0_TP0_EP0 pid=8457) ERROR 01-09 10:21:59 [multiproc_executor.py:751]     maybe_offload_to_cpu(layer_fn(prefix=f"{prefix}.{idx}"))
(Worker_DP0_TP0_EP0 pid=8457) ERROR 01-09 10:21:59 [multiproc_executor.py:751]                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(Worker_DP0_TP0_EP0 pid=8457) ERROR 01-09 10:21:59 [multiproc_executor.py:751]   File "/vllm-workspace/vllm/vllm/model_executor/models/qwen3_moe.py", line 414, in <lambda>
(Worker_DP0_TP0_EP0 pid=8457) ERROR 01-09 10:21:59 [multiproc_executor.py:751]     lambda prefix: Qwen3MoeDecoderLayer(vllm_config=vllm_config, prefix=prefix),
(Worker_DP0_TP0_EP0 pid=8457) ERROR 01-09 10:21:59 [multiproc_executor.py:751]                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(Worker_DP0_TP0_EP0 pid=8457) ERROR 01-09 10:21:59 [multiproc_executor.py:751]   File "/vllm-workspace/vllm/vllm/model_executor/models/qwen3_moe.py", line 352, in __init__
(Worker_DP0_TP0_EP0 pid=8457) ERROR 01-09 10:21:59 [multiproc_executor.py:751]     self.mlp = Qwen3MoeSparseMoeBlock(
(Worker_DP0_TP0_EP0 pid=8457) ERROR 01-09 10:21:59 [multiproc_executor.py:751]                ^^^^^^^^^^^^^^^^^^^^^^^
(Worker_DP0_TP0_EP0 pid=8457) ERROR 01-09 10:21:59 [multiproc_executor.py:751]   File "/vllm-workspace/vllm/vllm/model_executor/models/qwen3_moe.py", line 163, in __init__
(Worker_DP0_TP0_EP0 pid=8457) ERROR 01-09 10:21:59 [multiproc_executor.py:751]     self.experts = FusedMoE(
(Worker_DP0_TP0_EP0 pid=8457) ERROR 01-09 10:21:59 [multiproc_executor.py:751]                    ^^^^^^^^^
(Worker_DP0_TP0_EP0 pid=8457) ERROR 01-09 10:21:59 [multiproc_executor.py:751]   File "/vllm-workspace/vllm-ascend/vllm_ascend/ops/fused_moe/fused_moe.py", line 255, in __init__
(Worker_DP0_TP0_EP0 pid=8457) ERROR 01-09 10:21:59 [multiproc_executor.py:751]     setup_moe_comm_method(self.moe_config)
(Worker_DP0_TP0_EP0 pid=8457) ERROR 01-09 10:21:59 [multiproc_executor.py:751]   File "/vllm-workspace/vllm-ascend/vllm_ascend/ops/fused_moe/moe_comm_method.py", line 44, in setup_moe_comm_method
(Worker_DP0_TP0_EP0 pid=8457) ERROR 01-09 10:21:59 [multiproc_executor.py:751]     _MoECommMethods[MoECommType.ALLTOALL] = AlltoAllCommImpl(moe_config)
(Worker_DP0_TP0_EP0 pid=8457) ERROR 01-09 10:21:59 [multiproc_executor.py:751]                                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(Worker_DP0_TP0_EP0 pid=8457) ERROR 01-09 10:21:59 [multiproc_executor.py:751]   File "/vllm-workspace/vllm-ascend/vllm_ascend/ops/fused_moe/moe_comm_method.py", line 56, in __init__
(Worker_DP0_TP0_EP0 pid=8457) ERROR 01-09 10:21:59 [multiproc_executor.py:751]     self.token_dispatcher = self._get_token_dispatcher()
(Worker_DP0_TP0_EP0 pid=8457) ERROR 01-09 10:21:59 [multiproc_executor.py:751]                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(Worker_DP0_TP0_EP0 pid=8457) ERROR 01-09 10:21:59 [multiproc_executor.py:751]   File "/vllm-workspace/vllm-ascend/vllm_ascend/ops/fused_moe/moe_comm_method.py", line 235, in _get_token_dispatcher
(Worker_DP0_TP0_EP0 pid=8457) ERROR 01-09 10:21:59 [multiproc_executor.py:751]     return TokenDispatcherWithAll2AllV(
(Worker_DP0_TP0_EP0 pid=8457) ERROR 01-09 10:21:59 [multiproc_executor.py:751]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(Worker_DP0_TP0_EP0 pid=8457) ERROR 01-09 10:21:59 [multiproc_executor.py:751]   File "/vllm-workspace/vllm-ascend/vllm_ascend/ops/fused_moe/token_dispatcher.py", line 465, in __init__
(Worker_DP0_TP0_EP0 pid=8457) ERROR 01-09 10:21:59 [multiproc_executor.py:751]     self.moe_all_to_all_group_name = backend.get_hccl_comm_name(local_rank)
(Worker_DP0_TP0_EP0 pid=8457) ERROR 01-09 10:21:59 [multiproc_executor.py:751]                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(Worker_DP0_TP0_EP0 pid=8457) ERROR 01-09 10:21:59 [multiproc_executor.py:751] RuntimeError: create_config:build/CMakeFiles/torch_npu.dir/compiler_depend.ts:148 HCCL function error: hcclCommInitRootInfoConfig(numRanks, &rootInfo, rank, config, &(comm->hcclComm_)), error code is 1
(Worker_DP0_TP0_EP0 pid=8457) ERROR 01-09 10:21:59 [multiproc_executor.py:751] [ERROR] 2026-01-09-10:21:58 (PID:8457, Device:0, RankID:-1) ERR02200 DIST call hccl api failed.
(Worker_DP0_TP0_EP0 pid=8457) ERROR 01-09 10:21:59 [multiproc_executor.py:751] 
(Worker_DP0_TP0_EP0 pid=8457) INFO 01-09 10:21:59 [multiproc_executor.py:709] Parent process exited, terminating worker
(Worker_DP0_TP4_EP4 pid=8461) INFO 01-09 10:21:59 [multiproc_executor.py:709] Parent process exited, terminating worker
(Worker_DP0_TP1_EP1 pid=8458) INFO 01-09 10:21:59 [multiproc_executor.py:709] Parent process exited, terminating worker
(Worker_DP0_TP2_EP2 pid=8459) INFO 01-09 10:21:59 [multiproc_executor.py:709] Parent process exited, terminating worker
(Worker_DP0_TP7_EP7 pid=8464) INFO 01-09 10:21:59 [multiproc_executor.py:709] Parent process exited, terminating worker
(Worker_DP0_TP6_EP6 pid=8463) INFO 01-09 10:21:59 [multiproc_executor.py:709] Parent process exited, terminating worker
(Worker_DP0_TP3_EP3 pid=8460) INFO 01-09 10:21:59 [multiproc_executor.py:709] Parent process exited, terminating worker
(Worker_DP0_TP5_EP5 pid=8462) INFO 01-09 10:21:59 [multiproc_executor.py:709] Parent process exited, terminating worker
(EngineCore_DP0 pid=8041) ERROR 01-09 10:22:03 [core.py:866] EngineCore failed to start.
(EngineCore_DP0 pid=8041) ERROR 01-09 10:22:03 [core.py:866] Traceback (most recent call last):
(EngineCore_DP0 pid=8041) ERROR 01-09 10:22:03 [core.py:866]   File "/vllm-workspace/vllm/vllm/v1/engine/core.py", line 853, in run_engine_core
(EngineCore_DP0 pid=8041) ERROR 01-09 10:22:03 [core.py:866]     engine_core = DPEngineCoreProc(*args, **kwargs)
(EngineCore_DP0 pid=8041) ERROR 01-09 10:22:03 [core.py:866]                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(EngineCore_DP0 pid=8041) ERROR 01-09 10:22:03 [core.py:866]   File "/vllm-workspace/vllm/vllm/v1/engine/core.py", line 1159, in __init__
(EngineCore_DP0 pid=8041) ERROR 01-09 10:22:03 [core.py:866]     super().__init__(
(EngineCore_DP0 pid=8041) ERROR 01-09 10:22:03 [core.py:866]   File "/vllm-workspace/vllm/vllm/v1/engine/core.py", line 637, in __init__
(EngineCore_DP0 pid=8041) ERROR 01-09 10:22:03 [core.py:866]     super().__init__(
(EngineCore_DP0 pid=8041) ERROR 01-09 10:22:03 [core.py:866]   File "/vllm-workspace/vllm/vllm/v1/engine/core.py", line 102, in __init__
(EngineCore_DP0 pid=8041) ERROR 01-09 10:22:03 [core.py:866]     self.model_executor = executor_class(vllm_config)
(EngineCore_DP0 pid=8041) ERROR 01-09 10:22:03 [core.py:866]                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
(EngineCore_DP0 pid=8041) ERROR 01-09 10:22:03 [core.py:866]   File "/vllm-workspace/vllm/vllm/v1/executor/multiproc_executor.py", line 97, in __init__
(EngineCore_DP0 pid=8041) ERROR 01-09 10:22:03 [core.py:866]     super().__init__(vllm_config)
(EngineCore_DP0 pid=8041) ERROR 01-09 10:22:03 [core.py:866]   File "/vllm-workspace/vllm/vllm/v1/executor/abstract.py", line 101, in __init__
(EngineCore_DP0 pid=8041) ERROR 01-09 10:22:03 [core.py:866]     self._init_executor()
(EngineCore_DP0 pid=8041) ERROR 01-09 10:22:03 [core.py:866]   File "/vllm-workspace/vllm/vllm/v1/executor/multiproc_executor.py", line 172, in _init_executor
(EngineCore_DP0 pid=8041) ERROR 01-09 10:22:03 [core.py:866]     self.workers = WorkerProc.wait_for_ready(unready_workers)
(EngineCore_DP0 pid=8041) ERROR 01-09 10:22:03 [core.py:866]                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(EngineCore_DP0 pid=8041) ERROR 01-09 10:22:03 [core.py:866]   File "/vllm-workspace/vllm/vllm/v1/executor/multiproc_executor.py", line 660, in wait_for_ready
(EngineCore_DP0 pid=8041) ERROR 01-09 10:22:03 [core.py:866]     raise e from None
(EngineCore_DP0 pid=8041) ERROR 01-09 10:22:03 [core.py:866] Exception: WorkerProc initialization failed due to an exception in a background process. See stack trace for root cause.
(EngineCore_DP0 pid=8041) Process EngineCore_DP0:
(EngineCore_DP0 pid=8041) Traceback (most recent call last):
(EngineCore_DP0 pid=8041)   File "/usr/local/python3.11.13/lib/python3.11/multiprocessing/process.py", line 314, in _bootstrap
(EngineCore_DP0 pid=8041)     self.run()
(EngineCore_DP0 pid=8041)   File "/usr/local/python3.11.13/lib/python3.11/multiprocessing/process.py", line 108, in run
(EngineCore_DP0 pid=8041)     self._target(*self._args, **self._kwargs)
(EngineCore_DP0 pid=8041)   File "/vllm-workspace/vllm/vllm/v1/engine/core.py", line 870, in run_engine_core
(EngineCore_DP0 pid=8041)     raise e
(EngineCore_DP0 pid=8041)   File "/vllm-workspace/vllm/vllm/v1/engine/core.py", line 853, in run_engine_core
(EngineCore_DP0 pid=8041)     engine_core = DPEngineCoreProc(*args, **kwargs)
(EngineCore_DP0 pid=8041)                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(EngineCore_DP0 pid=8041)   File "/vllm-workspace/vllm/vllm/v1/engine/core.py", line 1159, in __init__
(EngineCore_DP0 pid=8041)     super().__init__(
(EngineCore_DP0 pid=8041)   File "/vllm-workspace/vllm/vllm/v1/engine/core.py", line 637, in __init__
(EngineCore_DP0 pid=8041)     super().__init__(
(EngineCore_DP0 pid=8041)   File "/vllm-workspace/vllm/vllm/v1/engine/core.py", line 102, in __init__
(EngineCore_DP0 pid=8041)     self.model_executor = executor_class(vllm_config)
(EngineCore_DP0 pid=8041)                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
(EngineCore_DP0 pid=8041)   File "/vllm-workspace/vllm/vllm/v1/executor/multiproc_executor.py", line 97, in __init__
(EngineCore_DP0 pid=8041)     super().__init__(vllm_config)
(EngineCore_DP0 pid=8041)   File "/vllm-workspace/vllm/vllm/v1/executor/abstract.py", line 101, in __init__
(EngineCore_DP0 pid=8041)     self._init_executor()
(EngineCore_DP0 pid=8041)   File "/vllm-workspace/vllm/vllm/v1/executor/multiproc_executor.py", line 172, in _init_executor
(EngineCore_DP0 pid=8041)     self.workers = WorkerProc.wait_for_ready(unready_workers)
(EngineCore_DP0 pid=8041)                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(EngineCore_DP0 pid=8041)   File "/vllm-workspace/vllm/vllm/v1/executor/multiproc_executor.py", line 660, in wait_for_ready
(EngineCore_DP0 pid=8041)     raise e from None
(EngineCore_DP0 pid=8041) Exception: WorkerProc initialization failed due to an exception in a background process. See stack trace for root cause.
(APIServer pid=7658) Traceback (most recent call last):
(APIServer pid=7658)   File "/usr/local/python3.11.13/bin/vllm", line 7, in <module>
(APIServer pid=7658)     sys.exit(main())
(APIServer pid=7658)              ^^^^^^
(APIServer pid=7658)   File "/vllm-workspace/vllm/vllm/entrypoints/cli/main.py", line 73, in main
(APIServer pid=7658)     args.dispatch_function(args)
(APIServer pid=7658)   File "/vllm-workspace/vllm/vllm/entrypoints/cli/serve.py", line 60, in cmd
(APIServer pid=7658)     uvloop.run(run_server(args))
(APIServer pid=7658)   File "/usr/local/python3.11.13/lib/python3.11/site-packages/uvloop/__init__.py", line 92, in run
(APIServer pid=7658)     return runner.run(wrapper())
(APIServer pid=7658)            ^^^^^^^^^^^^^^^^^^^^^
(APIServer pid=7658)   File "/usr/local/python3.11.13/lib/python3.11/asyncio/runners.py", line 118, in run
(APIServer pid=7658)     return self._loop.run_until_complete(task)
(APIServer pid=7658)            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(APIServer pid=7658)   File "uvloop/loop.pyx", line 1518, in uvloop.loop.Loop.run_until_complete
(APIServer pid=7658)   File "/usr/local/python3.11.13/lib/python3.11/site-packages/uvloop/__init__.py", line 48, in wrapper
(APIServer pid=7658)     return await main
(APIServer pid=7658)            ^^^^^^^^^^
(APIServer pid=7658)   File "/vllm-workspace/vllm/vllm/entrypoints/openai/api_server.py", line 1398, in run_server
(APIServer pid=7658)     await run_server_worker(listen_address, sock, args, **uvicorn_kwargs)
(APIServer pid=7658)   File "/vllm-workspace/vllm/vllm/entrypoints/openai/api_server.py", line 1417, in run_server_worker
(APIServer pid=7658)     async with build_async_engine_client(
(APIServer pid=7658)   File "/usr/local/python3.11.13/lib/python3.11/contextlib.py", line 210, in __aenter__
(APIServer pid=7658)     return await anext(self.gen)
(APIServer pid=7658)            ^^^^^^^^^^^^^^^^^^^^^
(APIServer pid=7658)   File "/vllm-workspace/vllm/vllm/entrypoints/openai/api_server.py", line 172, in build_async_engine_client
(APIServer pid=7658)     async with build_async_engine_client_from_engine_args(
(APIServer pid=7658)   File "/usr/local/python3.11.13/lib/python3.11/contextlib.py", line 210, in __aenter__
(APIServer pid=7658)     return await anext(self.gen)
(APIServer pid=7658)            ^^^^^^^^^^^^^^^^^^^^^
(APIServer pid=7658)   File "/vllm-workspace/vllm/vllm/entrypoints/openai/api_server.py", line 213, in build_async_engine_client_from_engine_args
(APIServer pid=7658)     async_llm = AsyncLLM.from_vllm_config(
(APIServer pid=7658)                 ^^^^^^^^^^^^^^^^^^^^^^^^^^
(APIServer pid=7658)   File "/vllm-workspace/vllm/vllm/v1/engine/async_llm.py", line 215, in from_vllm_config
(APIServer pid=7658)     return cls(
(APIServer pid=7658)            ^^^^
(APIServer pid=7658)   File "/vllm-workspace/vllm/vllm/v1/engine/async_llm.py", line 134, in __init__
(APIServer pid=7658)     self.engine_core = EngineCoreClient.make_async_mp_client(
(APIServer pid=7658)                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(APIServer pid=7658)   File "/vllm-workspace/vllm/vllm/v1/engine/core_client.py", line 120, in make_async_mp_client
(APIServer pid=7658)     return DPLBAsyncMPClient(*client_args)
(APIServer pid=7658)            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(APIServer pid=7658)   File "/vllm-workspace/vllm/vllm/v1/engine/core_client.py", line 1192, in __init__
(APIServer pid=7658)     super().__init__(
(APIServer pid=7658)   File "/vllm-workspace/vllm/vllm/v1/engine/core_client.py", line 1033, in __init__
(APIServer pid=7658)     super().__init__(
(APIServer pid=7658)   File "/vllm-workspace/vllm/vllm/v1/engine/core_client.py", line 820, in __init__
(APIServer pid=7658)     super().__init__(
(APIServer pid=7658)   File "/vllm-workspace/vllm/vllm/v1/engine/core_client.py", line 477, in __init__
(APIServer pid=7658)     with launch_core_engines(vllm_config, executor_class, log_stats) as (
(APIServer pid=7658)   File "/usr/local/python3.11.13/lib/python3.11/contextlib.py", line 144, in __exit__
(APIServer pid=7658)     next(self.gen)
(APIServer pid=7658)   File "/vllm-workspace/vllm/vllm/v1/engine/utils.py", line 903, in launch_core_engines
(APIServer pid=7658)     wait_for_engine_startup(
(APIServer pid=7658)   File "/vllm-workspace/vllm/vllm/v1/engine/utils.py", line 960, in wait_for_engine_startup
(APIServer pid=7658)     raise RuntimeError(
(APIServer pid=7658) RuntimeError: Engine core initialization failed. See root cause above. Failed core proc(s): {}
(APIServer pid=7658) [ERROR] 2026-01-09-10:22:06 (PID:7658, Device:-1, RankID:-1) ERR99999 UNKNOWN applicaiton exception
/usr/local/python3.11.13/lib/python3.11/multiprocessing/resource_tracker.py:254: UserWarning: resource_tracker: There appear to be 9 leaked shared_memory objects to clean up at shutdown
```

**Comment by gao12312** [comment]
this bug is  the pr   from https://github.com/vllm-project/vllm-ascend/pull/3532 , which using self.ep_group._get_backend(torch.device("npu"))  in  token_dispatcher.py  ,  however it can cause the  HCCL function problem in MOE and  i have fixed it and  later provide pr

**Comment by Yikun** [comment]
@gao12312 Any progress? 

also cc @wangxiyuan Looks like some thing we need to land in v0.14.0

**Comment by wangxiyuan** [comment]
So you mean that when set `VLLM_ASCEND_ENABLE_FUSED_MC2=1`, the error is raised, right? We'd like to reproduce this first.

**Comment by barcklist** [comment]
When I pull multiple nodes to deploy multiple 235b instances at once, I also encounter this issue, and it happens very frequently. However, fortunately, this problem can currently be resolved by re-pulling. The image I'm using is 0.11.0rc1

**Comment by barcklist** [comment]
If the number of nodes you pull up is relatively small, this issue seems to occur rarely. However, if you pull up a large number of nodes, this problem will appear frequently. It's very easy to reproduce

**Comment by Angazenn** [comment]
@gao12312 Since your node0 script does not include `--quantization ascend` (which is required to run a quantized model on ascend hardware), we're not sure whether the scripts you provided here are sufficient to reproduce the bug. If you still have any problems on this, can you provide more information on how to reproduce this bug?

**Comment by gao12312** [comment]
@Angazenn @Yikun @wangxiyuan  The problem seems have already fixed when i  use main branch to deploy


<details>
<summary>The output of `python collect_env.py`</summary>

```
Collecting environment information...
PyTorch version: 2.8.0+cpu
Is debug build: False

OS: Ubuntu 22.04.5 LTS (aarch64)
GCC version: (Ubuntu 11.4.0-1ubuntu1~22.04.2) 11.4.0
Clang version: Could not collect
CMake version: version 4.2.1
Libc version: glibc-2.35

Python version: 3.11.13 (main, Nov 20 2025, 16:02:27) [GCC 11.4.0] (64-bit runtime)
Python platform: Linux-4.19.90-2107.6.0.0251.43.oe1.bclinux.aarch64-aarch64-with-glibc2.35

CPU:
Architecture:                       aarch64
CPU op-mode(s):                     64-bit
Byte Order:                         Little Endian
CPU(s):                             192
On-line CPU(s) list:                0-191
Vendor ID:                          HiSilicon
Model name:                         Kunpeng-920
Model:                              0
Thread(s) per core:                 1
Core(s) per cluster:                48
Socket(s):                          -
Cluster(s):                         4
Stepping:                           0x1
BogoMIPS:                           200.00
Flags:                              fp asimd evtstrm aes pmull sha1 sha2 crc32 atomics fphp asimdhp cpuid asimdrdm jscvt fcma dcpop asimddp asimdfhm ssbs
L1d cache:                          12 MiB (192 instances)
L1i cache:                          12 MiB (192 instances)
L2 cache:                           96 MiB (192 instances)
L3 cache:                           192 MiB (8 instances)
NUMA node(s):                       8
NUMA node0 CPU(s):                  0-23
NUMA node1 CPU(s):                  24-47
NUMA node2 CPU(s):                  48-71
NUMA node3 CPU(s):                  72-95
NUMA node4 CPU(s):                  96-119
NUMA node5 CPU(s):                  120-143
NUMA node6 CPU(s):                  144-167
NUMA node7 CPU(s):                  168-191
Vulnerability Gather data sampling: Not affected
Vulnerability Itlb multihit:        Not affected
Vulnerability L1tf:                 Not affected
Vulnerability Mds:                  Not affected
Vulnerability Meltdown:             Not affected
Vulnerability Mmio stale data:      Not affected
Vulnerability Retbleed:             Not affected
Vulnerability Spec store bypass:    Mitigation; Speculative Store Bypass disabled via prctl
Vulnerability Spectre v1:           Mitigation; __user pointer sanitization
Vulnerability Spectre v2:           Not affected
Vulnerability Srbds:                Not affected
Vulnerability Tsx async abort:      Not affected

Versions of relevant libraries:
[pip3] numpy==1.26.4
[pip3] pyzmq==27.1.0
[pip3] torch==2.8.0+cpu
[pip3] torch_npu==2.8.0
[pip3] torchvision==0.23.0
[pip3] transformers==4.57.3
[conda] Could not collect
vLLM Version: 0.13.0
vLLM Ascend Version: 0.13.0rc2.dev286+g38edfd585.d20260122 (git sha: 38edfd585, date: 20260122)

ENV Variables:
ATB_OPSRUNNER_KERNEL_CACHE_LOCAL_COUNT=1
ATB_STREAM_SYNC_EVERY_RUNNER_ENABLE=0
ATB_OPSRUNNER_SETUP_CACHE_ENABLE=1
ATB_WORKSPACE_MEM_ALLOC_GLOBAL=1
ATB_DEVICE_TILING_BUFFER_BLOCK_NUM=32
ASCEND_VISIBLE_DEVICES=6,7,0,1,2,3,4,5
ATB_STREAM_SYNC_EVERY_KERNEL_ENABLE=0
ASCEND_RUNTIME_OPTIONS=
ATB_OPSRUNNER_KERNEL_CACHE_GLOABL_COUNT=5
ATB_HOME_PATH=/usr/local/Ascend/nnal/atb/latest/atb/cxx_abi_1
ASCEND_TOOLKIT_HOME=/usr/local/Ascend/ascend-toolkit/latest
ATB_COMPARE_TILING_EVERY_KERNEL=0
ASCEND_OPP_PATH=/usr/local/Ascend/ascend-toolkit/latest/opp
LD_LIBRARY_PATH=/usr/local/Ascend/nnal/atb/latest/atb/cxx_abi_1/lib:/usr/local/Ascend/nnal/atb/latest/atb/cxx_abi_1/examples:/usr/local/Ascend/nnal/atb/latest/atb/cxx_abi_1/tests/atbopstest:/usr/local/Ascend/ascend-toolkit/latest/tools/aml/lib64:/usr/local/Ascend/ascend-toolkit/latest/tools/aml/lib64/plugin:/usr/local/Ascend/ascend-toolkit/latest/lib64:/usr/local/Ascend/ascend-toolkit/latest/lib64/plugin/opskernel:/usr/local/Ascend/ascend-toolkit/latest/lib64/plugin/nnengine:/usr/local/Ascend/ascend-toolkit/latest/opp/built-in/op_impl/ai_core/tbe/op_tiling/lib/linux/aarch64:/usr/local/Ascend/nnal/atb/latest/atb/cxx_abi_0/lib:/usr/local/Ascend/nnal/atb/latest/atb/cxx_abi_0/examples:/usr/local/Ascend/nnal/atb/latest/atb/cxx_abi_0/tests/atbopstest:/usr/local/Ascend/ascend-toolkit/latest/tools/aml/lib64:/usr/local/Ascend/ascend-toolkit/latest/tools/aml/lib64/plugin:/usr/local/Ascend/ascend-toolkit/latest/lib64:/usr/local/Ascend/ascend-toolkit/latest/lib64/plugin/opskernel:/usr/local/Ascend/ascend-toolkit/latest/lib64/plugin/nnengine:/usr/local/Ascend/ascend-toolkit/latest/opp/built-in/op_impl/ai_core/tbe/op_tiling:/usr/local/Ascend/driver/lib64/common/:/usr/local/Ascend/driver/lib64/driver/:
ASCEND_AICPU_PATH=/usr/local/Ascend/ascend-toolkit/latest
ATB_STREAM_SYNC_EVERY_OPERATION_ENABLE=0
ASCEND_HOME_PATH=/usr/local/Ascend/ascend-toolkit/latest
ATB_MATMUL_SHUFFLE_K_ENABLE=1
ATB_WORKSPACE_MEM_ALLOC_ALG_TYPE=1
ATB_HOST_TILING_BUFFER_BLOCK_NUM=128
ATB_SHARE_MEMORY_NAME_SUFFIX=
TORCH_DEVICE_BACKEND_AUTOLOAD=1
PYTORCH_NVML_BASED_CUDA_CHECK=1
TORCHINDUCTOR_COMPILE_THREADS=1


NPU:
+------------------------------------------------------------------------------------------------+
| npu-smi 25.2.0                   Version: 25.2.0                                               |
+---------------------------+---------------+----------------------------------------------------+
| NPU   Name                | Health        | Power(W)    Temp(C)           Hugepages-Usage(page)|
| Chip                      | Bus-Id        | AICore(%)   Memory-Usage(MB)  HBM-Usage(MB)        |
+===========================+===============+====================================================+
| 0     910B2               | OK            | 92.6        40                0    / 0             |
| 0                         | 0000:C1:00.0  | 0           0    / 0          3421 / 65536         |
+===========================+===============+====================================================+
| 1     910B2               | OK            | 94.6        37                0    / 0             |
| 0                         | 0000:C2:00.0  | 0           0    / 0          3416 / 65536         |
+===========================+===============+====================================================+
| 2     910B2               | OK            | 89.8        37                0    / 0             |
| 0                         | 0000:81:00.0  | 0           0    / 0          3416 / 65536         |
+===========================+===============+====================================================+
| 3     910B2               | OK            | 91.8        38                0    / 0             |
| 0                         | 0000:82:00.0  | 0           0    / 0          3415 / 65536         |
+===========================+===============+====================================================+
| 4     910B2               | OK            | 89.6        41                0    / 0             |
| 0                         | 0000:01:00.0  | 0           0    / 0          3416 / 65536         |
+===========================+===============+====================================================+
| 5     910B2               | OK            | 94.7        41                0    / 0             |
| 0                         | 0000:02:00.0  | 0           0    / 0          3414 / 65536         |
+===========================+===============+====================================================+
| 6     910B2               | OK            | 95.4        42                0    / 0             |
| 0                         | 0000:41:00.0  | 0           0    / 0          3416 / 65536         |
+===========================+===============+====================================================+
| 7     910B2               | OK            | 88.1        40                0    / 0             |
| 0                         | 0000:42:00.0  | 0           0    / 0          3414 / 65536         |
+===========================+===============+====================================================+
+---------------------------+---------------+----------------------------------------------------+
| NPU     Chip              | Process id    | Process name             | Process memory(MB)      |
+===========================+===============+====================================================+
| No running processes found in NPU 0                                                            |
+===========================+===============+====================================================+
| No running processes found in NPU 1                                                            |
+===========================+===============+====================================================+
| No running processes found in NPU 2                                                            |
+===========================+===============+====================================================+
| No running processes found in NPU 3                                                            |
+===========================+===============+====================================================+
| No running processes found in NPU 4                                                            |
+===========================+===============+====================================================+
| No running processes found in NPU 5                                                            |
+===========================+===============+====================================================+
| No running processes found in NPU 6                                                            |
+===========================+===============+====================================================+
| No running processes found in NPU 7                                                            |
+===========================+===============+====================================================+

CANN:
package_name=Ascend-cann-toolkit
version=8.3.RC2
innerversion=V100R001C23SPC002B210
compatible_version=[V100R001C15],[V100R001C18],[V100R001C19],[V100R001C20],[V100R001C21],[V100R001C23]
arch=aarch64
os=linux
path=/usr/local/Ascend/ascend-toolkit/8.3.RC2/aarch64-linux
```

</details>

```python

NODE0:

#!/bin/sh

nic_name="XXX"
local_ip="XXX"

export VLLM_USE_MODELSCOPE=True
export HCCL_IF_IP=$local_ip
export GLOO_SOCKET_IFNAME=$nic_name
export TP_SOCKET_IFNAME=$nic_name
export HCCL_SOCKET_IFNAME=$nic_name
export HCCL_CONNECT_TIMEOUT=1200
export OMP_PROC_BIND=false
export OMP_NUM_THREADS=1
export VLLM_USE_V1=1
export HCCL_BUFFSIZE=1024
export PYTORCH_NPU_ALLOC_CONF=expandable_segments:True
export HCCL_OP_EXPANSION_MODE="AIV"
export TASK_QUEUE_ENABLE=1
export CPU_AFFINITY_CONF=2

vllm serve /workspace/cache/aiops-sh2/models/Qwen3-Coder-480B-A35B-Instruct-w8a8-QuaRot \
--host 0.0.0.0 \
--port 8000 \
--data-parallel-size 2 \
--data-parallel-size-local 1 \
--data-parallel-address $local_ip \
--data-parallel-rpc-port 13389 \
--seed 1024 \
--served-model-name qwen3_coder \
--enable-expert-parallel \
--tensor-parallel-size 8 \
--max-num-seqs 16 \
--max-model-len 32768 \
--max-num-batched-tokens 8192 \
--trust-remote-code \
--quantization ascend \
--gpu-memory-utilization 0.9 \
--async-scheduling \
--no-enable-prefix-caching \
--compilation-config '{"cudagraph_mode":"FULL_DECODE_ONLY"}'

NODE1:

#!/bin/sh

nic_name="XXX"
local_ip="XXX"
node0_ip="XXX"

export HCCL_IF_IP=$local_ip
export GLOO_SOCKET_IFNAME=$nic_name
export TP_SOCKET_IFNAME=$nic_name
export HCCL_SOCKET_IFNAME=$nic_name
export HCCL_CONNECT_TIMEOUT=1200
export VLLM_USE_MODELSCOPE=True
export OMP_PROC_BIND=false
export OMP_NUM_THREADS=1
export VLLM_USE_V1=1
export HCCL_BUFFSIZE=1024
export PYTORCH_NPU_ALLOC_CONF=expandable_segments:True
export HCCL_OP_EXPANSION_MODE="AIV"
export TASK_QUEUE_ENABLE=1
export CPU_AFFINITY_CONF=2

vllm serve /workspace/cache/aiops-sh2/models/Qwen3-Coder-480B-A35B-Instruct-w8a8-QuaRot \
--host 0.0.0.0 \
--port 8000 \
--headless \
--data-parallel-size 2 \
--data-parallel-size-local 1 \
--data-parallel-start-rank 1 \
--data-parallel-address $node0_ip \
--data-parallel-rpc-port 13389 \
--seed 1024 \
--tensor-parallel-size 8 \
--served-model-name qwen3-coder \
--quantization ascend \
--enable-expert-parallel \
--max-num-seqs 16 \
--max-model-len 32768 \
--max-num-batched-tokens 8192 \
--tool-call-parser qwen3_coder \
--gpu-memory-utilization 0.9 \
--async-scheduling \
--no-enable-prefix-caching \
--compilation-config '{"cudagraph_mode":"FULL_DECODE_ONLY"}'



```

**Comment by barcklist** [comment]
I also encountered an issue where, when using Ascend 910B4 and enabling prefix-cache, an "Out of NPU memory" error occurs after a period of inference (usually 5-6 hours). I strongly suspect that this is due to a memory leak introduced by prefix-cache, and I hope this issue can be confirmed and resolved in v0.14.0rc1. Currently, this problem can be alleviated by reducing the "gpu-memory-utilization" setting, but it cannot be completely fixed.

**Comment by barcklist** [comment]
The issue has been resolved in the main branch.
