### ISSUE TITLE
[Bug]: 单机910B4 8卡部署Qwen2.5 30B模型，vllm ascend 版本0.12.0.rc1，开启full decode only出现crash

### ISSUE THREAD

**Issue by jiager-npu** [vllm-project/vllm-ascend#6018]
### Your current environment

<details>
<summary>
CANN ： 8.3.rc2
torch_npu: 2.8.0
vllm: 0.12.0
vllm-ascend 0.12.0.rc2
昇腾环境910B4
</summary>
</details>

### 🐛 Describe the bug

并发压测出现报错码507011
plog报错：
[ERROR] RUNTIME(129510,all__):2026-01-20-09:48:14.622.900 [stars_engine.cc:1502]133843 ProcLogicCqReport:Task run failed, device_id=5, stream_id=1206, task_id=8029, sqe_type=7(notify wait), errType=0x20(sq sw status error), sqSwStatus=0x14db0028
[ERROR] RUNTIME(129510,all__):2026-01-20-09:48:14.623.842 [device_error_core_proc.cc:333]133843 ProcessStarsCoreErrorInfo:report error module_type=5, module_name=EZ9999
[ERROR] RUNTIME(129510,all__):2026-01-20-09:48:14.623.865 [device_error_core_proc.cc:333]133843 ProcessStarsCoreErrorInfo:The error from device(chipId:5, dieId:0), serial number is 59, there is an exception of fftsplus aivector error, core id is 8, error code = 0x10, dump info: pc start: 0x12c86e31cb04, current: 0x12c86e31dab0, vec error info: 0xf210372c02, mte error info: 0x7f060000d0, ifu error info: 0x14ee645804840, ccu error info: 0x7fff7fff3b0000a0, cube error info: 0, biu error info: 0, aic error mask: 0x6500020bd00028c, para base: 0x12c11fe3f000.
[ERROR] RUNTIME(129510,all__):2026-01-20-09:48:14.623.975 [device_error_core_proc.cc:353]133843 ProcessStarsCoreErrorInfo:report error module_type=5, module_name=EZ9999
[ERROR] RUNTIME(129510,all__):2026-01-20-09:48:14.623.980 [device_error_core_proc.cc:353]133843 ProcessStarsCoreErrorInfo:The extend info: errcode:(0x10, 0, 0) errorStr: Illegal instruction, which is usually caused by unaligned UUB addresses. fixp_error0 info: 0x60000d0, fixp_error1 info: 0x7f, fsmId:0, tslot:7, thread:0, ctxid:0, blk:17, sublk:0, subErrType:4.
[ERROR] RUNTIME(129510,all__):2026-01-20-09:48:14.623.997 [device_error_core_proc.cc:369]133843 ProcessStarsCoreErrorInfo:mte error, devId=5, streamId=1243, taskId=40, errorCode=0.
[ERROR] RUNTIME(129510,all__):2026-01-20-09:48:14.624.006 [stream.cc:3285]133843 EnterFailureAbort:stream_id=1206 enter failure abort.
[ERROR] RUNTIME(129510,all__):2026-01-20-09:48:14.624.017 [stream.cc:1188]133843 GetError:Stream Synchronize failed, stream_id=1206, retCode=0x91, [the model stream execute failed].
[ERROR] RUNTIME(129510,all__):2026-01-20-09:48:14.624.021 [model_execute_task_info.cc:593]133843 ReportErrorInfoForModelExecuteTask:model execute error, retCode=0x91, [the model stream execute failed].
[ERROR] RUNTIME(129510,all__):2026-01-20-09:48:14.624.046 [model_execute_task_info.cc:551]133843 PrintErrorInfoForModelExecuteTask:stream_id=1206, task_id=8028, sqVirtualAddr=0, head equal tail flag=0.
[ERROR] RUNTIME(129510,all__):2026-01-20-09:48:14.624.050 [model_execute_task_info.cc:507]133843 PrintErrorModelExecuteTaskFuncCall:funcCallSvmMem=0x124a00ba5000, funCallMemSize=480.

**Comment by jiager-npu** [comment]
tensor_parallel_size": 8,
"data_parallel_size": 1,
 "data_parallel_backend": "ray",
 "distributed_executor_backend": "ray",
 "max_model_len": 32768,
"max_input_tokens":  32768,
 "async_scheduling": false,
 "compilation_config": {
  "cudagraph_capture_sizes": [1, 8, 16],
 "cudagraph_mode": "FULL_DECODE_ONLY"
},
 "max_num_seqs": 16,
 "max_num_batched_tokens": 4096
在并发压测为8的时候出现崩溃

**Comment by zhoux77899** [comment]
@jiager-npu This issue has been resolved in the latest version. Please use the latest release or rc version (https://github.com/vllm-project/vllm-ascend/releases). If the issue persists, feel free to submit a new issue.
