### ISSUE TITLE
[Bug]: 使用vllm-ascend v0.11.0镜像在线服务遇到崩溃退出：ERR00100 PTA call acl api failed

### ISSUE THREAD

**Issue by liuzb0** [vllm-project/vllm-ascend#6190]
### Your current environment

<details>
<summary>The output of `python collect_env.py`</summary>

```text

卡型号 | 驱动 | D910B-376t | 7.5.0.5.220-24.1.0.3

```

</details>

### 🐛 Describe the bug

启动命令：
```shell
vllm serve \
    /path/to/Qwen3-Coder-30B-A3B-Instruct \
    --served-model-name Qwen3-Coder \
    -tp 4 \
    --max-model-len 65536 \
    --max-num-seqs 256 \
    --gpu-memory-utilization 0.85 \
    --enable-auto-tool-choice \
    --tool-call-parser qwen3_xml
```
服务运行97hours出现错误，服务崩溃，复现条件无法确定

关键堆栈：
```
(Worker_TP1 pid=416) ERROR 01-16 11:51:23 [multiproc_executor.py:671] WorkerProc hit an exception.
(Worker_TP1 pid=416) ERROR 01-16 11:51:23 [multiproc_executor.py:671] Traceback (most recent call last):
(Worker_TP1 pid=416) ERROR 01-16 11:51:23 [multiproc_executor.py:671]   File "/vllm-workspace/vllm/vllm/v1/executor/multiproc_executor.py", line 666, in worker_busy_loop
(Worker_TP1 pid=416) ERROR 01-16 11:51:23 [multiproc_executor.py:671]     output = func(*args, **kwargs)
(Worker_TP1 pid=416) ERROR 01-16 11:51:23 [multiproc_executor.py:671]              ^^^^^^^^^^^^^^^^^^^^^
(Worker_TP1 pid=416) ERROR 01-16 11:51:23 [multiproc_executor.py:671]   File "/vllm-workspace/vllm-ascend/vllm_ascend/worker/worker_v1.py", line 254, in execute_model
(Worker_TP1 pid=416) ERROR 01-16 11:51:23 [multiproc_executor.py:671]     output = self.model_runner.execute_model(scheduler_output,
(Worker_TP1 pid=416) ERROR 01-16 11:51:23 [multiproc_executor.py:671]              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(Worker_TP1 pid=416) ERROR 01-16 11:51:23 [multiproc_executor.py:671]   File "/usr/local/python3.11.13/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
(Worker_TP1 pid=416) ERROR 01-16 11:51:23 [multiproc_executor.py:671]     return func(*args, **kwargs)
(Worker_TP1 pid=416) ERROR 01-16 11:51:23 [multiproc_executor.py:671]            ^^^^^^^^^^^^^^^^^^^^^
(Worker_TP1 pid=416) ERROR 01-16 11:51:23 [multiproc_executor.py:671]   File "/vllm-workspace/vllm-ascend/vllm_ascend/worker/model_runner_v1.py", line 2030, in execute_model
(Worker_TP1 pid=416) ERROR 01-16 11:51:23 [multiproc_executor.py:671]     sampler_output = self.sampler(
(Worker_TP1 pid=416) ERROR 01-16 11:51:23 [multiproc_executor.py:671]                      ^^^^^^^^^^^^^
(Worker_TP1 pid=416) ERROR 01-16 11:51:23 [multiproc_executor.py:671]   File "/usr/local/python3.11.13/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
(Worker_TP1 pid=416) ERROR 01-16 11:51:23 [multiproc_executor.py:671]     return self._call_impl(*args, **kwargs)
(Worker_TP1 pid=416) ERROR 01-16 11:51:23 [multiproc_executor.py:671]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(Worker_TP1 pid=416) ERROR 01-16 11:51:23 [multiproc_executor.py:671]   File "/usr/local/python3.11.13/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1762, in _call_impl
(Worker_TP1 pid=416) ERROR 01-16 11:51:23 [multiproc_executor.py:671]     return forward_call(*args, **kwargs)
(Worker_TP1 pid=416) ERROR 01-16 11:51:23 [multiproc_executor.py:671]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(Worker_TP1 pid=416) ERROR 01-16 11:51:23 [multiproc_executor.py:671]   File "/vllm-workspace/vllm/vllm/v1/sample/sampler.py", line 100, in forward
(Worker_TP1 pid=416) ERROR 01-16 11:51:23 [multiproc_executor.py:671]     sampled, processed_logprobs = self.sample(logits, sampling_metadata)
(Worker_TP1 pid=416) ERROR 01-16 11:51:23 [multiproc_executor.py:671]                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(Worker_TP1 pid=416) ERROR 01-16 11:51:23 [multiproc_executor.py:671]   File "/vllm-workspace/vllm/vllm/v1/sample/sampler.py", line 180, in sample
(Worker_TP1 pid=416) ERROR 01-16 11:51:23 [multiproc_executor.py:671]     random_sampled, processed_logprobs = self.topk_topp_sampler(
(Worker_TP1 pid=416) ERROR 01-16 11:51:23 [multiproc_executor.py:671]                                          ^^^^^^^^^^^^^^^^^^^^^^^
(Worker_TP1 pid=416) ERROR 01-16 11:51:23 [multiproc_executor.py:671]   File "/usr/local/python3.11.13/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
(Worker_TP1 pid=416) ERROR 01-16 11:51:23 [multiproc_executor.py:671]     return self._call_impl(*args, **kwargs)
(Worker_TP1 pid=416) ERROR 01-16 11:51:23 [multiproc_executor.py:671]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(Worker_TP1 pid=416) ERROR 01-16 11:51:23 [multiproc_executor.py:671]   File "/usr/local/python3.11.13/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1762, in _call_impl
(Worker_TP1 pid=416) ERROR 01-16 11:51:23 [multiproc_executor.py:671]     return forward_call(*args, **kwargs)
(Worker_TP1 pid=416) ERROR 01-16 11:51:23 [multiproc_executor.py:671]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(Worker_TP1 pid=416) ERROR 01-16 11:51:23 [multiproc_executor.py:671]   File "/vllm-workspace/vllm-ascend/vllm_ascend/sample/sampler.py", line 70, in forward_native
(Worker_TP1 pid=416) ERROR 01-16 11:51:23 [multiproc_executor.py:671]     logits = self._apply_top_k_top_p(logits, k, p)
(Worker_TP1 pid=416) ERROR 01-16 11:51:23 [multiproc_executor.py:671]              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(Worker_TP1 pid=416) ERROR 01-16 11:51:23 [multiproc_executor.py:671]   File "/vllm-workspace/vllm-ascend/vllm_ascend/sample/sampler.py", line 32, in _apply_top_k_top_p
(Worker_TP1 pid=416) ERROR 01-16 11:51:23 [multiproc_executor.py:671]     if not is_310p() and p is not None and k is not None and 1 <= int(
(Worker_TP1 pid=416) ERROR 01-16 11:51:23 [multiproc_executor.py:671]                                                                   ^^^^
(Worker_TP1 pid=416) ERROR 01-16 11:51:23 [multiproc_executor.py:671] RuntimeError: The Inner error is reported as above. The process exits for this inner error, and the current working operator name is aclnnMatmul.
(Worker_TP1 pid=416) ERROR 01-16 11:51:23 [multiproc_executor.py:671] Since the operator is called asynchronously, the stacktrace may be inaccurate. If you want to get the accurate stacktrace, please set the environment variable ASCEND_LAUNCH_BLOCKING=1.
(Worker_TP1 pid=416) ERROR 01-16 11:51:23 [multiproc_executor.py:671] Note: ASCEND_LAUNCH_BLOCKING=1 will force ops to run in synchronous mode, resulting in performance degradation. Please unset ASCEND_LAUNCH_BLOCKING in time after debugging.
(Worker_TP1 pid=416) ERROR 01-16 11:51:23 [multiproc_executor.py:671] [ERROR] 2026-01-16-11:51:23 (PID:416, Device:1, RankID:-1) ERR00100 PTA call acl api failed.
(Worker_TP1 pid=416) ERROR 01-16 11:51:23 [multiproc_executor.py:671] 
(Worker_TP1 pid=416) ERROR 01-16 11:51:23 [multiproc_executor.py:671] Traceback (most recent call last):
(Worker_TP1 pid=416) ERROR 01-16 11:51:23 [multiproc_executor.py:671]   File "/vllm-workspace/vllm/vllm/v1/executor/multiproc_executor.py", line 666, in worker_busy_loop
(Worker_TP1 pid=416) ERROR 01-16 11:51:23 [multiproc_executor.py:671]     output = func(*args, **kwargs)
(Worker_TP1 pid=416) ERROR 01-16 11:51:23 [multiproc_executor.py:671]              ^^^^^^^^^^^^^^^^^^^^^
(Worker_TP1 pid=416) ERROR 01-16 11:51:23 [multiproc_executor.py:671]   File "/vllm-workspace/vllm-ascend/vllm_ascend/worker/worker_v1.py", line 254, in execute_model
(Worker_TP1 pid=416) ERROR 01-16 11:51:23 [multiproc_executor.py:671]     output = self.model_runner.execute_model(scheduler_output,
(Worker_TP1 pid=416) ERROR 01-16 11:51:23 [multiproc_executor.py:671]              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(Worker_TP1 pid=416) ERROR 01-16 11:51:23 [multiproc_executor.py:671]   File "/usr/local/python3.11.13/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
(Worker_TP1 pid=416) ERROR 01-16 11:51:23 [multiproc_executor.py:671]     return func(*args, **kwargs)
(Worker_TP1 pid=416) ERROR 01-16 11:51:23 [multiproc_executor.py:671]            ^^^^^^^^^^^^^^^^^^^^^
(Worker_TP1 pid=416) ERROR 01-16 11:51:23 [multiproc_executor.py:671]   File "/vllm-workspace/vllm-ascend/vllm_ascend/worker/model_runner_v1.py", line 2030, in execute_model
(Worker_TP1 pid=416) ERROR 01-16 11:51:23 [multiproc_executor.py:671]     sampler_output = self.sampler(
(Worker_TP1 pid=416) ERROR 01-16 11:51:23 [multiproc_executor.py:671]                      ^^^^^^^^^^^^^
(Worker_TP1 pid=416) ERROR 01-16 11:51:23 [multiproc_executor.py:671]   File "/usr/local/python3.11.13/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
(Worker_TP1 pid=416) ERROR 01-16 11:51:23 [multiproc_executor.py:671]     return self._call_impl(*args, **kwargs)
(Worker_TP1 pid=416) ERROR 01-16 11:51:23 [multiproc_executor.py:671]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(Worker_TP1 pid=416) ERROR 01-16 11:51:23 [multiproc_executor.py:671]   File "/usr/local/python3.11.13/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1762, in _call_impl
(Worker_TP1 pid=416) ERROR 01-16 11:51:23 [multiproc_executor.py:671]     return forward_call(*args, **kwargs)
(Worker_TP1 pid=416) ERROR 01-16 11:51:23 [multiproc_executor.py:671]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(Worker_TP1 pid=416) ERROR 01-16 11:51:23 [multiproc_executor.py:671]   File "/vllm-workspace/vllm/vllm/v1/sample/sampler.py", line 100, in forward
(Worker_TP1 pid=416) ERROR 01-16 11:51:23 [multiproc_executor.py:671]     sampled, processed_logprobs = self.sample(logits, sampling_metadata)
(Worker_TP1 pid=416) ERROR 01-16 11:51:23 [multiproc_executor.py:671]                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(Worker_TP1 pid=416) ERROR 01-16 11:51:23 [multiproc_executor.py:671]   File "/vllm-workspace/vllm/vllm/v1/sample/sampler.py", line 180, in sample
(Worker_TP1 pid=416) ERROR 01-16 11:51:23 [multiproc_executor.py:671]     random_sampled, processed_logprobs = self.topk_topp_sampler(
(Worker_TP1 pid=416) ERROR 01-16 11:51:23 [multiproc_executor.py:671]                                          ^^^^^^^^^^^^^^^^^^^^^^^
(Worker_TP1 pid=416) ERROR 01-16 11:51:23 [multiproc_executor.py:671]   File "/usr/local/python3.11.13/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
(Worker_TP1 pid=416) ERROR 01-16 11:51:23 [multiproc_executor.py:671]     return self._call_impl(*args, **kwargs)
(Worker_TP1 pid=416) ERROR 01-16 11:51:23 [multiproc_executor.py:671]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(Worker_TP1 pid=416) ERROR 01-16 11:51:23 [multiproc_executor.py:671]   File "/usr/local/python3.11.13/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1762, in _call_impl
(Worker_TP1 pid=416) ERROR 01-16 11:51:23 [multiproc_executor.py:671]     return forward_call(*args, **kwargs)
(Worker_TP1 pid=416) ERROR 01-16 11:51:23 [multiproc_executor.py:671]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(Worker_TP1 pid=416) ERROR 01-16 11:51:23 [multiproc_executor.py:671]   File "/vllm-workspace/vllm-ascend/vllm_ascend/sample/sampler.py", line 70, in forward_native
(Worker_TP1 pid=416) ERROR 01-16 11:51:23 [multiproc_executor.py:671]     logits = self._apply_top_k_top_p(logits, k, p)
(Worker_TP1 pid=416) ERROR 01-16 11:51:23 [multiproc_executor.py:671]              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(Worker_TP1 pid=416) ERROR 01-16 11:51:23 [multiproc_executor.py:671]   File "/vllm-workspace/vllm-ascend/vllm_ascend/sample/sampler.py", line 32, in _apply_top_k_top_p
(Worker_TP1 pid=416) ERROR 01-16 11:51:23 [multiproc_executor.py:671]     if not is_310p() and p is not None and k is not None and 1 <= int(
(Worker_TP1 pid=416) ERROR 01-16 11:51:23 [multiproc_executor.py:671]                                                                   ^^^^
(Worker_TP1 pid=416) ERROR 01-16 11:51:23 [multiproc_executor.py:671] RuntimeError: The Inner error is reported as above. The process exits for this inner error, and the current working operator name is aclnnMatmul.
(Worker_TP1 pid=416) ERROR 01-16 11:51:23 [multiproc_executor.py:671] Since the operator is called asynchronously, the stacktrace may be inaccurate. If you want to get the accurate stacktrace, please set the environment variable ASCEND_LAUNCH_BLOCKING=1.
(Worker_TP1 pid=416) ERROR 01-16 11:51:23 [multiproc_executor.py:671] Note: ASCEND_LAUNCH_BLOCKING=1 will force ops to run in synchronous mode, resulting in performance degradation. Please unset ASCEND_LAUNCH_BLOCKING in time after debugging.
(Worker_TP1 pid=416) ERROR 01-16 11:51:23 [multiproc_executor.py:671] [ERROR] 2026-01-16-11:51:23 (PID:416, Device:1, RankID:-1) ERR00100 PTA call acl api failed.
(Worker_TP1 pid=416) ERROR 01-16 11:51:23 [multiproc_executor.py:671] 
(Worker_TP1 pid=416) ERROR 01-16 11:51:23 [multiproc_executor.py:671] 
(Worker_TP0 pid=415) ERROR 01-16 11:51:23 [multiproc_executor.py:671] WorkerProc hit an exception.
(Worker_TP0 pid=415) ERROR 01-16 11:51:23 [multiproc_executor.py:671] Traceback (most recent call last):
(Worker_TP0 pid=415) ERROR 01-16 11:51:23 [multiproc_executor.py:671]   File "/vllm-workspace/vllm/vllm/v1/executor/multiproc_executor.py", line 666, in worker_busy_loop
(Worker_TP0 pid=415) ERROR 01-16 11:51:23 [multiproc_executor.py:671]     output = func(*args, **kwargs)
(Worker_TP0 pid=415) ERROR 01-16 11:51:23 [multiproc_executor.py:671]              ^^^^^^^^^^^^^^^^^^^^^
(Worker_TP0 pid=415) ERROR 01-16 11:51:23 [multiproc_executor.py:671]   File "/vllm-workspace/vllm-ascend/vllm_ascend/worker/worker_v1.py", line 254, in execute_model
(Worker_TP0 pid=415) ERROR 01-16 11:51:23 [multiproc_executor.py:671]     output = self.model_runner.execute_model(scheduler_output,
(Worker_TP0 pid=415) ERROR 01-16 11:51:23 [multiproc_executor.py:671]              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(Worker_TP0 pid=415) ERROR 01-16 11:51:23 [multiproc_executor.py:671]   File "/usr/local/python3.11.13/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
(Worker_TP0 pid=415) ERROR 01-16 11:51:23 [multiproc_executor.py:671]     return func(*args, **kwargs)
(Worker_TP0 pid=415) ERROR 01-16 11:51:23 [multiproc_executor.py:671]            ^^^^^^^^^^^^^^^^^^^^^
(Worker_TP0 pid=415) ERROR 01-16 11:51:23 [multiproc_executor.py:671]   File "/vllm-workspace/vllm-ascend/vllm_ascend/worker/model_runner_v1.py", line 2030, in execute_model
(Worker_TP0 pid=415) ERROR 01-16 11:51:23 [multiproc_executor.py:671]     sampler_output = self.sampler(
(Worker_TP0 pid=415) ERROR 01-16 11:51:23 [multiproc_executor.py:671]                      ^^^^^^^^^^^^^
(Worker_TP0 pid=415) ERROR 01-16 11:51:23 [multiproc_executor.py:671]   File "/usr/local/python3.11.13/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
(Worker_TP0 pid=415) ERROR 01-16 11:51:23 [multiproc_executor.py:671]     return self._call_impl(*args, **kwargs)
(Worker_TP0 pid=415) ERROR 01-16 11:51:23 [multiproc_executor.py:671]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(Worker_TP0 pid=415) ERROR 01-16 11:51:23 [multiproc_executor.py:671]   File "/usr/local/python3.11.13/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1762, in _call_impl
(Worker_TP0 pid=415) ERROR 01-16 11:51:23 [multiproc_executor.py:671]     return forward_call(*args, **kwargs)
(Worker_TP0 pid=415) ERROR 01-16 11:51:23 [multiproc_executor.py:671]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(Worker_TP0 pid=415) ERROR 01-16 11:51:23 [multiproc_executor.py:671]   File "/vllm-workspace/vllm/vllm/v1/sample/sampler.py", line 100, in forward
(Worker_TP0 pid=415) ERROR 01-16 11:51:23 [multiproc_executor.py:671]     sampled, processed_logprobs = self.sample(logits, sampling_metadata)
(Worker_TP0 pid=415) ERROR 01-16 11:51:23 [multiproc_executor.py:671]                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(Worker_TP0 pid=415) ERROR 01-16 11:51:23 [multiproc_executor.py:671]   File "/vllm-workspace/vllm/vllm/v1/sample/sampler.py", line 180, in sample
(Worker_TP0 pid=415) ERROR 01-16 11:51:23 [multiproc_executor.py:671]     random_sampled, processed_logprobs = self.topk_topp_sampler(
(Worker_TP0 pid=415) ERROR 01-16 11:51:23 [multiproc_executor.py:671]                                          ^^^^^^^^^^^^^^^^^^^^^^^
(Worker_TP0 pid=415) ERROR 01-16 11:51:23 [multiproc_executor.py:671]   File "/usr/local/python3.11.13/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
(Worker_TP0 pid=415) ERROR 01-16 11:51:23 [multiproc_executor.py:671]     return self._call_impl(*args, **kwargs)
(Worker_TP0 pid=415) ERROR 01-16 11:51:23 [multiproc_executor.py:671]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(Worker_TP0 pid=415) ERROR 01-16 11:51:23 [multiproc_executor.py:671]   File "/usr/local/python3.11.13/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1762, in _call_impl
(Worker_TP0 pid=415) ERROR 01-16 11:51:23 [multiproc_executor.py:671]     return forward_call(*args, **kwargs)
(Worker_TP0 pid=415) ERROR 01-16 11:51:23 [multiproc_executor.py:671]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(Worker_TP0 pid=415) ERROR 01-16 11:51:23 [multiproc_executor.py:671]   File "/vllm-workspace/vllm-ascend/vllm_ascend/sample/sampler.py", line 70, in forward_native
(Worker_TP0 pid=415) ERROR 01-16 11:51:23 [multiproc_executor.py:671]     logits = self._apply_top_k_top_p(logits, k, p)
(Worker_TP0 pid=415) ERROR 01-16 11:51:23 [multiproc_executor.py:671]              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(Worker_TP0 pid=415) ERROR 01-16 11:51:23 [multiproc_executor.py:671]   File "/vllm-workspace/vllm-ascend/vllm_ascend/sample/sampler.py", line 32, in _apply_top_k_top_p
(Worker_TP0 pid=415) ERROR 01-16 11:51:23 [multiproc_executor.py:671]     if not is_310p() and p is not None and k is not None and 1 <= int(
(Worker_TP0 pid=415) ERROR 01-16 11:51:23 [multiproc_executor.py:671]                                                                   ^^^^
(Worker_TP0 pid=415) ERROR 01-16 11:51:23 [multiproc_executor.py:671] RuntimeError: The Inner error is reported as above. The process exits for this inner error, and the current working operator name is aclnnRmsNorm.
(Worker_TP0 pid=415) ERROR 01-16 11:51:23 [multiproc_executor.py:671] Since the operator is called asynchronously, the stacktrace may be inaccurate. If you want to get the accurate stacktrace, please set the environment variable ASCEND_LAUNCH_BLOCKING=1.
(Worker_TP0 pid=415) ERROR 01-16 11:51:23 [multiproc_executor.py:671] Note: ASCEND_LAUNCH_BLOCKING=1 will force ops to run in synchronous mode, resulting in performance degradation. Please unset ASCEND_LAUNCH_BLOCKING in time after debugging.
(Worker_TP0 pid=415) ERROR 01-16 11:51:23 [multiproc_executor.py:671] [ERROR] 2026-01-16-11:51:23 (PID:415, Device:0, RankID:-1) ERR00100 PTA call acl api failed.
```

<details>

<summary>完整信息</summary>

```text
(Worker_TP1 pid=416) ERROR 01-16 11:51:23 [multiproc_executor.py:671] WorkerProc hit an exception.
(Worker_TP1 pid=416) ERROR 01-16 11:51:23 [multiproc_executor.py:671] Traceback (most recent call last):
(Worker_TP1 pid=416) ERROR 01-16 11:51:23 [multiproc_executor.py:671]   File "/vllm-workspace/vllm/vllm/v1/executor/multiproc_executor.py", line 666, in worker_busy_loop
(Worker_TP1 pid=416) ERROR 01-16 11:51:23 [multiproc_executor.py:671]     output = func(*args, **kwargs)
(Worker_TP1 pid=416) ERROR 01-16 11:51:23 [multiproc_executor.py:671]              ^^^^^^^^^^^^^^^^^^^^^
(Worker_TP1 pid=416) ERROR 01-16 11:51:23 [multiproc_executor.py:671]   File "/vllm-workspace/vllm-ascend/vllm_ascend/worker/worker_v1.py", line 254, in execute_model
(Worker_TP1 pid=416) ERROR 01-16 11:51:23 [multiproc_executor.py:671]     output = self.model_runner.execute_model(scheduler_output,
(Worker_TP1 pid=416) ERROR 01-16 11:51:23 [multiproc_executor.py:671]              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(Worker_TP1 pid=416) ERROR 01-16 11:51:23 [multiproc_executor.py:671]   File "/usr/local/python3.11.13/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
(Worker_TP1 pid=416) ERROR 01-16 11:51:23 [multiproc_executor.py:671]     return func(*args, **kwargs)
(Worker_TP1 pid=416) ERROR 01-16 11:51:23 [multiproc_executor.py:671]            ^^^^^^^^^^^^^^^^^^^^^
(Worker_TP1 pid=416) ERROR 01-16 11:51:23 [multiproc_executor.py:671]   File "/vllm-workspace/vllm-ascend/vllm_ascend/worker/model_runner_v1.py", line 2030, in execute_model
(Worker_TP1 pid=416) ERROR 01-16 11:51:23 [multiproc_executor.py:671]     sampler_output = self.sampler(
(Worker_TP1 pid=416) ERROR 01-16 11:51:23 [multiproc_executor.py:671]                      ^^^^^^^^^^^^^
(Worker_TP1 pid=416) ERROR 01-16 11:51:23 [multiproc_executor.py:671]   File "/usr/local/python3.11.13/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
(Worker_TP1 pid=416) ERROR 01-16 11:51:23 [multiproc_executor.py:671]     return self._call_impl(*args, **kwargs)
(Worker_TP1 pid=416) ERROR 01-16 11:51:23 [multiproc_executor.py:671]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(Worker_TP1 pid=416) ERROR 01-16 11:51:23 [multiproc_executor.py:671]   File "/usr/local/python3.11.13/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1762, in _call_impl
(Worker_TP1 pid=416) ERROR 01-16 11:51:23 [multiproc_executor.py:671]     return forward_call(*args, **kwargs)
(Worker_TP1 pid=416) ERROR 01-16 11:51:23 [multiproc_executor.py:671]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(Worker_TP1 pid=416) ERROR 01-16 11:51:23 [multiproc_executor.py:671]   File "/vllm-workspace/vllm/vllm/v1/sample/sampler.py", line 100, in forward
(Worker_TP1 pid=416) ERROR 01-16 11:51:23 [multiproc_executor.py:671]     sampled, processed_logprobs = self.sample(logits, sampling_metadata)
(Worker_TP1 pid=416) ERROR 01-16 11:51:23 [multiproc_executor.py:671]                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(Worker_TP1 pid=416) ERROR 01-16 11:51:23 [multiproc_executor.py:671]   File "/vllm-workspace/vllm/vllm/v1/sample/sampler.py", line 180, in sample
(Worker_TP1 pid=416) ERROR 01-16 11:51:23 [multiproc_executor.py:671]     random_sampled, processed_logprobs = self.topk_topp_sampler(
(Worker_TP1 pid=416) ERROR 01-16 11:51:23 [multiproc_executor.py:671]                                          ^^^^^^^^^^^^^^^^^^^^^^^
(Worker_TP1 pid=416) ERROR 01-16 11:51:23 [multiproc_executor.py:671]   File "/usr/local/python3.11.13/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
(Worker_TP1 pid=416) ERROR 01-16 11:51:23 [multiproc_executor.py:671]     return self._call_impl(*args, **kwargs)
(Worker_TP1 pid=416) ERROR 01-16 11:51:23 [multiproc_executor.py:671]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(Worker_TP1 pid=416) ERROR 01-16 11:51:23 [multiproc_executor.py:671]   File "/usr/local/python3.11.13/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1762, in _call_impl
(Worker_TP1 pid=416) ERROR 01-16 11:51:23 [multiproc_executor.py:671]     return forward_call(*args, **kwargs)
(Worker_TP1 pid=416) ERROR 01-16 11:51:23 [multiproc_executor.py:671]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(Worker_TP1 pid=416) ERROR 01-16 11:51:23 [multiproc_executor.py:671]   File "/vllm-workspace/vllm-ascend/vllm_ascend/sample/sampler.py", line 70, in forward_native
(Worker_TP1 pid=416) ERROR 01-16 11:51:23 [multiproc_executor.py:671]     logits = self._apply_top_k_top_p(logits, k, p)
(Worker_TP1 pid=416) ERROR 01-16 11:51:23 [multiproc_executor.py:671]              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(Worker_TP1 pid=416) ERROR 01-16 11:51:23 [multiproc_executor.py:671]   File "/vllm-workspace/vllm-ascend/vllm_ascend/sample/sampler.py", line 32, in _apply_top_k_top_p
(Worker_TP1 pid=416) ERROR 01-16 11:51:23 [multiproc_executor.py:671]     if not is_310p() and p is not None and k is not None and 1 <= int(
(Worker_TP1 pid=416) ERROR 01-16 11:51:23 [multiproc_executor.py:671]                                                                   ^^^^
(Worker_TP1 pid=416) ERROR 01-16 11:51:23 [multiproc_executor.py:671] RuntimeError: The Inner error is reported as above. The process exits for this inner error, and the current working operator name is aclnnMatmul.
(Worker_TP1 pid=416) ERROR 01-16 11:51:23 [multiproc_executor.py:671] Since the operator is called asynchronously, the stacktrace may be inaccurate. If you want to get the accurate stacktrace, please set the environment variable ASCEND_LAUNCH_BLOCKING=1.
(Worker_TP1 pid=416) ERROR 01-16 11:51:23 [multiproc_executor.py:671] Note: ASCEND_LAUNCH_BLOCKING=1 will force ops to run in synchronous mode, resulting in performance degradation. Please unset ASCEND_LAUNCH_BLOCKING in time after debugging.
(Worker_TP1 pid=416) ERROR 01-16 11:51:23 [multiproc_executor.py:671] [ERROR] 2026-01-16-11:51:23 (PID:416, Device:1, RankID:-1) ERR00100 PTA call acl api failed.
(Worker_TP1 pid=416) ERROR 01-16 11:51:23 [multiproc_executor.py:671] 
(Worker_TP1 pid=416) ERROR 01-16 11:51:23 [multiproc_executor.py:671] Traceback (most recent call last):
(Worker_TP1 pid=416) ERROR 01-16 11:51:23 [multiproc_executor.py:671]   File "/vllm-workspace/vllm/vllm/v1/executor/multiproc_executor.py", line 666, in worker_busy_loop
(Worker_TP1 pid=416) ERROR 01-16 11:51:23 [multiproc_executor.py:671]     output = func(*args, **kwargs)
(Worker_TP1 pid=416) ERROR 01-16 11:51:23 [multiproc_executor.py:671]              ^^^^^^^^^^^^^^^^^^^^^
(Worker_TP1 pid=416) ERROR 01-16 11:51:23 [multiproc_executor.py:671]   File "/vllm-workspace/vllm-ascend/vllm_ascend/worker/worker_v1.py", line 254, in execute_model
(Worker_TP1 pid=416) ERROR 01-16 11:51:23 [multiproc_executor.py:671]     output = self.model_runner.execute_model(scheduler_output,
(Worker_TP1 pid=416) ERROR 01-16 11:51:23 [multiproc_executor.py:671]              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(Worker_TP1 pid=416) ERROR 01-16 11:51:23 [multiproc_executor.py:671]   File "/usr/local/python3.11.13/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
(Worker_TP1 pid=416) ERROR 01-16 11:51:23 [multiproc_executor.py:671]     return func(*args, **kwargs)
(Worker_TP1 pid=416) ERROR 01-16 11:51:23 [multiproc_executor.py:671]            ^^^^^^^^^^^^^^^^^^^^^
(Worker_TP1 pid=416) ERROR 01-16 11:51:23 [multiproc_executor.py:671]   File "/vllm-workspace/vllm-ascend/vllm_ascend/worker/model_runner_v1.py", line 2030, in execute_model
(Worker_TP1 pid=416) ERROR 01-16 11:51:23 [multiproc_executor.py:671]     sampler_output = self.sampler(
(Worker_TP1 pid=416) ERROR 01-16 11:51:23 [multiproc_executor.py:671]                      ^^^^^^^^^^^^^
(Worker_TP1 pid=416) ERROR 01-16 11:51:23 [multiproc_executor.py:671]   File "/usr/local/python3.11.13/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
(Worker_TP1 pid=416) ERROR 01-16 11:51:23 [multiproc_executor.py:671]     return self._call_impl(*args, **kwargs)
(Worker_TP1 pid=416) ERROR 01-16 11:51:23 [multiproc_executor.py:671]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(Worker_TP1 pid=416) ERROR 01-16 11:51:23 [multiproc_executor.py:671]   File "/usr/local/python3.11.13/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1762, in _call_impl
(Worker_TP1 pid=416) ERROR 01-16 11:51:23 [multiproc_executor.py:671]     return forward_call(*args, **kwargs)
(Worker_TP1 pid=416) ERROR 01-16 11:51:23 [multiproc_executor.py:671]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(Worker_TP1 pid=416) ERROR 01-16 11:51:23 [multiproc_executor.py:671]   File "/vllm-workspace/vllm/vllm/v1/sample/sampler.py", line 100, in forward
(Worker_TP1 pid=416) ERROR 01-16 11:51:23 [multiproc_executor.py:671]     sampled, processed_logprobs = self.sample(logits, sampling_metadata)
(Worker_TP1 pid=416) ERROR 01-16 11:51:23 [multiproc_executor.py:671]                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(Worker_TP1 pid=416) ERROR 01-16 11:51:23 [multiproc_executor.py:671]   File "/vllm-workspace/vllm/vllm/v1/sample/sampler.py", line 180, in sample
(Worker_TP1 pid=416) ERROR 01-16 11:51:23 [multiproc_executor.py:671]     random_sampled, processed_logprobs = self.topk_topp_sampler(
(Worker_TP1 pid=416) ERROR 01-16 11:51:23 [multiproc_executor.py:671]                                          ^^^^^^^^^^^^^^^^^^^^^^^
(Worker_TP1 pid=416) ERROR 01-16 11:51:23 [multiproc_executor.py:671]   File "/usr/local/python3.11.13/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
(Worker_TP1 pid=416) ERROR 01-16 11:51:23 [multiproc_executor.py:671]     return self._call_impl(*args, **kwargs)
(Worker_TP1 pid=416) ERROR 01-16 11:51:23 [multiproc_executor.py:671]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(Worker_TP1 pid=416) ERROR 01-16 11:51:23 [multiproc_executor.py:671]   File "/usr/local/python3.11.13/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1762, in _call_impl
(Worker_TP1 pid=416) ERROR 01-16 11:51:23 [multiproc_executor.py:671]     return forward_call(*args, **kwargs)
(Worker_TP1 pid=416) ERROR 01-16 11:51:23 [multiproc_executor.py:671]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(Worker_TP1 pid=416) ERROR 01-16 11:51:23 [multiproc_executor.py:671]   File "/vllm-workspace/vllm-ascend/vllm_ascend/sample/sampler.py", line 70, in forward_native
(Worker_TP1 pid=416) ERROR 01-16 11:51:23 [multiproc_executor.py:671]     logits = self._apply_top_k_top_p(logits, k, p)
(Worker_TP1 pid=416) ERROR 01-16 11:51:23 [multiproc_executor.py:671]              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(Worker_TP1 pid=416) ERROR 01-16 11:51:23 [multiproc_executor.py:671]   File "/vllm-workspace/vllm-ascend/vllm_ascend/sample/sampler.py", line 32, in _apply_top_k_top_p
(Worker_TP1 pid=416) ERROR 01-16 11:51:23 [multiproc_executor.py:671]     if not is_310p() and p is not None and k is not None and 1 <= int(
(Worker_TP1 pid=416) ERROR 01-16 11:51:23 [multiproc_executor.py:671]                                                                   ^^^^
(Worker_TP1 pid=416) ERROR 01-16 11:51:23 [multiproc_executor.py:671] RuntimeError: The Inner error is reported as above. The process exits for this inner error, and the current working operator name is aclnnMatmul.
(Worker_TP1 pid=416) ERROR 01-16 11:51:23 [multiproc_executor.py:671] Since the operator is called asynchronously, the stacktrace may be inaccurate. If you want to get the accurate stacktrace, please set the environment variable ASCEND_LAUNCH_BLOCKING=1.
(Worker_TP1 pid=416) ERROR 01-16 11:51:23 [multiproc_executor.py:671] Note: ASCEND_LAUNCH_BLOCKING=1 will force ops to run in synchronous mode, resulting in performance degradation. Please unset ASCEND_LAUNCH_BLOCKING in time after debugging.
(Worker_TP1 pid=416) ERROR 01-16 11:51:23 [multiproc_executor.py:671] [ERROR] 2026-01-16-11:51:23 (PID:416, Device:1, RankID:-1) ERR00100 PTA call acl api failed.
(Worker_TP1 pid=416) ERROR 01-16 11:51:23 [multiproc_executor.py:671] 
(Worker_TP1 pid=416) ERROR 01-16 11:51:23 [multiproc_executor.py:671] 
(Worker_TP0 pid=415) ERROR 01-16 11:51:23 [multiproc_executor.py:671] WorkerProc hit an exception.
(Worker_TP0 pid=415) ERROR 01-16 11:51:23 [multiproc_executor.py:671] Traceback (most recent call last):
(Worker_TP0 pid=415) ERROR 01-16 11:51:23 [multiproc_executor.py:671]   File "/vllm-workspace/vllm/vllm/v1/executor/multiproc_executor.py", line 666, in worker_busy_loop
(Worker_TP0 pid=415) ERROR 01-16 11:51:23 [multiproc_executor.py:671]     output = func(*args, **kwargs)
(Worker_TP0 pid=415) ERROR 01-16 11:51:23 [multiproc_executor.py:671]              ^^^^^^^^^^^^^^^^^^^^^
(Worker_TP0 pid=415) ERROR 01-16 11:51:23 [multiproc_executor.py:671]   File "/vllm-workspace/vllm-ascend/vllm_ascend/worker/worker_v1.py", line 254, in execute_model
(Worker_TP0 pid=415) ERROR 01-16 11:51:23 [multiproc_executor.py:671]     output = self.model_runner.execute_model(scheduler_output,
(Worker_TP0 pid=415) ERROR 01-16 11:51:23 [multiproc_executor.py:671]              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(Worker_TP0 pid=415) ERROR 01-16 11:51:23 [multiproc_executor.py:671]   File "/usr/local/python3.11.13/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
(Worker_TP0 pid=415) ERROR 01-16 11:51:23 [multiproc_executor.py:671]     return func(*args, **kwargs)
(Worker_TP0 pid=415) ERROR 01-16 11:51:23 [multiproc_executor.py:671]            ^^^^^^^^^^^^^^^^^^^^^
(Worker_TP0 pid=415) ERROR 01-16 11:51:23 [multiproc_executor.py:671]   File "/vllm-workspace/vllm-ascend/vllm_ascend/worker/model_runner_v1.py", line 2030, in execute_model
(Worker_TP0 pid=415) ERROR 01-16 11:51:23 [multiproc_executor.py:671]     sampler_output = self.sampler(
(Worker_TP0 pid=415) ERROR 01-16 11:51:23 [multiproc_executor.py:671]                      ^^^^^^^^^^^^^
(Worker_TP0 pid=415) ERROR 01-16 11:51:23 [multiproc_executor.py:671]   File "/usr/local/python3.11.13/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
(Worker_TP0 pid=415) ERROR 01-16 11:51:23 [multiproc_executor.py:671]     return self._call_impl(*args, **kwargs)
(Worker_TP0 pid=415) ERROR 01-16 11:51:23 [multiproc_executor.py:671]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(Worker_TP0 pid=415) ERROR 01-16 11:51:23 [multiproc_executor.py:671]   File "/usr/local/python3.11.13/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1762, in _call_impl
(Worker_TP0 pid=415) ERROR 01-16 11:51:23 [multiproc_executor.py:671]     return forward_call(*args, **kwargs)
(Worker_TP0 pid=415) ERROR 01-16 11:51:23 [multiproc_executor.py:671]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(Worker_TP0 pid=415) ERROR 01-16 11:51:23 [multiproc_executor.py:671]   File "/vllm-workspace/vllm/vllm/v1/sample/sampler.py", line 100, in forward
(Worker_TP0 pid=415) ERROR 01-16 11:51:23 [multiproc_executor.py:671]     sampled, processed_logprobs = self.sample(logits, sampling_metadata)
(Worker_TP0 pid=415) ERROR 01-16 11:51:23 [multiproc_executor.py:671]                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(Worker_TP0 pid=415) ERROR 01-16 11:51:23 [multiproc_executor.py:671]   File "/vllm-workspace/vllm/vllm/v1/sample/sampler.py", line 180, in sample
(Worker_TP0 pid=415) ERROR 01-16 11:51:23 [multiproc_executor.py:671]     random_sampled, processed_logprobs = self.topk_topp_sampler(
(Worker_TP0 pid=415) ERROR 01-16 11:51:23 [multiproc_executor.py:671]                                          ^^^^^^^^^^^^^^^^^^^^^^^
(Worker_TP0 pid=415) ERROR 01-16 11:51:23 [multiproc_executor.py:671]   File "/usr/local/python3.11.13/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
(Worker_TP0 pid=415) ERROR 01-16 11:51:23 [multiproc_executor.py:671]     return self._call_impl(*args, **kwargs)
(Worker_TP0 pid=415) ERROR 01-16 11:51:23 [multiproc_executor.py:671]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(Worker_TP0 pid=415) ERROR 01-16 11:51:23 [multiproc_executor.py:671]   File "/usr/local/python3.11.13/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1762, in _call_impl
(Worker_TP0 pid=415) ERROR 01-16 11:51:23 [multiproc_executor.py:671]     return forward_call(*args, **kwargs)
(Worker_TP0 pid=415) ERROR 01-16 11:51:23 [multiproc_executor.py:671]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(Worker_TP0 pid=415) ERROR 01-16 11:51:23 [multiproc_executor.py:671]   File "/vllm-workspace/vllm-ascend/vllm_ascend/sample/sampler.py", line 70, in forward_native
(Worker_TP0 pid=415) ERROR 01-16 11:51:23 [multiproc_executor.py:671]     logits = self._apply_top_k_top_p(logits, k, p)
(Worker_TP0 pid=415) ERROR 01-16 11:51:23 [multiproc_executor.py:671]              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(Worker_TP0 pid=415) ERROR 01-16 11:51:23 [multiproc_executor.py:671]   File "/vllm-workspace/vllm-ascend/vllm_ascend/sample/sampler.py", line 32, in _apply_top_k_top_p
(Worker_TP0 pid=415) ERROR 01-16 11:51:23 [multiproc_executor.py:671]     if not is_310p() and p is not None and k is not None and 1 <= int(
(Worker_TP0 pid=415) ERROR 01-16 11:51:23 [multiproc_executor.py:671]                                                                   ^^^^
(Worker_TP0 pid=415) ERROR 01-16 11:51:23 [multiproc_executor.py:671] RuntimeError: The Inner error is reported as above. The process exits for this inner error, and the current working operator name is aclnnRmsNorm.
(Worker_TP0 pid=415) ERROR 01-16 11:51:23 [multiproc_executor.py:671] Since the operator is called asynchronously, the stacktrace may be inaccurate. If you want to get the accurate stacktrace, please set the environment variable ASCEND_LAUNCH_BLOCKING=1.
(Worker_TP0 pid=415) ERROR 01-16 11:51:23 [multiproc_executor.py:671] Note: ASCEND_LAUNCH_BLOCKING=1 will force ops to run in synchronous mode, resulting in performance degradation. Please unset ASCEND_LAUNCH_BLOCKING in time after debugging.
(Worker_TP0 pid=415) ERROR 01-16 11:51:23 [multiproc_executor.py:671] [ERROR] 2026-01-16-11:51:23 (PID:415, Device:0, RankID:-1) ERR00100 PTA call acl api failed.
(Worker_TP0 pid=415) ERROR 01-16 11:51:23 [multiproc_executor.py:671] 
(Worker_TP0 pid=415) ERROR 01-16 11:51:23 [multiproc_executor.py:671] Traceback (most recent call last):
(Worker_TP0 pid=415) ERROR 01-16 11:51:23 [multiproc_executor.py:671]   File "/vllm-workspace/vllm/vllm/v1/executor/multiproc_executor.py", line 666, in worker_busy_loop
(Worker_TP0 pid=415) ERROR 01-16 11:51:23 [multiproc_executor.py:671]     output = func(*args, **kwargs)
(Worker_TP0 pid=415) ERROR 01-16 11:51:23 [multiproc_executor.py:671]              ^^^^^^^^^^^^^^^^^^^^^
(Worker_TP0 pid=415) ERROR 01-16 11:51:23 [multiproc_executor.py:671]   File "/vllm-workspace/vllm-ascend/vllm_ascend/worker/worker_v1.py", line 254, in execute_model
(Worker_TP0 pid=415) ERROR 01-16 11:51:23 [multiproc_executor.py:671]     output = self.model_runner.execute_model(scheduler_output,
(Worker_TP0 pid=415) ERROR 01-16 11:51:23 [multiproc_executor.py:671]              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(Worker_TP0 pid=415) ERROR 01-16 11:51:23 [multiproc_executor.py:671]   File "/usr/local/python3.11.13/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
(Worker_TP0 pid=415) ERROR 01-16 11:51:23 [multiproc_executor.py:671]     return func(*args, **kwargs)
(Worker_TP0 pid=415) ERROR 01-16 11:51:23 [multiproc_executor.py:671]            ^^^^^^^^^^^^^^^^^^^^^
(Worker_TP0 pid=415) ERROR 01-16 11:51:23 [multiproc_executor.py:671]   File "/vllm-workspace/vllm-ascend/vllm_ascend/worker/model_runner_v1.py", line 2030, in execute_model
(Worker_TP0 pid=415) ERROR 01-16 11:51:23 [multiproc_executor.py:671]     sampler_output = self.sampler(
(Worker_TP0 pid=415) ERROR 01-16 11:51:23 [multiproc_executor.py:671]                      ^^^^^^^^^^^^^
(Worker_TP0 pid=415) ERROR 01-16 11:51:23 [multiproc_executor.py:671]   File "/usr/local/python3.11.13/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
(Worker_TP0 pid=415) ERROR 01-16 11:51:23 [multiproc_executor.py:671]     return self._call_impl(*args, **kwargs)
(Worker_TP0 pid=415) ERROR 01-16 11:51:23 [multiproc_executor.py:671]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(Worker_TP0 pid=415) ERROR 01-16 11:51:23 [multiproc_executor.py:671]   File "/usr/local/python3.11.13/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1762, in _call_impl
(Worker_TP0 pid=415) ERROR 01-16 11:51:23 [multiproc_executor.py:671]     return forward_call(*args, **kwargs)
(Worker_TP0 pid=415) ERROR 01-16 11:51:23 [multiproc_executor.py:671]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(Worker_TP0 pid=415) ERROR 01-16 11:51:23 [multiproc_executor.py:671]   File "/vllm-workspace/vllm/vllm/v1/sample/sampler.py", line 100, in forward
(Worker_TP0 pid=415) ERROR 01-16 11:51:23 [multiproc_executor.py:671]     sampled, processed_logprobs = self.sample(logits, sampling_metadata)
(Worker_TP0 pid=415) ERROR 01-16 11:51:23 [multiproc_executor.py:671]                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(Worker_TP0 pid=415) ERROR 01-16 11:51:23 [multiproc_executor.py:671]   File "/vllm-workspace/vllm/vllm/v1/sample/sampler.py", line 180, in sample
(Worker_TP0 pid=415) ERROR 01-16 11:51:23 [multiproc_executor.py:671]     random_sampled, processed_logprobs = self.topk_topp_sampler(
(Worker_TP0 pid=415) ERROR 01-16 11:51:23 [multiproc_executor.py:671]                                          ^^^^^^^^^^^^^^^^^^^^^^^
(Worker_TP0 pid=415) ERROR 01-16 11:51:23 [multiproc_executor.py:671]   File "/usr/local/python3.11.13/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1751, in _wrapped_call_impl
(Worker_TP0 pid=415) ERROR 01-16 11:51:23 [multiproc_executor.py:671]     return self._call_impl(*args, **kwargs)
(Worker_TP0 pid=415) ERROR 01-16 11:51:23 [multiproc_executor.py:671]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(Worker_TP0 pid=415) ERROR 01-16 11:51:23 [multiproc_executor.py:671]   File "/usr/local/python3.11.13/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1762, in _call_impl
(Worker_TP0 pid=415) ERROR 01-16 11:51:23 [multiproc_executor.py:671]     return forward_call(*args, **kwargs)
(Worker_TP0 pid=415) ERROR 01-16 11:51:23 [multiproc_executor.py:671]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(Worker_TP0 pid=415) ERROR 01-16 11:51:23 [multiproc_executor.py:671]   File "/vllm-workspace/vllm-ascend/vllm_ascend/sample/sampler.py", line 70, in forward_native
(Worker_TP0 pid=415) ERROR 01-16 11:51:23 [multiproc_executor.py:671]     logits = self._apply_top_k_top_p(logits, k, p)
(Worker_TP0 pid=415) ERROR 01-16 11:51:23 [multiproc_executor.py:671]              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(Worker_TP0 pid=415) ERROR 01-16 11:51:23 [multiproc_executor.py:671]   File "/vllm-workspace/vllm-ascend/vllm_ascend/sample/sampler.py", line 32, in _apply_top_k_top_p
(Worker_TP0 pid=415) ERROR 01-16 11:51:23 [multiproc_executor.py:671]     if not is_310p() and p is not None and k is not None and 1 <= int(
(Worker_TP0 pid=415) ERROR 01-16 11:51:23 [multiproc_executor.py:671]                                                                   ^^^^
(Worker_TP0 pid=415) ERROR 01-16 11:51:23 [multiproc_executor.py:671] RuntimeError: The Inner error is reported as above. The process exits for this inner error, and the current working operator name is aclnnRmsNorm.
(Worker_TP0 pid=415) ERROR 01-16 11:51:23 [multiproc_executor.py:671] Since the operator is called asynchronously, the stacktrace may be inaccurate. If you want to get the accurate stacktrace, please set the environment variable ASCEND_LAUNCH_BLOCKING=1.
(Worker_TP0 pid=415) ERROR 01-16 11:51:23 [multiproc_executor.py:671] Note: ASCEND_LAUNCH_BLOCKING=1 will force ops to run in synchronous mode, resulting in performance degradation. Please unset ASCEND_LAUNCH_BLOCKING in time after debugging.
(Worker_TP0 pid=415) ERROR 01-16 11:51:23 [multiproc_executor.py:671] [ERROR] 2026-01-16-11:51:23 (PID:415, Device:0, RankID:-1) ERR00100 PTA call acl api failed.
(EngineCore_DP0 pid=279) ERROR 01-16 11:51:23 [dump_input.py:69] Dumping input data for V1 LLM engine (v0.11.0rc3) with config: model='/home/mind/model/Qwen3-Coder-30B-A3B-Instruct', speculative_config=None, tokenizer='/home/mind/model/Qwen3-Coder-30B-A3B-Instruct', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, tokenizer_revision=None, trust_remote_code=False, dtype=torch.bfloat16, max_seq_len=65536, download_dir=None, load_format=auto, tensor_parallel_size=4, pipeline_parallel_size=1, data_parallel_size=1, disable_custom_all_reduce=True, quantization=None, enforce_eager=False, kv_cache_dtype=auto, device_config=npu, structured_outputs_config=StructuredOutputsConfig(backend='auto', disable_fallback=False, disable_any_whitespace=False, disable_additional_properties=False, reasoning_parser=''), observability_config=ObservabilityConfig(show_hidden_metrics_for_version=None, otlp_traces_endpoint=None, collect_detailed_traces=None), seed=0, served_model_name=Qwen3-Coder, enable_prefix_caching=True, chunked_prefill_enabled=False, pooler_config=None, compilation_config={"level":3,"debug_dump_path":"","cache_dir":"","backend":"","custom_ops":["all"],"splitting_ops":["vllm.unified_attention","vllm.unified_attention_with_output","vllm.mamba_mixer2","vllm.mamba_mixer","vllm.short_conv","vllm.linear_attention","vllm.plamo2_mamba_mixer","vllm.gdn_attention","vllm.unified_ascend_attention_with_output","vllm.mla_forward","vllm.unified_ascend_attention_with_output","vllm.mla_forward"],"use_inductor":false,"compile_sizes":[],"inductor_compile_config":{"enable_auto_functionalized_v2":false},"inductor_passes":{},"cudagraph_mode":1,"use_cudagraph":true,"cudagraph_num_of_warmups":1,"cudagraph_capture_sizes":[512,456,408,352,304,248,192,144,88,40,1],"cudagraph_copy_inputs":false,"full_cuda_graph":false,"use_inductor_graph_partition":false,"pass_config":{},"max_capture_size":512,"local_cache_dir":null}, 
(EngineCore_DP0 pid=279) ERROR 01-16 11:51:23 [dump_input.py:76] Dumping scheduler output for model execution: SchedulerOutput(scheduled_new_reqs=[NewRequestData(req_id=chatcmpl-d7224bc9dc064a699d0696df1d24529b,prompt_token_ids_len=2528,mm_features=[],sampling_params=SamplingParams(n=1, presence_penalty=0.0, frequency_penalty=0.0, repetition_penalty=1.05, temperature=0.6, top_p=0.8, top_k=20, min_p=0.0, seed=None, stop=[], stop_token_ids=[151643], bad_words=[], include_stop_str_in_output=False, ignore_eos=False, max_tokens=4096, min_tokens=0, logprobs=None, prompt_logprobs=None, skip_special_tokens=True, spaces_between_special_tokens=True, truncate_prompt_tokens=None, structured_outputs=None, extra_args=None),block_ids=([866, 867, 868, 869, 5293, 5473, 5476, 5503, 5694, 5657, 5374, 5626, 5427, 5532, 5551, 5663, 5543, 5553, 5616, 5614],),num_computed_tokens=768,lora_request=None,prompt_embeds_shape=None)], scheduled_cached_reqs=CachedRequestData(req_ids=[], resumed_from_preemption=[], new_token_ids=[], new_block_ids=[], num_computed_tokens=[]), num_scheduled_tokens={chatcmpl-d7224bc9dc064a699d0696df1d24529b: 1760}, total_num_scheduled_tokens=1760, scheduled_spec_decode_tokens={}, scheduled_encoder_inputs={}, num_common_prefix_blocks=[6], finished_req_ids=[], free_encoder_mm_hashes=[], structured_output_request_ids={}, grammar_bitmask=null, kv_connector_metadata=null)
(EngineCore_DP0 pid=279) ERROR 01-16 11:51:23 [dump_input.py:79] Dumping scheduler stats: SchedulerStats(num_running_reqs=7, num_waiting_reqs=0, step_counter=0, current_wave=0, kv_cache_usage=0.0077503142019270665, prefix_cache_stats=PrefixCacheStats(reset=False, requests=1, queries=2528, hits=768), spec_decoding_stats=None, kv_connector_stats=None, num_corrupted_reqs=0)
(EngineCore_DP0 pid=279) ERROR 01-16 11:51:23 [core.py:710] EngineCore encountered a fatal error.
(EngineCore_DP0 pid=279) ERROR 01-16 11:51:23 [core.py:710] Traceback (most recent call last):
(EngineCore_DP0 pid=279) ERROR 01-16 11:51:23 [core.py:710]   File "/vllm-workspace/vllm/vllm/v1/engine/core.py", line 701, in run_engine_core
(EngineCore_DP0 pid=279) ERROR 01-16 11:51:23 [core.py:710]     engine_core.run_busy_loop()
(EngineCore_DP0 pid=279) ERROR 01-16 11:51:23 [core.py:710]   File "/vllm-workspace/vllm/vllm/v1/engine/core.py", line 728, in run_busy_loop
(EngineCore_DP0 pid=279) ERROR 01-16 11:51:23 [core.py:710]     self._process_engine_step()
(EngineCore_DP0 pid=279) ERROR 01-16 11:51:23 [core.py:710]   File "/vllm-workspace/vllm/vllm/v1/engine/core.py", line 754, in _process_engine_step
(EngineCore_DP0 pid=279) ERROR 01-16 11:51:23 [core.py:710]     outputs, model_executed = self.step_fn()
(EngineCore_DP0 pid=279) ERROR 01-16 11:51:23 [core.py:710]                               ^^^^^^^^^^^^^^
(EngineCore_DP0 pid=279) ERROR 01-16 11:51:23 [core.py:710]   File "/vllm-workspace/vllm/vllm/v1/engine/core.py", line 284, in step
(EngineCore_DP0 pid=279) ERROR 01-16 11:51:23 [core.py:710]     model_output = self.execute_model_with_error_logging(
(EngineCore_DP0 pid=279) ERROR 01-16 11:51:23 [core.py:710]                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(EngineCore_DP0 pid=279) ERROR 01-16 11:51:23 [core.py:710]   File "/vllm-workspace/vllm/vllm/v1/engine/core.py", line 270, in execute_model_with_error_logging
(EngineCore_DP0 pid=279) ERROR 01-16 11:51:23 [core.py:710]     raise err
(EngineCore_DP0 pid=279) ERROR 01-16 11:51:23 [core.py:710]   File "/vllm-workspace/vllm/vllm/v1/engine/core.py", line 261, in execute_model_with_error_logging
(EngineCore_DP0 pid=279) ERROR 01-16 11:51:23 [core.py:710]     return model_fn(scheduler_output)
(EngineCore_DP0 pid=279) ERROR 01-16 11:51:23 [core.py:710]            ^^^^^^^^^^^^^^^^^^^^^^^^^^
(EngineCore_DP0 pid=279) ERROR 01-16 11:51:23 [core.py:710]   File "/vllm-workspace/vllm/vllm/v1/executor/multiproc_executor.py", line 181, in execute_model
(EngineCore_DP0 pid=279) ERROR 01-16 11:51:23 [core.py:710]     (output, ) = self.collective_rpc(
(EngineCore_DP0 pid=279) ERROR 01-16 11:51:23 [core.py:710]                  ^^^^^^^^^^^^^^^^^^^^
(EngineCore_DP0 pid=279) ERROR 01-16 11:51:23 [core.py:710]   File "/vllm-workspace/vllm/vllm/v1/executor/multiproc_executor.py", line 264, in collective_rpc
(EngineCore_DP0 pid=279) ERROR 01-16 11:51:23 [core.py:710]     result = get_response(w, dequeue_timeout,
(EngineCore_DP0 pid=279) ERROR 01-16 11:51:23 [core.py:710]              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(EngineCore_DP0 pid=279) ERROR 01-16 11:51:23 [core.py:710]   File "/vllm-workspace/vllm/vllm/v1/executor/multiproc_executor.py", line 248, in get_response
(EngineCore_DP0 pid=279) ERROR 01-16 11:51:23 [core.py:710]     raise RuntimeError(
(EngineCore_DP0 pid=279) ERROR 01-16 11:51:23 [core.py:710] RuntimeError: Worker failed with error 'The Inner error is reported as above. The process exits for this inner error, and the current working operator name is aclnnRmsNorm.
(EngineCore_DP0 pid=279) ERROR 01-16 11:51:23 [core.py:710] Since the operator is called asynchronously, the stacktrace may be inaccurate. If you want to get the accurate stacktrace, please set the environment variable ASCEND_LAUNCH_BLOCKING=1.
(EngineCore_DP0 pid=279) ERROR 01-16 11:51:23 [core.py:710] Note: ASCEND_LAUNCH_BLOCKING=1 will force ops to run in synchronous mode, resulting in performance degradation. Please unset ASCEND_LAUNCH_BLOCKING in time after debugging.
(EngineCore_DP0 pid=279) ERROR 01-16 11:51:23 [core.py:710] [ERROR] 2026-01-16-11:51:23 (PID:415, Device:0, RankID:-1) ERR00100 PTA call acl api failed.
(EngineCore_DP0 pid=279) ERROR 01-16 11:51:23 [core.py:710] ', please check the stack trace above for the root cause
(Worker_TP1 pid=416) INFO 01-16 11:51:23 [multiproc_executor.py:558] Parent process exited, terminating worker
(APIServer pid=9) ERROR 01-16 11:51:23 [async_llm.py:480] AsyncLLM output_handler failed.
(APIServer pid=9) ERROR 01-16 11:51:23 [async_llm.py:480] Traceback (most recent call last):
(APIServer pid=9) ERROR 01-16 11:51:23 [async_llm.py:480]   File "/vllm-workspace/vllm/vllm/v1/engine/async_llm.py", line 439, in output_handler
(APIServer pid=9) ERROR 01-16 11:51:23 [async_llm.py:480]     outputs = await engine_core.get_output_async()
(APIServer pid=9) ERROR 01-16 11:51:23 [async_llm.py:480]               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(APIServer pid=9) ERROR 01-16 11:51:23 [async_llm.py:480]   File "/vllm-workspace/vllm/vllm/v1/engine/core_client.py", line 846, in get_output_async
(APIServer pid=9) ERROR 01-16 11:51:23 [async_llm.py:480]     raise self._format_exception(outputs) from None
(APIServer pid=9) ERROR 01-16 11:51:23 [async_llm.py:480] vllm.v1.engine.exceptions.EngineDeadError: EngineCore encountered an issue. See stack trace (above) for the root cause.
(Worker_TP2 pid=417) INFO 01-16 11:51:23 [multiproc_executor.py:558] Parent process exited, terminating worker
(Worker_TP1 pid=416) INFO 01-16 11:51:23 [multiproc_executor.py:599] WorkerProc shutting down.
(Worker_TP3 pid=418) INFO 01-16 11:51:23 [multiproc_executor.py:558] Parent process exited, terminating worker
(APIServer pid=9) INFO:     10.3.128.216:36838 - "POST /v1/chat/completions HTTP/1.1" 500 Internal Server Error
(APIServer pid=9) INFO:     10.3.110.16:56926 - "POST /v1/chat/completions HTTP/1.1" 500 Internal Server Error
...
...
...
...
(APIServer pid=9) INFO:     10.3.110.16:46390 - "POST /v1/chat/completions HTTP/1.1" 500 Internal Server Error
(EngineCore_DP0 pid=279) Process EngineCore_DP0:
(EngineCore_DP0 pid=279) Traceback (most recent call last):
(EngineCore_DP0 pid=279)   File "/usr/local/python3.11.13/lib/python3.11/multiprocessing/process.py", line 314, in _bootstrap
(EngineCore_DP0 pid=279)     self.run()
(EngineCore_DP0 pid=279)   File "/usr/local/python3.11.13/lib/python3.11/multiprocessing/process.py", line 108, in run
(EngineCore_DP0 pid=279)     self._target(*self._args, **self._kwargs)
(EngineCore_DP0 pid=279)   File "/vllm-workspace/vllm/vllm/v1/engine/core.py", line 712, in run_engine_core
(EngineCore_DP0 pid=279)     raise e
(EngineCore_DP0 pid=279)   File "/vllm-workspace/vllm/vllm/v1/engine/core.py", line 701, in run_engine_core
(EngineCore_DP0 pid=279)     engine_core.run_busy_loop()
(EngineCore_DP0 pid=279)   File "/vllm-workspace/vllm/vllm/v1/engine/core.py", line 728, in run_busy_loop
(EngineCore_DP0 pid=279)     self._process_engine_step()
(EngineCore_DP0 pid=279)   File "/vllm-workspace/vllm/vllm/v1/engine/core.py", line 754, in _process_engine_step
(EngineCore_DP0 pid=279)     outputs, model_executed = self.step_fn()
(EngineCore_DP0 pid=279)                               ^^^^^^^^^^^^^^
(EngineCore_DP0 pid=279)   File "/vllm-workspace/vllm/vllm/v1/engine/core.py", line 284, in step
(EngineCore_DP0 pid=279)     model_output = self.execute_model_with_error_logging(
(EngineCore_DP0 pid=279)                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(EngineCore_DP0 pid=279)   File "/vllm-workspace/vllm/vllm/v1/engine/core.py", line 270, in execute_model_with_error_logging
(EngineCore_DP0 pid=279)     raise err
(EngineCore_DP0 pid=279)   File "/vllm-workspace/vllm/vllm/v1/engine/core.py", line 261, in execute_model_with_error_logging
(EngineCore_DP0 pid=279)     return model_fn(scheduler_output)
(EngineCore_DP0 pid=279)            ^^^^^^^^^^^^^^^^^^^^^^^^^^
(EngineCore_DP0 pid=279)   File "/vllm-workspace/vllm/vllm/v1/executor/multiproc_executor.py", line 181, in execute_model
(EngineCore_DP0 pid=279)     (output, ) = self.collective_rpc(
(EngineCore_DP0 pid=279)                  ^^^^^^^^^^^^^^^^^^^^
(EngineCore_DP0 pid=279)   File "/vllm-workspace/vllm/vllm/v1/executor/multiproc_executor.py", line 264, in collective_rpc
(EngineCore_DP0 pid=279)     result = get_response(w, dequeue_timeout,
(EngineCore_DP0 pid=279)              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(EngineCore_DP0 pid=279)   File "/vllm-workspace/vllm/vllm/v1/executor/multiproc_executor.py", line 248, in get_response
(EngineCore_DP0 pid=279)     raise RuntimeError(
(EngineCore_DP0 pid=279) RuntimeError: Worker failed with error 'The Inner error is reported as above. The process exits for this inner error, and the current working operator name is aclnnRmsNorm.
(EngineCore_DP0 pid=279) Since the operator is called asynchronously, the stacktrace may be inaccurate. If you want to get the accurate stacktrace, please set the environment variable ASCEND_LAUNCH_BLOCKING=1.
(EngineCore_DP0 pid=279) Note: ASCEND_LAUNCH_BLOCKING=1 will force ops to run in synchronous mode, resulting in performance degradation. Please unset ASCEND_LAUNCH_BLOCKING in time after debugging.
(EngineCore_DP0 pid=279) [ERROR] 2026-01-16-11:51:23 (PID:415, Device:0, RankID:-1) ERR00100 PTA call acl api failed.
(EngineCore_DP0 pid=279) ', please check the stack trace above for the root cause
(APIServer pid=9) INFO:     Shutting down
(APIServer pid=9) INFO:     Waiting for application shutdown.
(APIServer pid=9) INFO:     Application shutdown complete.
(APIServer pid=9) INFO:     Finished server process [9]
```
</details>

**Comment by Laasap** [comment]
@liuzb0 This issue has been resolved in the latest version. Please use the latest release or rc version (https://github.com/vllm-project/vllm-ascend/releases). If the issue persists, feel free to submit a new issue.
