### ISSUE TITLE
[Bug]: 双机910b2拉起deepseek v3.2量化版失败

### ISSUE THREAD

**Issue by gbdjxgp** [vllm-project/vllm-ascend#6275]
### Your current environment

# 主机
```
PyTorch version: 2.9.0+cpu
Is debug build: False

OS: Ubuntu 22.04.5 LTS (aarch64)
GCC version: (Ubuntu 11.4.0-1ubuntu1~22.04.2) 11.4.0
Clang version: 15.0.7
CMake version: version 4.2.1
Libc version: glibc-2.35

Python version: 3.11.14 (main, Jan 19 2026, 07:36:53) [GCC 11.4.0] (64-bit runtime)
Python platform: Linux-5.15.0-164-generic-aarch64-with-glibc2.35

CPU:
Architecture:                            aarch64
CPU op-mode(s):                          64-bit
Byte Order:                              Little Endian
CPU(s):                                  192
On-line CPU(s) list:                     0-191
Vendor ID:                               HiSilicon
Model name:                              Kunpeng-920
Model:                                   0
Thread(s) per core:                      1
Core(s) per cluster:                     48
Socket(s):                               -
Cluster(s):                              4
Stepping:                                0x1
BogoMIPS:                                200.00
Flags:                                   fp asimd evtstrm aes pmull sha1 sha2 crc32 atomics fphp asimdhp cpuid asimdrdm jscvt fcma dcpop asimddp asimdfhm ssbs
L1d cache:                               12 MiB (192 instances)
L1i cache:                               12 MiB (192 instances)
L2 cache:                                96 MiB (192 instances)
L3 cache:                                192 MiB (8 instances)
NUMA node(s):                            8
NUMA node0 CPU(s):                       0-23
NUMA node1 CPU(s):                       24-47
NUMA node2 CPU(s):                       48-71
NUMA node3 CPU(s):                       72-95
NUMA node4 CPU(s):                       96-119
NUMA node5 CPU(s):                       120-143
NUMA node6 CPU(s):                       144-167
NUMA node7 CPU(s):                       168-191
Vulnerability Gather data sampling:      Not affected
Vulnerability Indirect target selection: Not affected
Vulnerability Itlb multihit:             Not affected
Vulnerability L1tf:                      Not affected
Vulnerability Mds:                       Not affected
Vulnerability Meltdown:                  Not affected
Vulnerability Mmio stale data:           Not affected
Vulnerability Reg file data sampling:    Not affected
Vulnerability Retbleed:                  Not affected
Vulnerability Spec rstack overflow:      Not affected
Vulnerability Spec store bypass:         Mitigation; Speculative Store Bypass disabled via prctl
Vulnerability Spectre v1:                Mitigation; __user pointer sanitization
Vulnerability Spectre v2:                Mitigation; CSV2, but not BHB
Vulnerability Srbds:                     Not affected
Vulnerability Tsa:                       Not affected
Vulnerability Tsx async abort:           Not affected
Vulnerability Vmscape:                   Not affected

Versions of relevant libraries:
[pip3] numpy==1.26.4
[pip3] pyzmq==27.1.0
[pip3] torch==2.9.0+cpu
[pip3] torch_npu==2.9.0
[pip3] torchvision==0.24.0
[pip3] transformers==4.57.6
[conda] Could not collect
vLLM Version: 0.14.1
vLLM Ascend Version: 0.14.0rc1

ENV Variables:
ASCEND_TOOLKIT_LATEST_HOME=/usr/local/Ascend/ascend-toolkit/latest
ATB_OPSRUNNER_KERNEL_CACHE_LOCAL_COUNT=1
ATB_STREAM_SYNC_EVERY_RUNNER_ENABLE=0
ATB_STREAM_SYNC_EVERY_KERNEL_ENABLE=0
ATB_OPSRUNNER_KERNEL_CACHE_GLOABL_COUNT=5
PYTORCH_NPU_ALLOC_CONF=expandable_segments:True
ATB_HOME_PATH=/usr/local/Ascend/nnal/atb/latest/atb/cxx_abi_1
ASCEND_TOOLKIT_HOME=/usr/local/Ascend/cann-8.5.0
ASCEND_DOCKER_RUNTIME=True
ATB_COMPARE_TILING_EVERY_KERNEL=0
ASCEND_OPP_PATH=/usr/local/Ascend/cann-8.5.0/opp
LD_LIBRARY_PATH=/usr/local/Ascend/nnal/atb/latest/atb/cxx_abi_1/lib:/usr/local/Ascend/nnal/atb/latest/atb/cxx_abi_1/examples:/usr/local/Ascend/nnal/atb/latest/atb/cxx_abi_1/tests/atbopstest:/usr/local/Ascend/cann-8.5.0/lib64:/usr/local/Ascend/cann-8.5.0/lib64/plugin/opskernel:/usr/local/Ascend/cann-8.5.0/lib64/plugin/nnengine:/usr/local/Ascend/cann-8.5.0/opp/built-in/op_impl/ai_core/tbe/op_tiling/lib/linux/aarch64:/usr/local/Ascend/cann-8.5.0/tools/aml/lib64:/usr/local/Ascend/cann-8.5.0/tools/aml/lib64/plugin:/usr/local/Ascend/driver/lib64:/usr/local/Ascend/driver/lib64/common:/usr/local/Ascend/driver/lib64/driver:/usr/local/Ascend/nnal/atb/latest/atb/cxx_abi_1/lib:/usr/local/Ascend/nnal/atb/latest/atb/cxx_abi_1/examples:/usr/local/Ascend/nnal/atb/latest/atb/cxx_abi_1/tests/atbopstest:/usr/local/Ascend/driver/lib64:/usr/local/Ascend/driver/lib64/common:/usr/local/Ascend/driver/lib64/driver:/usr/local/Ascend/nnal/atb/latest/atb/cxx_abi_1/lib:/usr/local/Ascend/nnal/atb/latest/atb/cxx_abi_1/examples:/usr/local/Ascend/nnal/atb/latest/atb/cxx_abi_1/tests/atbopstest:/usr/local/Ascend/ascend-toolkit/latest/tools/aml/lib64:/usr/local/Ascend/ascend-toolkit/latest/tools/aml/lib64/plugin:/usr/local/Ascend/ascend-toolkit/latest/lib64:/usr/local/Ascend/ascend-toolkit/latest/lib64/plugin/opskernel:/usr/local/Ascend/ascend-toolkit/latest/lib64/plugin/nnengine:/usr/local/Ascend/ascend-toolkit/latest/opp/built-in/op_impl/ai_core/tbe/op_tiling:/usr/local/Ascend/driver/lib64:/usr/local/Ascend/driver/lib64/common/:/usr/local/Ascend/driver/lib64/driver/:/usr/local/python3.11.14/lib:
ASCEND_AICPU_PATH=/usr/local/Ascend/cann-8.5.0
ATB_STREAM_SYNC_EVERY_OPERATION_ENABLE=0
ASCEND_HOME_PATH=/usr/local/Ascend/cann-8.5.0
ATB_MATMUL_SHUFFLE_K_ENABLE=1
ATB_WORKSPACE_MEM_ALLOC_ALG_TYPE=1
ATB_SHARE_MEMORY_NAME_SUFFIX=
TORCH_DEVICE_BACKEND_AUTOLOAD=1
PYTORCH_NVML_BASED_CUDA_CHECK=1
TORCHINDUCTOR_COMPILE_THREADS=1


NPU:
+------------------------------------------------------------------------------------------------+
| npu-smi 24.1.rc3                 Version: 24.1.rc3                                             |
+---------------------------+---------------+----------------------------------------------------+
| NPU   Name                | Health        | Power(W)    Temp(C)           Hugepages-Usage(page)|
| Chip                      | Bus-Id        | AICore(%)   Memory-Usage(MB)  HBM-Usage(MB)        |
+===========================+===============+====================================================+
| 0     910B2               | OK            | 92.6        38                0    / 0             |
| 0                         | 0000:C1:00.0  | 0           0    / 0          3404 / 65536         |
+===========================+===============+====================================================+
| 1     910B2               | OK            | 94.0        39                0    / 0             |
| 0                         | 0000:C2:00.0  | 0           0    / 0          3401 / 65536         |
+===========================+===============+====================================================+
| 2     910B2               | OK            | 89.8        36                0    / 0             |
| 0                         | 0000:81:00.0  | 0           0    / 0          3402 / 65536         |
+===========================+===============+====================================================+
| 3     910B2               | OK            | 96.1        37                0    / 0             |
| 0                         | 0000:82:00.0  | 0           0    / 0          3403 / 65536         |
+===========================+===============+====================================================+
| 4     910B2               | OK            | 96.2        42                0    / 0             |
| 0                         | 0000:01:00.0  | 0           0    / 0          3402 / 65536         |
+===========================+===============+====================================================+
| 5     910B2               | OK            | 97.7        42                0    / 0             |
| 0                         | 0000:02:00.0  | 0           0    / 0          3402 / 65536         |
+===========================+===============+====================================================+
| 6     910B2               | OK            | 92.5        41                0    / 0             |
| 0                         | 0000:41:00.0  | 0           0    / 0          3403 / 65536         |
+===========================+===============+====================================================+
| 7     910B2               | OK            | 93.9        43                0    / 0             |
| 0                         | 0000:42:00.0  | 0           0    / 0          3401 / 65536         |
+===========================+===============+====================================================+
+---------------------------+---------------+----------------------------------------------------+
| NPU     Chip              | Process id    | Process name             | Process memory(MB)      |
+===========================+===============+====================================================+
| No running processes found in NPU 0                                                            |
+===========================+===============+====================================================+
| No running processes found in NPU 1                                                            |
+===========================+===============+====================================================+
| No running processes found in NPU 2                                                            |
+===========================+===============+====================================================+
| No running processes found in NPU 3                                                            |
+===========================+===============+====================================================+
| No running processes found in NPU 4                                                            |
+===========================+===============+====================================================+
| No running processes found in NPU 5                                                            |
+===========================+===============+====================================================+
| No running processes found in NPU 6                                                            |
+===========================+===============+====================================================+
| No running processes found in NPU 7                                                            |
+===========================+===============+====================================================+

CANN:
package_name=Ascend-cann-toolkit
version=8.5.0
innerversion=V100R001C25SPC001B232
compatible_version=[V100R001C15],[V100R001C18],[V100R001C19],[V100R001C20],[V100R001C21],[V100R001C23]
arch=aarch64
os=linux
path=/usr/local/Ascend/cann-8.5.0
```
# 从机
```
root@bms-61552410:/workspace# python collect_env.py
Collecting environment information...
PyTorch version: 2.9.0+cpu
Is debug build: False

OS: Ubuntu 22.04.5 LTS (aarch64)
GCC version: (Ubuntu 11.4.0-1ubuntu1~22.04.2) 11.4.0
Clang version: 15.0.7
CMake version: version 4.2.1
Libc version: glibc-2.35

Python version: 3.11.14 (main, Jan 19 2026, 07:36:53) [GCC 11.4.0] (64-bit runtime)
Python platform: Linux-5.10.0-221.0.0.120.oe2203sp4.aarch64-aarch64-with-glibc2.35

CPU:
Architecture:                       aarch64
CPU op-mode(s):                     64-bit
Byte Order:                         Little Endian
CPU(s):                             192
On-line CPU(s) list:                0-191
Vendor ID:                          HiSilicon
Model name:                         Kunpeng-920
Model:                              0
Thread(s) per core:                 1
Core(s) per cluster:                48
Socket(s):                          -
Cluster(s):                         4
Stepping:                           0x1
BogoMIPS:                           200.00
Flags:                              fp asimd evtstrm aes pmull sha1 sha2 crc32 atomics fphp asimdhp cpuid asimdrdm jscvt fcma dcpop asimddp asimdfhm ssbs
L1d cache:                          12 MiB (192 instances)
L1i cache:                          12 MiB (192 instances)
L2 cache:                           96 MiB (192 instances)
L3 cache:                           192 MiB (8 instances)
NUMA node(s):                       8
NUMA node0 CPU(s):                  0-23
NUMA node1 CPU(s):                  24-47
NUMA node2 CPU(s):                  48-71
NUMA node3 CPU(s):                  72-95
NUMA node4 CPU(s):                  96-119
NUMA node5 CPU(s):                  120-143
NUMA node6 CPU(s):                  144-167
NUMA node7 CPU(s):                  168-191
Vulnerability Gather data sampling: Not affected
Vulnerability Itlb multihit:        Not affected
Vulnerability L1tf:                 Not affected
Vulnerability Mds:                  Not affected
Vulnerability Meltdown:             Not affected
Vulnerability Mmio stale data:      Not affected
Vulnerability Retbleed:             Not affected
Vulnerability Spec rstack overflow: Not affected
Vulnerability Spec store bypass:    Mitigation; Speculative Store Bypass disabled via prctl
Vulnerability Spectre v1:           Mitigation; __user pointer sanitization
Vulnerability Spectre v2:           Not affected
Vulnerability Srbds:                Not affected
Vulnerability Tsx async abort:      Not affected

Versions of relevant libraries:
[pip3] numpy==1.26.4
[pip3] pyzmq==27.1.0
[pip3] torch==2.9.0+cpu
[pip3] torch_npu==2.9.0
[pip3] torchvision==0.24.0
[pip3] transformers==4.57.6
[conda] Could not collect
vLLM Version: 0.14.1
vLLM Ascend Version: 0.14.0rc1

ENV Variables:
ASCEND_TOOLKIT_LATEST_HOME=/usr/local/Ascend/ascend-toolkit/latest
ATB_OPSRUNNER_KERNEL_CACHE_LOCAL_COUNT=1
ATB_STREAM_SYNC_EVERY_RUNNER_ENABLE=0
ATB_STREAM_SYNC_EVERY_KERNEL_ENABLE=0
ATB_OPSRUNNER_KERNEL_CACHE_GLOABL_COUNT=5
PYTORCH_NPU_ALLOC_CONF=expandable_segments:True
ATB_HOME_PATH=/usr/local/Ascend/nnal/atb/latest/atb/cxx_abi_1
ASCEND_TOOLKIT_HOME=/usr/local/Ascend/cann-8.5.0
ATB_COMPARE_TILING_EVERY_KERNEL=0
ASCEND_OPP_PATH=/usr/local/Ascend/cann-8.5.0/opp
LD_LIBRARY_PATH=/usr/local/Ascend/nnal/atb/latest/atb/cxx_abi_1/lib:/usr/local/Ascend/nnal/atb/latest/atb/cxx_abi_1/examples:/usr/local/Ascend/nnal/atb/latest/atb/cxx_abi_1/tests/atbopstest:/usr/local/Ascend/cann-8.5.0/lib64:/usr/local/Ascend/cann-8.5.0/lib64/plugin/opskernel:/usr/local/Ascend/cann-8.5.0/lib64/plugin/nnengine:/usr/local/Ascend/cann-8.5.0/opp/built-in/op_impl/ai_core/tbe/op_tiling/lib/linux/aarch64:/usr/local/Ascend/cann-8.5.0/tools/aml/lib64:/usr/local/Ascend/cann-8.5.0/tools/aml/lib64/plugin:/usr/local/Ascend/driver/lib64:/usr/local/Ascend/driver/lib64/common:/usr/local/Ascend/driver/lib64/driver:/usr/local/Ascend/nnal/atb/latest/atb/cxx_abi_1/lib:/usr/local/Ascend/nnal/atb/latest/atb/cxx_abi_1/examples:/usr/local/Ascend/nnal/atb/latest/atb/cxx_abi_1/tests/atbopstest:/usr/local/Ascend/driver/lib64:/usr/local/Ascend/driver/lib64/common:/usr/local/Ascend/driver/lib64/driver:/usr/local/Ascend/nnal/atb/latest/atb/cxx_abi_1/lib:/usr/local/Ascend/nnal/atb/latest/atb/cxx_abi_1/examples:/usr/local/Ascend/nnal/atb/latest/atb/cxx_abi_1/tests/atbopstest:/usr/local/Ascend/ascend-toolkit/latest/tools/aml/lib64:/usr/local/Ascend/ascend-toolkit/latest/tools/aml/lib64/plugin:/usr/local/Ascend/ascend-toolkit/latest/lib64:/usr/local/Ascend/ascend-toolkit/latest/lib64/plugin/opskernel:/usr/local/Ascend/ascend-toolkit/latest/lib64/plugin/nnengine:/usr/local/Ascend/ascend-toolkit/latest/opp/built-in/op_impl/ai_core/tbe/op_tiling:/usr/local/Ascend/driver/lib64:/usr/local/Ascend/driver/lib64/common/:/usr/local/Ascend/driver/lib64/driver/:/usr/local/python3.11.14/lib:
ASCEND_AICPU_PATH=/usr/local/Ascend/cann-8.5.0
ATB_STREAM_SYNC_EVERY_OPERATION_ENABLE=0
ASCEND_HOME_PATH=/usr/local/Ascend/cann-8.5.0
ATB_MATMUL_SHUFFLE_K_ENABLE=1
ATB_WORKSPACE_MEM_ALLOC_ALG_TYPE=1
ATB_SHARE_MEMORY_NAME_SUFFIX=
TORCH_DEVICE_BACKEND_AUTOLOAD=1
PYTORCH_NVML_BASED_CUDA_CHECK=1
TORCHINDUCTOR_COMPILE_THREADS=1


NPU:
+------------------------------------------------------------------------------------------------+
| npu-smi 25.3.rc1                 Version: 25.3.rc1                                             |
+---------------------------+---------------+----------------------------------------------------+
| NPU   Name                | Health        | Power(W)    Temp(C)           Hugepages-Usage(page)|
| Chip                      | Bus-Id        | AICore(%)   Memory-Usage(MB)  HBM-Usage(MB)        |
+===========================+===============+====================================================+
| 0     910B2               | OK            | 93.9        37                0    / 0             |
| 0                         | 0000:C1:00.0  | 0           0    / 0          3442 / 65536         |
+===========================+===============+====================================================+
| 1     910B2               | OK            | 95.1        37                0    / 0             |
| 0                         | 0000:C2:00.0  | 0           0    / 0          3439 / 65536         |
+===========================+===============+====================================================+
| 2     910B2               | OK            | 89.9        36                0    / 0             |
| 0                         | 0000:81:00.0  | 0           0    / 0          3440 / 65536         |
+===========================+===============+====================================================+
| 3     910B2               | OK            | 90.3        37                0    / 0             |
| 0                         | 0000:82:00.0  | 0           0    / 0          3438 / 65536         |
+===========================+===============+====================================================+
| 4     910B2               | OK            | 97.2        41                0    / 0             |
| 0                         | 0000:01:00.0  | 0           0    / 0          3437 / 65536         |
+===========================+===============+====================================================+
| 5     910B2               | OK            | 92.7        41                0    / 0             |
| 0                         | 0000:02:00.0  | 0           0    / 0          3438 / 65536         |
+===========================+===============+====================================================+
| 6     910B2               | OK            | 99.4        41                0    / 0             |
| 0                         | 0000:41:00.0  | 0           0    / 0          3438 / 65536         |
+===========================+===============+====================================================+
| 7     910B2               | OK            | 101.1       44                0    / 0             |
| 0                         | 0000:42:00.0  | 0           0    / 0          3439 / 65536         |
+===========================+===============+====================================================+
+---------------------------+---------------+----------------------------------------------------+
| NPU     Chip              | Process id    | Process name             | Process memory(MB)      |
+===========================+===============+====================================================+
| No running processes found in NPU 0                                                            |
+===========================+===============+====================================================+
| No running processes found in NPU 1                                                            |
+===========================+===============+====================================================+
| No running processes found in NPU 2                                                            |
+===========================+===============+====================================================+
| No running processes found in NPU 3                                                            |
+===========================+===============+====================================================+
| No running processes found in NPU 4                                                            |
+===========================+===============+====================================================+
| No running processes found in NPU 5                                                            |
+===========================+===============+====================================================+
| No running processes found in NPU 6                                                            |
+===========================+===============+====================================================+
| No running processes found in NPU 7                                                            |
+===========================+===============+====================================================+

CANN:
package_name=Ascend-cann-toolkit
version=8.5.0
innerversion=V100R001C25SPC001B232
compatible_version=[V100R001C15],[V100R001C18],[V100R001C19],[V100R001C20],[V100R001C21],[V100R001C23]
arch=aarch64
os=linux
path=/usr/local/Ascend/cann-8.5.0
```

### 🐛 Describe the bug

双机器启动，参考：https://docs.vllm.ai/projects/ascend/en/latest/tutorials/DeepSeek-V3.2.html
权重使用量化的DeepSeek-V3.2-Exp-w8a8

```
export IMAGE=quay.io/ascend/vllm-ascend:v0.14.0rc1
docker run --rm \
    --name vllm-ascend \
    --shm-size=1g \
    --net=host \
    --device /dev/davinci0 \
    --device /dev/davinci1 \
    --device /dev/davinci2 \
    --device /dev/davinci3 \
    --device /dev/davinci4 \
    --device /dev/davinci5 \
    --device /dev/davinci6 \
    --device /dev/davinci7 \
    --device /dev/davinci_manager \
    --device /dev/devmm_svm \
    --device /dev/hisi_hdc \
    -v /usr/local/dcmi:/usr/local/dcmi \
    -v /usr/local/Ascend/driver/tools/hccn_tool:/usr/local/Ascend/driver/tools/hccn_tool \
    -v /usr/local/bin/npu-smi:/usr/local/bin/npu-smi \
    -v /usr/local/Ascend/driver/lib64/:/usr/local/Ascend/driver/lib64/ \
    -v /usr/local/Ascend/driver/version.info:/usr/local/Ascend/driver/version.info \
    -v /etc/ascend_install.info:/etc/ascend_install.info \
    -v /root/.cache:/root/.cache \
    -v /data1:/data1 \
    -v /data2:/data2 \
    -it $IMAGE bash





nic_name=data1.1044
local_ip=10.17.44.64
node0_ip=10.17.44.64

export HCCL_OP_EXPANSION_MODE="AIV"

export HCCL_IF_IP=$local_ip
export GLOO_SOCKET_IFNAME=$nic_name
export TP_SOCKET_IFNAME=$nic_name
export HCCL_SOCKET_IFNAME=$nic_name
export OMP_PROC_BIND=false
export OMP_NUM_THREADS=100
export VLLM_USE_V1=1
export HCCL_BUFFSIZE=200
export VLLM_ASCEND_ENABLE_MLAPO=1
export PYTORCH_NPU_ALLOC_CONF=expandable_segments:True
export VLLM_ASCEND_ENABLE_FLASHCOMM1=0
export HCCL_CONNECT_TIMEOUT=120
export HCCL_INTRA_PCIE_ENABLE=1
export HCCL_INTRA_ROCE_ENABLE=0


vllm serve /data1/models/DeepSeek-V3.2-Exp-w8a8/ \
--host 0.0.0.0 \
--port 8077 \
--data-parallel-size 2 \
--data-parallel-size-local 1 \
--data-parallel-address $node0_ip \
--data-parallel-rpc-port 13389 \
--tensor-parallel-size 8 \
--quantization ascend \
--seed 1024 \
--served-model-name deepseek_v3_2 \
--enable-expert-parallel \
--max-num-seqs 16 \
--max-model-len 8192 \
--max-num-batched-tokens 4096 \
--trust-remote-code \
--no-enable-prefix-caching \
--gpu-memory-utilization 0.92 \
--compilation-config '{"cudagraph_mode": "FULL_DECODE_ONLY", "cudagraph_capture_sizes":[3,6,9,12,15,18,21,24,27,30,33,36,39,42,45,48]}' \
--speculative-config '{"num_speculative_tokens": 2, "method": "deepseek_mtp"}'







nic_name=data1.1044
local_ip=10.17.44.60
node0_ip=10.17.44.64

export HCCL_OP_EXPANSION_MODE="AIV"

export HCCL_IF_IP=$local_ip
export GLOO_SOCKET_IFNAME=$nic_name
export TP_SOCKET_IFNAME=$nic_name
export HCCL_SOCKET_IFNAME=$nic_name
export OMP_PROC_BIND=false
export OMP_NUM_THREADS=100
export VLLM_USE_V1=1
export HCCL_BUFFSIZE=200
export VLLM_ASCEND_ENABLE_MLAPO=1
export PYTORCH_NPU_ALLOC_CONF=expandable_segments:True
export VLLM_ASCEND_ENABLE_FLASHCOMM1=0
export HCCL_CONNECT_TIMEOUT=120
export HCCL_INTRA_PCIE_ENABLE=1
export HCCL_INTRA_ROCE_ENABLE=0


vllm serve /data1/models/DeepSeek-V3.2-Exp-w8a8/ \
--host 0.0.0.0 \
--port 8077 \
--headless \
--data-parallel-size 2 \
--data-parallel-size-local 1 \
--data-parallel-start-rank 1 \
--data-parallel-address $node0_ip \
--data-parallel-rpc-port 13389 \
--tensor-parallel-size 8 \
--quantization ascend \
--seed 1024 \
--served-model-name deepseek_v3_2 \
--enable-expert-parallel \
--max-num-seqs 16 \
--max-model-len 8192 \
--max-num-batched-tokens 4096 \
--trust-remote-code \
--no-enable-prefix-caching \
--gpu-memory-utilization 0.92 \
--compilation-config '{"cudagraph_mode": "FULL_DECODE_ONLY", "cudagraph_capture_sizes":[3,6,9,12,15,18,21,24,27,30,33,36,39,42,45,48]}' \
--speculative-config '{"num_speculative_tokens": 2, "method": "deepseek_mtp"}'
```
报错：
```
[rank0]:[E126 10:59:03.013424380 compiler_depend.ts:444] checkUceErrAndRepair:build/CMakeFiles/torch_npu.dir/compiler_depend.ts:224 NPU error, error code is 507899
[ERROR] 2026-01-26-10:59:03 (PID:3821, Device:0, RankID:-1) ERR00100 PTA call acl api failed
[Error]: An internal error occurs in the Driver module.
        Rectify the fault based on the error information in the ascend log.
[PID: 3821] 2026-01-26-10:59:00.475.179 Invalid_Argument(EL0003): The argument is invalid.
        Solution: Try again with a valid argument.
        TraceBack (most recent call last):
        The error from device(chipId:0, dieId:0), serial number is 3, there is an exception of fftsplus aivector error, core id is 3, error code = 0x800000, dump info: pc start: 0x12c083d09af0, current: 0x12c083d0e43c, vec error info: 0x8d00000061, mte error info: 0x3903010403, ifu error info: 0x76c331f981040, ccu error info: 0x41315e860b800013, cube error info: 0, biu error info: 0, aic error mask: 0x6500020bd00028c, para base: 0x12c140001080.[FUNC:PrintCoreInfo][FILE:device_error_core_proc.cc][LINE:347]
        The extend info: errcode:(0x800000, 0, 0) errorStr: The DDR address of the MTE instruction is out of range. fixp_error0 info: 0x3010403, fixp_error1 info: 0x39, fsmId:0, tslot:1, thread:0, ctxid:0, blk:34, sublk:0, subErrType:4.[FUNC:PrintCoreInfo][FILE:device_error_core_proc.cc][LINE:360]
        Kernel task happen error, retCode=0x26, [aicore exception].[FUNC:PreCheckTaskErr][FILE:davinci_kernel_task.cc][LINE:1493]
        The argument is invalid.
        rtMemGetInfoByType execution failed, reason=driver error:invalid handle[FUNC:FuncErrorReason][FILE:error_message_manage.cc][LINE:61]
        dsa task submit failed, streamId=2, taskId=0, retCode=0x7010026[FUNC:LaunchRandomNumTask][FILE:context.cc][LINE:3711]
        rtsLaunchRandomNumTask execution failed, reason=device mem error[FUNC:FuncErrorReason][FILE:error_message_manage.cc][LINE:61]
        call rtsLaunchRandomNumTask failed, runtime result = 507053.[FUNC:ReportCallError][FILE:log_inner.cpp][LINE:148]
        rtsLaunchRandomNumTask failed, runtime error code: 507053
        Distribute failed
        DSA task distribute error.
        launch failed for DSARandomNormal, errno:561000.
        rtGetMemUceInfo execution failed, reason=driver error:internal error[FUNC:FuncErrorReason][FILE:error_message_manage.cc][LINE:61]
        [Call][Rts]call rts api [rtGetMemUceInfo] failed, retCode is 507899[FUNC:ReportCallError][FILE:log_inner.cpp][LINE:148]

Exception raised from checkUceErrAndRepair at build/CMakeFiles/torch_npu.dir/compiler_depend.ts:230 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) + 0xb0 (0xffffaca9c700 in /usr/local/python3.11.14/lib/python3.11/site-packages/torch/lib/libc10.so)
frame #1: c10::detail::torchCheckFail(char const*, char const*, unsigned int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) + 0x68 (0xffffaca3a860 in /usr/local/python3.11.14/lib/python3.11/site-packages/torch/lib/libc10.so)
frame #2: <unknown function> + 0xa2f220 (0xfffe3690f220 in /usr/local/python3.11.14/lib/python3.11/site-packages/torch_npu/lib/libtorch_npu.so)
frame #3: <unknown function> + 0xa2f42c (0xfffe3690f42c in /usr/local/python3.11.14/lib/python3.11/site-packages/torch_npu/lib/libtorch_npu.so)
frame #4: std::_Function_handler<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > (int), std::_Bind<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > (*(std::_Placeholder<1>))(int)> >::_M_invoke(std::_Any_data const&, int&&) + 0x38 (0xfffe3690fd58 in /usr/local/python3.11.14/lib/python3.11/site-packages/torch_npu/lib/libtorch_npu.so)
frame #5: <unknown function> + 0xa2c4a0 (0xfffe3690c4a0 in /usr/local/python3.11.14/lib/python3.11/site-packages/torch_npu/lib/libtorch_npu.so)
frame #6: <unknown function> + 0x1bc9f94 (0xfffe37aa9f94 in /usr/local/python3.11.14/lib/python3.11/site-packages/torch_npu/lib/libtorch_npu.so)
frame #7: <unknown function> + 0x2c77e24 (0xfffe38b57e24 in /usr/local/python3.11.14/lib/python3.11/site-packages/torch_npu/lib/libtorch_npu.so)
frame #8: <unknown function> + 0xa607d0 (0xfffe369407d0 in /usr/local/python3.11.14/lib/python3.11/site-packages/torch_npu/lib/libtorch_npu.so)
frame #9: <unknown function> + 0xa613ac (0xfffe369413ac in /usr/local/python3.11.14/lib/python3.11/site-packages/torch_npu/lib/libtorch_npu.so)
frame #10: <unknown function> + 0xa5f2c8 (0xfffe3693f2c8 in /usr/local/python3.11.14/lib/python3.11/site-packages/torch_npu/lib/libtorch_npu.so)
frame #11: <unknown function> + 0xd29cc (0xffffbaaa29cc in /lib/aarch64-linux-gnu/libstdc++.so.6)
frame #12: <unknown function> + 0x80398 (0xffffbac80398 in /lib/aarch64-linux-gnu/libc.so.6)
frame #13: <unknown function> + 0xe9e9c (0xffffbace9e9c in /lib/aarch64-linux-gnu/libc.so.6)

(Worker_DP0_TP0_EP0 pid=3821) ERROR 01-26 10:59:03 [multiproc_executor.py:822] WorkerProc hit an exception.
(Worker_DP0_TP0_EP0 pid=3821) ERROR 01-26 10:59:03 [multiproc_executor.py:822] Traceback (most recent call last):
(Worker_DP0_TP0_EP0 pid=3821) ERROR 01-26 10:59:03 [multiproc_executor.py:822]   File "/vllm-workspace/vllm/vllm/v1/executor/multiproc_executor.py", line 817, in worker_busy_loop
(Worker_DP0_TP0_EP0 pid=3821) ERROR 01-26 10:59:03 [multiproc_executor.py:822]     output = func(*args, **kwargs)
(Worker_DP0_TP0_EP0 pid=3821) ERROR 01-26 10:59:03 [multiproc_executor.py:822]              ^^^^^^^^^^^^^^^^^^^^^
(Worker_DP0_TP0_EP0 pid=3821) ERROR 01-26 10:59:03 [multiproc_executor.py:822]   File "/usr/local/python3.11.14/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 120, in decorate_context
(Worker_DP0_TP0_EP0 pid=3821) ERROR 01-26 10:59:03 [multiproc_executor.py:822]     return func(*args, **kwargs)
(Worker_DP0_TP0_EP0 pid=3821) ERROR 01-26 10:59:03 [multiproc_executor.py:822]            ^^^^^^^^^^^^^^^^^^^^^
(Worker_DP0_TP0_EP0 pid=3821) ERROR 01-26 10:59:03 [multiproc_executor.py:822]   File "/vllm-workspace/vllm-ascend/vllm_ascend/worker/worker.py", line 262, in determine_available_memory
(Worker_DP0_TP0_EP0 pid=3821) ERROR 01-26 10:59:03 [multiproc_executor.py:822]     self.model_runner.profile_run()
(Worker_DP0_TP0_EP0 pid=3821) ERROR 01-26 10:59:03 [multiproc_executor.py:822]   File "/vllm-workspace/vllm-ascend/vllm_ascend/worker/model_runner_v1.py", line 2176, in profile_run
(Worker_DP0_TP0_EP0 pid=3821) ERROR 01-26 10:59:03 [multiproc_executor.py:822]     super().profile_run()
(Worker_DP0_TP0_EP0 pid=3821) ERROR 01-26 10:59:03 [multiproc_executor.py:822]   File "/vllm-workspace/vllm/vllm/v1/worker/gpu_model_runner.py", line 4750, in profile_run
(Worker_DP0_TP0_EP0 pid=3821) ERROR 01-26 10:59:03 [multiproc_executor.py:822]     output = self._dummy_sampler_run(last_hidden_states)
(Worker_DP0_TP0_EP0 pid=3821) ERROR 01-26 10:59:03 [multiproc_executor.py:822]              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(Worker_DP0_TP0_EP0 pid=3821) ERROR 01-26 10:59:03 [multiproc_executor.py:822]   File "/usr/local/python3.11.14/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 120, in decorate_context
(Worker_DP0_TP0_EP0 pid=3821) ERROR 01-26 10:59:03 [multiproc_executor.py:822]     return func(*args, **kwargs)
(Worker_DP0_TP0_EP0 pid=3821) ERROR 01-26 10:59:03 [multiproc_executor.py:822]            ^^^^^^^^^^^^^^^^^^^^^
(Worker_DP0_TP0_EP0 pid=3821) ERROR 01-26 10:59:03 [multiproc_executor.py:822]   File "/vllm-workspace/vllm-ascend/vllm_ascend/worker/model_runner_v1.py", line 2158, in _dummy_sampler_run
(Worker_DP0_TP0_EP0 pid=3821) ERROR 01-26 10:59:03 [multiproc_executor.py:822]     hidden_states = hidden_states[logit_indices]
(Worker_DP0_TP0_EP0 pid=3821) ERROR 01-26 10:59:03 [multiproc_executor.py:822]                     ~~~~~~~~~~~~~^^^^^^^^^^^^^^^
(Worker_DP0_TP0_EP0 pid=3821) ERROR 01-26 10:59:03 [multiproc_executor.py:822] RuntimeError: The Inner error is reported as above. The process exits for this inner error, and the current working operator name is aclnnInplaceNormal.
(Worker_DP0_TP0_EP0 pid=3821) ERROR 01-26 10:59:03 [multiproc_executor.py:822] Since the operator is called asynchronously, the stacktrace may be inaccurate. If you want to get the accurate stacktrace, please set the environment variable ASCEND_LAUNCH_BLOCKING=1.
(Worker_DP0_TP0_EP0 pid=3821) ERROR 01-26 10:59:03 [multiproc_executor.py:822] Note: ASCEND_LAUNCH_BLOCKING=1 will force ops to run in synchronous mode, resulting in performance degradation. Please unset ASCEND_LAUNCH_BLOCKING in time after debugging.
(Worker_DP0_TP0_EP0 pid=3821) ERROR 01-26 10:59:03 [multiproc_executor.py:822] [ERROR] 2026-01-26-10:59:03 (PID:3821, Device:0, RankID:-1) ERR00100 PTA call acl api failed.
(Worker_DP0_TP0_EP0 pid=3821) ERROR 01-26 10:59:03 [multiproc_executor.py:822]
(Worker_DP0_TP0_EP0 pid=3821) ERROR 01-26 10:59:03 [multiproc_executor.py:822] Traceback (most recent call last):
(Worker_DP0_TP0_EP0 pid=3821) ERROR 01-26 10:59:03 [multiproc_executor.py:822]   File "/vllm-workspace/vllm/vllm/v1/executor/multiproc_executor.py", line 817, in worker_busy_loop
(Worker_DP0_TP0_EP0 pid=3821) ERROR 01-26 10:59:03 [multiproc_executor.py:822]     output = func(*args, **kwargs)
(Worker_DP0_TP0_EP0 pid=3821) ERROR 01-26 10:59:03 [multiproc_executor.py:822]              ^^^^^^^^^^^^^^^^^^^^^
(Worker_DP0_TP0_EP0 pid=3821) ERROR 01-26 10:59:03 [multiproc_executor.py:822]   File "/usr/local/python3.11.14/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 120, in decorate_context
(Worker_DP0_TP0_EP0 pid=3821) ERROR 01-26 10:59:03 [multiproc_executor.py:822]     return func(*args, **kwargs)
(Worker_DP0_TP0_EP0 pid=3821) ERROR 01-26 10:59:03 [multiproc_executor.py:822]            ^^^^^^^^^^^^^^^^^^^^^
(Worker_DP0_TP0_EP0 pid=3821) ERROR 01-26 10:59:03 [multiproc_executor.py:822]   File "/vllm-workspace/vllm-ascend/vllm_ascend/worker/worker.py", line 262, in determine_available_memory
(Worker_DP0_TP0_EP0 pid=3821) ERROR 01-26 10:59:03 [multiproc_executor.py:822]     self.model_runner.profile_run()
(Worker_DP0_TP0_EP0 pid=3821) ERROR 01-26 10:59:03 [multiproc_executor.py:822]   File "/vllm-workspace/vllm-ascend/vllm_ascend/worker/model_runner_v1.py", line 2176, in profile_run
(Worker_DP0_TP0_EP0 pid=3821) ERROR 01-26 10:59:03 [multiproc_executor.py:822]     super().profile_run()
(Worker_DP0_TP0_EP0 pid=3821) ERROR 01-26 10:59:03 [multiproc_executor.py:822]   File "/vllm-workspace/vllm/vllm/v1/worker/gpu_model_runner.py", line 4750, in profile_run
(Worker_DP0_TP0_EP0 pid=3821) ERROR 01-26 10:59:03 [multiproc_executor.py:822]     output = self._dummy_sampler_run(last_hidden_states)
(Worker_DP0_TP0_EP0 pid=3821) ERROR 01-26 10:59:03 [multiproc_executor.py:822]              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(Worker_DP0_TP0_EP0 pid=3821) ERROR 01-26 10:59:03 [multiproc_executor.py:822]   File "/usr/local/python3.11.14/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 120, in decorate_context
(Worker_DP0_TP0_EP0 pid=3821) ERROR 01-26 10:59:03 [multiproc_executor.py:822]     return func(*args, **kwargs)
(Worker_DP0_TP0_EP0 pid=3821) ERROR 01-26 10:59:03 [multiproc_executor.py:822]            ^^^^^^^^^^^^^^^^^^^^^
(Worker_DP0_TP0_EP0 pid=3821) ERROR 01-26 10:59:03 [multiproc_executor.py:822]   File "/vllm-workspace/vllm-ascend/vllm_ascend/worker/model_runner_v1.py", line 2158, in _dummy_sampler_run
(Worker_DP0_TP0_EP0 pid=3821) ERROR 01-26 10:59:03 [multiproc_executor.py:822]     hidden_states = hidden_states[logit_indices]
(Worker_DP0_TP0_EP0 pid=3821) ERROR 01-26 10:59:03 [multiproc_executor.py:822]                     ~~~~~~~~~~~~~^^^^^^^^^^^^^^^
(Worker_DP0_TP0_EP0 pid=3821) ERROR 01-26 10:59:03 [multiproc_executor.py:822] RuntimeError: The Inner error is reported as above. The process exits for this inner error, and the current working operator name is aclnnInplaceNormal.
(Worker_DP0_TP0_EP0 pid=3821) ERROR 01-26 10:59:03 [multiproc_executor.py:822] Since the operator is called asynchronously, the stacktrace may be inaccurate. If you want to get the accurate stacktrace, please set the environment variable ASCEND_LAUNCH_BLOCKING=1.
(Worker_DP0_TP0_EP0 pid=3821) ERROR 01-26 10:59:03 [multiproc_executor.py:822] Note: ASCEND_LAUNCH_BLOCKING=1 will force ops to run in synchronous mode, resulting in performance degradation. Please unset ASCEND_LAUNCH_BLOCKING in time after debugging.
(Worker_DP0_TP0_EP0 pid=3821) ERROR 01-26 10:59:03 [multiproc_executor.py:822] [ERROR] 2026-01-26-10:59:03 (PID:3821, Device:0, RankID:-1) ERR00100 PTA call acl api failed.
(Worker_DP0_TP0_EP0 pid=3821) ERROR 01-26 10:59:03 [multiproc_executor.py:822]
```

**Comment by LoganJane** [comment]
@gbdjxgp This issue has been resolved in the latest version. Please use the latest release or rc version (https://github.com/vllm-project/vllm-ascend/releases). If the issue persists, feel free to submit a new issue.
