### ISSUE TITLE
[Bug]: NPU function error when using Llama-3.1-8B-Instruct with eagle3 and long seq_lens prompt

### ISSUE THREAD

**Issue by zhaomingyu13** [vllm-project/vllm-ascend#6359]
### Your current environment

<details>
<summary>The output of `python collect_env.py`</summary>

```text
Collecting environment information...
PyTorch version: 2.8.0+cpu
Is debug build: False

OS: Ubuntu 24.04.3 LTS (aarch64)
GCC version: (Ubuntu 13.3.0-6ubuntu2~24.04) 13.3.0
Clang version: Could not collect
CMake version: version 4.2.1
Libc version: glibc-2.39

Python version: 3.11.10 (main, Jan 24 2026, 12:54:22) [GCC 13.3.0] (64-bit runtime)
Python platform: Linux-5.10.0-216.0.0.115.oe2203sp4.aarch64-aarch64-with-glibc2.39

CPU:
Architecture:                       aarch64
CPU op-mode(s):                     64-bit
Byte Order:                         Little Endian
CPU(s):                             640
On-line CPU(s) list:                0-639
Vendor ID:                          HiSilicon
BIOS Vendor ID:                     HiSilicon
Model name:                         -
BIOS Model name:                    Kunpeng 920 7285Z To be filled by O.E.M. CPU @ 3.0GHz
BIOS CPU family:                    280
Model:                              0
Thread(s) per core:                 2
Core(s) per socket:                 80
Socket(s):                          4
Stepping:                           0x0
Frequency boost:                    disabled
CPU(s) scaling MHz:                 100%
CPU max MHz:                        3000.0000
CPU min MHz:                        400.0000
BogoMIPS:                           200.00
Flags:                              fp asimd evtstrm aes pmull sha1 sha2 crc32 atomics fphp asimdhp cpuid asimdrdm jscvt fcma lrcpc dcpop sha3 sm3 sm4 asimddp sha512 sve asimdfhm dit uscat ilrcpc flagm ssbs sb dcpodp flagm2 frint svei8mm svef32mm svef64mm svebf16 i8mm bf16 dgh rng ecv
L1d cache:                          20 MiB (320 instances)
L1i cache:                          20 MiB (320 instances)
L2 cache:                           400 MiB (320 instances)
L3 cache:                           560 MiB (8 instances)
NUMA node(s):                       8
NUMA node0 CPU(s):                  0-79
NUMA node1 CPU(s):                  80-159
NUMA node2 CPU(s):                  160-239
NUMA node3 CPU(s):                  240-319
NUMA node4 CPU(s):                  320-399
NUMA node5 CPU(s):                  400-479
NUMA node6 CPU(s):                  480-559
NUMA node7 CPU(s):                  560-639
Vulnerability Gather data sampling: Not affected
Vulnerability Itlb multihit:        Not affected
Vulnerability L1tf:                 Not affected
Vulnerability Mds:                  Not affected
Vulnerability Meltdown:             Not affected
Vulnerability Mmio stale data:      Not affected
Vulnerability Retbleed:             Not affected
Vulnerability Spec rstack overflow: Not affected
Vulnerability Spec store bypass:    Mitigation; Speculative Store Bypass disabled via prctl
Vulnerability Spectre v1:           Mitigation; __user pointer sanitization
Vulnerability Spectre v2:           Not affected
Vulnerability Srbds:                Not affected
Vulnerability Tsx async abort:      Not affected

Versions of relevant libraries:
[pip3] numpy==1.26.4
[pip3] pyzmq==27.1.0
[pip3] torch==2.8.0
[pip3] torch_npu==2.8.0.post2
[pip3] torchvision==0.23.0
[pip3] transformers==4.57.6
[conda] Could not collect
vLLM Version: 0.13.0
vLLM Ascend Version: 0.13.0rc3.dev3+g014cab31a.d20260127 (git sha: 014cab31a, date: 20260127)

ENV Variables:
ATB_OPSRUNNER_KERNEL_CACHE_TILING_SIZE=10240
ATB_OPSRUNNER_KERNEL_CACHE_LOCAL_COUNT=1
ATB_STREAM_SYNC_EVERY_RUNNER_ENABLE=0
ATB_OPSRUNNER_SETUP_CACHE_ENABLE=1
ATB_WORKSPACE_MEM_ALLOC_GLOBAL=0
ATB_DEVICE_TILING_BUFFER_BLOCK_NUM=32
ATB_STREAM_SYNC_EVERY_KERNEL_ENABLE=0
ATB_OPSRUNNER_KERNEL_CACHE_GLOABL_COUNT=5
ATB_HOME_PATH=/usr/local/Ascend/nnal/atb/latest/atb/cxx_abi_1
ASCEND_TOOLKIT_HOME=/usr/local/Ascend/cann-8.5.0
ATB_COMPARE_TILING_EVERY_KERNEL=0
ASCEND_OPP_PATH=/usr/local/Ascend/cann-8.5.0/opp
LD_LIBRARY_PATH=/usr/local/Ascend/nnal/atb/latest/atb/cxx_abi_0/lib:/usr/local/Ascend/nnal/atb/latest/atb/cxx_abi_0/examples:/usr/local/Ascend/nnal/atb/latest/atb/cxx_abi_0/tests/atbopstest:/usr/local/Ascend/ascend-toolkit/latest/tools/aml/lib64:/usr/local/Ascend/ascend-toolkit/latest/tools/aml/lib64/plugin:/usr/local/Ascend/ascend-toolkit/latest/lib64:/usr/local/Ascend/ascend-toolkit/latest/lib64/plugin/opskernel:/usr/local/Ascend/ascend-toolkit/latest/lib64/plugin/nnengine:/usr/local/Ascend/ascend-toolkit/latest/opp/built-in/op_impl/ai_core/tbe/op_tiling:/usr/local/Ascend/driver/lib64/common/:/usr/local/Ascend/driver/lib64/driver/:/usr/local/Ascend/nnal/atb/latest/atb/cxx_abi_0/lib:/usr/local/Ascend/nnal/atb/latest/atb/cxx_abi_0/examples:/usr/local/Ascend/nnal/atb/latest/atb/cxx_abi_0/tests/atbopstest:/usr/local/Ascend/ascend-toolkit/latest/tools/aml/lib64:/usr/local/Ascend/ascend-toolkit/latest/tools/aml/lib64/plugin:/usr/local/Ascend/ascend-toolkit/latest/lib64/plugin/nnengine:/usr/local/Ascend/ascend-toolkit/latest/opp/built-in/op_impl/ai_core/tbe/op_tiling/lib/linux/:/usr/local/Ascend/ascend-toolkit/latest/lib64:/usr/local/Ascend/ascend-toolkit/latest/lib64/plugin/opskernel:/usr/local/Ascend/driver/lib64/driver:/usr/local/Ascend/driver/lib64/common:/usr/local/lib::/usr/local/Ascend/driver/lib64/driver:/usr/local/Ascend/driver/lib64/common:/usr/local/lib::/usr/local/Ascend/ascend-toolkit/latest/aarch64-linux/devlib
ASCEND_AICPU_PATH=/usr/local/Ascend/cann-8.5.0
ATB_OPSRUNNER_KERNEL_CACHE_TYPE=3
ATB_RUNNER_POOL_SIZE=64
ATB_STREAM_SYNC_EVERY_OPERATION_ENABLE=0
ASCEND_HOME_PATH=/usr/local/Ascend/cann-8.5.0
ATB_MATMUL_SHUFFLE_K_ENABLE=1
ATB_LAUNCH_KERNEL_WITH_TILING=1
ATB_WORKSPACE_MEM_ALLOC_ALG_TYPE=1
ATB_HOST_TILING_BUFFER_BLOCK_NUM=128
ATB_SHARE_MEMORY_NAME_SUFFIX=
TORCH_DEVICE_BACKEND_AUTOLOAD=1
PYTORCH_NVML_BASED_CUDA_CHECK=1
TORCHINDUCTOR_COMPILE_THREADS=1


NPU:
+------------------------------------------------------------------------------------------------+
| npu-smi 25.5.0                   Version: 25.5.0                                               |
+---------------------------+---------------+----------------------------------------------------+
| NPU   Name                | Health        | Power(W)    Temp(C)           Hugepages-Usage(page)|
| Chip  Phy-ID              | Bus-Id        | AICore(%)   Memory-Usage(MB)  HBM-Usage(MB)        |
+===========================+===============+====================================================+
| 0     Ascend910           | OK            | 163.4       29                0    / 0             |
| 0     0                   | 0000:9D:00.0  | 0           0    / 0          3145 / 65536         |
+------------------------------------------------------------------------------------------------+
| 0     Ascend910           | OK            | -           30                0    / 0             |
| 1     1                   | 0000:9F:00.0  | 0           0    / 0          2886 / 65536         |
+===========================+===============+====================================================+
| 1     Ascend910           | OK            | 164.4       29                0    / 0             |
| 0     2                   | 0000:99:00.0  | 0           0    / 0          3153 / 65536         |
+------------------------------------------------------------------------------------------------+
| 1     Ascend910           | OK            | -           29                0    / 0             |
| 1     3                   | 0000:9B:00.0  | 0           0    / 0          2874 / 65536         |
+===========================+===============+====================================================+
| 2     Ascend910           | OK            | 164.4       29                0    / 0             |
| 0     4                   | 0000:95:00.0  | 0           0    / 0          3140 / 65536         |
+------------------------------------------------------------------------------------------------+
| 2     Ascend910           | OK            | -           30                0    / 0             |
| 1     5                   | 0000:97:00.0  | 0           0    / 0          2876 / 65536         |
+===========================+===============+====================================================+
| 3     Ascend910           | OK            | 160.2       28                0    / 0             |
| 0     6                   | 0000:91:00.0  | 0           0    / 0          3122 / 65536         |
+------------------------------------------------------------------------------------------------+
| 3     Ascend910           | OK            | -           29                0    / 0             |
| 1     7                   | 0000:93:00.0  | 0           0    / 0          2882 / 65536         |
+===========================+===============+====================================================+
| 4     Ascend910           | OK            | 159.8       29                0    / 0             |
| 0     8                   | 0000:8D:00.0  | 0           0    / 0          56289/ 65536         |
+------------------------------------------------------------------------------------------------+
| 4     Ascend910           | OK            | -           29                0    / 0             |
| 1     9                   | 0000:8F:00.0  | 0           0    / 0          56005/ 65536         |
+===========================+===============+====================================================+
| 5     Ascend910           | OK            | 157.0       30                0    / 0             |
| 0     10                  | 0000:89:00.0  | 0           0    / 0          56265/ 65536         |
+------------------------------------------------------------------------------------------------+
| 5     Ascend910           | OK            | -           29                0    / 0             |
| 1     11                  | 0000:8B:00.0  | 0           0    / 0          56007/ 65536         |
+===========================+===============+====================================================+
| 6     Ascend910           | OK            | 160.8       28                0    / 0             |
| 0     12                  | 0000:85:00.0  | 0           0    / 0          2896 / 65536         |
+------------------------------------------------------------------------------------------------+
| 6     Ascend910           | OK            | -           28                0    / 0             |
| 1     13                  | 0000:87:00.0  | 0           0    / 0          2882 / 65536         |
+===========================+===============+====================================================+
| 7     Ascend910           | OK            | 152.2       29                0    / 0             |
| 0     14                  | 0000:81:00.0  | 0           0    / 0          2908 / 65536         |
+------------------------------------------------------------------------------------------------+
| 7     Ascend910           | OK            | -           29                0    / 0             |
| 1     15                  | 0000:83:00.0  | 0           0    / 0          2870 / 65536         |
+===========================+===============+====================================================+
+---------------------------+---------------+----------------------------------------------------+
| NPU     Chip              | Process id    | Process name             | Process memory(MB)      |
+===========================+===============+====================================================+
| No running processes found in NPU 0                                                            |
+===========================+===============+====================================================+
| No running processes found in NPU 1                                                            |
+===========================+===============+====================================================+
| No running processes found in NPU 2                                                            |
+===========================+===============+====================================================+
| No running processes found in NPU 3                                                            |
+===========================+===============+====================================================+
| 4       0                 | 3716946       |                          | 53176                   |
| 4       1                 | 3716947       |                          | 53176                   |
+===========================+===============+====================================================+
| 5       0                 | 3716948       |                          | 53176                   |
| 5       1                 | 3716949       |                          | 53175                   |
+===========================+===============+====================================================+
| No running processes found in NPU 6                                                            |
+===========================+===============+====================================================+
| No running processes found in NPU 7                                                            |
+===========================+===============+====================================================+

CANN:
package_name=Ascend-cann-toolkit
version=8.5.0
innerversion=V100R001C25SPC001B232
compatible_version=[V100R001C15],[V100R001C18],[V100R001C19],[V100R001C20],[V100R001C21],[V100R001C23]
arch=aarch64
os=linux
path=/usr/local/Ascend/cann-8.5.0
```

</details>

### 🐛 Describe the bug

```python
import os
from vllm import LLM, SamplingParams
os.environ["ASCEND_LAUNCH_BLOCKING"] = "1"
os.environ["VLLM_LOGGING_LEVEL"] = "DEBUG"

prompts = [
   {"role": "user", "content": "Please introduce Hangzhou!"*400},
]
sampling_params = SamplingParams(temperature=0.8, top_p=0.95)

llm = LLM(
    enforce_eager=True,
    model="meta-llama/Meta-Llama-3.1-8B-Instruct",
    tensor_parallel_size=1,
    gpu_memory_utilization=0.95,
    max_model_len=32768,
    max_num_batched_tokens=32768,
    speculative_config={
        "method": "eagle3",
        "model": "yuhuili/EAGLE3-LLaMA3.1-Instruct-8B",
        "draft_tensor_parallel_size": 1,
        "num_speculative_tokens": 3,
    },
)

outputs = llm.generate(prompts, sampling_params)

for output in outputs:
    prompt = output.prompt
    generated_text = output.outputs[0].text
    print(f"Prompt: {prompt!r}, Generated text: {generated_text!r}")
```
and the problem is here:

> INFO 01-28 17:23:20 [__init__.py:43] Available plugins for group vllm.platform_plugins:
INFO 01-28 17:23:20 [__init__.py:45] - ascend -> vllm_ascend:register
INFO 01-28 17:23:20 [__init__.py:48] All plugins in this group will be loaded. Set `VLLM_PLUGINS` to control which plugins to load.
INFO 01-28 17:23:20 [__init__.py:217] Platform plugin ascend is activated
INFO 01-28 17:23:24 [__init__.py:108] Registered model loader `<class 'vllm_ascend.model_loader.netloader.netloader.ModelNetLoaderElastic'>` with load format `netloader`
INFO 01-28 17:23:24 [utils.py:253] non-default args: {'max_model_len': 32768, 'gpu_memory_utilization': 0.95, 'max_num_batched_tokens': 32768, 'max_num_seqs': 4, 'enforce_eager': True, 'speculative_config': {'enforce_eager': False, 'method': 'eagle3', 'model': '/workspace/model/EAGLE3-LLaMA3.1-Instruct-8B', 'draft_tensor_parallel_size': 1, 'num_speculative_tokens': 3}, 'compilation_config': {'level': None, 'mode': None, 'debug_dump_path': None, 'cache_dir': '', 'compile_cache_save_format': 'binary', 'backend': 'vllm_ascend.compilation.compiler_interface.AscendCompiler', 'custom_ops': [], 'splitting_ops': None, 'compile_mm_encoder': False, 'compile_sizes': None, 'compile_ranges_split_points': None, 'inductor_compile_config': {'enable_auto_functionalized_v2': False}, 'inductor_passes': {}, 'cudagraph_mode': <CUDAGraphMode.FULL_DECODE_ONLY: (2, 0)>, 'cudagraph_num_of_warmups': 0, 'cudagraph_capture_sizes': [1, 3, 5, 10, 12, 23], 'cudagraph_copy_inputs': False, 'cudagraph_specialize_lora': True, 'use_inductor_graph_partition': None, 'pass_config': {}, 'max_cudagraph_capture_size': None, 'dynamic_shapes_config': {'type': <DynamicShapesType.BACKED: 'backed'>, 'evaluate_guards': False}, 'local_cache_dir': None}, 'model': '/workspace/model/Llama-3.1-8B-Instruct'}
INFO 01-28 17:23:24 [model.py:514] Resolved architecture: LlamaForCausalLM
INFO 01-28 17:23:24 [model.py:1661] Using max model len 32768
INFO 01-28 17:23:24 [model.py:514] Resolved architecture: LlamaForCausalLM
WARNING 01-28 17:23:24 [model.py:2005] Casting torch.float16 to torch.bfloat16.
INFO 01-28 17:23:24 [model.py:1661] Using max model len 2048
INFO 01-28 17:23:24 [scheduler.py:230] Chunked prefill is enabled with max_num_batched_tokens=32768.
WARNING 01-28 17:23:24 [vllm.py:622] Enforce eager set, overriding optimization level to -O0
INFO 01-28 17:23:24 [vllm.py:722] Cudagraph is disabled under eager mode
INFO 01-28 17:23:24 [ascend_config.py:55] Linear layer sharding enabled with config: None. Note: This feature works optimally with FLASHCOMM2 and DSA-CP enabled; using it without these features may result in significant performance degradation.
INFO 01-28 17:23:24 [platform.py:202] Compilation disabled, using eager mode by default
(EngineCore_DP0 pid=1878198) INFO 01-28 17:23:25 [core.py:93] Initializing a V1 LLM engine (v0.13.0) with config: model='/workspace/model/Llama-3.1-8B-Instruct', speculative_config=SpeculativeConfig(method='eagle3', model='/workspace/model/EAGLE3-LLaMA3.1-Instruct-8B', num_spec_tokens=3), tokenizer='/workspace/model/Llama-3.1-8B-Instruct', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, tokenizer_revision=None, trust_remote_code=False, dtype=torch.bfloat16, max_seq_len=32768, download_dir=None, load_format=auto, tensor_parallel_size=1, pipeline_parallel_size=1, data_parallel_size=1, disable_custom_all_reduce=True, quantization=None, enforce_eager=True, kv_cache_dtype=auto, device_config=npu, structured_outputs_config=StructuredOutputsConfig(backend='auto', disable_fallback=False, disable_any_whitespace=False, disable_additional_properties=False, reasoning_parser='', reasoning_parser_plugin='', enable_in_reasoning=False), observability_config=ObservabilityConfig(show_hidden_metrics_for_version=None, otlp_traces_endpoint=None, collect_detailed_traces=None, kv_cache_metrics=False, kv_cache_metrics_sample=0.01, cudagraph_metrics=False, enable_layerwise_nvtx_tracing=False), seed=0, served_model_name=/workspace/model/Llama-3.1-8B-Instruct, enable_prefix_caching=True, enable_chunked_prefill=True, pooler_config=None, compilation_config={'level': None, 'mode': <CompilationMode.NONE: 0>, 'debug_dump_path': None, 'cache_dir': '', 'compile_cache_save_format': 'binary', 'backend': 'vllm_ascend.compilation.compiler_interface.AscendCompiler', 'custom_ops': ['all'], 'splitting_ops': [], 'compile_mm_encoder': False, 'compile_sizes': [], 'compile_ranges_split_points': [32768], 'inductor_compile_config': {'enable_auto_functionalized_v2': False}, 'inductor_passes': {}, 'cudagraph_mode': <CUDAGraphMode.NONE: 0>, 'cudagraph_num_of_warmups': 1, 'cudagraph_capture_sizes': [], 'cudagraph_copy_inputs': False, 'cudagraph_specialize_lora': True, 'use_inductor_graph_partition': False, 'pass_config': {'fuse_norm_quant': False, 'fuse_act_quant': False, 'fuse_attn_quant': False, 'eliminate_noops': False, 'enable_sp': False, 'fuse_gemm_comms': False, 'fuse_allreduce_rms': False}, 'max_cudagraph_capture_size': 0, 'dynamic_shapes_config': {'type': <DynamicShapesType.BACKED: 'backed'>, 'evaluate_guards': False}, 'local_cache_dir': None}
(EngineCore_DP0 pid=1878198) INFO 01-28 17:23:27 [parallel_state.py:1203] world_size=1 rank=0 local_rank=0 distributed_init_method=tcp://141.61.81.162:53319 backend=hccl
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
(EngineCore_DP0 pid=1878198) INFO 01-28 17:23:27 [parallel_state.py:1411] rank 0 in world size 1 is assigned as DP rank 0, PP rank 0, PCP rank 0, TP rank 0, EP rank 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
(EngineCore_DP0 pid=1878198) WARNING 01-28 17:23:27 [__init__.py:204] min_p, logit_bias, and min_tokens parameters won't currently work with speculative decoding enabled.
(EngineCore_DP0 pid=1878198) WARNING 01-28 17:23:27 [__init__.py:204] min_p, logit_bias, and min_tokens parameters won't currently work with speculative decoding enabled.
(EngineCore_DP0 pid=1878198) INFO 01-28 17:23:27 [model_runner_v1.py:2369] Starting to load model /workspace/model/Llama-3.1-8B-Instruct...
Loading safetensors checkpoint shards:   0% Completed | 0/4 [00:00<?, ?it/s]
Loading safetensors checkpoint shards:  50% Completed | 2/4 [00:00<00:00,  3.78it/s]
Loading safetensors checkpoint shards:  75% Completed | 3/4 [00:01<00:00,  2.37it/s]
Loading safetensors checkpoint shards: 100% Completed | 4/4 [00:01<00:00,  2.00it/s]
Loading safetensors checkpoint shards: 100% Completed | 4/4 [00:01<00:00,  2.21it/s]
(EngineCore_DP0 pid=1878198) 
(EngineCore_DP0 pid=1878198) INFO 01-28 17:23:31 [default_loader.py:308] Loading weights took 2.10 seconds
(EngineCore_DP0 pid=1878198) INFO 01-28 17:23:31 [model_runner_v1.py:2376] Loading drafter model...
Loading pt checkpoint shards:   0% Completed | 0/1 [00:00<?, ?it/s]
Loading pt checkpoint shards: 100% Completed | 1/1 [00:00<00:00,  7.24it/s]
Loading pt checkpoint shards: 100% Completed | 1/1 [00:00<00:00,  7.23it/s]
(EngineCore_DP0 pid=1878198) 
(EngineCore_DP0 pid=1878198) INFO 01-28 17:23:31 [default_loader.py:308] Loading weights took 0.22 seconds
(EngineCore_DP0 pid=1878198) INFO 01-28 17:23:31 [eagle_proposer.py:236] Detected EAGLE model without its own embed_tokens in the checkpoint. Sharing target model embedding weights with the draft model.
(EngineCore_DP0 pid=1878198) INFO 01-28 17:23:31 [model_runner_v1.py:2386] Loading model weights took 15.7827 GB
(EngineCore_DP0 pid=1878198) INFO 01-28 17:23:36 [worker.py:302] Available memory: 35699365888, total memory: 65787658240
(EngineCore_DP0 pid=1878198) INFO 01-28 17:23:36 [kv_cache_utils.py:1291] GPU KV cache size: 264,064 tokens
(EngineCore_DP0 pid=1878198) INFO 01-28 17:23:36 [kv_cache_utils.py:1296] Maximum concurrency for 32,768 tokens per request: 8.06x
(EngineCore_DP0 pid=1878198) INFO 01-28 17:23:38 [core.py:259] init engine (profile, create kv cache, warmup model) took 6.96 seconds
(EngineCore_DP0 pid=1878198) WARNING 01-28 17:23:39 [vllm.py:629] Inductor compilation was disabled by user settings,Optimizations settings that are only active duringInductor compilation will be ignored.
(EngineCore_DP0 pid=1878198) INFO 01-28 17:23:39 [vllm.py:722] Cudagraph is disabled under eager mode
(EngineCore_DP0 pid=1878198) WARNING 01-28 17:23:39 [platform.py:475] Parameter '--all2all-backend' is set to 'flashinfer_all2allv', which may be incompatible with Ascend. Using internal plugin mechanisms.
(EngineCore_DP0 pid=1878198) INFO 01-28 17:23:39 [platform.py:202] Compilation disabled, using eager mode by default
INFO 01-28 17:23:39 [llm.py:360] Supported tasks: ['generate']
Adding requests: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 12.41it/s]
Processed prompts:   0%|                                                                           | 0/1 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]DumpHead: AIV-0, CoreType=AIV, block dim=4, total_block_num=4, block_remain_len=608, block_initial_space=1024, rsv=0, magic=5aa5bccd
[deprecated] NOTICE:assert has been deprecated, please use ascendc_assert instead! 
[ASSERT] /home/slave1/Ascend/8.5.0/opp/built-in/op_impl/ai_core/tbe/impl/dynamic/../ascendc/gather_v3/gather_v3_base.h:137: Assertion `(0 <= val && val < this->gxSize_)' Index 2048 out of range[0 2048)!
(EngineCore_DP0 pid=1878198) ERROR 01-28 17:23:40 [dump_input.py:72] Dumping input data for V1 LLM engine (v0.13.0) with config: model='/workspace/model/Llama-3.1-8B-Instruct', speculative_config=SpeculativeConfig(method='eagle3', model='/workspace/model/EAGLE3-LLaMA3.1-Instruct-8B', num_spec_tokens=3), tokenizer='/workspace/model/Llama-3.1-8B-Instruct', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, tokenizer_revision=None, trust_remote_code=False, dtype=torch.bfloat16, max_seq_len=32768, download_dir=None, load_format=auto, tensor_parallel_size=1, pipeline_parallel_size=1, data_parallel_size=1, disable_custom_all_reduce=True, quantization=None, enforce_eager=True, kv_cache_dtype=auto, device_config=npu, structured_outputs_config=StructuredOutputsConfig(backend='auto', disable_fallback=False, disable_any_whitespace=False, disable_additional_properties=False, reasoning_parser='', reasoning_parser_plugin='', enable_in_reasoning=False), observability_config=ObservabilityConfig(show_hidden_metrics_for_version=None, otlp_traces_endpoint=None, collect_detailed_traces=None, kv_cache_metrics=False, kv_cache_metrics_sample=0.01, cudagraph_metrics=False, enable_layerwise_nvtx_tracing=False), seed=0, served_model_name=/workspace/model/Llama-3.1-8B-Instruct, enable_prefix_caching=True, enable_chunked_prefill=True, pooler_config=None, compilation_config={'level': None, 'mode': <CompilationMode.NONE: 0>, 'debug_dump_path': None, 'cache_dir': '', 'compile_cache_save_format': 'binary', 'backend': 'vllm_ascend.compilation.compiler_interface.AscendCompiler', 'custom_ops': ['all'], 'splitting_ops': [], 'compile_mm_encoder': False, 'compile_sizes': [], 'compile_ranges_split_points': [32768], 'inductor_compile_config': {'enable_auto_functionalized_v2': False}, 'inductor_passes': {}, 'cudagraph_mode': <CUDAGraphMode.NONE: 0>, 'cudagraph_num_of_warmups': 1, 'cudagraph_capture_sizes': [], 'cudagraph_copy_inputs': False, 'cudagraph_specialize_lora': True, 'use_inductor_graph_partition': False, 'pass_config': {'fuse_norm_quant': False, 'fuse_act_quant': False, 'fuse_attn_quant': False, 'eliminate_noops': False, 'enable_sp': False, 'fuse_gemm_comms': False, 'fuse_allreduce_rms': False}, 'max_cudagraph_capture_size': 0, 'dynamic_shapes_config': {'type': <DynamicShapesType.BACKED: 'backed'>, 'evaluate_guards': False}, 'local_cache_dir': None}, 
(EngineCore_DP0 pid=1878198) ERROR 01-28 17:23:40 [dump_input.py:79] Dumping scheduler output for model execution: SchedulerOutput(scheduled_new_reqs=[], scheduled_cached_reqs=CachedRequestData(req_ids=['0'], resumed_req_ids=[], new_token_ids=[], all_token_ids={}, new_block_ids=[null], num_computed_tokens=[2043], num_output_tokens=[8]), num_scheduled_tokens={0: 4}, total_num_scheduled_tokens=4, scheduled_spec_decode_tokens={0: [11827, 382, 58138]}, scheduled_encoder_inputs={}, num_common_prefix_blocks=[17], finished_req_ids=[], free_encoder_mm_hashes=[], preempted_req_ids=[], pending_structured_output_tokens=false, kv_connector_metadata=null, ec_connector_metadata=null)
(EngineCore_DP0 pid=1878198) ERROR 01-28 17:23:40 [dump_input.py:81] Dumping scheduler stats: SchedulerStats(num_running_reqs=1, num_waiting_reqs=0, step_counter=0, current_wave=0, kv_cache_usage=0.008244422890397618, prefix_cache_stats=PrefixCacheStats(reset=False, requests=0, queries=0, hits=0, preempted_requests=0, preempted_queries=0, preempted_hits=0), connector_prefix_cache_stats=None, kv_cache_eviction_events=[], spec_decoding_stats=None, kv_connector_stats=None, waiting_lora_adapters={}, running_lora_adapters={}, cudagraph_stats=None)
(EngineCore_DP0 pid=1878198) ERROR 01-28 17:23:40 [patch_core.py:70] EngineCore encountered a fatal error.
(EngineCore_DP0 pid=1878198) ERROR 01-28 17:23:40 [patch_core.py:70] Traceback (most recent call last):
(EngineCore_DP0 pid=1878198) ERROR 01-28 17:23:40 [patch_core.py:70]   File "/workspace/vllm-workspace/vllm-ascend/vllm_ascend/patch/platform/patch_core.py", line 61, in run_engine_core
(EngineCore_DP0 pid=1878198) ERROR 01-28 17:23:40 [patch_core.py:70]     engine_core.run_busy_loop()
(EngineCore_DP0 pid=1878198) ERROR 01-28 17:23:40 [patch_core.py:70]   File "/workspace/vllm-workspace/vllm/vllm/v1/engine/core.py", line 886, in run_busy_loop
(EngineCore_DP0 pid=1878198) ERROR 01-28 17:23:40 [patch_core.py:70]     self._process_engine_step()
(EngineCore_DP0 pid=1878198) ERROR 01-28 17:23:40 [patch_core.py:70]   File "/workspace/vllm-workspace/vllm/vllm/v1/engine/core.py", line 919, in _process_engine_step
(EngineCore_DP0 pid=1878198) ERROR 01-28 17:23:40 [patch_core.py:70]     outputs, model_executed = self.step_fn()
(EngineCore_DP0 pid=1878198) ERROR 01-28 17:23:40 [patch_core.py:70]                               ^^^^^^^^^^^^^^
(EngineCore_DP0 pid=1878198) ERROR 01-28 17:23:40 [patch_core.py:70]   File "/workspace/vllm-workspace/vllm/vllm/v1/engine/core.py", line 353, in step
(EngineCore_DP0 pid=1878198) ERROR 01-28 17:23:40 [patch_core.py:70]     model_output = self.model_executor.sample_tokens(grammar_output)
(EngineCore_DP0 pid=1878198) ERROR 01-28 17:23:40 [patch_core.py:70]                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(EngineCore_DP0 pid=1878198) ERROR 01-28 17:23:40 [patch_core.py:70]   File "/workspace/vllm-workspace/vllm/vllm/v1/executor/uniproc_executor.py", line 110, in sample_tokens
(EngineCore_DP0 pid=1878198) ERROR 01-28 17:23:40 [patch_core.py:70]     return self.collective_rpc(
(EngineCore_DP0 pid=1878198) ERROR 01-28 17:23:40 [patch_core.py:70]            ^^^^^^^^^^^^^^^^^^^^
(EngineCore_DP0 pid=1878198) ERROR 01-28 17:23:40 [patch_core.py:70]   File "/workspace/vllm-workspace/vllm/vllm/v1/executor/uniproc_executor.py", line 75, in collective_rpc
(EngineCore_DP0 pid=1878198) ERROR 01-28 17:23:40 [patch_core.py:70]     result = run_method(self.driver_worker, method, args, kwargs)
(EngineCore_DP0 pid=1878198) ERROR 01-28 17:23:40 [patch_core.py:70]              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(EngineCore_DP0 pid=1878198) ERROR 01-28 17:23:40 [patch_core.py:70]   File "/workspace/vllm-workspace/vllm/vllm/v1/serial_utils.py", line 461, in run_method
(EngineCore_DP0 pid=1878198) ERROR 01-28 17:23:40 [patch_core.py:70]     return func(*args, **kwargs)
(EngineCore_DP0 pid=1878198) ERROR 01-28 17:23:40 [patch_core.py:70]            ^^^^^^^^^^^^^^^^^^^^^
(EngineCore_DP0 pid=1878198) ERROR 01-28 17:23:40 [patch_core.py:70]   File "/usr/local/python3.11.10/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 120, in decorate_context
(EngineCore_DP0 pid=1878198) ERROR 01-28 17:23:40 [patch_core.py:70]     return func(*args, **kwargs)
(EngineCore_DP0 pid=1878198) ERROR 01-28 17:23:40 [patch_core.py:70]            ^^^^^^^^^^^^^^^^^^^^^
(EngineCore_DP0 pid=1878198) ERROR 01-28 17:23:40 [patch_core.py:70]   File "/workspace/vllm-workspace/vllm-ascend/vllm_ascend/worker/worker.py", line 362, in sample_tokens
(EngineCore_DP0 pid=1878198) ERROR 01-28 17:23:40 [patch_core.py:70]     return self.model_runner.sample_tokens(grammar_output)
(EngineCore_DP0 pid=1878198) ERROR 01-28 17:23:40 [patch_core.py:70]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(EngineCore_DP0 pid=1878198) ERROR 01-28 17:23:40 [patch_core.py:70]   File "/usr/local/python3.11.10/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 120, in decorate_context
(EngineCore_DP0 pid=1878198) ERROR 01-28 17:23:40 [patch_core.py:70]     return func(*args, **kwargs)
(EngineCore_DP0 pid=1878198) ERROR 01-28 17:23:40 [patch_core.py:70]            ^^^^^^^^^^^^^^^^^^^^^
(EngineCore_DP0 pid=1878198) ERROR 01-28 17:23:40 [patch_core.py:70]   File "/workspace/vllm-workspace/vllm-ascend/vllm_ascend/worker/model_runner_v1.py", line 1735, in sample_tokens
(EngineCore_DP0 pid=1878198) ERROR 01-28 17:23:40 [patch_core.py:70]     propose_draft_token_ids(sampler_output.sampled_token_ids)
(EngineCore_DP0 pid=1878198) ERROR 01-28 17:23:40 [patch_core.py:70]   File "/workspace/vllm-workspace/vllm-ascend/vllm_ascend/worker/model_runner_v1.py", line 1699, in propose_draft_token_ids
(EngineCore_DP0 pid=1878198) ERROR 01-28 17:23:40 [patch_core.py:70]     self._draft_token_ids = self.propose_draft_token_ids(
(EngineCore_DP0 pid=1878198) ERROR 01-28 17:23:40 [patch_core.py:70]                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(EngineCore_DP0 pid=1878198) ERROR 01-28 17:23:40 [patch_core.py:70]   File "/workspace/vllm-workspace/vllm-ascend/vllm_ascend/worker/model_runner_v1.py", line 1448, in propose_draft_token_ids
(EngineCore_DP0 pid=1878198) ERROR 01-28 17:23:40 [patch_core.py:70]     draft_token_ids = self.drafter._propose(
(EngineCore_DP0 pid=1878198) ERROR 01-28 17:23:40 [patch_core.py:70]                       ^^^^^^^^^^^^^^^^^^^^^^
(EngineCore_DP0 pid=1878198) ERROR 01-28 17:23:40 [patch_core.py:70]   File "/workspace/vllm-workspace/vllm-ascend/vllm_ascend/spec_decode/eagle_proposer.py", line 545, in _propose
(EngineCore_DP0 pid=1878198) ERROR 01-28 17:23:40 [patch_core.py:70]     draft_token_ids = self._runnable(
(EngineCore_DP0 pid=1878198) ERROR 01-28 17:23:40 [patch_core.py:70]                       ^^^^^^^^^^^^^^^
(EngineCore_DP0 pid=1878198) ERROR 01-28 17:23:40 [patch_core.py:70]   File "/workspace/vllm-workspace/vllm-ascend/vllm_ascend/spec_decode/eagle_proposer.py", line 647, in _run_merged_draft
(EngineCore_DP0 pid=1878198) ERROR 01-28 17:23:40 [patch_core.py:70]     update_cos_sin(self.positions[:input_batch_size])
(EngineCore_DP0 pid=1878198) ERROR 01-28 17:23:40 [patch_core.py:70]   File "/workspace/vllm-workspace/vllm-ascend/vllm_ascend/ops/rotary_embedding.py", line 160, in update_cos_sin
(EngineCore_DP0 pid=1878198) ERROR 01-28 17:23:40 [patch_core.py:70]     _cos[:, :num_tokens] = _cos_sin_cache.index_select(0, positions).view(
(EngineCore_DP0 pid=1878198) ERROR 01-28 17:23:40 [patch_core.py:70]                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(EngineCore_DP0 pid=1878198) ERROR 01-28 17:23:40 [patch_core.py:70] RuntimeError: RunOpApiV2:build/CMakeFiles/torch_npu.dir/compiler_depend.ts:256 NPU function error: c10_npu::acl::AclrtSynchronizeStreamWithTimeout(stream), error code is 507035
(EngineCore_DP0 pid=1878198) ERROR 01-28 17:23:40 [patch_core.py:70] [ERROR] 2026-01-28-17:23:40 (PID:1878198, Device:0, RankID:-1) ERR00100 PTA call acl api failed
(EngineCore_DP0 pid=1878198) ERROR 01-28 17:23:40 [patch_core.py:70] [Error]: The vector core execution is abnormal. 
(EngineCore_DP0 pid=1878198) ERROR 01-28 17:23:40 [patch_core.py:70]         Rectify the fault based on the error information in the ascend log.
(EngineCore_DP0 pid=1878198) ERROR 01-28 17:23:40 [patch_core.py:70] EZ9999: Inner Error!
(EngineCore_DP0 pid=1878198) ERROR 01-28 17:23:40 [patch_core.py:70] EZ9999[PID: 1878198] 2026-01-28-17:23:40.501.863 (EZ9999):  The error from device(chipId:2, dieId:0), serial number is 13, there is an exception of aivec error, core id is 43, error code = 0, dump info: pc start: 0x12c08127bb74, current: 0x12c08127c4a4, vec error info: 0xf30a11426d, mte error info: 0xf2713e38ae, ifu error info: 0x138760f46bf80, ccu error info: 0x8040211877982668, cube error info: 0, biu error info: 0, aic error mask: 0x6500020bd00028c, para base: 0x12c100485400.[FUNC:PrintCoreInfo][FILE:device_error_core_proc.cc][LINE:347]
(EngineCore_DP0 pid=1878198) ERROR 01-28 17:23:40 [patch_core.py:70]         TraceBack (most recent call last):
(EngineCore_DP0 pid=1878198) ERROR 01-28 17:23:40 [patch_core.py:70]        The extend info: errcode:(0, 0, 0) errorStr: timeout or trap error. fixp_error0 info: 0x13e38ae, fixp_error1 info: 0xf2, fsmId:1, tslot:0, thread:0, ctxid:0, blk:0, sublk:0, subErrType:2.[FUNC:PrintCoreInfo][FILE:device_error_core_proc.cc][LINE:360]
(EngineCore_DP0 pid=1878198) ERROR 01-28 17:23:40 [patch_core.py:70]        Kernel task happen error, retCode=0x31, [vector core exception].[FUNC:PreCheckTaskErr][FILE:davinci_kernel_task.cc][LINE:1493]
(EngineCore_DP0 pid=1878198) ERROR 01-28 17:23:40 [patch_core.py:70]        rtStreamSynchronizeWithTimeout execution failed, reason=vector core exception[FUNC:FuncErrorReason][FILE:error_message_manage.cc][LINE:61]
(EngineCore_DP0 pid=1878198) ERROR 01-28 17:23:40 [patch_core.py:70]        synchronize stream with timeout failed, runtime result = 507035[FUNC:ReportCallError][FILE:log_inner.cpp][LINE:148]
(EngineCore_DP0 pid=1878198) ERROR 01-28 17:23:40 [patch_core.py:70] 
(EngineCore_DP0 pid=1878198) Process EngineCore_DP0:
Traceback (most recent call last):
  File "/home/z30075380/run/cos_sin_cache.py", line 83, in <module>
    outputs = llm.generate(prompts, sampling_params)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/vllm-workspace/vllm/vllm/entrypoints/llm.py", line 449, in generate
    outputs = self._run_engine(use_tqdm=use_tqdm)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/vllm-workspace/vllm/vllm/entrypoints/llm.py", line 1760, in _run_engine
    step_outputs = self.llm_engine.step()
                   ^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/vllm-workspace/vllm/vllm/v1/engine/llm_engine.py", line 293, in step
(EngineCore_DP0 pid=1878198) Traceback (most recent call last):
    outputs = self.engine_core.get_output()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/vllm-workspace/vllm/vllm/v1/engine/core_client.py", line 717, in get_output
    raise self._format_exception(outputs) from None
vllm.v1.engine.exceptions.EngineDeadError: EngineCore encountered an issue. See stack trace (above) for the root cause.
(EngineCore_DP0 pid=1878198)   File "/usr/local/python3.11.10/lib/python3.11/multiprocessing/process.py", line 314, in _bootstrap
(EngineCore_DP0 pid=1878198)     self.run()
(EngineCore_DP0 pid=1878198)   File "/usr/local/python3.11.10/lib/python3.11/multiprocessing/process.py", line 108, in run
(EngineCore_DP0 pid=1878198)     self._target(*self._args, **self._kwargs)
(EngineCore_DP0 pid=1878198)   File "/workspace/vllm-workspace/vllm-ascend/vllm_ascend/patch/platform/patch_core.py", line 72, in run_engine_core
(EngineCore_DP0 pid=1878198)     raise e
(EngineCore_DP0 pid=1878198)   File "/workspace/vllm-workspace/vllm-ascend/vllm_ascend/patch/platform/patch_core.py", line 61, in run_engine_core
(EngineCore_DP0 pid=1878198)     engine_core.run_busy_loop()
(EngineCore_DP0 pid=1878198)   File "/workspace/vllm-workspace/vllm/vllm/v1/engine/core.py", line 886, in run_busy_loop
(EngineCore_DP0 pid=1878198)     self._process_engine_step()
(EngineCore_DP0 pid=1878198)   File "/workspace/vllm-workspace/vllm/vllm/v1/engine/core.py", line 919, in _process_engine_step
(EngineCore_DP0 pid=1878198)     outputs, model_executed = self.step_fn()
(EngineCore_DP0 pid=1878198)                               ^^^^^^^^^^^^^^
(EngineCore_DP0 pid=1878198)   File "/workspace/vllm-workspace/vllm/vllm/v1/engine/core.py", line 353, in step
(EngineCore_DP0 pid=1878198)     model_output = self.model_executor.sample_tokens(grammar_output)
(EngineCore_DP0 pid=1878198)                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(EngineCore_DP0 pid=1878198)   File "/workspace/vllm-workspace/vllm/vllm/v1/executor/uniproc_executor.py", line 110, in sample_tokens
(EngineCore_DP0 pid=1878198)     return self.collective_rpc(
(EngineCore_DP0 pid=1878198)            ^^^^^^^^^^^^^^^^^^^^
(EngineCore_DP0 pid=1878198)   File "/workspace/vllm-workspace/vllm/vllm/v1/executor/uniproc_executor.py", line 75, in collective_rpc
(EngineCore_DP0 pid=1878198)     result = run_method(self.driver_worker, method, args, kwargs)
(EngineCore_DP0 pid=1878198)              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(EngineCore_DP0 pid=1878198)   File "/workspace/vllm-workspace/vllm/vllm/v1/serial_utils.py", line 461, in run_method
(EngineCore_DP0 pid=1878198)     return func(*args, **kwargs)
(EngineCore_DP0 pid=1878198)            ^^^^^^^^^^^^^^^^^^^^^
(EngineCore_DP0 pid=1878198)   File "/usr/local/python3.11.10/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 120, in decorate_context
(EngineCore_DP0 pid=1878198)     return func(*args, **kwargs)
(EngineCore_DP0 pid=1878198)            ^^^^^^^^^^^^^^^^^^^^^
(EngineCore_DP0 pid=1878198)   File "/workspace/vllm-workspace/vllm-ascend/vllm_ascend/worker/worker.py", line 362, in sample_tokens
(EngineCore_DP0 pid=1878198)     return self.model_runner.sample_tokens(grammar_output)
(EngineCore_DP0 pid=1878198)            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(EngineCore_DP0 pid=1878198)   File "/usr/local/python3.11.10/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 120, in decorate_context
(EngineCore_DP0 pid=1878198)     return func(*args, **kwargs)
(EngineCore_DP0 pid=1878198)            ^^^^^^^^^^^^^^^^^^^^^
(EngineCore_DP0 pid=1878198)   File "/workspace/vllm-workspace/vllm-ascend/vllm_ascend/worker/model_runner_v1.py", line 1735, in sample_tokens
(EngineCore_DP0 pid=1878198)     propose_draft_token_ids(sampler_output.sampled_token_ids)
(EngineCore_DP0 pid=1878198)   File "/workspace/vllm-workspace/vllm-ascend/vllm_ascend/worker/model_runner_v1.py", line 1699, in propose_draft_token_ids
(EngineCore_DP0 pid=1878198)     self._draft_token_ids = self.propose_draft_token_ids(
(EngineCore_DP0 pid=1878198)                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(EngineCore_DP0 pid=1878198)   File "/workspace/vllm-workspace/vllm-ascend/vllm_ascend/worker/model_runner_v1.py", line 1448, in propose_draft_token_ids
(EngineCore_DP0 pid=1878198)     draft_token_ids = self.drafter._propose(
(EngineCore_DP0 pid=1878198)                       ^^^^^^^^^^^^^^^^^^^^^^
(EngineCore_DP0 pid=1878198)   File "/workspace/vllm-workspace/vllm-ascend/vllm_ascend/spec_decode/eagle_proposer.py", line 545, in _propose
(EngineCore_DP0 pid=1878198)     draft_token_ids = self._runnable(
(EngineCore_DP0 pid=1878198)                       ^^^^^^^^^^^^^^^
(EngineCore_DP0 pid=1878198)   File "/workspace/vllm-workspace/vllm-ascend/vllm_ascend/spec_decode/eagle_proposer.py", line 647, in _run_merged_draft
(EngineCore_DP0 pid=1878198)     update_cos_sin(self.positions[:input_batch_size])
(EngineCore_DP0 pid=1878198)   File "/workspace/vllm-workspace/vllm-ascend/vllm_ascend/ops/rotary_embedding.py", line 160, in update_cos_sin
(EngineCore_DP0 pid=1878198)     _cos[:, :num_tokens] = _cos_sin_cache.index_select(0, positions).view(
(EngineCore_DP0 pid=1878198)                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(EngineCore_DP0 pid=1878198) RuntimeError: RunOpApiV2:build/CMakeFiles/torch_npu.dir/compiler_depend.ts:256 NPU function error: c10_npu::acl::AclrtSynchronizeStreamWithTimeout(stream), error code is 507035
(EngineCore_DP0 pid=1878198) [ERROR] 2026-01-28-17:23:40 (PID:1878198, Device:0, RankID:-1) ERR00100 PTA call acl api failed
(EngineCore_DP0 pid=1878198) [Error]: The vector core execution is abnormal. 
(EngineCore_DP0 pid=1878198)         Rectify the fault based on the error information in the ascend log.
(EngineCore_DP0 pid=1878198) EZ9999: Inner Error!
(EngineCore_DP0 pid=1878198) EZ9999[PID: 1878198] 2026-01-28-17:23:40.501.863 (EZ9999):  The error from device(chipId:2, dieId:0), serial number is 13, there is an exception of aivec error, core id is 43, error code = 0, dump info: pc start: 0x12c08127bb74, current: 0x12c08127c4a4, vec error info: 0xf30a11426d, mte error info: 0xf2713e38ae, ifu error info: 0x138760f46bf80, ccu error info: 0x8040211877982668, cube error info: 0, biu error info: 0, aic error mask: 0x6500020bd00028c, para base: 0x12c100485400.[FUNC:PrintCoreInfo][FILE:device_error_core_proc.cc][LINE:347]
(EngineCore_DP0 pid=1878198)         TraceBack (most recent call last):
(EngineCore_DP0 pid=1878198)        The extend info: errcode:(0, 0, 0) errorStr: timeout or trap error. fixp_error0 info: 0x13e38ae, fixp_error1 info: 0xf2, fsmId:1, tslot:0, thread:0, ctxid:0, blk:0, sublk:0, subErrType:2.[FUNC:PrintCoreInfo][FILE:device_error_core_proc.cc][LINE:360]
(EngineCore_DP0 pid=1878198)        Kernel task happen error, retCode=0x31, [vector core exception].[FUNC:PreCheckTaskErr][FILE:davinci_kernel_task.cc][LINE:1493]
(EngineCore_DP0 pid=1878198)        rtStreamSynchronizeWithTimeout execution failed, reason=vector core exception[FUNC:FuncErrorReason][FILE:error_message_manage.cc][LINE:61]
(EngineCore_DP0 pid=1878198)        synchronize stream with timeout failed, runtime result = 507035[FUNC:ReportCallError][FILE:log_inner.cpp][LINE:148]
(EngineCore_DP0 pid=1878198) 
[ERROR] 2026-01-28-17:23:40 (PID:1877804, Device:-1, RankID:-1) ERR99999 UNKNOWN applicaiton exception
Processed prompts:   0%|                                                                           | 0/1 [00:02<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]
sys:1: DeprecationWarning: builtin type swigvarlink has no __module__ attribute

**Comment by ClientHello-PSK** [comment]
@zhaomingyu13 This issue has been resolved in the latest version. Please use the latest release or rc version (https://github.com/vllm-project/vllm-ascend/releases). If the issue persists, feel free to submit a new issue.
