### ISSUE TITLE
[Bug]: A2尝试四机部署GLM5-bf16失败，报错：NPU function error: call aclnnSwiGlu failed, error code is 507014

### ISSUE THREAD

**Issue by HusterYoung** [vllm-project/vllm-ascend#6875]
### Your current environment

<details>
<summary>The output of `python collect_env.py`</summary>

```text
Collecting environment information...
PyTorch version: 2.9.0+cpu
Is debug build: False

OS: Ubuntu 22.04.5 LTS (aarch64)
GCC version: (Ubuntu 11.4.0-1ubuntu1~22.04.2) 11.4.0
Clang version: 15.0.7
CMake version: version 4.2.1
Libc version: glibc-2.35

Python version: 3.11.14 (main, Jan 19 2026, 07:36:53) [GCC 11.4.0] (64-bit runtime)
Python platform: Linux-4.19.90-vhulk2211.3.0.h1543.eulerosv2r10.aarch64-aarch64-with-glibc2.35

CPU:
Architecture:                    aarch64
CPU op-mode(s):                  64-bit
Byte Order:                      Little Endian
CPU(s):                          192
On-line CPU(s) list:             0-191
Vendor ID:                       HiSilicon
Model name:                      Kunpeng-920
Model:                           0
Thread(s) per core:              1
Core(s) per cluster:             48
Socket(s):                       -
Cluster(s):                      4
Stepping:                        0x1
BogoMIPS:                        200.00
Flags:                           fp asimd evtstrm aes pmull sha1 sha2 crc32 atomics fphp asimdhp cpuid asimdrdm jscvt fcma dcpop asimddp asimdfhm ssbs
L1d cache:                       12 MiB (192 instances)
L1i cache:                       12 MiB (192 instances)
L2 cache:                        96 MiB (192 instances)
L3 cache:                        192 MiB (8 instances)
NUMA node(s):                    8
NUMA node0 CPU(s):               0-23
NUMA node1 CPU(s):               24-47
NUMA node2 CPU(s):               48-71
NUMA node3 CPU(s):               72-95
NUMA node4 CPU(s):               96-119
NUMA node5 CPU(s):               120-143
NUMA node6 CPU(s):               144-167
NUMA node7 CPU(s):               168-191
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Mmio stale data:   Not affected
Vulnerability Retbleed:          Not affected
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl
Vulnerability Spectre v1:        Mitigation; __user pointer sanitization
Vulnerability Spectre v2:        Not affected
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected

Versions of relevant libraries:
[pip3] mypy==1.11.1
[pip3] mypy_extensions==1.1.0
[pip3] numpy==1.26.4
[pip3] pyzmq==27.1.0
[pip3] sentence-transformers==5.2.2
[pip3] torch==2.9.0+cpu
[pip3] torch_npu==2.9.0
[pip3] torchvision==0.24.0
[pip3] transformers==5.2.0.dev0
[pip3] triton-ascend==3.2.0
[pip3] zmq==0.0.0
[conda] No relevant packages
vLLM Version: 0.16.0rc2.dev3+g978a37c82 (git sha: 978a37c82)
vLLM Ascend Version: 0.14.0rc2.dev150+gff3a50d01 (git sha: ff3a50d01)

ENV Variables:
ASCEND_TOOLKIT_LATEST_HOME=/usr/local/Ascend/ascend-toolkit/latest
ATB_OPSRUNNER_KERNEL_CACHE_LOCAL_COUNT=1
ATB_STREAM_SYNC_EVERY_RUNNER_ENABLE=0
ASCEND_VISIBLE_DEVICES=1,2,3,4,5,6,7,0
ATB_STREAM_SYNC_EVERY_KERNEL_ENABLE=0
ASCEND_RUNTIME_OPTIONS=
ATB_OPSRUNNER_KERNEL_CACHE_GLOABL_COUNT=5
ATB_HOME_PATH=/usr/local/Ascend/nnal/atb/latest/atb/cxx_abi_0
ASCEND_TOOLKIT_HOME=/usr/local/Ascend/cann-8.5.0
ATB_COMPARE_TILING_EVERY_KERNEL=0
ASCEND_OPP_PATH=/usr/local/Ascend/cann-8.5.0/opp
LD_LIBRARY_PATH=/usr/local/Ascend/nnal/atb/latest/atb/cxx_abi_0/lib:/usr/local/Ascend/nnal/atb/latest/atb/cxx_abi_0/examples:/usr/local/Ascend/nnal/atb/latest/atb/cxx_abi_0/tests/atbopstest:/usr/local/Ascend/cann-8.5.0/lib64:/usr/local/Ascend/cann-8.5.0/lib64/plugin/opskernel:/usr/local/Ascend/cann-8.5.0/lib64/plugin/nnengine:/usr/local/Ascend/cann-8.5.0/opp/built-in/op_impl/ai_core/tbe/op_tiling/lib/linux/aarch64:/usr/local/Ascend/cann-8.5.0/tools/aml/lib64:/usr/local/Ascend/cann-8.5.0/tools/aml/lib64/plugin:/usr/local/Ascend/driver/lib64:/usr/local/Ascend/driver/lib64/common:/usr/local/Ascend/driver/lib64/driver:/usr/local/Ascend/nnal/atb/latest/atb/cxx_abi_1/lib:/usr/local/Ascend/nnal/atb/latest/atb/cxx_abi_1/examples:/usr/local/Ascend/nnal/atb/latest/atb/cxx_abi_1/tests/atbopstest:/usr/local/Ascend/ascend-toolkit/latest/tools/aml/lib64:/usr/local/Ascend/ascend-toolkit/latest/tools/aml/lib64/plugin:/usr/local/Ascend/ascend-toolkit/latest/lib64:/usr/local/Ascend/ascend-toolkit/latest/lib64/plugin/opskernel:/usr/local/Ascend/ascend-toolkit/latest/lib64/plugin/nnengine:/usr/local/Ascend/ascend-toolkit/latest/opp/built-in/op_impl/ai_core/tbe/op_tiling:/usr/local/Ascend/driver/lib64/common/:/usr/local/Ascend/driver/lib64/driver/:/usr/local/python3.11.14/lib:/usr/local/Ascend/cann-8.5.0/opp/built-in/op_impl/ai_core/tbe/op_tiling
ASCEND_AICPU_PATH=/usr/local/Ascend/cann-8.5.0
ATB_STREAM_SYNC_EVERY_OPERATION_ENABLE=0
ASCEND_HOME_PATH=/usr/local/Ascend/cann-8.5.0
ATB_MATMUL_SHUFFLE_K_ENABLE=1
ATB_WORKSPACE_MEM_ALLOC_ALG_TYPE=1
ATB_SHARE_MEMORY_NAME_SUFFIX=
TORCH_DEVICE_BACKEND_AUTOLOAD=1
PYTORCH_NVML_BASED_CUDA_CHECK=1
TORCHINDUCTOR_COMPILE_THREADS=1


NPU:
+------------------------------------------------------------------------------------------------+
| npu-smi 24.1.0.3                 Version: 24.1.0.3                                             |
+---------------------------+---------------+----------------------------------------------------+
| NPU   Name                | Health        | Power(W)    Temp(C)           Hugepages-Usage(page)|
| Chip                      | Bus-Id        | AICore(%)   Memory-Usage(MB)  HBM-Usage(MB)        |
+===========================+===============+====================================================+
| 0     910B2               | OK            | 90.9        34                0    / 0             |
| 0                         | 0000:C1:00.0  | 0           0    / 0          3458 / 65536         |
+===========================+===============+====================================================+
| 1     910B2               | OK            | 91.2        35                0    / 0             |
| 0                         | 0000:01:00.0  | 0           0    / 0          3423 / 65536         |
+===========================+===============+====================================================+
| 2     910B2               | OK            | 92.7        35                0    / 0             |
| 0                         | 0000:C2:00.0  | 0           0    / 0          3421 / 65536         |
+===========================+===============+====================================================+
| 3     910B2               | OK            | 90.9        36                0    / 0             |
| 0                         | 0000:02:00.0  | 0           0    / 0          3423 / 65536         |
+===========================+===============+====================================================+
| 4     910B2               | OK            | 91.2        36                0    / 0             |
| 0                         | 0000:81:00.0  | 0           0    / 0          3424 / 65536         |
+===========================+===============+====================================================+
| 5     910B2               | OK            | 89.5        36                0    / 0             |
| 0                         | 0000:41:00.0  | 0           0    / 0          3424 / 65536         |
+===========================+===============+====================================================+
| 6     910B2               | OK            | 96.1        35                0    / 0             |
| 0                         | 0000:82:00.0  | 0           0    / 0          3422 / 65536         |
+===========================+===============+====================================================+
| 7     910B2               | OK            | 93.5        35                0    / 0             |
| 0                         | 0000:42:00.0  | 0           0    / 0          3422 / 65536         |
+===========================+===============+====================================================+
+---------------------------+---------------+----------------------------------------------------+
| NPU     Chip              | Process id    | Process name             | Process memory(MB)      |
+===========================+===============+====================================================+
| No running processes found in NPU 0                                                            |
+===========================+===============+====================================================+
| No running processes found in NPU 1                                                            |
+===========================+===============+====================================================+
| No running processes found in NPU 2                                                            |
+===========================+===============+====================================================+
| No running processes found in NPU 3                                                            |
+===========================+===============+====================================================+
| No running processes found in NPU 4                                                            |
+===========================+===============+====================================================+
| No running processes found in NPU 5                                                            |
+===========================+===============+====================================================+
| No running processes found in NPU 6                                                            |
+===========================+===============+====================================================+
| No running processes found in NPU 7                                                            |
+===========================+===============+====================================================+

CANN:
package_name=Ascend-cann-toolkit
version=8.5.0
innerversion=V100R001C25SPC001B232
compatible_version=[V100R001C15],[V100R001C18],[V100R001C19],[V100R001C20],[V100R001C21],[V100R001C23]
arch=aarch64
os=linux
path=/usr/local/Ascend/cann-8.5.0
```

</details>

### 🐛 Describe the bug

配置参数：
```python
(APIServer pid=3302) INFO 02-28 16:42:33 [utils.py:223] non-default args: {'model_tag': '/cache/model/glm5', 'api_server_count': 1, 'host': '0.0.0.0', 'port': 1026, 'chat_template': '/cache/model/glm5/chat_template.jinja', 'enable_auto_tool_choice': True, 'tool_call_parser': 'glm47', 'model': '/cache/model/glm5', 'trust_remote_code': True, 'seed': 1024, 'max_model_len': 8192, 'served_model_name': ['GLM-5'], 'reasoning_parser': 'glm45', 'tensor_parallel_size': 8, 'data_parallel_size': 4, 'data_parallel_size_local': 1, 'data_parallel_address': '172.16.34.229', 'data_parallel_rpc_port': 12890, 'enable_expert_parallel': True, 'gpu_memory_utilization': 0.95, 'enable_prefix_caching': False, 'max_num_batched_tokens': 4096, 'max_num_seqs': 8, 'compilation_config': {'level': None, 'mode': None, 'debug_dump_path': None, 'cache_dir': '', 'compile_cache_save_format': 'binary', 'backend': 'vllm_ascend.compilation.compiler_interface.AscendCompiler', 'custom_ops': [], 'splitting_ops': None, 'compile_mm_encoder': False, 'compile_sizes': None, 'compile_ranges_split_points': None, 'inductor_compile_config': {'enable_auto_functionalized_v2': False, 'combo_kernels': True, 'benchmark_combo_kernel': True}, 'inductor_passes': {}, 'cudagraph_mode': <CUDAGraphMode.FULL_DECODE_ONLY: (2, 0)>, 'cudagraph_num_of_warmups': 0, 'cudagraph_capture_sizes': None, 'cudagraph_copy_inputs': False, 'cudagraph_specialize_lora': True, 'use_inductor_graph_partition': None, 'pass_config': {}, 'max_cudagraph_capture_size': None, 'dynamic_shapes_config': {'type': <DynamicShapesType.BACKED: 'backed'>, 'evaluate_guards': False, 'assume_32_bit_indexing': False}, 'local_cache_dir': None, 'fast_moe_cold_start': None, 'static_all_moe_layers': []}}
```

报错日志：
```python
Loading safetensors checkpoint shards: 100% Completed | 282/282 [00:45<00:00,  6.15it/s]
(Worker_DP0_TP0_EP0 pid=3753)
(Worker_DP0_TP0_EP0 pid=3753) INFO 02-28 16:45:12 [default_loader.py:293] Loading weights took 45.85 seconds
(Worker_DP0_TP7_EP7 pid=3760) WARNING 02-28 16:45:12 [sfa_v1.py:523] Currently mlapo only supports W8A8 quantization in SFA scenario.Some layers in your model are not quantized with W8A8,thus mlapo is disabled for these layers.
(Worker_DP0_TP0_EP0 pid=3753) WARNING 02-28 16:45:12 [sfa_v1.py:523] Currently mlapo only supports W8A8 quantization in SFA scenario.Some layers in your model are not quantized with W8A8,thus mlapo is disabled for these layers.
(Worker_DP0_TP4_EP4 pid=3757) INFO 02-28 16:45:12 [model_runner_v1.py:2323] Loading model weights took 50.1852 GB
(Worker_DP0_TP6_EP6 pid=3759) WARNING 02-28 16:45:13 [sfa_v1.py:523] Currently mlapo only supports W8A8 quantization in SFA scenario.Some layers in your model are not quantized with W8A8,thus mlapo is disabled for these layers.
(Worker_DP0_TP3_EP3 pid=3756) INFO 02-28 16:45:13 [model_runner_v1.py:2323] Loading model weights took 50.1852 GBtime="2026-02-28T16:48:17+08:00" level=info msg="analyzer is diagnosing" file="analyzer.go:305" Command=analyze Component=ma-training-toolkit Container=modelarts-training-sidecar Platform=ModelArts-Service
time="2026-02-28T16:48:17+08:00" level=info msg="time required for conclude： 5 ms" file="analyzer.go:411" Command=analyze Component=ma-training-toolkit Container=modelarts-training-sidecar Platform=ModelArts-Service

(Worker_DP0_TP2_EP2 pid=3755) INFO 02-28 16:45:13 [model_runner_v1.py:2323] Loading model weights took 50.1852 GB
(Worker_DP0_TP1_EP1 pid=3754) INFO 02-28 16:45:14 [model_runner_v1.py:2323] Loading model weights took 50.1852 GB
(Worker_DP0_TP7_EP7 pid=3760) INFO 02-28 16:45:14 [model_runner_v1.py:2323] Loading model weights took 50.1852 GB
(Worker_DP0_TP0_EP0 pid=3753) INFO 02-28 16:45:14 [model_runner_v1.py:2323] Loading model weights took 50.1852 GB
(Worker_DP0_TP6_EP6 pid=3759) INFO 02-28 16:45:15 [model_runner_v1.py:2323] Loading model weights took 50.1852 GB
(Worker_DP0_TP0_EP0 pid=3753) INFO 02-28 16:45:25 [backends.py:916] Using cache directory: /home/ma-user/.cache/vllm/torch_compile_cache/68b875a78a/rank_0_0/backbone for vLLM's torch.compile
(Worker_DP0_TP0_EP0 pid=3753) INFO 02-28 16:45:25 [backends.py:976] Dynamo bytecode transform time: 9.95 s
(Worker_DP0_TP0_EP0 pid=3753) INFO 02-28 16:45:53 [backends.py:368] Compiling a graph for compile range (1, 4096) takes 19.43 s
(Worker_DP0_TP0_EP0 pid=3753) INFO 02-28 16:45:53 [monitor.py:34] torch.compile takes 29.39 s in total
(EngineCore_DP0 pid=3584) INFO 02-28 16:46:15 [shm_broadcast.py:542] No available shared memory broadcast block found in 60 seconds. This typically happens when some processes are hanging or doing some time-consuming work (e.g. compilation, weight/kv cache quantization).
(EngineCore_DP0 pid=3584) INFO 02-28 16:47:15 [shm_broadcast.py:542] No available shared memory broadcast block found in 60 seconds. This typically happens when some processes are hanging or doing some time-consuming work (e.g. compilation, weight/kv cache quantization).
(EngineCore_DP0 pid=3584) INFO 02-28 16:48:15 [shm_broadcast.py:542] No available shared memory broadcast block found in 60 seconds. This typically happens when some processes are hanging or doing some time-consuming work (e.g. compilation, weight/kv cache quantization).
(EngineCore_DP0 pid=3584) INFO 02-28 16:49:15 [shm_broadcast.py:542] No available shared memory broadcast block found in 60 seconds. This typically happens when some processes are hanging or doing some time-consuming work (e.g. compilation, weight/kv cache quantization).
(EngineCore_DP0 pid=3584) INFO 02-28 16:50:15 [shm_broadcast.py:542] No available shared memory broadcast block found in 60 seconds. This typically happens when some processes are hanging or doing some time-consuming work (e.g. compilation, weight/kv cache quantization).
(EngineCore_DP0 pid=3584) INFO 02-28 16:51:15 [shm_broadcast.py:542] No available shared memory broadcast block found in 60 seconds. This typically happens when some processes are hanging or doing some time-consuming work (e.g. compilation, weight/kv cache quantization).
(EngineCore_DP0 pid=3584) INFO 02-28 16:52:15 [shm_broadcast.py:542] No available shared memory broadcast block found in 60 seconds. This typically happens when some processes are hanging or doing some time-consuming work (e.g. compilation, weight/kv cache quantization).
(EngineCore_DP0 pid=3584) INFO 02-28 16:53:15 [shm_broadcast.py:542] No available shared memory broadcast block found in 60 seconds. This typically happens when some processes are hanging or doing some time-consuming work (e.g. compilation, weight/kv cache quantization).
(EngineCore_DP0 pid=3584) INFO 02-28 16:54:15 [shm_broadcast.py:542] No available shared memory broadcast block found in 60 seconds. This typically happens when some processes are hanging or doing some time-consuming work (e.g. compilation, weight/kv cache quantization).
[rank1]:[E228 16:55:14.954683807 compiler_depend.ts:444] operator():build/CMakeFiles/torch_npu.dir/compiler_depend.ts:3997 NPU function error: call aclnnSwiGlu failed, error code is 507014
[ERROR] 2026-02-28-16:55:14 (PID:3754, Device:1, RankID:-1) ERR00100 PTA call acl api failed
[Error]: The aicore execution times out.
Rectify the fault based on the error information in the ascend log.
[PID: 3754] 2026-02-28-16:55:11.276.955 Invalid_Argument(EL0003): The argument is invalid.
Solution: Try again with a valid argument.
TraceBack (most recent call last):
The error from device(chipId:1, dieId:0), serial number is 5, there is an exception of fftsplus aivector error, core id is 0, error code = 0, dump info: pc start: 0x12e48136fdd0, current: 0x12e481372f68, vec error info: 0x6111171161, mte error info: 0x1c2b3ff02f, ifu error info: 0x33423bdfc0d00, ccu error info: 0xa832e8f3c9531c6, cube error info: 0, biu error info: 0, aic error mask: 0x6500020bd00028c, para base: 0x12e500002080.[FUNC:PrintCoreInfo][FILE:device_error_core_proc.cc][LINE:347]
The extend info: errcode:(0, 0, 0) errorStr: timeout or trap error. fixp_error0 info: 0xb3ff02f, fixp_error1 info: 0x1c, fsmId:0, tslot:1, thread:0, ctxid:0, blk:38, sublk:0, subErrType:4.[FUNC:PrintCoreInfo][FILE:device_error_core_proc.cc][LINE:360]
Kernel task happen error, retCode=0x25, [aicore timeout].[FUNC:PreCheckTaskErr][FILE:davinci_kernel_task.cc][LINE:1493]
The argument is invalid.
rtMemGetInfoByType execution failed, reason=driver error:invalid handle[FUNC:FuncErrorReason][FILE:error_message_manage.cc][LINE:61]
Failed to submit kernel task, retCode=0x7150025.[FUNC:LaunchKernelSubmit][FILE:context.cc][LINE:1189]
kernel launch submit failed.[FUNC:LaunchKernel][FILE:context.cc][LINE:1652]
rtsLaunchKernelWithHostArgs execution failed, reason=aicore timeout[FUNC:FuncErrorReason][FILE:error_message_manage.cc][LINE:61]
rtsLaunchKernelWithHostArgs failed, runtime result = 507014.[FUNC:ReportCallError][FILE:log_inner.cpp][LINE:148]
Check aclrtLaunchKernelWithHostArgs( funcHandle, blockDim, stream, &cfg, executor->argsExt.args, executor->argsExt.argsSize, NnopbaseGetRTSPlaceHolder(&executor->argsExt).data(), NnopbaseGetRTSPlaceHolderNum(&executor->argsExt)) failed
Assert ((NnopbaseExecutorLaunchKernel(executor, stream, blockDim)) == 0) failed
Check NnopbaseExecutorKernelLaunch(executor, stream) failed
Check NnopbaseRunWithWorkspace(executor, stream, workspace, workspaceSize) failed

Exception raised from operator() at build/CMakeFiles/torch_npu.dir/compiler_depend.ts:3997 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) + 0xb0 (0xffffa023c700 in /usr/local/python3.11.14/lib/python3.11/site-packages/torch/lib/libc10.so)
frame #1: c10::detail::torchCheckFail(char const*, char const*, unsigned int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) + 0x68 (0xffffa01da860 in /usr/local/python3.11.14/lib/python3.11/site-packages/torch/lib/libc10.so)
frame #2: <unknown function> + 0x23b4b70 (0xffff6be94b70 in /usr/local/python3.11.14/lib/python3.11/site-packages/torch_npu/lib/libtorch_npu.so)
frame #3: <unknown function> + 0x2c77e24 (0xffff6c757e24 in /usr/local/python3.11.14/lib/python3.11/site-packages/torch_npu/lib/libtorch_npu.so)
frame #4: <unknown function> + 0xa607d0 (0xffff6a5407d0 in /usr/local/python3.11.14/lib/python3.11/site-packages/torch_npu/lib/libtorch_npu.so)
frame #5: <unknown function> + 0xa613ac (0xffff6a5413ac in /usr/local/python3.11.14/lib/python3.11/site-packages/torch_npu/lib/libtorch_npu.so)
frame #6: <unknown function> + 0xa5f2c8 (0xffff6a53f2c8 in /usr/local/python3.11.14/lib/python3.11/site-packages/torch_npu/lib/libtorch_npu.so)
frame #7: <unknown function> + 0xd29cc (0xffffa00429cc in /lib/aarch64-linux-gnu/libstdc++.so.6)
frame #8: <unknown function> + 0x80398 (0xffffac680398 in /lib/aarch64-linux-gnu/libc.so.6)
frame #9: <unknown function> + 0xe9e9c (0xffffac6e9e9c in /lib/aarch64-linux-gnu/libc.so.6)

[rank6]:[E228 16:55:14.960919871 compiler_depend.ts:444] operator():build/CMakeFiles/torch_npu.dir/compiler_depend.ts:3997 NPU function error: call aclnnSwiGlu failed, error code is 507014
[ERROR] 2026-02-28-16:55:14 (PID:3759, Device:6, RankID:-1) ERR00100 PTA call acl api failed
[Error]: The aicore execution times out.
Rectify the fault based on the error information in the ascend log.
[PID: 3759] 2026-02-28-16:55:11.958.481 Invalid_Argument(EL0003): The argument is invalid.
Solution: Try again with a valid argument.
TraceBack (most recent call last):
The error from device(chipId:6, dieId:0), serial number is 5, there is an exception of fftsplus aivector error, core id is 0, error code = 0, dump info: pc start: 0x12e48136fdd0, current: 0x12e481372f68, vec error info: 0x7d031e1651, mte error info: 0x182e0161f, ifu error info: 0x2702003e201c0, ccu error info: 0x12cfce83b15bd80, cube error info: 0, biu error info: 0, aic error mask: 0x6500020bd00028c, para base: 0x12e500002080.[FUNC:PrintCoreInfo][FILE:device_error_core_proc.cc][LINE:347]
The extend info: errcode:(0, 0, 0) errorStr: timeout or trap error. fixp_error0 info: 0x2e0161f, fixp_error1 info: 0x1, fsmId:0, tslot:5, thread:0, ctxid:0, blk:40, sublk:0, subErrType:4.[FUNC:PrintCoreInfo][FILE:device_error_core_proc.cc][LINE:360]
Kernel task happen error, retCode=0x25, [aicore timeout].[FUNC:PreCheckTaskErr][FILE:davinci_kernel_task.cc][LINE:1493]
The argument is invalid.
rtMemGetInfoByType execution failed, reason=driver error:invalid handle[FUNC:FuncErrorReason][FILE:error_message_manage.cc][LINE:61]
Failed to submit kernel task, retCode=0x7150025.[FUNC:LaunchKernelSubmit][FILE:context.cc][LINE:1189]
kernel launch submit failed.[FUNC:LaunchKernel][FILE:context.cc][LINE:1652]
rtsLaunchKernelWithHostArgs execution failed, reason=aicore timeout[FUNC:FuncErrorReason][FILE:error_message_manage.cc][LINE:61]
rtsLaunchKernelWithHostArgs failed, runtime result = 507014.[FUNC:ReportCallError][FILE:log_inner.cpp][LINE:148]
Check aclrtLaunchKernelWithHostArgs( funcHandle, blockDim, stream, &cfg, executor->argsExt.args, executor->argsExt.argsSize, NnopbaseGetRTSPlaceHolder(&executor->argsExt).data(), NnopbaseGetRTSPlaceHolderNum(&executor->argsExt)) failed
Assert ((NnopbaseExecutorLaunchKernel(executor, stream, blockDim)) == 0) failed
Check NnopbaseExecutorKernelLaunch(executor, stream) failed
Check NnopbaseRunWithWorkspace(executor, stream, workspace, workspaceSize) failed

Exception raised from operator() at build/CMakeFiles/torch_npu.dir/compiler_depend.ts:3997 (most recent call first):
frame #0: c10::Error::Error(c10::SourceLocation, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >) + 0xb0 (0xffffaee0c700 in /usr/local/python3.11.14/lib/python3.11/site-packages/torch/lib/libc10.so)
frame #1: c10::detail::torchCheckFail(char const*, char const*, unsigned int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) + 0x68 (0xffffaedaa860 in /usr/local/python3.11.14/lib/python3.11/site-packages/torch/lib/libc10.so)
frame #2: <unknown function> + 0x23b4b70 (0xffff7aa64b70 in /usr/local/python3.11.14/lib/python3.11/site-packages/torch_npu/lib/libtorch_npu.so)
frame #3: <unknown function> + 0x2c77e24 (0xffff7b327e24 in /usr/local/python3.11.14/lib/python3.11/site-packages/torch_npu/lib/libtorch_npu.so)
frame #4: <unknown function> + 0xa607d0 (0xffff791107d0 in /usr/local/python3.11.14/lib/python3.11/site-packages/torch_npu/lib/libtorch_npu.so)
frame #5: <unknown function> + 0xa613ac (0xffff791113ac in /usr/local/python3.11.14/lib/python3.11/site-packages/torch_npu/lib/libtorch_npu.so)
frame #6: <unknown function> + 0xa5f2c8 (0xffff7910f2c8 in /usr/local/python3.11.14/lib/python3.11/site-packages/torch_npu/lib/libtorch_npu.so)
frame #7: <unknown function> + 0xd29cc (0xffffaec129cc in /lib/aarch64-linux-gnu/libstdc++.so.6)
frame #8: <unknown function> + 0x80398 (0xffffbb250398 in /lib/aarch64-linux-gnu/libc.so.6)
frame #9: <unknown function> + 0xe9e9c (0xffffbb2b9e9c in /lib/aarch64-linux-gnu/libc.so.6)

(Worker_DP0_TP6_EP6 pid=3759) ERROR 02-28 16:55:14 [multiproc_executor.py:863] WorkerProc hit an exception.
(Worker_DP0_TP6_EP6 pid=3759) ERROR 02-28 16:55:14 [multiproc_executor.py:863] Traceback (most recent call last):
(Worker_DP0_TP6_EP6 pid=3759) ERROR 02-28 16:55:14 [multiproc_executor.py:863]   File "/usr/local/python3.11.14/lib/python3.11/site-packages/vllm/v1/executor/multiproc_executor.py", line 858, in worker_busy_loop
(Worker_DP0_TP6_EP6 pid=3759) ERROR 02-28 16:55:14 [multiproc_executor.py:863]     output = func(*args, **kwargs)
(Worker_DP0_TP6_EP6 pid=3759) ERROR 02-28 16:55:14 [multiproc_executor.py:863]              ^^^^^^^^^^^^^^^^^^^^^
(Worker_DP0_TP6_EP6 pid=3759) ERROR 02-28 16:55:14 [multiproc_executor.py:863]   File "/usr/local/python3.11.14/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 120, in decorate_context
(Worker_DP0_TP6_EP6 pid=3759) ERROR 02-28 16:55:14 [multiproc_executor.py:863]     return func(*args, **kwargs)
(Worker_DP0_TP6_EP6 pid=3759) ERROR 02-28 16:55:14 [multiproc_executor.py:863]            ^^^^^^^^^^^^^^^^^^^^^
(Worker_DP0_TP6_EP6 pid=3759) ERROR 02-28 16:55:14 [multiproc_executor.py:863]   File "/vllm-workspace/vllm-ascend/vllm_ascend/worker/worker.py", line 312, in determine_available_memory
(Worker_DP0_TP6_EP6 pid=3759) ERROR 02-28 16:55:14 [multiproc_executor.py:863]     self.model_runner.profile_run()
(Worker_DP0_TP6_EP6 pid=3759) ERROR 02-28 16:55:14 [multiproc_executor.py:863]   File "/vllm-workspace/vllm-ascend/vllm_ascend/worker/model_runner_v1.py", line 2296, in profile_run
(Worker_DP0_TP6_EP6 pid=3759) ERROR 02-28 16:55:14 [multiproc_executor.py:863]     super().profile_run()
(Worker_DP0_TP6_EP6 pid=3759) ERROR 02-28 16:55:14 [multiproc_executor.py:863]   File "/usr/local/python3.11.14/lib/python3.11/site-packages/vllm/v1/worker/gpu_model_runner.py", line 5168, in profile_run
(Worker_DP0_TP6_EP6 pid=3759) ERROR 02-28 16:55:14 [multiproc_executor.py:863]     hidden_states, last_hidden_states = self._dummy_run(
(Worker_DP0_TP6_EP6 pid=3759) ERROR 02-28 16:55:14 [multiproc_executor.py:863]                                         ^^^^^^^^^^^^^^^^
(Worker_DP0_TP6_EP6 pid=3759) ERROR 02-28 16:55:14 [multiproc_executor.py:863]   File "/usr/local/python3.11.14/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 120, in decorate_context
(Worker_DP0_TP6_EP6 pid=3759) ERROR 02-28 16:55:14 [multiproc_executor.py:863]     return func(*args, **kwargs)
(Worker_DP0_TP6_EP6 pid=3759) ERROR 02-28 16:55:14 [multiproc_executor.py:863]            ^^^^^^^^^^^^^^^^^^^^^
(Worker_DP0_TP6_EP6 pid=3759) ERROR 02-28 16:55:14 [multiproc_executor.py:863]   File "/vllm-workspace/vllm-ascend/vllm_ascend/worker/model_runner_v1.py", line 2237, in _dummy_run
(Worker_DP0_TP6_EP6 pid=3759) ERROR 02-28 16:55:14 [multiproc_executor.py:863]     outputs = self._model_forward(
(Worker_DP0_TP6_EP6 pid=3759) ERROR 02-28 16:55:14 [multiproc_executor.py:863]               ^^^^^^^^^^^^^^^^^^^^
(Worker_DP0_TP6_EP6 pid=3759) ERROR 02-28 16:55:14 [multiproc_executor.py:863]   File "/vllm-workspace/vllm-ascend/vllm_ascend/worker/model_runner_v1.py", line 1632, in _model_forward
(Worker_DP0_TP6_EP6 pid=3759) ERROR 02-28 16:55:14 [multiproc_executor.py:863]     hidden_states = self.model(
(Worker_DP0_TP6_EP6 pid=3759) ERROR 02-28 16:55:14 [multiproc_executor.py:863]                     ^^^^^^^^^^^
(Worker_DP0_TP6_EP6 pid=3759) ERROR 02-28 16:55:14 [multiproc_executor.py:863]   File "/vllm-workspace/vllm-ascend/vllm_ascend/compilation/acl_graph.py", line 110, in __call__
(Worker_DP0_TP6_EP6 pid=3759) ERROR 02-28 16:55:14 [multiproc_executor.py:863]     return self.runnable(*args, **kwargs)
(Worker_DP0_TP6_EP6 pid=3759) ERROR 02-28 16:55:14 [multiproc_executor.py:863]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(Worker_DP0_TP6_EP6 pid=3759) ERROR 02-28 16:55:14 [multiproc_executor.py:863]   File "/usr/local/python3.11.14/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1775, in _wrapped_call_impl
(Worker_DP0_TP6_EP6 pid=3759) ERROR 02-28 16:55:14 [multiproc_executor.py:863]     return self._call_impl(*args, **kwargs)
(Worker_DP0_TP6_EP6 pid=3759) ERROR 02-28 16:55:14 [multiproc_executor.py:863]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(Worker_DP0_TP6_EP6 pid=3759) ERROR 02-28 16:55:14 [multiproc_executor.py:863]   File "/usr/local/python3.11.14/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1786, in _call_impl
(Worker_DP0_TP6_EP6 pid=3759) ERROR 02-28 16:55:14 [multiproc_executor.py:863]     return forward_call(*args, **kwargs)
(Worker_DP0_TP6_EP6 pid=3759) ERROR 02-28 16:55:14 [multiproc_executor.py:863]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(Worker_DP0_TP6_EP6 pid=3759) ERROR 02-28 16:55:14 [multiproc_executor.py:863]   File "/usr/local/python3.11.14/lib/python3.11/site-packages/vllm/model_executor/models/deepseek_v2.py", line 1263, in forward
(Worker_DP0_TP6_EP6 pid=3759) ERROR 02-28 16:55:14 [multiproc_executor.py:863]     hidden_states = self.model(
(Worker_DP0_TP6_EP6 pid=3759) ERROR 02-28 16:55:14 [multiproc_executor.py:863]                     ^^^^^^^^^^^
(Worker_DP0_TP6_EP6 pid=3759) ERROR 02-28 16:55:14 [multiproc_executor.py:863]   File "/usr/local/python3.11.14/lib/python3.11/site-packages/vllm/compilation/decorators.py", line 471, in __call__
(Worker_DP0_TP6_EP6 pid=3759) ERROR 02-28 16:55:14 [multiproc_executor.py:863]     return TorchCompileWithNoGuardsWrapper.__call__(self, *args, **kwargs)  # type: ignore[arg-type]
(Worker_DP0_TP6_EP6 pid=3759) ERROR 02-28 16:55:14 [multiproc_executor.py:863]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(Worker_DP0_TP6_EP6 pid=3759) ERROR 02-28 16:55:14 [multiproc_executor.py:863]   File "/usr/local/python3.11.14/lib/python3.11/site-packages/vllm/compilation/wrapper.py", line 225, in __call__
(Worker_DP0_TP6_EP6 pid=3759) ERROR 02-28 16:55:14 [multiproc_executor.py:863]     return self._call_with_optional_nvtx_range(
(Worker_DP0_TP6_EP6 pid=3759) ERROR 02-28 16:55:14 [multiproc_executor.py:863]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(Worker_DP0_TP6_EP6 pid=3759) ERROR 02-28 16:55:14 [multiproc_executor.py:863]   File "/usr/local/python3.11.14/lib/python3.11/site-packages/vllm/compilation/wrapper.py", line 119, in _call_with_optional_nvtx_range
(Worker_DP0_TP6_EP6 pid=3759) ERROR 02-28 16:55:14 [multiproc_executor.py:863]     return callable_fn(*args, **kwargs)
(Worker_DP0_TP6_EP6 pid=3759) ERROR 02-28 16:55:14 [multiproc_executor.py:863]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(Worker_DP0_TP6_EP6 pid=3759) ERROR 02-28 16:55:14 [multiproc_executor.py:863]   File "/usr/local/python3.11.14/lib/python3.11/site-packages/vllm/model_executor/models/deepseek_v2.py", line 1086, in forward
(Worker_DP0_TP6_EP6 pid=3759) ERROR 02-28 16:55:14 [multiproc_executor.py:863]     def forward(
(Worker_DP0_TP6_EP6 pid=3759) ERROR 02-28 16:55:14 [multiproc_executor.py:863]   File "/usr/local/python3.11.14/lib/python3.11/site-packages/torch/_dynamo/eval_frame.py", line 1044, in _fn
(Worker_DP0_TP6_EP6 pid=3759) ERROR 02-28 16:55:14 [multiproc_executor.py:863]     return fn(*args, **kwargs)
(Worker_DP0_TP6_EP6 pid=3759) ERROR 02-28 16:55:14 [multiproc_executor.py:863]            ^^^^^^^^^^^^^^^^^^^
(Worker_DP0_TP6_EP6 pid=3759) ERROR 02-28 16:55:14 [multiproc_executor.py:863]   File "/usr/local/python3.11.14/lib/python3.11/site-packages/vllm/compilation/caching.py", line 185, in __call__
(Worker_DP0_TP6_EP6 pid=3759) ERROR 02-28 16:55:14 [multiproc_executor.py:863]     return self.optimized_call(*args, **kwargs)
(Worker_DP0_TP6_EP6 pid=3759) ERROR 02-28 16:55:14 [multiproc_executor.py:863]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(Worker_DP0_TP6_EP6 pid=3759) ERROR 02-28 16:55:14 [multiproc_executor.py:863]   File "/usr/local/python3.11.14/lib/python3.11/site-packages/torch/fx/graph_module.py", line 837, in call_wrapped
(Worker_DP0_TP6_EP6 pid=3759) ERROR 02-28 16:55:14 [multiproc_executor.py:863]     return self._wrapped_call(self, *args, **kwargs)
(Worker_DP0_TP6_EP6 pid=3759) ERROR 02-28 16:55:14 [multiproc_executor.py:863]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(Worker_DP0_TP6_EP6 pid=3759) ERROR 02-28 16:55:14 [multiproc_executor.py:863]   File "/usr/local/python3.11.14/lib/python3.11/site-packages/torch/fx/graph_module.py", line 413, in __call__
(Worker_DP0_TP6_EP6 pid=3759) ERROR 02-28 16:55:14 [multiproc_executor.py:863]     raise e
(Worker_DP0_TP6_EP6 pid=3759) ERROR 02-28 16:55:14 [multiproc_executor.py:863]   File "/usr/local/python3.11.14/lib/python3.11/site-packages/torch/fx/graph_module.py", line 400, in __call__
(Worker_DP0_TP6_EP6 pid=3759) ERROR 02-28 16:55:14 [multiproc_executor.py:863]     return super(self.cls, obj).__call__(*args, **kwargs)  # type: ignore[misc]
(Worker_DP0_TP6_EP6 pid=3759) ERROR 02-28 16:55:14 [multiproc_executor.py:863]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(Worker_DP0_TP6_EP6 pid=3759) ERROR 02-28 16:55:14 [multiproc_executor.py:863]   File "/usr/local/python3.11.14/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1775, in _wrapped_call_impl
(Worker_DP0_TP6_EP6 pid=3759) ERROR 02-28 16:55:14 [multiproc_executor.py:863]     return self._call_impl(*args, **kwargs)
(Worker_DP0_TP6_EP6 pid=3759) ERROR 02-28 16:55:14 [multiproc_executor.py:863]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(Worker_DP0_TP6_EP6 pid=3759) ERROR 02-28 16:55:14 [multiproc_executor.py:863]   File "/usr/local/python3.11.14/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1786, in _call_impl
(Worker_DP0_TP6_EP6 pid=3759) ERROR 02-28 16:55:14 [multiproc_executor.py:863]     return forward_call(*args, **kwargs)
(Worker_DP0_TP6_EP6 pid=3759) ERROR 02-28 16:55:14 [multiproc_executor.py:863]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(Worker_DP0_TP6_EP6 pid=3759) ERROR 02-28 16:55:14 [multiproc_executor.py:863]   File "<eval_with_key>.10", line 245, in forward
(Worker_DP0_TP6_EP6 pid=3759) ERROR 02-28 16:55:14 [multiproc_executor.py:863]     submod_0 = self.submod_0(l_input_ids_, s72, l_self_modules_embed_tokens_parameters_weight_, l_self_modules_layers_modules_0_modules_input_layernorm_parameters_weight_, l_self_modules_layers_modules_0_modules_post_attention_layernorm_parameters_weight_, l_self_modules_layers_modules_0_modules_mlp_modules_gate_up_proj_parameters_weight_, l_self_modules_layers_modules_0_modules_mlp_modules_down_proj_parameters_weight_, l_self_modules_layers_modules_1_modules_input_layernorm_parameters_weight_, l_self_modules_layers_modules_1_modules_post_attention_layernorm_parameters_weight_, l_self_modules_layers_modules_1_modules_mlp_modules_gate_up_proj_parameters_weight_, l_self_modules_layers_modules_1_modules_mlp_modules_down_proj_parameters_weight_, l_self_modules_layers_modules_2_modules_input_layernorm_parameters_weight_, l_self_modules_layers_modules_2_modules_post_attention_layernorm_parameters_weight_, l_self_modules_layers_modules_2_modules_mlp_modules_gate_up_proj_parameters_weight_, l_self_modules_layers_modules_2_modules_mlp_modules_down_proj_parameters_weight_, l_self_modules_layers_modules_3_modules_input_layernorm_parameters_weight_, 
```

**Comment by HusterYoung** [comment]
并未开启MTP：
```python
    "--host" "$host"
    "--port" "$port"
    "--data-parallel-size" "4"
    "--data-parallel-size-local" "1"
    "--data-parallel-rpc-port" "$RPC_PORT"
    "--seed" "1024"
    "--served-model-name" "$MODEL_NAME"
    "--tensor-parallel-size" "8"
    "--max-num-seqs" "$max_num_seqs"
    "--trust-remote-code"
    "--max-model-len" "$max_model_len"
    "--max-num-batched-tokens" "$max_num_batched_tokens"
    "--no-enable-prefix-caching"
    "--gpu-memory-utilization" "$gpu_memory_utilization"
    "--enable-expert-parallel"
    "--enable-auto-tool-choice"
    "--tool-call-parser" "glm47"
    "--reasoning-parser" "glm45"
    "--chat-template" "${PRECHECKPOINT_PATH}/chat_template.jinja"
    "--compilation-config" '{"cudagraph_mode": "FULL_DECODE_ONLY"}'
```

**Comment by shijunan126-creator** [comment]
报错应该是因为No available shared memory broadcast block found in 60 seconds.
我之前解决方法是
1.增加容器的共享内存
2.export VLLM_ENGINE_READY_TIMEOUT_S=1200 延长容许时间

**Comment by HusterYoung** [comment]
> 报错应该是因为No available shared memory broadcast block found in 60 seconds. 我之前解决方法是 1.增加容器的共享内存 2.export VLLM_ENGINE_READY_TIMEOUT_S=1200 延长容许时间

设置export VLLM_ENGINE_READY_TIMEOUT_S=1200无效果

`df -h /dev/shm`
Filesystem      Size  Used Avail Use% Mounted on
tmpfs           709G  4.0K  709G   1% /dev/shm

目前单节点有这么多共享内存。

**Comment by 13051652726** [comment]
https://github.com/vllm-project/vllm-ascend/issues/5674
应该是物理机网络的问题，可以看看这个方案能不能解决

**Comment by HusterYoung** [comment]
取消--enable-expert-parallel参数后部署成功，但不知道原因为何。


> [#5674](https://github.com/vllm-project/vllm-ascend/issues/5674) 应该是物理机网络的问题，可以看看这个方案能不能解决

**Comment by HusterYoung** [comment]
> 报错应该是因为No available shared memory broadcast block found in 60 seconds. 我之前解决方法是 1.增加容器的共享内存 2.export VLLM_ENGINE_READY_TIMEOUT_S=1200 延长容许时间

取消--enable-expert-parallel参数后部署成功，但不知道原因为何。

**Comment by 13051652726** [comment]
> > 报错应该是因为No available shared memory broadcast block found in 60 seconds. 我之前解决方法是 1.增加容器的共享内存 2.export VLLM_ENGINE_READY_TIMEOUT_S=1200 延长容许时间
> 
> 取消--enable-expert-parallel参数后部署成功，但不知道原因为何。

我也是使用4台910B部署GLM5-bf16，但是上下文只能设置16k，--max-model-len 16384，你有遇到过这个问题嘛？

**Comment by HusterYoung** [comment]
> > > 报错应该是因为No available shared memory broadcast block found in 60 seconds. 我之前解决方法是 1.增加容器的共享内存 2.export VLLM_ENGINE_READY_TIMEOUT_S=1200 延长容许时间
> > 
> > 
> > 取消--enable-expert-parallel参数后部署成功，但不知道原因为何。
> 
> 我也是使用4台910B部署GLM5-bf16，但是上下文只能设置16k，--max-model-len 16384，你有遇到过这个问题嘛？

我遇到过，就是显存不够分配kv cache了，4机的上限就在这儿。

**Comment by 13051652726** [comment]
> 我遇到过，就是显存不够分配kv cache了，4机的上限就在这儿。
你也是设置了--max-model-len 16384 ？

有用w8a8量化权重部署么？

**Comment by HusterYoung** [comment]
> > 我遇到过，就是显存不够分配kv cache了，4机的上限就在这儿。
> > 你也是设置了--max-model-len 16384 ？
> 
> 有用w8a8量化权重部署么？

暂时没有尝试

**Comment by leo-pony** [comment]
@yydyzr Could you please take a look?

**Comment by gbdjxgp** [comment]
升级一下驱动试试，我之前24.1.rc3，也是
```
No available shared memory broadcast block found in 60 seconds. This typically happens when some processes are hanging or doing some time-consuming work (e.g. compilation, weight/kv cache quantization).
```
然后一段时间报错。升级到25.5.1之后正常了。
关联issue: #5295，#5468，#5087，#4914
可能关联的参考issue：#5674，#7154,#7160

**Comment by wang-shuibin** [comment]
> 升级一下驱动试试，我之前24.1.rc3，也是
> 
> ```
> No available shared memory broadcast block found in 60 seconds. This typically happens when some processes are hanging or doing some time-consuming work (e.g. compilation, weight/kv cache quantization).
> ```
> 
> 然后一段时间报错。升级到25.5.1之后正常了。 关联issue： [#5295](https://github.com/vllm-project/vllm-ascend/issues/5295)，[#5468](https://github.com/vllm-project/vllm-ascend/issues/5468)，[#5087](https://github.com/vllm-project/vllm-ascend/issues/5087)，[#4914](https://github.com/vllm-project/vllm-ascend/issues/4914) 可能关联的参考issue：[#5674](https://github.com/vllm-project/vllm-ascend/issues/5674)，[#7154](https://github.com/vllm-project/vllm-ascend/issues/7154)，[#7160](https://github.com/vllm-project/vllm-ascend/issues/7160)

我的驱动是25.7.rc1.1，还是报这个问题

**Comment by gbdjxgp** [comment]
@wang-shuibin 你是所有机器全是这个版本的么，我记得当时是两台机器部署的glm模型，但是两台机器npu版本不一致，导致的问题，如果还是不行的话，你可以开一个新issues去问问

**Comment by wang-shuibin** [comment]
> 你是所有机器全是这个版本的么，我记得当时是两台机器部署的glm模型，但是两台机器npu版本不一致，导致的问题，如果还是不行的话，你可以开一个新issue去问问

问了产品线，他们说重启机器，重启机器。就好像就好了
