### ISSUE TITLE
[Bug]: qwen3.5-27B A2单机8卡 使用v0.17.0rc1出现错误

### ISSUE THREAD

**Issue by lai-serena** [vllm-project/vllm-ascend#7360]
### Your current environment

<details>

<summary>
System Information
Manufacturer: Huawei
Product Name: Atlas 800T A2
910B3 8卡
torch: 2.9.0+cpu
torch_npu: 2.9.0
version=8.5.1
innerversion=V100R001C25SPC002B220
compatible_version=[V100R001C15],[V100R001C18],[V100R001C19],[V100R001C20],[V100R001C21],[V100R001C23]
version=8.5.1
innerversion=V100R001C25SPC002B220
compatible_version=[V100R001C15],[V100R001C18],[V100R001C19],[V100R001C20],[V100R001C21],[V100R001C23]
</summary>

```text
docker run -itd \
  --name qwen3p5-27b \
  --restart always \
  -p 30011:8010 \
  --shm-size 32g \
  --ipc host \
  --device /dev/davinci0:/dev/davinci0 \
  --device /dev/davinci1:/dev/davinci1 \
  --device /dev/davinci2:/dev/davinci2 \
  --device /dev/davinci3:/dev/davinci3 \
  --device /dev/davinci4:/dev/davinci4 \
  --device /dev/davinci5:/dev/davinci5 \
  --device /dev/davinci6:/dev/davinci6 \
  --device /dev/davinci7:/dev/davinci7 \
  --device /dev/davinci_manager:/dev/davinci_manager \
  --device /dev/devmm_svm:/dev/devmm_svm \
  --device /dev/hisi_hdc:/dev/hisi_hdc \
  -v /usr/local/dcmi:/usr/local/dcmi \
  -v /usr/local/bin/npu-smi:/usr/local/bin/npu-smi \
  -v /usr/local/Ascend/driver/lib64/:/usr/local/Ascend/driver/lib64/ \
  -v /usr/local/Ascend/driver/version.info:/usr/local/Ascend/driver/version.info \
  -v /etc/ascend_install.info:/etc/ascend_install.info \
  -v /root/.cache:/root/.cache \
  -v /data/models:/models \
  quay.io/ascend/vllm-ascend:v0.17.0rc1
```

</details>

### 🐛 Describe the bug

```
vllm serve /models/Qwen/Qwen3.5-27B/
      --served-model-name 'qwen3p5-27b'
      --host 0.0.0.0
      --port 8010
      --data-parallel-size 1
      --tensor-parallel-size 8
      --max-model-len 8192
      --max-num-batched-tokens 16384
      --max-num-seqs 32
      --gpu-memory-utilization 0.9
      --compilation-config '{\"cudagraph_mode\":\"FULL_DECODE_ONLY\"}'
      --trust-remote-code
      --async-scheduling
      --allowed-local-media-path /
      --mm-processor-cache-gb 0
      --additional-config {"enable_cpu_binding":true}
```
推理时出现错误：
```
(Worker pid=20816) (Worker_TP0 pid=20816) ERROR 03-17 03:11:43 [multiproc_executor.py:880]                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(Worker pid=20823) (Worker_TP7 pid=20823) ERROR 03-17 03:11:43 [multiproc_executor.py:880]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(Worker pid=20819) (Worker_TP3 pid=20819) ERROR 03-17 03:11:43 [multiproc_executor.py:880]     torch.ops.vllm.gdn_attention_core(
(Worker pid=20821) (Worker_TP5 pid=20821) ERROR 03-17 03:11:43 [multiproc_executor.py:880]     stream = driver.active.get_current_stream(device)
(Worker pid=20818) (Worker_TP2 pid=20818) ERROR 03-17 03:11:43 [multiproc_executor.py:880]   File "/vllm-workspace/vllm-ascend/vllm_ascend/ops/triton/fused_gdn_gating.py", line 94, in fused_gdn_gating_patch
(Worker pid=20816) (Worker_TP0 pid=20816) ERROR 03-17 03:11:43 [multiproc_executor.py:880]   File "/usr/local/python3.11.14/lib/python3.11/site-packages/triton/runtime/jit.py", line 592, in run
(Worker pid=20823) (Worker_TP7 pid=20823) ERROR 03-17 03:11:43 [multiproc_executor.py:880]   File "/vllm-workspace/vllm/vllm/model_executor/models/qwen3_5.py", line 186, in forward
(Worker pid=20819) (Worker_TP3 pid=20819) ERROR 03-17 03:11:43 [multiproc_executor.py:880]   File "/usr/local/python3.11.14/lib/python3.11/site-packages/torch/_ops.py", line 1255, in __call__
(Worker pid=20821) (Worker_TP5 pid=20821) ERROR 03-17 03:11:43 [multiproc_executor.py:880]              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(Worker pid=20818) (Worker_TP2 pid=20818) ERROR 03-17 03:11:43 [multiproc_executor.py:880]     fused_gdn_gating_kernel[grid](
(Worker pid=20816) (Worker_TP0 pid=20816) ERROR 03-17 03:11:43 [multiproc_executor.py:880]     stream = driver.active.get_current_stream(device)
(Worker pid=20823) (Worker_TP7 pid=20823) ERROR 03-17 03:11:43 [multiproc_executor.py:880]     torch.ops.vllm.gdn_attention_core(
(Worker pid=20819) (Worker_TP3 pid=20819) ERROR 03-17 03:11:43 [multiproc_executor.py:880]     return self._op(*args, **kwargs)
(Worker pid=20821) (Worker_TP5 pid=20821) ERROR 03-17 03:11:43 [multiproc_executor.py:880]   File "/usr/local/python3.11.14/lib/python3.11/site-packages/triton/backends/ascend/driver.py", line 219, in get_current_stream
(Worker pid=20818) (Worker_TP2 pid=20818) ERROR 03-17 03:11:43 [multiproc_executor.py:880]   File "/usr/local/python3.11.14/lib/python3.11/site-packages/triton/runtime/jit.py", line 353, in <lambda>
(Worker pid=20816) (Worker_TP0 pid=20816) ERROR 03-17 03:11:43 [multiproc_executor.py:880]              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(Worker pid=20823) (Worker_TP7 pid=20823) ERROR 03-17 03:11:43 [multiproc_executor.py:880]   File "/usr/local/python3.11.14/lib/python3.11/site-packages/torch/_ops.py", line 1255, in __call__
(Worker pid=20819) (Worker_TP3 pid=20819) ERROR 03-17 03:11:43 [multiproc_executor.py:880]            ^^^^^^^^^^^^^^^^^^^^^^^^^
(Worker pid=20821) (Worker_TP5 pid=20821) ERROR 03-17 03:11:43 [multiproc_executor.py:880]     return _npu_getCurrentRawStream(device)
(Worker pid=20818) (Worker_TP2 pid=20818) ERROR 03-17 03:11:43 [multiproc_executor.py:880]     return lambda *args, **kwargs: self.run(grid=grid, warmup=False, *args, **kwargs)
(Worker pid=20816) (Worker_TP0 pid=20816) ERROR 03-17 03:11:43 [multiproc_executor.py:880]   File "/usr/local/python3.11.14/lib/python3.11/site-packages/triton/backends/ascend/driver.py", line 219, in get_current_stream
(Worker pid=20823) (Worker_TP7 pid=20823) ERROR 03-17 03:11:43 [multiproc_executor.py:880]     return self._op(*args, **kwargs)
(Worker pid=20819) (Worker_TP3 pid=20819) ERROR 03-17 03:11:43 [multiproc_executor.py:880]   File "/vllm-workspace/vllm/vllm/model_executor/models/qwen3_next.py", line 1451, in gdn_attention_core
(Worker pid=20821) (Worker_TP5 pid=20821) ERROR 03-17 03:11:43 [multiproc_executor.py:880]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(Worker pid=20818) (Worker_TP2 pid=20818) ERROR 03-17 03:11:43 [multiproc_executor.py:880]                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(Worker pid=20816) (Worker_TP0 pid=20816) ERROR 03-17 03:11:43 [multiproc_executor.py:880]     return _npu_getCurrentRawStream(device)
(Worker pid=20823) (Worker_TP7 pid=20823) ERROR 03-17 03:11:43 [multiproc_executor.py:880]            ^^^^^^^^^^^^^^^^^^^^^^^^^
(Worker pid=20819) (Worker_TP3 pid=20819) ERROR 03-17 03:11:43 [multiproc_executor.py:880]     self._forward_core(
(Worker pid=20821) (Worker_TP5 pid=20821) ERROR 03-17 03:11:43 [multiproc_executor.py:880] RuntimeError: The Inner error is reported as above. The process exits for this inner error, and the current working operator name is aclnnCausalConv1d.
(Worker pid=20818) (Worker_TP2 pid=20818) ERROR 03-17 03:11:43 [multiproc_executor.py:880]   File "/usr/local/python3.11.14/lib/python3.11/site-packages/triton/runtime/jit.py", line 592, in run
(Worker pid=20816) (Worker_TP0 pid=20816) ERROR 03-17 03:11:43 [multiproc_executor.py:880]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(Worker pid=20823) (Worker_TP7 pid=20823) ERROR 03-17 03:11:43 [multiproc_executor.py:880]   File "/vllm-workspace/vllm/vllm/model_executor/models/qwen3_next.py", line 1451, in gdn_attention_core
(Worker pid=20819) (Worker_TP3 pid=20819) ERROR 03-17 03:11:43 [multiproc_executor.py:880]   File "/vllm-workspace/vllm-ascend/vllm_ascend/patch/worker/patch_qwen3_5.py", line 139, in _forward_core
(Worker pid=20821) (Worker_TP5 pid=20821) ERROR 03-17 03:11:43 [multiproc_executor.py:880] Since the operator is called asynchronously, the stacktrace may be inaccurate. If you want to get the accurate stacktrace, please set the environment variable ASCEND_LAUNCH_BLOCKING=1.
(Worker pid=20818) (Worker_TP2 pid=20818) ERROR 03-17 03:11:43 [multiproc_executor.py:880]     stream = driver.active.get_current_stream(device)
(Worker pid=20816) (Worker_TP0 pid=20816) ERROR 03-17 03:11:43 [multiproc_executor.py:880] RuntimeError: The Inner error is reported as above. The process exits for this inner error, and the current working operator name is aclnnCausalConv1d.
(Worker pid=20823) (Worker_TP7 pid=20823) ERROR 03-17 03:11:43 [multiproc_executor.py:880]     self._forward_core(
(Worker pid=20819) (Worker_TP3 pid=20819) ERROR 03-17 03:11:43 [multiproc_executor.py:880]     g, beta = fused_gdn_gating_patch(self.A_log, a, b, self.dt_bias)
(Worker pid=20821) (Worker_TP5 pid=20821) ERROR 03-17 03:11:43 [multiproc_executor.py:880] Note: ASCEND_LAUNCH_BLOCKING=1 will force ops to run in synchronous mode, resulting in performance degradation. Please unset ASCEND_LAUNCH_BLOCKING in time after debugging.
(Worker pid=20818) (Worker_TP2 pid=20818) ERROR 03-17 03:11:43 [multiproc_executor.py:880]              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(Worker pid=20816) (Worker_TP0 pid=20816) ERROR 03-17 03:11:43 [multiproc_executor.py:880] Since the operator is called asynchronously, the stacktrace may be inaccurate. If you want to get the accurate stacktrace, please set the environment variable ASCEND_LAUNCH_BLOCKING=1.
(Worker pid=20823) (Worker_TP7 pid=20823) ERROR 03-17 03:11:43 [multiproc_executor.py:880]   File "/vllm-workspace/vllm-ascend/vllm_ascend/patch/worker/patch_qwen3_5.py", line 139, in _forward_core
(Worker pid=20819) (Worker_TP3 pid=20819) ERROR 03-17 03:11:43 [multiproc_executor.py:880]               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(Worker pid=20821) (Worker_TP5 pid=20821) ERROR 03-17 03:11:43 [multiproc_executor.py:880] [ERROR] 2026-03-17-03:11:43 (PID:20821, Device:5, RankID:-1) ERR00100 PTA call acl api failed.
(Worker pid=20818) (Worker_TP2 pid=20818) ERROR 03-17 03:11:43 [multiproc_executor.py:880]   File "/usr/local/python3.11.14/lib/python3.11/site-packages/triton/backends/ascend/driver.py", line 219, in get_current_stream
(Worker pid=20816) (Worker_TP0 pid=20816) ERROR 03-17 03:11:43 [multiproc_executor.py:880] Note: ASCEND_LAUNCH_BLOCKING=1 will force ops to run in synchronous mode, resulting in performance degradation. Please unset ASCEND_LAUNCH_BLOCKING in time after debugging.
(Worker pid=20823) (Worker_TP7 pid=20823) ERROR 03-17 03:11:43 [multiproc_executor.py:880]     g, beta = fused_gdn_gating_patch(self.A_log, a, b, self.dt_bias)
(Worker pid=20819) (Worker_TP3 pid=20819) ERROR 03-17 03:11:43 [multiproc_executor.py:880]   File "/vllm-workspace/vllm-ascend/vllm_ascend/ops/triton/fused_gdn_gating.py", line 94, in fused_gdn_gating_patch
(Worker pid=20821) (Worker_TP5 pid=20821) ERROR 03-17 03:11:43 [multiproc_executor.py:880] 
(Worker pid=20818) (Worker_TP2 pid=20818) ERROR 03-17 03:11:43 [multiproc_executor.py:880]     return _npu_getCurrentRawStream(device)
(Worker pid=20816) (Worker_TP0 pid=20816) ERROR 03-17 03:11:43 [multiproc_executor.py:880] [ERROR] 2026-03-17-03:11:43 (PID:20816, Device:0, RankID:-1) ERR00100 PTA call acl api failed.
(Worker pid=20823) (Worker_TP7 pid=20823) ERROR 03-17 03:11:43 [multiproc_executor.py:880]               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(Worker pid=20819) (Worker_TP3 pid=20819) ERROR 03-17 03:11:43 [multiproc_executor.py:880]     fused_gdn_gating_kernel[grid](
(Worker pid=20821) (Worker_TP5 pid=20821) ERROR 03-17 03:11:43 [multiproc_executor.py:880] 
(Worker pid=20818) (Worker_TP2 pid=20818) ERROR 03-17 03:11:43 [multiproc_executor.py:880]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(Worker pid=20816) (Worker_TP0 pid=20816) ERROR 03-17 03:11:43 [multiproc_executor.py:880] 
(Worker pid=20823) (Worker_TP7 pid=20823) ERROR 03-17 03:11:43 [multiproc_executor.py:880]   File "/vllm-workspace/vllm-ascend/vllm_ascend/ops/triton/fused_gdn_gating.py", line 94, in fused_gdn_gating_patch
(Worker pid=20819) (Worker_TP3 pid=20819) ERROR 03-17 03:11:43 [multiproc_executor.py:880]   File "/usr/local/python3.11.14/lib/python3.11/site-packages/triton/runtime/jit.py", line 353, in <lambda>
(Worker pid=20818) (Worker_TP2 pid=20818) ERROR 03-17 03:11:43 [multiproc_executor.py:880] RuntimeError: The Inner error is reported as above. The process exits for this inner error, and the current working operator name is aclnnCausalConv1d.
(Worker pid=20816) (Worker_TP0 pid=20816) ERROR 03-17 03:11:43 [multiproc_executor.py:880] 
(Worker pid=20823) (Worker_TP7 pid=20823) ERROR 03-17 03:11:43 [multiproc_executor.py:880]     fused_gdn_gating_kernel[grid](
(Worker pid=20819) (Worker_TP3 pid=20819) ERROR 03-17 03:11:43 [multiproc_executor.py:880]     return lambda *args, **kwargs: self.run(grid=grid, warmup=False, *args, **kwargs)
(Worker pid=20818) (Worker_TP2 pid=20818) ERROR 03-17 03:11:43 [multiproc_executor.py:880] Since the operator is called asynchronously, the stacktrace may be inaccurate. If you want to get the accurate stacktrace, please set the environment variable ASCEND_LAUNCH_BLOCKING=1.
(Worker pid=20823) (Worker_TP7 pid=20823) ERROR 03-17 03:11:43 [multiproc_executor.py:880]   File "/usr/local/python3.11.14/lib/python3.11/site-packages/triton/runtime/jit.py", line 353, in <lambda>
(Worker pid=20819) (Worker_TP3 pid=20819) ERROR 03-17 03:11:43 [multiproc_executor.py:880]                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(Worker pid=20818) (Worker_TP2 pid=20818) ERROR 03-17 03:11:43 [multiproc_executor.py:880] Note: ASCEND_LAUNCH_BLOCKING=1 will force ops to run in synchronous mode, resulting in performance degradation. Please unset ASCEND_LAUNCH_BLOCKING in time after debugging.
(Worker pid=20823) (Worker_TP7 pid=20823) ERROR 03-17 03:11:43 [multiproc_executor.py:880]     return lambda *args, **kwargs: self.run(grid=grid, warmup=False, *args, **kwargs)
(Worker pid=20819) (Worker_TP3 pid=20819) ERROR 03-17 03:11:43 [multiproc_executor.py:880]   File "/usr/local/python3.11.14/lib/python3.11/site-packages/triton/runtime/jit.py", line 592, in run
(Worker pid=20818) (Worker_TP2 pid=20818) ERROR 03-17 03:11:43 [multiproc_executor.py:880] [ERROR] 2026-03-17-03:11:43 (PID:20818, Device:2, RankID:-1) ERR00100 PTA call acl api failed.
(Worker pid=20823) (Worker_TP7 pid=20823) ERROR 03-17 03:11:43 [multiproc_executor.py:880]                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(Worker pid=20819) (Worker_TP3 pid=20819) ERROR 03-17 03:11:43 [multiproc_executor.py:880]     stream = driver.active.get_current_stream(device)
(Worker pid=20818) (Worker_TP2 pid=20818) ERROR 03-17 03:11:43 [multiproc_executor.py:880] 
(Worker pid=20823) (Worker_TP7 pid=20823) ERROR 03-17 03:11:43 [multiproc_executor.py:880]   File "/usr/local/python3.11.14/lib/python3.11/site-packages/triton/runtime/jit.py", line 592, in run
(Worker pid=20819) (Worker_TP3 pid=20819) ERROR 03-17 03:11:43 [multiproc_executor.py:880]              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(Worker pid=20818) (Worker_TP2 pid=20818) ERROR 03-17 03:11:43 [multiproc_executor.py:880] 
(Worker pid=20823) (Worker_TP7 pid=20823) ERROR 03-17 03:11:43 [multiproc_executor.py:880]     stream = driver.active.get_current_stream(device)
(Worker pid=20819) (Worker_TP3 pid=20819) ERROR 03-17 03:11:43 [multiproc_executor.py:880]   File "/usr/local/python3.11.14/lib/python3.11/site-packages/triton/backends/ascend/driver.py", line 219, in get_current_stream
(Worker pid=20823) (Worker_TP7 pid=20823) ERROR 03-17 03:11:43 [multiproc_executor.py:880]              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(Worker pid=20819) (Worker_TP3 pid=20819) ERROR 03-17 03:11:43 [multiproc_executor.py:880]     return _npu_getCurrentRawStream(device)
(Worker pid=20823) (Worker_TP7 pid=20823) ERROR 03-17 03:11:43 [multiproc_executor.py:880]   File "/usr/local/python3.11.14/lib/python3.11/site-packages/triton/backends/ascend/driver.py", line 219, in get_current_stream
(Worker pid=20819) (Worker_TP3 pid=20819) ERROR 03-17 03:11:43 [multiproc_executor.py:880]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(Worker pid=20823) (Worker_TP7 pid=20823) ERROR 03-17 03:11:43 [multiproc_executor.py:880]     return _npu_getCurrentRawStream(device)
(Worker pid=20819) (Worker_TP3 pid=20819) ERROR 03-17 03:11:43 [multiproc_executor.py:880] RuntimeError: The Inner error is reported as above. The process exits for this inner error, and the current working operator name is aclnnCausalConv1d.
(Worker pid=20823) (Worker_TP7 pid=20823) ERROR 03-17 03:11:43 [multiproc_executor.py:880]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(Worker pid=20819) (Worker_TP3 pid=20819) ERROR 03-17 03:11:43 [multiproc_executor.py:880] Since the operator is called asynchronously, the stacktrace may be inaccurate. If you want to get the accurate stacktrace, please set the environment variable ASCEND_LAUNCH_BLOCKING=1.
(Worker pid=20823) (Worker_TP7 pid=20823) ERROR 03-17 03:11:43 [multiproc_executor.py:880] RuntimeError: The Inner error is reported as above. The process exits for this inner error, and the current working operator name is aclnnCausalConv1d.
(Worker pid=20819) (Worker_TP3 pid=20819) ERROR 03-17 03:11:43 [multiproc_executor.py:880] Note: ASCEND_LAUNCH_BLOCKING=1 will force ops to run in synchronous mode, resulting in performance degradation. Please unset ASCEND_LAUNCH_BLOCKING in time after debugging.
(Worker pid=20823) (Worker_TP7 pid=20823) ERROR 03-17 03:11:43 [multiproc_executor.py:880] Since the operator is called asynchronously, the stacktrace may be inaccurate. If you want to get the accurate stacktrace, please set the environment variable ASCEND_LAUNCH_BLOCKING=1.
(Worker pid=20819) (Worker_TP3 pid=20819) ERROR 03-17 03:11:43 [multiproc_executor.py:880] [ERROR] 2026-03-17-03:11:43 (PID:20819, Device:3, RankID:-1) ERR00100 PTA call acl api failed.
(Worker pid=20823) (Worker_TP7 pid=20823) ERROR 03-17 03:11:43 [multiproc_executor.py:880] Note: ASCEND_LAUNCH_BLOCKING=1 will force ops to run in synchronous mode, resulting in performance degradation. Please unset ASCEND_LAUNCH_BLOCKING in time after debugging.
(Worker pid=20819) (Worker_TP3 pid=20819) ERROR 03-17 03:11:43 [multiproc_executor.py:880] 
(Worker pid=20823) (Worker_TP7 pid=20823) ERROR 03-17 03:11:43 [multiproc_executor.py:880] [ERROR] 2026-03-17-03:11:43 (PID:20823, Device:7, RankID:-1) ERR00100 PTA call acl api failed.
(Worker pid=20819) (Worker_TP3 pid=20819) ERROR 03-17 03:11:43 [multiproc_executor.py:880] 
(Worker pid=20823) (Worker_TP7 pid=20823) ERROR 03-17 03:11:43 [multiproc_executor.py:880] 
(Worker pid=20823) (Worker_TP7 pid=20823) ERROR 03-17 03:11:43 [multiproc_executor.py:880] 
(EngineCore_DP0 pid=20803) ERROR 03-17 03:11:43 [dump_input.py:72] Dumping input data for V1 LLM engine (v0.17.0) with config: model='/models/Qwen/Qwen3.5-27B/', speculative_config=None, tokenizer='/models/Qwen/Qwen3.5-27B/', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, tokenizer_revision=None, trust_remote_code=True, dtype=torch.bfloat16, max_seq_len=8192, download_dir=None, load_format=auto, tensor_parallel_size=8, pipeline_parallel_size=1, data_parallel_size=1, disable_custom_all_reduce=True, quantization=None, enforce_eager=True, enable_return_routed_experts=False, kv_cache_dtype=auto, device_config=npu, structured_outputs_config=StructuredOutputsConfig(backend='auto', disable_fallback=False, disable_any_whitespace=False, disable_additional_properties=False, reasoning_parser='', reasoning_parser_plugin='', enable_in_reasoning=False), observability_config=ObservabilityConfig(show_hidden_metrics_for_version=None, otlp_traces_endpoint=None, collect_detailed_traces=None, kv_cache_metrics=False, kv_cache_metrics_sample=0.01, cudagraph_metrics=False, enable_layerwise_nvtx_tracing=False, enable_mfu_metrics=False, enable_mm_processor_stats=False, enable_logging_iteration_details=False), seed=0, served_model_name=qwen3p5-27b, enable_prefix_caching=False, enable_chunked_prefill=True, pooler_config=None, compilation_config={'level': None, 'mode': <CompilationMode.NONE: 0>, 'debug_dump_path': None, 'cache_dir': '', 'compile_cache_save_format': 'binary', 'backend': 'vllm_ascend.compilation.compiler_interface.AscendCompiler', 'custom_ops': ['all'], 'splitting_ops': [], 'compile_mm_encoder': False, 'compile_sizes': [], 'compile_ranges_split_points': [16384], 'inductor_compile_config': {'enable_auto_functionalized_v2': False, 'combo_kernels': True, 'benchmark_combo_kernel': True}, 'inductor_passes': {}, 'cudagraph_mode': <CUDAGraphMode.NONE: 0>, 'cudagraph_num_of_warmups': 1, 'cudagraph_capture_sizes': [], 'cudagraph_copy_inputs': False, 'cudagraph_specialize_lora': True, 'use_inductor_graph_partition': False, 'pass_config': {'fuse_norm_quant': True, 'fuse_act_quant': True, 'fuse_attn_quant': False, 'enable_sp': False, 'fuse_gemm_comms': False, 'fuse_allreduce_rms': False}, 'max_cudagraph_capture_size': 0, 'dynamic_shapes_config': {'type': <DynamicShapesType.BACKED: 'backed'>, 'evaluate_guards': False, 'assume_32_bit_indexing': False}, 'local_cache_dir': None, 'fast_moe_cold_start': True, 'static_all_moe_layers': []}, 
(EngineCore_DP0 pid=20803) ERROR 03-17 03:11:43 [dump_input.py:79] Dumping scheduler output for model execution: SchedulerOutput(scheduled_new_reqs=[NewRequestData(req_id=chatcmpl-96e6d3f3e00885f9-82c34cd6,prompt_token_ids_len=13,prefill_token_ids_len=None,mm_features=[],sampling_params=SamplingParams(n=1, presence_penalty=0.0, frequency_penalty=0.0, repetition_penalty=1.0, temperature=0.6, top_p=0.95, top_k=20, min_p=0.0, seed=None, stop=[], stop_token_ids=[248044], bad_words=[], include_stop_str_in_output=False, ignore_eos=False, max_tokens=8179, min_tokens=0, logprobs=None, prompt_logprobs=None, skip_special_tokens=True, spaces_between_special_tokens=True, structured_outputs=None, extra_args=None),block_ids=([1], [2], [3], [4]),num_computed_tokens=0,lora_request=None,prompt_embeds_shape=None)], scheduled_cached_reqs=CachedRequestData(req_ids=[],resumed_req_ids=set(),new_token_ids_lens=[],all_token_ids_lens={},new_block_ids=[],num_computed_tokens=[],num_output_tokens=[]), num_scheduled_tokens={chatcmpl-96e6d3f3e00885f9-82c34cd6: 13}, total_num_scheduled_tokens=13, scheduled_spec_decode_tokens={}, scheduled_encoder_inputs={}, num_common_prefix_blocks=[0, 0, 0, 0], finished_req_ids=[], free_encoder_mm_hashes=[], preempted_req_ids=[], has_structured_output_requests=false, pending_structured_output_tokens=false, num_invalid_spec_tokens=null, kv_connector_metadata=null, ec_connector_metadata=null)
(EngineCore_DP0 pid=20803) ERROR 03-17 03:11:43 [dump_input.py:81] Dumping scheduler stats: SchedulerStats(num_running_reqs=1, num_waiting_reqs=0, step_counter=0, current_wave=0, kv_cache_usage=0.0011095700416088317, encoder_cache_usage=0.0, prefix_cache_stats=PrefixCacheStats(reset=False, requests=0, queries=0, hits=0, preempted_requests=0, preempted_queries=0, preempted_hits=0), connector_prefix_cache_stats=None, kv_cache_eviction_events=[], spec_decoding_stats=None, kv_connector_stats=None, waiting_lora_adapters={}, running_lora_adapters={}, cudagraph_stats=None, perf_stats=None)
(EngineCore_DP0 pid=20803) ERROR 03-17 03:11:43 [core.py:1102] EngineCore encountered a fatal error.
(EngineCore_DP0 pid=20803) ERROR 03-17 03:11:43 [core.py:1102] Traceback (most recent call last):
(EngineCore_DP0 pid=20803) ERROR 03-17 03:11:43 [core.py:1102]   File "/vllm-workspace/vllm/vllm/v1/engine/core.py", line 1093, in run_engine_core
(EngineCore_DP0 pid=20803) ERROR 03-17 03:11:43 [core.py:1102]     engine_core.run_busy_loop()
(EngineCore_DP0 pid=20803) ERROR 03-17 03:11:43 [core.py:1102]   File "/vllm-workspace/vllm/vllm/v1/engine/core.py", line 1128, in run_busy_loop
(EngineCore_DP0 pid=20803) ERROR 03-17 03:11:43 [core.py:1102]     self._process_engine_step()
(EngineCore_DP0 pid=20803) ERROR 03-17 03:11:43 [core.py:1102]   File "/vllm-workspace/vllm/vllm/v1/engine/core.py", line 1165, in _process_engine_step
(EngineCore_DP0 pid=20803) ERROR 03-17 03:11:43 [core.py:1102]     outputs, model_executed = self.step_fn()
(EngineCore_DP0 pid=20803) ERROR 03-17 03:11:43 [core.py:1102]                               ^^^^^^^^^^^^^^
(EngineCore_DP0 pid=20803) ERROR 03-17 03:11:43 [core.py:1102]   File "/vllm-workspace/vllm/vllm/v1/engine/core.py", line 501, in step_with_batch_queue
(EngineCore_DP0 pid=20803) ERROR 03-17 03:11:43 [core.py:1102]     exec_model_fut.result()
(EngineCore_DP0 pid=20803) ERROR 03-17 03:11:43 [core.py:1102]   File "/vllm-workspace/vllm/vllm/v1/executor/multiproc_executor.py", line 83, in result
(EngineCore_DP0 pid=20803) ERROR 03-17 03:11:43 [core.py:1102]     return super().result()
(EngineCore_DP0 pid=20803) ERROR 03-17 03:11:43 [core.py:1102]            ^^^^^^^^^^^^^^^^
(EngineCore_DP0 pid=20803) ERROR 03-17 03:11:43 [core.py:1102]   File "/usr/local/python3.11.14/lib/python3.11/concurrent/futures/_base.py", line 449, in result
(EngineCore_DP0 pid=20803) ERROR 03-17 03:11:43 [core.py:1102]     return self.__get_result()
(EngineCore_DP0 pid=20803) ERROR 03-17 03:11:43 [core.py:1102]            ^^^^^^^^^^^^^^^^^^^
(EngineCore_DP0 pid=20803) ERROR 03-17 03:11:43 [core.py:1102]   File "/usr/local/python3.11.14/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
(EngineCore_DP0 pid=20803) ERROR 03-17 03:11:43 [core.py:1102]     raise self._exception
(EngineCore_DP0 pid=20803) ERROR 03-17 03:11:43 [core.py:1102]   File "/vllm-workspace/vllm/vllm/v1/executor/multiproc_executor.py", line 87, in wait_for_response
(EngineCore_DP0 pid=20803) ERROR 03-17 03:11:43 [core.py:1102]     response = self.aggregate(get_response())
(EngineCore_DP0 pid=20803) ERROR 03-17 03:11:43 [core.py:1102]                               ^^^^^^^^^^^^^^
(EngineCore_DP0 pid=20803) ERROR 03-17 03:11:43 [core.py:1102]   File "/vllm-workspace/vllm/vllm/v1/executor/multiproc_executor.py", line 372, in get_response
(EngineCore_DP0 pid=20803) ERROR 03-17 03:11:43 [core.py:1102]     raise RuntimeError(
(EngineCore_DP0 pid=20803) ERROR 03-17 03:11:43 [core.py:1102] RuntimeError: Worker failed with error 'The Inner error is reported as above. The process exits for this inner error, and the current working operator name is aclnnCausalConv1d.
(EngineCore_DP0 pid=20803) ERROR 03-17 03:11:43 [core.py:1102] Since the operator is called asynchronously, the stacktrace may be inaccurate. If you want to get the accurate stacktrace, please set the environment variable ASCEND_LAUNCH_BLOCKING=1.
(EngineCore_DP0 pid=20803) ERROR 03-17 03:11:43 [core.py:1102] Note: ASCEND_LAUNCH_BLOCKING=1 will force ops to run in synchronous mode, resulting in performance degradation. Please unset ASCEND_LAUNCH_BLOCKING in time after debugging.
(EngineCore_DP0 pid=20803) ERROR 03-17 03:11:43 [core.py:1102] [ERROR] 2026-03-17-03:11:43 (PID:20816, Device:0, RankID:-1) ERR00100 PTA call acl api failed.
(EngineCore_DP0 pid=20803) ERROR 03-17 03:11:43 [core.py:1102] ', please check the stack trace above for the root cause
(APIServer pid=20784) ERROR 03-17 03:11:43 [async_llm.py:708] AsyncLLM output_handler failed.
(APIServer pid=20784) ERROR 03-17 03:11:43 [async_llm.py:708] Traceback (most recent call last):
(APIServer pid=20784) ERROR 03-17 03:11:43 [async_llm.py:708]   File "/vllm-workspace/vllm/vllm/v1/engine/async_llm.py", line 664, in output_handler
(APIServer pid=20784) ERROR 03-17 03:11:43 [async_llm.py:708]     outputs = await engine_core.get_output_async()
(APIServer pid=20784) ERROR 03-17 03:11:43 [async_llm.py:708]               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(APIServer pid=20784) ERROR 03-17 03:11:43 [async_llm.py:708]   File "/vllm-workspace/vllm/vllm/v1/engine/core_client.py", line 1009, in get_output_async
(APIServer pid=20784) ERROR 03-17 03:11:43 [async_llm.py:708]     raise self._format_exception(outputs) from None
(APIServer pid=20784) ERROR 03-17 03:11:43 [async_llm.py:708] vllm.v1.engine.exceptions.EngineDeadError: EngineCore encountered an issue. See stack trace (above) for the root cause.
(APIServer pid=20784) INFO:     172.17.0.1:51702 - "POST /v1/chat/completions HTTP/1.1" 500 Internal Server Error
```

**Comment by MengqingCao** [comment]
@ppppeng @shaopeng-666 PTAL, thx!

**Comment by sadbb** [comment]
昇腾卡还不支持0.17.0吧，我看官方更新到0.13.0，所以暂时不支持qwen3.5系列模型？

**Comment by 3030373635** [comment]
> 昇腾卡还不支持0.17.0吧，我看官方更新到0.13.0，所以暂时不支持qwen3.5系列模型？

我910b4启动qwen3.5 122b跟他这个错，很像

**Comment by xiongdoudou9527-commits** [comment]
> > 昇腾卡还不支持0.17.0吧，我看官方更新到0.13.0，所以暂时不支持qwen3.5系列模型？
> 
> 我910b4启动qwen3.5 122b跟他这个错，很像

--max-num-batched-tokens 放小一点试试，我设置为8192，可以正常运行，就是推理延迟比qwen3_5-v0-a2这个镜像还高，qwen3_5-v0-a2这个镜像的vllm版本是v0.16rc02好像

**Comment by 3030373635** [comment]
> > > 昇腾卡还不支持0.17.0吧，我看官方更新到0.13.0，所以暂时不支持qwen3.5系列模型？
> > 
> > 
> > 我910b4启动qwen3.5 122b跟他这个错，很像
> 
> --max-num-batched-tokens 放小一点试试，我设置为8192，可以正常运行，就是推理延迟比qwen3_5-v0-a2这个镜像还高，qwen3_5-v0-a2这个镜像的vllm版本是v0.16rc02好像

方便发下您的启动参数吗，您使用的0day还是vllm0.17.0rc1

**Comment by tutain2005** [comment]
export PYTORCH_NPU_ALLOC_CONF=expandable_segments:True
export HCCL_BUFFSIZE=512
export OMP_PROC_BIND=false
export OMP_NUM_THREADS=1
export TASK_QUEUE_ENABLE=1

vllm serve /models/Qwen3.5-27B/
--served-model-name "qwen35"
--host 0.0.0.0
--port 8090
--data-parallel-size 2
--tensor-parallel-size 4
--seed 1024
--max-num-seqs 64
--max-model-len 262144
--max-num-batched-tokens 16384
--trust-remote-code
--gpu-memory-utilization 0.8
--speculative_config '{"method": "qwen3_5_mtp", "num_speculative_tokens": 3}'
--compilation-config '{"cudagraph_mode":"FULL_DECODE_ONLY","cudagraph_capture_sizes":[1,2,4,8,16,32,64,80,96,128]}'
--additional-config '{"enable_cpu_binding":true,"ascend_turbo_graph_config": {"enabled": true}}'
--async-scheduling

TP开到8好像一直报错，开到4可以拉起

**Comment by tutain2005** [comment]
> > export PYTORCH_NPU_ALLOC_CONF=expandable_segments:True export HCCL_BUFFSIZE=512 export OMP_PROC_BIND=false export OMP_NUM_THREADS=1 export TASK_QUEUE_ENABLE=1
> > vllm serve /models/Qwen3.5-27B/ --served-model-name "qwen35" --host 0.0.0.0 --port 8090 --data-parallel-size 2 --tensor-parallel-size 4 --seed 1024 --max-num-seqs 64 --max-model-len 262144 --max-num-batched-tokens 16384 --trust-remote-code --gpu-memory-utilization 0.8 --speculative_config '{"method": "qwen3_5_mtp", "num_speculative_tokens": 3}' --compilation-config '{"cudagraph_mode":"FULL_DECODE_ONLY","cudagraph_capture_sizes":[1,2,4,8,16,32,64,80,96,128]}' --additional-config '{"enable_cpu_binding":true,"ascend_turbo_graph_config": {"enabled": true}}' --async-scheduling
> > TP开到8好像一直报错，开到4可以拉起
> 
> 4张卡能起的起来？

8卡，dp2，tp4

**Comment by 3030373635** [comment]
> > > export PYTORCH_NPU_ALLOC_CONF=expandable_segments:True export HCCL_BUFFSIZE=512 export OMP_PROC_BIND=false export OMP_NUM_THREADS=1 export TASK_QUEUE_ENABLE=1
> > > vllm serve /models/Qwen3.5-27B/ --served-model-name "qwen35" --host 0.0.0.0 --port 8090 --data-parallel-size 2 --tensor-parallel-size 4 --seed 1024 --max-num-seqs 64 --max-model-len 262144 --max-num-batched-tokens 16384 --trust-remote-code --gpu-memory-utilization 0.8 --speculative_config '{"method": "qwen3_5_mtp", "num_speculative_tokens": 3}' --compilation-config '{"cudagraph_mode":"FULL_DECODE_ONLY","cudagraph_capture_sizes":[1,2,4,8,16,32,64,80,96,128]}' --additional-config '{"enable_cpu_binding":true,"ascend_turbo_graph_config": {"enabled": true}}' --async-scheduling
> > > TP开到8好像一直报错，开到4可以拉起
> > 
> > 
> > 4张卡能起的起来？
> 
> 8卡，dp2，tp4

谢谢bro，122b我跑起来了，可惜了，要是可以6卡跑起来就好了，用8卡跑。就没有资源跑其他模型了

**Comment by tutain2005** [comment]
> > > > export PYTORCH_NPU_ALLOC_CONF=expandable_segments:True export HCCL_BUFFSIZE=512 export OMP_PROC_BIND=false export OMP_NUM_THREADS=1 export TASK_QUEUE_ENABLE=1
> > > > vllm serve /models/Qwen3.5-27B/ --served-model-name "qwen35" --host 0.0.0.0 --port 8090 --data-parallel-size 2 --tensor-parallel-size 4 --seed 1024 --max-num-seqs 64 --max-model-len 262144 --max-num-batched-tokens 16384 --trust-remote-code --gpu-memory-utilization 0.8 --speculative_config '{"method": "qwen3_5_mtp", "num_speculative_tokens": 3}' --compilation-config '{"cudagraph_mode":"FULL_DECODE_ONLY","cudagraph_capture_sizes":[1,2,4,8,16,32,64,80,96,128]}' --additional-config '{"enable_cpu_binding":true,"ascend_turbo_graph_config": {"enabled": true}}' --async-scheduling
> > > > TP开到8好像一直报错，开到4可以拉起
> > > 
> > > 
> > > 4张卡能起的起来？
> > 
> > 
> > 8卡，dp2，tp4
> 
> 谢谢bro，122b我跑起来了，可惜了，要是可以6卡跑起来就好了，用8卡跑。就没有资源跑其他模型了

可以尝试tp2，pp3，手动指定pp切分层方式部署试试

**Comment by wuzheren** [comment]
dp2，tp4是可以，但tp8还是不行，这个目前有办法解决吗

**Comment by sharptornadoqsh** [comment]
这组参数能用，8张64GB的910B

> export PYTORCH_NPU_ALLOC_CONF=expandable_segments:True export HCCL_BUFFSIZE=512 export OMP_PROC_BIND=false export OMP_NUM_THREADS=1 export TASK_QUEUE_ENABLE=1
> 
> vllm serve /models/Qwen3.5-27B/ --served-model-name "qwen35" --host 0.0.0.0 --port 8090 --data-parallel-size 2 --tensor-parallel-size 4 --seed 1024 --max-num-seqs 64 --max-model-len 262144 --max-num-batched-tokens 16384 --trust-remote-code --gpu-memory-utilization 0.8 --speculative_config '{"method": "qwen3_5_mtp", "num_speculative_tokens": 3}' --compilation-config '{"cudagraph_mode":"FULL_DECODE_ONLY","cudagraph_capture_sizes":[1,2,4,8,16,32,64,80,96,128]}' --additional-config '{"enable_cpu_binding":true,"ascend_turbo_graph_config": {"enabled": true}}' --async-scheduling
> 
> TP开到8好像一直报错，开到4可以拉起

**Comment by RyanOvO** [comment]
使用eager模式可以绕过，加上 `--enforce-eager \`

**Comment by sharptornadoqsh** [comment]
您好，您的邮件我已经收到，我会尽快处理
