### ISSUE TITLE
[Bug][Qwen3.5][FullGraph]: The DDR address of the MTE instruction is out of range

### ISSUE THREAD

**Issue by Levi-JQ** [vllm-project/vllm-ascend#7570]
### Your current environment

<details>
<summary>The output of `python collect_env.py`</summary>

```text
Your output of above commands here
```

</details>

### 🐛 Describe the bug

```shell
vllm :  bcf2be96120005e9aea171927f85055a6a5c0cf6
vllm-ascend : 9d0b7c8e98032086204c0af22c342a845ab7f9c0
```

启动脚本：
```shell
export VLLM_USE_V1=1
export VLLM_EXECUTE_MODEL_TIMEOUT_SECONDS=380

export OTEL_EXPORTER_OTLP_TRACES_PROTOCOL=http/protobuf
export PROMETHEUS_MULTIPROC_DIR=/tmp/

export COMMON_ARGS="
    --trust-remote-code
    --served-model-name auto
    --distributed-executor-backend mp
    --model-loader-extra-config {\"enable_multithread_load\":true,\"num_threads\":8}
    --enable-log-requests
    --enable-prompt-tokens-details
    --otlp-traces-endpoint https://antcollector.alipay.com/namespace/aicloud/task/otlptrace/otlp/api/v1/traces
"

export HCCL_BUFFSIZE=512
export VLLM_ASCEND_ENABLE_NZ=2
export PYTORCH_NPU_ALLOC_CONF=expandable_segments:True

export VLLM_ASCEND_ENABLE_FUSED_MC2=1
nohup vllm serve /sfs_turbo/models/Qwen3.5-397B-A17B-w8a8-mtp \
    $COMMON_ARGS \
    --port 8006 \
    -tp 16 \
    -dp 1 \
    --max-model-len 262144 \
    --max-num-batched-tokens 16384 \
    --max-num-seqs 128 \
    --gpu-memory-utilization 0.94 \
    --compilation-config '{"cudagraph_capture_sizes":[1,4,8,16,32,64,72,128], "cudagraph_mode":"FULL_DECODE_ONLY"}' \
    --async-scheduling \
    --quantization ascend \
    --mm-processor-cache-gb 0 \
    --enable-expert-parallel \
    --additional-config '{"enable_cpu_binding":true, "multistream_overlap_shared_expert": true}' > qwen35-server.log 2>&1 &
```

测试方法：多模态图片数据集高并发（1024并发）打流测试复现

报错信息如下：
```shell
Traceback (most recent call last):^M
(Worker_TP15_EP15 pid=546306) ERROR 2026-03-23 13:28:52.481 [multiproc_executor.py:932]   File "/sfs_turbo/hw/yujinqi/issue/flashcomm2-official/vllm/vllm/v1/executor/multiproc_executor.py", line 927, in worker_busy_loop^M
(Worker_TP15_EP15 pid=546306) ERROR 2026-03-23 13:28:52.481 [multiproc_executor.py:932]     output = func(*args, **kwargs)^M
(Worker_TP15_EP15 pid=546306) ERROR 2026-03-23 13:28:52.481 [multiproc_executor.py:932]              ^^^^^^^^^^^^^^^^^^^^^^M
(Worker_TP15_EP15 pid=546306) ERROR 2026-03-23 13:28:52.481 [multiproc_executor.py:932]   File "/sfs_turbo/hw/yujinqi/issue/flashcomm2-official/vllm/vllm/v1/worker/worker_base.py", line 332, in execute_model^M
(Worker_TP15_EP15 pid=546306) ERROR 2026-03-23 13:28:52.481 [multiproc_executor.py:932]     return self.worker.execute_model(scheduler_output)^M
(Worker_TP15_EP15 pid=546306) ERROR 2026-03-23 13:28:52.481 [multiproc_executor.py:932]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^M
(Worker_TP15_EP15 pid=546306) ERROR 2026-03-23 13:28:52.481 [multiproc_executor.py:932]   File "/sfs_turbo/hw/yujinqi/issue/flashcomm2-official/vllm-ascend/vllm_ascend/worker/worker.py", line 406, in execute_model^M
(Worker_TP15_EP15 pid=546306) ERROR 2026-03-23 13:28:52.481 [multiproc_executor.py:932]     output = self.model_runner.execute_model(scheduler_output, intermediate_tensors)^M
(Worker_TP15_EP15 pid=546306) ERROR 2026-03-23 13:28:52.481 [multiproc_executor.py:932]              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^M
(Worker_TP15_EP15 pid=546306) ERROR 2026-03-23 13:28:52.481 [multiproc_executor.py:932]   File "/usr/local/python3.11.14/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 120, in decorate_context^M
(Worker_TP15_EP15 pid=546306) ERROR 2026-03-23 13:28:52.481 [multiproc_executor.py:932]     return func(*args, **kwargs)^M
(Worker_TP15_EP15 pid=546306) ERROR 2026-03-23 13:28:52.481 [multiproc_executor.py:932]            ^^^^^^^^^^^^^^^^^^^^^^M
(Worker_TP15_EP15 pid=546306) ERROR 2026-03-23 13:28:52.481 [multiproc_executor.py:932]   File "/sfs_turbo/hw/yujinqi/issue/flashcomm2-official/vllm-ascend/vllm_ascend/worker/model_runner_v1.py", line 1387, in execute_model^M
(Worker_TP15_EP15 pid=546306) ERROR 2026-03-23 13:28:52.481 [multiproc_executor.py:932]     hidden_states = self._model_forward(^M
(Worker_TP15_EP15 pid=546306) ERROR 2026-03-23 13:28:52.481 [multiproc_executor.py:932]                     ^^^^^^^^^^^^^^^^^^^^^M
(Worker_TP15_EP15 pid=546306) ERROR 2026-03-23 13:28:52.481 [multiproc_executor.py:932]   File "/sfs_turbo/hw/yujinqi/issue/flashcomm2-official/vllm-ascend/vllm_ascend/worker/model_runner_v1.py", line 1816, in _model_forward^M
(Worker_TP15_EP15 pid=546306) ERROR 2026-03-23 13:28:52.481 [multiproc_executor.py:932]     hidden_states = self.model(^M
(Worker_TP15_EP15 pid=546306) ERROR 2026-03-23 13:28:52.481 [multiproc_executor.py:932]                     ^^^^^^^^^^^^M
(Worker_TP15_EP15 pid=546306) ERROR 2026-03-23 13:28:52.481 [multiproc_executor.py:932]   File "/sfs_turbo/hw/yujinqi/issue/flashcomm2-official/vllm-ascend/vllm_ascend/compilation/acl_graph.py", line 201, in __call__^M
(Worker_TP15_EP15 pid=546306) ERROR 2026-03-23 13:28:52.481 [multiproc_executor.py:932]     torch.npu.current_stream().synchronize()^M
(Worker_TP15_EP15 pid=546306) ERROR 2026-03-23 13:28:52.481 [multiproc_executor.py:932]   File "/usr/local/python3.11.14/lib/python3.11/site-packages/torch_npu/npu/streams.py", line 85, in synchronize^M
(Worker_TP15_EP15 pid=546306) ERROR 2026-03-23 13:28:52.481 [multiproc_executor.py:932]     super(Stream, self).synchronize()^M
(Worker_TP15_EP15 pid=546306) ERROR 2026-03-23 13:28:52.481 [multiproc_executor.py:932] RuntimeError: synchronize:build/CMakeFiles/torch_npu.dir/compiler_depend.ts:361 NPU function error: c10_npu::acl::AclrtSynchronizeStreamWithTimeout(stream()), error code is 507011^M
(Worker_TP15_EP15 pid=546306) ERROR 2026-03-23 13:28:52.481 [multiproc_executor.py:932] [ERROR] 2026-03-23-13:28:52 (PID:546306, Device:15, RankID:-1) ERR00100 PTA call acl api failed^M
(Worker_TP15_EP15 pid=546306) ERROR 2026-03-23 13:28:52.481 [multiproc_executor.py:932] [Error]: Model execution failed. ^M
(Worker_TP15_EP15 pid=546306) ERROR 2026-03-23 13:28:52.481 [multiproc_executor.py:932]         Rectify the fault based on the error information in the ascend log.^M
(Worker_TP15_EP15 pid=546306) ERROR 2026-03-23 13:28:52.481 [multiproc_executor.py:932] EZ9999: Inner Error!^M
(Worker_TP15_EP15 pid=546306) ERROR 2026-03-23 13:28:52.481 [multiproc_executor.py:932] EZ9999[PID: 546306] 2026-03-23-13:28:52.455.705 (EZ9999):  The error from device(chipId:7, dieId:1), serial number is 64, there is an exception of aivec error, core id is 6, error code = 0x800000, dump info: pc start: 0x12c0c124bb8c, current: 0x12c0c124d58c, vec error info: 0xf1009e21c2, mte error info: 0x330300f0e6, ifu error info: 0x40c3d4ab01000, ccu error info: 0x1a08e83b5262c871, cube error info: 0, biu error info: 0, aic error mask: 0x6500020bd00028c, para base: 0x12c14169e000.[FUNC:PrintCoreInfo][FILE:device_error_core_proc.cc][LINE:347]^M
(Worker_TP15_EP15 pid=546306) ERROR 2026-03-23 13:28:52.481 [multiproc_executor.py:932]         TraceBack (most recent call last):^M
(Worker_TP15_EP15 pid=546306) ERROR 2026-03-23 13:28:52.481 [multiproc_executor.py:932]        The extend info: errcode:(0x800000, 0, 0) errorStr: The DDR address of the MTE instruction is out of range. fixp_error0 info: 0x300f0e6, fixp_error1 info: 0x33, fsmId:0, tslot:6, thread:0, ctxid:0, blk:2, sublk:0, subErrType:4.[FUNC:PrintCoreInfo][FILE:device_error_core_proc.cc][LINE:360]^M
(Worker_TP15_EP15 pid=546306) ERROR 2026-03-23 13:28:52.481 [multiproc_executor.py:932]        The error from device(chipId:7, dieId:1), serial number is 64, there is an exception of aivec error, core id is 7, error code = 0x800000, dump info: pc start: 0x12c0c124bb8c, current: 0x12c0c124d58c, vec error info: 0x46155441d7, mte error info: 0x33030040e6, ifu error info: 0x6c28f18264800, ccu error info: 0xee5e208900280, cube error info: 0, biu error info: 0, aic error mask: 0x6500020bd00028c, para base: 0x12c14169e000.[FUNC:PrintCoreInfo][FILE:device_error_core_proc.cc][LINE:347]
```

**Comment by linfeng-yuan** [comment]
Hi, please provide the output of `python collect_env.py`  in this issue context. @Levi-JQ

**Comment by linfeng-yuan** [comment]
Please have a look about this kernel error log with Qwen3.5 model. @LoganJane @shaopeng-666

**Comment by seven-mile** [comment]
I have the same problem for Qwen3 BF16 EP8 w/ MC2 (Non-Fused), FULL_DECODE_ONLY Graph and speculative decoding.

Please check [this plog file](https://gist.github.com/seven-mile/5e07819f9aa0b88d8340a8d9f377a761), I believe it reveals that the root cause is in `FusedInferAttentionScore` kernel.

PIECEWISE graph mode works flawlessly.

AFAIK, vllm-ascend has a complicated mechanism of `update_full_graph_params`, which interacts with attention backend with some magic kernel calls. Do we have any design docs about it to help with understanding what's happening here?

**Comment by LoganJane** [comment]
@Levi-JQ This issue has been resolved in the latest version. Please use the latest release or rc version (https://github.com/vllm-project/vllm-ascend/releases). If the issue persists, feel free to submit a new issue.
