### ISSUE TITLE
[Bug]: Qwen3.5-397B Prefill Decode Disaggregation fail requesting with set non zero temperature or without setting temperature

### ISSUE THREAD

**Issue by qaz2883383** [vllm-project/vllm-ascend#7604]
### Your current environment

<details>
<summary>The output of `python collect_env.py`</summary>
   using docker images 0.17.0RC1

```text
Qwen3.5-397B Prefill Decode Disaggregation fail requesting with set non zero temperature or without setting temperature
```

</details>
`
curl with temperature: 0    success
curl with temperature: 0.6 fail
curl without temperature  fail
`

### 🐛 Describe the bug

`
starting service with:

*******************p0
#!/bin/bash

# ==================== 网络配置 ====================
nic_name="eth0"
local_ip="10.222.33.235"
node0_ip="10.222.33.235"

# ==================== 环境变量设置 ====================
# 网络通信
export HCCL_IF_IP=$local_ip
export GLOO_SOCKET_IFNAME=$nic_name
export TP_SOCKET_IFNAME=$nic_name
export HCCL_SOCKET_IFNAME=$nic_name

# HCCL 配置
export HCCL_BUFFSIZE=200
export HCCL_INTRA_PCIE_ENABLE=1
export HCCL_INTRA_ROCE_ENABLE=0
export HCCL_OP_EXPANSION_MODE="AIV"

# HCCL 超时配置（新增）
export HCCL_EXEC_TIMEOUT=60
export HCCL_CONNECT_TIMEOUT=120

# NPU 内存配置
export PYTORCH_NPU_ALLOC_CONF="expandable_segments:True"

# 任务调度
export OMP_PROC_BIND=false
export OMP_NUM_THREADS=1
export TASK_QUEUE_ENABLE=1
export VLLM_ASCEND_BALANCE_SCHEDULING=1
export VLLM_ENGINE_READY_TIMEOUT_S=1200

# vLLM 相关配置（新增）
export VLLM_NIXL_ABORT_REQUEST_TIMEOUT=30000
export VLLM_TORCH_PROFILER_WITH_STACK=0

# 可选配置（根据需要开启）
# export VLLM_ASCEND_ENABLE_FLASHCOMM1=1
# export VLLM_TORCH_PROFILER_DIR=/home/profile

# ==================== 启动 vLLM 服务 ====================
vllm serve /workspace/mnt/models/Qwen3.5-397B-A17B-w8a8-mtp \
    --served-model-name "qwen35" \
    --trust-remote-code \
    --seed 1024 \
    --no-enable-prefix-caching \
    --distributed-executor-backend mp \
    --allowed-local-media-path / \
    \
    --tensor-parallel-size 8 \
    --data-parallel-size 2 \
    --data-parallel-size-local 1 \
    --enable-expert-parallel \
    --api-server-count 1 \
    --data-parallel-address 10.222.33.235 \
    --data-parallel-rpc-port 6884 \
    \
    --max-model-len 131072 \
    --max-num-batched-tokens 16384 \
    --max-num-seqs 32 \
    --gpu-memory-utilization 0.95 \
    \
    --quantization ascend \
    --no-disable-hybrid-kv-cache-manager \
    \
    --async-scheduling \
    --enforce-eager \
    \
    --speculative_config '{
        "method": "qwen3_5_mtp",
        "num_speculative_tokens": 3,
        "enforce_eager": true
    }' \
    \
    --additional-config '{
        "recompute_scheduler_enable": true
    }' \
    \
    --kv-transfer-config '{
        "kv_connector": "MooncakeLayerwiseConnector",
        "kv_role": "kv_producer",
        "kv_port": "23010",
        "engine_id": "0",
        "kv_connector_extra_config": {
            "prefill": {
                "dp_size": 2,
                "tp_size": 8
            },
            "decode": {
                "dp_size": 2,
                "tp_size": 8
            }
        }
    }'

*****************p1

#!/bin/bash

# ==================== 网络配置 ====================
nic_name="eth0"
local_ip="10.222.62.225"
node0_ip="10.222.33.235"

# ==================== 环境变量设置 ====================
# 网络通信
export HCCL_IF_IP=$local_ip
export GLOO_SOCKET_IFNAME=$nic_name
export TP_SOCKET_IFNAME=$nic_name
export HCCL_SOCKET_IFNAME=$nic_name

# HCCL 配置
export HCCL_BUFFSIZE=200
export HCCL_INTRA_PCIE_ENABLE=1
export HCCL_INTRA_ROCE_ENABLE=0
export HCCL_OP_EXPANSION_MODE="AIV"

# HCCL 超时配置
export HCCL_EXEC_TIMEOUT=60
export HCCL_CONNECT_TIMEOUT=120

# NPU 内存配置
export PYTORCH_NPU_ALLOC_CONF="expandable_segments:True"

# 任务调度
export OMP_PROC_BIND=false
export OMP_NUM_THREADS=1
export TASK_QUEUE_ENABLE=1
export VLLM_ASCEND_BALANCE_SCHEDULING=1
export VLLM_ENGINE_READY_TIMEOUT_S=1200

# vLLM 相关配置
export VLLM_NIXL_ABORT_REQUEST_TIMEOUT=30000
export VLLM_TORCH_PROFILER_WITH_STACK=0

# 可选配置（根据需要开启）
# export VLLM_ASCEND_ENABLE_FLASHCOMM1=1
# export VLLM_TORCH_PROFILER_DIR=/home/profile

# ==================== 启动 vLLM 服务 ====================
vllm serve /workspace/mnt/models/Qwen3.5-397B-A17B-w8a8-mtp \
    --served-model-name "qwen35" \
    --trust-remote-code \
    --seed 1024 \
    --no-enable-prefix-caching \
    --distributed-executor-backend mp \
    --allowed-local-media-path / \
    \
    --tensor-parallel-size 8 \
    --data-parallel-size 2 \
    --data-parallel-size-local 1 \
    --data-parallel-start-rank 1 \
    --enable-expert-parallel \
    --data-parallel-address 10.222.33.235 \
    --data-parallel-rpc-port 6884 \
    --headless \
    \
    --max-model-len 131072 \
    --max-num-batched-tokens 16384 \
    --max-num-seqs 32 \
    --gpu-memory-utilization 0.95 \
    \
    --quantization ascend \
    --no-disable-hybrid-kv-cache-manager \
    \
    --async-scheduling \
    --enforce-eager \
    \
    --speculative_config '{
        "method": "qwen3_5_mtp",
        "num_speculative_tokens": 3,
        "enforce_eager": true
    }' \
    \
    --additional-config '{
        "recompute_scheduler_enable": true
    }' \
    \
    --kv-transfer-config '{
        "kv_connector": "MooncakeLayerwiseConnector",
        "kv_role": "kv_producer",
        "kv_port": "23010",
        "engine_id": "0",
        "kv_connector_extra_config": {
            "prefill": {
                "dp_size": 2,
                "tp_size": 8
            },
            "decode": {
                "dp_size": 2,
                "tp_size": 8
            }
        }
    }'

**************d0
#!/bin/bash

# ==================== 网络配置 ====================
# 通过 ifconfig 获取本机信息
# nic_name 为当前节点 local_ip 对应的网卡接口名称
nic_name="eth0"
local_ip="10.222.62.34"

# node0_ip 的值必须与节点0（主节点）中设置的 local_ip 一致
node0_ip="10.222.62.34"

# ==================== 环境变量设置 ====================
# 网络通信
export HCCL_IF_IP=$local_ip
export GLOO_SOCKET_IFNAME=$nic_name
export TP_SOCKET_IFNAME=$nic_name
export HCCL_SOCKET_IFNAME=$nic_name

# HCCL 配置
export HCCL_BUFFSIZE=1024
export HCCL_INTRA_PCIE_ENABLE=1
export HCCL_INTRA_ROCE_ENABLE=0
export HCCL_OP_EXPANSION_MODE="AIV"

# NPU 内存配置
export PYTORCH_NPU_ALLOC_CONF="expandable_segments:True"

# 任务调度
export OMP_PROC_BIND=false
export OMP_NUM_THREADS=1
export TASK_QUEUE_ENABLE=1
export VLLM_ASCEND_BALANCE_SCHEDULING=1
export VLLM_ENGINE_READY_TIMEOUT_S=3600

export HCCL_EXEC_TIMEOUT=60
export HCCL_CONNECT_TIMEOUT=120
export VLLM_NIXL_ABORT_REQUEST_TIMEOUT=30000
export VLLM_TORCH_PROFILER_WITH_STACK=0
# 可选配置（根据需要开启）
# export VLLM_ASCEND_ENABLE_FLASHCOMM1=1
# export VLLM_TORCH_PROFILER_DIR=/home/profile

# ==================== 启动 vLLM 服务 ====================
vllm serve /workspace/mnt/models/Qwen3.5-397B-A17B-w8a8-mtp \
    --served-model-name "qwen35" \
    --trust-remote-code \
    --seed 1024 \
    --no-enable-prefix-caching \
    --distributed-executor-backend mp \
    --allowed-local-media-path / \
    \
    --tensor-parallel-size 8 \
    --data-parallel-size 2 \
    --data-parallel-size-local 1 \
    --enable-expert-parallel \
    --api-server-count 1 \
    --data-parallel-address 10.222.62.34 \
    --data-parallel-rpc-port 6884 \
    \
    --max-model-len 131072 \
    --max-num-batched-tokens 4096 \
    --max-num-seqs 32 \
    --gpu-memory-utilization 0.95 \
    \
    --quantization ascend \
    --no-disable-hybrid-kv-cache-manager \
    \
    --async-scheduling \
    \
    --compilation-config '{
        "cudagraph_capture_sizes": [1,4,8,12,16,24,32,48,56,64],
        "cudagraph_mode": "PIECEWISE"
    }' \
    --speculative_config '{
        "method": "qwen3_5_mtp",
        "num_speculative_tokens": 3,
        "enforce_eager": true
    }' \
    --additional-config '{
        "recompute_scheduler_enable": true
    }' \
    --kv-transfer-config '{
        "kv_connector": "MooncakeLayerwiseConnector",
        "kv_role": "kv_consumer",
        "kv_port": "23010",
        "engine_id": "0",
        "kv_connector_extra_config": {
            "prefill": {
                "dp_size": 2,
                "tp_size": 8
            },
            "decode": {
                "dp_size": 2,
                "tp_size": 8
            }
        }
    }'
    

****************d1
#!/bin/bash

# ==================== 网络配置 ====================
# 通过 ifconfig 获取本机信息
# nic_name 为当前节点 local_ip 对应的网卡接口名称
nic_name="eth0"
local_ip="10.222.50.227"

# node0_ip 的值必须与节点0（主节点）中设置的 local_ip 一致
node0_ip="10.222.62.34"

# ==================== 环境变量设置 ====================
# 网络通信
export HCCL_IF_IP=$local_ip
export GLOO_SOCKET_IFNAME=$nic_name
export TP_SOCKET_IFNAME=$nic_name
export HCCL_SOCKET_IFNAME=$nic_name

# HCCL 配置
export HCCL_BUFFSIZE=1024
export HCCL_INTRA_PCIE_ENABLE=1
export HCCL_INTRA_ROCE_ENABLE=0
export HCCL_OP_EXPANSION_MODE="AIV"

# NPU 内存配置
export PYTORCH_NPU_ALLOC_CONF="expandable_segments:True"

# 任务调度
export OMP_PROC_BIND=false
export OMP_NUM_THREADS=1
export TASK_QUEUE_ENABLE=1
export VLLM_ASCEND_BALANCE_SCHEDULING=1
export VLLM_ENGINE_READY_TIMEOUT_S=3600
export HCCL_EXEC_TIMEOUT=60
export HCCL_CONNECT_TIMEOUT=120
export VLLM_NIXL_ABORT_REQUEST_TIMEOUT=30000
export VLLM_TORCH_PROFILER_WITH_STACK=0
# 可选配置（根据需要开启）
# export VLLM_ASCEND_ENABLE_FLASHCOMM1=1
# export VLLM_TORCH_PROFILER_DIR=/home/profile

# ==================== 启动 vLLM 服务 ====================
vllm serve /workspace/mnt/models/Qwen3.5-397B-A17B-w8a8-mtp \
    --served-model-name "qwen35" \
    --trust-remote-code \
    --seed 1024 \
    --no-enable-prefix-caching \
    --distributed-executor-backend mp \
    --allowed-local-media-path / \
    \
    --tensor-parallel-size 8 \
    --data-parallel-size 2 \
    --data-parallel-size-local 1 \
    --data-parallel-start-rank 1 \
    --enable-expert-parallel \
    --data-parallel-address 10.222.62.34 \
    --data-parallel-rpc-port 6884 \
    --headless \
    \
    --max-model-len 131072 \
    --max-num-batched-tokens 4096 \
    --max-num_seqs 32 \
    --gpu-memory-utilization 0.95 \
    \
    --quantization ascend \
    --no-disable-hybrid-kv-cache-manager \
    \
    --async-scheduling \
    \
    --compilation-config '{"cudagraph_capture_sizes":[1,4,8,12,16,24,32,48,56,64], "cudagraph_mode":"PIECEWISE"}' \
    --speculative_config '{
        "method": "qwen3_5_mtp",
        "num_speculative_tokens": 3,
        "enforce_eager": true
    }' \
    \
    --additional-config '{
        "recompute_scheduler_enable": true
    }' \
    \
    --kv-transfer-config '{
        "kv_connector": "MooncakeLayerwiseConnector",
        "kv_role": "kv_consumer",
        "kv_port": "23010",
        "engine_id": "0",
        "kv_connector_extra_config": {
            "prefill": {
                "dp_size": 2,
                "tp_size": 8
            },
            "decode": {
                "dp_size": 2,
                "tp_size": 8
            }
        }
    }'
`

```
ERROR message:
(Worker pid=721) (Worker_DP0_TP6_EP6 pid=721) INFO 03-24 16:16:58 [mooncake_layerwise_connector.py:1235] Number of completed KV cache recv requests: 1, receive requests: {'chatcmpl-8c55aca7-251c-4f21-a77c-a5a1fa16950e-a5bee80a'}
(Worker pid=669) (Worker_DP0_TP5_EP5 pid=669) INFO 03-24 16:16:58 [mooncake_layerwise_connector.py:1235] Number of completed KV cache recv requests: 1, receive requests: {'chatcmpl-8c55aca7-251c-4f21-a77c-a5a1fa16950e-a5bee80a'}
(Worker pid=455) (Worker_DP0_TP1_EP1 pid=455) INFO 03-24 16:16:58 [mooncake_layerwise_connector.py:1235] Number of completed KV cache recv requests: 1, receive requests: {'chatcmpl-8c55aca7-251c-4f21-a77c-a5a1fa16950e-a5bee80a'}
(Worker pid=510) (Worker_DP0_TP2_EP2 pid=510) INFO 03-24 16:16:58 [mooncake_layerwise_connector.py:1235] Number of completed KV cache recv requests: 1, receive requests: {'chatcmpl-8c55aca7-251c-4f21-a77c-a5a1fa16950e-a5bee80a'}
(Worker pid=617) (Worker_DP0_TP4_EP4 pid=617) INFO 03-24 16:16:58 [mooncake_layerwise_connector.py:1235] Number of completed KV cache recv requests: 1, receive requests: {'chatcmpl-8c55aca7-251c-4f21-a77c-a5a1fa16950e-a5bee80a'}
(Worker pid=563) (Worker_DP0_TP3_EP3 pid=563) INFO 03-24 16:16:58 [mooncake_layerwise_connector.py:1235] Number of completed KV cache recv requests: 1, receive requests: {'chatcmpl-8c55aca7-251c-4f21-a77c-a5a1fa16950e-a5bee80a'}
(Worker pid=774) (Worker_DP0_TP7_EP7 pid=774) ERROR 03-24 16:17:14 [multiproc_executor.py:880] WorkerProc hit an exception.
(Worker pid=774) (Worker_DP0_TP7_EP7 pid=774) ERROR 03-24 16:17:14 [multiproc_executor.py:880] Traceback (most recent call last):
(Worker pid=774) (Worker_DP0_TP7_EP7 pid=774) ERROR 03-24 16:17:14 [multiproc_executor.py:880]   File "/vllm-workspace/vllm/vllm/v1/executor/multiproc_executor.py", line 875, in worker_busy_loop
(Worker pid=774) (Worker_DP0_TP7_EP7 pid=774) ERROR 03-24 16:17:14 [multiproc_executor.py:880]     output = func(*args, **kwargs)
(Worker pid=774) (Worker_DP0_TP7_EP7 pid=774) ERROR 03-24 16:17:14 [multiproc_executor.py:880]              ^^^^^^^^^^^^^^^^^^^^^
(Worker pid=774) (Worker_DP0_TP7_EP7 pid=774) ERROR 03-24 16:17:14 [multiproc_executor.py:880]   File "/vllm-workspace/vllm/vllm/v1/worker/worker_base.py", line 365, in execute_model
(Worker pid=774) (Worker_DP0_TP7_EP7 pid=774) ERROR 03-24 16:17:14 [multiproc_executor.py:880]     return self.worker.execute_model(scheduler_output)
(Worker pid=774) (Worker_DP0_TP7_EP7 pid=774) ERROR 03-24 16:17:14 [multiproc_executor.py:880]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(Worker pid=774) (Worker_DP0_TP7_EP7 pid=774) ERROR 03-24 16:17:14 [multiproc_executor.py:880]   File "/vllm-workspace/vllm-ascend/vllm_ascend/worker/worker.py", line 406, in execute_model
(Worker pid=774) (Worker_DP0_TP7_EP7 pid=774) ERROR 03-24 16:17:14 [multiproc_executor.py:880]     output = self.model_runner.execute_model(scheduler_output, intermediate_tensors)
(Worker pid=774) (Worker_DP0_TP7_EP7 pid=774) ERROR 03-24 16:17:14 [multiproc_executor.py:880]              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(Worker pid=774) (Worker_DP0_TP7_EP7 pid=774) ERROR 03-24 16:17:14 [multiproc_executor.py:880]   File "/usr/local/python3.11.14/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 120, in decorate_context
(Worker pid=774) (Worker_DP0_TP7_EP7 pid=774) ERROR 03-24 16:17:14 [multiproc_executor.py:880]     return func(*args, **kwargs)
(Worker pid=774) (Worker_DP0_TP7_EP7 pid=774) ERROR 03-24 16:17:14 [multiproc_executor.py:880]            ^^^^^^^^^^^^^^^^^^^^^
(Worker pid=774) (Worker_DP0_TP7_EP7 pid=774) ERROR 03-24 16:17:14 [multiproc_executor.py:880]   File "/vllm-workspace/vllm-ascend/vllm_ascend/worker/model_runner_v1.py", line 1382, in execute_model
(Worker pid=774) (Worker_DP0_TP7_EP7 pid=774) ERROR 03-24 16:17:14 [multiproc_executor.py:880]     hidden_states = self._model_forward(
(Worker pid=774) (Worker_DP0_TP7_EP7 pid=774) ERROR 03-24 16:17:14 [multiproc_executor.py:880]                     ^^^^^^^^^^^^^^^^^^^^
(Worker pid=774) (Worker_DP0_TP7_EP7 pid=774) ERROR 03-24 16:17:14 [multiproc_executor.py:880]   File "/vllm-workspace/vllm-ascend/vllm_ascend/worker/model_runner_v1.py", line 1808, in _model_forward
(Worker pid=774) (Worker_DP0_TP7_EP7 pid=774) ERROR 03-24 16:17:14 [multiproc_executor.py:880]     hidden_states = self.model(
(Worker pid=774) (Worker_DP0_TP7_EP7 pid=774) ERROR 03-24 16:17:14 [multiproc_executor.py:880]                     ^^^^^^^^^^^
(Worker pid=774) (Worker_DP0_TP7_EP7 pid=774) ERROR 03-24 16:17:14 [multiproc_executor.py:880]   File "/usr/local/python3.11.14/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1775, in _wrapped_call_impl
(Worker pid=774) (Worker_DP0_TP7_EP7 pid=774) ERROR 03-24 16:17:14 [multiproc_executor.py:880]     return self._call_impl(*args, **kwargs)
(Worker pid=774) (Worker_DP0_TP7_EP7 pid=774) ERROR 03-24 16:17:14 [multiproc_executor.py:880]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(Worker pid=774) (Worker_DP0_TP7_EP7 pid=774) ERROR 03-24 16:17:14 [multiproc_executor.py:880]   File "/usr/local/python3.11.14/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1786, in _call_impl
(Worker pid=774) (Worker_DP0_TP7_EP7 pid=774) ERROR 03-24 16:17:14 [multiproc_executor.py:880]     return forward_call(*args, **kwargs)
(Worker pid=774) (Worker_DP0_TP7_EP7 pid=774) ERROR 03-24 16:17:14 [multiproc_executor.py:880]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(Worker pid=774) (Worker_DP0_TP7_EP7 pid=774) ERROR 03-24 16:17:14 [multiproc_executor.py:880]   File "/vllm-workspace/vllm/vllm/model_executor/models/qwen3_5.py", line 738, in forward
(Worker pid=774) (Worker_DP0_TP7_EP7 pid=774) ERROR 03-24 16:17:14 [multiproc_executor.py:880]     hidden_states = self.language_model.model(
(Worker pid=774) (Worker_DP0_TP7_EP7 pid=774) ERROR 03-24 16:17:14 [multiproc_executor.py:880]                     ^^^^^^^^^^^^^^^^^^^^^^^^^^
(Worker pid=774) (Worker_DP0_TP7_EP7 pid=774) ERROR 03-24 16:17:14 [multiproc_executor.py:880]   File "/vllm-workspace/vllm/vllm/compilation/decorators.py", line 477, in __call__
(Worker pid=774) (Worker_DP0_TP7_EP7 pid=774) ERROR 03-24 16:17:14 [multiproc_executor.py:880]     return TorchCompileWithNoGuardsWrapper.__call__(self, *args, **kwargs)  # type: ignore[arg-type]
(Worker pid=774) (Worker_DP0_TP7_EP7 pid=774) ERROR 03-24 16:17:14 [multiproc_executor.py:880]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(Worker pid=774) (Worker_DP0_TP7_EP7 pid=774) ERROR 03-24 16:17:14 [multiproc_executor.py:880]   File "/vllm-workspace/vllm/vllm/compilation/wrapper.py", line 225, in __call__
(Worker pid=774) (Worker_DP0_TP7_EP7 pid=774) ERROR 03-24 16:17:14 [multiproc_executor.py:880]     return self._call_with_optional_nvtx_range(
(Worker pid=774) (Worker_DP0_TP7_EP7 pid=774) ERROR 03-24 16:17:14 [multiproc_executor.py:880]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(Worker pid=774) (Worker_DP0_TP7_EP7 pid=774) ERROR 03-24 16:17:14 [multiproc_executor.py:880]   File "/vllm-workspace/vllm/vllm/compilation/wrapper.py", line 119, in _call_with_optional_nvtx_range
(Worker pid=774) (Worker_DP0_TP7_EP7 pid=774) ERROR 03-24 16:17:14 [multiproc_executor.py:880]     return callable_fn(*args, **kwargs)
(Worker pid=774) (Worker_DP0_TP7_EP7 pid=774) ERROR 03-24 16:17:14 [multiproc_executor.py:880]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(Worker pid=774) (Worker_DP0_TP7_EP7 pid=774) ERROR 03-24 16:17:14 [multiproc_executor.py:880]   File "/vllm-workspace/vllm/vllm/model_executor/models/qwen3_next.py", line 1132, in forward
(Worker pid=774) (Worker_DP0_TP7_EP7 pid=774) ERROR 03-24 16:17:14 [multiproc_executor.py:880]     def forward(
(Worker pid=774) (Worker_DP0_TP7_EP7 pid=774) ERROR 03-24 16:17:14 [multiproc_executor.py:880]   File "/usr/local/python3.11.14/lib/python3.11/site-packages/torch/_dynamo/eval_frame.py", line 1044, in _fn
(Worker pid=774) (Worker_DP0_TP7_EP7 pid=774) ERROR 03-24 16:17:14 [multiproc_executor.py:880]     return fn(*args, **kwargs)
(Worker pid=774) (Worker_DP0_TP7_EP7 pid=774) ERROR 03-24 16:17:14 [multiproc_executor.py:880]            ^^^^^^^^^^^^^^^^^^^
(Worker pid=774) (Worker_DP0_TP7_EP7 pid=774) ERROR 03-24 16:17:14 [multiproc_executor.py:880]   File "/vllm-workspace/vllm/vllm/compilation/caching.py", line 198, in __call__
(Worker pid=774) (Worker_DP0_TP7_EP7 pid=774) ERROR 03-24 16:17:14 [multiproc_executor.py:880]     return self.optimized_call(*args, **kwargs)
(Worker pid=774) (Worker_DP0_TP7_EP7 pid=774) ERROR 03-24 16:17:14 [multiproc_executor.py:880]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(Worker pid=774) (Worker_DP0_TP7_EP7 pid=774) ERROR 03-24 16:17:14 [multiproc_executor.py:880]   File "/usr/local/python3.11.14/lib/python3.11/site-packages/torch/fx/graph_module.py", line 837, in call_wrapped
(Worker pid=774) (Worker_DP0_TP7_EP7 pid=774) ERROR 03-24 16:17:14 [multiproc_executor.py:880]     return self._wrapped_call(self, *args, **kwargs)
(Worker pid=774) (Worker_DP0_TP7_EP7 pid=774) ERROR 03-24 16:17:14 [multiproc_executor.py:880]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(Worker pid=774) (Worker_DP0_TP7_EP7 pid=774) ERROR 03-24 16:17:14 [multiproc_executor.py:880]   File "/usr/local/python3.11.14/lib/python3.11/site-packages/torch/fx/graph_module.py", line 413, in __call__
(Worker pid=774) (Worker_DP0_TP7_EP7 pid=774) ERROR 03-24 16:17:14 [multiproc_executor.py:880]     raise e
(Worker pid=774) (Worker_DP0_TP7_EP7 pid=774) ERROR 03-24 16:17:14 [multiproc_executor.py:880]   File "/usr/local/python3.11.14/lib/python3.11/site-packages/torch/fx/graph_module.py", line 400, in __call__
(Worker pid=774) (Worker_DP0_TP7_EP7 pid=774) ERROR 03-24 16:17:14 [multiproc_executor.py:880]     return super(self.cls, obj).__call__(*args, **kwargs)  # type: ignore[misc]
(Worker pid=774) (Worker_DP0_TP7_EP7 pid=774) ERROR 03-24 16:17:14 [multiproc_executor.py:880]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(Worker pid=774) (Worker_DP0_TP7_EP7 pid=774) ERROR 03-24 16:17:14 [multiproc_executor.py:880]   File "/usr/local/python3.11.14/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1775, in _wrapped_call_impl
(Worker pid=774) (Worker_DP0_TP7_EP7 pid=774) ERROR 03-24 16:17:14 [multiproc_executor.py:880]     return self._call_impl(*args, **kwargs)
(Worker pid=774) (Worker_DP0_TP7_EP7 pid=774) ERROR 03-24 16:17:14 [multiproc_executor.py:880]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(Worker pid=774) (Worker_DP0_TP7_EP7 pid=774) ERROR 03-24 16:17:14 [multiproc_executor.py:880]   File "/usr/local/python3.11.14/lib/python3.11/site-packages/torch/nn/modules/module.py", line 1786, in _call_impl
(Worker pid=774) (Worker_DP0_TP7_EP7 pid=774) ERROR 03-24 16:17:14 [multiproc_executor.py:880]     return forward_call(*args, **kwargs)
(Worker pid=774) (Worker_DP0_TP7_EP7 pid=774) ERROR 03-24 16:17:14 [multiproc_executor.py:880]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(Worker pid=774) (Worker_DP0_TP7_EP7 pid=774) ERROR 03-24 16:17:14 [multiproc_executor.py:880]   File "<eval_with_key>.130", line 452, in forward
(Worker pid=774) (Worker_DP0_TP7_EP7 pid=774) ERROR 03-24 16:17:14 [multiproc_executor.py:880]     submod_2 = self.submod_2(getitem_4, s59, getitem_3, l_self_modules_layers_modules_0_modules_linear_attn_modules_norm_parameters_weight_, l_self_modules_layers_modules_0_modules_linear_attn_modules_out_proj_parameters_weight_, getitem_5, l_self_modules_layers_modules_0_modules_post_attention_layernorm_parameters_weight_, l_inputs_embeds_, l_self_modules_layers_modules_0_modules_mlp_modules_gate_parameters_weight_, l_self_modules_layers_modules_1_modules_input_layernorm_parameters_weight_, l_self_modules_layers_modules_1_modules_linear_attn_modules_in_proj_qkvz_parameters_weight_, l_self_modules_layers_modules_1_modules_linear_attn_modules_in_proj_ba_parameters_weight_);  getitem_4 = getitem_3 = l_self_modules_layers_modules_0_modules_linear_attn_modules_norm_parameters_weight_ = l_self_modules_layers_modules_0_modules_linear_attn_modules_out_proj_parameters_weight_ = getitem_5 = l_self_modules_layers_modules_0_modules_post_attention_layernorm_parameters_weight_ = l_inputs_embeds_ = l_self_modules_layers_modules_0_modules_mlp_modules_gate_parameters_weight_ = l_self_modules_layers_modules_1_modules_input_layernorm_parameters_weight_ = l_self_modules_layers_modules_1_modules_linear_attn_modules_in_proj_qkvz_parameters_weight_ = l_self_modules_layers_modules_1_modules_linear_attn_modules_in_proj_ba_parameters_weight_ = None
(Worker pid=774) (Worker_DP0_TP7_EP7 pid=774) ERROR 03-24 16:17:14 [multiproc_executor.py:880]                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(Worker pid=774) (Worker_DP0_TP7_EP7 pid=774) ERROR 03-24 16:17:14 [multiproc_executor.py:880]   File "/vllm-workspace/vllm-ascend/vllm_ascend/compilation/acl_graph.py", line 201, in __call__
(Worker pid=774) (Worker_DP0_TP7_EP7 pid=774) ERROR 03-24 16:17:14 [multiproc_executor.py:880]     torch.npu.current_stream().synchronize()
(Worker pid=774) (Worker_DP0_TP7_EP7 pid=774) ERROR 03-24 16:17:14 [multiproc_executor.py:880]   File "/usr/local/python3.11.14/lib/python3.11/site-packages/torch_npu/npu/streams.py", line 85, in synchronize
(Worker pid=774) (Worker_DP0_TP7_EP7 pid=774) ERROR 03-24 16:17:14 [multiproc_executor.py:880]     super(Stream, self).synchronize()
(Worker pid=774) (Worker_DP0_TP7_EP7 pid=774) ERROR 03-24 16:17:14 [multiproc_executor.py:880] RuntimeError: synchronize:build/CMakeFiles/torch_npu.dir/compiler_depend.ts:361 NPU function error: SUSPECT REMOTE ERROR, error code is 507057
(Worker pid=774) (Worker_DP0_TP7_EP7 pid=774) ERROR 03-24 16:17:14 [multiproc_executor.py:880] [ERROR] 2026-03-24-16:17:14 (PID:774, Device:7, RankID:-1) ERR00100 PTA call acl api failed.
(Worker pid=774) (Worker_DP0_TP7_EP7 pid=774) ERROR 03-24 16:17:14 [multiproc_executor.py:880] EZ9999: Inner Error!
(Worker pid=774) (Worker_DP0_TP7_EP7 pid=774) ERROR 03-24 16:17:14 [multiproc_executor.py:880] EZ9999[PID: 774] 2026-03-24-16:17:14.686.036 (EZ9999):  The error from device(chipId:7, dieId:0), serial number is 11, there is an exception of aivec error, core id is 0, error code = 0x800000, dump info: pc start: 0x124e021fe000, current: 0x124e021fe380, vec error info: 0x1a07377804, mte error info: 0xf8030971df, ifu error info: 0x6554d4e0c0140, ccu error info: 0x5f23e5407c0000df, cube error info: 0, biu error info: 0, aic error mask: 0x6500020bd00028c, para base: 0x12c140403c00.[FUNC:PrintCoreInfo][FILE:device_error_core_proc.cc][LINE:347]
(Worker pid=774) (Worker_DP0_TP7_EP7 pid=774) ERROR 03-24 16:17:14 [multiproc_executor.py:880]         TraceBack (most recent call last):
(Worker pid=774) (Worker_DP0_TP7_EP7 pid=774) ERROR 03-24 16:17:14 [multiproc_executor.py:880]        The extend info: errcode:(0x800000, 0x4000, 0) errorStr: The DDR address of the MTE instruction is out of range.CCU instruction address check error. fixp_error0 info: 0x30971df, fixp_error1 info: 0xf8, fsmId:0, tslot:5, thread:0, ctxid:0, blk:14, sublk:0, subErrType:4.[FUNC:PrintCoreInfo][FILE:device_error_core_proc.cc][LINE:360]
(Worker pid=774) (Worker_DP0_TP7_EP7 pid=774) ERROR 03-24 16:17:14 [multiproc_executor.py:880]        The error from device(chipId:7, dieId:0), serial number is 11, there is an exception of aivec error, core id is 2, error code = 0x800000, dump info: pc start: 0x124e021fe000, current: 0x124e021fe39c, vec error info: 0xe907fd6386, mte error info: 0xf8030971df, ifu error info: 0x365487f408200, ccu error info: 0xfb8950b47c0000df, cube error info: 0, biu error info: 0, aic error mask: 0x6500020bd00028c, para base: 0x12c140403c00.[FUNC:PrintCoreInfo][FILE:device_error_core_proc.cc][LINE:347]
(Worker pid=774) (Worker_DP0_TP7_EP7 pid=774) ERROR 03-24 16:17:14 [multiproc_executor.py:880]        The extend info: errcode:(0x800000, 0x4000, 0) errorStr: The DDR address of the MTE instruction is out of range.CCU instruction address check error. fixp_error0 info: 0x30971df, fixp_error1 info: 0xf8, fsmId:0, tslot:5, thread:0, ctxid:0, blk:16, sublk:0, subErrType:4.[FUNC:PrintCoreInfo][FILE:device_error_core_proc.cc][LINE:360]
(Worker pid=774) (Worker_DP0_TP7_EP7 pid=774) ERROR 03-24 16:17:14 [multiproc_executor.py:880]        The error from device(chipId:7, dieId:0), serial number is 11, there is an exception of aivec error, core id is 3, error code = 0x800000, dump info: pc start: 0x124e021fe000, current: 0x124e021fe380, vec error info: 0x2011903b81, mte error info: 0xf8030971df, ifu error info: 0x1f4179f088000, ccu error info: 0x122182f07c0000df, cube error info: 0, biu error info: 0, aic error mask: 0x6500020bd00028c, para base: 0x12c140403c00.[FUNC:PrintCoreInfo][FILE:device_error_core_proc.cc][LINE:347]
(Worker pid=774) (Worker_DP0_TP7_EP7 pid=774) ERROR 03-24 16:17:14 [multiproc_executor.py:880]        The extend info: errcode:(0x800000, 0x4000, 0) errorStr: The DDR address of the MTE instruction is out of range.CCU instruction address check error. fixp_error0 info: 0x30971df, fixp_error1 info: 0xf8, fsmId:0, tslot:5, thread:0, ctxid:0, blk:17, sublk:0, subErrType:4.[FUNC:PrintCoreInfo][FILE:device_error_core_proc.cc][LINE:360]
(Worker pid=774) (Worker_DP0_TP7_EP7 pid=774) ERROR 03-24 16:17:14 [multiproc_executor.py:880]        The error from device(chipId:7, dieId:0), serial number is 11, there is an exception of aivec error, core id is 4, error code = 0x800000, dump info: pc start: 0x124e021fe000, current: 0x124e021fe380, vec error info: 0x6914277205, mte error info: 0xf8030971df, ifu error info: 0x253e78e046cc0, ccu error info: 0x812438797c0000df, cube error info: 0, biu error info: 0, aic error mask: 0x6500020bd00028c, para base: 0x12c140403c00.[FUNC:PrintCoreInfo][FILE:device_error_core_proc.cc][LINE:347]
(Worker pid=774) (Worker_DP0_TP7_EP7 pid=774) ERROR 03-24 16:17:14 [multiproc_executor.py:880]        The extend info: errcode:(0x800000, 0x4000, 0) errorStr: The DDR address of the MTE instruction is out of range.CCU instruction address check error. fixp_error0 info: 0x30971df, fixp_error1 info: 0xf8, fsmId:0, tslot:5, thread:0, ctxid:0, blk:18, sublk:0, subErrType:4.[FUNC:PrintCoreInfo][FILE:device_error_core_proc.cc][LINE:360]
(Worker pid=774) (Worker_DP0_TP7_EP7 pid=774) ERROR 03-24 16:17:14 [multiproc_executor.py:880]        The error from device(chipId:7, dieId:0), serial number is 11, there is an exception of aivec error, core id is 5, error code = 0x800000, dump info: pc start: 0x124e021fe000, current: 0x124e021fe39c, vec error info: 0x7911f62e38, mte error info: 0xf8030971df, ifu error info: 0x57c861c740300, ccu error info: 0xfcd531947c0000df, cube error info: 0, biu error info: 0, aic error mask: 0x6500020bd00028c, para base: 0x12c140403c00.[FUNC:PrintCoreInfo][FILE:device_error_core_proc.cc][LINE:347]
(Worker pid=774) (Worker_DP0_TP7_EP7 pid=774) ERROR 03-24 16:17:14 [multiproc_executor.py:880]        The extend info: errcode:(0x800000, 0x4000, 0) errorStr: The DDR address of the MTE instruction is out of range.CCU instruction address check error. fixp_error0 info: 0x30971df, fixp_error1 info: 0xf8, fsmId:0, tslot:5, thread:0, ctxid:0, blk:19, sublk:0, subErrType:4.[FUNC:PrintCoreInfo][FILE:device_error_core_proc.cc][LINE:360]
(Worker pid=774) (Worker_DP0_TP7_EP7 pid=774) ERROR 03-24 16:17:14 [multiproc_executor.py:880]        The error from device(chipId:7, dieId:0), serial number is 11, there is an exception of aivec error, core id is 7, error code = 0x800000, dump info: pc start: 0x124e021fe000, current: 0x124e021fe380, vec error info: 0x5308c6ef08, mte error info: 0xf8030971df, ifu error info: 0x7ed1001bf4500, ccu error info: 0x78cb9e067c0000df, cube error info: 0, biu error info: 0, aic error mask: 0x6500020bd00028c, para base: 0x12c140403c00.[FUNC:PrintCoreInfo][FILE:device_error_core_proc.cc][LINE:347]
(Worker pid=774) (Worker_DP0_TP7_EP7 pid=774) ERROR 03-24 16:17:14 [multiproc_executor.py:880]        The extend info: errcode:(0x800000, 0x4000, 0) errorStr: The DDR address of the MTE instruction is out of range.CCU instruction address check error. fixp_error0 info: 0x30971df, fixp_error1 info: 0xf8, fsmId:0, tslot:5, thread:0, ctxid:0, blk:21, sublk:0, subErrType:4.[FUNC:PrintCoreInfo][FILE:device_error_core_proc.cc][LINE:360]
(Worker pid=774) (Worker_DP0_TP7_EP7 pid=774) ERROR 03-24 16:17:14 [multiproc_executor.py:880]        The error from device(chipId:7, dieId:0), serial number is 11, there is an exception of aivec error, core id is 8, error code = 0x800000, dump info: pc start: 0x124e021fe000, current: 0x124e021fe380, vec error info: 0x7913374e28, mte error info: 0xf8030971df, ifu error info: 0x67fc8e7120500, ccu error info: 0x668171617c0000df, cube error info: 0, biu error info: 0, aic error mask: 0x6500020bd00028c, para base: 0x12c140403c00.[FUNC:PrintCoreInfo][FILE:device_error_core_proc.cc][LINE:347]
(Worker pid=774) (Worker_DP0_TP7_EP7 pid=774) ERROR 03-24 16:17:14 [multiproc_executor.py:880]        The extend info: errcode:(0x800000, 0x4000, 0) errorStr: The DDR address of the MTE instruction is out of range.CCU instruction address check error. fixp_error0 info: 0x30971df, fixp_error1 info: 0xf8, fsmId:0, tslot:5, thread:0, ctxid:0, blk:22, sublk:0, subErrType:4.[FUNC:PrintCoreInfo][FILE:device_error_core_proc.cc][LINE:360]
(Worker pid=774) (Worker_DP0_TP7_EP7 pid=774) ERROR 03-24 16:17:14 [multiproc_executor.py:880]        The error from device(chipId:7, dieId:0), serial number is 11, there is an exception of aivec error, core id is 10, error code = 0x800000, dump info: pc start: 0x124e021fe000, current: 0x124e021fe380, vec error info: 0x3714d96325, mte error info: 0xf8030971df, ifu error info: 0x718f11f4c02c0, ccu error info: 0x143093897c0000df, cube error info: 0, biu error info: 0, aic error mask: 0x6500020bd00028c, para base: 0x12c140403c00.[FUNC:PrintCoreInfo][FILE:device_error_core_proc.cc][LINE:347]
(Worker pid=774) (Worker_DP0_TP7_EP7 pid=774) ERROR 03-24 16:17:14 [multiproc_executor.py:880]        The extend info: errcode:(0x800000, 0x4000, 0) errorStr: The DDR address of the MTE instruction is out of range.CCU instruction address check error. fixp_error0 info: 0x30971df, fixp_error1 info: 0xf8, fsmId:0, tslot:5, thread:0, ctxid:0, blk:24, sublk:0, subErrType:4.[FUNC:PrintCoreInfo][FILE:device_error_core_proc.cc][LINE:360]
(Worker pid=774) (Worker_DP0_TP7_EP7 pid=774) ERROR 03-24 16:17:14 [multiproc_executor.py:880]        The error from device(chipId:7, dieId:0), serial number is 11, there is an exception of aivec error, core id is 12, error code = 0x800000, dump info: pc start: 0x124e021fe000, current: 0x124e021fe380, vec error info: 0x6e01402cfe, mte error info: 0xf8030971df, ifu error info: 0x71edfd384080, ccu error info: 0x7ff8ac387c0000df, cube error info: 0, biu error info: 0, aic error mask: 0x6500020bd00028c, para base: 0x12c140403c00.[FUNC:PrintCoreInfo][FILE:device_error_core_proc.cc][LINE:347]
(Worker pid=774) (Worker_DP0_TP7_EP7 pid=774) ERROR 03-24 16:17:14 [multiproc_executor.py:880]        The extend info: errcode:(0x800000, 0x4000, 0) errorStr: The DDR address of the MTE instruction is out of range.CCU instruction address check error. fixp_error0 info: 0x30971df, fixp_error1 info: 0xf8, fsmId:0, tslot:5, thread:0, ctxid:0, blk:26, sublk:0, subErrType:4.[FUNC:PrintCoreInfo][FILE:device_error_core_proc.cc][LINE:360]
(Worker pid=774) (Worker_DP0_TP7_EP7 pid=774) ERROR 03-24 16:17:14 [multiproc_executor.py:880]        The error from device(chipId:7, dieId:0), serial number is 11, there is an exception of aivec error, core id is 14, error code = 0x800000, dump info: pc start: 0x124e021fe000, current: 0x124e021fe39c, vec error info: 0x31416efbc, mte error info: 0xf8030971df, ifu error info: 0x25ac90e145e40, ccu error info: 0xd39811517c0000df, cube error info: 0, biu error info: 0, aic error mask: 0x6500020bd00028c, para base: 0x12c140403c00.[FUNC:PrintCoreInfo][FILE:device_error_core_proc.cc][LINE:347]
(Worker pid=774) (Worker_DP0_TP7_EP7 pid=774) ERROR 03-24 16:17:14 [multiproc_executor.py:880]        The extend info: errcode:(0x800000, 0x4000, 0) errorStr: The DDR address of the MTE instruction is out of range.CCU instruction address check error. fixp_error0 info: 0x30971df, fixp_error1 info: 0xf8, fsmId:0, tslot:5, thread:0, ctxid:0, blk:28, sublk:0, subErrType:4.[FUNC:PrintCoreInfo][FILE:device_error_core_proc.cc][LINE:360]
(Worker pid=774) (Worker_DP0_TP7_EP7 pid=774) ERROR 03-24 16:17:14 [multiproc_executor.py:880]        The error from device(chipId:7, dieId:0), serial number is 11, there is an exception of aivec error, core id is 19, error code = 0x800000, dump info: pc start: 0x124e021fe000, current: 0x124e021fe39c, vec error info: 0x71133d33a4, mte error info: 0xf8030971df, ifu error info: 0x35f9a7fe34300, ccu error info: 0x150067897c0000df, cube error info: 0, biu error info: 0, aic error mask: 0x6500020bd00028c, para base: 0x12c140403c00.[FUNC:PrintCoreInfo][FILE:device_error_core_proc.cc][LINE:347]
(Worker pid=774) (Worker_DP0_TP7_EP7 pid=774) ERROR 03-24 16:17:14 [multiproc_executor.py:880]        The extend info: errcode:(0x800000, 0x4000, 0) errorStr: The DDR address of the MTE instruction is out of range.CCU instruction address check error. fixp_error0 info: 0x30971df, fixp_error1 info: 0xf8, fsmId:0, tslot:5, thread:0, ctxid:0, blk:31, sublk:0, subErrType:4.[FUNC:PrintCoreInfo][FILE:device_error_core_proc.cc][LINE:360]
(Worker pid=774) (Worker_DP0_TP7_EP7 pid=774) ERROR 03-24 16:17:14 [multiproc_executor.py:880]        The error from device(chipId:7, dieId:0), serial number is 11, there is an exception of aivec error, core id is 36, error code = 0x800000, dump info: pc start: 0x124e021fe000, current: 0x124e021fe380, vec error info: 0x321cf32ffb, mte error info: 0xf8030971df, ifu error info: 0x453a7ef40bc00, ccu error info: 0xb716f1297c0000df, cube error info: 0, biu error info: 0, aic error mask: 0x6500020bd00028c, para base: 0x12c140403c00.[FUNC:PrintCoreInfo][FILE:device_error_core_proc.cc][LINE:347]
(Worker pid=774) (Worker_DP0_TP7_EP7 pid=774) ERROR 03-24 16:17:14 [multiproc_executor.py:880]        The extend info: errcode:(0x800000, 0x4000, 0) errorStr: The DDR address of the MTE instruction is out of range.CCU instruction address check error. fixp_error0 info: 0x30971df, fixp_error1 info: 0xf8, fsmId:0, tslot:5, thread:0, ctxid:0, blk:0, sublk:0, subErrType:4.[FUNC:PrintCoreInfo][FILE:device_error_core_proc.cc][LINE:360]
(Worker pid=774) (Worker_DP0_TP7_EP7 pid=774) ERROR 03-24 16:17:14 [multiproc_executor.py:880]        The error from device(chipId:7, dieId:0), serial number is 11, there is an exception of aivec error, core id is 37, error code = 0x800000, dump info: pc start: 0x124e021fe000, current: 0x124e021fe39c, vec error info: 0xe21ffe7d2c, mte error info: 0xf8030971df, ifu error info: 0x3ebf2571c4e00, ccu error info: 0xb969f0307c0000df, cube error info: 0, biu error info: 0, aic error mask: 0x6500020bd00028c, para base: 0x12c140403c00.[FUNC:PrintCoreInfo][FILE:device_error_core_proc.cc][LINE:347]
(Worker pid=774) (Worker_DP0_TP7_EP7 pid=774) ERROR 03-24 16:17:14 [multiproc_executor.py:880]        The extend info: errcode:(0x800000, 0x4000, 0) errorStr: The DDR address of the MTE instruction is out of range.CCU instruction address check error. fixp_error0 info: 0x30971df, fixp_error1 info: 0xf8, fsmId:0, tslot:5, thread:0, ctxid:0, blk:1, sublk:0, subErrType:4.[FUNC:PrintCoreInfo][FILE:device_error_core_proc.cc][LINE:360]
(Worker pid=774) (Worker_DP0_TP7_EP7 pid=774) ERROR 03-24 16:17:14 [multiproc_executor.py:880]        The error from device(chipId:7, dieId:0), serial number is 11, there is an exception of aivec error, core id is 38, error code = 0x800000, dump info: pc start: 0x124e021fe000, current: 0x124e021fe39c, vec error info: 0x7912242104, mte error info: 0xf8030971df, ifu error info: 0x7796c9506cc80, ccu error info: 0x1b9830c17c0000df, cube error info: 0, biu error info: 0, aic error mask: 0x6500020bd00028c, para base: 0x12c140403c00.[FUNC:PrintCoreInfo][FILE:device_error_core_proc.cc][LINE:347]
(Worker pid=774) (Worker_DP0_TP7_EP7 pid=774) ERROR 03-24 16:17:14 [multiproc_executor.py:880]        The extend info: errcode:(0x800000, 0x4000, 0) errorStr: The DDR address of the MTE instruction is out of range.CCU instruction address check error. fixp_error0 info: 0x30971df, fixp_error1 info: 0xf8, fsmId:0, tslot:5, thread:0, ctxid:0, blk:2, sublk:0, subErrType:4.[FUNC:PrintCoreInfo][FILE:device_error_core_proc.cc][LINE:360]
(Worker pid=774) (Worker_DP0_TP7_EP7 pid=774) ERROR 03-24 16:17:14 [multiproc_executor.py:880]        The error from device(chipId:7, dieId:0), serial number is 11, there is an exception of aivec error, core id is 40, error code = 0x800000, dump info: pc start: 0x124e021fe000, current: 0x124e021fe380, vec error info: 0xc319f267ad, mte error info: 0xf8030971df, ifu error info: 0x25211fa3e04c0, ccu error info: 0x7f11aa3a7c0000df, cube error info: 0, biu error info: 0, aic error mask: 0x6500020bd00028c, para base: 0x12c140403c00.[FUNC:PrintCoreInfo][FILE:device_error_core_proc.cc][LINE:347]
(Worker pid=774) (Worker_DP0_TP7_EP7 pid=774) ERROR 03-24 16:17:14 [multiproc_executor.py:880]        The extend info: errcode:(0x800000, 0x4000, 0) errorStr: The DDR address of the MTE instruction is out of range.CCU instruction address check error. fixp_error0 info: 0x30971df, fixp_error1 info: 0xf8, fsmId:0, tslot:5, thread:0, ctxid:0, blk:4, sublk:0, subErrType:4.[FUNC:PrintCoreInfo][FILE:device_error_core_proc.cc][LINE:360]
(Worker pid=774) (Worker_DP0_TP7_EP7 pid=774) ERROR 03-24 16:17:14 [multiproc_executor.py:880]        The error from device(chipId:7, dieId:0), serial number is 11, there is an exception of aivec error, core id is 41, error code = 0x800000, dump info: pc start: 0x124e021fe000, current: 0x124e021fe380, vec error info: 0x910ac29621, mte error info: 0xf8030971df, ifu error info: 0xffe85ec0f240, ccu error info: 0xdb8e5c237c0000df, cube error info: 0, biu error info: 0, aic error mask: 0x6500020bd00028c, para base: 0x12c140403c00.[FUNC:PrintCoreInfo][FILE:device_error_core_proc.cc][LINE:347]
(Worker pid=774) (Worker_DP0_TP7_EP7 pid=774) ERROR 03-24 16:17:14 [multiproc_executor.py:880]        The extend info: errcode:(0x800000, 0x4000, 0) errorStr: The DDR address of the MTE instruction is out of range.CCU instruction address check error. fixp_error0 info: 0x30971df, fixp_error1 info: 0xf8, fsmId:0, tslot:5, thread:0, ctxid:0, blk:5, sublk:0, subErrType:4.[FUNC:PrintCoreInfo][FILE:device_error_core_proc.cc][LINE:360]
(Worker pid=774) (Worker_DP0_TP7_EP7 pid=774) ERROR 03-24 16:17:14 [multiproc_executor.py:880]        The error from device(chipId:7, dieId:0), serial number is 11, there is an exception of aivec error, core id is 42, error code = 0x800000, dump info: pc start: 0x124e021fe000, current: 0x124e021fe380, vec error info: 0x411706aa00, mte error info: 0xf8030971df, ifu error info: 0x1eae671a7c00, ccu error info: 0x343931617c0000df, cube error info: 0, biu error info: 0, aic error mask: 0x6500020bd00028c, para base: 0x12c140403c00.[FUNC:PrintCoreInfo][FILE:device_error_core_proc.cc][LINE:347]
(Worker pid=774) (Worker_DP0_TP7_EP7 pid=774) ERROR 03-24 16:17:14 [multiproc_executor.py:880]        The extend info: errcode:(0x800000, 0x4000, 0) errorStr: The DDR address of the MTE instruction is out of range.CCU instruction address check error. fixp_error0 info: 0x30971df, fixp_error1 info: 0xf8, fsmId:0, tslot:5, thread:0, ctxid:0, blk:6, sublk:0, subErrType:4.[FUNC:PrintCoreInfo][FILE:device_error_core_proc.cc][LINE:360]
(Worker pid=774) (Worker_DP0_TP7_EP7 pid=774) ERROR 03-24 16:17:14 [multiproc_executor.py:880]        The error from device(chipId:7, dieId:0), serial number is 11, there is an exception of aivec error, core id is 44, error code = 0x800000, dump info: pc start: 0x124e021fe000, current: 0x124e021fe380, vec error info: 0x3b05b9ff54, mte error info: 0xf8030971df, ifu error info: 0x70fd1f63850c0, ccu error info: 0x338061167c0000df, cube error info: 0, biu error info: 0, aic error mask: 0x6500020bd00028c, para base: 0x12c140403c00.[FUNC:PrintCoreInfo][FILE:device_error_core_proc.cc][LINE:347]
(Worker pid=774) (Worker_DP0_TP7_EP7 pid=774) ERROR 03-24 16:17:14 [multiproc_executor.py:880]        The extend info: errcode:(0x800000, 0x4000, 0) errorStr: The DDR address of the MTE instruction is out of range.CCU instruction address check error. fixp_error0 info: 0x30971df, fixp_error1 info: 0xf8, fsmId:0, tslot:5, thread:0, ctxid:0, blk:8, sublk:0, subErrType:4.[FUNC:PrintCoreInfo][FILE:device_error_core_proc.cc][LINE:360]
(Worker pid=774) (Worker_DP0_TP7_EP7 pid=774) ERROR 03-24 16:17:14 [multiproc_executor.py:880]        The error from device(chipId:7, dieId:0), serial number is 11, there is an exception of aivec error, core id is 46, error code = 0x800000, dump info: pc start: 0x124e021fe000, current: 0x124e021fe380, vec error info: 0xf113bd0f25, mte error info: 0xf8030971df, ifu error info: 0x611b6f2e24600, ccu error info: 0x1527f1be7c0000df, cube error info: 0, biu error info: 0, aic error mask: 0x6500020bd00028c, para base: 0x12c140403c00.[FUNC:PrintCoreInfo][FILE:device_error_core_proc.cc][LINE:347]
(Worker pid=774) (Worker_DP0_TP7_EP7 pid=774) ERROR 03-24 16:17:14 [multiproc_executor.py:880]        The extend info: errcode:(0x800000, 0x4000, 0) errorStr: The DDR address of the MTE instruction is out of range.CCU instruction address check error. fixp_error0 info: 0x30971df, fixp_error1 info: 0xf8, fsmId:0, tslot:5, thread:0, ctxid:0, blk:10, sublk:0, subErrType:4.[FUNC:PrintCoreInfo][FILE:device_error_core_proc.cc][LINE:360]
(Worker pid=774) (Worker_DP0_TP7_EP7 pid=774) ERROR 03-24 16:17:14 [multiproc_executor.py:880]        The error from device(chipId:7, dieId:0), serial number is 11, there is an exception of aivec error, core id is 1, error code = 0x800000, dump info: pc start: 0x124e021fe000, current: 0x124e021fe39c, vec error info: 0x890f7526ec, mte error info: 0xf8030971df, ifu error info: 0x7bd01e9d80500, ccu error info: 0x32abfae97c0000df, cube error info: 0, biu error info: 0, aic error mask: 0x6500020bd00028c, para base: 0x12c140403c00.[FUNC:PrintCoreInfo][FILE:device_error_core_proc.cc][LINE:347]
(Worker pid=774) (Worker_DP0_TP7_EP7 pid=774) ERROR 03-24 16:17:14 [multiproc_executor.py:880]        The extend info: errcode:(0x800000, 0x4000, 0) errorStr: The DDR address of the MTE instruction is out of range.CCU instruction address check error. fixp_error0 info: 0x30971df, fixp_error1 info: 0xf8, fsmId:1, tslot:5, thread:0, ctxid:0, blk:15, sublk:0, subErrType:4.[FUNC:PrintCoreInfo][FILE:device_error_core_proc.cc][LINE:360]
(Worker pid=774) (Worker_DP0_TP7_EP7 pid=774) ERROR 03-24 16:17:14 [multiproc_executor.py:880]        The error from device(chipId:7, dieId:0), serial number is 11, there is an exception of aivec error, core id is 6, error code = 0x800000, dump info: pc start: 0x124e021fe000, current: 0x124e021fe380, vec error info: 0xc3149618ba, mte error info: 0xf8030971df, ifu error info: 0x6178049a40b40, ccu error info: 0xffe870037c0000df, cube error info: 0, biu error info: 0, aic error mask: 0x6500020bd00028c, para base: 0x12c140403c00.[FUNC:PrintCoreInfo][FILE:device_error_core_proc.cc][LINE:347]
(Worker pid=774) (Worker_DP0_TP7_EP7 pid=774) ERROR 03-24 16:17:14 [multiproc_executor.py:880]        The extend info: errcode:(0x800000, 0x4000, 0) errorStr: The DDR address of the MTE instruction is out of range.CCU instruction address check error. fixp_error0 info: 0x30971df, fixp_error1 info: 0xf8, fsmId:1, tslot:5, thread:0, ctxid:0, blk:20, sublk:0, subErrType:4.[FUNC:PrintCoreInfo][FILE:device_error_core_proc.cc][LINE:360]
(Worker pid=774) (Worker_DP0_TP7_EP7 pid=774) ERROR 03-24 16:17:14 [multiproc_executor.py:880]        The error from device(chipId:7, dieId:0), serial number is 11, there is an exception of aivec error, core id is 9, error code = 0x800000, dump info: pc start: 0x124e021fe000, current: 0x124e021fe380, vec error info: 0x6a17152a2c, mte error info: 0xf8030971df, ifu error info: 0x4dd84eefaf900, ccu error info: 0xd30ed8b07c0000df, cube error info: 0, biu error info: 0, aic error mask: 0x6500020bd00028c, para base: 0x12c140403c00.[FUNC:PrintCoreInfo][FILE:device_error_core_proc.cc][LINE:347]
(Worker pid=774) (Worker_DP0_TP7_EP7 pid=774) ERROR 03-24 16:17:14 [multiproc_executor.py:880]        The extend info: errcode:(0x800000, 0x4000, 0) errorStr: The DDR address of the MTE instruction is out of range.CCU instruction address check error. fixp_error0 info: 0x30971df, fixp_error1 info: 0xf8, fsmId:1, tslot:5, thread:0, ctxid:0, blk:23, sublk:0, subErrType:4.[FUNC:PrintCoreInfo][FILE:device_error_core_proc.cc][LINE:360]
(Worker pid=774) (Worker_DP0_TP7_EP7 pid=774) ERROR 03-24 16:17:14 [multiproc_executor.py:880]        The error from device(chipId:7, dieId:0), serial number is 11, there is an exception of aivec error, core id is 11, error code = 0x800000, dump info: pc start: 0x124e021fe000, current: 0x124e021fe39c, vec error info: 0x4b10a4eabd, mte error info: 0xf8030971df, ifu error info: 0x17f1a7620f840, ccu error info: 0x138b69177c0000df, cube error info: 0, biu error info: 0, aic error mask: 0x6500020bd00028c, para base: 0x12c140403c00.[FUNC:PrintCoreInfo][FILE:device_error_core_proc.cc][LINE:347]
(Worker pid=774) (Worker_DP0_TP7_EP7 pid=774) ERROR 03-24 16:17:14 [multiproc_executor.py:880]        The extend info: errcode:(0x800000, 0x4000, 0) errorStr: The DDR address of the MTE instruction is out of range.CCU instruction address check error. fixp_error0 info: 0x30971df, fixp_error1 info: 0xf8, fsmId:1, tslot:5, thread:0, ctxid:0, blk:25, sublk:0, subErrType:4.[FUNC:PrintCoreInfo][FILE:device_error_core_proc.cc][LINE:360]
(Worker pid=774) (Worker_DP0_TP7_EP7 pid=774) ERROR 03-24 16:17:14 [multiproc_executor.py:880]        The error from device(chipId:7, dieId:0), serial number is 11, there is an exception of aivec error, core id is 13, error code = 0x800000, dump info: pc start: 0x124e021fe000, current: 0x124e021fe380, vec error info: 0x6b153f01dc, mte error info: 0xf8030971df, ifu error info: 0x55dac3fd57d80, ccu error info: 0xf55988127c0000df, cube error info: 0, biu error info: 0, aic error mask: 0x6500020bd00028c, para base: 0x12c140403c00.[FUNC:PrintCoreInfo][FILE:device_error_core_proc.cc][LINE:347]
(Worker pid=774) (Worker_DP0_TP7_EP7 pid=774) ERROR 03-24 16:17:14 [multiproc_executor.py:880]        The extend info: errcode:(0x800000, 0x4000, 0) errorStr: The DDR address of the MTE instruction is out of range.CCU instruction address check error. fixp_error0 info: 0x30971df, fixp_error1 info: 0xf8, fsmId:1, tslot:5, thread:0, ctxid:0, blk:27, sublk:0, subErrType:4.[FUNC:PrintCoreInfo][FILE:device_error_core_proc.cc][LINE:360]
(Worker pid=774) (Worker_DP0_TP7_EP7 pid=774) ERROR 03-24 16:17:14 [multiproc_executor.py:880]        The error from device(chipId:7, dieId:0), serial number is 11, there is an exception of aivec error, core id is 15, error code = 0x800000, dump info: pc start: 0x124e021fe000, current: 0x124e021fe380, vec error info: 0x7215d50f84, mte error info: 0xf8030971df, ifu error info: 0xd13f1e6a4d40, ccu error info: 0xaa14da427c0000df, cube error info: 0, biu error info: 0, aic error mask: 0x6500020bd00028c, para base: 0x12c140403c00.[FUNC:PrintCoreInfo][FILE:device_error_core_proc.cc][LINE:347]
(Worker pid=774) (Worker_DP0_TP7_EP7 pid=774) ERROR 03-24 16:17:14 [multiproc_executor.py:880]        The extend info: errcode:(0x800000, 0x4000, 0) errorStr: The DDR address of the MTE instruction is out of range.CCU instruction address check error. fixp_error0 info: 0x30971df, fixp_error1 info: 0xf8, fsmId:1, tslot:5, thread:0, ctxid:0, blk:29, sublk:0, subErrType:4.[FUNC:PrintCoreInfo][FILE:device_error_core_proc.cc][LINE:360]
(Worker pid=774) (Worker_DP0_TP7_EP7 pid=774) ERROR 03-24 16:17:14 [multiproc_executor.py:880]        The error from device(chipId:7, dieId:0), serial number is 11, there is an exception of aivec error, core id is 18, error code = 0x800000, dump info: pc start: 0x124e021fe000, current: 0x124e021fe380, vec error info: 0x4411bdf918, mte error info: 0xf8030971df, ifu error info: 0x679735f207800, ccu error info: 0xff7727b07c0000df, cube error info: 0, biu error info: 0, aic error mask: 0x6500020bd00028c, para base: 0x12c140403c00.[FUNC:PrintCoreInfo][FILE:device_error_core_proc.cc][LINE:347]
(Worker pid=774) (Worker_DP0_TP7_EP7 pid=774) ERROR 03-24 16:17:14 [multiproc_executor.py:880]        The extend info: errcode:(0x800000, 0x4000, 0) errorStr: The DDR address of the MTE instruction is out of range.CCU instruction address check error. fixp_error0 info: 0x30971df, fixp_error1 info: 0xf8, fsmId:1, tslot:5, thread:0, ctxid:0, blk:30, sublk:0, subErrType:4.[FUNC:PrintCoreInfo][FILE:device_error_core_proc.cc][LINE:360]
(Worker pid=774) (Worker_DP0_TP7_EP7 pid=774) ERROR 03-24 16:17:14 [multiproc_executor.py:880]        The error from device(chipId:7, dieId:0), serial number is 11, there is an exception of aivec error, core id is 39, error code = 0x800000, dump info: pc start: 0x124e021fe000, current: 0x124e021fe380, vec error info: 0x8f1d9e2a01, mte error info: 0xf8030971df, ifu error info: 0x4b63e0fcce380, ccu error info: 0xbe48877a7c0000df, cube error info: 0, biu error info: 0, aic error mask: 0x6500020bd00028c, para base: 0x12c140403c00.[FUNC:PrintCoreInfo][FILE:device_error_core_proc.cc][LINE:347]
(Worker pid=774) (Worker_DP0_TP7_EP7 pid=774) ERROR 03-24 16:17:14 [multiproc_executor.py:880]        The extend info: errcode:(0x800000, 0x4000, 0) errorStr: The DDR address of the MTE instruction is out of range.CCU instruction address check error. fixp_error0 info: 0x30971df, fixp_error1 info: 0xf8, fsmId:1, tslot:5, thread:0, ctxid:0, blk:3, sublk:0, subErrType:4.[FUNC:PrintCoreInfo][FILE:device_error_core_proc.cc][LINE:360]
(Worker pid=774) (Worker_DP0_TP7_EP7 pid=774) ERROR 03-24 16:17:14 [multiproc_executor.py:880]        The error from device(chipId:7, dieId:0), serial number is 11, there is an exception of aivec error, core id is 43, error code = 0x800000, dump info: pc start: 0x124e021fe000, current: 0x124e021fe380, vec error info: 0x70123cd800, mte error info: 0xf8030971df, ifu error info: 0x6e18cfd45a00, ccu error info: 0x2904e1977c0000df, cube error info: 0, biu error info: 0, aic error mask: 0x6500020bd00028c, para base: 0x12c140403c00.[FUNC:PrintCoreInfo][FILE:device_error_core_proc.cc][LINE:347]
(Worker pid=774) (Worker_DP0_TP7_EP7 pid=774) ERROR 03-24 16:17:14 [multiproc_executor.py:880]        The extend info: errcode:(0x800000, 0x4000, 0) errorStr: The DDR address of the MTE instruction is out of range.CCU instruction address check error. fixp_error0 info: 0x30971df, fixp_error1 info: 0xf8, fsmId:1, tslot:5, thread:0, ctxid:0, blk:7, sublk:0, subErrType:4.[FUNC:PrintCoreInfo][FILE:device_error_core_proc.cc][LINE:360]
(Worker pid=774) (Worker_DP0_TP7_EP7 pid=774) ERROR 03-24 16:17:14 [multiproc_executor.py:880]        The error from device(chipId:7, dieId:0), serial number is 11, there is an exception of aivec error, core id is 45, error code = 0x800000, dump info: pc start: 0x124e021fe000, current: 0x124e021fe39c, vec error info: 0x7106f95245, mte error info: 0xf8030971df, ifu error info: 0x25c48df3d4980, ccu error info: 0x86d0e8717c0000df, cube error info: 0, biu error info: 0, aic error mask: 0x6500020bd00028c, para base: 0x12c140403c00.[FUNC:PrintCoreInfo][FILE:device_error_core_proc.cc][LINE:347]
(Worker pid=774) (Worker_DP0_TP7_EP7 pid=774) ERROR 03-24 16:17:14 [multiproc_executor.py:880]        The extend info: errcode:(0x800000, 0x4000, 0) errorStr: The DDR address of the MTE instruction is out of range.CCU instruction address check error. fixp_error0 info: 0x30971df, fixp_error1 info: 0xf8, fsmId:1, tslot:5, thread:0, ctxid:0, blk:9, sublk:0, subErrType:4.[FUNC:PrintCoreInfo][FILE:device_error_core_proc.cc][LINE:360]
(Worker pid=774) (Worker_DP0_TP7_EP7 pid=774) ERROR 03-24 16:17:14 [multiproc_executor.py:880]        The error from device(chipId:7, dieId:0), serial number is 11, there is an exception of aivec error, core id is 47, error code = 0x800000, dump info: pc start: 0x124e021fe000, current: 0x124e021fe39c, vec error info: 0xc310cc8109, mte error info: 0xf8030971df, ifu error info: 0x1f77ef7bfc140, ccu error info: 0xaf6330bd7c0000df, cube error info: 0, biu error info: 0, aic error mask: 0x6500020bd00028c, para base: 0x12c140403c00.[FUNC:PrintCoreInfo][FILE:device_error_core_proc.cc][LINE:347]
(Worker pid=774) (Worker_DP0_TP7_EP7 pid=774) ERROR 03-24 16:17:14 [multiproc_executor.py:880]        The extend info: errcode:(0x800000, 0x4000, 0) errorStr: The DDR address of the MTE instruction is out of range.CCU instruction address check error. fixp_error0 info: 0x30971df, fixp_error1 info: 0xf8, fsmId:1, tslot:5, thread:0, ctxid:0, blk:11, sublk:0, subErrType:4.[FUNC:PrintCoreInfo][FILE:device_error_core_proc.cc][LINE:360]
(Worker pid=774) (Worker_DP0_TP7_EP7 pid=774) ERROR 03-24 16:17:14 [multiproc_executor.py:880]        The error from device(chipId:7, dieId:0), serial number is 11, there is an exception of aivec error, core id is 48, error code = 0x800000, dump info: pc start: 0x124e021fe000, current: 0x124e021fe380, vec error info: 0x701bb5de0a, mte error info: 0xf8030971df, ifu error info: 0x441e29e346800, ccu error info: 0x11cc00717c0000df, cube error info: 0, biu error info: 0, aic error mask: 0x6500020bd00028c, para base: 0x12c140403c00.[FUNC:PrintCoreInfo][FILE:device_error_core_proc.cc][LINE:347]
(Worker pid=774) (Worker_DP0_TP7_EP7 pid=774) ERROR 03-24 16:17:14 [multiproc_executor.py:880]        The extend info: errcode:(0x800000, 0x4000, 0) errorStr: The DDR address of the MTE instruction is out of range.CCU instruction address check error. fixp_error0 info: 0x30971df, fixp_error1 info: 0xf8, fsmId:1, tslot:5, thread:0, ctxid:0, blk:12, sublk:0, subErrType:4.[FUNC:PrintCoreInfo][FILE:device_error_core_proc.cc][LINE:360]
(Worker pid=774) (Worker_DP0_TP7_EP7 pid=774) ERROR 03-24 16:17:14 [multiproc_executor.py:880]        The error from device(chipId:7, dieId:0), serial number is 11, there is an exception of aivec error, core id is 49, error code = 0x800000, dump info: pc start: 0x124e021fe000, current: 0x124e021fe39c, vec error info: 0x7b15968984, mte error info: 0xf8030971df, ifu error info: 0x5f86d0f3ad000, ccu error info: 0x27ab817e7c0000df, cube error info: 0, biu error info: 0, aic error mask: 0x6500020bd00028c, para base: 0x12c140403c00.[FUNC:PrintCoreInfo][FILE:device_error_core_proc.cc][LINE:347] 
...
(Worker pid=455) (Worker_DP0_TP1_EP1 pid=455) ERROR 03-24 16:17:14 [multiproc_executor.py:880]        wait event to be complete failed, runtime result = 507057[FUNC:ReportCallError][FILE:log_inner.cpp][LINE:148]
(Worker pid=455) (Worker_DP0_TP1_EP1 pid=455) ERROR 03-24 16:17:14 [multiproc_executor.py:880] 
(Worker pid=455) (Worker_DP0_TP1_EP1 pid=455) ERROR 03-24 16:17:14 [multiproc_executor.py:880] 
(APIServer pid=253) INFO 03-24 16:17:19 [loggers.py:259] Engine 000: Avg prompt throughput: 0.1 tokens/s, Avg generation throughput: 0.1 tokens/s, Running: 1 reqs, Waiting: 0 reqs, GPU KV cache usage: 1.0%, Prefix cache hit rate: 0.0%, External prefix cache hit rate: 100.0%
(APIServer pid=253) INFO 03-24 16:17:19 [metrics.py:100] SpecDecoding metrics: Mean acceptance length: 1.00, Accepted throughput: 0.00 tokens/s, Drafted throughput: 0.07 tokens/s, Accepted: 0 tokens, Drafted: 3 tokens, Per-position acceptance rate: 0.000, 0.000, 0.000, Avg Draft acceptance rate: 0.0%
(APIServer pid=253) INFO 03-24 16:17:29 [loggers.py:259] Engine 000: Avg prompt throughput: 0.0 tokens/s, Avg generation throughput: 0.0 tokens/s, Running: 1 reqs, Waiting: 0 reqs, GPU KV cache usage: 1.0%, Prefix cache hit rate: 0.0%, External prefix cache hit rate: 100.0%
```

**Comment by Celdrick** [comment]
Same problem appears when deploy Eco-Tech/Qwen3.5-27B-w8a8-mtp Prefill Decode Disaggregation

**Comment by realliujiaxu** [comment]
@LoganJane @shaopeng-666

**Comment by MengqingCao** [comment]
Could you post the exact info about your env, including pip list and cpu arch, thx!

**Comment by qaz2883383** [comment]
@MengqingCao 就0.17.0RC1的开源镜像，ARM的机器，4机PD分离

**Comment by wyu0-0** [comment]
> [@MengqingCao](https://github.com/MengqingCao) 就0.17.0RC1的开源镜像，ARM的机器，4机PD分离

@qaz2883383 Please upgrade the version to the latest 0.18. This problem has been resolved in the new version.
