### ISSUE TITLE
[Bug]: torch_npu.npu_fused_infer_attention_score | When layout is TND, queryD(128) or keyD(128) must be 192, valueD(128) must be 192/128!

### ISSUE THREAD

**Issue by MuqiuX** [vllm-project/vllm-ascend#8045]
### Your current environment

dirver==24.1.rc3
toolkit==8.3.RC1
nnal==8.3.RC1

python==3.11.13
torch==2.8.0
torch_npu==2.8.0
vllm==0.13.0
vllm-ascend==0.13.0rc1
<details>
<summary>The output of `python collect_env.py`</summary>

```text
PyTorch version: 2.8.0+cpu
Is debug build: False

OS: Ubuntu 22.04.5 LTS (aarch64)
GCC version: (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
Clang version: Could not collect
CMake version: version 4.3.1
Libc version: glibc-2.35

Python version: 3.11.13 (main, Jun  5 2025, 13:03:00) [GCC 11.2.0] (64-bit runtime)
Python platform: Linux-5.15.0-101-generic-aarch64-with-glibc2.35

CPU:
Architecture:                       aarch64
CPU op-mode(s):                     64-bit
Byte Order:                         Little Endian
CPU(s):                             192
On-line CPU(s) list:                0-191
Vendor ID:                          HiSilicon
Model name:                         Kunpeng-920
Model:                              0
Thread(s) per core:                 1
Core(s) per cluster:                48
Socket(s):                          -
Cluster(s):                         4
Stepping:                           0x1
BogoMIPS:                           200.00
Flags:                              fp asimd evtstrm aes pmull sha1 sha2 crc32 atomics fphp asimdhp cpuid asimdrdm jscvt fcma dcpop asimddp asimdfhm ssbs
L1d cache:                          12 MiB (192 instances)
L1i cache:                          12 MiB (192 instances)
L2 cache:                           96 MiB (192 instances)
L3 cache:                           192 MiB (8 instances)
NUMA node(s):                       8
NUMA node0 CPU(s):                  0-23
NUMA node1 CPU(s):                  24-47
NUMA node2 CPU(s):                  48-71
NUMA node3 CPU(s):                  72-95
NUMA node4 CPU(s):                  96-119
NUMA node5 CPU(s):                  120-143
NUMA node6 CPU(s):                  144-167
NUMA node7 CPU(s):                  168-191
Vulnerability Gather data sampling: Not affected
Vulnerability Itlb multihit:        Not affected
Vulnerability L1tf:                 Not affected
Vulnerability Mds:                  Not affected
Vulnerability Meltdown:             Not affected
Vulnerability Mmio stale data:      Not affected
Vulnerability Retbleed:             Not affected
Vulnerability Spec rstack overflow: Not affected
Vulnerability Spec store bypass:    Mitigation; Speculative Store Bypass disabled via prctl
Vulnerability Spectre v1:           Mitigation; __user pointer sanitization
Vulnerability Spectre v2:           Not affected
Vulnerability Srbds:                Not affected
Vulnerability Tsx async abort:      Not affected

Versions of relevant libraries:
[pip3] numpy==1.26.4
[pip3] pyzmq==27.1.0
[pip3] torch==2.8.0
[pip3] torch_npu==2.8.0
[pip3] torchaudio==2.9.0
[pip3] torchvision==0.23.0
[pip3] transformers==4.57.6
[conda] numpy                     1.26.4                   pypi_0    pypi
[conda] pyzmq                     27.1.0                   pypi_0    pypi
[conda] torch                     2.8.0                    pypi_0    pypi
[conda] torch-npu                 2.8.0                    pypi_0    pypi
[conda] torchaudio                2.9.0                    pypi_0    pypi
[conda] torchvision               0.23.0                   pypi_0    pypi
[conda] transformers              4.57.6                   pypi_0    pypi
vLLM Version: 0.13.0
vLLM Ascend Version: 0.13.0rc1

ENV Variables:
ATB_OPSRUNNER_KERNEL_CACHE_LOCAL_COUNT=1
ATB_STREAM_SYNC_EVERY_RUNNER_ENABLE=0
ATB_OPSRUNNER_SETUP_CACHE_ENABLE=1
ATB_WORKSPACE_MEM_ALLOC_GLOBAL=1
ATB_DEVICE_TILING_BUFFER_BLOCK_NUM=32
ATB_STREAM_SYNC_EVERY_KERNEL_ENABLE=0
ATB_OPSRUNNER_KERNEL_CACHE_GLOABL_COUNT=5
ATB_HOME_PATH=/usr/local/Ascend/nnal/atb/latest/atb/cxx_abi_1
ASCEND_TOOLKIT_HOME=/usr/local/Ascend/ascend-toolkit/latest
VLLM_PLUGINS=ascend
ATB_COMPARE_TILING_EVERY_KERNEL=0
ASCEND_OPP_PATH=/usr/local/Ascend/ascend-toolkit/latest/opp
LD_LIBRARY_PATH=/usr/local/Ascend/nnal/atb/latest/atb/cxx_abi_1/lib:/usr/local/Ascend/nnal/atb/latest/atb/cxx_abi_1/examples:/usr/local/Ascend/nnal/atb/latest/atb/cxx_abi_1/tests/atbopstest:/usr/local/Ascend/ascend-toolkit/latest/tools/aml/lib64:/usr/local/Ascend/ascend-toolkit/latest/tools/aml/lib64/plugin:/usr/local/Ascend/ascend-toolkit/latest/lib64:/usr/local/Ascend/ascend-toolkit/latest/lib64/plugin/opskernel:/usr/local/Ascend/ascend-toolkit/latest/lib64/plugin/nnengine:/usr/local/Ascend/ascend-toolkit/latest/opp/built-in/op_impl/ai_core/tbe/op_tiling/lib/linux/aarch64:/usr/local/Ascend/nnal/atb/latest/atb/cxx_abi_0/lib:/usr/local/Ascend/nnal/atb/latest/atb/cxx_abi_0/examples:/usr/local/Ascend/nnal/atb/latest/atb/cxx_abi_0/tests/atbopstest:/usr/local/Ascend/ascend-toolkit/latest/tools/aml/lib64:/usr/local/Ascend/ascend-toolkit/latest/tools/aml/lib64/plugin:/usr/local/Ascend/ascend-toolkit/latest/lib64:/usr/local/Ascend/ascend-toolkit/latest/lib64/plugin/opskernel:/usr/local/Ascend/ascend-toolkit/latest/lib64/plugin/nnengine:/usr/local/Ascend/ascend-toolkit/latest/opp/built-in/op_impl/ai_core/tbe/op_tiling/lib/linux/aarch64:/usr/local/Ascend/nnal/atb/latest/atb/cxx_abi_1/lib:/usr/local/Ascend/nnal/atb/latest/atb/cxx_abi_1/examples:/usr/local/Ascend/nnal/atb/latest/atb/cxx_abi_1/tests/atbopstest:/usr/local/Ascend/ascend-toolkit/latest/tools/aml/lib64:/usr/local/Ascend/ascend-toolkit/latest/tools/aml/lib64/plugin:/usr/local/Ascend/ascend-toolkit/latest/lib64:/usr/local/Ascend/ascend-toolkit/latest/lib64/plugin/opskernel:/usr/local/Ascend/ascend-toolkit/latest/lib64/plugin/nnengine:/usr/local/Ascend/ascend-toolkit/latest/opp/built-in/op_impl/ai_core/tbe/op_tiling/lib/linux/aarch64:/usr/local/Ascend/nnal/atb/latest/atb/cxx_abi_1/lib:/usr/local/Ascend/nnal/atb/latest/atb/cxx_abi_1/examples:/usr/local/Ascend/nnal/atb/latest/atb/cxx_abi_1/tests/atbopstest:/usr/local/Ascend/ascend-toolkit/latest/tools/aml/lib64:/usr/local/Ascend/ascend-toolkit/latest/tools/aml/lib64/plugin:/usr/local/Ascend/ascend-toolkit/latest/lib64:/usr/local/Ascend/ascend-toolkit/latest/lib64/plugin/opskernel:/usr/local/Ascend/ascend-toolkit/latest/lib64/plugin/nnengine:/usr/local/Ascend/ascend-toolkit/latest/opp/built-in/op_impl/ai_core/tbe/op_tiling/lib/linux/aarch64:/usr/local/Ascend/nnal/atb/latest/atb/cxx_abi_1/lib:/usr/local/Ascend/nnal/atb/latest/atb/cxx_abi_1/examples:/usr/local/Ascend/nnal/atb/latest/atb/cxx_abi_1/tests/atbopstest:/usr/local/Ascend/ascend-toolkit/latest/tools/aml/lib64:/usr/local/Ascend/ascend-toolkit/latest/tools/aml/lib64/plugin:/usr/local/Ascend/ascend-toolkit/latest/lib64:/usr/local/Ascend/ascend-toolkit/latest/lib64/plugin/opskernel:/usr/local/Ascend/ascend-toolkit/latest/lib64/plugin/nnengine:/usr/local/Ascend/ascend-toolkit/latest/opp/built-in/op_impl/ai_core/tbe/op_tiling/lib/linux/aarch64::/usr/local/Ascend/driver/lib64/common/:/usr/local/Ascend/driver/lib64/driver/:/usr/local/Ascend/driver/lib64/common/:/usr/local/Ascend/driver/lib64/driver/
ASCEND_AICPU_PATH=/usr/local/Ascend/ascend-toolkit/latest
ATB_STREAM_SYNC_EVERY_OPERATION_ENABLE=0
ASCEND_HOME_PATH=/usr/local/Ascend/ascend-toolkit/latest
ATB_MATMUL_SHUFFLE_K_ENABLE=1
ATB_WORKSPACE_MEM_ALLOC_ALG_TYPE=1
ATB_HOST_TILING_BUFFER_BLOCK_NUM=128
ATB_SHARE_MEMORY_NAME_SUFFIX=
TORCH_DEVICE_BACKEND_AUTOLOAD=1
PYTORCH_NVML_BASED_CUDA_CHECK=1
TORCHINDUCTOR_COMPILE_THREADS=1


NPU:
+------------------------------------------------------------------------------------------------+
| npu-smi 24.1.rc3                 Version: 24.1.rc3                                             |
+---------------------------+---------------+----------------------------------------------------+
| NPU   Name                | Health        | Power(W)    Temp(C)           Hugepages-Usage(page)|
| Chip                      | Bus-Id        | AICore(%)   Memory-Usage(MB)  HBM-Usage(MB)        |
+===========================+===============+====================================================+
| 1     910B2               | OK            | 95.2        46                0    / 0             |
| 0                         | 0000:01:00.0  | 0           0    / 0          3426 / 65536         |
+===========================+===============+====================================================+
+---------------------------+---------------+----------------------------------------------------+
| NPU     Chip              | Process id    | Process name             | Process memory(MB)      |
+===========================+===============+====================================================+
| No running processes found in NPU 1                                                            |
+===========================+===============+====================================================+

CANN:
package_name=Ascend-cann-toolkit
version=8.3.RC1
innerversion=V100R001C23SPC001B235
compatible_version=[V100R001C15],[V100R001C18],[V100R001C19],[V100R001C20],[V100R001C21],[V100R001C23]
arch=aarch64
os=linux
path=/usr/local/Ascend/ascend-toolkit/8.3.RC1/aarch64-linux
```

</details>

### 🐛 Describe the bug

运行下面脚本（Qwen/Qwen3-8B模型）后，在进行模型推理阶段报错
```
(EngineCore_DP0 pid=189310)   File "/root/miniconda3/envs/lm/lib/python3.11/site-packages/vllm_ascend/attention/attention_v1.py", line 539, in forward_fused_infer_attention
(EngineCore_DP0 pid=189310)     attn_output, _ = torch_npu.npu_fused_infer_attention_score(
(EngineCore_DP0 pid=189310)                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(EngineCore_DP0 pid=189310)   File "/root/miniconda3/envs/lm/lib/python3.11/site-packages/torch/_ops.py", line 1243, in __call__
(EngineCore_DP0 pid=189310)     return self._op(*args, **kwargs)
(EngineCore_DP0 pid=189310)            ^^^^^^^^^^^^^^^^^^^^^^^^^
(EngineCore_DP0 pid=189310) RuntimeError: npu_fused_infer_attention_score_symint:build/CMakeFiles/torch_npu.dir/compiler_depend.ts:208 NPU function error: call aclnnFusedInferAttentionScoreV3 failed, error code is 561002
(EngineCore_DP0 pid=189310) [ERROR] 2026-04-08-15:35:45 (PID:189310, Device:0, RankID:-1) ERR00100 PTA call acl api failed.
(EngineCore_DP0 pid=189310) E89999: Inner Error!
(EngineCore_DP0 pid=189310) E89999[PID: 189310] 2026-04-08-15:35:45.267.382 (E89999):  When layout is TND, queryD(128) or keyD(128) must be 192, valueD(128) must be 192/128![FUNC:DoOpTilingFusedInferAttentionScore][FILE:fused_infer_attention_score_tiling.cpp][LINE:494]
```

查找了Ascend Extension for PyTorch torch_npu.npu_fused_infer_attention_score 部分相关文档得到
在7.1.0版本下

<img width="865" height="140" alt="Image" src="https://github.com/user-attachments/assets/b2e8f8f6-de3d-44e5-9d9a-8fa5e37b12ab" />

在7.2.0版本

<img width="865" height="133" alt="Image" src="https://github.com/user-attachments/assets/a96bf91f-7d39-4ed6-9fe7-5c0e4c478820" />

在7.2.0版本对应我当前的torch-npu==2.8.0版本，描述的情况中Q_D, K_D,V_D应该是支持的，但是报错显示更像是对应了7.1.0版本的情况

```python
import os
import torch
from vllm import LLM, SamplingParams
from vllm.platforms import current_platform

print(f"Current Platform: {current_platform}")
print(f"Platform Type: {type(current_platform)}")

if "USE_FLAGGEMS" in os.environ:
    print(f"USE_FLAGGEMS: {os.environ['USE_FLAGGEMS']}")
if __name__ == "__main__":
    prompts = [
        "Hello, my name is",
    ]
    sampling_params = SamplingParams(max_tokens=10, temperature=0.0)
    llm = LLM(
              model="/root/autodl-tmp/model/Qwen3-8B", 
              max_num_batched_tokens=16384, 
              max_num_seqs=2048, 
              enforce_eager=True)
    # Generate texts from the prompts.
    outputs = llm.generate(prompts, sampling_params)
    for output in outputs:
        prompt = output.prompt
        generated_text = output.outputs[0].text
        print(f"Prompt: {prompt!r}, Generated text: {generated_text!r}")
    del llm
    torch.cuda.empty_cache()
    print("\n Reasoning complete, resources cleared.")
```

<img width="1507" height="457" alt="Image" src="https://github.com/user-attachments/assets/e13744d6-eef2-4c2f-8e08-a6c5f67ce30b" />

**Comment by yiz-liu** [comment]
Could you please update to the latest release version, or try the latest docker image?

**Comment by MuqiuX** [comment]
@yiz-liu 问题解决了，是我下载cann的时候没装kernels包了，他这个节省编译时间让我以为是预编译包就没安装

<img width="612" height="139" alt="Image" src="https://github.com/user-attachments/assets/79c95b04-c572-409a-a280-08fa8ba01316" />
