### ISSUE TITLE
[Bug]: Qwen3-Omni-30B-A3B-Instruct 模型服务拉起失败

### ISSUE THREAD

**Issue by ly13836333251-stack** [vllm-project/vllm-ascend#8068]
### Your current environment

<details>
<summary>The output of `python collect_env.py`</summary>

```text
PyTorch version: 2.9.0+cpu
Is debug build: False

OS: Ubuntu 22.04.5 LTS (aarch64)
GCC version: (Ubuntu 11.4.0-1ubuntu1~22.04.3) 11.4.0
Clang version: 15.0.7
CMake version: version 4.3.1
Libc version: glibc-2.35

Python version: 3.11.14 (main, Feb 26 2026, 04:49:14) [GCC 11.4.0] (64-bit runtime)
Python platform: Linux-5.4.119-19.0009.44-aarch64-with-glibc2.35

CPU:
Architecture:                    aarch64
CPU op-mode(s):                  64-bit
Byte Order:                      Little Endian
CPU(s):                          192
On-line CPU(s) list:             0-191
Vendor ID:                       HiSilicon
Model name:                      Kunpeng-920
Model:                           0
Thread(s) per core:              1
Core(s) per cluster:             48
Socket(s):                       -
Cluster(s):                      4
Stepping:                        0x1
BogoMIPS:                        200.00
Flags:                           fp asimd evtstrm aes pmull sha1 sha2 crc32 atomics fphp asimdhp cpuid asimdrdm jscvt fcma dcpop asimddp asimdfhm ssbs
L1d cache:                       12 MiB (192 instances)
L1i cache:                       12 MiB (192 instances)
L2 cache:                        96 MiB (192 instances)
L3 cache:                        192 MiB (8 instances)
NUMA node(s):                    4
NUMA node0 CPU(s):               0-47
NUMA node1 CPU(s):               48-95
NUMA node2 CPU(s):               96-143
NUMA node3 CPU(s):               144-191
Vulnerability Itlb multihit:     Not affected
Vulnerability L1tf:              Not affected
Vulnerability Mds:               Not affected
Vulnerability Meltdown:          Not affected
Vulnerability Spec store bypass: Mitigation; Speculative Store Bypass disabled via prctl
Vulnerability Spectre v1:        Mitigation; __user pointer sanitization
Vulnerability Spectre v2:        Not affected
Vulnerability Srbds:             Not affected
Vulnerability Tsx async abort:   Not affected

Versions of relevant libraries:
[pip3] ema-pytorch==0.7.9
[pip3] numpy==1.26.4
[pip3] onnxruntime==1.24.4
[pip3] onnxruntime-cann==1.24.4
[pip3] pyzmq==27.1.0
[pip3] torch==2.9.0
[pip3] torch_npu==2.9.0
[pip3] torchaudio==2.9.0
[pip3] torchsde==0.2.6
[pip3] torchvision==0.24.0
[pip3] transformers==4.57.6
[pip3] triton-ascend==3.2.0
[pip3] x-transformers==2.17.9
[conda] Could not collect
vLLM Version: 0.18.0
vLLM Ascend Version: 0.18.0rc1

ENV Variables:
ASCEND_TOOLKIT_LATEST_HOME=/usr/local/Ascend/ascend-toolkit/latest
ATB_OPSRUNNER_KERNEL_CACHE_LOCAL_COUNT=1
ATB_STREAM_SYNC_EVERY_RUNNER_ENABLE=0
ASCEND_VISIBLE_DEVICES=2,1
ATB_STREAM_SYNC_EVERY_KERNEL_ENABLE=0
ATB_OPSRUNNER_KERNEL_CACHE_GLOABL_COUNT=5
ATB_HOME_PATH=/usr/local/Ascend/nnal/atb/latest/atb/cxx_abi_1
ASCEND_TOOLKIT_HOME=/usr/local/Ascend/cann-8.5.1
ATB_COMPARE_TILING_EVERY_KERNEL=0
ASCEND_OPP_PATH=/usr/local/Ascend/cann-8.5.1/opp
LD_LIBRARY_PATH=/usr/local/Ascend/nnal/atb/latest/atb/cxx_abi_1/lib:/usr/local/Ascend/nnal/atb/latest/atb/cxx_abi_1/examples:/usr/local/Ascend/nnal/atb/latest/atb/cxx_abi_1/tests/atbopstest:/usr/local/Ascend/cann-8.5.1/lib64:/usr/local/Ascend/cann-8.5.1/lib64/plugin/opskernel:/usr/local/Ascend/cann-8.5.1/lib64/plugin/nnengine:/usr/local/Ascend/cann-8.5.1/opp/built-in/op_impl/ai_core/tbe/op_tiling/lib/linux/aarch64:/usr/local/Ascend/cann-8.5.1/tools/aml/lib64:/usr/local/Ascend/cann-8.5.1/tools/aml/lib64/plugin:/usr/local/Ascend/driver/lib64:/usr/local/Ascend/driver/lib64/common:/usr/local/Ascend/driver/lib64/driver:/usr/local/Ascend/nnal/atb/latest/atb/cxx_abi_1/lib:/usr/local/Ascend/nnal/atb/latest/atb/cxx_abi_1/examples:/usr/local/Ascend/nnal/atb/latest/atb/cxx_abi_1/tests/atbopstest:/usr/local/Ascend/ascend-toolkit/latest/tools/aml/lib64:/usr/local/Ascend/ascend-toolkit/latest/tools/aml/lib64/plugin:/usr/local/Ascend/ascend-toolkit/latest/lib64:/usr/local/Ascend/ascend-toolkit/latest/lib64/plugin/opskernel:/usr/local/Ascend/ascend-toolkit/latest/lib64/plugin/nnengine:/usr/local/Ascend/ascend-toolkit/latest/opp/built-in/op_impl/ai_core/tbe/op_tiling:/usr/local/Ascend/driver/lib64:/usr/local/Ascend/driver/lib64/common/:/usr/local/Ascend/driver/lib64/driver/:/usr/local/python3.11.14/lib:
ASCEND_AICPU_PATH=/usr/local/Ascend/cann-8.5.1
VLLM_LOGGING_LEVEL=INFO
ATB_STREAM_SYNC_EVERY_OPERATION_ENABLE=0
ASCEND_HOME_PATH=/usr/local/Ascend/cann-8.5.1
ATB_MATMUL_SHUFFLE_K_ENABLE=1
ATB_WORKSPACE_MEM_ALLOC_ALG_TYPE=1
ATB_SHARE_MEMORY_NAME_SUFFIX=
TORCH_DEVICE_BACKEND_AUTOLOAD=1
PYTORCH_NVML_BASED_CUDA_CHECK=1
TORCHINDUCTOR_COMPILE_THREADS=1


NPU:
+------------------------------------------------------------------------------------------------+
| npu-smi 25.5.0                   Version: 25.5.0                                               |
+---------------------------+---------------+----------------------------------------------------+
| NPU   Name                | Health        | Power(W)    Temp(C)           Hugepages-Usage(page)|
| Chip                      | Bus-Id        | AICore(%)   Memory-Usage(MB)  HBM-Usage(MB)        |
+===========================+===============+====================================================+
| 1     910B3               | OK            | 98.7        37                0    / 0             |
| 0                         | 0000:C2:00.0  | 0           0    / 0          3448 / 65536         |
+===========================+===============+====================================================+
| 2     910B3               | OK            | 93.0        35                0    / 0             |
| 0                         | 0000:81:00.0  | 0           0    / 0          3445 / 65536         |
+===========================+===============+====================================================+
+---------------------------+---------------+----------------------------------------------------+
| NPU     Chip              | Process id    | Process name             | Process memory(MB)      |
+===========================+===============+====================================================+
| No running processes found in NPU 1                                                            |
+===========================+===============+====================================================+
| No running processes found in NPU 2                                                            |
+===========================+===============+====================================================+

CANN:
package_name=Ascend-cann-toolkit
version=8.5.1
innerversion=V100R001C25SPC002B220
compatible_version=[V100R001C15],[V100R001C18],[V100R001C19],[V100R001C20],[V100R001C21],[V100R001C23]
arch=aarch64
os=linux
path=/usr/local/Ascend/cann-8.5.1
```

</details>

### 🐛 Describe the bug

vllm使用版本：0.18.0
vllm-ascend使用版本：0.18.0rc1
vllm-omni使用版本：0.18.0

运行启动命令：
```
vllm serve /data/Qwen/Qwen3-Omni-30B-A3B-Instruct/master/Qwen_Qwen3-Omni-30B-A3B-Instruct_master_20250928_02/ --omni --tensor-parallel-size 2
```

报错：
```
INFO 04-09 02:05:26 [__init__.py:44] Available plugins for group vllm.platform_plugins:
INFO 04-09 02:05:26 [__init__.py:46] - ascend -> vllm_ascend:register
INFO 04-09 02:05:26 [__init__.py:49] All plugins in this group will be loaded. Set `VLLM_PLUGINS` to control which plugins to load.
INFO 04-09 02:05:26 [__init__.py:239] Platform plugin ascend is activated
INFO 04-09 02:05:42 [__init__.py:110] Registered model loader `<class 'vllm_ascend.model_loader.netloader.netloader.ModelNetLoaderElastic'>` with load format `netloader`
INFO 04-09 02:05:42 [__init__.py:110] Registered model loader `<class 'vllm_ascend.model_loader.rfork.rfork_loader.RForkModelLoader'>` with load format `rfork`
INFO 04-09 02:05:52 [logo.py:45]        █     █     █▄   ▄█       ▄▀▀▀▀▄ █▄   ▄█ █▄    █ ▀█▀ 
INFO 04-09 02:05:52 [logo.py:45]  ▄▄ ▄█ █     █     █ ▀▄▀ █  ▄▄▄  █    █ █ ▀▄▀ █ █ ▀▄  █  █  
INFO 04-09 02:05:52 [logo.py:45]   █▄█▀ █     █     █     █       █    █ █     █ █   ▀▄█  █  
INFO 04-09 02:05:52 [logo.py:45]    ▀▀  ▀▀▀▀▀ ▀▀▀▀▀ ▀     ▀        ▀▀▀▀  ▀     ▀ ▀     ▀ ▀▀▀ 
INFO 04-09 02:05:52 [logo.py:45] 
(APIServer pid=24645) INFO 04-09 02:05:52 [utils.py:297] vLLM server version 0.18.0, serving model /data/Qwen/Qwen3-Omni-30B-A3B-Instruct/master/Qwen_Qwen3-Omni-30B-A3B-Instruct_master_20250928_02/
(APIServer pid=24645) INFO 04-09 02:05:52 [utils.py:233] non-default args: {'model_tag': '/data/Qwen/Qwen3-Omni-30B-A3B-Instruct/master/Qwen_Qwen3-Omni-30B-A3B-Instruct_master_20250928_02/', 'model': '/data/Qwen/Qwen3-Omni-30B-A3B-Instruct/master/Qwen_Qwen3-Omni-30B-A3B-Instruct_master_20250928_02/', 'tensor_parallel_size': 2}
(APIServer pid=24645) INFO 04-09 02:05:52 [omni_base.py:93] [AsyncOmni] Initializing with model /data/Qwen/Qwen3-Omni-30B-A3B-Instruct/master/Qwen_Qwen3-Omni-30B-A3B-Instruct_master_20250928_02/
(APIServer pid=24645) INFO 04-09 02:05:52 [async_omni_engine.py:216] [AsyncOmniEngine] Initializing with model /data/Qwen/Qwen3-Omni-30B-A3B-Instruct/master/Qwen_Qwen3-Omni-30B-A3B-Instruct_master_20250928_02/
(APIServer pid=24645) Unrecognized keys in `rope_scaling` for 'rope_type'='default': {'mrope_interleaved', 'mrope_section', 'interleaved'}
(APIServer pid=24645) Unrecognized keys in `rope_scaling` for 'rope_type'='default': {'mrope_section', 'interleaved'}
(APIServer pid=24645) Unrecognized keys in `rope_scaling` for 'rope_type'='default': {'mrope_interleaved', 'mrope_section', 'interleaved'}
(APIServer pid=24645) Unrecognized keys in `rope_scaling` for 'rope_type'='default': {'mrope_section', 'interleaved'}
(APIServer pid=24645) WARNING 04-09 02:05:52 [utils.py:115] Filtered out 1 callable object(s) from base_engine_args that are not compatible with OmegaConf: ['dispatch_function']. 
(APIServer pid=24645) INFO 04-09 02:05:53 [async_omni_engine.py:248] [AsyncOmniEngine] Launching Orchestrator thread with 3 stages
(APIServer pid=24645) INFO 04-09 02:05:53 [initialization.py:251] Auto-configuring SharedMemoryConnector for edge ('0', '1')
(APIServer pid=24645) INFO 04-09 02:05:53 [initialization.py:251] Auto-configuring SharedMemoryConnector for edge ('1', '2')
(APIServer pid=24645) INFO 04-09 02:05:53 [initialization.py:270] Loaded OmniTransferConfig with 2 connector configurations
(APIServer pid=24645) INFO 04-09 02:05:53 [async_omni_engine.py:466] [AsyncOmniEngine] Initializing stage 0
(APIServer pid=24645) INFO 04-09 02:05:53 [stage_init_utils.py:222] [stage_init] Stage-0 set runtime devices: 0,1
(APIServer pid=24645) INFO 04-09 02:05:53 [async_omni_engine.py:466] [AsyncOmniEngine] Initializing stage 1
(APIServer pid=24645) INFO 04-09 02:05:53 [async_omni_engine.py:466] [AsyncOmniEngine] Initializing stage 2
(APIServer pid=24645) WARNING 04-09 02:05:53 [config.py:338] Config format `mistral` is already registered, and will be overwritten by the new parser class `<class 'vllm_omni.model_executor.models.voxtral_tts.configuration_voxtral_tts.VoxtralTTSConfigParser'>`.
(APIServer pid=24645) INFO 04-09 02:05:53 [config.py:349] Registered config parser `<class 'vllm_omni.model_executor.models.voxtral_tts.configuration_voxtral_tts.VoxtralTTSConfigParser'>` with config format `mistral`
(APIServer pid=24645) Unrecognized keys in `rope_scaling` for 'rope_type'='default': {'mrope_interleaved', 'mrope_section', 'interleaved'}
(APIServer pid=24645) Unrecognized keys in `rope_scaling` for 'rope_type'='default': {'mrope_section', 'interleaved'}
(APIServer pid=24645) INFO 04-09 02:05:53 [model.py:533] Resolved architecture: Qwen3OmniMoeForConditionalGeneration
(APIServer pid=24645) INFO 04-09 02:05:53 [model.py:1582] Using max model len 65536
(APIServer pid=24645) INFO 04-09 02:05:53 [scheduler.py:231] Chunked prefill is enabled with max_num_batched_tokens=8192.
(APIServer pid=24645) INFO 04-09 02:05:53 [vllm.py:754] Asynchronous scheduling is enabled.
(APIServer pid=24645) WARNING 04-09 02:05:53 [platform.py:749] Parameter '--disable-cascade-attn' is a GPU-specific feature. Resetting to False for Ascend.
(APIServer pid=24645) WARNING 04-09 02:05:53 [platform.py:838] Ignored parameter 'disable_flashinfer_prefill'. This is a GPU-specific feature not supported on Ascend. Resetting to False.
(APIServer pid=24645) INFO 04-09 02:05:53 [ascend_config.py:425] Dynamic EPLB is False
(APIServer pid=24645) INFO 04-09 02:05:53 [ascend_config.py:426] The number of redundant experts is 0
(APIServer pid=24645) INFO 04-09 02:05:53 [platform.py:354] PIECEWISE compilation enabled on NPU. use_inductor not supported - using only ACL Graph mode
(APIServer pid=24645) INFO 04-09 02:05:53 [utils.py:549] Calculated maximum supported batch sizes for ACL graph: 11
(APIServer pid=24645) WARNING 04-09 02:05:53 [utils.py:550] Currently, communication is performed using FFTS+ method, which reduces the number of available streams and, as a result, limits the range of runtime shapes that can be handled. To both improve communication performance and increase the number of supported shapes, set HCCL_OP_EXPANSION_MODE=AIV.
(APIServer pid=24645) INFO 04-09 02:05:53 [utils.py:582] No adjustment needed for ACL graph batch sizes: Qwen3OmniMoeForConditionalGeneration model (layers: 48) with 1 sizes
(APIServer pid=24645) INFO 04-09 02:05:53 [utils.py:1114] Block size is set to 128 if prefix cache or chunked prefill is enabled.
(APIServer pid=24645) INFO 04-09 02:05:53 [platform.py:502] Set PYTORCH_NPU_ALLOC_CONF=expandable_segments:True
(APIServer pid=24645) INFO 04-09 02:05:53 [compilation.py:289] Enabled custom fusions: norm_quant, act_quant
(APIServer pid=24645) INFO 04-09 02:05:53 [async_omni_engine.py:360] [AsyncOmniEngine] Stage 0 engine launch started
(APIServer pid=24645) INFO 04-09 02:05:53 [stage_init_utils.py:222] [stage_init] Stage-1 set runtime devices: 2
(APIServer pid=24645) Unrecognized keys in `rope_scaling` for 'rope_type'='default': {'mrope_interleaved', 'mrope_section', 'interleaved'}
(APIServer pid=24645) Unrecognized keys in `rope_scaling` for 'rope_type'='default': {'mrope_section', 'interleaved'}
(APIServer pid=24645) INFO 04-09 02:05:53 [model.py:533] Resolved architecture: Qwen3OmniMoeForConditionalGeneration
(APIServer pid=24645) INFO 04-09 02:05:53 [model.py:1582] Using max model len 65536
(APIServer pid=24645) INFO 04-09 02:05:53 [model.py:1582] Using max model len 65536
(APIServer pid=24645) INFO 04-09 02:05:53 [scheduler.py:231] Chunked prefill is enabled with max_num_batched_tokens=8192.
(APIServer pid=24645) WARNING 04-09 02:05:53 [vllm.py:788] Enforce eager set, disabling torch.compile and CUDAGraphs. This is equivalent to setting -cc.mode=none -cc.cudagraph_mode=none
(APIServer pid=24645) WARNING 04-09 02:05:53 [vllm.py:799] Inductor compilation was disabled by user settings, optimizations settings that are only active during inductor compilation will be ignored.
(APIServer pid=24645) INFO 04-09 02:05:53 [vllm.py:964] Cudagraph is disabled under eager mode
(APIServer pid=24645) WARNING 04-09 02:05:53 [platform.py:749] Parameter '--disable-cascade-attn' is a GPU-specific feature. Resetting to False for Ascend.
(APIServer pid=24645) WARNING 04-09 02:05:53 [platform.py:838] Ignored parameter 'disable_flashinfer_prefill'. This is a GPU-specific feature not supported on Ascend. Resetting to False.
(APIServer pid=24645) INFO 04-09 02:05:53 [platform.py:297] Compilation disabled, using eager mode by default
(APIServer pid=24645) INFO 04-09 02:05:53 [utils.py:1114] Block size is set to 128 if prefix cache or chunked prefill is enabled.
(APIServer pid=24645) INFO 04-09 02:05:53 [platform.py:502] Set PYTORCH_NPU_ALLOC_CONF=expandable_segments:True
(APIServer pid=24645) INFO 04-09 02:05:53 [async_omni_engine.py:360] [AsyncOmniEngine] Stage 1 engine launch started
(APIServer pid=24645) INFO 04-09 02:05:53 [stage_init_utils.py:222] [stage_init] Stage-2 set runtime devices: 2
(APIServer pid=24645) Unrecognized keys in `rope_scaling` for 'rope_type'='default': {'mrope_interleaved', 'mrope_section', 'interleaved'}
(APIServer pid=24645) Unrecognized keys in `rope_scaling` for 'rope_type'='default': {'mrope_section', 'interleaved'}
(APIServer pid=24645) INFO 04-09 02:05:53 [model.py:533] Resolved architecture: Qwen3OmniMoeForConditionalGeneration
(APIServer pid=24645) INFO 04-09 02:05:53 [model.py:1582] Using max model len 65536
(APIServer pid=24645) INFO 04-09 02:05:53 [scheduler.py:231] Chunked prefill is enabled with max_num_batched_tokens=1000000.
(APIServer pid=24645) WARNING 04-09 02:05:53 [scheduler.py:273] max_num_batched_tokens (1000000) exceeds max_num_seqs * max_model_len (65536). This may lead to unexpected behavior.
(APIServer pid=24645) INFO 04-09 02:05:53 [vllm.py:754] Asynchronous scheduling is disabled.
(APIServer pid=24645) WARNING 04-09 02:05:53 [vllm.py:788] Enforce eager set, disabling torch.compile and CUDAGraphs. This is equivalent to setting -cc.mode=none -cc.cudagraph_mode=none
(APIServer pid=24645) WARNING 04-09 02:05:53 [vllm.py:799] Inductor compilation was disabled by user settings, optimizations settings that are only active during inductor compilation will be ignored.
(APIServer pid=24645) INFO 04-09 02:05:53 [vllm.py:964] Cudagraph is disabled under eager mode
(APIServer pid=24645) WARNING 04-09 02:05:53 [platform.py:749] Parameter '--disable-cascade-attn' is a GPU-specific feature. Resetting to False for Ascend.
(APIServer pid=24645) WARNING 04-09 02:05:53 [platform.py:838] Ignored parameter 'disable_flashinfer_prefill'. This is a GPU-specific feature not supported on Ascend. Resetting to False.
(APIServer pid=24645) INFO 04-09 02:05:53 [platform.py:297] Compilation disabled, using eager mode by default
(APIServer pid=24645) INFO 04-09 02:05:53 [utils.py:1114] Block size is set to 128 if prefix cache or chunked prefill is enabled.
(APIServer pid=24645) INFO 04-09 02:05:53 [platform.py:502] Set PYTORCH_NPU_ALLOC_CONF=expandable_segments:True
INFO 04-09 02:06:02 [__init__.py:44] Available plugins for group vllm.platform_plugins:
INFO 04-09 02:06:02 [__init__.py:46] - ascend -> vllm_ascend:register
INFO 04-09 02:06:02 [__init__.py:49] All plugins in this group will be loaded. Set `VLLM_PLUGINS` to control which plugins to load.
INFO 04-09 02:06:03 [__init__.py:239] Platform plugin ascend is activated
INFO 04-09 02:06:03 [__init__.py:44] Available plugins for group vllm.platform_plugins:
INFO 04-09 02:06:03 [__init__.py:46] - ascend -> vllm_ascend:register
INFO 04-09 02:06:03 [__init__.py:49] All plugins in this group will be loaded. Set `VLLM_PLUGINS` to control which plugins to load.
INFO 04-09 02:06:03 [__init__.py:239] Platform plugin ascend is activated
WARNING 04-09 02:06:11 [interface.py:657] Current platform  does not have '_enum' attribute.
(EngineCore pid=24805) INFO 04-09 02:06:12 [__init__.py:110] Registered model loader `<class 'vllm_ascend.model_loader.netloader.netloader.ModelNetLoaderElastic'>` with load format `netloader`
(EngineCore pid=24805) INFO 04-09 02:06:12 [__init__.py:110] Registered model loader `<class 'vllm_ascend.model_loader.rfork.rfork_loader.RForkModelLoader'>` with load format `rfork`
(EngineCore pid=24805) INFO 04-09 02:06:12 [core.py:103] Initializing a V1 LLM engine (v0.18.0) with config: model='/data/Qwen/Qwen3-Omni-30B-A3B-Instruct/master/Qwen_Qwen3-Omni-30B-A3B-Instruct_master_20250928_02/', speculative_config=None, tokenizer='/data/Qwen/Qwen3-Omni-30B-A3B-Instruct/master/Qwen_Qwen3-Omni-30B-A3B-Instruct_master_20250928_02/', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, tokenizer_revision=None, trust_remote_code=True, dtype=torch.bfloat16, max_seq_len=65536, download_dir=None, load_format=auto, tensor_parallel_size=2, pipeline_parallel_size=1, data_parallel_size=1, decode_context_parallel_size=1, dcp_comm_backend=ag_rs, disable_custom_all_reduce=True, quantization=None, enforce_eager=True, enable_return_routed_experts=False, kv_cache_dtype=auto, device_config=npu, structured_outputs_config=StructuredOutputsConfig(backend='auto', disable_any_whitespace=False, disable_additional_properties=False, reasoning_parser='', reasoning_parser_plugin='', enable_in_reasoning=False), observability_config=ObservabilityConfig(show_hidden_metrics_for_version=None, otlp_traces_endpoint=None, collect_detailed_traces=None, kv_cache_metrics=False, kv_cache_metrics_sample=0.01, cudagraph_metrics=False, enable_layerwise_nvtx_tracing=False, enable_mfu_metrics=False, enable_mm_processor_stats=False, enable_logging_iteration_details=False), seed=0, served_model_name=/data/Qwen/Qwen3-Omni-30B-A3B-Instruct/master/Qwen_Qwen3-Omni-30B-A3B-Instruct_master_20250928_02/, enable_prefix_caching=False, enable_chunked_prefill=True, pooler_config=None, compilation_config={'mode': <CompilationMode.NONE: 0>, 'debug_dump_path': None, 'cache_dir': '', 'compile_cache_save_format': 'binary', 'backend': 'vllm_ascend.compilation.compiler_interface.AscendCompiler', 'custom_ops': ['all'], 'splitting_ops': [], 'compile_mm_encoder': False, 'compile_sizes': [], 'compile_ranges_endpoints': [8192], 'inductor_compile_config': {'enable_auto_functionalized_v2': False, 'combo_kernels': True, 'benchmark_combo_kernel': True}, 'inductor_passes': {}, 'cudagraph_mode': <CUDAGraphMode.NONE: 0>, 'cudagraph_num_of_warmups': 1, 'cudagraph_capture_sizes': [], 'cudagraph_copy_inputs': False, 'cudagraph_specialize_lora': True, 'use_inductor_graph_partition': False, 'pass_config': {'fuse_norm_quant': True, 'fuse_act_quant': True, 'fuse_attn_quant': False, 'enable_sp': False, 'fuse_gemm_comms': False, 'fuse_allreduce_rms': False}, 'max_cudagraph_capture_size': 0, 'dynamic_shapes_config': {'type': <DynamicShapesType.BACKED: 'backed'>, 'evaluate_guards': False, 'assume_32_bit_indexing': False}, 'local_cache_dir': None, 'fast_moe_cold_start': True, 'static_all_moe_layers': []}
(EngineCore pid=24805) INFO 04-09 02:06:12 [multiproc_executor.py:134] DP group leader: node_rank=0, node_rank_within_dp=0, master_addr=127.0.0.1, mq_connect_ip=172.30.12.132 (local), world_size=2, local_world_size=2
(EngineCore pid=24802) INFO 04-09 02:06:13 [__init__.py:110] Registered model loader `<class 'vllm_ascend.model_loader.netloader.netloader.ModelNetLoaderElastic'>` with load format `netloader`
(EngineCore pid=24802) INFO 04-09 02:06:13 [__init__.py:110] Registered model loader `<class 'vllm_ascend.model_loader.rfork.rfork_loader.RForkModelLoader'>` with load format `rfork`
(EngineCore pid=24802) INFO 04-09 02:06:13 [core.py:103] Initializing a V1 LLM engine (v0.18.0) with config: model='/data/Qwen/Qwen3-Omni-30B-A3B-Instruct/master/Qwen_Qwen3-Omni-30B-A3B-Instruct_master_20250928_02/', speculative_config=None, tokenizer='/data/Qwen/Qwen3-Omni-30B-A3B-Instruct/master/Qwen_Qwen3-Omni-30B-A3B-Instruct_master_20250928_02/', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, tokenizer_revision=None, trust_remote_code=True, dtype=torch.bfloat16, max_seq_len=65536, download_dir=None, load_format=auto, tensor_parallel_size=2, pipeline_parallel_size=1, data_parallel_size=1, decode_context_parallel_size=1, dcp_comm_backend=ag_rs, disable_custom_all_reduce=True, quantization=None, enforce_eager=False, enable_return_routed_experts=False, kv_cache_dtype=auto, device_config=npu, structured_outputs_config=StructuredOutputsConfig(backend='auto', disable_any_whitespace=False, disable_additional_properties=False, reasoning_parser='', reasoning_parser_plugin='', enable_in_reasoning=False), observability_config=ObservabilityConfig(show_hidden_metrics_for_version=None, otlp_traces_endpoint=None, collect_detailed_traces=None, kv_cache_metrics=False, kv_cache_metrics_sample=0.01, cudagraph_metrics=False, enable_layerwise_nvtx_tracing=False, enable_mfu_metrics=False, enable_mm_processor_stats=False, enable_logging_iteration_details=False), seed=0, served_model_name=/data/Qwen/Qwen3-Omni-30B-A3B-Instruct/master/Qwen_Qwen3-Omni-30B-A3B-Instruct_master_20250928_02/, enable_prefix_caching=False, enable_chunked_prefill=True, pooler_config=None, compilation_config={'mode': <CompilationMode.VLLM_COMPILE: 3>, 'debug_dump_path': None, 'cache_dir': '', 'compile_cache_save_format': 'binary', 'backend': 'vllm_ascend.compilation.compiler_interface.AscendCompiler', 'custom_ops': ['all'], 'splitting_ops': ['vllm::unified_attention', 'vllm::unified_attention_with_output', 'vllm::unified_mla_attention', 'vllm::unified_mla_attention_with_output', 'vllm::mamba_mixer2', 'vllm::mamba_mixer', 'vllm::short_conv', 'vllm::linear_attention', 'vllm::plamo2_mamba_mixer', 'vllm::gdn_attention_core', 'vllm::olmo_hybrid_gdn_full_forward', 'vllm::kda_attention', 'vllm::sparse_attn_indexer', 'vllm::rocm_aiter_sparse_attn_indexer', 'vllm::unified_kv_cache_update', 'vllm::unified_mla_kv_cache_update', 'vllm::mla_forward'], 'compile_mm_encoder': False, 'compile_sizes': [], 'compile_ranges_endpoints': [8192], 'inductor_compile_config': {'enable_auto_functionalized_v2': False, 'combo_kernels': True, 'benchmark_combo_kernel': True}, 'inductor_passes': {}, 'cudagraph_mode': <CUDAGraphMode.PIECEWISE: 1>, 'cudagraph_num_of_warmups': 1, 'cudagraph_capture_sizes': [1], 'cudagraph_copy_inputs': False, 'cudagraph_specialize_lora': True, 'use_inductor_graph_partition': False, 'pass_config': {'fuse_norm_quant': True, 'fuse_act_quant': True, 'fuse_attn_quant': False, 'enable_sp': False, 'fuse_gemm_comms': False, 'fuse_allreduce_rms': False}, 'max_cudagraph_capture_size': 1, 'dynamic_shapes_config': {'type': <DynamicShapesType.BACKED: 'backed'>, 'evaluate_guards': False, 'assume_32_bit_indexing': False}, 'local_cache_dir': None, 'fast_moe_cold_start': True, 'static_all_moe_layers': []}
(EngineCore pid=24802) INFO 04-09 02:06:13 [multiproc_executor.py:134] DP group leader: node_rank=0, node_rank_within_dp=0, master_addr=127.0.0.1, mq_connect_ip=172.30.12.132 (local), world_size=2, local_world_size=2
INFO 04-09 02:06:20 [__init__.py:44] Available plugins for group vllm.platform_plugins:
INFO 04-09 02:06:20 [__init__.py:46] - ascend -> vllm_ascend:register
INFO 04-09 02:06:20 [__init__.py:49] All plugins in this group will be loaded. Set `VLLM_PLUGINS` to control which plugins to load.
INFO 04-09 02:06:20 [__init__.py:239] Platform plugin ascend is activated
INFO 04-09 02:06:20 [__init__.py:44] Available plugins for group vllm.platform_plugins:
INFO 04-09 02:06:20 [__init__.py:46] - ascend -> vllm_ascend:register
INFO 04-09 02:06:20 [__init__.py:49] All plugins in this group will be loaded. Set `VLLM_PLUGINS` to control which plugins to load.
INFO 04-09 02:06:20 [__init__.py:239] Platform plugin ascend is activated
INFO 04-09 02:06:22 [__init__.py:44] Available plugins for group vllm.platform_plugins:
INFO 04-09 02:06:22 [__init__.py:46] - ascend -> vllm_ascend:register
INFO 04-09 02:06:22 [__init__.py:49] All plugins in this group will be loaded. Set `VLLM_PLUGINS` to control which plugins to load.
INFO 04-09 02:06:22 [__init__.py:239] Platform plugin ascend is activated
INFO 04-09 02:06:22 [__init__.py:44] Available plugins for group vllm.platform_plugins:
INFO 04-09 02:06:22 [__init__.py:46] - ascend -> vllm_ascend:register
INFO 04-09 02:06:22 [__init__.py:49] All plugins in this group will be loaded. Set `VLLM_PLUGINS` to control which plugins to load.
INFO 04-09 02:06:22 [__init__.py:239] Platform plugin ascend is activated
WARNING 04-09 02:06:29 [interface.py:657] Current platform  does not have '_enum' attribute.
WARNING 04-09 02:06:29 [interface.py:657] Current platform  does not have '_enum' attribute.
INFO 04-09 02:06:30 [__init__.py:110] Registered model loader `<class 'vllm_ascend.model_loader.netloader.netloader.ModelNetLoaderElastic'>` with load format `netloader`
INFO 04-09 02:06:30 [__init__.py:110] Registered model loader `<class 'vllm_ascend.model_loader.rfork.rfork_loader.RForkModelLoader'>` with load format `rfork`
INFO 04-09 02:06:31 [__init__.py:110] Registered model loader `<class 'vllm_ascend.model_loader.netloader.netloader.ModelNetLoaderElastic'>` with load format `netloader`
INFO 04-09 02:06:31 [__init__.py:110] Registered model loader `<class 'vllm_ascend.model_loader.rfork.rfork_loader.RForkModelLoader'>` with load format `rfork`
INFO 04-09 02:06:32 [__init__.py:110] Registered model loader `<class 'vllm_ascend.model_loader.netloader.netloader.ModelNetLoaderElastic'>` with load format `netloader`
INFO 04-09 02:06:32 [__init__.py:110] Registered model loader `<class 'vllm_ascend.model_loader.rfork.rfork_loader.RForkModelLoader'>` with load format `rfork`
INFO 04-09 02:06:32 [__init__.py:110] Registered model loader `<class 'vllm_ascend.model_loader.netloader.netloader.ModelNetLoaderElastic'>` with load format `netloader`
INFO 04-09 02:06:32 [__init__.py:110] Registered model loader `<class 'vllm_ascend.model_loader.rfork.rfork_loader.RForkModelLoader'>` with load format `rfork`
INFO 04-09 02:06:35 [ascend_config.py:425] Dynamic EPLB is False
INFO 04-09 02:06:35 [ascend_config.py:426] The number of redundant experts is 0
INFO 04-09 02:06:35 [ascend_config.py:425] Dynamic EPLB is False
INFO 04-09 02:06:35 [ascend_config.py:426] The number of redundant experts is 0
INFO 04-09 02:06:36 [ascend_config.py:425] Dynamic EPLB is False
INFO 04-09 02:06:36 [ascend_config.py:426] The number of redundant experts is 0
INFO 04-09 02:06:36 [ascend_config.py:425] Dynamic EPLB is False
INFO 04-09 02:06:36 [ascend_config.py:426] The number of redundant experts is 0
ERROR 04-09 02:06:36 [multiproc_executor.py:852] WorkerProc failed to start.
ERROR 04-09 02:06:36 [multiproc_executor.py:852] Traceback (most recent call last):
ERROR 04-09 02:06:36 [multiproc_executor.py:852]   File "/data/kj1/default/fw2/80383696/vllm/vllm-0.18.0/vllm/v1/executor/multiproc_executor.py", line 821, in worker_main
ERROR 04-09 02:06:36 [multiproc_executor.py:852]     worker = WorkerProc(*args, **kwargs)
ERROR 04-09 02:06:36 [multiproc_executor.py:852]              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR 04-09 02:06:36 [multiproc_executor.py:852]   File "/data/kj1/default/fw2/80383696/vllm/vllm-0.18.0/vllm/tracing/otel.py", line 178, in sync_wrapper
ERROR 04-09 02:06:36 [multiproc_executor.py:852]     return func(*args, **kwargs)
ERROR 04-09 02:06:36 [multiproc_executor.py:852]            ^^^^^^^^^^^^^^^^^^^^^
ERROR 04-09 02:06:36 [multiproc_executor.py:852]   File "/data/kj1/default/fw2/80383696/vllm/vllm-0.18.0/vllm/v1/executor/multiproc_executor.py", line 593, in __init__
ERROR 04-09 02:06:36 [multiproc_executor.py:852]     wrapper.init_worker(all_kwargs)
ERROR 04-09 02:06:36 [multiproc_executor.py:852]   File "/data/kj1/default/fw2/80383696/vllm/vllm-0.18.0/vllm/tracing/otel.py", line 178, in sync_wrapper
ERROR 04-09 02:06:36 [multiproc_executor.py:852]     return func(*args, **kwargs)
ERROR 04-09 02:06:36 [multiproc_executor.py:852]            ^^^^^^^^^^^^^^^^^^^^^
ERROR 04-09 02:06:36 [multiproc_executor.py:852]   File "/data/kj1/default/fw2/80383696/vllm/vllm-0.18.0/vllm/v1/worker/worker_base.py", line 300, in init_worker
ERROR 04-09 02:06:36 [multiproc_executor.py:852]     self.worker = worker_class(**kwargs)
ERROR 04-09 02:06:36 [multiproc_executor.py:852]                   ^^^^^^^^^^^^^^^^^^^^^^
ERROR 04-09 02:06:36 [multiproc_executor.py:852]   File "/data/kj1/default/fw2/80383696/Qwen3-Omni/vllmomni/lib/python3.11/site-packages/vllm_omni/worker/mixins.py", line 10, in __init__
ERROR 04-09 02:06:36 [multiproc_executor.py:852]     super().__init__(*args, **kwargs)
ERROR 04-09 02:06:36 [multiproc_executor.py:852]   File "/data/kj1/default/fw2/80383696/Qwen3-Omni/vllmomni/lib/python3.11/site-packages/vllm_omni/platforms/npu/worker/base.py", line 19, in __init__
ERROR 04-09 02:06:36 [multiproc_executor.py:852]     super().__init__(*args, **kwargs)
ERROR 04-09 02:06:36 [multiproc_executor.py:852]   File "/data/kj1/default/fw2/80383696/Qwen3-Omni/vllmomni/lib/python3.11/site-packages/vllm_ascend/worker/worker.py", line 109, in __init__
ERROR 04-09 02:06:36 [multiproc_executor.py:852]     check_ascend_device_type()
ERROR 04-09 02:06:36 [multiproc_executor.py:852]   File "/data/kj1/default/fw2/80383696/Qwen3-Omni/vllmomni/lib/python3.11/site-packages/vllm_ascend/utils.py", line 723, in check_ascend_device_type
ERROR 04-09 02:06:36 [multiproc_executor.py:852]     soc_version = torch_npu.npu.get_soc_version()
ERROR 04-09 02:06:36 [multiproc_executor.py:852]                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR 04-09 02:06:36 [multiproc_executor.py:852]   File "/data/kj1/default/fw2/80383696/Qwen3-Omni/vllmomni/lib/python3.11/site-packages/torch_npu/npu/_backends.py", line 97, in get_soc_version
ERROR 04-09 02:06:36 [multiproc_executor.py:852]     torch_npu.npu._lazy_init()
ERROR 04-09 02:06:36 [multiproc_executor.py:852]   File "/data/kj1/default/fw2/80383696/Qwen3-Omni/vllmomni/lib/python3.11/site-packages/torch_npu/npu/__init__.py", line 255, in _lazy_init
ERROR 04-09 02:06:36 [multiproc_executor.py:852]     torch_npu._C._npu_init()
ERROR 04-09 02:06:36 [multiproc_executor.py:852] RuntimeError: Initialize:build/CMakeFiles/torch_npu.dir/compiler_depend.ts:134 NPU function error: aclInit, error code is 107001
ERROR 04-09 02:06:36 [multiproc_executor.py:852] [ERROR] 2026-04-09-02:06:36 (PID:24929, Device:0, RankID:-1) ERR00100 PTA call acl api failed
ERROR 04-09 02:06:36 [multiproc_executor.py:852] [Error]: Invalid device ID.
ERROR 04-09 02:06:36 [multiproc_executor.py:852]         Check whether the device ID is valid.
ERROR 04-09 02:06:36 [multiproc_executor.py:852] [PID: 24929] 2026-04-09-02:06:36.500.406 Invalid_Argument(EE1001): The argument is invalid.Reason: rtGetDevMsg execution failed, the context is a null pointer.
ERROR 04-09 02:06:36 [multiproc_executor.py:852]         Solution: 1.Check the input parameter range of the function. 2.Check the function invocation relationship.
ERROR 04-09 02:06:36 [multiproc_executor.py:852]         TraceBack (most recent call last):
ERROR 04-09 02:06:36 [multiproc_executor.py:852]         input error deviceId:0 is err:0x7010003[FUNC:SetDefaultDeviceId][FILE:api_error.cc][LINE:5556]
ERROR 04-09 02:06:36 [multiproc_executor.py:852]         rtSetDefaultDeviceId execution failed, reason=device id error[FUNC:FuncErrorReason][FILE:error_message_manage.cc][LINE:61]
ERROR 04-09 02:06:36 [multiproc_executor.py:852]         set default device id failed, ret:107001[FUNC:ReportCallError][FILE:log_inner.cpp][LINE:148]
ERROR 04-09 02:06:36 [multiproc_executor.py:852]         [Process][DefaultDevice]process HandleDefaultDevice failed[FUNC:ReportInnerError][FILE:log_inner.cpp][LINE:132]
ERROR 04-09 02:06:36 [multiproc_executor.py:852]         ctx is NULL![FUNC:GetDevErrMsg][FILE:api_impl.cc][LINE:6338]
ERROR 04-09 02:06:36 [multiproc_executor.py:852]         The argument is invalid.Reason: rtGetDevMsg execution failed, the context is a null pointer.
ERROR 04-09 02:06:36 [multiproc_executor.py:852] 
ERROR 04-09 02:06:36 [multiproc_executor.py:852] WorkerProc failed to start.
ERROR 04-09 02:06:36 [multiproc_executor.py:852] Traceback (most recent call last):
ERROR 04-09 02:06:36 [multiproc_executor.py:852]   File "/data/kj1/default/fw2/80383696/vllm/vllm-0.18.0/vllm/v1/executor/multiproc_executor.py", line 821, in worker_main
ERROR 04-09 02:06:36 [multiproc_executor.py:852]     worker = WorkerProc(*args, **kwargs)
ERROR 04-09 02:06:36 [multiproc_executor.py:852]              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR 04-09 02:06:36 [multiproc_executor.py:852]   File "/data/kj1/default/fw2/80383696/vllm/vllm-0.18.0/vllm/tracing/otel.py", line 178, in sync_wrapper
ERROR 04-09 02:06:36 [multiproc_executor.py:852]     return func(*args, **kwargs)
ERROR 04-09 02:06:36 [multiproc_executor.py:852]            ^^^^^^^^^^^^^^^^^^^^^
ERROR 04-09 02:06:36 [multiproc_executor.py:852]   File "/data/kj1/default/fw2/80383696/vllm/vllm-0.18.0/vllm/v1/executor/multiproc_executor.py", line 593, in __init__
ERROR 04-09 02:06:36 [multiproc_executor.py:852]     wrapper.init_worker(all_kwargs)
ERROR 04-09 02:06:36 [multiproc_executor.py:852]   File "/data/kj1/default/fw2/80383696/vllm/vllm-0.18.0/vllm/tracing/otel.py", line 178, in sync_wrapper
ERROR 04-09 02:06:36 [multiproc_executor.py:852]     return func(*args, **kwargs)
ERROR 04-09 02:06:36 [multiproc_executor.py:852]            ^^^^^^^^^^^^^^^^^^^^^
ERROR 04-09 02:06:36 [multiproc_executor.py:852]   File "/data/kj1/default/fw2/80383696/vllm/vllm-0.18.0/vllm/v1/worker/worker_base.py", line 300, in init_worker
ERROR 04-09 02:06:36 [multiproc_executor.py:852]     self.worker = worker_class(**kwargs)
ERROR 04-09 02:06:36 [multiproc_executor.py:852]                   ^^^^^^^^^^^^^^^^^^^^^^
ERROR 04-09 02:06:36 [multiproc_executor.py:852]   File "/data/kj1/default/fw2/80383696/Qwen3-Omni/vllmomni/lib/python3.11/site-packages/vllm_omni/worker/mixins.py", line 10, in __init__
ERROR 04-09 02:06:36 [multiproc_executor.py:852]     super().__init__(*args, **kwargs)
ERROR 04-09 02:06:36 [multiproc_executor.py:852]   File "/data/kj1/default/fw2/80383696/Qwen3-Omni/vllmomni/lib/python3.11/site-packages/vllm_omni/platforms/npu/worker/base.py", line 19, in __init__
ERROR 04-09 02:06:36 [multiproc_executor.py:852]     super().__init__(*args, **kwargs)
ERROR 04-09 02:06:36 [multiproc_executor.py:852]   File "/data/kj1/default/fw2/80383696/Qwen3-Omni/vllmomni/lib/python3.11/site-packages/vllm_ascend/worker/worker.py", line 109, in __init__
ERROR 04-09 02:06:36 [multiproc_executor.py:852]     check_ascend_device_type()
ERROR 04-09 02:06:36 [multiproc_executor.py:852]   File "/data/kj1/default/fw2/80383696/Qwen3-Omni/vllmomni/lib/python3.11/site-packages/vllm_ascend/utils.py", line 723, in check_ascend_device_type
ERROR 04-09 02:06:36 [multiproc_executor.py:852]     soc_version = torch_npu.npu.get_soc_version()
ERROR 04-09 02:06:36 [multiproc_executor.py:852]                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ERROR 04-09 02:06:36 [multiproc_executor.py:852]   File "/data/kj1/default/fw2/80383696/Qwen3-Omni/vllmomni/lib/python3.11/site-packages/torch_npu/npu/_backends.py", line 97, in get_soc_version
ERROR 04-09 02:06:36 [multiproc_executor.py:852]     torch_npu.npu._lazy_init()
ERROR 04-09 02:06:36 [multiproc_executor.py:852]   File "/data/kj1/default/fw2/80383696/Qwen3-Omni/vllmomni/lib/python3.11/site-packages/torch_npu/npu/__init__.py", line 255, in _lazy_init
ERROR 04-09 02:06:36 [multiproc_executor.py:852]     torch_npu._C._npu_init()
ERROR 04-09 02:06:36 [multiproc_executor.py:852] RuntimeError: Initialize:build/CMakeFiles/torch_npu.dir/compiler_depend.ts:134 NPU function error: aclInit, error code is 107001
ERROR 04-09 02:06:36 [multiproc_executor.py:852] [ERROR] 2026-04-09-02:06:36 (PID:24930, Device:0, RankID:-1) ERR00100 PTA call acl api failed
ERROR 04-09 02:06:36 [multiproc_executor.py:852] [Error]: Invalid device ID.
ERROR 04-09 02:06:36 [multiproc_executor.py:852]         Check whether the device ID is valid.
ERROR 04-09 02:06:36 [multiproc_executor.py:852] [PID: 24930] 2026-04-09-02:06:36.512.995 Invalid_Argument(EE1001): The argument is invalid.Reason: rtGetDevMsg execution failed, the context is a null pointer.
ERROR 04-09 02:06:36 [multiproc_executor.py:852]         Solution: 1.Check the input parameter range of the function. 2.Check the function invocation relationship.
ERROR 04-09 02:06:36 [multiproc_executor.py:852]         TraceBack (most recent call last):
ERROR 04-09 02:06:36 [multiproc_executor.py:852]         input error deviceId:0 is err:0x7010003[FUNC:SetDefaultDeviceId][FILE:api_error.cc][LINE:5556]
ERROR 04-09 02:06:36 [multiproc_executor.py:852]         rtSetDefaultDeviceId execution failed, reason=device id error[FUNC:FuncErrorReason][FILE:error_message_manage.cc][LINE:61]
ERROR 04-09 02:06:36 [multiproc_executor.py:852]         set default device id failed, ret:107001[FUNC:ReportCallError][FILE:log_inner.cpp][LINE:148]
ERROR 04-09 02:06:36 [multiproc_executor.py:852]         [Process][DefaultDevice]process HandleDefaultDevice failed[FUNC:ReportInnerError][FILE:log_inner.cpp][LINE:132]
ERROR 04-09 02:06:36 [multiproc_executor.py:852]         ctx is NULL![FUNC:GetDevErrMsg][FILE:api_impl.cc][LINE:6338]
ERROR 04-09 02:06:36 [multiproc_executor.py:852]         The argument is invalid.Reason: rtGetDevMsg execution failed, the context is a null pointer.
ERROR 04-09 02:06:36 [multiproc_executor.py:852] 
(Worker pid=24938) INFO 04-09 02:06:39 [parallel_state.py:1395] world_size=2 rank=0 local_rank=0 distributed_init_method=tcp://127.0.0.1:53497 backend=hccl
(Worker pid=24939) INFO 04-09 02:06:39 [parallel_state.py:1395] world_size=2 rank=1 local_rank=1 distributed_init_method=tcp://127.0.0.1:53497 backend=hccl
[Gloo] Rank 0 is connected to 1 peer ranks. Expected number of connected peer ranks is : 1
[Gloo] Rank 1 is connected to 1 peer ranks. Expected number of connected peer ranks is : 1
[Gloo] Rank 1 is connected to 1 peer ranks. Expected number of connected peer ranks is : 1
[Gloo] Rank 0 is connected to 1 peer ranks. Expected number of connected peer ranks is : 1
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 1 peer ranks. Expected number of connected peer ranks is : 1
[Gloo] Rank 1 is connected to 1 peer ranks. Expected number of connected peer ranks is : 1
(Worker pid=24938) INFO 04-09 02:06:39 [parallel_state.py:1717] rank 0 in world size 2 is assigned as DP rank 0, PP rank 0, PCP rank 0, TP rank 0, EP rank 0, EPLB rank N/A
(Worker pid=24939) INFO 04-09 02:06:39 [parallel_state.py:1717] rank 1 in world size 2 is assigned as DP rank 0, PP rank 0, PCP rank 0, TP rank 1, EP rank 1, EPLB rank N/A
[Gloo] Rank 0 is connected to 1 peer ranks. Expected number of connected peer ranks is : 1
[Gloo] Rank 1 is connected to 1 peer ranks. Expected number of connected peer ranks is : 1
(EngineCore pid=24805) ERROR 04-09 02:06:40 [core.py:1099] EngineCore failed to start.
(EngineCore pid=24805) ERROR 04-09 02:06:40 [core.py:1099] Traceback (most recent call last):
(EngineCore pid=24805) ERROR 04-09 02:06:40 [core.py:1099]   File "/data/kj1/default/fw2/80383696/vllm/vllm-0.18.0/vllm/v1/engine/core.py", line 1073, in run_engine_core
(EngineCore pid=24805) ERROR 04-09 02:06:40 [core.py:1099]     engine_core = EngineCoreProc(*args, engine_index=dp_rank, **kwargs)
(EngineCore pid=24805) ERROR 04-09 02:06:40 [core.py:1099]                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(EngineCore pid=24805) ERROR 04-09 02:06:40 [core.py:1099]   File "/data/kj1/default/fw2/80383696/vllm/vllm-0.18.0/vllm/tracing/otel.py", line 178, in sync_wrapper
(EngineCore pid=24805) ERROR 04-09 02:06:40 [core.py:1099]     return func(*args, **kwargs)
(EngineCore pid=24805) ERROR 04-09 02:06:40 [core.py:1099]            ^^^^^^^^^^^^^^^^^^^^^
(EngineCore pid=24805) ERROR 04-09 02:06:40 [core.py:1099]   File "/data/kj1/default/fw2/80383696/vllm/vllm-0.18.0/vllm/v1/engine/core.py", line 839, in __init__
(EngineCore pid=24805) ERROR 04-09 02:06:40 [core.py:1099]     super().__init__(
(EngineCore pid=24805) ERROR 04-09 02:06:40 [core.py:1099]   File "/data/kj1/default/fw2/80383696/vllm/vllm-0.18.0/vllm/v1/engine/core.py", line 112, in __init__
(EngineCore pid=24805) ERROR 04-09 02:06:40 [core.py:1099]     self.model_executor = executor_class(vllm_config)
(EngineCore pid=24805) ERROR 04-09 02:06:40 [core.py:1099]                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
(EngineCore pid=24805) ERROR 04-09 02:06:40 [core.py:1099]   File "/data/kj1/default/fw2/80383696/vllm/vllm-0.18.0/vllm/v1/executor/multiproc_executor.py", line 101, in __init__
(EngineCore pid=24805) ERROR 04-09 02:06:40 [core.py:1099]     super().__init__(vllm_config)
(EngineCore pid=24805) ERROR 04-09 02:06:40 [core.py:1099]   File "/data/kj1/default/fw2/80383696/vllm/vllm-0.18.0/vllm/tracing/otel.py", line 178, in sync_wrapper
(EngineCore pid=24805) ERROR 04-09 02:06:40 [core.py:1099]     return func(*args, **kwargs)
(EngineCore pid=24805) ERROR 04-09 02:06:40 [core.py:1099]            ^^^^^^^^^^^^^^^^^^^^^
(EngineCore pid=24805) ERROR 04-09 02:06:40 [core.py:1099]   File "/data/kj1/default/fw2/80383696/vllm/vllm-0.18.0/vllm/v1/executor/abstract.py", line 103, in __init__
(EngineCore pid=24805) ERROR 04-09 02:06:40 [core.py:1099]     self._init_executor()
(EngineCore pid=24805) ERROR 04-09 02:06:40 [core.py:1099]   File "/data/kj1/default/fw2/80383696/vllm/vllm-0.18.0/vllm/v1/executor/multiproc_executor.py", line 190, in _init_executor
(EngineCore pid=24805) ERROR 04-09 02:06:40 [core.py:1099]     self.workers = WorkerProc.wait_for_ready(unready_workers)
(EngineCore pid=24805) ERROR 04-09 02:06:40 [core.py:1099]                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(EngineCore pid=24805) ERROR 04-09 02:06:40 [core.py:1099]   File "/data/kj1/default/fw2/80383696/vllm/vllm-0.18.0/vllm/v1/executor/multiproc_executor.py", line 731, in wait_for_ready
(EngineCore pid=24805) ERROR 04-09 02:06:40 [core.py:1099]     raise e from None
(EngineCore pid=24805) ERROR 04-09 02:06:40 [core.py:1099] Exception: WorkerProc initialization failed due to an exception in a background process. See stack trace for root cause.
(EngineCore pid=24805) Process EngineCore:
(EngineCore pid=24805) Traceback (most recent call last):
(EngineCore pid=24805)   File "/usr/local/python3.11.14/lib/python3.11/multiprocessing/process.py", line 314, in _bootstrap
(EngineCore pid=24805)     self.run()
(EngineCore pid=24805)   File "/usr/local/python3.11.14/lib/python3.11/multiprocessing/process.py", line 108, in run
(EngineCore pid=24805)     self._target(*self._args, **self._kwargs)
(EngineCore pid=24805)   File "/data/kj1/default/fw2/80383696/vllm/vllm-0.18.0/vllm/v1/engine/core.py", line 1103, in run_engine_core
(EngineCore pid=24805)     raise e
(EngineCore pid=24805)   File "/data/kj1/default/fw2/80383696/vllm/vllm-0.18.0/vllm/v1/engine/core.py", line 1073, in run_engine_core
(EngineCore pid=24805)     engine_core = EngineCoreProc(*args, engine_index=dp_rank, **kwargs)
(EngineCore pid=24805)                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(EngineCore pid=24805)   File "/data/kj1/default/fw2/80383696/vllm/vllm-0.18.0/vllm/tracing/otel.py", line 178, in sync_wrapper
(EngineCore pid=24805)     return func(*args, **kwargs)
(EngineCore pid=24805)            ^^^^^^^^^^^^^^^^^^^^^
(EngineCore pid=24805)   File "/data/kj1/default/fw2/80383696/vllm/vllm-0.18.0/vllm/v1/engine/core.py", line 839, in __init__
(EngineCore pid=24805)     super().__init__(
(EngineCore pid=24805)   File "/data/kj1/default/fw2/80383696/vllm/vllm-0.18.0/vllm/v1/engine/core.py", line 112, in __init__
(EngineCore pid=24805)     self.model_executor = executor_class(vllm_config)
(EngineCore pid=24805)                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
(EngineCore pid=24805)   File "/data/kj1/default/fw2/80383696/vllm/vllm-0.18.0/vllm/v1/executor/multiproc_executor.py", line 101, in __init__
(EngineCore pid=24805)     super().__init__(vllm_config)
(EngineCore pid=24805)   File "/data/kj1/default/fw2/80383696/vllm/vllm-0.18.0/vllm/tracing/otel.py", line 178, in sync_wrapper
(EngineCore pid=24805)     return func(*args, **kwargs)
(EngineCore pid=24805)            ^^^^^^^^^^^^^^^^^^^^^
(EngineCore pid=24805)   File "/data/kj1/default/fw2/80383696/vllm/vllm-0.18.0/vllm/v1/executor/abstract.py", line 103, in __init__
(EngineCore pid=24805)     self._init_executor()
(EngineCore pid=24805)   File "/data/kj1/default/fw2/80383696/vllm/vllm-0.18.0/vllm/v1/executor/multiproc_executor.py", line 190, in _init_executor
(EngineCore pid=24805)     self.workers = WorkerProc.wait_for_ready(unready_workers)
(EngineCore pid=24805)                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
(EngineCore pid=24805)   File "/data/kj1/default/fw2/80383696/vllm/vllm-0.18.0/vllm/v1/executor/multiproc_executor.py", line 731, in wait_for_ready
(EngineCore pid=24805)     raise e from None
(EngineCore pid=24805) Exception: WorkerProc initialization failed due to an exception in a background process. See stack trace for root cause.
(Worker pid=24939) INFO 04-09 02:06:40 [cpu_binding.py:320] [cpu_bind_mode] mode=topo_affinity rank=1 visible_npus=[0, 1]
...stage2的错误信息是一样的
```
但是在相同的环境下Qwen3-Omni-30B-A3B-Thinking使用vllm就能够正常部署

**Comment by MengqingCao** [comment]
@gcanlin It seems an issue with vllm-omni, plz take a look at this.

**Comment by gcanlin** [comment]
Root cause below:

```
ERROR 04-09 02:06:36 [multiproc_executor.py:852] [Error]: Invalid device ID.
ERROR 04-09 02:06:36 [multiproc_executor.py:852]         Check whether the device ID is valid.
```

Please use `ASCEND_RT_VISIBLE_DEVICES` env var to make sure vllm-omni access to your device.

**Comment by gcanlin** [comment]
Could you use 

```
vllm serve /data/Qwen/Qwen3-Omni-30B-A3B-Instruct/master/Qwen_Qwen3-Omni-30B-A3B-Instruct_master_20250928_02/ --omni
```

instead of adding `--tensor-parallel-size 2`?

vLLM Omni has multi-stage config and recommend users to config the engine args in yaml file. We have created the default config. You can check it in `vllm_omni/platforms/npu/stage_configs`.

**Comment by ly13836333251-stack** [comment]
感谢您的回复，根据您的指引，上述问题已经解决。

步骤如下：
1、通过ASCEND_RT_VISIBLE_DEVICES设置可见设备ID
```
export ASCEND_RT_VISIBLE_DEVICES=0,1
```

2、复制vllm_omni/platforms/npu/stage_configs/qwen3_omni_moe.yaml到某个文件夹，并修改三个stage对应的devices配置

3、通过如下命令启动服务：
```
vllm serve /data/Qwen/Qwen3-Omni-30B-A3B-Instruct/master/Qwen_Qwen3-Omni-30B-A3B-Instruct_master_20250928_02/ --omni --stage-configs-path /path/to/stage_config.yaml
```
