### ISSUE TITLE
[Bug]: Service crashes with `FULL_DECODE_ONLY` + MTP speculative decoding: `rtMemcpy` fails in ACL Graph replay (error code 107030)

### ISSUE THREAD

**Issue by lingxling** [vllm-project/vllm-ascend#8587]
### Your current environment

<details>
<summary>The output of `python collect_env.py`</summary>

```text
Collecting environment information...
PyTorch version: 2.8.0+cpu
Is debug build: False

OS: Ubuntu 22.04.5 LTS (aarch64)
GCC version: (Ubuntu 11.4.0-1ubuntu1~22.04.2) 11.4.0
Clang version: 15.0.7
CMake version: version 4.2.1
Libc version: glibc-2.35

Python version: 3.11.14 (main, Jan 19 2026, 07:36:53) [GCC 11.4.0] (64-bit runtime)
Python platform: Linux-5.15.0-119-generic-aarch64-with-glibc2.35

CPU:
Architecture:                         aarch64
CPU op-mode(s):                       64-bit
Byte Order:                           Little Endian
CPU(s):                               192
On-line CPU(s) list:                  0-191
Vendor ID:                            HiSilicon
Model name:                           Kunpeng-920
Model:                                0
Thread(s) per core:                   1
Core(s) per socket:                   48
Socket(s):                            4
Stepping:                             0x1
Frequency boost:                      disabled
CPU max MHz:                          2600.0000
CPU min MHz:                          200.0000
BogoMIPS:                             200.00
Flags:                                fp asimd evtstrm aes pmull sha1 sha2 crc32 atomics fphp asimdhp cpuid asimdrdm jscvt fcma dcpop asimddp asimdfhm ssbs
L1d cache:                            12 MiB (192 instances)
L1i cache:                            12 MiB (192 instances)
L2 cache:                             96 MiB (192 instances)
L3 cache:                             192 MiB (8 instances)
NUMA node(s):                         8
NUMA node0 CPU(s):                    0-23
NUMA node1 CPU(s):                    24-47
NUMA node2 CPU(s):                    48-71
NUMA node3 CPU(s):                    72-95
NUMA node4 CPU(s):                    96-119
NUMA node5 CPU(s):                    120-143
NUMA node6 CPU(s):                    144-167
NUMA node7 CPU(s):                    168-191
Vulnerability Gather data sampling:   Not affected
Vulnerability Itlb multihit:          Not affected
Vulnerability L1tf:                   Not affected
Vulnerability Mds:                    Not affected
Vulnerability Meltdown:               Not affected
Vulnerability Mmio stale data:        Not affected
Vulnerability Reg file data sampling: Not affected
Vulnerability Retbleed:               Not affected
Vulnerability Spec rstack overflow:   Not affected
Vulnerability Spec store bypass:      Mitigation; Speculative Store Bypass disabled via prctl
Vulnerability Spectre v1:             Mitigation; __user pointer sanitization
Vulnerability Spectre v2:             Not affected
Vulnerability Srbds:                  Not affected
Vulnerability Tsx async abort:        Not affected

Versions of relevant libraries:
[pip3] numpy==1.26.4
[pip3] pyzmq==27.1.0
[pip3] torch==2.8.0+cpu
[pip3] torch_npu==2.8.0.post2
[pip3] torchvision==0.23.0
[pip3] transformers==4.57.6
[pip3] triton-ascend==3.2.0
[conda] Could not collect
vLLM Version: 0.13.0
vLLM Ascend Version: 0.13.0

ENV Variables:
ASCEND_TOOLKIT_LATEST_HOME=/usr/local/Ascend/ascend-toolkit/latest
ATB_OPSRUNNER_KERNEL_CACHE_LOCAL_COUNT=1
ATB_STREAM_SYNC_EVERY_RUNNER_ENABLE=0
ATB_STREAM_SYNC_EVERY_KERNEL_ENABLE=0
ATB_OPSRUNNER_KERNEL_CACHE_GLOABL_COUNT=5
ATB_HOME_PATH=/usr/local/Ascend/nnal/atb/latest/atb/cxx_abi_1
ASCEND_TOOLKIT_HOME=/usr/local/Ascend/cann-8.5.0
ATB_COMPARE_TILING_EVERY_KERNEL=0
ASCEND_OPP_PATH=/usr/local/Ascend/cann-8.5.0/opp
LD_LIBRARY_PATH=/usr/local/Ascend/nnal/atb/latest/atb/cxx_abi_1/lib:/usr/local/Ascend/nnal/atb/latest/atb/cxx_abi_1/examples:/usr/local/Ascend/nnal/atb/latest/atb/cxx_abi_1/tests/atbopstest:/usr/local/Ascend/cann-8.5.0/lib64:/usr/local/Ascend/cann-8.5.0/lib64/plugin/opskernel:/usr/local/Ascend/cann-8.5.0/lib64/plugin/nnengine:/usr/local/Ascend/cann-8.5.0/opp/built-in/op_impl/ai_core/tbe/op_tiling/lib/linux/aarch64:/usr/local/Ascend/cann-8.5.0/tools/aml/lib64:/usr/local/Ascend/cann-8.5.0/tools/aml/lib64/plugin:/usr/local/Ascend/driver/lib64:/usr/local/Ascend/driver/lib64/common:/usr/local/Ascend/driver/lib64/driver:/usr/local/Ascend/nnal/atb/latest/atb/cxx_abi_1/lib:/usr/local/Ascend/nnal/atb/latest/atb/cxx_abi_1/examples:/usr/local/Ascend/nnal/atb/latest/atb/cxx_abi_1/tests/atbopstest:/usr/local/Ascend/ascend-toolkit/latest/tools/aml/lib64:/usr/local/Ascend/ascend-toolkit/latest/tools/aml/lib64/plugin:/usr/local/Ascend/ascend-toolkit/latest/lib64:/usr/local/Ascend/ascend-toolkit/latest/lib64/plugin/opskernel:/usr/local/Ascend/ascend-toolkit/latest/lib64/plugin/nnengine:/usr/local/Ascend/ascend-toolkit/latest/opp/built-in/op_impl/ai_core/tbe/op_tiling:/usr/local/Ascend/driver/lib64:/usr/local/Ascend/driver/lib64/common/:/usr/local/Ascend/driver/lib64/driver/:/usr/local/python3.11.14/lib:
ASCEND_AICPU_PATH=/usr/local/Ascend/cann-8.5.0
ATB_STREAM_SYNC_EVERY_OPERATION_ENABLE=0
ASCEND_HOME_PATH=/usr/local/Ascend/cann-8.5.0
ATB_MATMUL_SHUFFLE_K_ENABLE=1
ATB_WORKSPACE_MEM_ALLOC_ALG_TYPE=1
ATB_SHARE_MEMORY_NAME_SUFFIX=
TORCH_DEVICE_BACKEND_AUTOLOAD=1
PYTORCH_NVML_BASED_CUDA_CHECK=1
TORCHINDUCTOR_COMPILE_THREADS=1


NPU:
+------------------------------------------------------------------------------------------------+
| npu-smi 25.5.0                   Version: 25.5.0                                               |
+---------------------------+---------------+----------------------------------------------------+
| NPU   Name                | Health        | Power(W)    Temp(C)           Hugepages-Usage(page)|
| Chip                      | Bus-Id        | AICore(%)   Memory-Usage(MB)  HBM-Usage(MB)        |
+===========================+===============+====================================================+
| 0     910B2               | OK            | 99.8        41                0    / 0             |
| 0                         | 0000:C1:00.0  | 0           0    / 0          3457 / 65536         |
+===========================+===============+====================================================+
| 1     910B2               | OK            | 93.9        40                0    / 0             |
| 0                         | 0000:C2:00.0  | 0           0    / 0          3449 / 65536         |
+===========================+===============+====================================================+
| 2     910B2               | OK            | 91.4        40                0    / 0             |
| 0                         | 0000:81:00.0  | 0           0    / 0          3448 / 65536         |
+===========================+===============+====================================================+
| 3     910B2               | OK            | 96.5        38                0    / 0             |
| 0                         | 0000:82:00.0  | 0           0    / 0          3448 / 65536         |
+===========================+===============+====================================================+
| 4     910B2               | OK            | 94.8        45                0    / 0             |
| 0                         | 0000:01:00.0  | 0           0    / 0          3454 / 65536         |
+===========================+===============+====================================================+
| 5     910B2               | OK            | 95.3        45                0    / 0             |
| 0                         | 0000:02:00.0  | 0           0    / 0          3448 / 65536         |
+===========================+===============+====================================================+
| 6     910B2               | OK            | 97.5        43                0    / 0             |
| 0                         | 0000:41:00.0  | 0           0    / 0          3448 / 65536         |
+===========================+===============+====================================================+
| 7     910B2               | OK            | 96.6        45                0    / 0             |
| 0                         | 0000:42:00.0  | 0           0    / 0          3448 / 65536         |
+===========================+===============+====================================================+
+---------------------------+---------------+----------------------------------------------------+
| NPU     Chip              | Process id    | Process name             | Process memory(MB)      |
+===========================+===============+====================================================+
| No running processes found in NPU 0                                                            |
+===========================+===============+====================================================+
| No running processes found in NPU 1                                                            |
+===========================+===============+====================================================+
| No running processes found in NPU 2                                                            |
+===========================+===============+====================================================+
| No running processes found in NPU 3                                                            |
+===========================+===============+====================================================+
| No running processes found in NPU 4                                                            |
+===========================+===============+====================================================+
| No running processes found in NPU 5                                                            |
+===========================+===============+====================================================+
| No running processes found in NPU 6                                                            |
+===========================+===============+====================================================+
| No running processes found in NPU 7                                                            |
+===========================+===============+====================================================+

CANN:
package_name=Ascend-cann-toolkit
version=8.5.0
innerversion=V100R001C25SPC001B232
compatible_version=[V100R001C15],[V100R001C18],[V100R001C19],[V100R001C20],[V100R001C21],[V100R001C23]
arch=aarch64
os=linux
path=/usr/local/Ascend/cann-8.5.0
```

</details>

### 🐛 Describe the bug

**Describe the bug**

When serving DeepSeek-V3.2 with `cudagraph_mode: FULL_DECODE_ONLY` and MTP speculative decoding (`method: deepseek_mtp`) on a 2-node, 16-card (Ascend 910B) deployment, the service crashes during benchmark stress testing at concurrency=4 with `Input=1024, Output=128`. All 8 worker processes on node1 (DP rank 1) crash simultaneously, and the API server starts returning HTTP 500 for all subsequent requests.

The crash is fully reproducible. Removing `--compilation-config '{"cudagraph_mode": "FULL_DECODE_ONLY"}'` eliminates the crash.

**Environment**

- **vllm-ascend version:** 0.13.0
- **vllm version:** 0.13.0
- **Hardware:** Ascend 910B × 16 (2 nodes × 8 cards)
- **Model:** DeepSeek-V3.2 w4a8 quantized (QuaRot)

**To Reproduce**

**Node 0 (master):**

```bash
export HCCL_OP_EXPANSION_MODE="AIV"
export HCCL_IF_IP=172.27.123.235
export GLOO_SOCKET_IFNAME=enp67s0f0np0
export TP_SOCKET_IFNAME=enp67s0f0np0
export HCCL_SOCKET_IFNAME=enp67s0f0np0
export OMP_PROC_BIND=false
export OMP_NUM_THREADS=10
export VLLM_USE_V1=1
export HCCL_BUFFSIZE=200
export VLLM_ASCEND_ENABLE_MLAPO=1
export PYTORCH_NPU_ALLOC_CONF=expandable_segments:True
export VLLM_ASCEND_ENABLE_FLASHCOMM1=0

vllm serve <model_path> \
  --host 0.0.0.0 --port 8077 \
  --data-parallel-size 2 --data-parallel-size-local 1 \
  --data-parallel-address 172.27.123.235 --data-parallel-rpc-port 12890 \
  --tensor-parallel-size 8 \
  --quantization ascend \
  --seed 1024 \
  --enable-expert-parallel \
  --max-num-seqs 16 --max-model-len 65536 --max-num-batched-tokens 4096 \
  --gpu-memory-utilization 0.92 \
  --no-enable-prefix-caching \
  --compilation-config '{"cudagraph_mode": "FULL_DECODE_ONLY"}' \
  --additional-config '{"layer_sharding": ["q_b_proj", "o_proj"]}' \
  --speculative-config '{"num_speculative_tokens": 3, "method": "deepseek_mtp"}'
```

**Node 1 (worker):**

```bash
# Same env vars as node0, with local_ip=172.27.123.236

vllm serve <model_path> \
  --host 0.0.0.0 --port 8077 \
  --headless \
  --data-parallel-size 2 --data-parallel-size-local 1 \
  --data-parallel-start-rank 1 \
  --data-parallel-address 172.27.123.235 --data-parallel-rpc-port 12890 \
  --tensor-parallel-size 8 \
  --quantization ascend \
  --seed 1024 \
  --enable-expert-parallel \
  --max-num-seqs 16 --max-model-len 65536 --max-num-batched-tokens 4096 \
  --gpu-memory-utilization 0.92 \
  --no-enable-prefix-caching \
  --compilation-config '{"cudagraph_mode": "FULL_DECODE_ONLY"}' \
  --additional-config '{"layer_sharding": ["q_b_proj", "o_proj"]}' \
  --speculative-config '{"num_speculative_tokens": 3, "method": "deepseek_mtp"}'
```

**Trigger:**

```bash
vllm bench serve \
  --host 172.27.123.235 --port 8077 \
  --model <model_path> \
  --input-len 1024 --output-len 128 \
  --max-concurrency 4 \
  --num-prompts 20
```

Service crashes when concurrency reaches 4 with input=1024, output=128. Concurrency 1 and 2 complete successfully.

---

**Expected behavior**

Service should run stably under all concurrency levels, or raise a clear error at startup if the configuration is unsupported.

---

**Actual behavior**

All 8 worker processes on node1 crash simultaneously during ACL Graph replay. The crash originates in MTP speculative decoding when `aclnnKvRmsNormRopeCache` performs a synchronous `rtMemcpy` inside the graph replay context, which is illegal under ACL Graph capture mode.

Root error from node1 worker logs:

```
EE9999: rtMemcpy execution failed,
reason=the current capture mode does not support this operation
synchronized memcpy failed, kind=1, runtime result=107030
The DDR address of the MTE instruction is out of range.
```

Call stack leading to the crash:

```
sample_tokens()                            # vllm_ascend/worker/worker.py
  └─ propose_draft_token_ids()             # MTP speculative decoding
       └─ drafter._propose()               # mtp_proposer.py
            └─ self.model()                # deepseek_mtp.py forward
                 └─ acl_graph.__call__()   # ACL Graph replay
                      └─ aclnnKvRmsNormRopeCache()
                           └─ rtMemcpy()   ← crash here, error code 107030
```

The error timestamp in the Ascend Runtime log (`10:08:08`) matches the ACL Graph capture phase at startup, indicating the error was recorded during warmup but only surfaces during inference execution — consistent with Ascend Runtime's deferred error reporting behavior.

---

**Additional context**

- The crash is **not triggered** at concurrency=1 or concurrency=2.
- Removing `--compilation-config '{"cudagraph_mode": "FULL_DECODE_ONLY"}'` completely eliminates the crash. Service runs stably without this flag.
- The startup log already warns: *"WARNING: You have enabled the \*full graph\* feature. This is an early experimental stage and may involve various unknown issues."* — however there is no indication at startup that this specific combination (FULL_DECODE_ONLY + MTP) is unsupported, and no error is raised until the service crashes mid-inference.
- Reproduced twice independently with identical failure mode.

**Comment by yiz-liu** [comment]
@rjg-lyh Can we try reproduce this? I don't think the copy is the root cause, since the graph is static and will not add a copy out of nowhere at run-time. More likely there's another error before that.

**Comment by lingxling** [comment]
Here are complete logs.

[deepseek-v3.2-w4a8-node0.log](https://github.com/user-attachments/files/27005321/deepseek-v3.2-w4a8-node0.log)

[deepseek-v3.2-w4a8-node1.log](https://github.com/user-attachments/files/27005323/deepseek-v3.2-w4a8-node1.log)

**Comment by yiz-liu** [comment]
@Nagisa125 Please follow up this issue.

**Comment by Nagisa125** [comment]
In the mixed configuration scenario, enabling layer_sharding causes issues. Earlier versions did not perform assertions. It is recommended to use version 0180 and disable layer_sharding at the same time to try it out. If the error still occurs, it is likely due to insufficient GPU memory. It is suggested to lower the gpu-memory-utilization and try again.

**Comment by lingxling** [comment]
> In the mixed configuration scenario, enabling layer_sharding causes issues. Earlier versions did not perform assertions. It is recommended to use version 0180 and disable layer_sharding at the same time to try it out. If the error still occurs, it is likely due to insufficient GPU memory. It is suggested to lower the gpu-memory-utilization and try again.

Thanks for the suggestion.

We have switched to v0.18.0 and disabled layer_sharding. After upgrading, the issue no longer occurs and the bug has disappeared in our environment.

We will continue monitoring it, but for now the problem appears to be resolved with v0.18.0.
