### ISSUE TITLE
[Bug]: 0.18.0rc1版本A2双机背靠背组网 GLM-5.1-W4A8 模型拉起报错(error_code:107030)

### ISSUE THREAD

**Issue by lz1z** [vllm-project/vllm-ascend#8646]
### Your current environment

<details>
<summary>The output of `python collect_env.py`</summary>

```text
Collecting environment information...
PyTorch version: 2.9.0+cpu
Is debug build: False

OS: Ubuntu 22.04.5 LTS (aarch64)
GCC version: (Ubuntu 11.4.0-1ubuntu1~22.04.3) 11.4.0
Clang version: 15.0.7
CMake version: version 4.3.1
Libc version: glibc-2.35

Python version: 3.11.14 (main, Feb 26 2026, 04:49:14) [GCC 11.4.0] (64-bit runtime)
Python platform: Linux-5.10.0-216.0.0.115.oe2203sp4.aarch64-aarch64-with-glibc2.35

CPU:
Architecture:                       aarch64
CPU op-mode(s):                     64-bit
Byte Order:                         Little Endian
CPU(s):                             192
On-line CPU(s) list:                0-191
Vendor ID:                          HiSilicon
BIOS Vendor ID:                     HiSilicon
Model name:                         Kunpeng-920
BIOS Model name:                    HUAWEI Kunpeng 920 5250
Model:                              0
Thread(s) per core:                 1
Core(s) per socket:                 48
Socket(s):                          4
Stepping:                           0x1
Frequency boost:                    disabled
CPU max MHz:                        2600.0000
CPU min MHz:                        200.0000
BogoMIPS:                           200.00
Flags:                              fp asimd evtstrm aes pmull sha1 sha2 crc32 atomics fphp asimdhp cpuid asimdrdm jscvt fcma dcpop asimddp asimdfhm ssbs
L1d cache:                          12 MiB (192 instances)
L1i cache:                          12 MiB (192 instances)
L2 cache:                           96 MiB (192 instances)
L3 cache:                           192 MiB (8 instances)
NUMA node(s):                       8
NUMA node0 CPU(s):                  0-23
NUMA node1 CPU(s):                  24-47
NUMA node2 CPU(s):                  48-71
NUMA node3 CPU(s):                  72-95
NUMA node4 CPU(s):                  96-119
NUMA node5 CPU(s):                  120-143
NUMA node6 CPU(s):                  144-167
NUMA node7 CPU(s):                  168-191
Vulnerability Gather data sampling: Not affected
Vulnerability Itlb multihit:        Not affected
Vulnerability L1tf:                 Not affected
Vulnerability Mds:                  Not affected
Vulnerability Meltdown:             Not affected
Vulnerability Mmio stale data:      Not affected
Vulnerability Retbleed:             Not affected
Vulnerability Spec rstack overflow: Not affected
Vulnerability Spec store bypass:    Mitigation; Speculative Store Bypass disabled via prctl
Vulnerability Spectre v1:           Mitigation; __user pointer sanitization
Vulnerability Spectre v2:           Not affected
Vulnerability Srbds:                Not affected
Vulnerability Tsx async abort:      Not affected

Versions of relevant libraries:
[pip3] numpy==1.26.4
[pip3] pyzmq==27.1.0
[pip3] torch==2.9.0+cpu
[pip3] torch_npu==2.9.0.post1+gitee7ba04
[pip3] torchaudio==2.9.0
[pip3] torchvision==0.24.0
[pip3] transformers==5.4.0
[pip3] triton-ascend==3.2.0.dev20260322
[conda] Could not collect
vLLM Version: 0.18.0
vLLM Ascend Version: 0.18.0rc1

ENV Variables:
ASCEND_TOOLKIT_LATEST_HOME=/usr/local/Ascend/ascend-toolkit/latest
ATB_OPSRUNNER_KERNEL_CACHE_LOCAL_COUNT=1
ATB_STREAM_SYNC_EVERY_RUNNER_ENABLE=0
ATB_STREAM_SYNC_EVERY_KERNEL_ENABLE=0
ATB_OPSRUNNER_KERNEL_CACHE_GLOABL_COUNT=5
ATB_HOME_PATH=/usr/local/Ascend/nnal/atb/latest/atb/cxx_abi_1
ASCEND_TOOLKIT_HOME=/usr/local/Ascend/cann-8.5.1
ATB_COMPARE_TILING_EVERY_KERNEL=0
ASCEND_OPP_PATH=/usr/local/Ascend/cann-8.5.1/opp
LD_LIBRARY_PATH=/usr/local/Ascend/nnal/atb/latest/atb/cxx_abi_1/lib:/usr/local/Ascend/nnal/atb/latest/atb/cxx_abi_1/examples:/usr/local/Ascend/nnal/atb/latest/atb/cxx_abi_1/tests/atbopstest:/usr/local/Ascend/ascend-toolkit/latest/tools/aml/lib64:/usr/local/Ascend/ascend-toolkit/latest/tools/aml/lib64/plugin:/usr/local/Ascend/ascend-toolkit/latest/lib64:/usr/local/Ascend/ascend-toolkit/latest/lib64/plugin/opskernel:/usr/local/Ascend/ascend-toolkit/latest/lib64/plugin/nnengine:/usr/local/Ascend/ascend-toolkit/latest/opp/built-in/op_impl/ai_core/tbe/op_tiling:/usr/local/Ascend/cann-8.5.1/tools/aml/lib64:/usr/local/Ascend/cann-8.5.1/tools/aml/lib64/plugin:/usr/local/Ascend/cann-8.5.1/lib64:/usr/local/Ascend/cann-8.5.1/lib64/plugin/opskernel:/usr/local/Ascend/cann-8.5.1/lib64/plugin/nnengine:/usr/local/Ascend/cann-8.5.1/opp/built-in/op_impl/ai_core/tbe/op_tiling:/usr/local/Ascend/driver/lib64:/usr/local/Ascend/driver/lib64/common/:/usr/local/Ascend/driver/lib64/driver/:/usr/local/python3.11.14/lib::/usr/local/lib
ASCEND_AICPU_PATH=/usr/local/Ascend/cann-8.5.1
ATB_STREAM_SYNC_EVERY_OPERATION_ENABLE=0
ASCEND_HOME_PATH=/usr/local/Ascend/cann-8.5.1
ATB_MATMUL_SHUFFLE_K_ENABLE=1
ATB_WORKSPACE_MEM_ALLOC_ALG_TYPE=1
ATB_SHARE_MEMORY_NAME_SUFFIX=
TORCH_DEVICE_BACKEND_AUTOLOAD=1
PYTORCH_NVML_BASED_CUDA_CHECK=1
TORCHINDUCTOR_COMPILE_THREADS=1


NPU:
+------------------------------------------------------------------------------------------------+
| npu-smi 25.2.3                   Version: 25.2.3                                               |
+---------------------------+---------------+----------------------------------------------------+
| NPU   Name                | Health        | Power(W)    Temp(C)           Hugepages-Usage(page)|
| Chip                      | Bus-Id        | AICore(%)   Memory-Usage(MB)  HBM-Usage(MB)        |
+===========================+===============+====================================================+
| 0     910B4-1             | OK            | 99.0        47                0    / 0             |
| 0                         | 0000:C1:00.0  | 0           0    / 0          3409 / 65536         |
+===========================+===============+====================================================+
| 1     910B4-1             | OK            | 103.6       49                0    / 0             |
| 0                         | 0000:C2:00.0  | 0           0    / 0          3406 / 65536         |
+===========================+===============+====================================================+
| 2     910B4-1             | OK            | 93.5        45                0    / 0             |
| 0                         | 0000:81:00.0  | 0           0    / 0          3406 / 65536         |
+===========================+===============+====================================================+
| 3     910B4-1             | OK            | 99.2        46                0    / 0             |
| 0                         | 0000:82:00.0  | 0           0    / 0          3407 / 65536         |
+===========================+===============+====================================================+
| 4     910B4-1             | OK            | 101.4       55                0    / 0             |
| 0                         | 0000:01:00.0  | 0           0    / 0          3406 / 65536         |
+===========================+===============+====================================================+
| 5     910B4-1             | OK            | 100.0       49                0    / 0             |
| 0                         | 0000:02:00.0  | 0           0    / 0          3406 / 65536         |
+===========================+===============+====================================================+
| 6     910B4-1             | OK            | 97.7        46                0    / 0             |
| 0                         | 0000:41:00.0  | 0           0    / 0          3406 / 65536         |
+===========================+===============+====================================================+
| 7     910B4-1             | OK            | 92.0        49                0    / 0             |
| 0                         | 0000:42:00.0  | 0           0    / 0          3406 / 65536         |
+===========================+===============+====================================================+
+---------------------------+---------------+----------------------------------------------------+
| NPU     Chip              | Process id    | Process name             | Process memory(MB)      |
+===========================+===============+====================================================+
| No running processes found in NPU 0                                                            |
+===========================+===============+====================================================+
| No running processes found in NPU 1                                                            |
+===========================+===============+====================================================+
| No running processes found in NPU 2                                                            |
+===========================+===============+====================================================+
| No running processes found in NPU 3                                                            |
+===========================+===============+====================================================+
| No running processes found in NPU 4                                                            |
+===========================+===============+====================================================+
| No running processes found in NPU 5                                                            |
+===========================+===============+====================================================+
| No running processes found in NPU 6                                                            |
+===========================+===============+====================================================+
| No running processes found in NPU 7                                                            |
+===========================+===============+====================================================+

CANN:
package_name=Ascend-cann-toolkit
version=8.5.1
innerversion=V100R001C25SPC002B220
compatible_version=[V100R001C15],[V100R001C18],[V100R001C19],[V100R001C20],[V100R001C21],[V100R001C23]
arch=aarch64
os=linux
path=/usr/local/Ascend/cann-8.5.1
```

</details>

### 🐛 Describe the bug

A2双机背靠背组网，node0部署W4A8脚本：
```text
pkill -9 python
pkill -9 VLLM

nic_name="enp67s0f0np0"
local_ip="192.168.200.2"
node0_ip="192.168.200.2"

export HCCL_OP_EXPANSION_MODE="AIV"

export HCCL_IF_IP=$local_ip
export GLOO_SOCKET_IFNAME=$nic_name
export TP_SOCKET_IFNAME=$nic_name
export HCCL_SOCKET_IFNAME=$nic_name

export OMP_PROC_BIND=false
export OMP_NUM_THREADS=10
export HCCL_BUFFSIZE=256
export PYTORCH_NPU_ALLOC_CONF=expandable_segments:True
export VLLM_LOGGING_LEVEL=INFO
export VLLM_ASCEND_BALANCE_SCHEDULING=1

export ASCEND_GLOBAL_LOG_LEVEL=2

vllm serve /data/models/GLM-5.1-w4a8 \
--host 0.0.0.0 \
--port 8321 \
--data-parallel-size 2 \
--data-parallel-size-local 1 \
--data-parallel-address $node0_ip \
--data-parallel-rpc-port 12890 \
--tensor-parallel-size 8 \
--quantization ascend \
--seed 1024 \
--served-model-name glm-5.1 \
--enable-expert-parallel \
--enable-auto-tool-choice \
--tool-call-parser glm47 \
--reasoning-parser glm45 \
--max-num-seqs 32 \
--max-model-len 131072 \
--max-num-batched-tokens 4096 \
--trust-remote-code \
--gpu-memory-utilization 0.95 \
--enable-chunked-prefill \
--enable-prefix-caching \
--async-scheduling \
--compilation-config '{"cudagraph_capture_sizes": [1,4,8,12,16,20,24,28,32,36,40,48,56,64,80,96], "cudagraph_mode": "FULL_DECODE_ONLY"}' \
--additional-config '{"multistream_overlap_shared_expert":true, "fuse_qknorm_rope": false, "fuse_muls_add": true, "enable_npugraph_ex": true}' \
--speculative-config '{"num_speculative_tokens": 3, "method": "deepseek_mtp"}' \
--enable-log-outputs \
--enable-log-requests \
--log-error-stack \
&

```
node1部署W4A8脚本：
```text
pkill -9 python
pkill -9 VLLM

nic_name="enp67s0f0np0"
local_ip="192.168.201.2"
node0_ip="192.168.200.2"

export HCCL_OP_EXPANSION_MODE="AIV"

export HCCL_IF_IP=$local_ip
export GLOO_SOCKET_IFNAME=$nic_name
export TP_SOCKET_IFNAME=$nic_name
export HCCL_SOCKET_IFNAME=$nic_name

export OMP_PROC_BIND=false
export OMP_NUM_THREADS=10
export HCCL_BUFFSIZE=256
export PYTORCH_NPU_ALLOC_CONF=expandable_segments:True
export VLLM_LOGGING_LEVEL=INFO
export VLLM_ASCEND_BALANCE_SCHEDULING=1

export ASCEND_GLOBAL_LOG_LEVEL=2

vllm serve /data/models/GLM-5.1-w4a8 \
--host 0.0.0.0 \
--port 8321 \
--headless \
--data-parallel-size 2 \
--data-parallel-size-local 1 \
--data-parallel-start-rank 1 \
--data-parallel-address $node0_ip \
--data-parallel-rpc-port 12890 \
--tensor-parallel-size 8 \
--quantization ascend \
--seed 1024 \
--served-model-name glm-5.1 \
--enable-expert-parallel \
--enable-auto-tool-choice \
--tool-call-parser glm47 \
--reasoning-parser glm45 \
--max-num-seqs 32 \
--max-model-len 131072 \
--max-num-batched-tokens 4096 \
--trust-remote-code \
--gpu-memory-utilization 0.95 \
--enable-chunked-prefill \
--enable-prefix-caching \
--async-scheduling \
--compilation-config '{"cudagraph_capture_sizes": [1,4,8,12,16,20,24,28,32,36,40,48,56,64,80,96], "cudagraph_mode": "FULL_DECODE_ONLY"}' \
--additional-config '{"multistream_overlap_shared_expert":true, "fuse_qknorm_rope": false, "fuse_muls_add": true, "enable_npugraph_ex": true}' \
--speculative-config '{"num_speculative_tokens": 3, "method": "deepseek_mtp"}' \
--enable-log-outputs \
--enable-log-requests \
--log-error-stack \
&
```

进行模型拉起关键报错信息：
```text
RuntimeError: operator():build/CMakeFiles/torch_npu.dir/compiler_depend.ts:47 NPU function error: c10_npu::acl::AclrtSynchronizeStreamWithTimeout(copy_stream), error code is 107027
[ERROR] 2026-04-24-01:59:30 (PID:57388, Device:4, RankID:-1) ERR00100 PTA call acl api failed.
EE9999: Inner Error!
EE9999[PID: 57388] 2026-04-24-01:59:30.892.760 (EE9999):  rtMemcpy execution failed, reason=the current capture mode does not support this operation[FUNC:FuncErrorReason][FILE:error_message_manage.cc][LINE:61]
        TraceBack (most recent call last):
       synchronized memcpy failed, kind = 1, runtime result = 107030[FUNC:ReportCallError][FILE:log_inner.cpp][LINE:148]
       Not allow to synchronize captured-stream, stream_id=15.[FUNC:StreamSynchronize][FILE:api_error.cc][LINE:1002]
       rtStreamSynchronizeWithTimeout execution failed, reason=stream is captured[FUNC:FuncErrorReason][FILE:error_message_manage.cc][LINE:61]
       synchronize stream with timeout failed, runtime result = 107027[FUNC:ReportCallError][FILE:log_inner.cpp][LINE:148]
```

plog首报错：
```text
[WARNING] OP(57274,):2026-04-24-01:59:30.894.569 [launch_arg_info.h:265][NNOP][AppendInputLaunchArg][57355] OpName:[aclnnQuantMatmulWeightNz_13431_QuantBatchMatmulV3] Append Launch NULL aclTensor
[WARNING] OP(57274,):2026-04-24-01:59:30.894.573 [launch_arg_info.h:271][NNOP][AppendInputLaunchArg][57355] OpName:[aclnnQuantMatmulWeightNz_13431_QuantBatchMatmulV3] Append Launch NULL aclTensor placeholder
[WARNING] OP(57274,):2026-04-24-01:59:30.894.576 [launch_arg_info.h:265][NNOP][AppendInputLaunchArg][57355] OpName:[aclnnQuantMatmulWeightNz_13431_QuantBatchMatmulV3] Append Launch NULL aclTensor
[WARNING] OP(57274,):2026-04-24-01:59:30.894.580 [launch_arg_info.h:271][NNOP][AppendInputLaunchArg][57355] OpName:[aclnnQuantMatmulWeightNz_13431_QuantBatchMatmulV3] Append Launch NULL aclTensor placeholder
[WARNING] OP(57274,):2026-04-24-01:59:30.894.599 [op_cache.cpp:1204][NNOP][CanUse][57355] OpName:[aclnnQuantMatmulWeightNz_13431_QuantBatchMatmulV3] can not hit cache, may be hash conflict, xcurrent: aclnnQuantMatmulWeightNz, cache: aclnnQuantMatmulWeightNz
[WARNING] OP(57274,):2026-04-24-01:59:30.895.720 [op_kernel.h:678][NNOP][Launch][57355] OpName:[aclnnContiguous_13432_TransposeAiCore] Core type: VectorCore.
[ERROR] RUNTIME(57274,):2026-04-24-01:59:30.895.806 [api_impl.cc:2677]57274 MemCopySync:The current capture mode:threadCaptureMode=0, exchangeCaptureMode=0, contextCaptureMode=0
[ERROR] RUNTIME(57274,):2026-04-24-01:59:30.895.815 [api_error.cc:1571]57274 MemCopySync:Memory copy sync failed, cnt=72, kind=1.
[ERROR] RUNTIME(57274,):2026-04-24-01:59:30.895.832 [api_c.cc:1097]57274 rtMemcpy:ErrCode=107030, desc=[the current capture mode does not support this operation], InnerCode=0x703001c
[ERROR] RUNTIME(57274,):2026-04-24-01:59:30.895.839 [error_message_manage.cc:61]57274 FuncErrorReason:rtMemcpy execution failed, reason=the current capture mode does not support this operation
[ERROR] ASCENDCL(57274,):2026-04-24-01:59:30.896.200 [memory.cpp:541]57274 aclrtMemcpyImpl:synchronized memcpy failed, kind = 1, runtime result = 107030
[WARNING] OP(57274,):2026-04-24-01:59:30.896.484 [op_executor.cpp:1337][NNOP][PTAGetExecCache][57274] OpName:[aclnnQuantMatmulWeightNz_13434] cache is nullptr.
[WARNING] OP(57274,):2026-04-24-01:59:30.896.500 [common_types.cpp:261][NNOP][aclTensor][57274] OpName:[aclnnQuantMatmulWeightNz_13434] the private format[FRACTAL_NZ], should not use this constructor.
[WARNING] OP(57274,):2026-04-24-01:59:30.896.553 [kernel_arg.cpp:77][NNOP][GenKeyByArgImpl][57274] OpName:[aclnnQuantMatmulWeightNz_13435_QuantBatchMatmulV3] tensor is nullptr when genKeyByArgImpl.
[WARNING] OP(57274,):2026-04-24-01:59:30.896.559 [kernel_arg.cpp:77][NNOP][GenKeyByArgImpl][57274] OpName:[aclnnQuantMatmulWeightNz_13435_QuantBatchMatmulV3] tensor is nullptr when genKeyByArgImpl.
[WARNING] OP(57274,):2026-04-24-01:59:30.896.682 [op_cache.cpp:1204][NNOP][CanUse][57355] OpName:[aclnnQuantMatmulWeightNz_13435] can not hit cache, may be hash conflict, xcurrent: aclnnQuantMatmulWeightNz, cache: aclnnQuantMatmulWeightNz
[WARNING] OP(57274,):2026-04-24-01:59:30.896.694 [kernel_arg.cpp:77][NNOP][GenKeyByArgImpl][57355] OpName:[aclnnQuantMatmulWeightNz_13435_QuantBatchMatmulV3] tensor is nullptr when genKeyByArgImpl.
[WARNING] OP(57274,):2026-04-24-01:59:30.896.698 [kernel_arg.cpp:77][NNOP][GenKeyByArgImpl][57355] OpName:[aclnnQuantMatmulWeightNz_13435_QuantBatchMatmulV3] tensor is nullptr when genKeyByArgImpl.
```
完整报错日志：

[plog-57274_20260424015804417.zip](https://github.com/user-attachments/files/27034556/plog-57274_20260424015804417.zip)

**Comment by weijinqian0** [comment]
@yydyzr plz take a look at this issue.

**Comment by 1024daniel** [comment]
A3双机双机roce组网 参考https://3ms.huawei.com/km/groups/3959141/blogs/details/22135539修改之后tp16dp2正常拉起，tp8dp4有相似错误

**Comment by lz1z** [comment]
> A3双机双机roce组网 参考[https://3ms.huawei.com/km/groups/3959141/blogs/details/22135539修改之后tp16dp2正常拉起，tp8dp4有相似错误](https://3ms.huawei.com/km/groups/3959141/blogs/details/22135539%E4%BF%AE%E6%94%B9%E4%B9%8B%E5%90%8Etp16dp2%E6%AD%A3%E5%B8%B8%E6%8B%89%E8%B5%B7%EF%BC%8Ctp8dp4%E6%9C%89%E7%9B%B8%E4%BC%BC%E9%94%99%E8%AF%AF)
这个错误已经手动规避解决了。

**Comment by 1024daniel** [comment]
> > A3双机双机roce组网 参考[https://3ms.huawei.com/km/groups/3959141/blogs/details/22135539修改之后tp16dp2正常拉起，tp8dp4有相似错误](https://3ms.huawei.com/km/groups/3959141/blogs/details/22135539%E4%BF%AE%E6%94%B9%E4%B9%8B%E5%90%8Etp16dp2%E6%AD%A3%E5%B8%B8%E6%8B%89%E8%B5%B7%EF%BC%8Ctp8dp4%E6%9C%89%E7%9B%B8%E4%BC%BC%E9%94%99%E8%AF%AF)
> > 这个错误已经手动规避解决了。

请问一下怎么手动规避解决的

**Comment by weijinqian0** [comment]
moe_comm_type=MoECommType.ALLGATHER
