### ISSUE TITLE
[Bug]: Many ops report error or unsupported for Qwen3-0.6B/Qwen3-30B-A3B/Qwen3.6-35B-A3B on 950PR

### ISSUE THREAD

**Issue by monellz** [vllm-project/vllm-ascend#9677]
### Your current environment

<details>
<summary>The output of `python collect_env.py`</summary>

```text
Collecting environment information...
PyTorch version: 2.10.0+cpu
Is debug build: False

OS: Ubuntu 24.04.4 LTS (x86_64)
GCC version: (Ubuntu 13.3.0-6ubuntu2~24.04.1) 13.3.0
Clang version: Could not collect
CMake version: version 4.3.2
Libc version: glibc-2.39

Python version: 3.12.13 (main, May 10 2026, 19:30:01) [Clang 22.1.3 ] (64-bit runtime)
Python platform: Linux-6.8.0-117-generic-x86_64-with-glibc2.39

CPU:
Architecture:                            x86_64
CPU op-mode(s):                          32-bit, 64-bit
Address sizes:                           52 bits physical, 57 bits virtual
Byte Order:                              Little Endian
CPU(s):                                  32
On-line CPU(s) list:                     0-31
Vendor ID:                               GenuineIntel
Model name:                              INTEL(R) XEON(R) GOLD 6530
CPU family:                              6
Model:                                   207
Thread(s) per core:                      1
Core(s) per socket:                      1
Socket(s):                               32
Stepping:                                2
BogoMIPS:                                4200.00
Flags:                                   fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts mmx fxsr sse sse2 ss syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology cpuid tsc_known_freq pni pclmulqdq dtes64 vmx ssse3 fma cx16 pdcm pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch cpuid_fault ssbd ibrs ibpb stibp ibrs_enhanced tpr_shadow flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid avx512f avx512dq rdseed adx smap avx512ifma clflushopt clwb avx512cd sha_ni avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves avx_vnni avx512_bf16 wbnoinvd arat vnmi avx512vbmi umip pku ospke waitpkg avx512_vbmi2 gfni vaes vpclmulqdq avx512_vnni avx512_bitalg avx512_vpopcntdq la57 rdpid bus_lock_detect cldemote movdiri movdir64b fsrm md_clear serialize tsxldtrk amx_bf16 avx512_fp16 amx_tile amx_int8 flush_l1d arch_capabilities
Virtualization:                          VT-x
Hypervisor vendor:                       KVM
Virtualization type:                     full
L1d cache:                               1 MiB (32 instances)
L1i cache:                               1 MiB (32 instances)
L2 cache:                                128 MiB (32 instances)
L3 cache:                                512 MiB (32 instances)
NUMA node(s):                            1
NUMA node0 CPU(s):                       0-31
Vulnerability Gather data sampling:      Not affected
Vulnerability Indirect target selection: Not affected
Vulnerability Itlb multihit:             Not affected
Vulnerability L1tf:                      Not affected
Vulnerability Mds:                       Not affected
Vulnerability Meltdown:                  Not affected
Vulnerability Mmio stale data:           Not affected
Vulnerability Reg file data sampling:    Not affected
Vulnerability Retbleed:                  Not affected
Vulnerability Spec rstack overflow:      Not affected
Vulnerability Spec store bypass:         Mitigation; Speculative Store Bypass disabled via prctl
Vulnerability Spectre v1:                Mitigation; usercopy/swapgs barriers and __user pointer sanitization
Vulnerability Spectre v2:                Mitigation; Enhanced / Automatic IBRS; IBPB conditional; PBRSB-eIBRS SW sequence; BHI BHI_DIS_S
Vulnerability Srbds:                     Not affected
Vulnerability Tsa:                       Not affected
Vulnerability Tsx async abort:           Mitigation; TSX disabled
Vulnerability Vmscape:                   Not affected

Versions of relevant libraries:
[pip3] numpy==2.4.6
[pip3] pyzmq==27.1.0
[pip3] torch==2.10.0+cpu
[pip3] torch_npu==2.10.0
[pip3] torchaudio==2.10.0+cpu
[pip3] torchvision==0.25.0+cpu
[pip3] transformers==5.5.3
[conda] Could not collect
vLLM Version: 0.20.2
vLLM Ascend Version: 0.19.1rc2.dev223+g5d2babe1a.d20260526 (git sha: 5d2babe1a, date: 20260526)

ENV Variables:
ATB_OPSRUNNER_KERNEL_CACHE_LOCAL_COUNT=1
ATB_STREAM_SYNC_EVERY_RUNNER_ENABLE=0
ATB_STREAM_SYNC_EVERY_KERNEL_ENABLE=0
ATB_OPSRUNNER_KERNEL_CACHE_GLOABL_COUNT=5
ATB_HOME_PATH=/home/zrx/Ascend/nnal/atb/latest/atb/cxx_abi_1
ASCEND_TOOLKIT_HOME=/home/zrx/Ascend/cann-9.0.0
ATB_COMPARE_TILING_EVERY_KERNEL=0
ASCEND_OPP_PATH=/home/zrx/Ascend/cann-9.0.0/opp
LD_LIBRARY_PATH=/home/zrx/Ascend/nnal/atb/latest/atb/cxx_abi_1/lib:/home/zrx/Ascend/nnal/atb/latest/atb/cxx_abi_1/examples:/home/zrx/Ascend/nnal/atb/latest/atb/cxx_abi_1/tests/atbopstest:/home/zrx/Ascend/cann-9.0.0/lib64:/home/zrx/Ascend/cann-9.0.0/lib64/plugin/opskernel:/home/zrx/Ascend/cann-9.0.0/lib64/plugin/nnengine:/home/zrx/Ascend/cann-9.0.0/opp/built-in/op_impl/ai_core/tbe/op_tiling/lib/linux/x86_64:/usr/local/Ascend/driver/lib64:/usr/local/Ascend/driver/lib64/common:/usr/local/Ascend/driver/lib64/driver:/home/zrx/Ascend/nnal/atb/latest/atb/cxx_abi_1/lib:/home/zrx/Ascend/nnal/atb/latest/atb/cxx_abi_1/examples:/home/zrx/Ascend/nnal/atb/latest/atb/cxx_abi_1/tests/atbopstest:/usr/local/Ascend/driver/lib64:/usr/local/Ascend/driver/lib64/common:/usr/local/Ascend/driver/lib64/driver
ASCEND_AICPU_PATH=/home/zrx/Ascend/cann-9.0.0
ATB_STREAM_SYNC_EVERY_OPERATION_ENABLE=0
ASCEND_HOME_PATH=/home/zrx/Ascend/cann-9.0.0
ATB_MATMUL_SHUFFLE_K_ENABLE=1
ATB_WORKSPACE_MEM_ALLOC_ALG_TYPE=1
ATB_SHARE_MEMORY_NAME_SUFFIX=
TORCH_DEVICE_BACKEND_AUTOLOAD=1
TORCHINDUCTOR_CACHE_DIR=/tmp/torchinductor_zrx
PYTORCH_NVML_BASED_CUDA_CHECK=1
TORCHINDUCTOR_COMPILE_THREADS=1


NPU:
+-------------------------------------------------------------------------------------------------+
| npu-smi 25.7.rc1.b081                            Version: 25.7.rc1.b081                         |
+--------+------------------+---------------+-----------------------------------------------------+
| NPU ID | Name             | Health        | Power(W)    Temp(C)           Hugepages-Usage(page) |
|        |                  | Bus-Id        | AICore(%)   Memory-Usage(MB)  HBM-Usage(MB)         |
+========+==================+===============+=====================================================+
| 0      | Ascend950PR      | OK            | 203.5       58                0     / 0             |
|        |                  | 0000:05:00.0  | 0           0    / 0          5227  / 131072        |
+========+==================+===============+=====================================================+
| 1      | Ascend950PR      | OK            | 186.5       56                0     / 0             |
|        |                  | 0000:06:00.0  | 0           0    / 0          5015  / 131072        |
+========+==================+===============+=====================================================+
+---------------------------+---------------+-----------------------------------------------------+
| NPU ID                    | Process id    | Process name             | Process memory(MB)       |
+===========================+===============+=====================================================+
| No running processes found in NPU 0                                                             |
+===========================+===============+=====================================================+
| No running processes found in NPU 1                                                             |
+===========================+===============+=====================================================+

CANN:
package_name=Ascend-cann-toolkit
version=9.0.0
innerversion=V100R001C10SPC001B226
compatible_version=[V100R001C15],[V100R001C19],[V100R001C20],[V100R001C21],[V100R001C23],[V100R001C10]
arch=x86_64
os=linux
path=/usr/local/Ascend/cann-9.0.0
```

</details>

### 🐛 Describe the bug

I want to run Qwen3-0.6B/Qwen3-35B-A3B/Qwen3.6-35B-A3B on 950PR, but there are many codegen errors or unsupported errors.

1. `rope_forward_triton` in `vllm_ascend.ops.triton.rope`
2. `_compute_slot_mapping_kernel` in `vllm.v1.worker.block_table`
3. `torch.ops._C_ascend.npu_causal_conv1d_custom`
4. `torch.ops._C_ascend.npu_gemma_rms_norm`
5. almost all triton kernels for GatedDeltaNet

# Reproduce scripts
`rope_forward_triton` and `_compute_slot_mapping_kernel`
```python
import sys

import torch
import torch_npu  # noqa: F401 — must come before NPU tensor creation


def test_rope() -> None:
    from vllm_ascend.ops.triton.rope import rope_forward_triton
    from vllm_ascend.ops.triton.triton_utils import init_device_properties_triton

    device = "npu"
    # NPU vector/aic core counts are queried lazily by rope_forward_triton
    # (via get_vectorcore_num) — initialize them once.
    torch.npu.set_device(0)
    init_device_properties_triton()
    # Captured from Qwen3-0.6B profile_run (max_num_batched_tokens=8192,
    # n_q_head=16, n_kv_head=8, head_dim=128).
    num_tokens, n_q_head, n_kv_head, head_dim = 8192, 16, 8, 128
    rope_dim = head_dim

    q = torch.randn(num_tokens, n_q_head, head_dim, dtype=torch.bfloat16, device=device)
    k = torch.randn(num_tokens, n_kv_head, head_dim, dtype=torch.bfloat16, device=device)
    cos_sin_cache = torch.randn(40960, rope_dim, dtype=torch.bfloat16, device=device)
    positions = torch.arange(num_tokens, dtype=torch.int64, device=device)

    print("[rope] launching _triton_rope ...", flush=True)
    q_out, k_out = rope_forward_triton(
        q,
        k,
        cos_sin_cache=cos_sin_cache,
        positions=positions,
        rope_dim=rope_dim,
        is_neox_style=True,
    )
    torch.npu.synchronize()
    print(f"[rope] OK  q_out.shape={tuple(q_out.shape)}  k_out.shape={tuple(k_out.shape)}")


def test_slot_mapping() -> None:
    from vllm.v1.worker.block_table import _compute_slot_mapping_kernel

    device = "npu"
    # Captured from Qwen3-0.6B decode step (num_tokens=1, max_num_tokens=8192,
    # block_table shape (256, 320), BLOCK_SIZE=1024).
    num_tokens = 1
    max_num_tokens = 8192
    block_size = 128
    max_num_reqs = 256
    max_num_blocks_per_req = 320
    grid = 2  # num_reqs + 1

    query_start_loc = torch.tensor([0, 1], dtype=torch.int32, device=device)
    positions = torch.zeros(num_tokens, dtype=torch.int64, device=device)
    block_table = torch.zeros(
        (max_num_reqs, max_num_blocks_per_req), dtype=torch.int32, device=device
    )
    slot_mapping = torch.full(
        (max_num_tokens + 512,), -1, dtype=torch.int32, device=device
    )  # 8704 from dump

    print("[slot_mapping] launching _compute_slot_mapping_kernel ...", flush=True)
    _compute_slot_mapping_kernel[(grid,)](
        num_tokens,
        max_num_tokens,
        query_start_loc,
        positions,
        block_table,
        block_table.stride(0),
        block_size,
        slot_mapping,
        TOTAL_CP_WORLD_SIZE=1,
        TOTAL_CP_RANK=0,
        CP_KV_CACHE_INTERLEAVE_SIZE=1,
        PAD_ID=-1,
        BLOCK_SIZE=1024,
    )
    torch.npu.synchronize()
    print(f"[slot_mapping] OK  first 8 slots={slot_mapping[:8].tolist()}")


def main() -> int:
    which = sys.argv[1] if len(sys.argv) > 1 else "both"
    tests = {"rope": test_rope, "slot_mapping": test_slot_mapping}
    targets = tests.values() if which == "both" else [tests[which]]
    rc = 0
    for fn in targets:
        try:
            fn()
        except Exception as e:
            print(f"[{fn.__name__}] FAILED: {type(e).__name__}: {e}", file=sys.stderr)
            rc = 1
    return rc


if __name__ == "__main__":
    sys.exit(main())
```
Expected Error:
```bash
(950pr-system-exp) zrx@fuse2v:~/dev/950pr-system-exp/scripts$ python test_kernels.py
INFO 05-28 12:32:26 [__init__.py:44] Available plugins for group vllm.platform_plugins:
INFO 05-28 12:32:26 [__init__.py:46] - ascend -> vllm_ascend:register
INFO 05-28 12:32:26 [__init__.py:49] All plugins in this group will be loaded. Set `VLLM_PLUGINS` to control which plugins to load.
INFO 05-28 12:32:26 [__init__.py:238] Platform plugin ascend is activated
/home/zrx/dev/950pr-system-exp/.venv/lib/python3.12/site-packages/transformers/loss/loss_for_object_detection.py:27: UserWarning: A NumPy version >=1.22.4 and <2.3.0 is required for this version of SciPy (detected version 2.4.6)
  from scipy.optimize import linear_sum_assignment
INFO 05-28 12:32:29 [nixl_utils.py:20] Setting UCX_RCACHE_MAX_UNRELEASED to '1024' to avoid a rare memory leak in UCX when using NIXL.
WARNING 05-28 12:32:29 [nixl_utils.py:34] NIXL is not available
WARNING 05-28 12:32:29 [nixl_utils.py:44] NIXL agent config is not available
[rope] launching _triton_rope ...
[test_rope] FAILED: MLIRCompilationError:
///------------------[ERROR][Triton][BEG]------------------
[ConvertLinalgRToBinary] encounters error:
bisheng: error: clang frontend command failed with exit code 139 (use -v to see invocation)
2026-04-03T18:03:06+08:00 clang version 15.0.5 (clang-5c68a1cb1231 flang-5c68a1cb1231)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /home/zrx/Ascend/cann-9.0.0/tools/ccec_compiler/bin
[ERROR] Executing: /home/zrx/Ascend/cann-9.0.0/tools/ccec_compiler/bin/bisheng --cce-aicore-arch=dav-c310-vec --cce-aicore-only -O2 -cce-bitcode-is-aicore -Wno-override-module -cce-link-aicore-ll-module /tmp/bishengir-bc-manager-c79325/autogen_meta_op_aiv.bc -o /tmp/tmpufws58x_/kernel.o /tmp/tmpufws58x_/kernel.ll -mllvm --cce-vf-auto-sync=global -mllvm -cce-aicore-dcci-insert-for-scalar=false --cce-aicore-input-parameter-size=1536 -mllvm -cce-vf-aa-between-iters=true -mllvm -cce-vf-enable-loop-fusion=false -cce-link-aicore-ll-module /home/zrx/dev/950pr-system-exp/.venv/lib/python3.12/site-packages/triton/backends/ascend/lib/libdevice.10.bc
loc("/tmp/bishengir-compile-f5cb0d/module.hivm.opt.mlir":4:1): error: Failed to compile BiShengLIR for device
[ERROR] Failed to run HIVMC pipeline
[ERROR] Executing: /home/zrx/dev/950pr-system-exp/.venv/lib/python3.12/site-packages/triton/backends/ascend/bishengir-a5/bin/hivmc-a5 /tmp/bishengir-compile-f5cb0d/module.hivm.opt.mlir --target=Ascend950PR_9579 --enable-auto-multi-buffer=False --enable-auto-bind-sub-block=True --disable-ffts --enable-hfusion-compile=true --enable-triton-kernel-compile=true --append-bisheng-options=-cce-link-aicore-ll-module /home/zrx/dev/950pr-system-exp/.venv/lib/python3.12/site-packages/triton/backends/ascend/lib/libdevice.10.bc --enable-vf-merge-level=1 -o /tmp/tmpufws58x_/kernel --only-run-hivm-pipeline=false
[ERROR] Failed to run BiShengIR pipeline


[INFO]: The compiled kernel cache is in /home/zrx/.triton/cache/ori00eHQob525o82sVB4PLe9vj4IcKNS1RiN0kXJv7E

///------------------[ERROR][Triton][END]------------------

[slot_mapping] launching _compute_slot_mapping_kernel ...
[test_slot_mapping] FAILED: MLIRCompilationError:
///------------------[ERROR][Triton][BEG]------------------
[ConvertLinalgRToBinary] encounters error:
fatal error: error in backend: Do not know how to expand the result of this operator!
bisheng: error: clang frontend command failed with exit code 70 (use -v to see invocation)
2026-04-03T18:03:06+08:00 clang version 15.0.5 (clang-5c68a1cb1231 flang-5c68a1cb1231)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /home/zrx/Ascend/cann-9.0.0/tools/ccec_compiler/bin
[ERROR] Executing: /home/zrx/Ascend/cann-9.0.0/tools/ccec_compiler/bin/bisheng --cce-aicore-arch=dav-c310-vec --cce-aicore-only -O2 -cce-bitcode-is-aicore -Wno-override-module -cce-link-aicore-ll-module /tmp/bishengir-bc-manager-4a8e8b/autogen_meta_op_aiv.bc -o /tmp/tmpb0as8o2m/kernel.o /tmp/tmpb0as8o2m/kernel.ll -mllvm --cce-vf-auto-sync=global -mllvm -cce-aicore-dcci-insert-for-scalar=false --cce-aicore-input-parameter-size=1536 -mllvm -cce-vf-aa-between-iters=true -mllvm -cce-vf-enable-loop-fusion=false -cce-link-aicore-ll-module /home/zrx/dev/950pr-system-exp/.venv/lib/python3.12/site-packages/triton/backends/ascend/lib/libdevice.10.bc
loc("/tmp/bishengir-compile-c88327/module.hivm.opt.mlir":4:1): error: Failed to compile BiShengLIR for device
[ERROR] Failed to run HIVMC pipeline
[ERROR] Executing: /home/zrx/dev/950pr-system-exp/.venv/lib/python3.12/site-packages/triton/backends/ascend/bishengir-a5/bin/hivmc-a5 /tmp/bishengir-compile-c88327/module.hivm.opt.mlir --target=Ascend950PR_9579 --enable-auto-multi-buffer=False --enable-auto-bind-sub-block=True --disable-ffts --enable-hfusion-compile=true --enable-triton-kernel-compile=true --append-bisheng-options=-cce-link-aicore-ll-module /home/zrx/dev/950pr-system-exp/.venv/lib/python3.12/site-packages/triton/backends/ascend/lib/libdevice.10.bc --enable-vf-merge-level=1 -o /tmp/tmpb0as8o2m/kernel --only-run-hivm-pipeline=false
[ERROR] Failed to run BiShengIR pipeline


[INFO]: The compiled kernel cache is in /home/zrx/.triton/cache/a4UcmJH88_5avUiGfrMUI92Ly5bxgU3xDiOuZBOqaGE

///------------------[ERROR][Triton][END]------------------
```

`causal_conv1d`
```python
import sys
import traceback

import torch
import torch_npu  # noqa: F401

import vllm_ascend  # noqa: F401
from vllm_ascend import vllm_ascend_C  # noqa: F401 — registers torch.ops._C_ascend


def make_inputs(num_tokens=4, channels=32, kernel_dim=4, num_seqs=1,
                dtype=torch.bfloat16, device="npu:0"):
    torch.npu.set_device(device)
    x = torch.randn(num_tokens, channels, dtype=dtype, device=device)
    weight = torch.randn(channels, kernel_dim, dtype=dtype, device=device)
    output = torch.empty_like(x)
    # mamba conv state lives in (num_seqs, channels, kernel_dim - 1) typically
    conv_state = torch.zeros(num_seqs, channels, kernel_dim - 1, dtype=dtype, device=device)
    return output, x, weight, conv_state


def main() -> int:
    output, x, weight, conv_state = make_inputs()
    print("=== torch.ops._C_ascend.npu_causal_conv1d_custom ===", flush=True)
    try:
        torch.ops._C_ascend.npu_causal_conv1d_custom(
            output,
            x,
            weight,
            conv_state,
            None,                  # bias_opt
            (0, x.shape[0]),       # query_start_loc_opt
            (0,),                  # cache_indices_opt
            (0,),                  # initial_state_mode_opt (0 = no initial)
            (),                    # num_accepted_tokens_opt (non-spec path)
            1,                     # activation_mode (1 = silu)
            -1,                    # pad_slot_id
            0,                     # run_mode
        )
        torch.npu.synchronize()
        print(f"  OK  output.shape={tuple(output.shape)}")
    except Exception as e:
        print(f"  FAILED: {type(e).__name__}: {e}", flush=True)
        traceback.print_exc()
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
```
Expected Error
```bash
(950pr-system-exp) zrx@fuse2v:~/dev/950pr-system-exp/scripts$ python test_causal_conv1d.py
/home/zrx/dev/950pr-system-exp/scripts/test_causal_conv1d.py:32: UserWarning: Cannot create tensor with interal format while allow_internel_format=False, tensor will be created with base format. (Triggered internally at ../torch_npu/csrc/aten/common/TensorFactories.cpp:340.)
  output = torch.empty_like(x)
=== torch.ops._C_ascend.npu_causal_conv1d_custom ===
  FAILED: RuntimeError: aclnnCausalConv1d or aclnnCausalConv1dGetWorkspaceSize not in libopapi.so, or libopapi.sonot found.
Traceback (most recent call last):
  File "/home/zrx/dev/950pr-system-exp/scripts/test_causal_conv1d.py", line 42, in main
    torch.ops._C_ascend.npu_causal_conv1d_custom(
  File "/home/zrx/dev/950pr-system-exp/.venv/lib/python3.12/site-packages/torch/_ops.py", line 1209, in __call__
    return self._op(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: aclnnCausalConv1d or aclnnCausalConv1dGetWorkspaceSize not in libopapi.so, or libopapi.sonot found.
(950pr-system-exp) zrx@fuse2v:~/dev/950pr-system-exp/scripts$
```

`gemma_rms_norm`
```python
import sys
import traceback

import torch
import torch_npu  # noqa: F401

# vllm-ascend's wrapper lives in torch.ops._C_ascend. `import vllm_ascend`
# alone does NOT load the C extension; the .so is `vllm_ascend.vllm_ascend_C`
# and registers TORCH_LIBRARY(_C_ascend, ...) on import.
import vllm_ascend  # noqa: F401
from vllm_ascend import vllm_ascend_C  # noqa: F401


def make_inputs(num_tokens=8, hidden=2048, dtype=torch.bfloat16, device="npu:0"):
    torch.npu.set_device(device)
    x = torch.randn(num_tokens, hidden, dtype=dtype, device=device)
    gamma = torch.randn(hidden, dtype=dtype, device=device)
    return x, gamma


def try_torch_npu():
    print("=== (a) torch_npu.npu_gemma_rms_norm ===", flush=True)
    x, gamma = make_inputs()
    try:
        y, rstd = torch_npu.npu_gemma_rms_norm(x, gamma, 1e-6)
        torch.npu.synchronize()
        print(f"  OK  y.shape={tuple(y.shape)}  rstd.shape={tuple(rstd.shape)}")
    except Exception as e:
        print(f"  FAILED: {type(e).__name__}: {e}", flush=True)
        traceback.print_exc()


def try_vllm_ascend_wrapper():
    print("=== (b) torch.ops._C_ascend.npu_gemma_rms_norm ===", flush=True)
    x, gamma = make_inputs()
    try:
        y, rstd = torch.ops._C_ascend.npu_gemma_rms_norm(x, gamma, 1e-6)
        torch.npu.synchronize()
        print(f"  OK  y.shape={tuple(y.shape)}  rstd.shape={tuple(rstd.shape)}")
    except Exception as e:
        print(f"  FAILED: {type(e).__name__}: {e}", flush=True)
        traceback.print_exc()


def main() -> int:
    try_torch_npu()
    try_vllm_ascend_wrapper()
    return 0


if __name__ == "__main__":
    sys.exit(main())
```
Expected Error
```bash
(950pr-system-exp) zrx@fuse2v:~/dev/950pr-system-exp/scripts$ python test_gemma_rms_norm.py
=== (a) torch_npu.npu_gemma_rms_norm ===
[W528 12:36:26.649365929 TensorFactories.cpp:340] Warning: Cannot create tensor with interal format while allow_internel_format=False, tensor will be created with base format. (function operator())
  FAILED: RuntimeError: npu_gemma_rms_norm:../third_party/op-plugin/op_plugin/ops/opapi/GemmaRmsNormKernelOpApi.cpp:31 NPU function error: device error type 0, error code is 161001
[ERROR] 2026-05-28-12:36:26 (PID:6897, Device:0, RankID:-1) ERR00100 PTA call acl api failed.
[PID: 6897] 2026-05-28-12:36:26.976.290 AclNN_Parameter_Error(EZ1001): Get regInfo failed, The binary_info_config.json of socVersion [ascend950] does not support opType [GemmaRmsNorm].
        TraceBack (most recent call last):
        Check nnopExecutor != nullptr failed

Traceback (most recent call last):
  File "/home/zrx/dev/950pr-system-exp/scripts/test_gemma_rms_norm.py", line 49, in try_torch_npu
    y, rstd = torch_npu.npu_gemma_rms_norm(x, gamma, 1e-6)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zrx/dev/950pr-system-exp/.venv/lib/python3.12/site-packages/torch/_ops.py", line 1209, in __call__
    return self._op(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: npu_gemma_rms_norm:../third_party/op-plugin/op_plugin/ops/opapi/GemmaRmsNormKernelOpApi.cpp:31 NPU function error: device error type 0, error code is 161001
[ERROR] 2026-05-28-12:36:26 (PID:6897, Device:0, RankID:-1) ERR00100 PTA call acl api failed.
[PID: 6897] 2026-05-28-12:36:26.976.290 AclNN_Parameter_Error(EZ1001): Get regInfo failed, The binary_info_config.json of socVersion [ascend950] does not support opType [GemmaRmsNorm].
        TraceBack (most recent call last):
        Check nnopExecutor != nullptr failed

=== (b) torch.ops._C_ascend.npu_gemma_rms_norm ===
  FAILED: RuntimeError: call aclnnGemmaRmsNorm failed, detail:[PID: 6897] 2026-05-28-12:36:26.979.050 AclNN_Parameter_Error(EZ1001): Get regInfo failed, The binary_info_config.json of socVersion [ascend950] does not support opType [GemmaRmsNorm].
        TraceBack (most recent call last):
        Check nnopExecutor != nullptr failed

Traceback (most recent call last):
  File "/home/zrx/dev/950pr-system-exp/scripts/test_gemma_rms_norm.py", line 61, in try_vllm_ascend_wrapper
    y, rstd = torch.ops._C_ascend.npu_gemma_rms_norm(x, gamma, 1e-6)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/zrx/dev/950pr-system-exp/.venv/lib/python3.12/site-packages/torch/_ops.py", line 1209, in __call__
    return self._op(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: call aclnnGemmaRmsNorm failed, detail:[PID: 6897] 2026-05-28-12:36:26.979.050 AclNN_Parameter_Error(EZ1001): Get regInfo failed, The binary_info_config.json of socVersion [ascend950] does not support opType [GemmaRmsNorm].
        TraceBack (most recent call last):
        Check nnopExecutor != nullptr failed

(950pr-system-exp) zrx@fuse2v:~/dev/950pr-system-exp/scripts$
```

**Comment by kunpengW-code** [comment]
@LoganJane Please see this issue.

**Comment by earthmanylf** [comment]
@monellz Can you please provide the version of vllm, vllm-ascend and triton-ascend?
@U1stRsouland Please take a look. I think we have a revent version tested for Qwen3-0.6B and Qwen3-30B-A3B in 950PR, you can provide the commit id of vllm, vllm-ascend and other environment information.

**Comment by monellz** [comment]
@earthmanylf 

vllm v0.20.2
vllm-ascend 5d2babe1ab41e8d7ebb756d44d9d74bb7f7d1588
triton-ascend 3.2.1

full pip list:
```bash
Package                                  Version                               Editable project location
---------------------------------------- ------------------------------------- ----------------------------------------------
aiofiles                                 25.1.0
aiohappyeyeballs                         2.6.2
aiohttp                                  3.13.5
aiosignal                                1.4.0
annotated-doc                            0.0.4
annotated-types                          0.7.0
anthropic                                0.104.1
anyio                                    4.13.0
apache-tvm-ffi                           0.1.11
arctic-inference                         0.1.1
astor                                    0.8.1
attrs                                    24.2.0
blake3                                   1.0.8
blinker                                  1.9.0
cachetools                               7.1.4
cbor2                                    6.1.1
certifi                                  2026.5.20
cffi                                     2.0.0
charset-normalizer                       3.4.7
click                                    8.4.1
cloudpickle                              3.1.2
cmake                                    4.3.2
compressed-tensors                       0.15.0.1
cryptography                             48.0.0
decorator                                5.1.1
depyf                                    0.20.0
detect-installer                         0.1.0
dill                                     0.4.1
diskcache                                5.6.3
distro                                   1.9.0
dnspython                                2.8.0
docstring-parser                         0.18.0
einops                                   0.8.2
email-validator                          2.3.0
execnet                                  2.1.2
fastapi                                  0.123.10
fastapi-cli                              0.0.24
fastapi-cloud-cli                        0.18.0
fastar                                   0.11.0
filelock                                 3.29.0
flask                                    3.1.3
frozenlist                               1.8.0
fsspec                                   2026.4.0
gguf                                     0.19.0
googleapis-common-protos                 1.75.0
grpcio                                   1.80.0
h11                                      0.16.0
h2                                       4.3.0
hf-xet                                   1.5.0
hpack                                    4.1.0
httpcore                                 1.0.9
httptools                                0.8.0
httpx                                    0.28.1
httpx-sse                                0.4.3
huggingface-hub                          1.16.1
hypercorn                                0.18.0
hyperframe                               6.1.0
idna                                     3.16
ijson                                    3.5.0
iniconfig                                2.3.0
interegular                              0.3.3
itsdangerous                             2.2.0
jinja2                                   3.1.6
jiter                                    0.15.0
jmespath                                 1.1.0
jsonschema                               4.26.0
jsonschema-specifications                2025.9.1
lark                                     1.2.2
llguidance                               1.3.0
llvmlite                                 0.47.0
lm-format-enforcer                       0.11.3
loguru                                   0.7.3
markdown-it-py                           4.2.0
markupsafe                               3.0.3
mcp                                      1.27.1
mdurl                                    0.1.2
memcache-hybrid                          1.1.0
memfabric-hybrid                         1.1.0
mistral-common                           1.11.2
model-hosting-container-standards        0.1.15
mpmath                                   1.3.0
msgpack                                  1.1.2
msgspec                                  0.21.1
multidict                                6.7.1
networkx                                 3.6.1
ninja                                    1.13.0
numba                                    0.65.1
numpy                                    2.4.6
openai                                   2.38.0
openai-harmony                           0.0.8
opencv-python-headless                   4.13.0.92
opentelemetry-api                        1.42.1
opentelemetry-exporter-otlp              1.42.1
opentelemetry-exporter-otlp-proto-common 1.42.1
opentelemetry-exporter-otlp-proto-grpc   1.42.1
opentelemetry-exporter-otlp-proto-http   1.42.1
opentelemetry-proto                      1.42.1
opentelemetry-sdk                        1.42.1
opentelemetry-semantic-conventions       0.63b1
opentelemetry-semantic-conventions-ai    0.5.1
outlines-core                            0.2.14
packaging                                26.2
pandas                                   3.0.3
pandas-stubs                             3.0.0.260204
partial-json-parser                      0.2.1.1.post7
pillow                                   12.2.0
pip                                      26.1.1
pluggy                                   1.6.0
priority                                 2.0.0
prometheus-client                        0.25.0
prometheus-fastapi-instrumentator        7.1.0
propcache                                0.5.2
protobuf                                 6.33.6
psutil                                   6.0.0
py-cpuinfo                               9.0.0
pybase64                                 1.4.3
pybind11                                 3.0.4
pycountry                                26.2.16
pycparser                                3.0
pydantic                                 2.13.4
pydantic-core                            2.46.4
pydantic-extra-types                     2.11.1
pydantic-settings                        2.14.1
pygments                                 2.20.0
pyjwt                                    2.13.0
pytest                                   8.3.2
pytest-xdist                             3.6.1
python-dateutil                          2.9.0.post0
python-dotenv                            1.2.2
python-json-logger                       4.1.0
python-multipart                         0.0.29
pyyaml                                   6.0.3
pyzmq                                    27.1.0
quart                                    0.20.0
referencing                              0.37.0
regex                                    2026.5.9
requests                                 2.34.2
rich                                     15.0.0
rich-toolkit                             0.19.10
rignore                                  0.7.6
rpds-py                                  0.30.0
safetensors                              0.7.0
scipy                                    1.13.1
sentencepiece                            0.2.1
sentry-sdk                               2.60.0
setproctitle                             1.3.7
setuptools                               80.10.2
setuptools-scm                           10.0.5
shellingham                              1.5.4
six                                      1.17.0
sniffio                                  1.3.1
sse-starlette                            3.4.4
starlette                                0.50.0
supervisor                               4.3.0
sympy                                    1.14.0
tiktoken                                 0.13.0
tokenizers                               0.22.2
torch                                    2.10.0+cpu
torch-npu                                2.10.0
torchaudio                               2.10.0+cpu
torchvision                              0.25.0+cpu
tqdm                                     4.67.3
transformers                             5.5.3
triton                                   3.2.0
triton-ascend                            3.2.1
typer                                    0.25.1
typing-extensions                        4.15.0
typing-inspection                        0.4.2
urllib3                                  2.7.0
uvicorn                                  0.48.0
uvloop                                   0.22.1
vcs-versioning                           1.1.1
vllm                                     0.20.2+empty                          /home/zrx/dev/950pr-system-exp/3rd/vllm
vllm-ascend                              0.19.1rc2.dev223+g5d2babe1a.d20260526 /home/zrx/dev/950pr-system-exp/3rd/vllm-ascend
watchfiles                               1.2.0
websockets                               16.0
werkzeug                                 3.1.8
wheel                                    0.47.0
wsproto                                  1.3.2
xgrammar                                 0.2.1
yarl                                     1.24.2
```

**Comment by LoganJane** [comment]
@monellz This issue has been resolved in the latest version. Please use the latest release or rc version (https://github.com/vllm-project/vllm-ascend/releases). If the issue persists, feel free to submit a new issue.
